### ISSUE TITLE
Не работает с https?

### ISSUE THREAD

**Issue by erufagg** [ValdikSS/GoodbyeDPI#1]
Все так же вылетает ошибка сертификата при заходе с фокса на е621. Остальные буру открываются нормально. Флаги все перепробывал, эффекта ноль. Что я делаю не так?

**Comment by ValdikSS** [comment]
Ваш провайдер может перенаправлять весь HTTPS-трафик к заблокированным сайтам на свой сервер со страницей-заглушкой. Выполните тест [blockcheck](https://github.com/ValdikSS/blockcheck) и пришлите сюда полный вывод.

**Comment by erufagg** [comment]
Присылаю полный вывод: https://pastebin.com/agQfmv5d

**Comment by ValdikSS** [comment]
По всей видимости, провайдер действительно перенаправляет HTTPS-трафик на свой сервер, не через DPI. Скоро выйдет программа и для такого типа блокировок, но уже другая, ждите.

**Comment by erufagg** [comment]
Ясно. У меня тут еще такой вопрос, не совсем относящийся к теме: почему ендлес сосач не работает?

**Comment by ValdikSS** [comment]
Под новый год проверял, работал. Может, опять что-то на стороне сосача поменяли.
