### ISSUE TITLE
"Error opening filter: the system cannot find the file specified"

### ISSUE THREAD

**Issue by stealzy** [ValdikSS/GoodbyeDPI#101]
Windows 7 SP1 x64, GoodbyeDPI 0.1.5 rc3.
There is no error on stable 0.1.4 version.

btw: ability to run several instance goodbyedpi.exe looks strange.

**Comment by stealzy** [comment]
1) No.
2) I'm pretty sure, I download and unpack .zip from release github page and run .bat file.

**Comment by ValdikSS** [comment]
No answer, closing.

**Comment by morkich** [comment]
Аналогичная ситуация =(
Имени файла нет 

лог прилагаю:
GoodbyeDPI v0.2.2: Passive DPI blocker and Active DPI circumvention utility
https://github.com/ValdikSS/GoodbyeDPI

Loaded 137451 hosts from file ..\russia-blacklist.txt
Loaded 4 hosts from file ..\russia-youtube.txt
Block passive: 0
Block QUIC/HTTP3: 1
Fragment HTTP: 2
Fragment persistent HTTP: 2
Fragment HTTPS: 2
Fragment by SNI: 0
Native fragmentation (splitting): 1
Fragments sending in reverse: 1
hoSt: 0
Host no space: 0
Additional space: 0
Mix Host: 0
HTTP AllPorts: 0
HTTP Persistent Nowait: 1
DNS redirect: 0
DNSv6 redirect: 0
Allow missing SNI: 0
Fake requests, TTL: fixed (fixed: 0, auto: 0-0-0, min distance: 0)
Fake requests, wrong checksum: 1
Fake requests, wrong SEQ/ACK: 1
Max payload size: 1200

Opening filter
Error opening filter: The system cannot find the path specified.

**Comment by arleenlasleur** [comment]
win 10.0.19045.4651 x64, была та же проблема.
перезагрузка помогла, но появилось шесть лишних NIC
![image](https://github.com/user-attachments/assets/9d3290dd-8f74-4abf-a705-2393f2991471)

туннели i2pd, yggdrasil и прочие сети работают в штатном режиме

**Comment by george123-321** [comment]
Error opening filter: The system cannot find the path specified.
я уже заеб"""лся 
свяжитесь со мной пж если можете помочь disvord:ggo4a
вот полный лог:

GoodbyeDPI v0.2.2: Passive DPI blocker and Active DPI circumvention utility
https://github.com/ValdikSS/GoodbyeDPI

Loaded 137451 hosts from file ..\russia-blacklist.txt
Loaded 4 hosts from file ..\russia-youtube.txt
Block passive: 0
Block QUIC/HTTP3: 1
Fragment HTTP: 2
Fragment persistent HTTP: 2
Fragment HTTPS: 2
Fragment by SNI: 0
Native fragmentation (splitting): 1
Fragments sending in reverse: 1
hoSt: 0
Host no space: 0
Additional space: 0
Mix Host: 0
HTTP AllPorts: 0
HTTP Persistent Nowait: 1
DNS redirect: 0
DNSv6 redirect: 0
Allow missing SNI: 0
Fake requests, TTL: fixed (fixed: 0, auto: 0-0-0, min distance: 0)
Fake requests, wrong checksum: 1
Fake requests, wrong SEQ/ACK: 1
Max payload size: 1200

Opening filter
Error opening filter: The system cannot find the path specified.

**Comment by ElectroidDes** [comment]
I just had the same thing!
After updating and rebooting Windows, the file "WinDivert64.sys" disappeared from the "x86_64" folder.
After unzipping this file again, everything worked.
SO CHECK IF THE "WinDivert64.sys" FILE IS IN THE Folder!

**Comment by dfasaAZ** [comment]
Ошибка возникла, когда ставил новую версию. Перезагрузка, снос папки со старой версией, а затем запуск service_remove.cmd в папке с новой - решило проблему
