### ISSUE TITLE
Соединение сброшено

### ISSUE THREAD

**Issue by Krubinka** [ValdikSS/GoodbyeDPI#104]
Имеджборды все как один выдают эту ошибку в хардкор/сервис режиме, при использовании первого и второго выдаёт ERR_CERT_AUTHORITY_INVALID в хроме, в других браузерах попросту не грузит. 
В это же время рутрекер, nnm и прочие вроде как работают.

**Comment by ValdikSS** [comment]
Это не ошибка GoodbyeDPI.

**Comment by Krubinka** [comment]
Даже с учётом того что через VPN всё работает?
