### ISSUE TITLE
Windows 10 x64 1809 - does not work at all

### ISSUE THREAD

**Issue by gjf** [ValdikSS/GoodbyeDPI#105]
I've tried to start 3_all_dnsredir_hardcore.cmd - and nothing happened.
As far as I understand at least dns server should be changed, but it looks like it remains the same. So all blocked websites cannot be even resolved.

**Comment by Atavic** [comment]
While [this] isn't implemented yet... have you run the file as *Admin*?

**Comment by ValdikSS** [comment]
DNS queries are redirected to another DNS server transparently, you won't see any changes in interface DNS configuration.
Please describe in details what exactly doesn't work. How did you try to resolve DNS? `nslookup` does not use OS dns lookups and will be broken with GoodbyeDPI. All other software should work.

**Comment by Trojaner** [comment]
Works for me

**Comment by ValdikSS** [comment]
@gif can you provide details for this issue?

**Comment by gjf** [comment]
@ValdikSS the issue is very simple: nothing happens and the blocking is still active.
According to your information DNS should remain the same - so it is not indication that the program does not work.
Also I cannot use nslookup to check it.

Please provide instruction what I have to test - because what I see is that all blocked resources are still blocked and I cannot check what is wrong in normal way.

**Comment by ValdikSS** [comment]
@gjf Are the domains you're trying to resolve do successfully resolve without GoodbyeDPI running? Have you checked if your ISP block external DNS servers by manually trying to resolve via different public servers? Or maybe it blocks DNS queries on non-standard port (GoodbyeDPI cmd file uses 77.88.8.8:1253)?
Do you even see GoodbyeDPI console window upon running cmd file? Is the issue is only with DNS? Have you tried to start GoodbyeDPI using other cmd files which do not set dnsredir?

**Comment by gjf** [comment]
I will try as soon as I will be able to connect to VPN with provider blocking and let you know.

**Comment by Trojaner** [comment]
Try running GoodbyeDPI with no DNS redirection and then install Simple DNSCrypt (don't forget to start its service and to set it up correctly)

**Comment by SiegHeil** [comment]
Подтверждаю, на Win10 LTSC (v1809) ничего не происходит. Такое чувство, будто windivert перестал работать

**Comment by ValdikSS** [comment]
@SiegHeil, как именно «ничего не происходит»? Сделайте скриншот, или запишите видео.

**Comment by SiegHeil** [comment]
@ValdikSS как если бы всё перестало работать, т.е. всё также запускается как и ранее, но при этом никакие механизмы не отрабатывают. Точно такая же ситуация с другими продуктами, использующими windivert. Может какой лог можно сформировать или ещё что-то, т.к. по скриншоту или видео ничего понятно не будет (ошибок или сообщений никаких не выдаёт)

**Comment by ValdikSS** [comment]
@SiegHeil У вас установлен какой-либо антивирус или что-то подобное, что могло бы влиять на трафик?

**Comment by SiegHeil** [comment]
@ValdikSS ничего, кроме стандартного защитника Windows

**Comment by SiegHeil** [comment]
@ValdikSS nodevfee на базе windivert'а также перестала работать

**Comment by SiegHeil** [comment]
Может какое логгирование запустить можно, чтобы хоть немного помочь разобраться что происходит?

**Comment by ValdikSS** [comment]
Я обновил виртуалку до 1809, GoodbyeDPI продолжает работать. Даже не знаю.

**Comment by SiegHeil** [comment]
Может какой режим есть возможность добавить, который бы максимально логировал происходящее? Есть большое желание понять чего не там с моей Win10 LTSC
Вот эта "пиратская" софтина с WinDivert внутри работает без проблем, но только она
![image](https://user-images.githubusercontent.com/12028666/50641829-2fa66d00-0fa4-11e9-9a4e-4d73751717ca.png)

**Comment by ValdikSS** [comment]
Вот эта версия будет писать о каждом полученном пакете.
[goodbyedpi-x86_64-debug.zip](https://github.com/ValdikSS/GoodbyeDPI/files/2724642/goodbyedpi-x86_64-debug.zip)

**Comment by SiegHeil** [comment]
@ValdikSS Прогнал на нескольких вариантах. В каких-то случаях выкидывает заглушку от ТТК (мой провайдер), а в других просто ничего не происходит
[log.zip](https://github.com/ValdikSS/GoodbyeDPI/files/2725816/log.zip)

**Comment by ValdikSS** [comment]
@SiegHeil запишите дамп трафика со включенным GoodbyeDPI: https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by SiegHeil** [comment]
@ValdikSS Отправил на указанное в статье е-мыло, но у меня закрались подозрения, что это ТТК во всём виноват в данном случае, а другой софт не работает по иным причинам

**Comment by YoulianBoshi** [comment]
Thx

**Comment by FlynnRider3000** [comment]
Добрый день!
Также не работает на win10 LTSC. Только rutracker открывает. На других сайтах зависает. Может проблема в том, что на win10 нет необходимых dll?
win10 64 LTSC
![windivert dll dependency win10 64](https://user-images.githubusercontent.com/22592883/51620876-49691d80-1f6e-11e9-833f-fdfab33726a9.jpg)
win7 64
![windivert dll dependency win7 64](https://user-images.githubusercontent.com/22592883/51620877-4a01b400-1f6e-11e9-9da5-d9d7bc6afa6e.jpg)

**Comment by ValdikSS** [comment]
@FlynnRider3000 если rutracker открывается, значит программа работает. В чём конкретно проблема? Если программа не разблокирует сайты у вашего провайдера, это не означает, что она не работает — DPI вашего провайдера просто не совместим с GoodbyeDPI.

**Comment by FlynnRider3000** [comment]
Провайдер ростелеком
На win 7 64 все работает отлично, все заблокированные сайты открываются
На win 10 64 LTSC rutracker открывается, но многие заблокированные сайты не открываются, например telegram.org, fonbet.com, просто зависают. Рядом на win7 эти же сайты нормально открываются. В чем может быть проблема?

**Comment by r4sas** [comment]
А LTSC это какой билд?

**Comment by FlynnRider3000** [comment]
Win10 корпоративная Версия 1809 (Сборка ОС 17763.253)
Антивируса нет, защитник и брандмауэр отключил. ДНС гугла.
Установлен только офис
![default](https://user-images.githubusercontent.com/22592883/51801262-3f009980-2276-11e9-82c4-460b11e9cd67.jpg)

**Comment by ValdikSS** [comment]
Предоставьте дамп трафика с обоих компьютеров: https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by ValdikSS** [comment]
This is interesting.

@FlynnRider3000's ISP sends TCP RST for a certain IP address as the reply for SYN if SYN contains usual TCP handshake with standard Windows 7/10 TCP options, and **no real host reply is received (not even SYN/ACK)**. TCP options are as follows: 
TCP MSS, NOP, Window Scale, NOP, NOP, SACK permitted.
![screenshot_20190128_045630](https://user-images.githubusercontent.com/3054729/51810476-13eb6980-22b9-11e9-94a1-8dbb175f0239.png)

After some time, Windows 7 with GoodbyeDPI enabled (which blocks RST packets from OS) thinks that something may be wrong with host IP stack or firewall/middleware and tries to send SYN with another set of TCP options:
TCP MSS, NOP, NOP, SACK permitted.
![screenshot_20190128_050929](https://user-images.githubusercontent.com/3054729/51810764-e43d6100-22ba-11e9-921c-584420ac2a76.png)

With this set of TCP options, DPI **accepts first SYN, SYN/ACK could be received from remote host**, and connection successfully establishes. DPI understands the situation right after ClientHello and starts sending RSTs, but the connection keeps working if RSTs are blocked.

cc: @mathemonkey

**Comment by ValdikSS** [comment]
@FlynnRider3000 Что у вас за регион Ростелекома? Ваш провайдер раньше назывался по-другому, и был перекуплен Ростелекомом?

**Comment by FlynnRider3000** [comment]
Республика Бурятия. В нашей деревне это ед.провайдер) Интернет через ADSL модем.

**Comment by r4sas** [comment]
@ValdikSS На мыло отправлен аналогичный экземпляр с Win10. Подробности в мыле.

**Comment by Nebula-Mechanica** [comment]
> 
> 
> This is interesting.
> 
> @FlynnRider3000's ISP sends TCP RST for a certain IP address as the reply for SYN if SYN contains usual TCP handshake with standard Windows 7/10 TCP options, and **no real host reply is received (not even SYN/ACK)**. TCP options are as follows:
> TCP MSS, NOP, Window Scale, NOP, NOP, SACK permitted.
> ![screenshot_20190128_045630](https://user-images.githubusercontent.com/3054729/51810476-13eb6980-22b9-11e9-94a1-8dbb175f0239.png)
> 
> After some time, Windows 7 with GoodbyeDPI enabled (which blocks RST packets from OS) thinks that something may be wrong with host IP stack or firewall/middleware and tries to send SYN with another set of TCP options:
> TCP MSS, NOP, NOP, SACK permitted.
> ![screenshot_20190128_050929](https://user-images.githubusercontent.com/3054729/51810764-e43d6100-22ba-11e9-921c-584420ac2a76.png)
> 
> With this set of TCP options, DPI **accepts first SYN, SYN/ACK could be received from remote host**, and connection successfully establishes. DPI understands the situation right after ClientHello and starts sending RSTs, but the connection keeps working if RSTs are blocked.
> 
> Windows 10, on the contrary, does not switch to alternative TCP options set, that's why GoodbyeDPI "does not work".
> Why does Windows 7 change TCP Options? It seems, in the past there used to be routers and hosts which interpret TCP Window Scaling incorrectly: [1](https://wiki.squid-cache.org/KnowledgeBase/BrokenWindowSize), [2](https://bugzilla.redhat.com/show_bug.cgi?id=143316), [3](https://bugzilla.redhat.com/show_bug.cgi?id=133884).
> 
> cc: @darkk



> 
> 
> This is interesting.
> 
> @FlynnRider3000's ISP sends TCP RST for a certain IP address as the reply for SYN if SYN contains usual TCP handshake with standard Windows 7/10 TCP options, and **no real host reply is received (not even SYN/ACK)**. TCP options are as follows:
> TCP MSS, NOP, Window Scale, NOP, NOP, SACK permitted.
> ![screenshot_20190128_045630](https://user-images.githubusercontent.com/3054729/51810476-13eb6980-22b9-11e9-94a1-8dbb175f0239.png)
> 
> After some time, Windows 7 with GoodbyeDPI enabled (which blocks RST packets from OS) thinks that something may be wrong with host IP stack or firewall/middleware and tries to send SYN with another set of TCP options:
> TCP MSS, NOP, NOP, SACK permitted.
> ![screenshot_20190128_050929](https://user-images.githubusercontent.com/3054729/51810764-e43d6100-22ba-11e9-921c-584420ac2a76.png)
> 
> With this set of TCP options, DPI **accepts first SYN, SYN/ACK could be received from remote host**, and connection successfully establishes. DPI understands the situation right after ClientHello and starts sending RSTs, but the connection keeps working if RSTs are blocked.
> 
> Windows 10, on the contrary, does not switch to alternative TCP options set, that's why GoodbyeDPI "does not work".
> Why does Windows 7 change TCP Options? It seems, in the past there used to be routers and hosts which interpret TCP Window Scaling incorrectly: [1](https://wiki.squid-cache.org/KnowledgeBase/BrokenWindowSize), [2](https://bugzilla.redhat.com/show_bug.cgi?id=143316), [3](https://bugzilla.redhat.com/show_bug.cgi?id=133884).
> 
> cc: @darkk

@ValdikSS Нет случайно способа вернуть такое поведение? Ну или что-то ещё сделать. Всю голову себе сломал сегодня, почему на Win7 работает, а на десятке - только с некоторыми сайтами.

Или хотя бы как эта фича называется, если он вообще документирована.

Ростелеком, Алтайский Край.

**Comment by ValdikSS** [comment]
@Nebula-Mechanica как эта функция называется не знаю, и как вернуть — тоже. Можно, разве что, прокси на Linux-роутере поднять, на котором отключить некоторые TCP-опции.
Подробнее здесь: https://github.com/ValdikSS/GoodbyeDPI/wiki/Интереснная-особенность-DPI-Ростелекома

**Comment by ValdikSS** [comment]
Если у вас всё ещё наблюдаются проблемы с GoodbyeDPI, попробуйте экспериментальную сборку с новой версией WinDivert 2.2.0
https://github.com/ValdikSS/GoodbyeDPI/actions/runs/1653692403

Я протестировал и эту, и обычные релизы на последних сборках Windows 10 — программа работает корректно.
Если проблема до сих пор проявляется, напишите в этом тикете, и я его переоткрою.

**Comment by gjf** [comment]
Как топикстартер заявляю, что к сожалению проверить уже не могу, поскольку сто раз обновлял билд, а сейчас - вообще уже на Win 11.
Поэтому от темы отписываюсь.

**Comment by ValdikSS** [comment]
@gjf, работает ли у вас на текущей ОС релизная и тестовая версии GoodbyeDPI?
