### ISSUE TITLE
pandora.tv can't show video

### ISSUE THREAD

**Issue by DandyClubs** [ValdikSS/GoodbyeDPI#106]
Windows 10 RS5

GoodbyeDPI v0.1.5rc3

@ECHO OFF
PUSHD "%~dp0"
IF "%PROCESSOR_ARCHITECTURE%"=="x86" (
set _arch=x86
) ELSE (
set _arch=x86_64
)

echo This script should be run with administrator privileges.
echo Right click - run as administrator.
echo Press any key if you're running it as administrator.
pause
sc stop "GoodbyeDPI"
sc delete "GoodbyeDPI"
sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -1" start= "auto"
sc description "GoodbyeDPI" "Passive Deep Packet Inspection blocker and Active DPI circumvention utility"
sc start "GoodbyeDPI"

POPD
 

pandora.tv can't show video

only cna show video when stop GoodbyeDPI service

**Comment by ValdikSS** [comment]
If the video is loaded over HTTP, then their HTTP server is not fully compatible with HTTP/1.1 specification. If it's loaded over HTTPS, most probably their server or balancer can't handle fragmented packets.

**Comment by ValdikSS** [comment]
Seems that the video plays over HTTP. The best is to write site administrators with incompatibility examples.
