### ISSUE TITLE
Не работает инструмент

### ISSUE THREAD

**Issue by HarukoKisaragi** [ValdikSS/GoodbyeDPI#11]
Добрый день.

Инструмент не работает, провайдер - МТС
Какую информацию необходимо предоставить, чтобы помочь Вам устранить данную проблему

![2017-07-20 19_13_51-rutracker org](https://user-images.githubusercontent.com/10998168/28427688-b3649d38-6d7f-11e7-96ae-2682222fe3c0.png)
![2017-07-20 19_14_27-bittorrent rutracker org](https://user-images.githubusercontent.com/10998168/28427689-b36b9a7a-6d7f-11e7-84b1-a97a0b2e6176.png)

**Comment by ValdikSS** [comment]
Приложили полный вывод Blockcheck
https://github.com/ValdikSS/blockcheck/releases

**Comment by HarukoKisaragi** [comment]
Готово. Проблематично скопировать результат из blockcheck, приложил скриншоты
![1](https://user-images.githubusercontent.com/10998168/28483856-f154e0aa-6e77-11e7-9dc3-417b72c6c549.png)
![2](https://user-images.githubusercontent.com/10998168/28483855-f14e0898-6e77-11e7-9ece-303adc3146a8.png)

**Comment by ValdikSS** [comment]
Вы пробовали запускать программу с разными параметрами? С -2, например?

**Comment by ValdikSS** [comment]
Проявляется ли проблема с последней версией программы?

**Comment by HarukoKisaragi** [comment]
Нет, никаких проблем
