### ISSUE TITLE
не работает на мгтс?

### ISSUE THREAD

**Issue by dmitrydimm** [ValdikSS/GoodbyeDPI#110]
Здравствуйте.Есть ли возможность как то обходить блокировки на мгтс?Ни один сайт из списка заблокированных не открывается,просто висит,единственно не пишет Block Мгтс  но толку то.Сайты в списках есть

**Comment by r4sas** [comment]
С какими параметрами запускаете то?

**Comment by dmitrydimm** [comment]
x86 64,ну для 32 тоже пробовал.все равно не пашет.как администратор

**Comment by dmitrydimm** [comment]
> С какими параметрами запускаете то?

а у вас мгтс и работает,раз вы про параметры спрашиваете?там вроде легкие параметры,даже ребенок справится))

**Comment by dmitrydimm** [comment]
единственно почему то некоторые сайты которые не открывает все же открывает с программой,но некоторые нет

**Comment by r4sas** [comment]
Я вас не про разрядность программы спрашиваю, а про параметры запуска.
Короче говоря, вам сюда: https://github.com/ValdikSS/GoodbyeDPI#how-to-use

**Comment by dmitrydimm** [comment]
> Я вас не про разрядность программы спрашиваю, а про параметры запуска.
> Короче говоря, вам сюда: https://github.com/ValdikSS/GoodbyeDPI#how-to-use

ведь если не работает на самых простых настройках то ускорять смысла нет я читал.И что там нажимать?там миллион кнопок,если честно я много чего потыкал уже и листы проверял и запускал по отдельности разные cmd файлы -тщетно.сайты через https ни один не открывает,через просто http иногда открывает

**Comment by dmitrydimm** [comment]
> > Я вас не про разрядность программы спрашиваю, а про параметры запуска.
> > Короче говоря, вам сюда: https://github.com/ValdikSS/GoodbyeDPI#how-to-use
> 
> ведь если не работает на самых простых настройках то ускорять смысла нет я читал.И что там нажимать?там миллион кнопок,если честно я много чего потыкал уже и листы проверял и запускал по отдельности разные cmd файлы -тщетно.сайты через https ни один не открывает,через просто http иногда открывает
