### ISSUE TITLE
как зайти на https сайты?

### ISSUE THREAD

**Issue by dmitrydimm** [ValdikSS/GoodbyeDPI#111]
Почему мою тему закрыли не разобравшись https://github.com/ValdikSS/GoodbyeDPI/issues/110 ?Я пробовал по вашей инструкции,ничего не получилось.К тому же не все программисты.Вы можете объяснить поподробней?

**Comment by r4sas** [comment]
Потому что вы сами нажали закрыть.

**Comment by dmitrydimm** [comment]
> Потому что вы сами нажали закрыть.

извиняюсь.наверное я ошибся,там написал лишний пост и хотел удалить его,а оказалось что это кнопка закрытия темы

**Comment by ValdikSS** [comment]
Если программа не работает с вашим провайдером, то это не ошибка программы, а несовместимость с вашим конкретным провайдером. Программа работает только с определенными типами DPI, и эксплуатирует недостатки в системах блокировки, которые не всегда присутствуют.

**Comment by ValdikSS** [comment]
@dmitrydimm См. https://nnm-club.me/forum/viewtopic.php?p=9934957#9934957
Если сможете предоставить виртуальную машину, я посмотрю, что можно сделать с МГТС.
