### ISSUE TITLE
Не работает --blacklist

### ISSUE THREAD

**Issue by username30** [ValdikSS/GoodbyeDPI#112]
Здравствуйте!

В первую очередь, спасибо большое за замечательную программу :) Я и не думал, что мой провайдер просто повесил "ограничивающую ленточку" и банальная фрагментация пакетов всё решит без необходимости использовать прокси.

Однако есть нюанс. Даже при включённой опции --blacklist приложение продолжает перелопачивать пакеты, направляющиеся к адресам вне данного списка. Например:

![2018-12-18_11-18-22](https://user-images.githubusercontent.com/24947452/50142253-b7a92900-02ba-11e9-8288-0b6edeb28760.png)

На скриншоте в окошке программы видно, что она корректно обработала параметр --blacklist и загрузила список целевых хостов. Однако левее в окошке wireshark видно также, что запрос был побит и вместо чистого "GET / HTTP/1.1..." его побило на "GE" и "T / HTTP/1.1..."

Для запуска я использую предлагаемый Вами файл "2_all.cmd", изменив саму строку запуска на
start "" goodbyedpi.exe -f 2 -k 2 -n -e 40 --blacklist ..\blacklist.txt

Я проверил, такая же ситуация происходит и при более общем формате запуска, если использовать
start "" goodbyedpi.exe -2 --blacklist ..\blacklist.txt

Для тестирования я использовал сайт fansubs.ru, т.к. там самый простой HTTP без усложнений и легко виден тот самый GET-запрос. Я проверил, сайт не находится в файле blacklist.txt.

Мне кажется, было бы здорово починить этот функционал, чтобы список обрабатываемых сайтов работал правильно, чтобы не вызывать у провайдеров и надзирающих органов лишних подозрений слишком большим числом "странных" пакетов, а использовать такую лазейку более скрытно, только там, где она действительно нужна - это позволит использовать её более длительное время.

Ещё раз спасибо за Ваши труды :)

**Comment by ValdikSS** [comment]
Фрагментация осуществляется на уровне TCP операционной системой, ещё до того момента, как программа сможет определить запрашиваемый домен. Опция `--blacklist` выполняет модификации заголовков HTTP только для тех доменов, которые указаны в файле, но на фрагментацию это не влияет.

**Comment by username30** [comment]
> Фрагментация осуществляется на уровне TCP операционной системой, ещё до того момента, как программа сможет определить запрашиваемый домен. Опция `--blacklist` выполняет модификации заголовков HTTP только для тех доменов, которые указаны в файле, но на фрагментацию это не влияет.

Разве программа не перехватывает TCP пакеты так же, как и HTTP, и, соответственно может модифицировать их аналогичным образом? Или фрагментация может осуществляться только операционной системой? Фрагментируется ведь на 2 байта только первый пакет, а вторая половина передаётся одним куском...
Буду благодарен за разъяснения, нигде в документации программы не нашёл этого аспекта :)

**Comment by ValdikSS** [comment]
Фрагментация (опции `-f` и `-e`) осуществляется путем установки TCP-окна (TCP Window Size) в ACK-пакете от сервера, ещё до того, как начинают передаваться данные, и, соответственно, до того, как GoodbyeDPI сможет определить запрашиваемый домен.
Можно фрагментировать иначе, не изменяя TCP-окно, так, чтобы программа уже знала запрашиваемый домен на момент фрагментации, и это будет реализовано в новых версиях.

**Comment by username30** [comment]
Понял, спасибо! Будем ждать :)

**Comment by goldsanity** [comment]
Объясните чайнику: все сайты, внесенные в blacklist.txt, будут обрабабываться goodbyedpi, а остальные работать как без него?
Пробовал редактировать список, делал пустым, разницы не заметил. Обрабатывает все подряд.

**Comment by goldsanity** [comment]
> Если указан параметр `--blacklist blacklist.txt` то программа будет обрабатывать запросы только к хостам из данного списка.

Как я понял из инструкции, это влияет только на http сайты. А https в любом случае обрабатывается?

> --blacklist   [txtfile]  perform HTTP tricks only to host names and subdomains from
>                           supplied text file

**Comment by r4sas** [comment]
HTTPS это подкатегория HTTP, так что оно там тоже будет работать.
Если у вас не работает. предоставьте разработчику [дамп траффика](https://github.com/ValdikSS/GoodbyeDPI/wiki/%D0%9A%D0%B0%D0%BA-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%B4%D0%B0%D0%BC%D0%BF-%D1%82%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0-%D0%B2-Wireshark).

**Comment by ValdikSS** [comment]
@goldsanity 
>Как я понял из инструкции, это влияет только на http сайты. А https в любом случае обрабатывается?

Всё верно.

**Comment by ValdikSS** [comment]
Исправлено в GoodbyeDPI 0.1.8
https://github.com/ValdikSS/GoodbyeDPI/commit/35c6e401db72dedb66a47d74fa9bb5c28317a9e4
