### ISSUE TITLE
Make goodbyedpi run only on certain websites

### ISSUE THREAD

**Issue by Saya47** [ValdikSS/GoodbyeDPI#113]
Hello!
Can you make GoodbyeDPI run only on user-specified websites?

Because I only use GoodbyeDPI for YouTube, and when I want to view other websites I have to close GoodbyeDPI because it breaks other websites on my ISP. So is there any way to make it run only for youtube? 

Thanks :)

**Comment by ValdikSS** [comment]
Implemented in https://github.com/ValdikSS/GoodbyeDPI/commit/35c6e401db72dedb66a47d74fa9bb5c28317a9e4
