### ISSUE TITLE
 sandboxie SBIE2103 — 'windivert1.4 [DefaultBox]'

### ISSUE THREAD

**Issue by woodenn** [ValdikSS/GoodbyeDPI#114]
SBIE2103 Предотвращена попытка загрузить системный драйвер 'windivert1.4 [DefaultBox]' Не удаётся установить в  sandboxie

**Comment by woodenn** [comment]
Не получается установить в песочнице.

**Comment by ValdikSS** [comment]
Вы считаете, что это ошибка GoodbyeDPI? Для поддержки этой программы разработчикам нужно что-то делать дополнительно?

**Comment by woodenn** [comment]
Нет, я так не считаю. Sandboxie считает, что предотвратила установку  вредоносного руткита в систему. Я хотел совет, что можно сделать?

**Comment by woodenn** [comment]
Нет, я так не считаю. Sandboxie решило, что предотвратила установку  вредоносного руткита в систему. Я хотел совет, что можно сделать? Может у вас есть опыт  с Sandboxie.

**Comment by ValdikSS** [comment]
Я не пользовался Sandboxie. Если эта проргамма не позволяет использовать ПО, которое загружает свой драйвер, то это не ошибка GoodbyeDPI.

**Comment by ValdikSS** [comment]
Sandboxie, похоже, работает только в userspace, и не дает программам загружать драйвера. Переоткройте, если считаете иначе.
