### ISSUE TITLE
1.1.1.1 DNS has blocked ''http://archive.is/''

### ISSUE THREAD

**Issue by metapea** [ValdikSS/GoodbyeDPI#115]
For some time now, CloudFlare's DNS 1.1.1.1 has blocked the site web archive site ''http://archive.is/''.
I'm wondering, if you could bypass the DNS with goodbyeDPI while using it or check if the DNS is even blocking it in the first place. 

http://archive.is/y5JBA (https://twitter.com/archiveis/status/1081276424781287427)
https://community.cloudflare.com/t/archive-is-error-1001/18227 (i tried archiving it, but it was left blank: http://archive.fo/g0epf)

**Comment by r4sas** [comment]
huh? How DNS server can block site? Use other DNS server instead if CloudFlare gives incorrect record. GDPI cant help here.

**Comment by metapea** [comment]
Alright, just asking here since the site's userbase was mad and censured and the site wasn't working for me recently.

**Comment by ValdikSS** [comment]
This is not a GoodbyeDPI issue, and CloudFlare DNS does not block archive.is.
```
$ dig archive.is @1.1.1.1 +short
no-ecs.archive.is.
104.27.170.40
104.27.171.40
```

**Comment by Atavic** [comment]
From Twitter:

> Please do not use archive.IS mirror for linking, use others mirrors [.TODAY .FO .LI .VN .MD .PH]. .IS might stop working soon.

**Comment by metapea** [comment]
> From Twitter:
> 
> > Please do not use archive.IS mirror for linking, use others mirrors [.TODAY .FO .LI .VN .MD .PH]. .IS might stop working soon.

none of the mirrors worked, that why i asked.

**Comment by daveio** [comment]
The authoritative DNS for archive.is (and other TLDs) actively refuses to respond to queries initiated by recursive resolvers which don't send EDNS Client Subnet. Cloudflare is one of these resolvers, citing privacy concerns. Resolvers which send Client Subnet must be used to access archive.* domains. Yes, really: https://twitter.com/archiveis/status/1018691421182791680

**Comment by daveio** [comment]
@ValdikSS see previous comment for why this is a legit ticket and something this project can address.

**Comment by ValdikSS** [comment]
@daveoi, I know that archive.is and several other websites block Cloudflare resolvers, but I don't see this as a GoodbyeDPI issue. GoodbyeDPI only DNS function is DNS redirection, and by default it uses Yandex.DNS 77.88.8.8.

**Comment by volth** [comment]
>  and by default it uses Yandex.DNS 77.88.8.8.

Yandex DNS is not able to resolve ALL domains in `.mil` zone
