### ISSUE TITLE
doesn't work for imgur in Turkey

### ISSUE THREAD

**Issue by iamnotagentleman** [ValdikSS/GoodbyeDPI#118]
I was try all filters, but not one of doesn't work for imgur with "https", if you want wireshark scan or anything, I'd be glad to help you

**Comment by cheytacllc** [comment]
In Turkey use goodbyedpi with dnscrypt. Alternatively you can both of them in a single package github.com/cheytacllc/GUI-for-GoodbyeDPI

**Comment by abazad** [comment]
add this urls to blacklist.txt

imgur.com
i.imgur.com
img.imgur.com

**Comment by ValdikSS** [comment]
Please capture Wireshark dump and send it to me for analysis
https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark

**Comment by Bloomfear** [comment]
This is the blockcheck report. Is there anything i can do to bypass the block on wikipedia or imgur?

Test was made while goodbyedpi and dsncrypt turned off.

[Blockcheck.txt](https://github.com/ValdikSS/GoodbyeDPI/files/2997992/Blockcheck.txt)

**Comment by Guardiandota** [comment]
not working in UZ
[blockcheck.txt](https://github.com/ValdikSS/GoodbyeDPI/files/3000569/blockcheck.txt)

**Comment by ValdikSS** [comment]
For everybody in Turkey: it seems your DPI is now correctly handle fragmented packets.

**Comment by loserXD** [comment]
I'm in turkey and I can access imgur just fine with goodbyedpi

**Comment by iamnotagentleman** [comment]
Right Now, Working on Turkey !
