### ISSUE TITLE
Adnroid девайсы телефоны планшеты

### ISSUE THREAD

**Issue by avazzz** [ValdikSS/GoodbyeDPI#119]
Можно ли сделать такую программу для андроид телефонов планшетов?

**Comment by ValdikSS** [comment]
Да, но работать программа сможет только при наличии root-прав.

Программе требуется открывать RAW-сокет и изменять правила iptables, а для этого нужны root-права. Google считает, что безопасность превыше возможности использования всех функций ОС, поэтому пользователю нельзя давать права администратора на устройстве. В понимании Google, устройства под управлением Android — совсем не компьютеры, я же считаю это абсурдом.
