### ISSUE TITLE
Сваливается в die() после "Opening filter"  - UPD: была не запущена служба BFE

### ISSUE THREAD

**Issue by Himmler** [ValdikSS/GoodbyeDPI#12]
При запуске на Win7 программа сваливается в die(), после "Opening filter", запущена с правами администратора.

UPD: Разобрался, проблема была из-за выключенной службы базовой фильтрации (BFE), которая используется в WinDivert.
Может быть, стоит в описании указать о необходимости данной службы для работы ?

**Comment by ValdikSS** [comment]
Эта служба включена по умолчанию, не считаю нужным указывать это.
