### ISSUE TITLE
Блокировка подсетей с помощью отброса трафика

### ISSUE THREAD

**Issue by IRainman** [ValdikSS/GoodbyeDPI#120]
Доброго времени суток!

Такое впечатление что провайдер Ростелеком (Онлайм) при блокировке подсетями (в примере с 7zip 159.65.0.0/16 )использует что то вроде iptables drop поскольку 
rutracker.org открывается и корректно редиректится на https://rutracker.org/forum/index.php

а прямая ссылка на  https://www.7-zip.org/history.txt отваливается по таймауту. Через VPN в Нидерландах работает. 
`(__|__)`

**Comment by ValdikSS** [comment]
У Ростелекома появилось какое-то in-band-железо, которое настроено для заблокированных подсетей. Это не ошибка GoodbyeDPI (хотя, возможно, в следующей версии будет сделана опция, в какой-то мере обходящая это железо).

**Comment by IRainman** [comment]
Понял, благодарю. Хотелось бы получить уведомление когда можно будет потестировать что либо по теме ибо я первый раз попробовал сегодня GoodbayDPI и вернулся обратно на VPN ^_^'
