### ISSUE TITLE
NNM-club does not work completely.

### ISSUE THREAD

**Issue by Degaron** [ValdikSS/GoodbyeDPI#125]
Do not open sites from:

http://nnmclub.to/forum/search.php?cx=partner-pub-7768347321290299%3A4038489206&cof=FORID%3A10&q=hexlet&sa=%D0%98%D1%81%D0%BA%D0%B0%D1%82%D1%8C&siteurl=http%3A%2F%2Fnnmclub.to%2Fforum%2Flogin.php%3Fredirect%3Dsearch.php%3Fcx%3Dpartner-pub-7768347321290299%253A4038489206%26cof%3DFORID%253A10%26q%3Dhexlet%26sa%3D%25D0%2598%25D1%2581%25D0%25BA%25D0%25B0%25D1%2582%25D1%258C%26siteurl%3Dhttp%253A%252F%252Fnnmclub.to%252F

But they work through Tor.

Check this:
nnm-club.me/forum/viewtopic.php?t=1001642
nnm-club.me/forum/portal.php?d=09.01.2017
nnm-club.me/forum/viewtopic.php?t=1236076
...

**Comment by ValdikSS** [comment]
nnm-club.me is down.

**Comment by Degaron** [comment]
Чего давн? Всё работает через Тор.
И я про .to говорю. У них же зеркала.
Вон та длинная ссылка, это поиск по nnm-клубу, берём результаты оттуда и кидаем в Тор-Браузер, всё мгновенно открывается, а напрямую, через GDPI не открывается.

**Comment by ValdikSS** [comment]
Когда я это писал, сайт nnm-club.me у меня не открывался (попробовал из трех стран), а nnmclub.to открывался. Сейчас nnm-club.me открывается.

**Comment by Degaron** [comment]
Я предположил это, но я дал ссылку на .to, и ты по идее должен был проверить и её.

**Comment by ValdikSS** [comment]
Я не понимаю, о чём вы. Что мне нужно было проверить? Сейчас сайт открывается?
Если GoodbyeDPI не разблокирует некоторые сайты, то это не является ошибкой программы, и не следует писать об этом сюда. GoodbyeDPI не гарантирует полную разблокировку на любом провайдере.

**Comment by Degaron** [comment]
Да, не главная страница сайта, а часть внутренних ссылок не работает. И мне это даже странным показалось.

**Comment by ValdikSS** [comment]
У меня и сейчас из Латвии не работают эти ссылки. Проблема на стороне сайта.

**Comment by Degaron** [comment]
Вот и я подумал на сайт, но работает же в Торе.
Может, блокируют ещё где-то на пути до этого сайта.
Или действительно так странно настроен сайт, что через Тор всё норм, а так нет.

**Comment by Degaron** [comment]
Ладно, отпишу там Админу, может, решат проблему.
спс

**Comment by Degaron** [comment]
Ладно, само пройдёт, может.
Спс за помощь и прогу, жаль, она не поможет при чебурнете.

**Comment by AHOHNMYC** [comment]
На текущий момент ссылки починились и открываются.

**Comment by Degaron** [comment]
У меня так ничего и не работает.
