### ISSUE TITLE
opening websides with servers inside my country after bypass

### ISSUE THREAD

**Issue by Aliallameh** [ValdikSS/GoodbyeDPI#128]
So much slow or won't opening websites with servers inside my country. what can I do about this?

**Comment by r4sas** [comment]
Telepaths on vacation. We can't guess about which country you say.
Project target is Russia,

**Comment by ValdikSS** [comment]
Try to run program with `-4` argument, like `goodbyedpi.exe -4`. Does that still unblock blocked sites, and is it faster than default setting?

**Comment by Aliallameh** [comment]
i was talking about Iran.
telegram, for example, is blocked in here.
i tried all methods, -4 is not working
or websites that blocked us (for example console.cloud.google.com) will not work but others such as twitter youtube facebook,etc will work.
however I have used my special dns redirect and it worked opening sites like console.cloud.google that blocked iran successfully.
I just don't understand why telegram still not works
or for example, xda-developers is not closed in my country but after using this it will not open.
a question; can I add multiple dns?

**Comment by ValdikSS** [comment]
Websites which block you should not work. How is your last message related to the issue described in the first message?
What do you mean by adding multiple DNS?

**Comment by ValdikSS** [comment]
Websites which block you should not work. How is your last message related to the issue described in the first message?
What do you mean by adding multiple DNS?

**Comment by ValdikSS** [comment]
Websites which block you should not work. How is your last message related to the issue described in the first message?
What do you mean by adding multiple DNS?

**Comment by ValdikSS** [comment]
Websites which block you should not work. How is your last message related to the issue described in the first message?
What do you mean by adding multiple DNS?

**Comment by alim1369** [comment]
the problem is that goodbye dpi are can not pass dns.
In Iran all dns packets are replay by 10.10.34.35

**Comment by r4sas** [comment]
Use DNSCrypt in that way.

**Comment by ValdikSS** [comment]
GoodbyeDPI 0.1.8+ should work in this case by default, with `--auto-ttl` option.
