### ISSUE TITLE
Windows 10 BSOD

### ISSUE THREAD

**Issue by Arhelay** [ValdikSS/GoodbyeDPI#13]
Доброго дня.
Имею Win10 лицензию, с последними обновлениями.
При запуске программы ловлю BSOD либо сразу, либо при попытке перейти по любой ссылке/адресу в строке. 
Сообщение BSOD: Bad pool caller

**Comment by ValdikSS** [comment]
Попробуйте последнюю версию драйвера [WinDivert 1.2](https://reqrypt.org/windivert.html), во всех трех вариантах: MSVC, WDDK, MINGW. Просто подмените sys и dll-файлы. Каждый раз нужно перезагружаться. Заведите [issue](https://github.com/basil00/Divert/issues) по результатам, пожалуйста.

**Comment by chromigo** [comment]
У меня была такая же проблема. Не помогал ни один WinDivert 1.2 по ссылке. Помогло отключение антивируса(Avast). Ну и WinDivert 1.2 стоял MSVC к тому моменту.

**Comment by ValdikSS** [comment]
Попробуйте версию GoodbyeDPI 0.0.9, в ней теперь WinDivert 1.1.8 WDDM.

**Comment by chromigo** [comment]
В случае с Avast не помогло

**Comment by ValdikSS** [comment]
Попробуйте версию 0.1.1.

**Comment by Qwentor** [comment]
Хм, у меня тоже Avast и BSOD
минидамп: https://yadi.sk/d/V3f7R0zo3N7yh2

**Comment by ValdikSS** [comment]
Ошибка в WinDivert. Разработчик Avast говорит, что добавил код для обхода ошибки WinDivert в Avast. Вероятно, новая версия еще не распространяется через каналы обновления Avast.

**Comment by Qwentor** [comment]
>Ошибка в WinDivert
Ясно, спасибо
А разработчик WinDivert что-то говорит об этой ошибке?
Извиняюсь за наглость)

**Comment by ValdikSS** [comment]
https://github.com/basil00/Divert/issues/90

**Comment by Qwentor** [comment]
спс

**Comment by ValdikSS** [comment]
@basil0 исправил проблему, попробуйте WinDivert 1.3.0:
https://reqrypt.org/download/WinDivert-1.3.0-MINGW.zip

**Comment by ValdikSS** [comment]
GoodbyeDPI 0.1.1 теперь использует WinDivert 1.3.0, проблема с BSoD должна быть устранена. Откройте этот issue заново, если проблема проявляется.
