### ISSUE TITLE
Telegram Service

### ISSUE THREAD

**Issue by Aliallameh** [ValdikSS/GoodbyeDPI#130]
Why telegram both web and Application won't work after opening?
this service is blocked in my country

**Comment by r4sas** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/128#issuecomment-466642943

**Comment by ValdikSS** [comment]
Because GoodbyeDPI does not work with all ISPs and in all cases. Please carefully read issue report template instead of just deleting it.
>GoodbyeDPI does not guarantee to work on your ISP on 100% or at all. If GoodbyeDPI can't unblock some or any websites, this is most likely not a software bug, and you should not report it.
