### ISSUE TITLE
Сайт не работает.

### ISSUE THREAD

**Issue by kiridu1988** [ValdikSS/GoodbyeDPI#134]
Этот сайт не открывается.
https://learnxinyminutes.com/docs/ru-ru/nim-ru/

Хотя работает через Тор.

**Comment by ValdikSS** [comment]
Каким образом вы создали это сообщение об ошибке без шаблона? Что вы нажимали?

**Comment by kiridu1988** [comment]
Я взломал вселенную, а управление данным сайтом теперь для меня пустяковое дело. ^^

Я нажал на надпись под двумя шаблонами, но какая разница?

И что с моим вопросом?

![vzlom vselennoy](https://user-images.githubusercontent.com/47792950/54149247-c54bf600-4446-11e9-9b72-0b8e3c698e24.jpg)

**Comment by ValdikSS** [comment]
Не нажимайте эту кнопку, и прочтите текст шаблона:
>ВНИМАНИЕ! Пожалуйста, прочтите!
GoodbyeDPI не гарантирует ни 100% работу с вашим провайдером, ни работу вообще. Если GoodbyeDPI не разблокирует доступ к некоторым или всем веб-сайтам, вероятнее всего, это не программная ошибка, и не стоит о ней сообщать здесь.
Сообщайте только об ошибках в программе, таких как: некорректная работа с веб-сайтами (когда веб-сайт работает без GoodbyeDPI, но ломается с GoodbyeDPI), несовместимость с антивирусами, проблемы с перенаправлением DNS, некорректная обработка пакетов, и другие проблемы.
Также посмотрите другие открытые и закрытые баги. Возможно, ваш вопрос или проблема уже обсуждались.

**Comment by kiridu1988** [comment]
Валди, но всё остальное работает.
Может, лист обновить?

**Comment by ValdikSS** [comment]
Этот сайт находится на заблокированном диапазоне IP-адресов 159.203.0.0/16, принадлежащем Digital Ocean. Диапазоны адресов блокируются средствами маршрутизаторов, а не DPI, и GoodbyeDPI не поможет в таких случаях.

**Comment by kiridu1988** [comment]
Оппа, и Телеграм не работает.
А я всего-лишь перекатился на 10ку с 8ки.

**Comment by kiridu1988** [comment]
Я поставлю 8ку в виртуал и проверю, работает ли там.

**Comment by ValdikSS** [comment]
Видимо, у вас Ростелеком?
https://github.com/ValdikSS/GoodbyeDPI/wiki/Интереснная-особенность-DPI-Ростелекома

**Comment by kiridu1988** [comment]
Да, Ростелеком.

**Comment by kiridu1988** [comment]
Так можно всё же решение проблемы для Windows 10 сделать, через модификацию GoogbyeDPI или нет?

**Comment by ValdikSS** [comment]
Да, технически это возможно. Это требует серьезной модификации кода (написания системы отслеживания состояния TCP-соединений и модификации SEQ/ACK number), и запланировано на когда-нибудь.

В качестве альтернативы, можете установить Linux (например, OpenWRT) в виртуальную машину, настроить на нём [zapret](https://github.com/bol-van/zapret/), настроить обход блокировки Ростелекома (ссылка выше), и использовать его в качестве роутера.

**Comment by kiridu1988** [comment]
Слишком солжно :(

**Comment by kiridu1988** [comment]
К тому же, итак лаги сети бывают...

**Comment by kiridu1988** [comment]
Вот беру я рандомно сайт из блоклиста и спокойно захожу на него, а вот эти пара сайтов не работают
(телега и обучение nim).

Разве такое должно быть, если проблема с размером пакетов?

**Comment by kiridu1988** [comment]
Валди?

**Comment by kiridu1988** [comment]
В общем результат моих экспериментов с виртуальной Виндовс 8.1:
GoodbyeDPI включён везде, GoodbyeDPI включён только на хосте, GoodbyeDPI включён только на виртуалке: Два этих сайта не открываются, остальное работает.

Т.е. всегда одно и тоже.

**Comment by kiridu1988** [comment]
Виртуальный роутер DD-WRT x86 на VirtualBox
https://habr.com/ru/post/414655/
