### ISSUE TITLE
На сайт заходит, но музыку не крутит.

### ISSUE THREAD

**Issue by kiridu1988** [ValdikSS/GoodbyeDPI#136]
На сайт заходит, но музыку не крутит. На 10ке.
https://myzuka.club/Album/952179/Ryadom-S-Ptitsei-Ryadom-S-Ptitsei-2008

На 8.1 работало. Правда, иногда вроде какие-то перебои были.

Через Тор-браузер всегда работало и сейчас тоже.

**Comment by r4sas** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/new?assignees=&labels=&template=bug-report----------------------.md&title=

**Comment by kiridu1988** [comment]
Я уже заполнил всё, больше ничего не буду делать.

**Comment by kiridu1988** [comment]
https://www10.myzuka.me/Album/902194/Invektiva-Pomni-2017

А вот этот альбом работает. Странно.
И ты вообще кто такой?

Где Валдик?

**Comment by kiridu1988** [comment]
У второго альбома третья песня не работает. Может, не только.

**Comment by kiridu1988** [comment]
Как я и думал, Валдика надолго не хватило, и он забил хуй на GDPI.

**Comment by ValdikSS** [comment]
Это не ошибка GoodbyeDPI: музыка не играет и без программы.
Пожалуйста, следуйте шаблону, я же не просто так их написал. Как вы вообще его пропустили, удалили, что ли?

**Comment by AHOHNMYC** [comment]
*[Извините](https://files.catbox.moe/e4nycg.png)*
