### ISSUE TITLE
Not Work IN TURKEY

### ISSUE THREAD

**Issue by UtkuGARIP** [ValdikSS/GoodbyeDPI#139]
Not Work IN TURKEY :(

**Comment by ValdikSS** [comment]
GoodbyeDPI does not guarantee to work on your ISP on 100% or at all. If GoodbyeDPI can't unblock some or any websites, this is most likely not a software bug, and you should not report it.
Please report software bugs, such as: website incompatibility (if the website works without GoodbyeDPI but breaks with GoobyeDPI enabled), antivirus incompatibility, DNS redirection problems, incorrect packet handling, and other software issues.
Please make sure to check other opened and closed issues, it could be your question or issue has been already discussed.
