### ISSUE TITLE
Windows 7 Professional не инсталлируется/ не работает

### ISSUE THREAD

**Issue by kiridu1988** [ValdikSS/GoodbyeDPI#140]
Windows 7 Professional (не работает на двух разных сборках, одна точно MSDN официальная):

Инсталлируем (cmd от админа) и получаем ошибку, на заблокированные сайты после этого не заходит:
...\goodbyedpi-0.1.5>service_install_russia_blacklist
This script should be run with administrator privileges.
Right click - run as administrator.
Press any key if you're running it as administrator.
Для продолжения нажмите любую клавишу . . .
[SC] ControlService: ошибка: 1062:

Служба не запущена.

[SC] DeleteService: успех
[SC] CreateService: успех
[SC] ChangeServiceConfig2: успех

Имя_службы: GoodbyeDPI
        Тип                : 10  WIN32_OWN_PROCESS
        Состояние          : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        Код_выхода_Win32   : 0  (0x0)
        Код_выхода_службы  : 0  (0x0)
        Контрольная_точка  : 0x0
        Ожидание           : 0x0
        ID_процесса        : 6576
        Флаги              :

**Comment by ValdikSS** [comment]
Работает ли программа, будучи запущена не в виде сервиса? Проблемы только с установкой сервиса? Вы распаковали zip?

**Comment by ValdikSS** [comment]
```
WARNING! If you see this error on Windows 7, it means your system is horribly ou
tdated and SHOULD NOT BE USED TO ACCESS THE INTERNET!
Most probably, you don't have security patches installed and anyone in you LAN o
r public Wi-Fi network can get full access to your computer (MS17-010 and others
).
You should install updates IMMEDIATELY.
```

**Comment by kiridu1988** [comment]
Да, я вижу, что там написано, спс. Этим и занимался.
Я установил это обновление, после чего программа без ошибок установилась, и теперь браузер заходит на заблокированные сайты.

Но вы сами подумайте, вот установил человек программу, он не знает, как она устроена, что ей нужно для работы, а она, оп, и не запускается или не устанавливается.
И он же даже не знает, что _надо идти в какую-то вложенную папку_ и **запускать ЧЕРЕЗ КОНСОЛЬ** _какой-нибудь exe-шник_, который будет там лежать, чтобы **ПРОЧИТАТЬ В КОНСОЛИ** сообщение о том, что ему нужно что-то доустановить на его ОС, _что-то абсолютно неизвестное и непонятное ему_, _о чём он слышит в первые в жизни_.
Я думаю, чел, просто возьмёт, да удалит прогу в большинстве случаев и даже не пойдёт ни на какие Гитхабы, чтобы спросить совета там. Так все и делают.

Если вы программу только для себя написали, тогда зачем вы о ней рассказываете другим, чтобы они поставили её и удалили с испорченным настроением?

Вам надо фильм "Автостопом по галактике" посмотреть.
А то, что надо доустановить обнову на Винду нужно написать только в виде комментария посреди кода (поглубже закопать) и оставить его только там в сырцах. Вот.

Вы же всех честно предупредили, что требуется проге, всё, вы своё дело сделали и теперь вы чисты.

**Comment by r4sas** [comment]
Если человек установил не прочитав даже описания (которое есть [в корне](https://github.com/ValdikSS/GoodbyeDPI#known-issues) репозитория), то это сугубо его проблемы.

**Comment by r4sas** [comment]
@ValdikSS тебе на рассмотрение: https://gist.github.com/r4sas/7c895a24beb5b53ba49e301d510bbd4d

**Comment by ValdikSS** [comment]
> Я установил это обновление, после чего программа без ошибок установилась, и теперь браузер заходит на заблокированные сайты.

Если вы установили только это обновление, то вы всё ещё пользуетесь очень незащищенной ОС. Рекомендую не пользоваться ей для доступа в интернет. Вас могут легко взломать соседи по локальной сети, как пример.

>Но вы сами подумайте, вот установил человек программу, он не знает, как она устроена, что ей нужно для работы, а она, оп, и не запускается или не устанавливается.

Обычно, в таком случае читают справку. В справке указано, как запускать программу. Почему вы сразу начали устанавливать её в виде сервиса? Нашли рекоммендацию на каком-то стороннем сайте?
Справка советует использовать bat-файлы для запуска (с номерными префиксами), с ними вы бы увидели ошибку.

>Если вы программу только для себя написали, тогда зачем вы о ней рассказываете другим, чтобы они поставили её и удалили с испорченным настроением?

Чтобы использовать программу, нужно прочитать краткую справку по её использованию. Я старался сделать её понятной простому человеку, но программа не имеет графического интерфейса и подразумевает использование более-менее технически подкованным пользователем. Вы же, к сожалению, столкнувшись с проблемой, не стали читать справку или пытаться пробовать запускать другие bat-файлы, а сразу написали сюда, в обход шаблона для сообщения об ошибке. Мне это портит настроение, без шуток.

**Comment by XXLCXX** [comment]
Thank you for the good work.
