### ISSUE TITLE
error opening filter

### ISSUE THREAD

**Issue by yekayee** [ValdikSS/GoodbyeDPI#142]
![image](https://user-images.githubusercontent.com/17975832/59548458-f3772f80-8f79-11e9-9fd0-d5e8cff26aec.png)

can help ?

**Comment by ValdikSS** [comment]
Have you made sure you're running fully updated OS?

**Comment by yekayee** [comment]
already updated

**Comment by ValdikSS** [comment]
Seems like you haven't. Make sure you have KB3033929 installed. [x86](https://www.microsoft.com/en-us/download/details.aspx?id=46078), [x64](https://www.microsoft.com/en-us/download/details.aspx?id=46148) link.

**Comment by Degaron** [comment]
meow

**Comment by ValdikSS** [comment]
@yekayee does it work for you now?

**Comment by ValdikSS** [comment]
No response, closing.
