### ISSUE TITLE
Error Opening Filter.

### ISSUE THREAD

**Issue by RichiYuuki** [ValdikSS/GoodbyeDPI#143]
При запуске GoodbyeDPI выдает ошибку.

```
Opening filter
Error opening filter: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
```

![image](https://user-images.githubusercontent.com/31278421/59553828-97290580-8fa3-11e9-99a0-bdef8c1104f5.png)

Буду благодарен если подскажут как решить. Гуглить пробовал, но как-то результата никакого не дало.

**Comment by ValdikSS** [comment]
Пробовали перезагружаться?

**Comment by RichiYuuki** [comment]
Пока нет, сейчас возьмусь и перезагружусь.

**Comment by QwertySP234** [comment]
Ошибка 1058, раньше вроде норм работало
![QCMHaW7N9q](https://github.com/user-attachments/assets/9bf9f53e-d2d8-4c1b-bc62-901e347fbc6b)
