### ISSUE TITLE
Вопрос / багрепорт по комплексной проблеме

### ISSUE THREAD

**Issue by XCanG** [ValdikSS/GoodbyeDPI#144]
Я уже пользуюсь более полугода GoodbyeDPI и с недавних пор на одном сайте я стал замечать такую проблему, но сам я не могу понять что тут не так.
Я запускаю программу с такими параметрами (служба):
```
"D:\Prog\goodbyedpi-0.1.5\x86_64\goodbyedpi.exe" -4 --blacklist "D:\Prog\goodbyedpi-0.1.5\blacklist.txt"
```

Обычно оно обходит все блокировки. Если сайта нету в списке (список обновляю периодически), я добавляю его в список и после перезапуска смогу на него заходить. Где-то с месяц назад я встретил такую проблему на одном сайте: грузится сайт, CSS, JS, но не грузятся картинки на главной, если я открываю страницу с картинкой, то после того как она прогружается, возвращаясь назад загружаются все миниатюры и они продолжают подгружаться ещё какое-то время, если сёрфить по сайту (минут 10 примерно). Процесс можно повторить и всё будет работать и дальше. Мне совершенно непонятно такое явление, но вчера этот метод перестал работать. Покопавшись я нашёл способ, но перед этим вопрос: если в blacklist'е указан домен, то и его поддомены тоже учитываются? Потому что у миниатюр поддомен `t.`, а у изображений `i.` Как заработало сейчас: Я добавил поддомены в список (но не уверен если они и так раньше включались), если я перезапускаю программу с аргументом `-1`, то картинки подгружаются и я могу изменить обратно на `-4` и они будут продолжать работать тоже некоторое время, после чего нужно разок открыть страницу с `-1`, чтобы хоть одна снова подгрузилась.

В общем что тут можно сделать? Я бы может помониторил это как-то, но не знаю как/чем.
Есть идея использования `-1` для этих поддоменов и `-4` для всех остальных сайтов из списка, но в программе такого функционала нету.

**Comment by ValdikSS** [comment]
О каком сайте речь? Возможно, на пути следования пакетов до этого сайта есть система DPI от другого провайдера, для которой опции `-4` недостаточно.
Откройте инструменты сети в браузере (F12, вкладка network), обновите страницу и посмотрите, по каким URL загружаются картинки, и какие ошибки возвращают. Опубликуйте ссылки на эти картинки (и, желательно, скриншот вкладки network с этими ссылками) мне, я посмотрю, что с ними не так.

Запуск GoodbyeDPI с параметром `-1`, а затем с `-4` продолжает открывать страницы, вероятнее всего, из-за того, что браузер продолжает держать соединение с сайтом открытым какое-то время, даже если они не используется и вкладки уже закрыты.

В blacklist'е идет поиск по доменным зонам, т.е. при добавленной строке `www.ru` в файле блеклиста разблокировка будет применяться к самому `www.ru` и ко всем поддоменам.

**Comment by XCanG** [comment]
Ошибки никакой нету, ни 200, ни 400 или 500 каких-то, пусто. Даже заголовки не показывает, говорит они пустые. Я только могу сказать что пока я на странице мне пишет в углу: `Выполнение TLS-рукопожатия...`
В хроме ничего не понятно в инспекторе, в файрефоксе хотя-бы больше информации, вот например тайминги. Я тут ждал пока не отменил загрузку страницы.
![image](https://user-images.githubusercontent.com/4011523/62417999-96921e80-b678-11e9-98b7-5c2230606bc8.png)

Теперь если переключаюсь на `-1`, ответ такой:
```
HTTP/2.0 200 OK
server: nginx
date: Sun, 04 Aug 2019 00:29:56 GMT
content-type: image/jpeg
content-length: 18112
last-modified: Sat, 03 Aug 2019 21:33:46 GMT
expires: Thu, 31 Dec 2037 23:55:55 GMT
cache-control: max-age=315360000
vary: Accept
accept-ranges: bytes
X-Firefox-Spdy: h2
```
Тайминги
![image](https://user-images.githubusercontent.com/4011523/62418039-246e0980-b679-11e9-9998-36f2d71739b2.png)

Для страницы с картинкой
```
HTTP/2.0 200 OK
server: nginx
date: Sun, 04 Aug 2019 00:32:06 GMT
content-type: image/jpeg
content-length: 770694
last-modified: Sat, 03 Aug 2019 21:35:22 GMT
expires: Thu, 31 Dec 2037 23:55:55 GMT
cache-control: max-age=315360000
cache-control: public
accept-ranges: bytes
X-Firefox-Spdy: h2
```
![image](https://user-images.githubusercontent.com/4011523/62418050-5c754c80-b679-11e9-9e86-b496510defb6.png)

Переключаюсь снова на `-4`
Открываю какую-нибуть другую страницу (где в кеш не скачивалсь ничего, т.е. чтобы не возвратило 304 Not Modified)
```
HTTP/2.0 200 OK
server: nginx
date: Sun, 04 Aug 2019 00:34:01 GMT
content-type: image/jpeg
content-length: 45583
last-modified: Sat, 03 Aug 2019 13:26:24 GMT
expires: Thu, 31 Dec 2037 23:55:55 GMT
cache-control: max-age=315360000
vary: Accept
accept-ranges: bytes
X-Firefox-Spdy: h2
```
![image](https://user-images.githubusercontent.com/4011523/62418068-dc031b80-b679-11e9-82c0-b65669fdf374.png)

В хроме также, только не скопировать по-простому.

**Comment by ValdikSS** [comment]
О каком сайте идет речь?

**Comment by ValdikSS** [comment]
Нет ответа.
