### ISSUE TITLE
Не удается продолжить выполнения кода,поскольку система не обнаружила WinDivert.dll

### ISSUE THREAD

**Issue by Tigranius** [ValdikSS/GoodbyeDPI#145]
Сегодня скачал goodbyedpi версии 0.1.5 и при запуске exe файла в win rar пишет:системная ошибка Не удается продолжить выполнения кода,поскольку система не обнаружила WinDivert.dll. Для устранения этой проблемы попробуйте переустановить программу. после нескольких попыток запустить файл он все же запускается только в черном окне внизу написано: Error opening filter: The system cannot find the file specified. Видел на этом сайте подобный вопрос ответ на который была попытка удалить предыдущую версию программы но я скачивал программу в первый раз и предыдущих версий у меня не было.Буду очень благодарен

**Comment by r4sas** [comment]
> запуске exe файла в win rar

Надеюсь из архива то распаковали?

> я скачивал программу в первый раз

Если GDPI ставится впервые, это не значит что WinDivert не использовал какой либо другой сторонний софт (например те же активаторы от некоторых авторов).

Попробуйте проверить по тому же принципу, как это делал я: https://github.com/basil00/Divert/issues/165

**Comment by r4sas** [comment]
Поиск и удаление драйвера:
```cmd
>driverquery | find "Divert"
WinDivert1.4 WinDivert1.4           Kernel        1/16/2018 2:37:57 PM

>sc stop WinDivert1.4
...

>sc delete WinDivert1.4
...
```
Выполняем в командной строке с правами администратора, После этого ребут и новая попытка запустить GDPI.

**Comment by Tigranius** [comment]
Спасибо,попробую как смогу и отпишусь

**Comment by Tigranius** [comment]
вводить надо полностью? >driverquery | find "Divert" или какую то часть?

**Comment by r4sas** [comment]
Вводить всё кроме `>`.

**Comment by Tigranius** [comment]
ввожу первую часть >driverquery | find "Divert" ничего не происходит

**Comment by Tigranius** [comment]
и в списке драйверов не нашел Divert

**Comment by Tigranius** [comment]
просто перелистывывается дальше

**Comment by r4sas** [comment]
хм, а программу саму запускаете с правами администратора? У вас скорее всего WinRAR запускает без прав. Перейдите лучше с помощью проводника в папку где распакована программа и запустите оттуда через контекстное меню вызываемое правой кнопкой мыши.

**Comment by Tigranius** [comment]
В проводнике программа отображается значком WinRAR и в меню вызываемой правой мышкой нету возможности запустить от имени администратора

**Comment by Tigranius** [comment]
Я смог запустить программу от имени администратора но все осталось так же как я описывал выше

**Comment by r4sas** [comment]
> значком WinRAR

Я потому и спросил в первом ответе, распаковали ли вы программу?
Содержимое папки покажите.

**Comment by Tigranius** [comment]
Завтра постараюсь как можно раньше скинуть.

**Comment by Tigranius** [comment]
Спасибо большое,я перенёс из винрара папку на рабочий стол и запустил от имени администратора и все работает,ещё раз спасибо за уделённое вами время

**Comment by Tigranius** [comment]
🤓
--
Отправлено из  Mail для Android вторник, 14 января 2025г., 17:51 +04:00 от default-writer  ***@***.*** :
