### ISSUE TITLE
Question about Toredo tunneling

### ISSUE THREAD

**Issue by Setaran** [ValdikSS/GoodbyeDPI#146]
**Description**
Hello I just am very curious and have a few questions about Toredo tunneling.

1. What provider are you using to give us IPv6 through GBDPI? (My ISP doesn't have native IPv6).

2. IPv6 is SOOOO helpful in circumventing and opening all blocked (censored) websites.
For example I was never able to open blocked HTTP websites but now with Toredo IPv6 I can (I was only able to open blocked HTTPS websites without Toredo).

3. It used to work before for quite a while and then it stopped working.. why?! But now it's working again fortunately.

Thanks very much, I appreciate your time and effort.

**Comment by r4sas** [comment]
You mean Teredo?

**Comment by ValdikSS** [comment]
>What provider are you using to give us IPv6 through GBDPI? (My ISP doesn't have native IPv6).

GoodbyeDPI does not provide IPv6 access, it only modifies the packets over IPv6 too, as well as with IPv4. It does not use any external service and does not tunnel/proxy the traffic.

>[Teredo]… used to work before for quite a while and then it stopped working.. why?! But now it's working again fortunately.

I don't know, you should check your Teredo configuration and server. GoodbyeDPI could not influence your IPv6 connectivity.

**Comment by Setaran** [comment]
Oh.. I understand now ValdikSS :) Thanks very much!
@r4sas yes.. xD
