### ISSUE TITLE
Works weird in turkey

### ISSUE THREAD

**Issue by ajdarkonkon** [ValdikSS/GoodbyeDPI#147]
i test with many sites seems like it wont work with sites dont exist in blacklist and when i try to add or use every other option doesnt work (like imgur,pastebin,tunein)

but when i  use any site exist in blacklist works perfectly fine.Either blacklist not works as intended or only bugged in turkey.

**Comment by ValdikSS** [comment]
Please write in your native language (Turkish) and I'll try to translate it using automatic translation.

**Comment by Bloomfear** [comment]
He is trying to say that adding blocked sites to the blacklist doesn't work. I can't reach some websites even though i added them to the blacklist.

**Comment by ValdikSS** [comment]
Blacklist works only for HTTP protocol, not for HTTPS.
https://github.com/ValdikSS/GoodbyeDPI/issues/112

>Fragmentation is performed on TCP level by the operation system, before when the program can determine requested domain name. `--blacklist` option only controls for which domain names HTTP modification options are to be applied (such as `-r, -s, -m`), but that doesn't have any effect on fragmentation.

>Fragmentation (`-f` and `-e` options) is performed by shrinking TCP window size in server's ACK packet, that happens before any payload transmission, so the fragmentation is already performed but GoodbyeDPI doesn't know the domain name yet.
It's possible to fragment the other way, not by shrinking the window size, and that would be implemented in the future versions of the software.

**Comment by Bloomfear** [comment]
Ah thank you, is there any chrome extension that forces websites to use http instead of https?

**Comment by ValdikSS** [comment]
Try https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp

**Comment by ValdikSS** [comment]
Oh, you want wise-versa. I don't know such extension.

**Comment by ValdikSS** [comment]
Blacklist for HTTPS websites has been implemented in GoodbyeDPI 0.1.8
https://github.com/ValdikSS/GoodbyeDPI/commit/35c6e401db72dedb66a47d74fa9bb5c28317a9e4
