### ISSUE TITLE
I've Android Rooted device & so excited to test the Android release.

### ISSUE THREAD

**Issue by hamedsbt** [ValdikSS/GoodbyeDPI#149]
Hello, I'm a professional Android user and my device is Oneplus One with Android Pie, Rooted (Magisk , exposed and dnscrypt) 

Magisk? https://forum.xda-developers.com/apps/magisk
Xposed? https://github.com/ElderDrivers/EdXposed
DNScrypt? https://github.com/jedisct1/dnscrypt-proxy

So I'm ready to run, test and report debug log to help for build up stable release for Android app and help to people for access to uncensored internet.

Also I've a suggestion: Please review the [Fragmenting SSL ClientHello](https://github.com/prodeveloper0/FuckDPI_V2) project too, it may teach you more tricks that currently working (at least in my country)

Thank you.

**Comment by ValdikSS** [comment]
GoodbyeDPI is Windows-only and I don't know when it would be ported to another OS.
You can try [zapret](https://github.com/bol-van/zapret), it should worn on Android.
Your link (FuckDPI_V2) contains the code already present in GoodbyeDPI.
