### ISSUE TITLE
Рубит службу

### ISSUE THREAD

**Issue by 22PAiN** [ValdikSS/GoodbyeDPI#15]
Добрый день.

При запуске из под админа служба запускается, все работает.
Спустя секунд 10 служба останавливается.
Win 7, 64.
В чем может быть затык?
Служба базовой фильтрации (BFE) включена

**Comment by ValdikSS** [comment]
Я не пользуюсь Windows. Может, кто-то сможет вам помочь.

**Comment by nshopik** [comment]
Гляньте application логи в винде, там обычно причина есть почему была служба остановленна

**Comment by sergeevabc** [comment]
Родной способ установки какого-либо бинарника как службы в Windows:
```sc.exe create GoodbyeDPI binPath= "диск:\путь\goodbyedpi.exe -4" start= auto```
Но если бинарник не имеет функций для работы службой, то служба вскоре остановится с [ошибкой 1053][1].
Возможно, Валдик добавит отсутствующие функции в следующей версии.

[1]: https://www.reddit.com/r/sysadmin/comments/2s7llg/how_to_create_a_windows_service/

**Comment by Tallefer** [comment]
Еще можно попутно глянуть в DNSCrypt, там встроена самоустановка в службы

**Comment by 22PAiN** [comment]
Всем спасибо за помощь. 
Служба работает. Ставил х86. Cнес ее и установил х64. Все норм.
Только не пробил заглушку, пришлось, дополнительно, DNSCrypt ставить.

**Comment by sergeevabc** [comment]
Доработку GoodbyeDPI (используя комментарии от меня и @Tallefer) можно вынести в отдельную задачу..

**Comment by ValdikSS** [comment]
@Tallefer, @sergeevabc, возможность работы в виде службы добавлена в commit 23babdc8facff4cc9528bcace843e79615d2676f.

**Comment by Tallefer** [comment]
Круто, спасибо. К сожалению, не смогу потестить, ибо сижу пока на ХР, но это точно полезная фича.
