### ISSUE TITLE
Драйвер в автозагрузку + Bitcoin

### ISSUE THREAD

**Issue by ParAmbula** [ValdikSS/GoodbyeDPI#151]
При обновлении blacklist в автозагрузку прописался WinDivert1.4 и сразу же удалился, при просмотре через Autorun Organizer можно получить следующее сообщение. Что это за драйвер и для чего он нужен?
![Capture](https://user-images.githubusercontent.com/36849204/68218815-d8ff2a80-ffdc-11e9-85b6-5a8f863158a4.PNG)

**Comment by r4sas** [comment]
RTFM:
https://github.com/ValdikSS/GoodbyeDPI#how-to-build-from-source ->
https://github.com/basil00/Divert/blob/master/README

**Comment by ValdikSS** [comment]
Этот драйвер используется для получения и отправки сетевых пакетов.
