### ISSUE TITLE
Проблема с провайдером ТТК

### ISSUE THREAD

**Issue by newTomas** [ValdikSS/GoodbyeDPI#152]
У меня провайдер, который берет инет от ТТК (при заходе на заблокированные сайты кидает на сайт ТТК). Стандартные конфиги не обходят его защиту, помог ключ -m. Только он и ничего лишнего, все начинает работать как надо, но вот сайт РЖД выдает 403 ошибку при включенном GoodByeDPI. Сделайте пожалуйста уже отмену редиректа на сайт провайдера, я бы указал уже сайт провайдера и не мучался, теперь придется blacklist обновлять каждый раз.

**Comment by ValdikSS** [comment]
Ключ `-m` с блеклистом должен работать корректно и не должен влиять на незаблокированные сайты. У вас не открывается сайт rzd.ru с `-m` и `--blacklist` одновременно, при этом в blacklist нет домена rzd.ru?

>Сделайте пожалуйста уже отмену редиректа на сайт провайдера, я бы указал уже сайт провайдера и не мучался, теперь придется blacklist обновлять каждый раз.

Не понял, о чём вы. Вы полагаете, что если заблокировать перенаправление на страницу-заглушку провайдера, то заблокированные сайты начнут открываться? Нет, с активным DPI, который у ТТК, не начнут.
