### ISSUE TITLE
Не работают трекеры bt*.t-ru.org и сайт t.me (telegram.org)

### ISSUE THREAD

**Issue by AlexMak58** [ValdikSS/GoodbyeDPI#153]
Не работают трекеры __bt*.t-ru.org__ и сайт **t.me** (**telegram.org**).

С ReQrypt 1.4.1 webUI (Windows 10) все работает отлично, но зачастую сервер на обработку исходящего трафика недоступен.

Провайдер: МТС

**Comment by bavefiy111** [comment]
Попробуйте в хост прописать

163.172.167.207 bt.t-ru.org
163.172.167.207 bt2.t-ru.org
163.172.167.207 bt3.t-ru.org
163.172.167.207 bt4.t-ru.org

У меня телеграм открывается. Стоит dnscrypt + 1_russia_blacklist_dnsredir

**Comment by AlexMak58** [comment]
@bavefiy111, да, я в курсе про файл hosts, но хотелось бы иметь возможность обходить блокировки только утилитой GoodbyeDPI. Буду пробовать другие настройки.

**Comment by ValdikSS** [comment]
Это не проблема _программы_. Пожалуйста, читайте сообщение внутри шаблона при создании сообщения о проблеме.
