### ISSUE TITLE
Проблемы со входом на сайты sberbank.ru и sberbank.online.ru

### ISSUE THREAD

**Issue by liveonloan** [ValdikSS/GoodbyeDPI#158]
С включенным goodbyedpi-0.1.6 (используется) 1_russia_blacklist.cmd
Наблюдаются периодические (практически постоянные) проблемы с входом на сайты sberbank.ru и sberbank.online.ru
Иногда они открываются сразу, иногда через секунд 15, иногда и чаще всего вообще не открываются.
Хуже всего обстоят дела с sberbank.online.ru, он обычно вообще не открывается, а если открылся - то на авторизации "вечная загрузка" и вот такое сообщение:
![Screenshot_6](https://user-images.githubusercontent.com/35786329/70267861-58d10e00-17b0-11ea-8a72-a4ea6b911803.jpg)
Когда отключаю goodbyedpi-0.1.6, все становится хорошо, оба сайта загружаются мгновенно и с авторизацией нет никаких проблем.

С другими сайтами с включенным goodbyedpi-0.1.6 никаких проблем.
Только Сбербанк глючит.

p.s.
На другой машине goodbyedpi более древний - на нем тоже самое.

Провайдер: РOCTEЛEKОM (Подольск).
Роутер: KEENETIC GIGA KN-1010
Винда: Windows 10 LTSC x64 RU
Браузеры: "Разные" на всех этот глюк, основной браузер CENT BROWSER

**Comment by ValdikSS** [comment]
Вероятно, срабатывают какие-то защитные механизмы сайта. Напишите в Сбербанк, если есть желание, но абсолютно уверен, что они не будут делать ничего.

**Comment by liveonloan** [comment]
ValdikSS 
Это все понимаю :) Глюпый вопрос:
А возможно ли как то добавить sberbank.ru и sberbank.online.ru в исключение? Что бы "механизмы сбербанка" не портили малину?
Можно конечно просто выключать goodbyedpi, но сами понимаете - лишние клики и все такое!

**Comment by Dante4** [comment]
Могу добавить, что на версии 1.5rc1 online сбер работал.

**Comment by Dante4** [comment]
Могу сказать, что изменения в сайте Сбера произошли не так давно, потому что 2 недели назад он работал с Goodbyedpi

**Comment by slva2000** [comment]
Подтверждаю.
ValdikSS, даёшь белый лист!

**Comment by liveonloan** [comment]
@slva2000 
Я нашел решение.
GoodbyeDPI 0.1.6 + Launcher 3.7 - там все можно под себя настроить.
Теперь и сбер работает и сайты заблокированные доступны.

**Comment by slva2000** [comment]
> @slva2000
> Я нашел решение.
> GoodbyeDPI 0.1.6 + Launcher 3.7 - там все можно под себя настроить.
> Теперь и сбер работает и сайты заблокированные доступны.

Юзаю последний лаунчер. Прошу скрин чеков или как...?

**Comment by liveonloan** [comment]
@slva2000 
Для меня главным "открытие" стало то, что если GoodbyeDPI 0.1.6 + Launcher 3.7 запущен в обычном режиме **(не как служба windows)** то сайт сбербанка и сбербанк онлайн работает.
Провайдер РТ (московская область).
Настроил так:
1) https://funkyimg.com/i/355QQ.jpg
2) https://funkyimg.com/i/355QR.jpg
3) https://funkyimg.com/i/355QS.jpg
4) https://funkyimg.com/i/355QT.jpg

Если у вас такой трюк не прокатит, попробуйте поставить галочку вот тут:
1) https://funkyimg.com/i/355Rb.jpg

Обязательно почистите кеши и куки браузера!

Скрины с подтверждением что все работает *у меня* с такими настройками.
Главное: GoodbyeDPI 0.1.6 + Launcher 3.7 запущен в обычном режиме, а не как служба windows:
1) https://funkyimg.com/i/355Rf.jpg
2) https://funkyimg.com/i/355Rg.jpg

**Comment by slva2000** [comment]
Спасибо, но, дело не совсем в этом. Вероятно даже не в самом сбере, а, как мне кажется, в провайдере (Ростелеком Сибирь).

Не "как служба" - точно не помогает. Крыжик - фильтровать только из списка - помогло. Но, это не выход, так как этот список "медленнее" РКН

**Comment by liveonloan** [comment]
@slva2000 
Хорошо что помогло! Думаю от провайдера это тоже может зависть.
Я редко посещаю незнакомые (заблокированные) сайты. 
Есть основной набор трекеров и других ресурсов которые посещаю ежедневно. По этому гонки с РКН не устраиваю :)

**Comment by sergeevabc** [comment]
Лаунчер никак не помогает пробиться к Сбербанку — это всего лишь параметры командной строки GoodbyeDPI, выполненные в виде галок и кнопок. Повторить расписанное @liveonloan можно так: ```goodbyedpi.exe -4 --blacklist domains-export.txt``` (до этого скачав [domains-export.txt][1]). Однако, если фильтр провайдера хоть чего-то стоит, то на Рутор или Рутрекер таким образом уже не зайти, вылетит заглушка провайдера или повиснет долгое ожидание — приходится применять более сложные трюки вроде фрагментации HTTPS, которую, увы, не переваривает Сбербанк (с другими банками подобного не наблюдаю). Как изначально писал @ValdikSS, надо долбить техподдержку.

[1]: https://antizapret.prostovpn.org/domains-export.txt

**Comment by liveonloan** [comment]
@sergeevabc 
На рутор мне и так не зайти! (с недавних пор) :) Рутор просто врубает **переадресацию** на нерабочее (просроченное) зеркало... И хоть тресни я её выключить не могу. Долблю рутор - молчат... Долбил до этого сбербанк - они вообще не понимают что я от них хочу :)

**Comment by Neurotoxin001** [comment]
А почему сбербанк вообще задевает, если я использую "блеклист", то есть GoodbyeDPI должен работать только на сайты из этого "блеклиста"? А сбера в нём нет.

**Comment by ValdikSS** [comment]
Проблемы с TCP-фрагментацией должны быть решены в версии GoodbyeDPI 0.1.7, опцией `--reverse-frag`.

TCP fragmentation issues should be solved in GoodbyeDPI 0.1.7, by using `--reverse-frag` option.
