### ISSUE TITLE
WinDivert farms bitcoins

### ISSUE THREAD

**Issue by Rinkashikachi** [ValdikSS/GoodbyeDPI#159]
I tryed to move the folder to different place after launching this program and closing it. It didn't allow me, because WinDivert was still running. There also was shown some URL and then "Bitcoin: %random letters and numbers looking like a bitcoin wallet code%". I understand that screenshots would be nice, but Im not launching this shit again

**Comment by ValdikSS** [comment]
It also installs trojans, wipes you whole PC, and then kills your dog.

No, it doesn't farm bitcoins. Why would you think that? It just has developer's bitcoin wallet in the driver description. You can't move the driver because, well, it's running.

**Comment by Rinkashikachi** [comment]
lol, for what reason it can have developers bitcoin app?

**Comment by ValdikSS** [comment]
It has developer's bitcoin address (wallet) for donations.

**Comment by Rinkashikachi** [comment]
and what is the normal way (instead of finding that it has bitcoin wallet while trying to move the file) to lookup this wallet through this file?

**Comment by ValdikSS** [comment]
Right-click on the driver and check its description and other metadata.

**Comment by Rinkashikachi** [comment]
ok, thanks, seems legit
