### ISSUE TITLE
Proxifier

### ISSUE THREAD

**Issue by asmadeus08** [ValdikSS/GoodbyeDPI#16]
Есть ли возможность совместить proxifier и данный софт. Или чтобы он проксировал весь трафик. Например я пользуюсь десктоп версией Telegram и кроме браузеров и торрента у меня блокировку нигде не обходит. Проживаю в Центральной Азии.

**Comment by ValdikSS** [comment]
Программа модифицирует запросы только на порты 80 и 443, на уровне системы. Это не прокси-сервер, вам не нужен proxifier для него, как и какие-либо настройки.

**Comment by asmadeus08** [comment]
Я понимаю этот момент но хотелось бы чтобы программа была совместима с proxifier чтобы я мог совместить весь системный трафик, наприме десктоп-клиент telegram который заблочен у меня в стране. А так в браузере и в торрент-клиенте все работает.

**Comment by ValdikSS** [comment]
Как проявляется несовместимость сейчас?

**Comment by asmadeus08** [comment]
Речи о не совместимости нет. Просто я не знаю как объединить работу goodbyedpi и proxifier чтобы он заворачивал весь десктопный трафик. Например десктоп версия телеграм.

**Comment by ValdikSS** [comment]
Я не понимаю, что вы пытаетесь сказать. Proxifier перестает работать с прокси-сервером, если запустить GoodbyeDPI?

**Comment by asmadeus08** [comment]
У меня есть proxifier. И есть goodbyedpi. Я хочу совместить обе эти программы чтобы goodbyedpi делал разблокировку по socks5 протоколу а не только по порту 80/443

**Comment by ValdikSS** [comment]
У вас сейчас настроен Proxifier на какой-либо Socks5-прокси? Ваш провайдер блокирует трафик внутри Socks5, или вообще Socks5? Зачем вам Proxifier, если в Telegram и так есть поддержка Socks5? Я не понимаю, чего вы хотите добиться, и как пытаетесь это сделать. GoodbyeDPI — не Socks5-прокси, его нельзя настроить в Proxifier.

**Comment by asmadeus08** [comment]
1 На данный момент использую shadowsocks (внешний сервер) + profixier чтобы заворачивать весь системный трафик через внешний сервер.
2 Мой провайдер использует активный DPI для блокировки vpn/ssh/proxy сервисов
3 В телеграм есть поддержка сокс но ее нужно писать вручную тогда как proxifier все на автомате покрывает следуя заданный правилам. А вот вашу программу никак объединить с proxifier нельзя чтобы она помогала обходить блокировки, так как не поддерждивается протокол socks5 а что делать если программа не поддерживает http/https?
4 Про то и речь может есть возможность как-то объединить или написать дополнение для создания socks-layer?

**Comment by ValdikSS** [comment]
>а что делать если программа не поддерживает http/https?

Ничего. Программа модифицирует заголовки HTTP, и заставляет ОС разрезать первый пакет HTTPS на два (или более). Для не-HTTP-трафика единственная возможность обхода DPI — фрагментация. Не думаю, что она будет эффективна для Socks5, ведь там нет шифрования.

У вас уже есть Shadowsocks, зачем вам GoodbyeDPI?

**Comment by asmadeus08** [comment]
Думал чтобы не зависеть от внешних серверов. Тогда другой момент. А что делать с udp? У меня провайдер блокирует UDP-пакеты по активному и пассивному DPI. Из-за этого у меня вместо 650 кбайт на выходе получается 65 кбайт, поэтому я вынужден пользоваться shadowsocks. Если ваш софт мог udp-блокировку обходить в обоих направлениях было бы вообще замечательно.

**Comment by ValdikSS** [comment]
Как связана скорость с блокировкой? Какие протоколы по UDP блокирует ваш провайдер?

**Comment by asmadeus08** [comment]
Весь UDP полностью режет, а именно работа UDP дает полную скорость, именно только shadowsocks дает возможность обходить обрезание скорости по UDP, не знаю как связано но это факт.

**Comment by ValdikSS** [comment]
Если бы у вас был заблокирован UDP полностью, у вас бы не работал DNS и NTP, и вы бы сюда не писали.

**Comment by asmadeus08** [comment]
Потому я и пользуюсь shadowsocks + dnscrypt ведь без них у меня практически никуда нет доступа.

**Comment by sergeevabc** [comment]
> @ValdikSS: Я не понимаю, что вы пытаетесь сказать. 

Я тоже едва понял. Крепитесь!
