### ISSUE TITLE
Loading of images on some sites

### ISSUE THREAD

**Issue by Freybjorn** [ValdikSS/GoodbyeDPI#160]
I have two problems with the performance of some sites from the territory of the CIS (Russia): blocked access from the territory of the Russian Federation on the site itself (not by providers in the Russian Federation) - e-hentai.org: is it possible to use your application to bypass (somehow) restrictions on this site?
And the second: -booru forums of a similar theme (simple arts on characters of geek-culture, and hentai) there are problems: sfw site: danbooru.donmai.us opens the pictures correctly, but gelbooru.com loads the thumbnails, but does not open the pictures. What do you think could be the matter?
I can’t remember exactly, but it seems I used to work with the "-1 -a" settings, but now it’s not working. Today I updated application to the latest version (used two outdated versions earlier) and still have a prob. :C

**Comment by ValdikSS** [comment]
>e-hentai.org: is it possible to use your application to bypass (somehow) restrictions on this site?

The administrator of e-hentai has blocked access for Russian IP addresses. It's not possible to bypass that with GoodbyeDPI.

>-booru forums of a similar theme (simple arts on characters of geek-culture, and hentai) there are problems: sfw site: danbooru.donmai.us opens the pictures correctly, but gelbooru.com loads the thumbnails, but does not open the pictures. What do you think could be the matter?

Could you provide the example link?

**Comment by ValdikSS** [comment]
No response, closing.
