### ISSUE TITLE
Unable to Access thewindowsclub.com

### ISSUE THREAD

**Issue by pc-v2** [ValdikSS/GoodbyeDPI#161]
Option that i use:
`2_all_dnsredir.cmd`
What to expect:
Able to open thewindowsclub

I also can't access netflix (throttled by isp) if i don't use goodbyedpi
`service_install_russia_blacklist_dnsredir.cmd`

![image](https://user-images.githubusercontent.com/58063311/71323094-073fb780-2502-11ea-9140-09ee776a1e1a.png)

![image](https://user-images.githubusercontent.com/58063311/71323098-0d359880-2502-11ea-99d9-167614e1300e.png)

**Comment by ValdikSS** [comment]
See #4

**Comment by ValdikSS** [comment]
Works fine for me right now. Can you confirm?

**Comment by pc-v2** [comment]
> Works fine for me right now. Can you confirm?

yes!
