### ISSUE TITLE
GoodbyeDPI ломает работу сайта ulmart.ru и citilink.ru

### ISSUE THREAD

**Issue by krab** [ValdikSS/GoodbyeDPI#162]
Запускается в службах Windows так: ` "C:\Program Files\goodbyedpi\x86_64\goodbyedpi.exe" -1 --blacklist "C:\Program Files\goodbyedpi\blacklist.txt" ` 

Список обновляется так в планировщике заданий Windows: `chp "C:\Program Files\goodbyedpi\0_russia_update_blacklist_file.cmd" ` (но это не важно).

Ошибка в Firefox при открытии 
` При соединении с www.ulmart.ru произошла ошибка. PR_END_OF_FILE_ERROR `

Провайдер: Ростелеком (Чувашия).
Роутер: ASUS RT-AC57U 
Браузер: Firefox, Chrome, MS Edge.

**Comment by krab** [comment]
На ситилинке тоже самое. Чяднт?

**Comment by ValdikSS** [comment]
См. https://github.com/ValdikSS/GoodbyeDPI/issues/4

**Comment by ValdikSS** [comment]
У меня проблема не наблюдается, оба сайта открываются корректно с `-1`. Можете снять дамп трафика и прислать на iam@valdikss.org.ru?
https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by ValdikSS** [comment]
Ulmart закрылся, Citilink открывается.
