### ISSUE TITLE
Unload WinDivert Driver

### ISSUE THREAD

**Issue by thankuverymuch** [ValdikSS/GoodbyeDPI#163]
Hello.
WinDivert64.sys file is not deleted after execution.
How can I unload a driver without rebooting?
I'd like to unload the WinDivert with a command-line.
Thank you.

**Comment by ValdikSS** [comment]
```
sc stop WinDivert1.3
sc delete WinDivert1.3
```

**Comment by thankuverymuch** [comment]
This is not a question.
It's a bug if it can't be erased by the end of the program.
Why do drivers reside?
Fix it.

**Comment by thankuverymuch** [comment]
And the way you told me won't work.
sc stop WinDivert1.3
sc delete WinDivert1.3
It doesn't work.
[SC] OpenService fail 1060:

**Comment by ValdikSS** [comment]
The driver may be used by other software, that's why it's not unloaded automatically by WinDivert library. I'm not aware if it's possible to detect whether there are other software using this driver, and I don't see this as an issue. This is a documented WinDivert behavior.

**Comment by thankuverymuch** [comment]
Then I want to unload it manually.
But the way you told me doesn't work.

**Comment by ValdikSS** [comment]
You need to run these commands as administrator.

**Comment by thankuverymuch** [comment]
The SC command is meaningless because you have never registered for a service.
I'm an administrator account.

**Comment by ValdikSS** [comment]
WinDivert registers the service. Try WinDivert1.4.

**Comment by thankuverymuch** [comment]
Oh, it was 1.4. Thank you.

**Comment by AlphaBlue7** [comment]
I tried those commands that was mentioned in powershell but i still can't delete WinDivert64.sys, i found out that the latest version is 2.2 but even after replacing the version number in the commands but I still can't delete WinDivert64.sys
