### ISSUE TITLE
Настройка брандмауэра Windows 10

### ISSUE THREAD

**Issue by hardwarecrypto** [ValdikSS/GoodbyeDPI#164]
Брандмауэр работает для "общего профиля" в режиме "исходящие подключения" - <блокировать>.
Создано правило для "исходящего подключения" для программы chrome.exe "действие" - <разрешить подключение>, удаленные протоколы и порты TCP 80, 443.
После запуска GoodbyeDPI в любом режиме подключение блокируется для всех запросов.
Если создать правило для "исходящего подключения" для "все программы и службы" - <разрешить подключение>, удаленные протоколы и порты TCP 80, 443. То подключения с запущенным GoodbyeDPI не блокируется для всех запросов.
Для каких конкретно служб должны быть настроены дополнительные правила, чтобы не отрывать для всех программ и служб исходящие подключения?

**Comment by ValdikSS** [comment]
Please DO NOT ASK QUESTIONS in Github issues. This section is for issues only. Use support forum at https://ntc.party/c/community-software/goodbyedpi.
