### ISSUE TITLE
GoodbyeDPI блокирует подключения

### ISSUE THREAD

**Issue by hardwarecrypto** [ValdikSS/GoodbyeDPI#165]
Брандмауэр работает для "общего профиля" в режиме "исходящие подключения" - <блокировать>.
Создано правило для "исходящего подключения" для программы chrome.exe "действие" - <разрешить подключение>, удаленные протоколы и порты TCP 80, 443.
После запуска GoodbyeDPI в любом режиме подключение блокируется для всех запросов.

**Comment by ValdikSS** [comment]
Пожалуйста, не делайте вид, что вы меня не поняли. Не игнорируйте шаблоны issues, задавайте вопросы на форуме, а не здесь.
