### ISSUE TITLE
перестало пускать на https://www.lostfilm.tv/

### ISSUE THREAD

**Issue by lowtrucks** [ValdikSS/GoodbyeDPI#166]
**Опишите проблему**
GoodbyeDPI запущен в виде сервиса.

уже вторую неделю перестало пускать на https://www.lostfilm.tv/.

выдаёт следующую ошибку - Error code: SSL_ERROR_RX_MALFORMED_SERVER_HELLO

провайдер - МТС.

**Comment by IRainman** [comment]
А это не та же самая проблема  #4

**Comment by lowtrucks** [comment]
честно говоря, не знаю.

когда lostfilm.tv был заблокирован в РФ, на него можно было зайти при запущенном GoodbyeDPI.

данный способ обхода работал неделю, а потом перестал.

**Comment by r4sas** [comment]
Так возможно переехали на блокировку по IP.

**Comment by lowtrucks** [comment]
да, видимо, так и есть.

получилось зайти на lostfilm.tv при помощи GoodbyeDPI + anonymoX.
