### ISSUE TITLE
Похожие проекты

### ISSUE THREAD

**Issue by zhenyolka** [ValdikSS/GoodbyeDPI#167]
Как я вижу, у тебя в readme есть список похожих приложений. Прошу тебя туда добавить свое приложение для андроид [DPITunnel](https://github.com/zhenyolka/DPITunnel).
Эта штука создает локальный http proxy и, с его помощью, модифицирует пакеты. Умеет все, кроме атаки десинхронизации.

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/commit/b69ab64d5d2494debd7d9f39dd5b3277e4b0b681

Было бы здорово всё-таки сделать единое универсальное ядро, чтобы в каждом проекте не приходилось каждому писать весь код заново. Может, займётесь?

P.S. как в Android обрабатываются данные внутри VPN? Можно ли их обрабатывать по TCP-потокам, а не по-пакетно? Или обязательно нужен userspace IP-стек?

**Comment by zhenyolka** [comment]
К сожалению у меня нет много времени на поддержание проекта и тем более создание общего ядра.
Android'овский VpnService позволяет обрабатывать только по одному пакету, поэтому я и сделал DPI Tunnel в виде прокси, чтобы иметь комфортную возможность обрабатывать по-запросно.

**Comment by ValdikSS** [comment]
Каким образом вы перенаправляете запросы на прокси? userspace-стеком, или как-то иначе?

**Comment by zhenyolka** [comment]
Командой от рута "settings put global http_proxy 127.0.0.1:port", если нету рута, пользователь сам должен прописать в настройках wifi или APN.

**Comment by ValdikSS** [comment]
Это несерьезно, лучше сделайте через lwip.

**Comment by ValdikSS** [comment]
См. https://github.com/ambrop72/badvpn/wiki/Tun2socks и похожие проекты.
