### ISSUE TITLE
GoodbyeDPI vs ГИС ЖКХ (https://dom.gosuslugi.ru)

### ISSUE THREAD

**Issue by RangerRU** [ValdikSS/GoodbyeDPI#169]
С активным GoodbyeDPI перестает работать сайт https://dom.gosuslugi.ru (ГИС ЖКХ)
ошибка в IE11: Не удается безопасно подключиться к этой странице
в хроме: Не удается получить доступ к сайту

Как только отключаешь GoodbyeDPI - сайт сразу открывается

Юзаю сборку с https://topersoft.ml/programs/launchergdpi

Провайдер: РOCTEЛEKОM (Амурская область)
Роутер: ASUS DSL-N12U
Винда: Windows 10 LTSC x64 RU / Windows 10 Pro 1903 x64 RU
Браузер: Internet Explorer 11, Google Chrome, Mozilla Firefox, Яндекс-Браузер

**Comment by ValdikSS** [comment]
См. #4 
Отправил информацию об ошибке в техническую поддержку dom.gosuslugi.ru.

**Comment by RangerRU** [comment]
Благодарю!
ТП на госпорталах не отличается умом и сообразительностью...

**Comment by ValdikSS** [comment]
Периодически отвечают, что-то пытаются делать, вроде как.

**Comment by RangerRU** [comment]
@ValdikSS похоже заработало)))
