### ISSUE TITLE
Проблема с плеерами

### ISSUE THREAD

**Issue by SilverIceee** [ValdikSS/GoodbyeDPI#17]
Здравствуйте.
Не представляется возможным использовать ключ "-p" с плеерами на сайтах вроде kinogo.club, gidonline.club и т.д. Плееры просто не грузятся. Без данного ключа всё прекрасно работает.

**Comment by ValdikSS** [comment]
Приведите прямую ссылку на страницу с проблемными плеерами.

**Comment by ValdikSS** [comment]
Полностью решить проблему в общем виде, без добавления поиска строк вроде "zapret", "block", не получится. Возможно, частично поможет блокировка перенаправлений только с заголовком `Connection: close`.

**Comment by SilverIceee** [comment]
Как минимум можно добавить функцию поиска заглушки по адресу. А адрес сообщать дополнительным параметром. Но для текущей проблемы это будет просто костылём.

**Comment by ValdikSS** [comment]
Часто бывает так, что на пути прохождения пакета не один DPI, а несколько, и не всегда можно наверняка знать, на какие заглушки они перенаправят. У меня есть pcap'ы, где пакет проходит 3 DPI, прежде чем дойдет до сайта.

**Comment by ValdikSS** [comment]
Исправлено в v0.0.8.
