### ISSUE TITLE
Unable to resolve local DNS names after 'ipconfig /flushdns'

### ISSUE THREAD

**Issue by GCRaistlin** [ValdikSS/GoodbyeDPI#175]
If 'ipconfig /flushdns' was executed while GoodbyeDPI is running (launched by 1_russia_blacklist_dnsredir.cmd) it is unable to resolve local DNS names:
```
ping server.domain.local
Ping request could not find host server.domain.local. Please check the name and try again.

nslookup server.domain.local
Server:  UnKnown
Address:  192.168.0.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to UnKnown timed-out
```
Right after closing GoodbyeDPI the commands above start working.
The same issue exists after returning from hibernation.

**Comment by ValdikSS** [comment]
Well, it's because of DNS redirection in 1_russia_blacklist_**dnsredir**.cmd. Do not use it in this case.
