### ISSUE TITLE
Protonmail is blocked in Russia

### ISSUE THREAD

**Issue by twepl** [ValdikSS/GoodbyeDPI#178]
ValdikSS see if you'll be able to do something.

https://protonmail.com/

**Comment by ValdikSS** [comment]
Yes, it's blocked. If GoodbyeDPI doesn't unblock it, there's nothing I can additionally do to make it work. Use proxy/VPN in this case.

**Comment by ValdikSS** [comment]
Protonmail has a small TCP Window size in SYN-ACK packet for selected Russian ISP, this applies at least to Rostelecom IP addresses.
You can use GoodbyeDPI v0.2.1 with `--allow-no-sni` option, it should work.

**Comment by Neurotoxin001** [comment]
Не открывается даже с `--allow-no-sni`
0.2.1
`goodbyedpi.exe -5 --allow-no-sni --blacklist blacklist.txt`
