### ISSUE TITLE
Не работает для меня.

### ISSUE THREAD

**Issue by powerofgreed** [ValdikSS/GoodbyeDPI#179]
Здравствуйте. Перепробовал все режимы. Ни в каких из них не получалось обойти блокировку. В большинстве из них переставали открываться некоторые сайты, например тот же гитхаб. Пользуюсь провайдером ТТК города Магнитогорск. Не пользуюсь роутером, PPP соединения. Замена сайта происходит даже без подключения к интернету. 
Есть вариант как-то разобраться через какие-либо мои логи? как их сделать?

**Comment by r4sas** [comment]
https://github.com/ValdikSS/blockcheck

**Comment by powerofgreed** [comment]
[test.txt](https://github.com/ValdikSS/GoodbyeDPI/files/4547870/test.txt)
Сделал.

**Comment by powerofgreed** [comment]
По итогу вариантов обходить DPI нет, кроме ВПН или Прокси ?

**Comment by ValdikSS** [comment]
blockcheck заброшен и не работает, будет всегда показывать неверный результат.
Мне пока не до тестирования новых провайдеров. Используйте VPN или прокси.

**Comment by ValdikSS** [comment]
blockcheck заброшен и не работает, будет всегда показывать неверный результат.
Мне пока не до тестирования новых провайдеров. Используйте VPN или прокси.
