### ISSUE TITLE
Worried about the legality of this program

### ISSUE THREAD

**Issue by arenavetissian** [ValdikSS/GoodbyeDPI#182]
Is this legal?

**Comment by sa3dany** [comment]
Depends on where you live of course, so check your local laws.

**Comment by ValdikSS** [comment]
This software is designed to bypass Internet censorship. Check your local laws whether this is legal in your country.

Issue section is for software bugs, incompatibilities or other problems, not for questions or discussions.
For questions use https://ntc.party/c/community-software/goodbyedpi
