### ISSUE TITLE
Only 3_all_dnsredir_hardcore.cmd successfully bypasses dpi

### ISSUE THREAD

**Issue by unirockers** [ValdikSS/GoodbyeDPI#183]
Hey, I'm running Windows 10 and I tried using 
**service_install_russia_blacklist.cmd** by replacing **-1** with a **-2**/**-3**/**-4** 
but nothing works, I keep getting the "URL Blocked!" page.

But when I run **3_all_dnsredir_hardcore.cmd** 
everything works, and dpi is bypassed, 
please tell me a way to add **3_all_dnsredir_hardcore.cmd** 
as a service without any dialog box (always open command prompt)

![Untitled](https://user-images.githubusercontent.com/66122696/83259960-95694980-a1d6-11ea-8691-f40c06b73dfa.png)

**Comment by ValdikSS** [comment]
You'll need to create your own .bat file or to run it once manually with all the required flags. Check the files and do similar.
Please restrain from asking questions in the issue section. This doesn't belong here.
