### ISSUE TITLE
Some websites redirect to http://aidiyet.esb.org.tr

### ISSUE THREAD

**Issue by discomfortingsounds** [ValdikSS/GoodbyeDPI#185]
GoodbyeDPI works for most websites in Turkey (and thank you a lot for that), but for some reason, some websites redirect to http://aidiyet.esb.org.tr
For example: http://www.imagebam.com/ redirects to http://aidiyet.esb.org.tr/landpage?ms=http://www.imagebam.com/ and it fails to load saying "ERROR 404 Page Not Found"

Do you have any idea what technique they might be using to do this, and if you can somehow bypass it?

Thanks

**Comment by ValdikSS** [comment]
Could that be DNS hijacking I guess? Try to use DNS over HTTPS or DNS over TLS.

**Comment by Bloomfear** [comment]
It must be an ISP error. I'm also in Turkey using Kablonet with DNS  1.1.1.1.

This site is working fine http://www.imagebam.com/

**Comment by ValdikSS** [comment]
This is clearly a misconfiguration of `aidiyet.esb.org.tr`, which I assume should be an informational page with block reason etc.
Not a GoodbyeDPI issue.
