### ISSUE TITLE
Can't configure settings

### ISSUE THREAD

**Issue by alfarizigan** [ValdikSS/GoodbyeDPI#187]
I wanna change GoodbyeDPI's default DNS to Google DNS but how to set it? Whenever I open goodbyedpi.exe it's always shows like that and I cant type anything..
![googbye](https://user-images.githubusercontent.com/67716370/86301057-0add9500-bc2f-11ea-9c05-c31fd1f0dac9.png)

One more question, if I changed the default GoodbyeDPI's DNS to Google DNS would it still be work to unblock those blocked websites and etc?

**Comment by ValdikSS** [comment]
Issue section is for software bugs, incompatibilities or other problems, not for questions or discussions.
For questions use https://ntc.party/c/community-software/goodbyedpi
