### ISSUE TITLE
WinXP support

### ISSUE THREAD

**Issue by Tallefer** [ValdikSS/GoodbyeDPI#19]
Как насчет сабжа? Не вдаваясь в целесообразность этого, по возможности... :)
Бинарник, слава создателю, написан на старозаветной сишечке и пашет на ХР без проблем, даже у WinDivert.dll заголовок подразумевает запуск на всем, начиная с НТ4, а вот драйвер WinDivert32.sys уже только с 6.1. Но он скомпилен в 2015 и чужой, поэтому есть предположение, что его перекомпилить было проблематично по каким-то причинам. Или там проблема с завязкой на особенности свежих систем?

**Comment by ValdikSS** [comment]
В Windows нет Windows Filtering Platform, который использует драйвер.
Пожалуйста, не используйте Windows XP.
