### ISSUE TITLE
Just asking about goodbyedpi

### ISSUE THREAD

**Issue by darkreaperboy** [ValdikSS/GoodbyeDPI#190]
I live in iran and most of sites like Facebook, tweeter, everything that we are blocked by government
I was looking for a way to unblock sites without vpn and i found this on a fourm:
[Stubby+Goodbyedpi.zip](https://github.com/ValdikSS/GoodbyeDPI/files/5304794/Stubby%2BGoodbyedpi.zip)

This version is all about double click and most of sites are unblocked and was fine and one day my friend scan this and told this has a trojan and since i am not developer, i wanted to ask if it's safe to use or not....

**Comment by ValdikSS** [comment]
Well, at least GoodbyeDPI and WinDivert are original files, haven't been modified.
Didn't check stubby.
