### ISSUE TITLE
При включенном GoodbyeDPI не работает приложение Uplay.

### ISSUE THREAD

**Issue by alucarD1701** [ValdikSS/GoodbyeDPI#192]
GoodbyeDPI установлен как сервис, параметры -f 2 -k 2 -n -e 40. Пол года назад такой проблемы не было. Винда 10 2004.
![image](https://user-images.githubusercontent.com/11311781/96354712-59317980-10e2-11eb-8719-fb647e1b1258.png)

**Comment by arrow00009** [comment]
Im facing same issue

**Comment by ValdikSS** [comment]
I suppose it's #4.

**Comment by alucarD1701** [comment]
Ну а мне то что делать? Постоянно включать-выключать goodbyedpi неудобно, юплей нужен, на заблокированные сайты тоже постоянно захожу. Исключения для https в goodbyedpi не предусмотрены, так понимаю. Им в тп писать? Так они меня лесом пошлют.

**Comment by XCanG** [comment]
Есть какие-то решения этой и похожей проблемы? Я не сразу понял в чём было дело и долго разбирался почему что-то не работает. Вообще с 23.11 внезапно многие сервисы и сайты стали отваливаться. blacklist обновил в то время, но результат остался таким же.

К примеру что отвалилось:
* Uplay синхронизация, но вход работает
* Steam просмотр страниц товара (коммьюнити, подключения, синхронизации и пр. всё-ещё работают)
* Личный кабинет налогоплатильщика lkfl2.nalog.ru
* Полные версии некоторых кртинок в Discord'е. Предпросмотр их проксированных изображений работает, но бывает что полная версия не прогружается.
* и пр.

Профиль стоял `-2`

**Comment by smell-of-rain** [comment]
Йоу, вопрос такой, фрагментация https пакетов относится только к TCP стеку?
UDP соединения по протоколу QUIC не затрагиваются, так?

**Comment by ValdikSS** [comment]
@smell-of-rain, да, однако QUIC всё равно первоначально согласовывается внутри TLS (TCP) соединения.

**Comment by ValdikSS** [comment]
Проблемы с TCP-фрагментацией должны быть решены в версии GoodbyeDPI 0.1.7, опцией `--reverse-frag`.

TCP fragmentation issues should be solved in GoodbyeDPI 0.1.7, by using `--reverse-frag` option.

**Comment by ValdikSS** [comment]
Если проблема была не с фрагментацией, напишите об этом здесь, я переоткрою тикет.

**Comment by alucarD1701** [comment]
> Если проблема была не с фрагментацией, напишите об этом здесь, я переоткрою тикет.

Да, теперь Uplay работакт корректно. Спасибо.

**Comment by XCanG** [comment]
> Если проблема была не с фрагментацией, напишите об этом здесь, я переоткрою тикет.

У меня в итоге перестал работать GoodbyeDPI какое-то время назад, заставить работать я его не смог (со всевозможными комбинациями флагов), в итоге решил взять VPN. Было бы неплохо, если бы вы обновили `blockcheck`, чтобы понять что стоит у провайдера сейчас (может там активный DPI).

Я конечно могу попробовать новую версию, но если оно не работало глобально, то не думаю что заработает сейчас.

**Comment by alucarD1701** [comment]
> > Если проблема была не с фрагментацией, напишите об этом здесь, я переоткрою тикет.
> 
> У меня в итоге перестал работать GoodbyeDPI какое-то время назад, заставить работать я его не смог (со всевозможными комбинациями флагов), в итоге решил взять VPN. Было бы неплохо, если бы вы обновили `blockcheck`, чтобы понять что стоит у провайдера сейчас (может там активный DPI).
> 
> Я конечно могу попробовать новую версию, но если оно не работало глобально, то не думаю что заработает сейчас.

У меня Дом.ру, где-то неделю назад перестал работать GoodbyeDPI, но немного потанцевас с wrong-chksum и set-ttl снова всё заработало.
