### ISSUE TITLE
перестало работать на RT

### ISSUE THREAD

**Issue by westyles** [ValdikSS/GoodbyeDPI#196]
Здравствуйте. Позавчера на ростелекоме перестало работать, сайты не открываются, с надписью: 

> Не удается безопасно подключиться к этой странице
> 
> Возможно, на сайте используются устаревшие или ненадежные параметры безопасности протокола TLS. Если это будет повторяться, обратитесь к владельцу веб-сайта.

Такое было несколько месяцев назад, часов 12 не работало. Потом опять всё стало работать само. Скорее всего что то в РТ делают с этим. Я использую всё время: service_install_russia_blacklist.cmd (v1.6)
Проверил сейчас все заготовленные батники с другимим вариантами запуска. Так же гуи сейчас проверил (v3.8) с разными вариантами и ручными вариантами разными, либо перебрасывает на заглушку РТ либо просто не открывается сайт.

Могу передать нужные данные или что то проверить, если потребуется. Блокчек пишет что можно использовать любой вариант обхода, но все сайт там не открываются когда он проверяет, но он устарел скорее всего сильно.
Проверял всё на https://nnmclub.to
При открытии долго идёт подключение: Выполнение TLS-Рукопожатия ...
А через прокси открывается.
Обновление винды не ставил давно, браузер тот же, касперский обновлял неделю назад. так что дело не в этом. Винда Windows 10 LTSC x64

**Comment by otohime-inari** [comment]
Подтверждаю. У ростелекома явно что-то поменялось несколько дней назад. У меня завелось вот с такими настройками
goodbyedpi.exe -1 --wrong-chksum --set-ttl 5 --blacklist ..\blacklist.txt

**Comment by westyles** [comment]
> 
> 
> Подтверждаю. У ростелекома явно что-то поменялось несколько дней назад. У меня завелось вот с такими настройками
> goodbyedpi.exe -1 --wrong-chksum --set-ttl 5 --blacklist ..\blacklist.txt

У меня не открывает. Я проверял только на nnmclub.to

**Comment by liveonloan** [comment]
@westyles пробуй такую комбинацию! 
![Screenshot_1](https://user-images.githubusercontent.com/35786329/99926404-a1336400-2d52-11eb-9d21-7f415c7c69fc.jpg)
С недавних пор такая же лабуда с РТ - мне помогло это (как на скриншоте)!
Для начала - обязательно перезагрузи роутер!
Далее:
Блокировка пассивных DPI всегда вкл.
Замена заголовка Host на hoSt (пробуй включить)
или
Удаление пробела между именем параметра Host.... (пробуй включить)
(2ю и 3ю галку можно попробовать поставить одновременно)
Отправка фейковых HTTP/HTTPS запросов.... (пробуй включить и ставь значение от 3 до 5) - без этого параметра у меня никакие варианты не срабатывали!

https://nnmclub.to/ - у меня стал доступен после этого.

**Comment by westyles** [comment]
**liveonloan** Заработало, даже с **HTTP**! Премного благодарен. раньше работало только с **HTTPS**
Работает и при твоих настройках и проверил при первых 4 включенных + TTL c 3 по 5. Роутеры выключал на минуту.

Вот для батника так работает на RT.
`goodbyedpi.exe -1 -p -r -s -m --set-ttl 3 --blacklist ..\blacklist.txt`

Для установки службой на такую строку заменить для Ростелеком:
`sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -1 -p -r -s -m --set-ttl 3 --blacklist \"%CD%\blacklist.txt\"" start= "auto"`

**Comment by liveonloan** [comment]
@westyles Рад что получилось! 
С этой штукой боролся всю ночь, а под утро роутер перегрузил, от отчаяния и еще раз попробовал (получилось).
Надеюсь что этот вариант будет еще долго работать. Но чувствую что пора *на всякий пожарный, подыскивать torrent friendly vpn.
Все сильнее гайки закручивают...

**Comment by darkk** [comment]
Возможо, это в какой-то мере совпадает по времени с выкатыванием врезки рекламы в HTTP-трафик Ростелекомом в Питере в последний месяц:
- 27 октября 2020 https://habr.com/en/company/roskomsvoboda/blog/485902/#comment_22232158
- 18 ноября 2020 https://t.me/theyforcedme/2528

**Comment by ValdikSS** [comment]
@westyles, @otohime-inari, @liveonloan, в каких вы регионах?

**Comment by otohime-inari** [comment]
@ValdikSS 
Мурманск

**Comment by liveonloan** [comment]
@ValdikSS 
Московская область, г. Подольск, мкр. Климовск

**Comment by westyles** [comment]
Северо-Западный регион.

**Comment by liveonloan** [comment]
@westyles 
Иногда nnmclub.to почему то недоступен - возможно проблемы с сервером...
Нашел еще одно прекрасное решение!
Устанавливаешь расширение в хром или мозилу: https://blockchain-dns.info/
И спокойно заходишь на http://nnm-club.lib/
(На всякий пожарный этот способ - пригодится).

**Comment by Erquint** [comment]
РТ МО и, ой вей, у меня началась какая-то знатная йухня.
Сначала GDPI потерял всякую эффективность — спасался автопрокси АнтиЗапрет.
Затем и прокси перестали иметь эффект — всё равно выхожу на заглушки.
На что только не грешил, уже и SVM отключал в железке…

При том BlockCheck не может ни до прокси, ни до isup.me достучаться и некорректно обрабатывает аргументы запуска.

Крыша едет, присаживаюсь на измену, нужна помощь.
Так как провал какой-то неоднозначный, боюсь сыпать issues в несколько репозиториев не разобравшись в корне казуса.
Пообщаться бы с Валдиком в человеческом режиме, но Джаббер надо отрыть…

**Comment by liveonloan** [comment]
@Erquint Привет!
Пробуй как на скриншоте: https://github.com/ValdikSS/GoodbyeDPI/issues/196#issuecomment-731906721

**Comment by Erquint** [comment]
@liveonloan Да ведь пробовал уже, без ГУИ только. И "перед" перезагружал и после.
Поставил Акулу, чтобы к пакетам присмотреться. Сейчас ребутнусь для завершения установки и попробую ещё раз.

**Comment by liveonloan** [comment]
@Erquint 
Можно попробовать с Ланчером GoodbyeDPI.
Если не выйдет, пробуй: рекрипт https://reqrypt.org/reqrypt.html псифон https://www.psiphon3.com/ru/index.html и варп https://1.1.1.1/
Но с ними желательно использовать Adguard в его расширенных настройках, следует обязательно поставить галку "использовать драйвер в режиме перенаправления" (рекрипт, псифон и варп могут рекламу встраивать - *предположение, или не давать её нормально фильтровать).

**Comment by Erquint** [comment]
Да вот ГУИ (лаунчеру) этому стороннему я не очень склонен доверять.
Ну посудите сами: автор нашёл на какой-то помойке истории MSVB, накодил в нём нечто, что может выдавать два разных набора крякозябр без Юникода, обфусцировал это всё двумя (?) пакерами и, вместо репозитория с открытым кодом, распространяет эту дичь на (внимание!) уже заблокированном ГосНаркоБорделем торрент-трекере.
[![](https://i.imgur.com/mawOt12m.jpg)](https://i.imgur.com/mawOt12.png)
Такие дела и в общем вещь ненужная.

Хотя вон некоторый турок написал свой аналог под вменяемые QT и открыл [репу](https://github.com/Include-sys/GUI-for-GoodbyeDPI) по-соседству.
У них там тоже жара с блокировками…

Сейчас вот заработала такая комбинация: `goodbyedpi.exe -p -r --set-ttl 3`, **но меня очень напрягает, что ситуация как-то очень быстро меняется в течении дня**, будто они наживую там орудуют над блокиратором своим.
Вчера всё было по-другому и утром тоже снова иначе. Прокси то работали, то нет. GDPI только сейчас заработал наконец хоть как-то.
Видать тестируют разные подходы для оценки эффективности в предверьи каких-нибудь очередных выборов и т. п.
Чего теперь ждать завтра..?

На всякий пожарный есть ТОР, но я не люблю доверять свой траффик третьим лицам, и даже не из соображений безопасности, а с технической стороны, так что шифрование тут ни при чём. GDPI подкупает своей автономностью и надёжностью. С первого релиза на Хабре безупречно пахал на `-3`.

Теперь вот этот `--set-ttl`… Мне придётся его теперь перекалибровывать в случае изменений пропускной способности до провайдера?

Продолжаю с нетерпением ожидать расширенной документации, которая бы объяснила почему и как работает каждая из применяемых техник, но понимаю, что это связано с риском преждевременного обнаружения…

**Comment by Mavreak** [comment]
Народ, помогите плиз, не понимаю но у меня по какой то причине goodbyedpi вообще отказывается работать, то есть запускаю в макс режиме, но браузер будто игнорит наличие goodbyedpi, я один такой безрукий, или на самом деле есть сложности?

**Comment by Erquint** [comment]
@Mavreak Сложности всегда где-то у кого-то есть. Вон у меня те ещё…
Вы бы описали подробности, приложили лог blockcheck'а, рассказали, работал ли он раньше и при каких настройках, уточнили провайдера, опять же, регион.
Чем сочнее картину болезни нарисуете — тем легче будет вам помочь.

Предложеные выше решения пробовали?

**Comment by Mavreak** [comment]
> 
> 
> @Mavreak Сложности всегда где-то у кого-то есть. Вон у меня те ещё…
> Вы бы описали подробности, приложили лог blockcheck'а, рассказали, работал ли он раньше и при каких настройках, уточнили провайдера, опять же, регион.
> Чем сочнее картину болезни нарисуете — тем легче будет вам помочь.
> 
> Предложеные выше решения пробовали?
Сегодня первый раз попробовал работать  через goodbyedpi,кроме фактически запуска и запустить как службу больше ничего не пробовал
Город: СПб
Провайдер: SkyNet

Вот лог:

BlockCheck v0.0.9.8
Для получения корректных результатов используйте DNS-сервер провайдера и отключите средства обхода блокировок.

Проверка работоспособности IPv6: IPv6 недоступен.
[O] Тестируем IPv4 DNS
	Через системный DNS:	 ['185.37.129.10', '185.37.129.10', '185.37.129.10', '185.37.129.10', '185.37.129.10', '185.37.129.10']
	Через Google DNS:	 ['104.18.182.1', '104.18.183.1', '104.26.10.39', '104.26.11.39', '104.26.4.231', '104.26.5.231', '172.67.70.38', '172.67.70.99', '195.8.215.136', '195.82.146.214', '67.202.114.141']
	Через Google API:	 ['104.18.182.1', '104.18.183.1', '104.26.10.39', '104.26.11.39', '104.26.4.231', '104.26.5.231', '172.67.70.38', '172.67.70.99', '195.8.215.136', '195.82.146.214', '67.202.114.141']
	Несуществующий DNS не вернул адресов (это не ошибка)
[☠] DNS-записи подменяются
[✓] DNS не перенаправляется

[O] Тестируем HTTP (по настоящим IP-адресам сайтов)
	Открываем  http://a.putinhuylo.com/
[✓] Сайт открывается
	Открываем  http://furry.booru.org/
[☠] Получен неожиданный ответ, скорее всего, страница-заглушка провайдера. Пробуем через прокси.
[☠] Сайт не открывается через прокси
	Проверяем доступность через isup.me
[⁇] Неожиданный ответ от isup.me, код 403
	Открываем  http://furry.booru.org/index.php?page=post&s=view&id=111173
[☠] Сайт не открывается, пробуем через прокси
[☠] Сайт не открывается через прокси
	Проверяем доступность через isup.me
[⁇] Неожиданный ответ от isup.me, код 403
	Открываем  http://pbooru.com/
[☠] Сайт не открывается, пробуем через прокси
[☠] Сайт не открывается через прокси
	Проверяем доступность через isup.me
[⁇] Неожиданный ответ от isup.me, код 403
	Открываем  http://pbooru.com/index.php?page=post&s=view&id=303026
[☠] Сайт не открывается, пробуем через прокси
[☠] Сайт не открывается через прокси
	Проверяем доступность через isup.me
[⁇] Неожиданный ответ от isup.me, код 403
	Открываем  http://rutracker.org/forum/index.php
[✓] Сайт открывается

[O] Тестируем HTTPS
	Открываем  https://e621.net/
[☠] Сайт не открывается
	Открываем  https://lolibooru.moe/
[☠] Сайт не открывается
	Открываем  https://rutracker.org/forum/index.php
[✓] Сайт открывается
	Открываем  https://www.dailymotion.com/
[✓] Сайт открывается

[O] Тестируем обход DPI
	Пробуем способ «дополнительный пробел после GET» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «заголовок hOSt вместо Host» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «заголовок hoSt вместо Host» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «значение Host БОЛЬШИМИ БУКВАМИ» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «необычный порядок заголовков» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «отсутствие пробела между двоеточием и значением заголовка Host» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «перенос строки в заголовках в UNIX-стиле» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «перенос строки перед GET» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «табуляция в конце домена» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «точка в конце домена» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «фрагментирование заголовка» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «фрагментирование заголовка, hoSt и отсутствие пробела одновременно» на pbooru.com
[☠] Сайт не открывается
	Пробуем способ «дополнительный пробел после GET» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «заголовок hOSt вместо Host» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «заголовок hoSt вместо Host» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «значение Host БОЛЬШИМИ БУКВАМИ» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «необычный порядок заголовков» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «отсутствие пробела между двоеточием и значением заголовка Host» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «перенос строки в заголовках в UNIX-стиле» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «перенос строки перед GET» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «табуляция в конце домена» на rutracker.org
[☠] Сайт не открывается
	Пробуем способ «точка в конце домена» на rutracker.org
[☠] Сайт не открывается
	Пробуем способ «фрагментирование заголовка» на rutracker.org
[✓] Сайт открывается
	Пробуем способ «фрагментирование заголовка, hoSt и отсутствие пробела одновременно» на rutracker.org
[✓] Сайт открывается

[!] Результат:
[⚠] Ваш провайдер подменяет DNS-записи, но не перенаправляет сторонние IPv4 DNS-серверы на свой.
 Вам поможет смена DNS, например, на Яндекс.DNS 77.88.8.8 или Google DNS 8.8.8.8 и 8.8.4.4.
[⚠] Ваш провайдер полностью блокирует доступ к HTTPS-сайтам из реестра.
[⚠] isup.me даёт неожиданные ответы или недоступен. Рекомендуем повторить тест, когда он начнёт работать. Возможно, эта версия программы устарела. Возможно (но маловероятно), что сам isup.me уже занесён в чёрный список.
[⚠] Если проигнорировать isup.me, то у вашего провайдера "полный" DPI. Он отслеживает ссылки даже внутри прокси, поэтому вам следует использовать любое шифрованное соединение, например, VPN или Tor.

**Comment by Erquint** [comment]
@Mavreak Извините за педантизм, но тема о провайдере Ростелеком, а у вас SkyNet (название то какое) — вам бы может быть оформить отдельную жалобу…

Но таки да, начните со сторонних DNS, а там видно будет.

Далее BlockCheck не очень предназначен для тестирования с запущенным GoodbyeDPI, ибо во-первых централизованно собирает статистику о видах блокировок, которая становится неверной при самостоятельной попытке обхода ограничений, а во вторых BlockCheck будет тупо врать — у меня вот сейчас он очень жалуется, что всё закрыто и не работает, когда таки из браузера всё пашет. Ну и у него какие-то очевидные проблемы с CloudFlare.

Если всё же будете впредь запускать BlockCheck, то поставляйте ему аргумент `--no-report`, хотя-бы в знак уважения автору.
Лучше тестировать пытясь в браузере зайти на блокируемые страницы, такие как:
* http://rutracker.org (http-вариант)
* https://rutracker.org (https-вариант)
* http://maxima-library.org
* https://nnmclub.to (может долго соединяться)
* https://streamable.com

После смены DNS запустите `blockcheck-0.0.9.8-windows.exe --no-report --disable-ipv6 --force-dpi-check --no-isup` и сохраняйте вывод.

**Comment by Mavreak** [comment]
@Erquint
Спасибо, буду тестить.

**Comment by ValdikSS** [comment]
Пожалуйста, обсуждайте работу программы на форуме, а не в issues (проблемах) GitHub.
Issues существуют для того, чтобы сообщать об _ошибках_ в программе, а не для обсуждения работоспособности на том или ином провайдере.

https://ntc.party/c/community-software/goodbyedpi

**Comment by Erquint** [comment]
@Figarround В терминале или шеллскрипт файле настраивайте (BAT/CMD/PS1/…).  
Каку трогать не советую.
