### ISSUE TITLE
У меня одного софт перестал работать?

### ISSUE THREAD

**Issue by TrustedPeople** [ValdikSS/GoodbyeDPI#197]
Использовал 3 метод уже как 7 месяцев и все спокойно обходилось, а сегодня вдруг перестало работать. Провайдер TTK. Кэш удалял и даже пробовал в заходить из виртуальной машины. Проверь если сможешь спасибо
![PDkEZ0O](https://user-images.githubusercontent.com/72614096/100336101-cf30d680-2fe6-11eb-9c22-627cf13afff5.png)

**Comment by Sergey7701** [comment]
Тоже самое сегодня на Ростелекоме

**Comment by Erquint** [comment]
Что за очередная сборка с ГУИ?

**Comment by ValdikSS** [comment]
Пожалуйста, обсуждайте работу программы на форуме, а не в issues (проблемах) GitHub.
Issues существуют для того, чтобы сообщать об _ошибках_ в программе, а не для обсуждения работоспособности на том или ином провайдере.

https://ntc.party/c/community-software/goodbyedpi
