### ISSUE TITLE
It's not open sites on port 8000 / 8080

### ISSUE THREAD

**Issue by ozzymanborn** [ValdikSS/GoodbyeDPI#198]
If a blocked site (mostly iptv sites using that) has a main site in 80 port but iptv (or playlist) server on 8000 or 8080 port goodbyedpi works good on 80 port site/dashboard but  " Hmmm… can't reach this page / The connection was reset ." error happens on port 8000 site.

Edit: Non blocked 8000 / 8080 sites are opening when I use goodbyedpi normally.

**Comment by ValdikSS** [comment]
Please make an provide network capture dump, here's the instruction: https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark

**Comment by ozzymanborn** [comment]
start "" goodbyedpi.exe -1 -w --port 8080 --port 8000 solves the issue thanks...
