### ISSUE TITLE
Проблема с сайтами с перенаправлением с http на https

### ISSUE THREAD

**Issue by nxrighthere** [ValdikSS/GoodbyeDPI#2]
Я заметил что сайты на которых стоит перенаправление с http на https, просто не открываются. Например http://stopgame.ru не открывается, а так https://stopgame.ru сайт нормально загружается.

**Comment by ValdikSS** [comment]
Исправлено в 0.0.4, попробуйте.

**Comment by nxrighthere** [comment]
Работает, спасибо!
