### ISSUE TITLE
Turkey (changes - Turk Telekom)

### ISSUE THREAD

**Issue by ozzymanborn** [ValdikSS/GoodbyeDPI#201]
Turk Telekom seems made changes as method 2 was working long time but suddenly method 4 was used on some sites. But in last 2-3 days method 4 is having issues also (I will send my wireshark dump to your mail.)

I tried with tunein.com

**Comment by ValdikSS** [comment]
Method 4 is for passive DPI, which drops injection. Try:

`-p -r -s --set-ttl 5`
