### ISSUE TITLE
Can you please elaborate on the steps cuz i cant do anything

### ISSUE THREAD

**Issue by waitill** [ValdikSS/GoodbyeDPI#204]
My downloaded folder doesn't have any exe file that can run (Only full of Windows Command Script and a TXT file). When I navigate into the x84_64 folder and run the goodbye dpi application it ran and shows that filter activated but in the end I still cant access the website I want.

The results after running the application:

GoodbyeDPI v0.1.6: Passive DPI blocker and Active DPI circumvention utility
https://github.com/ValdikSS/GoodbyeDPI

Block passive: 1
Fragment HTTP: 2
Fragment persistent HTTP: 2
Fragment HTTPS: 2
hoSt: 1
Host no space: 1
Additional space: 0
Mix Host: 0
HTTP AllPorts: 0
HTTP Persistent Nowait: 1
DNS redirect: 0
DNSv6 redirect: 0
Fake requests, TTL: 0
Fake requests, wrong checksum: 0

Opening filter
Filter activated!

But after this nothing happens
What should I do?

**Comment by r4sas** [comment]
Provide wireshark dumps: https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark

**Comment by ValdikSS** [comment]
Your ISP either does not use DPI.
