### ISSUE TITLE
Non-intrusive mode?

### ISSUE THREAD

**Issue by Kein** [ValdikSS/GoodbyeDPI#207]
Readme states:
> The program loads WinDivert driver which uses Windows Filtering Platform to set filters and redirect packets to the userspace. It's running as long as console window is visible and terminates when you close the window.

However, from what I an see it installs both DIRVER and SERVICE, which is intrusive. Can you add an actual mom-intrusive mode that does not install anything into the system (does not dirty it) and actually works as stated in readme (which is incorrect and misleading atm).

**Comment by ValdikSS** [comment]
The program neither installs service nor driver. The driver is automatically, but not getting unloaded after you close the program (that's a feature of WinDivert driver: it may be used not only by GoodbyeDPI and stays loaded until unloaded manually), but is it not installed to the system (it does not copy any files to the system, it will not load after reboot).
The service installation is a manual process (run .bat script), the program does not do that.
