### ISSUE TITLE
[W10] [0.0.9] The system cannot find the file specified.

### ISSUE THREAD

**Issue by Erquint** [ValdikSS/GoodbyeDPI#21]
Какой файл она ищет?

**Comment by ValdikSS** [comment]
` The driver files WinDivert32.sys or WinDivert64.sys were not found. `

**Comment by Erquint** [comment]
Пардон, пикча отклеилась:
http://i.imgur.com/fkfs3LG.png

**Comment by ValdikSS** [comment]
У вас не может загрузиться драйвер, по какой-то причине.

**Comment by Erquint** [comment]
Антивирусами не балуюсь, "стена огня" была выключена, пробовал включить, безуспешно.

**Comment by ValdikSS** [comment]
На скриншоте вы пытаетесь запустить 32-битную версию. У вас 32-битная версия Windows? Если нет, то вам нужно запускать 64-битную версию.

**Comment by Erquint** [comment]
Вы правы — промахнулся с битностью. Не предпожил, что на системные драйверы обратная совместимость может не распространяться.
Приношу свои глубочайшие извинения за потраченное на этот казус время.
