### ISSUE TITLE
Крайне сильно тормозит Youtube при использовании GoodbyeDPI

### ISSUE THREAD

**Issue by Manazius** [ValdikSS/GoodbyeDPI#210]
Привет! Сильно тормозит Youtube при использовании вашей программы. Главная страница нормально работает, а вот если куда-то дальше заходить — всё, лаги и загрузки видео нужно ждать по минуте-две. Иногда этого торможения нет и работает всё как часы, а иногда — очень сильное. 
Провайдер: Уфанет (с разблокировкой сайтов и твиттера проблем нет).
Использую режим 4_fakepacket_all_dnsredir_ttlonly.

**Comment by Glazami** [comment]
Меня больше интересует почему virustotal видит кучу вирусов, почему винда и браузер не даёт скачать тоже.

**Comment by r4sas** [comment]
> Меня больше интересует почему virustotal видит кучу вирусов, почему винда и браузер не даёт скачать тоже.

Ложный детект из-за WinDivert.

**Comment by Shionsan** [comment]
Такая же фигня, но только с видео. Есть моменты, где они просто не грузятся пока не перезапустишь GoodbyeDPI. Проблема при этом есть не только с Youtube.
Провайдер: Ростелеком северо-запад
Параметры: -p --set-ttl 5
Добавил blacklist по рекомендации с форума, но это не помогло.

**Comment by Kein** [comment]
Проект на хиатусе давно и надолго. Там на реддите кто-то линковал форк активный, но я не помню имя, см. по форками и проверяй активные

**Comment by ValdikSS** [comment]
Сделайте дамп трафика Wireshark и пришилите мне на почту.
https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by legovo** [comment]
> 
> 
> Прошу прощения. После долгих копаний в системе, оказалось, что виной была одна из настроек TCP в Windows.

Какая именно? Я тоже стокнулся с подобной проблемой. Что интересно, такое происходит только в браузерах на основе Firefox. Видимо, это из-за различий шифрования с BoringSSL в Chromium, который изначально делался под нужны Google.

**Comment by grandsilence** [comment]
@Shionsan Тоже интересно, расскажите пожалуйста, что за настройка?

**Comment by Shionsan** [comment]
@legovo  @grandsilence этой опцией оказалась: `netsh int tcp set global autotuninglevel=disabled`
Не смотря на то, что она должна выключать автоподстройку, она почему-то резала весь HTTP трафик до 1-2Мбит. Торренты при этом не ограничивались.

В итоге пришлось включить обратно `netsh int tcp set global autotuninglevel=normal`, после чего с некоторых серверов смог увидеть волшебные 30Мб/сек.

**Comment by Shionsan** [comment]
Потому что показалось, что выключение этой опции уберет ограничения. А оно их почему-то зафиксировало на 2Мбит.

**Comment by Kein** [comment]
> Посчитал, что выключение этой опции уберет все ограничения. А оно их наоборот зафиксировало на 2Мбит.

Ну так само собой:
https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/receive-window-auto-tuning-for-http

**Comment by ValdikSS** [comment]
Проверьте версию 0.1.7 с опцией `--native-frag` или `--reverse-frag`.

**Comment by ValdikSS** [comment]
Полагаю, что с рабочим `--blacklist` для TLS SNI проблема должна быть решена.
