### ISSUE TITLE
При использовании вашей программы игра call of duty warzone не может соединиться с сервером. Проверьте пожалуйста и устраните проблему. 

### ISSUE THREAD

**Issue by pecok** [ValdikSS/GoodbyeDPI#211]
**Describe the bug / Опишите проблему**
A clear and concise description of what the bug is. If the issue about software incompatibility, include your operating system version and software name/version.
Подробно опишите, в чём заключается проблема. Если проблема касается совместимости с другими программами, укажите версию вашей операционной системы, имя и версию программы.

**To Reproduce / Шаги воспроизведения проблемы**

**Expected behavior / ожидаемое поведение программы**
Подробно опишите, как вы ожидаете, чтобы программа работала.

**Actual behavior / текущее поведение программы**
Подробно опишите, что происходит с программой на текущий момент.

**Screenshots / Скриншоты**
Если необходимо, добавьте скриншоты, объясняющие проблему.

**Additional context / дополнительная информация**

**Comment by pecok** [comment]
Windows 10 x64. При запущенной программе GoodbyeDPI игра call of duty warzone не может соединиться с игровыми серверами. Что тут может быть не понятного?

**Comment by r4sas** [comment]
В том, что кто-то не умеет пользоваться поиском перед тем как создавать иссуи.
https://github.com/ValdikSS/GoodbyeDPI/issues/172

**Comment by pecok** [comment]
> В том, что кто-то не умеет пользоваться поиском перед тем как создавать иссуи.
> #172

Лучше скажи как исправить проблему если такой умный.
