### ISSUE TITLE
There are no more endpoints available from the endpoint mapper

### ISSUE THREAD

**Issue by Jorge9811** [ValdikSS/GoodbyeDPI#212]
I opened 3_all_dnsredir_hardcore.cmd and I got an error.
![Untitled5322](https://user-images.githubusercontent.com/54429803/118379071-6b0ec880-b5ae-11eb-823a-42dd4fe7146c.png)

**Comment by ValdikSS** [comment]
>EPT_S_NOT_REGISTERED | 1753 | **This error occurs when the Base Filtering Engine service has been disabled.**

https://www.reqrypt.org/windivert-doc-1.4.html
