### ISSUE TITLE
Не срабатывает опция  --blacklist "только из чёрного списка".

### ISSUE THREAD

**Issue by IgorLY** [ValdikSS/GoodbyeDPI#213]
Сайты, такие как https://tv.yandex.ru/, https://www.okmarket.ru/ и некоторые другие, перестают открываться при запущенном обходе блокировок и выдают одну и ту же ошибку ERR_CONNECTION_RESET. Ошибка связана с тем, что мне приходится использовать опцию --set-ttl для обхода ограничений 2СОМ (иначе никак). При действующем обходе без --set-ttl или отключенном сайты открываются. Складывается впечатление что GPI применят опции ко всем сайтам, не смотря на блэклист и не реагирует на указание "только из чёрного списка".
 ОС Win 8.1/64. Пуск от имени Администратора (как процесс). Браузер Хром.
С уважением, Игорь.

**Comment by ValdikSS** [comment]
Эта опция работает только для http-сайтов, а на https не оказывает влияния.

**Comment by Neurotoxin001** [comment]
Может быть стоить уточнить это в readme на главной репозитория?

Потому что в коммите https://github.com/ValdikSS/GoodbyeDPI/commit/bfed8638e58401fd725c6274e9bf65672c4f34ec это уточнено отдельно:
`Does not affect HTTPS data`, а в readme не совсем понятно.

**Comment by ValdikSS** [comment]
Будет исправлено в версии 0.1.8.
