### ISSUE TITLE
Switched from Intel CPU to AMD, GoodbyeDPI no longer works

### ISSUE THREAD

**Issue by discomfortingsounds** [ValdikSS/GoodbyeDPI#215]
No ISP change, same Windows 10 installation. Switched my motherboard (from an MSI mobo to another MSI mobo) and CPU (from Intel i5 to Ryzen 7), and GoodbyeDPI no longer does anything. 
I use the "service_install_russia_blacklist" to install the service, and it used to work for most websites on my old cpu-mobo, but now the service runs without any effect
Any idea what might be the reason for this? Maybe something related to the LAN-driver? 
Thanks in advance
Edit: Tested it with the motherboard's wi-fi now, and no luck

**Comment by r4sas** [comment]
Start it from command line and check for output.

**Comment by discomfortingsounds** [comment]
> Start it from command line and check for output.

Thanks for the reply. Would you mind elaborating how I can do that?

**Comment by r4sas** [comment]
Run one of cmd files in distribution directory, starting with number, as administrator. But remove service first. using `service_remove.cmd`

**Comment by discomfortingsounds** [comment]
I should have done more testing before opening this issue. I just tried the most hardcore method mentioned in the main page, and it worked. I will try to narrow down what works and go from there. Thank you for your help
