### ISSUE TITLE
javlibrary.com doesn't work. It was working before. 

### ISSUE THREAD

**Issue by Wonyoung1** [ValdikSS/GoodbyeDPI#220]
I reninstalled manytimes and still doesn't work. javlibrary.com was working before now i can't open without vpn. 

Please help.

**Comment by r4sas** [comment]
RTFM: https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark

**Comment by ValdikSS** [comment]
Doesn't seem to be a server-related issue. Works for me currently.
