### ISSUE TITLE
Не фильтруется HTTP заглушка

### ISSUE THREAD

**Issue by Shionsan** [ValdikSS/GoodbyeDPI#221]
goodbyedpi.exe -p --set-ttl 5

Не фильтрует HTTP редирект и заглушку (РТК, Мурманск).

Так же не помогают параметры -r -s -a -m -f -k -n и --ip-id 0.

[cap.zip](https://github.com/ValdikSS/GoodbyeDPI/files/7059383/cap.zip)

**Comment by Shionsan** [comment]
Так разве RST и редирект пакеты не должны фильтроваться, даже если оригинального ответа от сервера нет?

**Comment by ValdikSS** [comment]
Нет, redirect 307 не обрабатывается.
