### ISSUE TITLE
Service Remove does not working on windows 10.

### ISSUE THREAD

**Issue by littlesudip** [ValdikSS/GoodbyeDPI#222]
I have successfully installed goodbyedpi in my windows 10 with service_install_russia_blacklist.cmd. but now I want to remove the goodbyedpi. but the service_remove.cmd does not work. I've tried many times by running service_remove.cmd as administrator. but goodbyedpi still working is my pc. how can I remove the goodbyedpi permanently? please give a solution.

**Comment by ValdikSS** [comment]
Why do you think the service is not getting removed? What exactly you get when service_remove.cmd is ran?

**Comment by littlesudip** [comment]
Thanks for response. Some of website are blocked by my isp. But when i install goodbye DPI, it unblock all those website. So if i remove goodbyefpi, those website should be blocked as before. But whenever i run service_remove.cmd, its run without any problem but those website are still unblocked. That's why i'm  thinking goodbyedpi Didn't removed successfully. Can you help me with this issues?

**Comment by ValdikSS** [comment]
If there's no GoodbyeDPI service running and/or exist, that means it is not running.
You won't be able to move or remove the goodbyedpi.exe file in the folder where you initially installed service from if it is running. If you can remove the file, it means the service is not running.
Regarding unblocked websites, your browser or DNS resolved may have cached another (not blocked) IP address or your browser is still connected to the website in a long keep-alive session. Just restart the browser and/or system.
