### ISSUE TITLE
Can not access figma.com

### ISSUE THREAD

**Issue by farhan2077** [ValdikSS/GoodbyeDPI#223]
**Describe the bug**
Basically what the title says. I could access [https://www.figma.com](https://www.figma.com) before. But after using `goodbyedpi.exe`, I can not access it now. However I tried a vpn and then again I could access figma.
So now my question is _how to I undo the changes made by `goodbyedpi.exe`_. I have tried to run `service_remove.cmd` with admin privilege but still no luck.

**Screenshots**
![image](https://user-images.githubusercontent.com/32035481/136432780-8bb87244-74e3-47e2-a470-0260fce5593e.png)

**Comment by ValdikSS** [comment]
Doesn't seem to be fragmentation-related. Is it still not working for you?

**Comment by farhan2077** [comment]
I deleted and redownloaded GoodbyeDPI again and then it was working. Till then I haven't faced any other issue.
