### ISSUE TITLE
Goodbye DPI больше не работает

### ISSUE THREAD

**Issue by kiridu1988** [ValdikSS/GoodbyeDPI#225]
Goodbye DPI перестал работать.
Больше не заходит на заблокированные сайты.
Хотя ещё совсем недавно и Рутрекер и Яммианиме работали.

**Comment by kiridu1988** [comment]
Яммианиме заработал, а рутрекер нет.

**Comment by kiridu1988** [comment]
Wireshark не видит пакеты.

**Comment by kiridu1988** [comment]
И ещё
```
C:\Users\user>nslookup youtube.com
DNS request timed out.
    timeout was 2 seconds.
╤хЁтхЁ:  UnKnown
Address:  fe80::1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Превышено время ожидания запроса UnKnown

C:\Users\user>
```

**Comment by kiridu1988** [comment]
Сделал файлы без фильтрации и отправил ValdikSS. С фильтрацией не получается.

**Comment by ValdikSS** [comment]
Попробуйте опцию `--set-ttl`, начиная с 8, уменьшая значение параметра --set-ttl до такого значения, пока обход блокировок работает.

**Comment by kiridu1988** [comment]
Завтра попробую, сегодня я бухой, сорьки.
Не понял ток, куда эту опцию включать, в ярлык gdpi-инсталла что ли?
И какой конкретно должна быть строка тоже нипанятна.
Я же обычный пользователь, даже не продвинутый, как и большинство и то дополнительно знаю про параметры запуска, а это уже не просто.

Как писать? Вот так (свойства ярлыка): "C:\Program Files (x86)\goodbyedpi-0.1.6\service_install_russia_blacklist.cmd --set-ttl 8" ?

**Comment by ValdikSS** [comment]
Запускайте программу через `4_fakepacket_all_dnsredir.cmd`, а редактируйте его блокнотом.

**Comment by kiridu1988** [comment]
Заработало с --set-ttl 8, что дальше?

**Comment by ValdikSS** [comment]
Уменьшайте это значение на единицу, до тех пор, пока обход блокировок будет продолжать работать. Чем меньше цифра, тем лучше. Как определите эту цифру — пользуйтесь.

**Comment by kiridu1988** [comment]
А можно ли установить GDPI с этой настройкой, чтобы не приходилось каждый раз запускать вручную? Т.е. чтобы при старте ОС всё автоматически работало.

**Comment by ValdikSS** [comment]
Добавьте соответствующую строку с `--set-ttl` в `service_install_russia_blacklist.cmd`, и запустите.

**Comment by kiridu1988** [comment]
`sc start "GoodbyeDPI" --set-ttl 3` - вот так нет доступа к сайтам.
`sc start "GoodbyeDPI --set-ttl 3"` - а вот так GDPI вообще не стартует.

**Comment by kiridu1988** [comment]
`sc start "GoodbyeDPI" "--set-ttl 3"` - нет доступа к сайтам.

**Comment by kiridu1988** [comment]
`sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -1 --blacklist \"%CD%\blacklist.txt\"" --set-ttl 3 start= "auto"` - и вот так не стартует.

**Comment by ValdikSS** [comment]
> `sc start "GoodbyeDPI" "--set-ttl 3"` - нет доступа к сайтам.

Если имеется в виду, что заблокированные сайты не открываются, то увеличьте цифру в set-ttl.

**Comment by ValdikSS** [comment]
> `sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -1 --blacklist \"%CD%\blacklist.txt\"" --set-ttl 3 start= "auto"` - и вот так не стартует.

Разберитесь, почему не стартует, и поправьте так, чтобы стартовало. У меня нет Windows под рукой. Строка выглядит корректно, на первый взгляд.

**Comment by r4sas** [comment]
Так оно должно быть:
`sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -1 --set-ttl 3 --blacklist \"%CD%\blacklist.txt\"" start= "auto"`

**Comment by kiridu1988** [comment]
спс, парни, завтра попробую, сегодня я опять бухой.

**Comment by kiridu1988** [comment]
Вот так работает, правда, перезагрузку пока не делал.

```
@ECHO OFF
PUSHD "%~dp0"
set _arch=x86
IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)

echo This script should be run with administrator privileges.
echo Right click - run as administrator.
echo Press any key if you're running it as administrator.
pause
sc stop "GoodbyeDPI"
sc delete "GoodbyeDPI"
sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -1 --set-ttl 3 --blacklist \"%CD%\blacklist.txt\"" start= "auto"
sc description "GoodbyeDPI" "Passive Deep Packet Inspection blocker and Active DPI circumvention utility"
sc start "GoodbyeDPI" "-1 --set-ttl 3"

POPD
```

**Comment by kiridu1988** [comment]
Спасибо, за помощь.

**Comment by kiridu1988** [comment]
Кстати, сегодня включил комп и всё автоматом работает, как и раньше.
