### ISSUE TITLE
Не работает сайт Госуслуг

### ISSUE THREAD

**Issue by RangerRU** [ValdikSS/GoodbyeDPI#227]
GoodbyeDPI ломает работу сайта Госуслуг https://www.gosuslugi.ru/

В Google Chrome ошибка: _Не удается получить доступ к сайту Соединение сброшено_

Настройки:
```
goodbyedpi.exe -3 --blacklist blacklist.txt
GoodbyeDPI v0.1.6: Passive DPI blocker and Active DPI circumvention utility
https://github.com/ValdikSS/GoodbyeDPI

Loaded 90638 hosts from file blacklist.txt
Block passive: 1
Fragment HTTP: 0
Fragment persistent HTTP: 0
Fragment HTTPS: 40
hoSt: 1
Host no space: 1
Additional space: 0
Mix Host: 0
HTTP AllPorts: 0
HTTP Persistent Nowait: 0
DNS redirect: 0
DNSv6 redirect: 0
Fake requests, TTL: 0
Fake requests, wrong checksum: 0

Opening filter
Filter activated!
```

[gosuslugi_pcapng.zip](https://github.com/ValdikSS/GoodbyeDPI/files/7519759/gosuslugi_pcapng.zip)

**Comment by RangerRU** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/217

**Comment by RangerRU** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/217

**Comment by RangerRU** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/217

**Comment by RangerRU** [comment]
Написал в суппорт:
_По Вашему обращению заведён инцидент INC000014295852 . Пожалуйста, ожидайте._

**Comment by ValdikSS** [comment]
Проблемы с TCP-фрагментацией должны быть решены в версии GoodbyeDPI 0.1.7, опцией `--reverse-frag`.

TCP fragmentation issues should be solved in GoodbyeDPI 0.1.7, by using `--reverse-frag` option.

**Comment by RangerRU** [comment]
Спасибо. Заработало!

ТП как обычно начало мозг выносить:

> - пошаговые скриншоты воспроизведения проблемы с отображением системной даты и времени;
> - лог-браузера в формате .har по вкладкам "Network" и "Console". (ссылка на страницу с инструкцией www.gosuslugi.ru/help/faq/c-1/2770).
