### ISSUE TITLE
The connection was reset.

### ISSUE THREAD

**Issue by Shaw4543** [ValdikSS/GoodbyeDPI#229]
I have this problem when I access banned sites. (nsfwmonster.com etc,)

**Comment by Owyn** [comment]
Same here. Seems to be a DPI upgrade in Russia (Beeline)

Chrome: ERR_CONNECTION_RESET
Firefox: PR_CONNECT_RESET_ERROR

--set-ttl 7 helped (for now)

**Comment by ValdikSS** [comment]
Doesn't seem like a fragmentation issue, the website is currently working with GoodbyeDPI.
