### ISSUE TITLE
It's not working anymore.

### ISSUE THREAD

**Issue by mag339** [ValdikSS/GoodbyeDPI#230]
I was using this beautiful thing for couple of months and yesterday it just stopped working. I live in Turkey. A lot of website is blocked here. I don't really understand how this works, i don't know much about it but yesterday it stopped working. I hope you can help me. I love this app.

**Comment by octangonalo** [comment]
You should start it like this for TR;

`start "" goodbyedpi.exe -p -r -s --set-ttl 5`

and don't forget to use a dns too

**Comment by mag339** [comment]
Worked perfectly thank you!
