### ISSUE TITLE
GoodbyeDPI не работает больше на Windows10 и не позволяет обходить блокировки... 

### ISSUE THREAD

**Issue by CloudSnowPony** [ValdikSS/GoodbyeDPI#232]
Если кратко, то даже с правами администратора ничего не меняется, или меняется частично. Уже всё перепробовал в плане своих сил. Прошу помочь. Частая ошибка "Отказано в доступе: 1060"

**Comment by ValdikSS** [comment]
Если кратко — мне ничего не понятно. Следуйте шаблону сообщения о проблеме, а не удаляйте его. Опишите проблему настолько детально, насколько возможно, приложите скриншоты. Только так я смогу понять причину _вашей_ проблемы и попытаться её решить.
