### ISSUE TITLE
Не работает, начиная с версии 0.1.7

### ISSUE THREAD

**Issue by FirstGuard** [ValdikSS/GoodbyeDPI#234]
### Operating system / операционная система

Windows 8.1

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the issue / Опишите проблему

До определённого момента всё было хорошо, но после релиза версии 0.1.7 не срабатывает. Последующие версии так же не помогают

**Comment by ValdikSS** [comment]
Что конкретно не работает?
Руководствуйтесь https://valdikss.org.ru/smart-questions.html

**Comment by ValdikSS** [comment]
Нет ответа.
