### ISSUE TITLE
Goodbyedpi suddenly not working. I can't enter a lot websites...

### ISSUE THREAD

**Issue by Wonyoung99** [ValdikSS/GoodbyeDPI#237]
### Operating system / операционная система

Windows 10  21H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the issue / Опишите проблему

Goodbyedpi suddenly not working. I can't enter a lot websites... It was good until 2 day ago. Now it's complately broken. 

Please help me .

**Comment by ValdikSS** [comment]
https://ntc.party/c/community-software/goodbyedpi
