### ISSUE TITLE
Проблема с сайтом

### ISSUE THREAD

**Issue by advokat11** [ValdikSS/GoodbyeDPI#238]
### Operating system / операционная система

Windows 10 21H2 19044.1466

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the issue / Опишите проблему

Не заходит при включенном goodbyedpi режиме -5 с российским блэклистом на сайт https://ru.dotabuff.com/

**Comment by ValdikSS** [comment]
Напишите версию GoodbyeDPI и полную команду запуска

**Comment by advokat11** [comment]
> Напишите версию GoodbyeDPI и полную команду запуска

Версия последняя, в режиме -3 сайт работает. Команда из файла service install blacklist

**Comment by ValdikSS** [comment]
Сделайте дамп трафика с GoodbyeDPI и без него и пришлите файл на почту:
https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by BARUCHER777** [comment]
Доброго времени суток! Большинство треккеров не открываются, приходится их открывать через TOR Browser, DPI снова работает! Сервисы удалял и ставил заново, пробовал разные версии вашего софта, ничего не помогло решить проблему...

**Comment by kirillz** [comment]
Доброй ночи, не подтверждаю все работает у меня.

**Comment by BARUCHER777** [comment]
https://pb.wtf открывает:? rutor.info ?

**Comment by BARUCHER777** [comment]
Проблема появилась после обновления драйверов сетевой карты от интел...
![Network-Lan1](https://user-images.githubusercontent.com/18327150/150620387-f51d2ee4-6b01-4087-b5b5-0c2b68f068ae.jpg)

**Comment by advokat11** [comment]
Проблема ушла сама собой.
