### ISSUE TITLE
Не открывается protonmail.com

### ISSUE THREAD

**Issue by walkman99** [ValdikSS/GoodbyeDPI#239]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the issue / Опишите проблему

Пробовал оба варианта запуска, список обновлял, версия 0.2.1. Ростелеком.
Перестал открывать сайт: "При соединении с mail.protonmail.com произошла ошибка. PR_CONNECT_RESET_ERROR"
Через antizapret работает.

**Comment by ValdikSS** [comment]
Запускайте с дополнительным параметром `--allow-no-sni`. Если не заработает, то GoodbyeDPI не поможет.

**Comment by walkman99** [comment]
С параметром отваливается по таймауту. Ясно, буду через прокси/VPN ходить.
