### ISSUE TITLE
Error opening filter: (null)

### ISSUE THREAD

**Issue by t0int** [ValdikSS/GoodbyeDPI#240]
### Operating system / операционная система

Windows 11 Pro 21H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the issue / Опишите проблему

Program cant open the filter.

### Additional information / Дополнительная информация

GoodbyeDPI v0.2.1: Passive DPI blocker and Active DPI circumvention utility
https://github.com/ValdikSS/GoodbyeDPI

WARNING: host  is less than 3 bytes, skipping
Loaded 89322 hosts from file ..\russia-blacklist.txt
Block passive: 0
Fragment HTTP: 2
Fragment persistent HTTP: 2
Fragment HTTPS: 2
Native fragmentation (splitting): 1
Fragments sending in reverse: 1
hoSt: 0
Host no space: 0
Additional space: 0
Mix Host: 0
HTTP AllPorts: 0
HTTP Persistent Nowait: 1
DNS redirect: 0
DNSv6 redirect: 0
Allow missing SNI: 0
Fake requests, TTL: auto (fixed: 0, auto: 1-4-10, min distance: 3)
Fake requests, wrong checksum: 0
Fake requests, wrong SEQ/ACK: 0
Max payload size: 1200

Opening filter
Error opening filter: (null)

**Comment by ValdikSS** [comment]
That's strange. I'd guess you have WPF service disabled.
First of all, try the build with WinDivert 2.2.0: https://github.com/ValdikSS/GoodbyeDPI/actions/runs/1653692403

**Comment by t0int** [comment]
> That's strange. I'd guess you have WPF service disabled. First of all, try the build with WinDivert 2.2.0: https://github.com/ValdikSS/GoodbyeDPI/actions/runs/1653692403

Im using a modified windows 11. and the some of features disabled on this one.
and also that one worked its working now thanks.
