### ISSUE TITLE
Может ли "это" быть альтернативным способом обхода?

### ISSUE THREAD

**Issue by Quqas** [ValdikSS/GoodbyeDPI#241]
### Describe your feature / Опишите ваше предложение

Привет.
экспериментирую с внезапно включённой защитой провайдера (вообще не было блокировок до июля 2021) заметил что его dpi не срабатывает если заведомо неправильный порт указывать
например **http**://rutracker.org:443/ или **https**://rutracker.org:80/
получаем ошибку nginx или ERR_SSL_PROTOCOL_ERROR соответственно 
т.е. запрос доходит до самого сервака в обоих случаях.
также через telnet nginx нормально отвечает с любых заблоченных сайтов и без запущенной GoodbyeDPI
_(если писать правильно **http**://rutracker.org - то блок заглушка если без GoodbyeDPI)_

другое дело что невозможно прописать адрес **https**://rutracker.org:443/  любой браузер :443 из строки удаляет, считая излишним

отсюда вопрос, можно ли в GoodbyeDPI модифицировать запросы принудительно добавляя :443 к https и :80 к http соответственно?  
или это заведомо бессмысленно? и dpi это не прошибёт (моего прова)

**Comment by ruSauron** [comment]
:443 и :80 браузер удаляет потому, что эти порты и так используются для доступа к https и http соответственно, то есть заведомо бессмысленно.

**Comment by Quqas** [comment]
то что это дефолтные порты я, _внезапно_, знаю. другое дело что **возможно** дополнительное двоеточие с (портом) введёт в ступор dpi 
не знаю лишь как отреагируют на это сами сайты

**Comment by ValdikSS** [comment]
Если я вас правильно понял, то вы предлагаете использовать протокол HTTP на порту 443 и HTTPS на порту 80. Не сомневаюсь, что у многих провайдеров включён фильтр конкретных протоколов только на определённых портах, однако в интернете почти не бывает хостов, которые бы позволили вам отправлять запросы на нестандартные порты.

Если речь про собственный сервер, то просто используйте нестандартные порты (не обязательно <1024) для обоих протоколов.

**Comment by ValdikSS** [comment]
>можно ли в GoodbyeDPI модифицировать запросы принудительно добавляя :443 к https и :80 к http соответственно?

Поле Server Name Indication в TLS не должно содержать номер порта, согласно RFC.
Для HTTP подобное можно добавить, но не уверен, что это будет значительно отличаться от добавления точки в конце домена (эта функция уже имеется в GoodbyeDPI) — скорее всего, там, где работает указание порта, будет работать и точка. Разве что совместимость с сайтами может быть выше, в каких-то случаях.

**Comment by Quqas** [comment]
-увы способ точка в конце не работает.
-сам держу https ресурс на нестандартном :44369 - нормально работает и даже редирект с http. так что про RFC не понял (поэтому если такую функцию ввести, как-то проверять надо, а не указан ли уже другой порт в строке)

это просто предложение-предположение было, что dpi так можно обойти. хотя бы на уровне потестить

**Comment by ValdikSS** [comment]
> -увы способ точка в конце не работает.

А современные способы обхода для HTTP работают? Пробовали запустить **1_russia_blacklist_dnsredir.cmd**, как рекомендуется?


> так что про RFC не понял (поэтому если такую функцию ввести, как-то проверять надо, а не указан ли уже другой порт в строке)

Когда вы набираете `https://example.com:44369` в адресной строке, браузер подключается к `example.com` на порту `44369` и запрашивает просто `example.com` в TLS SNI, а не `example.com:44369`.
Это работает потому, что DPI вашего провайдера не отслеживает нестандартные порты. А у части провайдеров — отслеживает, и это бы не сработало.

**Comment by ValdikSS** [comment]
> хотя тот же telnet на 80 и на 443 пробивает как то и без goodbyedpi

Скорее всего потому, что telnet отправляет каждую строку в новом пакете, либо же вы набираете вручную и медленно, выходя за таймаут обработки на DPI.

**Comment by Quqas** [comment]
тогда последний вопрос, на другую тему.
есть представление почему без подключения листа с `goodbyedpi.exe -f 2 -e 2 --wrong-chksum --reverse-frag`
в хроме не работает алиэкспресс(ERR_SSL_PROTOCOL_ERROR) но работает в ie11 (по крайней мере открывается)?

может знаешь как в хроме какието настройки сменить чтоб не параноил?
