### ISSUE TITLE
I want to add and maintain a blacklist for Turkey

### ISSUE THREAD

**Issue by ODAKAB** [ValdikSS/GoodbyeDPI#243]
### Describe your feature / Опишите ваше предложение

I started to use GoodByeDPI few days ago and everything works well except it's causing issues on some websites.
I would like to maintain a blacklist for Turkey if you can include it on releases.

**Comment by ValdikSS** [comment]
Great, is there publicly available blacklist already anywhere?

**Comment by ODAKAB** [comment]
I prepared this for myself yesterday:
https://gist.githubusercontent.com/ODAKAB/e92c2a22b0390f98c90bea33a8ed516b/raw/turkey-dpi-blocked

Some websites were possible to unblock only with DNSCrypt, but this list includes websites blocked with DPI which i can access only when i use GoodByeDPI and DNSCrypt together. I'll test and add to this list as i keep browsing and notice censorship by DPI.

![image](https://user-images.githubusercontent.com/49538323/152409842-bef38b52-7e9b-4414-b4dd-f231a60ba5e8.png)

**Comment by ilkersays** [comment]
Thank you for your post but i couldn't install the list as cmd file format. Can you describe it?

**Comment by ODAKAB** [comment]
> Thank you for your post but i couldn't install the list as cmd file format. Can you describe it?

Modify existing scripts for Russia

**Comment by cohenmusic** [comment]
Done! Thank you for your help..

**Comment by ValdikSS** [comment]
@ODAKAB, could you create a repository/website/anything else with the URL where you will publish the blacklist, to make it updatable? I'll prepare the scripts and think how to integrate it with the ease of use in mind.

**Comment by ODAKAB** [comment]
If you want a repository that can be committed by public, better you own it and include multiple countries.
Otherwise gist link above already works fine.

**Comment by hellwalker31** [comment]
while i tried these, still cant enter p*rn sites as a test
