### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by Shams-Raju** [ValdikSS/GoodbyeDPI#245]
### Operating system / операционная система

Windows 11

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the issue / Опишите проблему

Goodbyedpi v0.2.1 is not working on Windows 11...

**Comment by ValdikSS** [comment]
That's not helpful, I can't understand the issue unless you provide at least some information.
http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by Shams-Raju** [comment]
> That's not helpful, I can't understand the issue unless you provide at least some information. http://www.catb.org/~esr/faqs/smart-questions.html

It does not work in Windows 11, What more information do you need? -_-

**Comment by r4sas** [comment]
At least dump, used version, windivert version.

**Comment by ValdikSS** [comment]
> It does not work in Windows 11, What more information do you need? -_-

The program works on Windows 11, I've tested it on two desktops and in VM. There are no known global compatibility issues with Windows 11.

If it doesn't work in your case, please describe what exactly does not work, how do you start the program (in which configuration and with what options), whether did it work on other OS, have you tried to debug the issue.
