### ISSUE TITLE
If run as service, "set-ttl n" or "auto-ttl a-b-c" crashes app

### ISSUE THREAD

**Issue by Vanav** [ValdikSS/GoodbyeDPI#246]
### Operating system / операционная система

Windows 11

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the issue / Опишите проблему

If I run as service command
"C:\Utils\goodbyedpi\x86_64\goodbyedpi.exe" -f 2 --set-ttl 3 --wrong-seq --max-payload
or
"C:\Utils\goodbyedpi\x86_64\goodbyedpi.exe" -f 2 --auto-ttl 1-3-3 --wrong-seq --max-payload
then service crashes. Command line (not service) works correctly. How ti run as service with this key?

### Additional information / Дополнительная информация

Fault bucket 1250341151944235227, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: goodbyedpi.exe
P2: 0.0.0.0
P3: 61cdf748
P4: goodbyedpi.exe
P5: 0.0.0.0
P6: 61cdf748
P7: c0000005
P8: 000000000000901c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f70fdd00-eb43-4e1f-96ab-c820735562bb.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.750306ef-626d-49c4-a649-8d6a84fa978b.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e58e6667-3856-4a40-a680-3e34e8da4a32.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.194880b5-1426-4666-a699-d48e59eaf627.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7212d86c-dab2-4911-92d2-fe5094e182a3.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_goodbyedpi.exe_bd656b2e8a60aee02f41f2233eedf8bb589378a_739b3904_e3d7fd3c-eed0-40d0-92be-9637a7bc18ce

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0e4fed9e-5139-4223-8327-3e05ffa446ec
Report Status: 268435456
Hashed bucket: 5cbced4eb257fc26415a1aa731b058db
Cab Guid: 0

Faulting application name: goodbyedpi.exe, version: 0.0.0.0, time stamp: 0x61cdf748
Faulting module name: goodbyedpi.exe, version: 0.0.0.0, time stamp: 0x61cdf748
Exception code: 0xc0000005
Fault offset: 0x000000000000901c
Faulting process id: 0x3f58
Faulting application start time: 0x01d81f8e12f3a40d
Faulting application path: C:\Utils\goodbyedpi\x86_64\goodbyedpi.exe
Faulting module path: C:\Utils\goodbyedpi\x86_64\goodbyedpi.exe
Report Id: 0e4fed9e-5139-4223-8327-3e05ffa446ec
Faulting package full name: 
Faulting package-relative application ID:

**Comment by ValdikSS** [comment]
Something's wrong with `--max-payload`, I'll take a look.
