### ISSUE TITLE
GoodByeDPI перестали открываться обычные сайты

### ISSUE THREAD

**Issue by Uefi1** [ValdikSS/GoodbyeDPI#248]
### Operating system / операционная система

windows 7 x64

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the issue / Опишите проблему

Собственно перестали открываться обычные сайты если GoodByeDpi запущен, а блокированные открываются началось около пары тройки недель назад исправьте пожалуйста !
Запускаю как и раньше обычным способом просто goodbyedpi-0.2.1\x86_64\goodbyedpi.exe

**Comment by ValdikSS** [comment]
Неоткрывающиеся сайты не являются _ошибкой_ программы, баг-трекер_ — не место для поиска помощи и вопросов.

С вопросами следует обращаться на форум: https://ntc.party/c/community-software/goodbyedpi/8

**Comment by Uefi1** [comment]
GitHub и репозитории в нём существуют чтобы задавать вопросы на них а не скитаться по форумам
