### ISSUE TITLE
GoodbyeDPI doesn't work with desktop apps/ping

### ISSUE THREAD

**Issue by actualdankcoder** [ValdikSS/GoodbyeDPI#249]
### Operating system / операционная система

Windows 11 10.0.22000 Build 22000

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the issue / Опишите проблему

GoodbyeDPI works perfectly in browser, but if try to ping a blocked site using command prompt

```
> ping nyaa.si

Pinging nyaa.si [2405:xxxxxxxxxxx] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
```

Same behaviour in desktop apps that make request to blocked websites, they will timeout as well

### Additional information / Дополнительная информация

Both Chrome and Windows are running on Google Public DNS, chrome works but windows ping/apps doesn't. I've tried other DNS providers but no luck

**Comment by actualdankcoder** [comment]
The launch command for the service is `goodbyedpi -2`

**Comment by ValdikSS** [comment]
Nyaa.si has blocked ICMP echo reply, that's why you don't receive the reply.
GoodbyeDPI does not handle ICMP.

**Comment by ValdikSS** [comment]
> Same behaviour in desktop apps that make request to blocked websites, they will timeout as well

It could be that only IPv4 is reachable, and in browser you have [Happy Eyeballs](https://en.wikipedia.org/wiki/Happy_Eyeballs) working while not all desktop programs support it and try to use unreachable IPv6 address. Check that. Also check DNS and make sure no hijack is performed by your ISP.
