### ISSUE TITLE
на днях перестала работать yahoo-почта с  --wrong-chksum 

### ISSUE THREAD

**Issue by Quqas** [ValdikSS/GoodbyeDPI#250]
### Operating system / операционная система

windows 7x64

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the issue / Опишите проблему

**I.** прекрасно работал 0.2.1 с -f 2 -e 2 --wrong-chksum --reverse-frag
по крайней мере все сайты которые посещаю.
и вдруг перестало пускать на яхупочту ERR_SSL_PROTOCOL_ERROR
т.е. как раньше было с госсуслугами
новые ключи запуска все перепробовал но если   --wrong-chksum  то ни в какую. понятно что на стороне сервера что-то сломали (опять же блэклист тоже помог бы - но не юзаю) так что это скорее просьба изучить, что особого на этой яхе. вдруг поможет добавить функционал.

### Additional information / Дополнительная информация

**II.** стал запускать по дефолту (-5) с почтой помогло, но выяснился 1 заблокированый сайт - перестало пускать pimpletv.ru
понять чем он отличается от других типа рутракера с точки зрения прова - не смог, выходной хоп вроде один и тот же 

стал экспериментировать с --max-payload и наобум с --max-payload 12000 стало пускать и на него, но с оговорками.
надо чётко добавлять https://pimpletv.ru - тогда открывает. (с   --wrong-chksum можно просто pimpletv.ru)  +в ie11(специально для тестов и открываю, а так всегда в хроме) не работает много блоченных сайтов но уже по https. с http норм.
+даже  -f 2 -e 2 --auto-ttl --reverse-frag --max-payload 12000 стал перебирать сайты из блэклиста, которые мне и не нужны, и далеко не все открываются, но работают  с  --wrong-chksum . т.е. пров "сломанную" чексумму не переваривает, но она же продолжает ломать некоторые сайты.

**III.** может есть какой то "научный" способ подобрать _более-лучший_  --max-payload ?  как понял, уменьшая до 120 - пров начинает блочить даже то что с 1200 пускает, а с 12000 начал пускать на нужный сайт, но опять же не на тольколишьвсе из блэклиста

**Comment by Quqas** [comment]
вобщем небольшие уточнения - очень трудно дебажить разные ключи из-за склонности винды и хрома к кэшированию не пойми чего, тока перезагрузка даёт ясную картину
остановился на  -f 2 -e 2 --auto-ttl --reverse-frag и хром с ними открывает то что мне надо и yahoo не бажит, но с оговорками же
1. таки надо указывать https там где с --wrong-chksum не надо было, работал редирект. а щас без указания ни заглушка прова - ни страницы сайта, ни ошибки внятной, тупняк непонятный.
2. но даже с https всё равно не всё из блэклиста открывается. благо оно и не нужно, но для теста неприятно. с --wrong-chksum же открывает, но ломает яху и ещё другие некоторые
3. и главный уже мой косяк в дебаге ERR_SSL_PROTOCOL_ERROR с --wrong-chksum на mail.yahoo.com это только в хроме началось недавно, в ie11 таки открывает и с --wrong-chksum. понять что хрому не нравится - не в состоянии.

**Comment by Quqas** [comment]
update2: в итоге так и вернулся к -f 2 -e 2 --wrong-chksum --reverse-frag забив на яху. тем более что тут хромовый тупняк неизлечимый - в ie11 ошибки нет

любые другие комбинации ломают те или иные ресурсы каждый раз по всякому. даже --auto-ttl  стал в хроме выдавать ssl error на видеохостингах вроде stream.voidboost.cc. а я то страдал - почему половина не грузится вовсе и никакой не отрыть в fullhd... но опять же это хром моросит а ie норм

**Comment by ValdikSS** [comment]
> что особого на этой яхе

На IP-адресе `87.248.119.251` домена `mail.yahoo.com` отключена валидация контрольной суммы TCP, из-за чего поддельный пакет, который должен отбрасываться, принимается сервером.
На IP-адресе `87.248.116.11` валидация работает, можете добавить этот адрес в hosts, и проблема будет решена.

> но выяснился 1 заблокированый сайт - перестало пускать pimpletv.ru
> надо чётко добавлять https://pimpletv.ru - тогда открывает

Полагаю, сайт установил вам большие cookie, и вы используете `--max-payload` при этом. Проблема известная, придумаю, как исправить. Пока можете отключить (вернее, не указывать) `--max-payload`.

> в ie11(специально для тестов и открываю, а так всегда в хроме) не работает много блоченных сайтов но уже по https

Если не ошибаюсь, IE11 устанавливает TLS-соединение чуть-чуть не так, как все остальные браузеры и программы, не думаю, что GoodbyeDPI с ним вообще работает — это объясняет, почему у вас yahoo в IE открывается. Он уже почти не поддерживается Microsoft.

> есть какой то "научный" способ подобрать _более-лучший_ --max-payload ?

Смысла использовать что-то отличное от 1200-1400 совсем не много. Эта опция нужна только для пропуска обработки больших пакетов, для уменьшения нагрузки на процессор.

Наиболее надёжный вариант — задать TTL поддельного пакета через `--set-ttl` вручную. Чем меньше, тем лучше. Также используйте `--blacklist`.

Не устану повторять: пожалуйста, задавайте вопросы на форуме. Github issues не предназначены для настройки программы.
