### ISSUE TITLE
Doesn't work in Russia for the twitter page.

### ISSUE THREAD

**Issue by kp6ic** [ValdikSS/GoodbyeDPI#251]
### Describe your feature / Опишите ваше предложение

Could you fix it in the new version? Thx.

**Comment by ValdikSS** [comment]
Кратко:

* Скачайте [GoodbyeDPI 36](https://github.com/ValdikSS/GoodbyeDPI/releases), распауйте архив;
* Запустите 0_russia_update_blacklist_file.cmd, дождитесь закрытия окна;
* Запустите 1_russia_blacklist_dnsredir.cmd, сверните (но не закрывайте) окно;
* Пользуйтесь интернетом.

Если не заработает, обращайтесь вот сюда: https://ntc.party/t/facebook-twitter-goodbyedpi/1741

**Comment by Neurotoxin001** [comment]
Там ещё такой домен есть:
`https://abs-0.twimg.com/emoji/v2/svg/26aa.svg`

**Comment by ValdikSS** [comment]
@Neurotoxin001, этот домен уже присутствует в листе. Попробуйте использовать опцию `--set-ttl` или поменять параметры `--auto-ttl`. Пожалуйста, не используйте issues для вопросов.

**Comment by Neurotoxin001** [comment]
С `set-ttl` работает, но я не указал никакую цифру, т.к не знаю, какую указывать. А на главной в инструкции не написано дефолтное значение для этой команды.

**Comment by ValdikSS** [comment]
> С `set-ttl` работает, но я не указал никакую цифру, т.к не знаю, какую указывать. А на главной в инструкции не написано дефолтное значение для этой команды.

Спасибо, вы нашли баг в программе: "0" (ноль) в доменах обрабатывается неправильно. Добавьте опцию `--allow-no-sni` в конец 1_russia_blacklist_dnsredir.cmd, с ней заработает.

**Comment by ValdikSS** [comment]
В сети **Билайн** Москва (Корбина), AS8402, наблюдается блокировка отдельных IP-адресов Твиттера.
Чтобы обойти, добавьте следующее в файл hosts (C:\Windows\System32\drivers\etc\hosts):

```
104.244.42.3  twitter.com www.twitter.com
104.244.42.66 api.twitter.com
104.244.42.5  t.co
```

**Comment by Owyn** [comment]
Тоже самое с Instragram на Beeline, у него можно так же ip незаблокированные прописать?

**Comment by Neurotoxin001** [comment]
Из-под эстонских\латвийских\литовских VPN (Surfshark) твиттер не открывается с запущенным goodbyedpi (с -5 и --blacklist), пишет ERR_SSL_PROTOCOL_ERROR. Блеклист обновлял.

![image](https://github.com/ValdikSS/GoodbyeDPI/assets/39812401/c63e9bef-8aa9-4500-936d-c7349cc19c77)

![image](https://github.com/ValdikSS/GoodbyeDPI/assets/39812401/79b729c1-525b-401b-bc4f-d3b9d0159e03)

**Comment by r4sas** [comment]
А зачем запускать GDPI с внешним VPN?

**Comment by Neurotoxin001** [comment]
> А зачем запускать GDPI с внешним VPN?

Я знал, что об этом спросят. Просто постоянно включать\выключать впн\гудбайдпи — лень, поэтому гудбайдпи запущен всегда, а впн — запускаю иногда, когда нужен. Твиттер с гудбайдпи работает плохо (даже с прописанными в hosts айпишниками). Поэтому так.

Но почему только с впн из этих стран проблема — загадка.

**Comment by ValdikSS** [comment]
От @BitModding:

# Доступ в Твиттер(Икс) в 2024 году - Россия
Доступ в Твиттер(X) с использованием GoodBye-DPI. Проверено на провайдере Билайн. Январь 2024  
!!! НЕ ГАРАНТИРУЮ РАБОТУ НА ДРУГИХ ОПЕРАТОРАХ !!!

Вставить в файл hosts:

```
#GoodBye-DPI --- Twitter(X) --- Russia
#Актуальный список-лист для обхода блокировок Twitter(X) с GoodBye-DPI.
104.244.42.1 twitter.com
104.244.42.2 api.twitter.com
104.244.42.3 twitter.com www.twitter.com 
104.244.42.4 api.tweetdeck.com
104.244.42.5 t.co
104.244.42.6 mobile.twitter.com
104.244.42.7 support.twitter.com
104.244.42.8 syndication.twitter.com
104.244.42.9 abs-0.twimg.com
104.244.42.11 upload.twitter.com
104.244.42.66 api.twitter.com 
104.244.43.3 abs-0.twimg.com
151.101.84.157 static.ads-twitter.com
```

Единственное, что не работает - так это эмодзи по адресу, указанному снизу  
`104.244.43.131 abs-0.twimg.com`

**Comment by Neurotoxin001** [comment]
> 104.244.42.1 twitter.com

Из-за этого вообще открываться перестало. Таймаут. Билайн. А так в целом ничего не изменилось по сравнению с https://github.com/ValdikSS/GoodbyeDPI/issues/251#issuecomment-1066114798

**Comment by JAKill02** [comment]
а нельзя ли выкладывать тут (допустим в отдельной теме) обновлённый "russia-blacklist.txt" ? 
его ОООООООООООЧЕНЬ сложно обновить через "0_russia_update_blacklist_file.cmd"
чаще всего процесс заканчивается этим. (он очень долго думает, и нихрена не скачивает)
![изображение](https://github.com/ValdikSS/GoodbyeDPI/assets/55640282/824909ec-efad-4b4d-9682-84840ad437d0)

может повезти где-то раз в месяц - два, и это если очень сильно повезёт.
этого явно недостаточно для актуального использования.
(в тех редких случаях когда обновление всё таки произошло, окно даже и не думает закрываться "как указано в описании" - всё ручками)

**Comment by Owyn** [comment]
> Единственное, что не работает - так это эмодзи по адресу

videos.twimg.com почему-то 404 отдаёт вместо видео твиттерских очень часто и твиттер бесконечно перезагружает их почти вешая весь браузер
![image](https://github.com/ValdikSS/GoodbyeDPI/assets/1309656/487089a4-9e30-4c3f-80fd-3d51a9312ce5)

через ТОР работает видео:
![image](https://github.com/ValdikSS/GoodbyeDPI/assets/1309656/5f1de214-75c6-452d-bf12-322c83799b65)


Билайн

**Comment by sergeevabc** [comment]
> @JAKill02
а нельзя ли выкладывать тут (допустим в отдельной теме) обновлённый "russia-blacklist.txt" ?

У Антизапрета [сменили](https://ntc.party/t/%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B0%D0%BD%D1%82%D0%B8%D0%B7%D0%B0%D0%BF%D1%80%D0%B5%D1%82%D0%B0/4269) порт.

В файле `0_russia_update_blacklist_file.cmd` замените строчку с командой bits на
``` console
powershell -c "(New-Object System.Net.WebClient).DownloadFile('https://antizapret.prostovpn.org:8443/domains-export.txt', '%CD%\russia-blacklist.txt')"
```

**Comment by JAKill02** [comment]
> У Антизапрета [сменили](https://ntc.party/t/%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B0%D0%BD%D1%82%D0%B8%D0%B7%D0%B0%D0%BF%D1%80%D0%B5%D1%82%D0%B0/4269) порт.
> 
> В файле `0_russia_update_blacklist_file.cmd` замените строчку с командой bits на
> 
> ```
> powershell -c "(New-Object System.Net.WebClient).DownloadFile('https://antizapret.prostovpn.org:8443/domains-export.txt', '%CD%\russia-blacklist.txt')"
> ```

с этой вашей строчкой **не всё так просто**. у меня на компе всё обновляет хорошо, на другом компе заменил ей родную, и при попытке обновления она просто удаляет "russia-blacklist.txt" и всё, **приехали**. 
думал накосячил со строкой, скопировал туда свой файл которым обновляюсь сам, эффект тот же самый, - при попытке  обновления в самом конце очень быстро появляюется какая-то красная надпись и файл удаляется.

**и вообще, почему молчит сам разработчик? если знает что у людей ЕСТЬ проблемы с обновлением "russia-blacklist.txt" и САМ не предоставляет советов или способов для его обновления.** 
_при этом не обновляя версию программы и встроенные средства обновления. "russia-blacklist.txt"_

**Comment by JAKill02** [comment]
>>@sergeevabc 
> >У Антизапрета [сменили](https://ntc.party/t/%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B0%D0%BD%D1%82%D0%B8%D0%B7%D0%B0%D0%BF%D1%80%D0%B5%D1%82%D0%B0/4269) порт.
> 
> В файле `0_russia_update_blacklist_file.cmd` замените строчку с командой bits на
> 
> ```
> powershell -c "(New-Object System.Net.WebClient).DownloadFile('https://antizapret.prostovpn.org:8443/domains-export.txt', '%CD%\russia-blacklist.txt')"
> ```

с этой вашей строчкой **не всё так просто**. у меня на компе всё обновляет хорошо, на другом компе заменил ей родную, и при попытке обновления она просто удаляет "russia-blacklist.txt" и всё, **приехали.**
думал накосячил со строкой, скопировал туда свой файл которым обновляюсь сам, эффект тот же самый, - при попытке обновления в самом конце очень быстро появляюется какая-то красная надпись и файл удаляется.

**и вообще, почему молчит сам разработчик? если знает что у людей ЕСТЬ проблемы с обновлением "russia-blacklist.txt" и САМ не предоставляет советов или способов для его обновления.**
_при этом не обновляя версию программы и встроенные средства обновления. "russia-blacklist.txt"_

**Comment by sergeevabc** [comment]
@JAKill02, адрес же опять сменили, [следите за новостями](https://ntc.party/c/antizapret-prostovpn-org/5).
Теперь надо так:
``` console
powershell -c "(New-Object System.Net.WebClient).DownloadFile('https://p.thenewone.lol:8443/domains-export.txt', 'russia-blacklist.txt')"
```

**Comment by JAKill02** [comment]
> @sergeevabc, адрес же опять сменили, [следите за новостями](https://ntc.party/c/antizapret-prostovpn-org/5).
> 
> Теперь надо так:
> 
> ```
> powershell -c "(New-Object System.Net.WebClient).DownloadFile('https://p.thenewone.lol:8443/domains-export.txt', '%CD%\russia-blacklist.txt')"
> ```
-----------------
вообще ничего не поменялось, при обновлении так же просто удаляется файл "russia-blacklist.txt" с той же ошибкой красным в теле окна.

зато, я смог получить точно такую же ошибку и точно такую же реакцию с удалением файла, когда попытался обновить файл без подключённого к сетевой карте сетевого шнура (то есть, без доступа к инету)  (дописал pause в тело чтобы не ловить момент на видеозахватах.). 
![upd_ !!!!](https://github.com/ValdikSS/GoodbyeDPI/assets/55640282/d0598b53-ae87-4ed5-bc9a-23735c1cda0d)

наверное кого-то это должно будет навести на какие-то мысли.  от отличающихся на драйверном уровне приципов работы сетевых карт, до закрытых у большинства провайдеров (если у вас нет выделенного IP), портов, которые приоткрываются только в случае прохождения по ним хоть какого-то трафика, да и-то я бы сказал, условно. я в этом не спец, сужу по работе торрент клиентов.

**Comment by JAKill02** [comment]
кароче, ребят, чем вы умнее, тем больше от вас текста и меньше толка.
я сделаю умнее (**goodbyedpi - russia-blacklist (updatable)**): https://drive.google.com/drive/folders/1Ukve1TJErz0lh4jgrURGvXXjs-m9Q8KD
пока сам смогу обновлять этот файл, время от времени буду загружать сюда более новую версию.

**Comment by sergeevabc** [comment]
@JAKill02

PowerShell это программа, которая среди прочего умеет получать файлы из сети. Вместо неё можно использовать другие программы для получения файлов (например, Wget, Curl, Aria2) — просто PowerShell уже присутствует в Windows, поэтому в батниках зачастую используют именно её. Чтобы убедиться, что она работает исправно, можно получить нейтральный файл с адреса, который никем официально не блокируется в России.

``` console
powershell -c "(New-Object System.Net.WebClient).DownloadFile('https://www.yandex.ru/robots.txt', 'robots.txt')"
```

Если robots.txt удалось получить, а с получением domains-export.txt возникает проблема, то либо по указанному адресу нет файла, либо к этому адресу невозможно подключиться. PowerShell при сбое пытается объяснить, что именно помешало выполнить команду — достаточно вставить текст сообщения об ошибке в поисковик и узнаете много интересного, нежели нервничать, устанавливая .Net Framework, настраивая файрволл и обвиняя кого-то. В частности, на обоих скриншотах говорится о невозможности подключиться к адресу. В первом случае это следствие блокировки домена prostovpn.org [Роскомназдором](https://eais.rkn.gov.ru/) от 06.03.2024, а во втором случае используемый DNS сервер не айпишник домена p.thenewone.lol.  Перепроверить это можно следующим образом.

``` console
nslookup p.thenewone.lol

p.thenewone.lol
195.123.208.131

nslookup p.thenewone.lol 77.88.8.8

p.thenewone.lol
195.123.208.131
```

Первая команда пытается узнать айпишник домена, используя DNS сервер, указанный в настройках текущего сетевого соединения. Вторая команда использует другой DNS сервер (здесь это Yandex). В обоих случаях должны быть видны айпишники. Если айпишник видно только во втором случае или не видно вовсе, то пора менять DNS сервер или даже звонить провайдеру. А на столичных провайдерах Акадо, МГТС и Ростелеком всё это работает.

**Comment by JAKill02** [comment]
> @sergeevabc

robots.txt получает без проблем,

проверки проходит
![gd01](https://github.com/ValdikSS/GoodbyeDPI/assets/55640282/4608eaa2-e4ab-41e0-aed9-e0b33bdedc17)
![gd02](https://github.com/ValdikSS/GoodbyeDPI/assets/55640282/b03eed03-4239-4ab2-952c-000b9a8e7c06)

сервак пингуется, хоть и стабильно нестабильно.
![gd03](https://github.com/ValdikSS/GoodbyeDPI/assets/55640282/d8fc36fc-9e2f-422c-9ad9-87a447da305b)
![gd04](https://github.com/ValdikSS/GoodbyeDPI/assets/55640282/fb504424-6118-4529-8c22-c376ac25b1ec)

с прочими сайтами таких проблем нет.
![gd05](https://github.com/ValdikSS/GoodbyeDPI/assets/55640282/49ef750b-b211-4005-9a79-780d0d5f8ed5)
![gd06](https://github.com/ValdikSS/GoodbyeDPI/assets/55640282/e760e7ac-ccf5-448d-b48b-2ed6b340f140)

отмечу опять таки, у нас один и тот же провайдер  "IP Home", один и тот же район, одна и та же винда.

какие ещё идеи будут?

**Comment by Alexisback** [comment]
This work, script powershell 
```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Invoke-WebRequest -Uri 'https://antizapret.prostovpn.org:8443/domains-export.txt' -OutFile "$PWD\russia-blacklist.txt"
```

**Comment by sergeevabc** [comment]
> Какие ещё идеи будут?

* Файл https://p.thenewone.lol:8443/domains-export.txt открывается в браузере?

  * Если да, то какой браузер и какая версия?

* Команда `powershell -c "irm https://p.thenewone.lol:8443/domains-export.txt -outfile russia-blacklist.txt"` скачивает файл?

  * Если нет, то какая версия PowerShell? Это можно посмотреть командой `powershell -c "$PSVersionTable"`

Соответственно, если браузер открывает файл, но PowerShell его почему-то не скачивает, то можно либо поковырять PowerShell, либо заменить его на другую программу. Например, [Busybox](https://frippery.org/busybox/#downloads).

``` console
busybox.exe wget https://p.thenewone.lol:8443/domains-export.txt -O domains-export.txt
```

**Comment by JAKill02** [comment]
@Alexisback 
> This work, script powershell

Sorry, we didn't understand where to put this XD
it doesn't work in CMD/BAT

---------------
@sergeevabc

адрес с текстовиком https://p.thenewone.lol:8443/domains-export.txt спокойно открывается без каких любо ухищрений и у меня 
![FFX 15](https://github.com/ValdikSS/GoodbyeDPI/assets/55640282/ffdd983b-e12c-40bc-bb7b-38ba34177675)
![IE 11](https://github.com/ValdikSS/GoodbyeDPI/assets/55640282/ee1a9f6b-6db3-442b-b1bd-e8653c758226)


и на том компе.
![z02](https://github.com/ValdikSS/GoodbyeDPI/assets/55640282/1ecd423c-2329-4f30-91a1-0a69ac164035)
![z01](https://github.com/ValdikSS/GoodbyeDPI/assets/55640282/e56d0a1b-c1ed-4883-b393-fb1577ec01ff)

-------------
> Команда `powershell -c "irm https://p.thenewone.lol:8443/domains-export.txt -outfile russia-blacklist.txt" `скачивает файл?

![x01](https://github.com/ValdikSS/GoodbyeDPI/assets/55640282/750fda5d-5a0f-4f64-9f6d-3eb2f022f242)


- **нет**. не у меня, не там.
-------
> А если удлинить изначальную команду, тогда что?
` powershell -c "$Protocol = [Enum]::ToObject([System.Net.SecurityProtocolType], 3072); [System.Net.ServicePointManager]::SecurityProtocol = $Protocol; (New-Object System.Net.WebClient).DownloadFile('https://antizapret.prostovpn.org:8443/domains-export.txt', 'russia-blacklist.txt')"`

-  этот вариант **работает** и у меня и на **том** компе.
-------

> Соответственно, если браузер открывает файл, но PowerShell почему-то не скачивает его, то можно либо дальше ковырять PowerShell, либо воспользоваться другой программой с функцией получения файлов. Например, [BusyBox](https://frippery.org/busybox/#downloads).

```
busybox.exe wget https://p.thenewone.lol:8443/domains-export.txt -O russia-blacklist.txt

Connecting to p.thenewone.lol:8443 (195.123.208.131:8443)
saving to 'russia-blacklist.txt'
russia-blacklist.txt 100% |********************************************************************************| 2105k  0:00:00 ETA 'russia-blacklist.txt' saved
```
- с закинутым к корень папки **busybox.exe** откуда стартует батник, **работает**, но зачем-то открывает скачанный файл, и закрывается вместе с закрытием  .txt  файла
![z03](https://github.com/ValdikSS/GoodbyeDPI/assets/55640282/afb7f471-da98-4f8e-a9d7-963701ba7bd2)
**но свою задачу выполняет одинаково и на обоих системах.**

**Comment by sergeevabc** [comment]
> > А если удлинить изначальную команду, тогда что?
> > ` powershell -c "$Protocol = [Enum]::ToObject([System.Net.SecurityProtocolType], 3072); [System.Net.ServicePointManager]::SecurityProtocol = $Protocol; (New-Object System.Net.WebClient).DownloadFile('https://antizapret.prostovpn.org:8443/domains-export.txt', 'russia-blacklist.txt')"`
> 
> * этот вариант **работает** и у меня и на **том** компе.

Вот используйте эту команду тогда. Разве что `'russia-blacklist.txt'` можно заменить _в батнике_ на `'%CD%\russia-blacklist.txt'`. А в свете того, что команда с irm выдала ошибку, у вас очень старый PowerShell, но это дело наживное.

**Comment by JAKill02** [comment]
@sergeevabc

> Вот используйте эту команду тогда. Разве что `'russia-blacklist.txt'` можно заменить _в батнике_ на `'%CD%\russia-blacklist.txt'`. А в свете того, что команда с _irm_ выдала ошибку, у вас древний PowerShell, но это дело наживное.

ок
`powershell -c "$Protocol = [Enum]::ToObject([System.Net.SecurityProtocolType], 3072); [System.Net.ServicePointManager]::SecurityProtocol = $Protocol; (New-Object System.Net.WebClient).DownloadFile('https://antizapret.prostovpn.org:8443/domains-export.txt', '%CD%\russia-blacklist.txt')"`

самое главное чтобы это работало у всех, вне зависимости от древности.
**спасибо**.

**Comment by Vl1dimir** [comment]
Судя по всему афтар давно уже умер и не занимается этим всем. Сегодня нихрена не работает, всё перепробовал уже. Ф топку

**Comment by recoil24** [comment]
> Судя по всему афтар давно уже умер и не занимается этим всем. Сегодня нихрена не работает, всё перепробовал уже. Ф топку

Да, есть такой момент... однако буквально в июне всё работало идеально.

**Comment by Al3xanderMakunin** [comment]
> От @BitModding:
> 
> # Доступ в Твиттер(Икс) в 2024 году - Россия
> Доступ в Твиттер(X) с использованием GoodBye-DPI. Проверено на провайдере Билайн. Январь 2024 !!! НЕ ГАРАНТИРУЮ РАБОТУ НА ДРУГИХ ОПЕРАТОРАХ !!!
> 
> Вставить в файл hosts:
> 
> ```
> #GoodBye-DPI --- Twitter(X) --- Russia
> #Актуальный список-лист для обхода блокировок Twitter(X) с GoodBye-DPI.
> 104.244.42.1 twitter.com
> 104.244.42.2 api.twitter.com
> 104.244.42.3 twitter.com www.twitter.com 
> 104.244.42.4 api.tweetdeck.com
> 104.244.42.5 t.co
> 104.244.42.6 mobile.twitter.com
> 104.244.42.7 support.twitter.com
> 104.244.42.8 syndication.twitter.com
> 104.244.42.9 abs-0.twimg.com
> 104.244.42.11 upload.twitter.com
> 104.244.42.66 api.twitter.com 
> 104.244.43.3 abs-0.twimg.com
> 151.101.84.157 static.ads-twitter.com
> ```
> 
> Единственное, что не работает - так это эмодзи по адресу, указанному снизу `104.244.43.131 abs-0.twimg.com`
> 
> # Доступ в Instagram в 2024 году - Россия
> Кому надо для Instagram, то вот снизу, вставить в Hosts:
> 
> ```
> #Актуальный список-лист для обхода блокировок Instagram с GoodBye-DPI
> 157.240.245.174 instagram.com www.instagram.com graph.instagram.com i.instagram.com static.cdninstagram.com scontent.cdninstagram.com
> 31.13.81.52 scontent-arn2-1.cdninstagram.com
> ```

МегаФон.
macOS.
Spoof-DPI.
Не работает.

**Comment by 4Sol** [comment]
+1 не работает твиттер
ничего не помогает
последня версия GBPDI

**Comment by kogkodeniska** [comment]
2 января 2025:
Инстаграм грузит все страницы, но не грузит фотографии и видео.
![image](https://github.com/user-attachments/assets/0c6c5e49-b72c-4c6e-8460-b2151b69edda)
С Твиттером ситуация по хуже
![image](https://github.com/user-attachments/assets/49a45b61-fad1-478c-af6a-5cdf2e05bfc4)

**Comment by kogkodeniska** [comment]
> Инстаграм грузит все страницы, но не грузит фотографии и видео. ![image](https://private-user-images.githubusercontent.com/187298212/399788586-0c6c5e49-b72c-4c6e-8460-b2151b69edda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4NDYxMzQsIm5iZiI6MTczNTg0NTgzNCwicGF0aCI6Ii8xODcyOTgyMTIvMzk5Nzg4NTg2LTBjNmM1ZTQ5LWI3MmMtNGM2ZS04NDYwLWIyMTUxYjY5ZWRkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQxOTIzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODdhMGJmODA1NTk0NDMxNmI1ZmM3MmY1NmIzYjhmZmExOGZjZGY3MjllYjBjZWZmNDU4MmY1MzI1OGE1ZTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2hoJeAgbRaTnibJhIZ04ijOguYRPIvZqhrp2-llJH2s) С Твиттером ситуация по хуже ![image](https://private-user-images.githubusercontent.com/187298212/399788714-49a45b61-fad1-478c-af6a-5cdf2e05bfc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4NDYxMzQsIm5iZiI6MTczNTg0NTgzNCwicGF0aCI6Ii8xODcyOTgyMTIvMzk5Nzg4NzE0LTQ5YTQ1YjYxLWZhZDEtNDc4Yy1hZjZhLTVjZGYyZTA1YmZjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQxOTIzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGU1NjEzODZlNGQ0YzdhNDljMzA0NGVjMThkMDkxZDAzNDU4NGY1MGM3NzI4YzMwNDFhOGVmM2MwOGZjNzg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BK4QCATX8foFnBnDKqlC63zb1bFLUno8Jq9tdb5caTU)

Сравнение с ВПН`ом:
![image](https://github.com/user-attachments/assets/1df344f6-22d0-44f6-bcfc-c605e871cb27)

**Comment by kogkodeniska** [comment]
Заработала Инста после рестарта пк
![image](https://github.com/user-attachments/assets/844da421-68b6-412f-82ec-e7ac220d4959)

Твиттер по прежнему лежит...
![image](https://github.com/user-attachments/assets/3293c911-7472-4f41-a235-731b2cf0cf2f)

**Comment by casshh87** [comment]
Где находится файл Hosts? У меня его нет
