### ISSUE TITLE
Error opening filter: Access is denied

### ISSUE THREAD

**Issue by ykpon** [ValdikSS/GoodbyeDPI#252]
### Operating system / операционная система

Windows 11 Pro 21H2 22000.527

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the issue / Опишите проблему

При запуске программы вручную без параметров либо через 1_russia_blacklist_dnsredir.cmd получаю одну и ту же ошибку.
Запускаю от имени администратора.
![](https://i.imgur.com/AKbvrEq.png)

**Comment by ValdikSS** [comment]
Смотрите системный журнал ОС, в нём должны быть подробности. Скорее всего, блокируется загрузка драйвера WinDivert.

**Comment by ykpon** [comment]
> Смотрите системный журнал ОС, в нём должны быть подробности. Скорее всего, блокируется загрузка драйвера WinDivert.

Да, так и есть, спасибо. Буду думать как исправить. Пока ни в какую не хочет заводиться.

**Comment by ValdikSS** [comment]
Попробуйте версию с обновлённой версией WinDivert 2.2.0, с ней работает?
https://github.com/ValdikSS/GoodbyeDPI/actions/runs/1653692403

**Comment by ykpon** [comment]
Нет, ошибка такая же в журнале Windows
> Сбой при запуске службы "WinDivert" из-за ошибки 
Отказано в доступе.

Предыдущую версию драйвера предварительно удалил
> sc delete windivert

Удаление прошло успешно.

**Comment by ValdikSS** [comment]
Возможно, у вас установлена какая-то защита от загрузки драйверов или отключёны важные сервисы. Если passthru.exe из https://www.reqrypt.org/download/WinDivert-2.2.0-A.zip, https://www.reqrypt.org/download/WinDivert-2.2.0-B.zip и https://www.reqrypt.org/download/WinDivert-2.2.0-C.zip у вас также не запускается, то проблема не в GoodbyeDPI/WinDivert, а в вашей системе или настройках.

**Comment by ykpon** [comment]
Так и есть, не запускаются с теми же ошибками.

**Comment by ValdikSS** [comment]
Полагаю, у вас отключены какие-то важные службы или другие компоненты, из-за чего драйвер не запускается. Если у вас даже passthru.exe не запускается, то на стороне GoodbyeDPI с этим ничего не сделать, пишите в багтрекер WinDivert: https://github.com/basil00/Divert/issues
Автор поможет вам продиагностировать и решить проблему.
