### ISSUE TITLE
Strange behavior with simplewall

### ISSUE THREAD

**Issue by FreePlague** [ValdikSS/GoodbyeDPI#257]
### Operating system / операционная система

Windows 7 x64

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the issue / Опишите проблему

GoodbyeDPI v0.2.1+ simplewall v3.6.1
С параметром -5 DPI обходится, то есть GoodbyeDPI в принципе работает.

Две проблемы этой связки:
1. simplewall это WPF фаерволл. Если процессу System (C:\Windows\system32\ntoskrnl.exe) не дать доступ в Интернет, то ни один сайт не работает, в логе simplewall видно, что System начинает инициировать все соединения, а не только из списка GoodbyeDPI. Получается путь 2b на схеме архитектуры [WinDivert ](https://github.com/basil00/Divert) всё равно перепосылает пакеты от системы даже для сайтов не из списка. По идее GoodbyeDPI не должен никак влиять на соединения с сайтами не из списка.
2. Даже если бы без разрешения System доступа в сеть, не работали только сайты из списка, всё равно для доступа к этим сайтам нужно System открыть доступ в сеть, чего делать не хочется (обновления, телеметрия и прочее).

Действительно ли так или только у меня? На Windows 10 будет также?

**Comment by ValdikSS** [comment]
Github issues не предназначены для вопросов. Пожалуйста, задавайте вопросы по программе на https://ntc.party/c/community-software/goodbyedpi.
