### ISSUE TITLE
auto-ttl не хочет быть auto?

### ISSUE THREAD

**Issue by Owyn** [ValdikSS/GoodbyeDPI#258]
### Operating system / операционная система

Win10 21H1

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

> некорректная обработка сетевых пакетов

При стандартном `auto-ttl 1-4-8` сайты всё так же бывают не открываются (CONNECTION_RESET_BY_PEER или как-то так - блок),

до этого вручную подбирал ttl - нужен 7 чтоб работало, на 8 не хочет, но попробовал стандартные современные режимы авто - чтот они автоматом 7 не ставят чтоб сайты открывались?

поставил  `auto-ttl 1-4-7` и все сайты сразу начали открываться, видимо режим `auto-ttl` сперва пробует правое самое значение и потом уменьшает когда надо? Но похоже он не понимает что надо уменьшать и этого не делает и поэтому на `auto-ttl 1-4-8`  просто остаётся 8ка и сайты не открывает?

### Additional information / Дополнительная информация

Билайн проводной

**Comment by ValdikSS** [comment]
Стандартные настройки: `--auto-ttl 1-4-10`, `--min-ttl 3`.
`auto-ttl` и `min-ttl` устроены достаточно сложно, алгоритм следующий:

1. Запоминается TTL входящего пакета SYN-ACK (первого пакета-ответа от сервера)
2. Высчитывается «дистанция» (разность) в TTL до сервера, полагая, что TTL один из стандартных: либо 64, либо 128.
3. Если дистанция меньше первого параметра auto-ttl (1), или меньше `--min-ttl`, то обработка пакета прекращается, фиктивный пакет не высылается. Это нужно для сохранения работоспособности локальных и провайдерских сайтов, которые расположены очень «близко».
4. Рассчитывается TTL фиктивного пакета: дистанция - второй параметр auto-ttl (4).
5. Если получившийся TTL меньше второго параметра auto-ttl (4), то применяется весовая формула, которая рассчитывает TTL в зависимости от дистанции, используя диапазон первый-второй параметр auto-ttl (1-4).
6. Если рассчитанный TTL получился больше, чем третий параметр auto-ttl max (10), устанавливаем его в это значение (10).

Этот метод может работать не всегда, в частности, не все хосты могут использовать стандартные TTL 64 или 128, некоторые системы DPI в некоторых случаях изменяют TTL входящих пакетов, система DPI может находиться «дальше» по дистанции, чем рассчитанный TTL, маршрутизация может быть сильно асимметричная, из-за чего TTL входящего пакета не отражает дистанцию исходящего пути, и т.п.

Если у вас DPI стоит на 7 хопе, то используйте `--set-ttl 7`, возможно в связке с `--min-ttl 7`.

https://github.com/ValdikSS/GoodbyeDPI/blob/f94a20d2215dc911c98951ea2fa067ff0fa3ddc9/src/ttltrack.c#L222

**Comment by Owyn** [comment]
> в связке с --min-ttl

А разве есть смысл его использовать вместе с set-ttl без auto-ttl? ведь с set-ttl и так же будет фиксированный ttl, куда ему ещё минимум указывать?

**Comment by ValdikSS** [comment]
`--min-ttl` на самом деле должен называться `--min-distance`. Неудачное название параметра.
`--set-ttl` будет срабатывать только в том случае, если дистанция (количество хопов) до сервера больше `--min-ttl`. Если использовать только `--set-ttl 7`, то сайты, расположенные ближе 7 хопов, просто не будут открываться: до них будет доходить фиктивный пакет, а он не должен доходить до хоста назначения ни в каком случае.

**Comment by Owyn** [comment]
Странно, `--set-ttl 7` работает, но `-set-ttl 7 --min-ttl 7` даёт SSL_RECORD_TOO_LONG 🤔

**Comment by ValdikSS** [comment]
Используйте [GoodbyeDPI v0.2.2](https://github.com/ValdikSS/GoodbyeDPI/releases/tag/0.2.2).

**Comment by Owyn** [comment]
да, с 0.2.2 теперь работает `-set-ttl 7 --min-ttl 7`
