### ISSUE TITLE
GoodbyeDPI aint working for Roblox

### ISSUE THREAD

**Issue by ZZEEPEO** [ValdikSS/GoodbyeDPI#259]
### Operating system / операционная система

Windows 10 21H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

So when i use GoodbyeDPI 0.1.7 ( i use 4_fakepacket_all to be specific) to access roblox I can load into the site but I cant play the game. I tried using 0.1.7 x86_64 and that didn't work too.

### Additional information / Дополнительная информация

Also it randomly works sometimes but after 1 hour it dosent work

**Comment by ValdikSS** [comment]
You have outdated version, use 0.2.2.

**Comment by ZZEEPEO** [comment]
> You have outdated version, use 0.2.2.
I tried using 0.2.2 (I tried using 2_any_country_dnsredir, 2_any_country and x86_64) but it didn't work

**Comment by ValdikSS** [comment]
Try goodbyedpi.exe -6, check if it works.
If it does, the issue is in fake packet: the TTL is too big, tune auto-ttl parameters, or use static set-ttl or use blacklist.

**Comment by ZZEEPEO** [comment]
> Try goodbyedpi.exe -6, check if it works. If it does, the issue is in fake packet: the TTL is too big, tune auto-ttl parameters, or use static set-ttl or use blacklist.



How do i use -6? and the other stuff you mentioned. Sorry I am just new to techy things

**Comment by ZZEEPEO** [comment]
Hello, can u tell me how to do -6 and the other things that you mentioned?
Sorry I  am just new to tech

**Comment by ValdikSS** [comment]
1. Navigate to the folder with goodbyedpi.exe
2. Enter "cmd" in the address bar, where the folder path is displayed
3. In the new command window, enter goodbyedpi.exe -6 for example.

**Comment by ZZEEPEO** [comment]
![image](https://user-images.githubusercontent.com/84075381/164007022-4f195c4d-b33a-40c2-bcc6-80f2c1b6dede.png)
Um....

**Comment by r4sas** [comment]
Recheck directory contents and try to find out yourself what's going wrong.

**Comment by ValdikSS** [comment]
> Um....

`cd x86_64`
