### ISSUE TITLE
Reposting because i didnt get a solution

### ISSUE THREAD

**Issue by ZZEEPEO** [ValdikSS/GoodbyeDPI#260]
### Operating system / операционная система

Windows 10 21H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

So when I use GoodbyeDPI 0.2.2 ( i use 4_fakepacket_all to be specific) to access Roblox I can load into the site but I can't play the game. I tried using 0.2.2 x86_64 and that didn't work too.I

### Additional information / Дополнительная информация

Also, it randomly works sometimes but after 1 hour it doesn't work

**Comment by ValdikSS** [comment]
Please don't spam, I wrote you what to try the first time. This us not a support board, you're on your own.

**Comment by ZZEEPEO** [comment]
Oh, my bad I didn't know that. Could you please tell me how to do -6 and
other stuff? Again I'm  really sorry I did know that.

**Comment by ValdikSS** [comment]
https://ntc.party/t/help-me/2165/2

**Comment by ZZEEPEO** [comment]
Hey, I have a question about the arguments and how do I use them. Also if
you want I can give you access to my PC through anydesk(if u want)
