### ISSUE TITLE
Возвращает goo.gle вместо искомого адреса

### ISSUE THREAD

**Issue by sdfsdf53** [ValdikSS/GoodbyeDPI#263]
### Operating system / операционная система

Win 7 SP1 x64

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

При подключении к адресу ru.xhamster.com исходный адрес в строке браузера меняется на ru.goo.gle и, соответственно, не может подключиться, т.к такого адреса не существует. В любом браузере.

Остальные заблокированные адреса прекрасно работают.

**Comment by ValdikSS** [comment]
Вероятно, сам сайт перенаправляет вас на этот домен. GoodbyeDPI такого точно не умеет и не делает.
