### ISSUE TITLE
DLL initialization failed when running under Wine

### ISSUE THREAD

**Issue by nikita2498** [ValdikSS/GoodbyeDPI#264]
### Operating system / операционная система

Ubuntu 18.04.6

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

![image](https://user-images.githubusercontent.com/93794420/169578155-cd724f51-587b-4f1e-bd30-ecd357762408.png)
I especially wanted GoodbyeDPI to run in Wine under Ubuntu but it doesn't work, is it a Wine problem or DLL? please help me with this

**Comment by r4sas** [comment]
There is no support outside Windows.

**Comment by nikita2498** [comment]
> There is no support outside Windows.
i had VPN problem, and i will delete this topic now

**Comment by r4sas** [comment]
Check readme for similar projects for linux: https://github.com/ValdikSS/GoodbyeDPI#similar-projects
