### ISSUE TITLE
GoodbyeDPI with several DNS servers

### ISSUE THREAD

**Issue by d3vv** [ValdikSS/GoodbyeDPI#265]
### Operating system / операционная система

Windows 11 Pro 21H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

If we used several DNS and one from them for local net we can't to resolve thru local DNS after start of GoodByeDPI.

### Additional information / Дополнительная информация

info below from `ipconfig` command where `192.168.1.1` is DNS for local infranet:

```
Ethernet adapter Ethernet 2:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Generic Marvell Yukon 88E8053 based Ethernet Controller #2
   Physical Address. . . . . . . . . : 48-5B-39-D5-44-85
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::453a:57b2:de4d:fcab%10(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.1.71(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.1.1
   DHCPv6 IAID . . . . . . . . . . . : 436219976
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-27-1D-13-28-48-5B-39-D5-44-85
   DNS Servers . . . . . . . . . . . : 208.67.220.220
                                         DoH: https://doh.opendns.com/dns-query
                                       1.1.1.1
                                         DoH: https://cloudflare-dns.com/dns-query
                                       192.168.1.1
                                       8.8.8.8
   NetBIOS over Tcpip. . . . . . . . : Enabled
```

**Comment by ValdikSS** [comment]
Please give more details. As I understand, you have local resolver 192.168.1.1 with local zones which resolve only using said resolver? And I assume you start GoodbyeDPI with dns redirection function? If so, it won't work because DNS redirection function redirects everything, all the requests to the specified server.

**Comment by d3vv** [comment]
@ValdikSS Я тебя понял.. Но смотри, если без GoodbyeDPI, Windows получив отсутсвие записи в первом DNS сервере или при его недоступности делает fallback на следующий (и так по цепочке). Очень бы хотелось, чтобы GoodbyeDPI мог делать такой fallback , да хотябы на какой-то один конкрено указанный DNS в параметрах. Иначе не возможно им пользоваться на регулярной основе в локальных инфраструктурах.

**Comment by ValdikSS** [comment]
Так не используйте функцию перенаправления DNS, и проблема решена. Если у вас уже собственный резолвер, зачем вам она?

**Comment by d3vv** [comment]
@ValdikSS Я наверное, что-то не понял. Не будут же работать заблокированные ресурсы через такой резольвер:)) Ну а подобный резольвер не всегда еще и подконтроллен.

**Comment by ValdikSS** [comment]
Функция перенаправления DNS нужна только для тех провайдеров, которые не просто подменяют DNS-записи для заблокированных доменов, но еще и перенаправляют все сторонние резолверы на свой собственный, исключая возможность прописать какой-то публичный адрес в настройках системы. В России провайдеров, которые применяют такой метод, немного.

Функция реализована именно так, чтобы надёжно перенаправить все DNS-запросы к заданному резолверу, независимо от настроек системы, т.к. в Windows 10 (по крайней мере, в ранних билдах) нельзя было отключить резолвинг через разные DNS каким-либо более-менее простым методом ([и я в своё время сделал опцию для OpenVPN ровно с такой же функциональностью](https://habr.com/ru/post/268173/)).

Это не баг.
