### ISSUE TITLE
Возможность свернуть окно в трей

### ISSUE THREAD

**Issue by BANanaD3V** [ValdikSS/GoodbyeDPI#267]
### Describe your feature / Опишите ваше предложение

Мне очень не удобно смотреть на постоянно работающее окно на таскбаре. У меня goodbyedpi запускается автоматом с системой. Очень хочу запуск в трей.

**Comment by r4sas** [comment]
Запускайте как сервис, скрипты в папке присутствуют.

**Comment by ValdikSS** [comment]
Dupe #40
