### ISSUE TITLE
Publish GoodbyeDPI on Microsoft Windows Store

### ISSUE THREAD

**Issue by fpietrosanti** [ValdikSS/GoodbyeDPI#27]
This ticket is to publish GoodbyeDPI on Microsoft Windows Store in order to increase end-user base and provide a non-censorable/collateral-damage way to acquire it.

**Comment by ValdikSS** [comment]
Windows Store supports only UWP applications (APPX extension), which GoodbyeDPI is not. GoodbyeDPI can be converted to UWP using Desktop Bridge software, but Microsoft Store prohibit UWP applications to require privilege escalation or service installation, let alone driver loading.

So, most probably won't happen.

**Comment by ValdikSS** [comment]
Closing because it's not possible.
