### ISSUE TITLE
Не работает Instagram web в браузере. 

### ISSUE THREAD

**Issue by UnoFortunato** [ValdikSS/GoodbyeDPI#274]
### Operating system / операционная система

Windows 11

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Не работает **Instagram web** в браузере. Провайдер Билайн Москва.

**Comment by ValdikSS** [comment]
Пожалуйста, внимательно читайте информационное сообщение о том, что такое баг.
Это не баг.

**Comment by UnoFortunato** [comment]
А там у вас другой опции нет, к сожалению.

**Comment by ValdikSS** [comment]
>Для вопросов, а также в случае сомнений в определении бага, обращайтесь [на форум NTC.party](https://ntc.party/c/community-software/goodbyedpi).

**Comment by UnoFortunato** [comment]
Еще там надо пройти регистрацию! Ну и бюрократия!  Хорошо, что не в Госдуму направили. На том спасибо!

**Comment by krlvm** [comment]
Попробуйте дописать в файл hosts:
```
157.240.194.174 instagram.com www.instagram.com
```

**Comment by UnoFortunato** [comment]
> Попробуйте дописать в файл hosts:
> 
> ```
> 157.240.194.174 instagram.com www.instagram.com
> ```

Нет, не открывается.

**Comment by UnoFortunato** [comment]
> Попробуйте дописать в файл hosts:
> 
> ```
> 157.240.194.174 instagram.com www.instagram.com
> ```

После перезапуска браузера можно войти в аккаунт, но лента пустая, то есть посты не загружаются.

**Comment by krlvm** [comment]
Посмотрите в инструментах разработчика, к каким еще доменам ограничивается доступ
