### ISSUE TITLE
https://www.torproject.org/ DNS redirection problems from Turquie not work without proxies or vnp yet

### ISSUE THREAD

**Issue by spamkutu** [ValdikSS/GoodbyeDPI#279]
### Operating system / операционная система

Windows10 20H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

https://www.torproject.org/ 
DNS redirection problems from Turquie not work without proxies or vnp yet

**Comment by ValdikSS** [comment]
USE THIS FORM ONLY FOR BUGS
GoodbyeDPI does not guarantee to work with your ISP for every blocked website or at all. If GoodbyeDPI can't unblock some or any websites, this is most likely not a software bug, and you should not report it here.

Please only report software bugs, such as:

* program crash
* incorrect network packet handling
* antivirus incompatibility
* DNS redirection problems
* other software

Please make sure to check other opened and closed issues, it could be your bug has been reported already.
For questions, or if in doubt, [use NTC.party forum](https://ntc.party/c/community-software/goodbyedpi).
