### ISSUE TITLE
Does running this impact speed in any way?

### ISSUE THREAD

**Issue by Bearmancer** [ValdikSS/GoodbyeDPI#281]
### Describe your feature / Опишите ваше предложение

I realize that questions should be posted on the GoodbyeDPI forum but I did not want to create a new account just for one question.

I installed the service with Russian blacklist filter but I notice that some sites are still blocked. If I wanted to run it at all times as a service I would just install it as:
`sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -5 start= "auto"`

Correct?

My question is if running this software 24/7 will impact loading speeds, create latency, etc. or it has no impact whatsoever on internet speeds.

**Comment by Lui22** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/173#issuecomment-609406097
