### ISSUE TITLE
Не работает hdkinoteatr.com

### ISSUE THREAD

**Issue by ffsmyusernameistaken** [ValdikSS/GoodbyeDPI#286]
### Operating system / операционная система

Windows 7

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

С сегодняшнего дня не работает hdkinoteatr.com, с vpn всё нормально. Я не думаю, что админ сайта заблокировал российские ip, т.к. он бы давно уже это сделал, если б хотел и большинство посетителей из России.
![2022-11-08_19-01-06](https://user-images.githubusercontent.com/26306446/200615215-0aec7ef7-9e19-4a3d-b15d-95015b21587e.png)

**Comment by Lui22** [comment]
Вероятно, стоит указать провайдера и город, потому что у меня работает

**Comment by Abwehr** [comment]
Сейчас еще с инстаграммом проблемы появились. Ростелеком.

**Comment by ffsmyusernameistaken** [comment]
Rutracker тоже не работает.

**Comment by ValdikSS** [comment]
ИСПОЛЬЗУЙТЕ ЭТУ ФОРМУ ТОЛЬКО ДЛЯ БАГОВ
GoodbyeDPI не гарантирует ни 100% работу с вашим провайдером, ни работу с каждым заблокированным сайтом. Если GoodbyeDPI не разблокирует доступ к некоторым или всем веб-сайтам, вероятнее всего, это не программная ошибка, и не стоит о ней сообщать здесь.

Пожалуйста, сообщайте только об ошибках в программе, таких как:

* падение программы
* некорректная обработка сетевых пакетов
* несовместимость с антивирусами
* проблемы с перенаправлением DNS
* другие ошибки в программе

Также посмотрите другие открытые и закрытые баги. Возможно, ошибка уже обсуждалась или исправлена.
Для вопросов, а также в случае сомнений в определении бага, обращайтесь [на форум NTC.party](https://ntc.party/c/community-software/goodbyedpi).

**Comment by ffsmyusernameistaken** [comment]
> ИСПОЛЬЗУЙТЕ ЭТУ ФОРМУ ТОЛЬКО ДЛЯ БАГОВ GoodbyeDPI не гарантирует ни 100% работу с вашим провайдером, ни работу с каждым заблокированным сайтом. Если GoodbyeDPI не разблокирует доступ к некоторым или всем веб-сайтам, вероятнее всего, это не программная ошибка, и не стоит о ней сообщать здесь.
> 
> Пожалуйста, сообщайте только об ошибках в программе, таких как:
> 
> * падение программы
> * некорректная обработка сетевых пакетов
> * несовместимость с антивирусами
> * проблемы с перенаправлением DNS
> * другие ошибки в программе
> 
> Также посмотрите другие открытые и закрытые баги. Возможно, ошибка уже обсуждалась или исправлена. Для вопросов, а также в случае сомнений в определении бага, обращайтесь [на форум NTC.party](https://ntc.party/c/community-software/goodbyedpi).

Всё работало до того дня, когда я это написала, так что, по-моему, это связано с программой. Без программы сайты не открывались. Неважно, потому что сейчас всё работает опять.
