### ISSUE TITLE
Блокированные сайты даже с включённым GoodbyeDPI не открываются(мгтс)

### ISSUE THREAD

**Issue by f1refa11** [ValdikSS/GoodbyeDPI#288]
### Operating system / операционная система

Windows 10 Pro 21H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Сайты не открываются даже с включённым GoodbyeDPI
например:
twitter.com
всякие google сервисы для фотографий
и много всяких других сайтов
![изображение](https://user-images.githubusercontent.com/58619409/201963201-ad7d5c64-3249-4176-bf2b-bd9f503a7e85.png)

### Additional information / Дополнительная информация

Провайдер: МГТС
ошибка сразу появляется

**Comment by sattew** [comment]
Ghj,jdfkb https://github.com/ValdikSS/GoodbyeDPI/issues/251?
