### ISSUE TITLE
Didn't work in Nhentai.net

### ISSUE THREAD

**Issue by Samapoke** [ValdikSS/GoodbyeDPI#292]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Nothing happened to Nhentai when I running the program.

### Additional information / Дополнительная информация

I'm from Vietnam, my country has just banned Nhentai recently, not just Nhentai but other H-pages in Vietnam, I ran the program with sloved the most of my country H-pages, but Nhentai isn't, please help me!

**Comment by ascent-sys** [comment]
[v](https://nhentai.uk/)?
