### ISSUE TITLE
How to delete it

### ISSUE THREAD

**Issue by chiragnahata** [ValdikSS/GoodbyeDPI#294]
### Operating system / операционная система

Windows 11 22h2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

How to uninstall it

**Comment by ValdikSS** [comment]
It does not install. Just delete the directory where you've unpacked the software.

**Comment by boyrin** [comment]
я не щарю как через cmd  удалить можете подсказать. винда 10
