### ISSUE TITLE
Добавление сервера play.google.com в список заблокированных сайтов

### ISSUE THREAD

**Issue by dillema1** [ValdikSS/GoodbyeDPI#298]
### Describe your feature / Опишите ваше предложение

Здравствуйте. Такое дело, что в России заблокирован сервер play.google.com, вследствие чего пользование сайтом YouTube становится каким-то странным, всё-таки непривычно видеть то, что заместо аватарок на сайте серые кружочки, а заместо фотографий в обсуждениях - пустота. Можете ли вы добавить данный сервер для обхода DPI? Спасибо.

**Comment by dillema1** [comment]
В этот список можно также добавить обход блокировки саундклауд.

**Comment by LonerD** [comment]
Также не помешает добавить в фильтры google.com, google.ru и прочих гугловских поисковиков, учитывая, что гугл блокирует доступ к поисковику с российских IP.

**Comment by ValdikSS** [comment]
Готово.
