### ISSUE TITLE
yt3.ggpht.com not loading in Russia 11.02.2023

### ISSUE THREAD

**Issue by HuntezWOTB** [ValdikSS/GoodbyeDPI#299]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Перестали загружатся иконки ютуба, при этом заходя на домен yt3.ggpht.com выходит ошибка гугла 400
Провайдер Билайн

**Comment by HuntezWOTB** [comment]
![image](https://user-images.githubusercontent.com/64587859/218279622-81bdab01-f29c-4833-80c9-50f98fe17b20.png)

**Comment by HuntezWOTB** [comment]
Большие иконки и баннеры каналов перешли на домен yt3.googleusercontent.com. Маленькие перестали работать

**Comment by ValdikSS** [comment]
Это не ошибка программы.
