### ISSUE TITLE
Переодически страницы возвращают ошибку 400 Bad Request

### ISSUE THREAD

**Issue by nxrighthere** [ValdikSS/GoodbyeDPI#3]
Периодически страницы на разных сайтах возвращают ошибку 400 Bad Request. Как правило помогает простое обновление страницы. В клиенте Steam например, если просто открыть и полистать список рекомендаций, то там практически каждый раз страница возвращает эту ошибку.

**Comment by ValdikSS** [comment]
Приведите пример сайтов.

**Comment by nxrighthere** [comment]
Чаще всего на http://store.steampowered.com и https://rule34.xxx

![Steam](https://s10.postimg.org/mf699j9a1/steam.png)
![Rule34](https://s12.postimg.org/ym1mrkz59/rule34.png)

**Comment by ValdikSS** [comment]
С какими параметрами вы запускаете программу?

**Comment by ValdikSS** [comment]
Понажимал на все нажимаемое на обоих сайтах, не проявляется. Я догадываюсь, в чем проблема, но мне нужно воспроизвести ее самостоятельно. Есть ли какая-то конкретная ссылка, на которой проявляется ошибка?

**Comment by nxrighthere** [comment]
Программу запускаю с параметрами по умолчанию. Вот, посмотрите как это происходит https://a.pomf.cat/zhtehd.mp4

**Comment by nxrighthere** [comment]
Тоже самое на http://vinesauce.booru.org, http://gravityfalls.booru.org, http://5naf.booru.org и прочих имиджбордах.

**Comment by nxrighthere** [comment]
Забавно, если обращаюсь к странице напрямую, например вот так http://rule34.xxx/index.php?page=post&s=list&tags=sfw, то ошибка не возникает, а если перейти через поиск по тегу с главной страницы, то появляется ошибка.

**Comment by ValdikSS** [comment]
Попробуйте 0.0.6, должно быть исправлено.

**Comment by nxrighthere** [comment]
Теперь вроде как стабильно странички открываются, спасибо.
