### ISSUE TITLE
russia-blacklist.txt misspells Exhentai's domain

### ISSUE THREAD

**Issue by MarqFJA87** [ValdikSS/GoodbyeDPI#300]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

The russia-blacklist.txt file mistakenly uses "exhentai.me" instead of "exhentai.org". I can only access the site with GoodbyeDPI after editing the entry in that file to the latter.

**Comment by ValdikSS** [comment]
There's no such entry in the blacklist. Extentai.org is not blocked in Russia.

**Comment by MarqFJA87** [comment]
> There's no such entry in the blacklist. Extentai.org is not blocked in Russia.

Sir, you just open the file and search "exhentai.me" to find the misspelled entry; it's even in the latest version that I can download. I don't know what else to tell you.

PS: I'm not from Russia or even that close to it (culturally or geographically), but much of the sites blocked there are also blocked in my region.

**Comment by ValdikSS** [comment]
`russia-blacklist.txt` contains the list of websites blocked in Russia. `exhentai.org` is not blocked in Russia.

**Comment by MarqFJA87** [comment]
> `russia-blacklist.txt` contains the list of websites blocked in Russia. `exhentai.org` is not blocked in Russia.

Well exhentai.org is inaccessible to me unless I modify that entry in the file to change ".me" to ".org". What other solution do you suggest?

**Comment by ValdikSS** [comment]
You can construct your own blacklist file or run the program without one.
