### ISSUE TITLE
Чудовищно занижает скорость работы Steam

### ISSUE THREAD

**Issue by envlightsourcegaben** [ValdikSS/GoodbyeDPI#301]
### Operating system / операционная система

Windows 10 20H2 

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

При работе программы не грузятся изображения в магазине стим, и в целом залогиниться невозможно. Если отключить все снова работает.

**Comment by ValdikSS** [comment]
Покрутите настройки TTL, наиболее вероятно, проблема в них.
Это не ошибка в программе. В следующий раз задавайте вопросы на форуме, как указано в шаблоне.
