### ISSUE TITLE
--blacklist option doesn't work when running goodbyedpi.exe -2 mode

### ISSUE THREAD

**Issue by onmyouji** [ValdikSS/GoodbyeDPI#302]
### Operating system / операционная система

Windows 10 21H2 

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Hello,

The --blacklist option doesn't work when I use `goodbyedpi.exe -2`

I tested with `goodbyedpi.exe -2` and `goodbyedpi.exe -5`

On -5, the blacklist works just fine. But on -2, the blacklist doesn't work.

Is this a bug or limitation of the program?

Thanks

**Comment by ValdikSS** [comment]
This is a known issue. SNI/hostname analysis works only for Window Size=1 or 2, not more.
Non-window-size splitting does not have this issue.

It should print this message:
https://github.com/ValdikSS/GoodbyeDPI/blob/4a82fd442dcdd69de731fb717fb055f8547083fa/src/goodbyedpi.c#L998-L1002
