### ISSUE TITLE
Проблемы с браузером Vivaldi

### ISSUE THREAD

**Issue by kkaazzoo** [ValdikSS/GoodbyeDPI#306]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

При включении программы получаю проблемы с браузером Vivaldi. Открывает или не открывает сайты рандомным образом из поиска, при открытии сайтов сильно тормозит. Например стабильно не открывает Хабр, выдаtт ошибку SSL-сертификата. С другими браузерами проблем нет.

**Comment by Shionsan** [comment]
Такая же фигня. Отключение QUIC в доп настройках (vivaldi:flags) не спасло. Как это дебажить?

**Comment by BlackAures1** [comment]
+1 к проблеме. Также будто появились проблемы с видеокартой. Люто фризит и выключает всё что нагружало комп (игру, сам браузер и дискорд). До установки такой пробелемы не было. Хотелось бы получить инструкцию по удалению GoodbyeDPI

**Comment by BlackAures1** [comment]
Решила проблему менее радикально. Баги происходят именно от изменения экспериментальных настроек.
Experimental QUIC protocol/TLS 1.3 hybridized Kyber support 
Без них GoodbyeDPI всё ещё работает, просто иногда приходится перезапускать страницу видоса.

**Comment by kkaazzoo** [comment]
Проблема была решена после установки релиза 0.2.3rc1. Можно закрывать тему.

**Comment by BlackAures1** [comment]
В общем, отключение экспериментальных настроек и так далее проблему не решили. Всё равно ровно раз в 30 минут происходит перегрузка браузера с последующим отключением всего и вся. Версия самая последняя, которая 7 часов назад была залита. Пока не найдётся решение, буду смотреть через активности в дискорде.

**Comment by ValdikSS** [comment]
@BlackAures1 решение простое — использовать blacklist.

**Comment by BlackAures1** [comment]
![image](https://github.com/user-attachments/assets/770b8d1f-b661-4063-8773-d281caa97d47)
 
 Если ты про это, то это именно то что я и запускала :)
