### ISSUE TITLE
Games support (Paladins, Pavlov vr, Black ops 2-3)

### ISSUE THREAD

**Issue by Smelt1993** [ValdikSS/GoodbyeDPI#307]
### Describe your feature / Опишите ваше предложение

Речь идёт про Крым/Донецк/Луганск, там эти игры в онлайн режимах не работают, впрочем как и BattleNet. 
Можно ли как-то с помощью вашего софта проходить авторизацию там или же нет. Проверяли в ДНР Paladins уже, по дефолтным настройкам он не проходит авторизацию в игре. Извиняюсь, если написал не туда, куда стоило.

**Comment by AHOHNMYC** [comment]
GoodbyeDPI не подменяет местоположение, он изменяет заголовки пакетов, чтобы их не зарезало <s>провайдерское</s> ФСБшное оборудование, то есть работает с блокировками, созданными "изнутри" страны.
