### ISSUE TITLE
с версией 0.1.0 не открывается ни один сайт

### ISSUE THREAD

**Issue by f242** [ValdikSS/GoodbyeDPI#31]
пришлось откатиться на предыдущую 0.0.9, на ней всё ок, запускаю в режиме по-умолчанию без каких либо параметров
версия x64
win10 x64

**Comment by ValdikSS** [comment]
Установлен ли у вас какой-либо антивирус или файрволл?
Пишите, пожалуйста, по-английски, при возможности.

**Comment by ValdikSS** [comment]
Попробуйте этот EXE и напишите, изменилось ли что-либо.
[goodbyedpi.zip](https://github.com/ValdikSS/GoodbyeDPI/files/1275386/goodbyedpi.zip)

**Comment by f242** [comment]
@ValdikSS всё снова заработало!
Avira free antivirus, фаервол штатный.
Intel(R) 82579V Gigabit Network Connection, driver v12.15.31.4

**Comment by BroodWay** [comment]
Тоже ни один сайт не открывается, антивируса нет, win 10, фаервол штатный

**Comment by ValdikSS** [comment]
@f242, @BroodWay, хм, хорошо, попробуйте вот этот, пожалуйста:
[goodbyedpi.zip](https://github.com/ValdikSS/GoodbyeDPI/files/1284442/goodbyedpi.zip)

**Comment by f242** [comment]
@ValdikSS с этим снова всё перестаёт открываться, кстати, очень нехватает в окне указания версии

**Comment by ValdikSS** [comment]
@f242 давайте еще раз пальцем в небо: 
[goodbyedpi-test3.zip](https://github.com/ValdikSS/GoodbyeDPI/files/1284510/goodbyedpi.zip)

**Comment by f242** [comment]
@ValdikSS тоже всё перестаёт открываться

**Comment by BroodWay** [comment]
goodbyedpi-test3.zip - проверил, интернет перестает работать вообще, пока включено приложение.

**Comment by ValdikSS** [comment]
Попробуйте версию 0.1.1, должна работать. Если не работает — откройте issue заново.
