### ISSUE TITLE
Some websites redirect to w3.org

### ISSUE THREAD

**Issue by CoffeNook** [ValdikSS/GoodbyeDPI#310]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

I am able to access certain websites using GoodbyeDPI but when I click on a link, it redirects me to w3.org. It doesn't let me browse the website. However if I use any VPN instead of GoodbyeDPI, it doesn't redirect. Does the GoodbyeDPI app have any built-in redirection feature? 

### Additional information / Дополнительная информация

I'm in Turkey.

**Comment by r4sas** [comment]
https://github.com/ValdikSS/GoodbyeDPI/blob/4a82fd442dcdd69de731fb717fb055f8547083fa/src/fakepackets.c#L10-L12

**Comment by r4sas** [comment]
Use any other than `-5` and `-6` modes, or configure yourself without any options which enables "Fake Request Mode".
