### ISSUE TITLE
0_russia_update_blacklist_file.cmd не обновляет чёрный список

### ISSUE THREAD

**Issue by SoundBoomer** [ValdikSS/GoodbyeDPI#311]
### Operating system / операционная система

Windows 10 2004

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

При запуске скрипта на обновление чёрного списка идёт бесконечный коннект, загрузка не начинается.
![изображение](https://github.com/ValdikSS/GoodbyeDPI/assets/116379859/8f4d4aba-d9d3-4bdd-9f95-f8dbce9ec4d6)

### Additional information / Дополнительная информация

Скорее всего проблема связана с тем, что РКН заблокировали адреса АнтиЗапрета

**Comment by cebep133** [comment]
Ага! И если запустить сам GoodbyeDPI , то это не помогает разблокировать доступ к сайту)) Парадокс))

**Comment by uffemcev** [comment]
Можно использовать альтернативные порты:
https://antizapret.prostovpn.org:8443/domains-export.txt
https://antizapret.prostovpn.org:18443/domains-export.txt

Или другой источник, где файл весит под 8 мб: https://reestr.rublacklist.net/api/v3/domains
Но здесь нужно чистить мусор, к примеру через powershell:
`(iwr "https://reestr.rublacklist.net/api/v3/domains") -split '", "' -replace ('[\[\]"]'), ('') | sc "$env:USERPROFILE\Desktop\russia-blacklist.txt"`

**Comment by cebep133** [comment]
> Тред на эту тему https://ntc.party/t/topic/4269
> 
> Можно использовать альтернативные порты: https://antizapret.prostovpn.org:8443/domains-export.txt https://antizapret.prostovpn.org:18443/domains-export.txt
> 
> Или другой источник, где файл весит под 8 мб: https://reestr.rublacklist.net/api/v3/domains Но здесь нужно чистить мусор, к примеру через powershell: `(iwr "https://reestr.rublacklist.net/api/v3/domains") -split '", "' -replace ('[\[\]"]'), ('') | sc "$env:USERPROFILE\Desktop\russia-blacklist.txt"`

Спасибо за инфу

**Comment by uffemcev** [comment]
> Ну мож файл и обновился, но прога то всё равно не фурычит, сайты не открываются увы и ах. Провайдер домсру ![scr_25_05_2023_23_32_21](https://user-images.githubusercontent.com/11617079/241052669-f684a5d5-3387-4c49-81bf-fbba0fdc3cb2.png)

Попробуйте dns адреса поменять в самой системе на cloudflare dns over https, а в программе отключить сторонние dns.

Так же попробуйте поменять режимы, по идее 5 самый универсальный, но есть и другие.

**Comment by cebep133** [comment]
А обновление не планируется со всеми внесенными изменениями для работоспособности?
А то я например, как рядовой пользователь не знаю ничего про режимы dns и где это смотреть)))

**Comment by MARK2580** [comment]
Со сменой DNS на прямую в адаптере некоторые сайты начинают ошибки выдавать, а другие неадекватно долго прогружаться, то ещё удовольствие.

**Comment by ValdikSS** [comment]
Смените в файле порт на 8443 или 18443.
