### ISSUE TITLE
Не могли бы вы скомпилировать dll программы для C#

### ISSUE THREAD

**Issue by Dragon-0609** [ValdikSS/GoodbyeDPI#312]
Я хочу запустить GoodbyDPI через свою программу в C#, но не разбираюсь в C. Поэтому, не могли бы вы скомпилировать dll версию?

**Comment by sadtango289** [comment]
Allow me, just a small question for the developer, long time no see updates, any news please ?

**Comment by AHOHNMYC** [comment]
Странный вопрос. dll представляет собой библиотеку (library) функций. GoodbyeDPI — продукт изначально не модульный, так что функции для экспорта надо прописывать самому. В какие из точек вы захотите потыкаться и на каком уровне — известно только вам.

Начать можно с [этого](https://stackoverflow.com/a/538179) ответа, а продолжить [этим чтивом](http://www.cygwin.com/cygwin-ug-net/dll.html). Примерный синтаксис вызова функции из dll описан [тут](https://stackoverflow.com/a/15773851).

Вышла какая-то игра в LMGTFY, ну да ладно. Всяко лучше, чем простое закрытие ишшуеса с `won't do`.

**Comment by ValdikSS** [comment]
> хочу запустить GoodbyDPI через свою программу в C#,

Достаточно запустить сам .exe, для этого не нужна .dll.
