### ISSUE TITLE
Somehow it broken Windows native network layer stacks

### ISSUE THREAD

**Issue by skshpr** [ValdikSS/GoodbyeDPI#313]
### Operating system / операционная система

Windows 11 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

With not often use it broken native windows network layer stack somehow so created earlier VPN connection (win native l2tp) started working very slow and it begin works well when gdpi start to work. Also same scenario thing happens when trying to run any simple tool from actual version of windivert (flowtrack).
Resetting all TCP, network settings - doesn't' help.
Removing VPN settings - doesn't' help.
Removing all network devices with drivers, and it's further reinstalling - doesn't help
Trying to kill \ uninstall windivert via windivertctl.exe - doesn't help.

Don't want to reinstall win. It will be last mile.

Summary:
Ethernet connection works well without VPN and GDPI.
When running VPN, main Ethernet traffic have full speed, but VPN connection is 20 times slower.
When running VPN with windivert, main Ethernet traffic is 80% of full speed, VPN connection run at full speed.
If switching from Ethernet to WiFi adapter so all works well for main traffic and VPN tho.

Will appreciate any suggestion to dig in...

**Comment by r4sas** [comment]
Better to ask on WinDivert: https://github.com/basil00/Divert. GDPI works using it on network layer.

**Comment by skshpr** [comment]
> Will try. TU 73

**Comment by skshpr** [comment]
Hey guys, sorry for bothering you but seems it was recent fuc...up update from Microsoft.
Confirming:
[Link 1](https://petri.com/microsoft-slow-vpn-connection-windows-11/)
[Link 2](https://www.reddit.com/r/meraki/comments/13ermrb/kb5025305_causes_speed_issues_on_l2tpipsec_vpn/)
And solution that 100% works well (and @ValdikSS you pointed in right place)
[Link](https://jj1gtb.com/vpn-is-slow-after-windows-11-i-cant-connect-change-your-settings-in-the-control-panel-to-improve-your-connection-speed/)
In my case problematic update couldn't be uninstalled.
