### ISSUE TITLE
There are no more endpoints available from the endpoint mapper

### ISSUE THREAD

**Issue by Sicarioes** [ValdikSS/GoodbyeDPI#314]
### Operating system / операционная система

Windows 10 21H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

![image](https://github.com/ValdikSS/GoodbyeDPI/assets/138219759/f5d26053-c7c5-4ffe-88b5-8d0dbe247efa)
пишет "There are no more endpoints available from the endpoint mapper."

### Additional information / Дополнительная информация

Раньше всё работало, после у меня отвалились службы интернета, я их запустил вручную, возможно ли что это помешало?

**Comment by ValdikSS** [comment]
#212
