### ISSUE TITLE
Opening filter Error opening filter: There are no more endpoints available from the endpoint mapper.

### ISSUE THREAD

**Issue by Kedr228** [ValdikSS/GoodbyeDPI#315]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Когда я запускаю 2_any_country_dnsredir.cmd и любые другие файлы, пишет Opening filter
Error opening filter: There are no more endpoints available from the endpoint mapper.

![image](https://github.com/ValdikSS/GoodbyeDPI/assets/61898849/68e77069-9fca-4583-8294-fb2c34db23cc)

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/212
