### ISSUE TITLE
Program runs but DNS not bypassed

### ISSUE THREAD

**Issue by Sayangd095** [ValdikSS/GoodbyeDPI#317]
### Operating system / операционная система

Windows 11 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Hey Vlad, using goodbyedpi for months now without any issue whatsoever, and it works like a charm. I recently purchased a laptop and can't get goodbyedpi to work on it for some reason. Both my PC(Where i have been using goodbyeDPI for over a year) & my laptop(Newly purchased) are on the same ISP and connected to the same router. Any leads to what might be causing this issue?

### Additional information / Дополнительная информация

.

**Comment by ValdikSS** [comment]
See this
https://github.com/ValdikSS/GoodbyeDPI/issues/313

Sep 10, 2023 12:15:10 Sayangd095 ***@***.***>:

**Comment by Sayangd095** [comment]
Hey,

Before trying that I just upgraded to WIndows 11 Pro from the Home Edition and that fixed the issue. It's running again.

Thank You
