### ISSUE TITLE
Не открывается некоторые web-страницы Blizzard

### ISSUE THREAD

**Issue by shinreisg** [ValdikSS/GoodbyeDPI#32]
Здравствуйте!
Используется GoodbyeDPI версии 0.1.1 с параметрами запуска -1 -a.
С включенным GoodbyeDPI страницы http://eu.battle.net/sc2/ru/ и http://eu.battle.net/heroes/ru/ не открываются, выдается сообщение в браузере: "Bad Request. Your browser sent a request that this server could not understand."

**Comment by ValdikSS** [comment]
Это нормально и ожидаемо.
```
Try to run goodbyedpi.exe -1 -a first. If you can open blocked websites it means your ISP has DPI which can be circumvented. This is the slowest and **prone to break websites mode**, but suitable for most DPI.
```
