### ISSUE TITLE
Что с этой программой?

### ISSUE THREAD

**Issue by oleedd** [ValdikSS/GoodbyeDPI#323]
### Operating system / операционная система

W7

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

>[O] Тестируем обход DPI
	Пробуем способ «отсутствие пробела между двоеточием и значением заголовка Host» на www.kaspersky.ru
[☠] Сайт не открывается
	Пробуем способ «перенос строки перед GET» на www.kaspersky.ru
[☠] Сайт не открывается
	Пробуем способ «фрагментирование заголовка» на www.kaspersky.ru
[☠] Сайт не открывается
	Пробуем способ «перенос строки в заголовках в UNIX-стиле» на www.kaspersky.ru
[☠] Сайт не открывается
	Пробуем способ «точка в конце домена» на www.kaspersky.ru
[☠] Сайт не открывается
	Пробуем способ «дополнительный пробел после GET» на www.kaspersky.ru
[☠] Сайт не открывается
	Пробуем способ «фрагментирование заголовка, hoSt и отсутствие пробела одновременно» на www.kaspersky.ru
[☠] Сайт не открывается
	Пробуем способ «табуляция в конце домена» на www.kaspersky.ru
[☠] Сайт не открывается
	Пробуем способ «заголовок hoSt вместо Host» на www.kaspersky.ru
[☠] Сайт не открывается
	Пробуем способ «необычный порядок заголовков» на www.kaspersky.ru
[☠] Сайт не открывается

Но этот сайт работает, он не заблокирован!

**Comment by Glazami** [comment]
Всё дело в том что заблокировали сайт с которого подгружался список заблокированных сайтов.
Включить vpn, запустите процесс обновления списка заблокированных сайтов, потом уже запускайте программу.
