### ISSUE TITLE
TLS inspection bypass

### ISSUE THREAD

**Issue by Hhk78** [ValdikSS/GoodbyeDPI#325]
### Describe your feature / Опишите ваше предложение

The program runs smoothly under normal conditions. Thank you to the producers.
However, my school internet has TLS inspection. It is not possible to access the internet directly without the CA certificate issued by my school. Dns is extremely poisoned but I can solve it with dns over https. When I run Goodbye dpi, I can access http sites, but I cannot access https sites because of the "secure connection could not be established" error.
Is there a way to bypass TLS inspection?
Can this feature be added along with goodbye dpi in the future?
Sorry for the English, I used google translate.

**Comment by Simulping** [comment]
at that point i would suggest using trojan/v2ray instead

**Comment by Hhk78** [comment]
> at that point i would suggest using trojan/v2ray instead

you need to pay money to rent any server using this method. i want to do it for free
otherwise, this tool would not make sense, we would pay for the vpn

**Comment by ValdikSS** [comment]
> Is there a way to bypass TLS inspection?

I don't think so. Usually it's not possible unless the proxy is misconfigured (or has some kind of whitelist hosts, i.e. `google.com` or something like that).

Enterprise filtering in general is performed with different kind of software and configuration compared to mass-scale government ones. GoodbyeDPI doesn't aim to circumvent such blocks.
