### ISSUE TITLE
Crashes in 10 second after every start, doesnt work as before / Перестал работать, вылетает после запуска

### ISSUE THREAD

**Issue by feelredsnow** [ValdikSS/GoodbyeDPI#329]
### Operating system / операционная система

Windows 11 x64

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Пользовался больше 2 месяцев, только 1_russia_blacklist_dnsredir.cmd, в 1-ин момент перестал работать, возможно после установки каких-то программ, пробовал удалять программы не помогло. выключается через 10 секунд после запуска.
I used it for more than 2 months, only 1_russia_blacklist_dnsredir.cmd, at one point it stopped working, maybe after installing some programs, I tried deleting the programs, it didn’t help. turns off 10 seconds after startup.

```
Loaded 117607 hosts from file ..\russia-blacklist.txt
Block passive: 0
Fragment HTTP: 2
Fragment persistent HTTP: 2
Fragment HTTPS: 2
Native fragmentation (splitting): 1
Fragments sending in reverse: 1
hoSt: 0
Host no space: 0
Additional space: 0
Mix Host: 0
HTTP AllPorts: 0
HTTP Persistent Nowait: 1
DNS redirect: 1
DNSv6 redirect: 1
Allow missing SNI: 0
Fake requests, TTL: auto (fixed: 0, auto: 1-4-10, min distance: 3)
Fake requests, wrong checksum: 0
Fake requests, wrong SEQ/ACK: 0
Max payload size: 1200

Opening filter
Error opening filter: The system cannot find the file specified.
```

**Comment by hamitozdemir** [comment]
Hello, I had a similar problem just now after running League of Legends (for the first time on this PC), it launched in a very small resolution like 800x600, I restarted my computer and afterwards I was having the same goodbyedpi problem as you do. 

I noticed `WinDivert64.sys` file was missing from `x86_64` directory in goodbyedpi folder. I don't know if it was LoL that deleted the file because it was interfering with network or some sort of other problem that occurred during my restart, but after replacing the file the `Error opening filter: The system cannot find the file specified.` problem was resolved for me.

**Comment by feelredsnow** [comment]
> Hello, I had a similar problem just now after running League of Legends (for the first time on this PC), it launched in a very small resolution like 800x600, I restarted my computer and afterwards I was having the same goodbyedpi problem as you do.
> 
> I noticed `WinDivert64.sys` file was missing from `x86_64` directory in goodbyedpi folder. ~I don't know if it was LoL that deleted the file because it was interfering with network or some sort of other problem that occurred during my restart, but~ after replacing the file the `Error opening filter: The system cannot find the file specified.` problem was resolved for me.
> 
> Related to #327. Apparently it's Windows Defender's fault.

Thanks that's it! i did make an exclusion in Windows Defender but didn't thought something was already gone from my folder

**Comment by feelredsnow** [comment]
just rearchive .zip and check for integrity of all files with the original
