### ISSUE TITLE
Twitter(X) - Hosts list for Russia (January 2024)

### ISSUE THREAD

**Issue by BitModding** [ValdikSS/GoodbyeDPI#332]
### Operating system / операционная система

Windows 11

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

# Доступ в Твиттер(Икс) в 2024 году - Россия
Доступ в Твиттер(X) с использованием GoodBye-DPI. Проверено на провайдере Билайн. Январь 2024
!!! НЕ ГАРАНТИРУЮ РАБОТУ НА ДРУГИХ ОПЕРАТОРАХ !!!

Вставить в файл hosts:

#GoodBye-DPI --- Twitter(X) --- Russia
#Актуальный список-лист для обхода блокировок Twitter(X) с GoodBye-DPI.
104.244.42.1 twitter.com
104.244.42.2 api.twitter.com
104.244.42.3 twitter.com www.twitter.com 
104.244.42.4 api.tweetdeck.com
104.244.42.5 t.co
104.244.42.6 mobile.twitter.com
104.244.42.7 support.twitter.com
104.244.42.8 syndication.twitter.com
104.244.42.9 abs-0.twimg.com
104.244.42.11 upload.twitter.com
104.244.42.66 api.twitter.com 
104.244.43.3 abs-0.twimg.com
151.101.84.157 static.ads-twitter.com
#Завершение списка-лист для обхода блокировок Twitter(X) с GoodBye-DPI.

### Additional information / Дополнительная информация

Единственное, что не работает - так это эмодзи по адресу, указанному снизу
104.244.43.131 abs-0.twimg.com

Если и добавить в hosts - ничего не меняется

**Comment by BitModding** [comment]
В основном, посидеть в Твиттере можно, но без эмодзи.

Кому надо для Instagram, то вот снизу, вставить в Hosts:

# Актуальный список-лист для обхода блокировок Instagram с GoodBye-DPI
157.240.245.174 instagram.com www.instagram.com graph.instagram.com i.instagram.com static.cdninstagram.com scontent.cdninstagram.com
31.13.81.52 scontent-arn2-1.cdninstagram.com
# Завершение списка-лист для обхода блокировок Instagram с GoodBye-DPI

**Comment by ValdikSS** [comment]
Есть закреплённый #251, перенесите туда.
