### ISSUE TITLE
IP and ARP spoofing

### ISSUE THREAD

**Issue by Pantyhose-X** [ValdikSS/GoodbyeDPI#333]
### Describe your feature / Опишите ваше предложение

IP spoofing bypassing General IP Blocking. example Streaming Media Website blocks access to your country. Using the X-Forwarded-For HTTP Header Some can be bypassed, some can't.
###  ip spoofing
* X-Forwarded-For HTTP Header
`X-Forwarded-For`, `X-Originating-IP`, `X-Remote-IP`, `X-Remote-Addr` HTTP headers

### ARP spoofing
https://en.wikipedia.org/wiki/ARP_spoofing
https://en.wikipedia.org/wiki/Ettercap_(software)

ARP spoofing bypassing For example, DuckDuckGo Deep IP Filtering,  DuckDuckGo Using Iran ip to search NSFW you can't find any related sites, Settings: Region Changes the preferred region for search results. Invalid Search engine filters results based on ip

**Comment by ValdikSS** [comment]
> * X-Forwarded-For HTTP Header
>       `X-Forwarded-For`, `X-Originating-IP`, `X-Remote-IP`, `X-Remote-Addr` HTTP headers

It works in some cases, where the server is misconfigured, but in general it's rare to see it working.



> ARP spoofing bypassing For example, DuckDuckGo Deep IP Filtering, DuckDuckGo Using Iran ip to search NSFW

Did you confuse it with some other kind of spoofing? ARP doesn't work on the internet, it's a Ethernet segment protocol (your LAN).

**Comment by Pantyhose-X** [comment]
spoofing It's a good technique for getting around censorship, but people classify it as malicious.
Fast flux -- https://en.wikipedia.org/wiki/Fast_flux
Domain generation algorithm -- https://en.wikipedia.org/wiki/Domain_generation_algorithm
