### ISSUE TITLE
При запущенном GoodbyeDPI не работает Discord и прочие проблемы

### ISSUE THREAD

**Issue by CodeSpartan** [ValdikSS/GoodbyeDPI#336]
### Operating system / операционная система

Win 11 pro 10.0.22631

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Не работают Discord (в т.ч. ptb), не открываются некоторые сайты, например habr.com, не грузятся картинки на dtf.ru
Провайдер dom.ru
Стоит бесплатный антивирус Касперский.

**Comment by ArtemFaling** [comment]
Проблема с блокировкой адресов, советую просканить комп через Dr.Web - мне помогло

**Comment by ValdikSS** [comment]
Не похоже на ошибку в программе. Что-то более конкретное можно сказать только после анализа дампа трафика.

Внимательно читайте шаблон при создании issue, в нём подробно написано, что является багом, а что нет, и что нужно делать в том или ином случае.

**Comment by CureFlora** [comment]
Такая же проблема. Есть советы куда копать?

**Comment by Uthank** [comment]
Тоже дискорд умирает при включенном GoodbyeDPI. Если закрыть окно GoodbyeDPI, то дискорд сразу оживает

**Comment by Uthank** [comment]
Также еще в твиттере раз в 5-10 минут лочит аккаунт, приходится восстанавливать через телефон. В параметрах запуска GDPI не копался, накатил по ссылке для ютуба и в браузере Kyber выключил. Возможно есть какие-то параметры, которые это фиксят, и это не ошибка, но пока руки не дошли посмотреть

**Comment by NetDriver0** [comment]
та же самая проблема с дискордом

**Comment by blavonne** [comment]
Та же проблема

**Comment by Xxproner** [comment]
Мб это какое-то чудо, но после включения и выключения goodbye у меня заработал discord
