### ISSUE TITLE
Displays error 1062 on the latest version of Windows 10

### ISSUE THREAD

**Issue by ArtemFaling** [ValdikSS/GoodbyeDPI#337]
### Operating system / операционная система

Windows 10 Version 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

I don't know what to do

[
![ApplicationFrameHost_wQLqygxCcT](https://github.com/ValdikSS/GoodbyeDPI/assets/96381200/46b178ba-a4a6-49ce-bbb6-79fb96509e40)
![ApplicationFrameHost_JgpW5KYdRR](https://github.com/ValdikSS/GoodbyeDPI/assets/96381200/640aa716-c5ff-494d-b858-77aae507f4af)
](url)

**Comment by ValdikSS** [comment]
Well, does it work not as a service?

**Comment by ArtemFaling** [comment]
> Well, does it work not as a service?

As I understand it, no, I launch it through this file, but the service does not start
![explorer_sCx1AcA5yV](https://github.com/ValdikSS/GoodbyeDPI/assets/96381200/18af8f6b-5394-4ff4-b35d-df043758c6d8)

**Comment by ValdikSS** [comment]
Run 1_russia_blacklist_dnsredir

**Comment by ArtemFaling** [comment]
> Run 1_russia_blacklist_dnsredir

thanks, it's really help😌
