### ISSUE TITLE
Delays due to conflicts between programs and PC

### ISSUE THREAD

**Issue by Kyeronic** [ValdikSS/GoodbyeDPI#338]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

As a result of testing, even if you remove the current program after executing it, there is a delay for unknown reasons, and not only does the PC itself slow down, but it also ruins the overall activity.

The ISP has become unstable and the game itself refuses connections.

For example Call of Duty, Valorant, Ubisoft

**Comment by LazyDevv** [comment]
I had the same issue.
Fixed it by using Disk-Cleanup function from this [repository](https://github.com/Chuyu-Team/Dism-Multi-language).
Specifically cleaning the "WinINet Web Cache" fixed the issue for me.

**Comment by ValdikSS** [comment]
In some cases the WinDivert driver may stay loaded after you close the application. You can stop it using:

```
sc stop windivert
sc stop windivert1.4
sc delete windivert
sc delete windivert1.4
```

If the service was already unloaded/not existed, GoodbyeDPI has nothing to do with the issue you've described.
Additionally, windivert is not started automatically, rebooting the PC would completely eliminate any of its effect.
