### ISSUE TITLE
Полный DPI у домру

### ISSUE THREAD

**Issue by Corsten56** [ValdikSS/GoodbyeDPI#34]
Доброе время суток. :)

У меня несколько вопросов-предложений.
Провайдер Эртелеком - контора крупная, с сильным СОРМом.
Не работает ни ReQrypt, ни GoodbyeDPI. Пробовал все 4 режима.
Пробовал также с установленной службой и перезагрузками.
StopDPI тоже не работает, и к тому же его удалили с github.

Может быть встроить какую-то внутреннюю проверку в саму goodbyeDPI, а то совершенно не понятно почему не работает. 
Или возможно автоматический перебор методов.

VPN куплен на случай массовых блокировок с 01.11.2017, но могут и его заблокировать, так что ищутся альтернативные варианты.

Лог BlockCheck'а прикрепляю.
[domru-ertelekom.txt](https://github.com/ValdikSS/GoodbyeDPI/files/1395107/domru-ertelekom.txt)

**Comment by ValdikSS** [comment]
Поясните, как конкретно не работают программы. Судя по логу Blockcheck, GoodbyeDPI должен работать.

**Comment by Corsten56** [comment]
Вот скрины какие ошибки выдает Firefox и запущенной программы.
Соответственно запускаю ярлык к GoodbyeDPI от администратора с параметрами
-1 -a
-2 -a
-3 -a
-4 -a

Пробовал перезагружаться, чистить кэш браузера и flushdns. Картина не меняется.
![bitfinex1](https://user-images.githubusercontent.com/16915805/31768225-ddead298-b4e7-11e7-8c15-e89f1f5e2fa3.png)
![bitfinex1_goodbyedpi](https://user-images.githubusercontent.com/16915805/31768226-de1a7412-b4e7-11e7-81cd-43d5fabdcf5a.png)
![bitfinex2](https://user-images.githubusercontent.com/16915805/31768227-de4fbe24-b4e7-11e7-9b8c-d7fefb1b3a5e.png)
![bitfinex2_goodbyedpi](https://user-images.githubusercontent.com/16915805/31768228-de737238-b4e7-11e7-8871-72277e856f7e.png)
![bitfinex3](https://user-images.githubusercontent.com/16915805/31768229-de922e1c-b4e7-11e7-9bb0-744a74382369.png)
![bitfinex3_goodbyedpi](https://user-images.githubusercontent.com/16915805/31768230-deb5aa04-b4e7-11e7-8a64-63799a92c20c.png)
![bitfinex4](https://user-images.githubusercontent.com/16915805/31768232-def1d448-b4e7-11e7-9949-9a8521e02bb2.png)
![bitfinex4_goodbyedpi](https://user-images.githubusercontent.com/16915805/31768234-df147de0-b4e7-11e7-832a-e68c32d3032d.png)

**Comment by ValdikSS** [comment]
Blockcheck не умеет проверять возможность обхода DPI для HTTPS-сайтов. Попробуйте, например, зайти на rutracker.org по HTTP для проверки GoodbyeDPI.

**Comment by Corsten56** [comment]
Попробовал все 4 варианта - выдаётся стандартная заглушка http://lawfilter.ertelecom.ru/

**Comment by ValdikSS** [comment]
Возможно, она закешировалась. Попробуйте приватный режим браузера.

**Comment by Corsten56** [comment]
Попробовал в приватных режимах, тоже самое.
У меня два варианта почему так происходит:
1) Я что-то не так делаю, хотя всё вроде по инструкции.
2) GoodbyeDPI не может отработать по непонятным причинам.
Антивируса нет, файрвола и hips тоже. Защитник отключен. Система Win 8.1 x64 Pro.

Что ещё можно попробовать или проверить?

**Comment by Corsten56** [comment]
pbooru.com? У меня и без средств обхода открывается.
Рутрекер так и не открылся.
[rutracker-capture.zip](https://github.com/ValdikSS/GoodbyeDPI/files/1399470/rutracker-capture.zip)

**Comment by ValdikSS** [comment]
Вы что-то не то выложили. Не рутрекер.

**Comment by ValdikSS** [comment]
Так, стоп, вы знаете, что вам нужно использовать dnscrypt?

**Comment by Corsten56** [comment]
А вот про днскрипт я и не знал.

В итоге Simple DNSCrypt + GoodbyeDPI в 1 режиме - всё заработало.
Спасибо.

**Comment by whocares7777** [comment]
> А вот про днскрипт я и не знал.
> 
> В итоге Simple DNSCrypt + GoodbyeDPI в 1 режиме - всё заработало. Спасибо.

А можно по подробнее?
У меня просто та же проблема. Что там в этом вашем Simple DNSCrypt жать?
