### ISSUE TITLE
No internet after deleting GoodbyeDPI

### ISSUE THREAD

**Issue by Trioon** [ValdikSS/GoodbyeDPI#341]
### Operating system / операционная система

Windows 11 

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

I tried the program but it didn't work so i just deleted it , now the wifi that i used the program on it does not work AT ALL tried every youtube how to fix video and NOTHING Worked , other wifis work fine but this exact one doesn't work which i need  the most

### Additional information / Дополнительная информация

i get DNS_PROBE_finished_no_internet

**Comment by ValdikSS** [comment]
It's unlikely to have something with the software. Try another PC/phone with this network, it's likely won't work either.
