### ISSUE TITLE
Сайт rutracker.org открывает, но не прогружает полностью

### ISSUE THREAD

**Issue by slayernn** [ValdikSS/GoodbyeDPI#342]
### Operating system / операционная система

Win10 1903, Win10 22H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Пров Билайн Краснодар
Примерно с неделю перестал заходить нормально на сайт rutracker.org
Пробовал с 3х машин - ни с одной не заходит
NNmclub.to нормально открывает, видеосервисы - открывает. Всё отлично. А этот нет
Для начала скажу, роутер перезагружал
flushdns делал
использовал хром в связке doh cloudflare или dns.sb 
https://i123.fastpic.org/big/2024/0330/d1/c18e730bdcfafee2c117b9a2102cfdd1.png

с vpn таких проблем нет

использовал стандартные связки service_russia_blacklist
еще такие связки, не работают, с ttl отличным от 5 вообще ничего не открывает
goodbyedpi.exe -1 --wrong-chksum --set-ttl 5 --blacklist ..\blacklist.txt
goodbyedpi.exe -p -r -s -m --set-ttl 3 --blacklist ..\blacklist.txt
goodbyedpi.exe -1 -p -r -s -m --set-ttl 3 --blacklist ..\blacklist.txt
goodbyedpi.exe -1 --set-ttl 3 --blacklist ..\blacklist.txt

менял браузеры, менял dns - результат тот же.  Доступ к rutracker.org критичен для меня, надеюсь на вашу помощь

**Comment by slavassh** [comment]
Попробуйте обновить russia-blacklist.txt
В комментариях официальной группы рутрекера в ВК пишут, что часть ресурсов сайта грузится с домена rutracker.cc, которого не было в старом списке антизапрета.
Мне помогло.

**Comment by slayernn** [comment]
> Попробуйте обновить russia-blacklist.txt В комментариях официальной группы рутрекера в ВК пишут, что часть ресурсов сайта грузится с домена rutracker.cc, которого не было в старом списке антизапрета. Мне помогло.
Спасибо добрый человек, обновил список. Теперь сайт работает нормально
Очень благодарен
