### ISSUE TITLE
Using it without the Command Prompt / Использование его без командной строки 

### ISSUE THREAD

**Issue by NiKola-UE** [ValdikSS/GoodbyeDPI#343]
### Describe your feature / Опишите ваше предложение

Hello, 

As a blind person, I cannot use GoodbyeDPI in the Command Prompt. Please enable this to work with keyboard cursor and with all available and new features and shortcuts if any. 

Привет,

Как слепой, я не могу использовать GoodbyeDPI в командной строке. Пожалуйста, включите это, чтобы работать с курсором клавиатуры и со всеми доступными и новыми функциями и сочетаниями клавиш, если таковые имеются.

**Comment by ValdikSS** [comment]
> As a blind person, I cannot use GoodbyeDPI in the Command Prompt.

Huh, why? I thought this is the most accessible and easy to use interface for the blind person.

**Comment by NiKola-UE** [comment]
I take your word for it, but I just can't make it. I tried several times, but it won't work. Maybe it's a problem with screen readers, but that's another matter. Although, with other similar tools, like GreenTunnel or PowerTunnel everything works as it should. 


Thank you for your effort though.

**Comment by ValdikSS** [comment]
Do you have experience with other command-line tools?

There's no graphical user interface. You need to use it using the console. You supply the options you need in the console as the arguments after the .exe file, then the application stats and prints out text, in case of GoodbyeDPI this is just a configuration information.

That's all. For GoodbyeDPI, sane configuration is already set by default, all you need in general is just to run the .exe file without arguments, or use one of the included .cmd files.

**Comment by NiKola-UE** [comment]
"Do you have experience with other command-line tools?
There's no graphical user interface. You need to use it using the console." 

> 





Yes, that's where my biggest problem is. I thought that the program could somehow work independently of Command Prompt, as it were, in some other mode (roughly like the mentioned two tools), but well... The trouble is that screen readers are quite poorly or not customized to the graphical console at all, and I would it would be useful if I could use the keyboard cursor for navigation if it could somehow be done. If he really can't, that's okay - it doesn't even matter...

**Comment by rdavydov** [comment]
Hello, @NiKola-UE !

Maybe you can just launch `service_install_russia_blacklist.cmd` or `service_install_russia_blacklist_dnsredir.cmd` to install and start the service. And later launch `service_remove.cmd` to stop and remove it.

Essentially they're like shortcuts to on/off GoodbyeDPI that leave no open console windows. But they both require to be run as an Administrator.

There is also an abandoned repository of [GUI for GoodbyeDPI](https://github.com/Include-sys/GUI-for-GoodbyeDPI). No guarantees that it'll work, but may be worth to check it out if you're really want to use GoodbyeDPI without any console interaction.

**Comment by NiKola-UE** [comment]
Thank you for try to help me, but my problem is not that. So, it is not about any specific blocking or interruption of the Internet, but simply about the fact that I cannot navigate in the program with the keyboard, using only the arrows, Tab, Alt, Space and Enter keys, because the interface is intended exclusively for the Command Prompt, which of course I have nothing against, but for technical reasons we does not match. If you compare it with the tools I referred to, 
[(GreenTunnel ](https://github.com/SadeghHayeri/GreenTunnel) 
and 
[PowerTunnel) ](https://github.com/krlvm/PowerTunnel) 
maybe it will be clearer to you what I'm talking about because their interface suits me completely, they are based on a different principle, but their purpose is the same or similar. 


So, my only problem is that GDPI is not so a keyboard-friendly.

**Comment by rdavydov** [comment]
The program does not have a user interface as such; after launch, it only displays statistical and debugging information about its operation. There is no navigation there at all. All control of the program is carried out by passing the necessary parameters on the command line when starting the program. After starting the program, nothing can be changed, user can only stop the program and start again with the new parameters.

One can understand that such interaction would be almost impossible for the Screen Reader. For these purposes, it is necessary to develop a GUI that can be controlled not only by the mouse, but also by the keyboard, so that you can switch between controls using the keyboard.

Have you looked at [GUI for GoodbyeDPI](https://github.com/Include-sys/GUI-for-GoodbyeDPI), does it not meet your requirements?

**Comment by NiKola-UE** [comment]
Yes, that is correct! I am glad that you understood everything perfectly and explained it correctly. Everything you said is absolutely correct. Perhaps the solution would be for the next version to be better adapted and more accessible to some users. I repeat: I don't mind the user interface being graphical and minimalistic, but I'm not very good with Command Prompt and I don't have the necessary technical knowledge to use it. 



It wouldn't be bad if there were two different versions: one that would continue the previous one and the other with a slightly more complex and full text interface with maybe some more options that would be more suitable for users like me.

**Comment by ValdikSS** [comment]
> I'm not very good with Command Prompt and I don't have the necessary technical knowledge to use it.

There aren't any knowledge requirements. I believe you're just overthinking the concept. The concept is super simple and plain: you read the README text and execute the software with the necessary options, entering them manually, just like you'd write the text in the text editor.

There's nothing to read in the output after the program is started, nothing to interact with.

Anyway, graphical user interface is not planned.

**Comment by NiKola-UE** [comment]
I understand what you mean, but as far as I know, to use the Command Prompt you need to know the MS Dos language, but I don't know it. 


I don't need a graphical interface. I need a full text and keyboard-friendly interface to be able to use the program for the reasons I have already described, which you can do in the next version. Without it, the instructions mean nothing to me, because without it I can't move in the program.

**Comment by ValdikSS** [comment]
@NiKola-UE, as I told earlier, there's no interface, thus no interaction with the application possible while it's already running. There isn't to move anywhere, nothing to navigate keyboard into. The application is designed to be run unattended, without any user attendance whatsoever.

> to use the Command Prompt you need to know the MS Dos language

No, you don't need to know that.

The application is designed to be used with default settings unless it doesn't work or you want another settings. There's just _no need_ to change anything. Just run the goodbyedpi.exe, and if it works, it works.

If you want to learn more, the top answer from [Quora](https://www.quora.com/How-do-you-run-a-console-application-on-a-Windows-operating-system) seems to explain in pretty well.

**Comment by NiKola-UE** [comment]
If I understand correctly, the application just needs to be launched and then it will do everything it needs to in the background, right? 


But how do I know exactly if it works or not? Thus, the GreenTunnel bar shows whether it is on or not and has a button / switch for that. There isn't even that here.

**Comment by ValdikSS** [comment]
If it runs, it works. Try opening blocked website. When you close it, it stops working.

**Comment by NiKola-UE** [comment]
Thank you, everything is clearer to me now. 




However, I cannot say what the results will be because here in Serbia there are no specific sites that are reliably known to be blocked, but privacy is being violated more and more, although it is done quite trivially. 



When you publish a new version, please add a notification, balloon, bubble or anything similar; purely because of the intuitive appearance of the program, if it is not a problem.
