### ISSUE TITLE
After running the program once, gradle and curl cannot connect to certain https websites

### ISSUE THREAD

**Issue by rusnuker** [ValdikSS/GoodbyeDPI#344]
### Operating system / операционная система

Windows 10 21H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

After running `1_russia_blacklist_dnsredir.cmd` once, certain programs cannot read certain websites. As of now, I found only three websites that curl has trouble connecting to (hangs with no output): `blackspigot.com`, `repo.spongepowered.org` and `files.minecraftforge.net`. Opening them in any browser works fine. I also noticed that it reads fine without `https://`. I tried many things to make it work again, including flushing the dns cache and trying to connect with goodbyedpi running, nothing worked.

### Additional information / Дополнительная информация

I'm pretty sure this is a GoodbyeDPI problem, because I didn't install any software except this.

**Comment by ValdikSS** [comment]
If the program is not running, it's not effective. The websites mentioned are not reachable due to the block in Russia.
https://community.cloudflare.com/t/russia-blocks-tls-v1-2-requests-to-cloudflare-edges/636460

**Comment by rusnuker** [comment]
I'm pretty sure these websites worked fine before running the program. `repo.spongepowered.org` and `files.minecraftforge.net` are Maven repositories, I had been using them for a long time now.

**Comment by ValdikSS** [comment]
All these domains are Cloudflare-fronted.

**Comment by rusnuker** [comment]
I know.

**Comment by rusnuker** [comment]
This doesn't make any sense: it worked before, now these websites only open in browsers which don't have any bypassing extensions installed, and running GoodbyeDPI any-country doesn't work either.

**Comment by rusnuker** [comment]
fixed it, ran `Disable-TlsCipherSuite -Name TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` in an admin powershell
