### ISSUE TITLE
[Regression] Roblox Player is unable to launch/update/download when GoodbyeDPI enabled.

### ISSUE THREAD

**Issue by Derpitron** [ValdikSS/GoodbyeDPI#345]
### Operating system / операционная система

Windows 11 23H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Crashing Application: Roblox Player
Suspected cause: GoodbyeDPI.exe (source: from https://github.com/ValdikSS/GoodbyeDPI)

Application Error:
![image](https://github.com/ValdikSS/GoodbyeDPI/assets/46134462/5f02a731-fe90-4d74-963e-b38b9ae820a2)

Application Crash Log (sensitive details censored:
[0.619.0.6190508_20240406T093842Z_Player_FC63C_last.log](https://github.com/ValdikSS/GoodbyeDPI/files/14893131/0.619.0.6190508_20240406T093842Z_Player_FC63C_last.log)

GoodbyeDPI version: `0.2.2`
When the problem first started occuring: `03-April-2024`

Custom GoodbyeDPI service install script/config I used (I made it myself by taking `service_install_russia_blacklist_dnsredir.cmd` script, then removing `--blacklist`, and changing the DNS settings to use Quad9 DNS's ip addresses):
<details>
<summary>Details</summary>

```cmd
@ECHO OFF
PUSHD "%~dp0"
set _arch=x86
IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)

echo This script should be run with administrator privileges.
echo Right click - run as administrator.
echo Press any key if you're running it as administrator.
pause
sc stop "GoodbyeDPI"
sc delete "GoodbyeDPI"
sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -5 --dns-addr 9.9.9.9 --dns-port 1253 --dnsv6-addr 2620:fe::fe --dnsv6-port 1253" start= "auto"
sc description "GoodbyeDPI" "Passive Deep Packet Inspection blocker and Active DPI circumvention utility"
sc start "GoodbyeDPI"

POPD

```

</details>

### Additional information / Дополнительная информация

How I know that GoodbyeDPI is the problem: I killed each running process one by one, testing the application each time. When the application resumed working as normal, GoodbyeDPI.exe was the last process I killed. Thus killing GoodbyeDPI.exe solved the problem.

How I know that my custom config is Not the problem: The application functioned completely normally for months before this, while my custom configuration was active.

I will also file a bug report with Roblox itself. Perhaps this regression is the fault of an application update.

**Comment by ReinRaus** [comment]
РосТелеком, домашний интернет, Мурманская область - минимально необходимые настройки для работы всех сайтов отмечены галочками, но из-за двух галочек, которые я выделил красным Roblox Player и Roblox Studio не могут загружать ресурсы :(
![Снимок экрана 2024-04-10 135124](https://github.com/ValdikSS/GoodbyeDPI/assets/693231/9500ef9a-8e7c-411c-8f0d-8f65594f3ee9)

**Comment by Derpitron** [comment]
Sorry I cannot read Russian. Please tell me what GUI program this is, and what settings those are which you've highlighted? Thanks

**Comment by ReinRaus** [comment]
> Sorry I cannot read Russian. Please tell me what GUI program this is, and what settings those are which you've highlighted? Thanks

GUI: GoodbyeDPI Launcher

The selected items are the minimum settings of my provider.

Red highlight - elements that break the work of Roblox.

**Comment by Derpitron** [comment]
Thank you. I'll research more on it.

**Comment by ValdikSS** [comment]
Your cmd file contains:
`--dns-addr 9.9.9.9 --dns-port 1253 --dnsv6-addr 2620:fe::fe --dnsv6-port 1253`

There's no DNS resolvers on 9.9.9.9 port 1253 or 2620:fe::fe port 53.

```
$ dig www.com @9.9.9.9 -p1253
;; communications error to 9.9.9.9#1253: host unreachable
;; communications error to 9.9.9.9#1253: host unreachable
;; communications error to 9.9.9.9#1253: host unreachable

; <<>> DiG 9.18.24 <<>> www.com @9.9.9.9 -p1253
;; global options: +cmd
;; no servers could be reached
```

**Comment by Derpitron** [comment]
> Your cmd file contains: `--dns-addr 9.9.9.9 --dns-port 1253 --dnsv6-addr 2620:fe::fe --dnsv6-port 1253`
> 
> There's no DNS resolvers on 9.9.9.9 port 1253 or 2620:fe::fe port 53.
> 
> ```
> $ dig www.com @9.9.9.9 -p1253
> ;; communications error to 9.9.9.9#1253: host unreachable
> ;; communications error to 9.9.9.9#1253: host unreachable
> ;; communications error to 9.9.9.9#1253: host unreachable
> 
> ; <<>> DiG 9.18.24 <<>> www.com @9.9.9.9 -p1253
> ;; global options: +cmd
> ;; no servers could be reached
> ```

If this is the case then how/why did it work normally for months until recently?

**Comment by ValdikSS** [comment]
No idea. Probably you have DNS over HTTPS enabled OS-wide.

**Comment by Derpitron** [comment]
> No idea. Probably you have DNS over HTTPS enabled OS-wide.

You mean, DNS over HTTPS is what is causing the problem?

**Comment by ValdikSS** [comment]
The problem is that you're trying to use DNS which doesn't work.
