### ISSUE TITLE
Запускаю 0_russia_update_blacklist_file и выдает ошибку

### ISSUE THREAD

**Issue by Agnatuti** [ValdikSS/GoodbyeDPI#346]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

![изображение](https://github.com/ValdikSS/GoodbyeDPI/assets/88045371/fb0b1407-9fa1-4159-b2df-b2c2935f3ce5)

### Additional information / Дополнительная информация

Конечно мб дело в провайдере Yota

**Comment by Agnatuti** [comment]
бля а я это не как сервис запускал просто в форме заполнил случайно

**Comment by TaplierShiru** [comment]
Не совсем понятны детали запуска, однако судя по ошибке - она связана с не возможностью стянуть актуальный лист сайтов в `russia-blacklist.txt` с соотв. сайта. Ранее была уже подобная ошибка [тут](https://github.com/ValdikSS/GoodbyeDPI/issues/251#issuecomment-2057950074). Там предлагается несколько решений проблемы (нужно заменить команду скачивания файла `russia-blacklist.txt` в файле `0_russia_update_blacklist_file.cmd`). Сам txt можно скачать вручную с соотв. сайтов и сохранить под именем `russia-blacklist.txt`, далее запуская программу через `1_russia_blacklist_dnsredir.cmd` или `1_russia_blacklist.cmd`. Я протестировал сейчас пару команд из того поста, и мне удалось скачать файл команде из 2 предложения.
Соотв. файл `0_russia_update_blacklist_file.cmd` выглядит так:
```
@ECHO OFF
PUSHD "%~dp0"
powershell -c "irm https://p.thenewone.lol:8443/domains-export.txt -outfile russia-blacklist.txt"
POPD
```
Если это не поможет, то в [посте ](https://github.com/ValdikSS/GoodbyeDPI/issues/251#issuecomment-2057950074)есть еще варианты.

**Comment by BlackMightyRavenDark** [comment]
А зачем вообще нужен файл `russia-blacklist.txt`? Я не вижу разницы при запуске с ним и без него. Сайты, которые открываются - открываются и без этого файла.
А, например, `rutracker.org` не открывается никак. Просто выдаёт разные ошибки в зависимости от того, с какими параметрами запущен `goodbyedpi.exe`.

**Comment by BlackMightyRavenDark** [comment]
> было так

Да,  и правда. Уже заметил. Некоторые сайты не работают, если их нет в списке. Но рутрекер и nnm-club не пробивает (ни в каком виде не открываются).
А на другом компе (с другим провайдером) происходит как у вас. И рутрекер там работает. NNM-club не пробовал.

**Comment by ValdikSS** [comment]
Домен заблокирован, поэтому файл не скачивается. Скачайте его вручную через VPN/прокси.
