### ISSUE TITLE
Резко перестало работать, не знаю в че проблема

### ISSUE THREAD

**Issue by ArtemFaling** [ValdikSS/GoodbyeDPI#347]
### Operating system / операционная система

 Windows 10  20H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

![msedge_HRi8T8l0AV](https://github.com/ValdikSS/GoodbyeDPI/assets/96381200/7169c624-c9d7-41d8-a308-45e67eeea4e3)
Перестало работать, причина не известна. Запускаю и через 1_russia_blacklist_dnsredir и 2_any_country_dnsredir, но не работало.
![image](https://github.com/ValdikSS/GoodbyeDPI/assets/96381200/7ef08a1a-9540-46ac-88af-7146e44d8ac4)

**Comment by ArtemFaling** [comment]
обычный vpn работает

**Comment by hamitozdemir** [comment]
I noticed now you need to refresh the website you're trying to access like 5-10 times. Having the same issue since 2 days ago.

**Comment by anon567321** [comment]
Дело в последнем обновлении Хрома. Зайдите в `chrome://flags/`, найдите флаг `#enable-tls13-kyber`, отключите его и перезапустите хром.

**Comment by hamitozdemir** [comment]
Thank you! Seems to have fixed the issue for me. #340 is a possibly related issue. Appreciate the help.

**Comment by ValdikSS** [comment]
Unlikely to be a software issue.
Refer to https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark to record the dump and check what's in there.

**Comment by anon567321** [comment]
Отправил на `iam@valdikss.org.ru` 4 дампа трафика, вкл/выкл GoodbyeDPI + вкл/выкл TLS 1.3 hybridized Kyber support (#enable-tls13-kyber).
Дамп для рутрекера `host 104.21.32.39 or 172.67.182.196`
Открывается только в режиме GoodbyeDPI on TLS 1.3 hybridized Kyber support off

**Comment by ValdikSS** [comment]
> Открывается только в режиме GoodbyeDPI on TLS 1.3 hybridized Kyber support off

Да, в этом и проблема. См. https://github.com/ValdikSS/GoodbyeDPI/issues/330
