### ISSUE TITLE
Doesn't work on Google Chrome for me anymore. All is fine on all other browsers.

### ISSUE THREAD

**Issue by metalslayer** [ValdikSS/GoodbyeDPI#348]
### Operating system / операционная система

Windows 11 23H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Doesn't work on Google Chrome for me anymore. All is fine on all other browsers.

### Additional information / Дополнительная информация

Doesn't work on Google Chrome for me anymore. All is fine on all other browsers.

**Comment by metalslayer** [comment]
Disabled Kyber on Chrome flags and now it's working

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/330
