### ISSUE TITLE
Не работает GoodbyeDPI, VPN не работает  (тем что пользовался), форум ntc.party открыть возможности нет

### ISSUE THREAD

**Issue by VolodyaUrban** [ValdikSS/GoodbyeDPI#349]
### Operating system / операционная система

Windows 22H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Конец близок (чебурнет), только ты герой ([ValdikSS](https://github.com/ValdikSS)) можешь его остановить!
Я очень надеюсь, что у тебя все получится!

**Comment by kp6ic** [comment]
Да, перестал работать от слова совсем.

**Comment by anon567321** [comment]
Если у тебя Хром, попробуй это:
Зайдите в chrome://flags/, найдите флаг #enable-tls13-kyber, отключите его и перезапустите хром.

**Comment by kp6ic** [comment]
> Если у тебя Хром, попробуй это: Зайдите в chrome://flags/, найдите флаг #enable-tls13-kyber, отключите его и перезапустите хром.

заработало, благодарю

**Comment by mrEluminate** [comment]
А есть какие-то варианты для Фаерфокс?

**Comment by VolodyaUrban** [comment]
> Если у тебя Хром, попробуй это:
> Зайдите в chrome://flags/, найдите флаг #enable-tls13-kyber, отключите его и перезапустите хром.

Спасибо, целую в попу

**Comment by Tapo4ek87** [comment]
здравствуйте
а с opera есть решение?

**Comment by MsKolai** [comment]
> Если у тебя Хром, попробуй это: Зайдите в chrome://flags/, найдите флаг #enable-tls13-kyber, отключите его и перезапустите хром.

спасибо тебе огромнийшее, благодаря тебе я не только снова почувствовал вкус свободного интернета, но и вспомнил, что у меня оказывается был акк на гитхабе <3

**Comment by dope6630** [comment]
Не работает. "флаги" отключал, вчера все работал и спокойно смотрел ютубчик, сседня не пашет, чтоб эти мрази из ркн дристали кровавым поносом полгода по 10 часов в сутки за блок ютуба из-за ущемленок политических.

**Comment by izogfif** [comment]
@dope6630 Возможно, у вас Windows 11? В любом случае, попробуйте создать (если еще нет) виртуальную машину с Windows 10 (64-битной) и запустить программу там. Может, заработает?

**Comment by lony256** [comment]
> Если у тебя Хром, попробуй это: Зайдите в chrome://flags/, найдите флаг #enable-tls13-kyber, отключите его и перезапустите хром.

всё равно не работает

**Comment by SGrek** [comment]
> @dope6630 Возможно, у вас Windows 11? В любом случае, попробуйте создать (если еще нет) виртуальную машину с Windows 10 (64-битной) и запустить программу там. Может, заработает?

Неа, на 10-ке не работает

**Comment by Vitobe** [comment]
0.2.2 работает. Но некоторые сайты не открывает такие как artstation и sketchfab.com.А например Pinterest и авито открывает. Почему?

**Comment by Vitobe** [comment]
Если на artstation зайти заранее(открыть вкладку до включения  GoodbyeDPI)все работает. А вот на sketchfab.com не грузятся модельки(это сайт с 3д моделями)

**Comment by Monvis** [comment]
Не работает. Файл запущен, флаг отключён, никаких изменений
