### ISSUE TITLE
goodbyedpi огранчивает скорость сети

### ISSUE THREAD

**Issue by krab** [ValdikSS/GoodbyeDPI#35]
Goodbyedpi установлен как служба через nssm.
Если смотреть видео на twitch при этом запустить загрузку игры в steam то интернет из 50мбит превращается где-то в 20-30 + на твитч начинает тормозить вплоть до 160p, steam качает 3.3 MB.
Если же остановить службу goodbyedpi то никаких проблем нет, твитч 720/1080, steam 6 MB.
При этом в диспетчере задач видно что goodbyedpi.exe грузит CPU всего на 2-3% редко 4%.

**Comment by ValdikSS** [comment]
В WinDivert есть известные проблемы производительности, но они проявляются на гигабитных скоростях. Какую версию GoodbyeDPI и WinDivert вы используете?

**Comment by krab** [comment]
Windows пишет что WinDivert64.sys 1.1.8, узнать версию goodbyedpi июня месяца. Сейчас попробую https://github.com/ValdikSS/GoodbyeDPI/releases/tag/0.1.1

**Comment by krab** [comment]
С goodbyedpi 0.1.1 steam загружает все нормально, с максимальной скоростью как и без него, проблема была в версии релиза от июня.

Тем не менее интересно как Диспетчер задач отображает скорость сети.
С goodbyedpi в диспетчере steam отображается как 60 Мбит/с, без него 12 Мбит/c.
Proccess Explorer в то время в обоих случаях 12 Мбит/c.
Сам же steam в обоих случаях загружает одинаково примерно 6 MB/s, судя по его GUI.
