### ISSUE TITLE
Не работает на Ноутбуке

### ISSUE THREAD

**Issue by AlexNTFox** [ValdikSS/GoodbyeDPI#350]
### Operating system / операционная система

Windows 11 Pro, 23H2, Лицензия

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Доброго времени суток!

Программа почему-то не работает на новом ноутбуке. Устанавливал, настраивал, все как по инструкции. Сайты как не открывались, так и не открываются.
На компьютере с Windows 10 Pro, на 22H2, лицензии все работает как часы. Ни от WIFI ни от Кабеля Goodbyedpi работа никак не меняется. 
Готов предоставить любые логи в помощь, главное какие и инструкции.

**Comment by ValdikSS** [comment]
Внимательно читайте шаблон. Это не ошибка программы.
