### ISSUE TITLE
GoodbyeDPI doesn't seem to affect Brave Browser

### ISSUE THREAD

**Issue by tipsyConfection** [ValdikSS/GoodbyeDPI#351]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Brave, for some reason, isn't affected by active GoodbyeDPI, so if a website is blocked — I still can't open it in Brave while easily opening it in any other browser (Firefox, Chrome, Edge, Opera GX).

### Additional information / Дополнительная информация

I tried turning off Security measures in it, but got no result, still won't load.

**Comment by yediw14352** [comment]
chrome://flags/#enable-tls13-kyber set to "Disabled"

**Comment by tipsyConfection** [comment]
> chrome://flags/#enable-tls13-kyber set to "Disabled"

Works now! Bless you.

**Comment by tputraa** [comment]
some of website still cannot be accessed with brave, can you download chrome extension?
