### ISSUE TITLE
curl can't complete handshake with blocked websites (TLS v1.2 0x16 0x03 0x03)

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [ValdikSS/GoodbyeDPI#353]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

The blocked websites work fine in the Firefox browser, but curl can't access them.
Here is an example:
```
>curl -v https://rutracker.org
* Host rutracker.org:443 was resolved.
* IPv6: (none)
* IPv4: 104.21.32.39, 172.67.182.196
*   Trying 104.21.32.39:443...
* Connected to rutracker.org (104.21.32.39) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: D:\curl\bin\curl-ca-bundle.crt
*  CApath: none
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to rutracker.org:443
* Closing connection
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to rutracker.org:443
```

**Comment by ValdikSS** [comment]
Provide the pcap dumps of both Firefox and cURL.
https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark

**Comment by ValdikSS** [comment]
GoodbyeDPI does not handle "TLSv1.2" record version handshakes yet.

https://github.com/ValdikSS/GoodbyeDPI/blob/4a82fd442dcdd69de731fb717fb055f8547083fa/src/goodbyedpi.c#L1132

**Comment by ValdikSS** [comment]
Try it, it should work.
https://github.com/ValdikSS/GoodbyeDPI/actions/runs/9307102451
Please report if it still doesn't.

**Comment by WPMGPRoSToTeMa** [comment]
It works, thanks!
