### ISSUE TITLE
GoodBye DPI doesn't work at all

### ISSUE THREAD

**Issue by semaidk** [ValdikSS/GoodbyeDPI#354]
### Operating system / операционная система

Windows 11 Pro 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Hello there. In my personal and work PCs Goodbye DPI doesn't work at all. I've tried everything, installing all components, fully remove the service from system and re-download it (all actions were performed with admin rights), but there's still no changes.

Location: **Russia.**

**Comment by fireaid** [comment]
Какие сайты не работают у тебя?

**Comment by ValdikSS** [comment]
That doesn't sound like an application bug. Please don't skip the text, it's written on purpose.

**Comment by NumericSpace** [comment]
soundcloud работает, а youtube нет, ничего не помогает
