### ISSUE TITLE
Soundcloud.com not working with enabled --blacklist russia-blacklist.txt 

### ISSUE THREAD

**Issue by titemov** [ValdikSS/GoodbyeDPI#358]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

with "--blacklist \russia-blacklist.txt" argument soundcloud does not work, meanwhile without --blacklist it works perfecrly fine. I guess there is hostname somehow related to soundcloud in this list, but I cannot found it. I wish you can help me or tell me what am I doing wrong. Thanks! 

### Additional information / Дополнительная информация

Not working here (with blacklist):
![изображение](https://github.com/ValdikSS/GoodbyeDPI/assets/105934494/1f944755-ee29-4c9c-97f0-cd5062a590cb)
Working here (without blacklist):
![изображение](https://github.com/ValdikSS/GoodbyeDPI/assets/105934494/28a9fbb7-50fe-473c-a125-bc912fb20d7d)

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark

**Comment by titemov** [comment]
Just send you an email at [iam@valdikss.org.ru](mailto:iam@valdikss.org.ru)

**Comment by ValdikSS** [comment]
> I guess there is hostname somehow related to soundcloud in this list, but I cannot found it

Well, is there soundcloud.com domain in the list?

**Comment by titemov** [comment]
I had the same thought when i first ran into the problem. I was trying find some and it didnt workout there is no matches. I tried to find "soundcloud.com" "*sndcld*" "*snd*" "*soundcloud*" and no mathces. I guess there is some hosting services name that is blocked like cloudfare or smth

**Comment by ValdikSS** [comment]
Well, what's the issue then? Just add it to the list.

**Comment by titemov** [comment]
there is a funny thing: i had same problem with rutracker.org (Not working with blacklist enabled and working without blacklist) and after I REMOVED "rutracker.org" string from russia-blacklist.txt this website started working no matter if blacklist enabled or disabled. thats why I created this thread

**Comment by Jeefrect** [comment]
> I tried to find "soundcloud.com" "sndcld" "snd" "soundcloud" and no mathces.

```
soundcloud.com
api.soundcloud.com
feeds.soundcloud.com
media.soundcloud.com
cf-media.sndcdn.com
edge-api.soundcloud.com
w1.sndcdn.com
api-v2.soundcloud.com
assets.soundcloud.com
secure-media.soundcloud.com
```
Extended list:
```
soundcloud.com
api.soundcloud.com
feeds.soundcloud.com
media.soundcloud.com
cf-media.sndcdn.com
edge-api.soundcloud.com
w1.sndcdn.com
api-v2.soundcloud.com
assets.soundcloud.com
secure-media.soundcloud.com
cf-hls-media.sndcdn.com
cf-media.sndcdn.com
sndcdn.com
mobi.soundcloud.com
promote-v2.soundcloud.com
charts.soundcloud.com
developers.soundcloud.com
checkout.soundcloud.com
pre-pnd.soundcloud.com
pnd.soundcloud.com
help.soundcloud.com
support.soundcloud.com
```
