### ISSUE TITLE
Help disable GoodbyeDPI

### ISSUE THREAD

**Issue by Elder178** [ValdikSS/GoodbyeDPI#359]
### Operating system / операционная система

Win 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Greetings!
Sometimes it happens that a user who is far from programming finds a complex program that is clearly not intended for him, and for some reason turns it on.

Please tell me how to completely disable its effect? Is it enough to delete or does it overwrite some network parameters?

The following parameters were applied:
russia_blacklist_dnsredir.cmd
Service_delete

**Comment by ValdikSS** [comment]
It does not overwrite any parameters. When the program is not running, it's not running.
If you have installed it as a service (used `service_install`), then run `service_delete`. If you just ran it as a regular application, just close the window.
