### ISSUE TITLE
Проблема в работе uTorrent при запущенном сервисе

### ISSUE THREAD

**Issue by Kommunist7304** [ValdikSS/GoodbyeDPI#36]
Russian language:

Доброго дня!
До начала этой недели все работало прекрасно, но сейчас началась одна неприятная проблема.
Мой конфиг: Win 10 Pro x64 Build 1709 с последними обновлениями, uTorrent 3.5 build 44090 (проверил на версии 2.0 - тоже наблюдается проблема), KES 10.3.0.6294.
Суть проблемы: при запущенном сервисе GoodByDPI последней версии 0.1.1 ломается запрос к трекеру http://bt9.tracktor.in (трекер лостфильма) и он начинает отдавать 400 ошибку. Пробовал менять параметр запуска -4 на -3 и -2, проблема остается. Проблем с другими трекерами не наблюдается.
uTorrent и сервис добавлены в исключения антивируса.
Провайдер Билайн (L2TP), но интернет раздает гигабитный маршрутизатор.

Спасибо за Ваш проект и надеюсь данную проблему удастся исправить или как-то обойти без отключения сервиса.

**Comment by ValdikSS** [comment]
У меня он вообще не работает. Там точно порт 80?

**Comment by Kommunist7304** [comment]
Спасибо за ответ!
Полная ссылка в качестве примера: http://bt99.tracktor.in/tracker.php/f7c152a62e233bb4b542bb3eae95a5c2/announce

**Comment by ValdikSS** [comment]
Вы ошиблись в домене в первом сообщении.
Полагаю ссылка содержала работающий ключ, я его отредактировал.

HTTP-сервер на этом домене не может обработать заголовок без пробела в разделителе. Стандарт HTTP гласит, что любой HTTP-сервер должен обрабатывать заголовки с любым количеством пробелов в разделителе (в том числе и без пробелов вообще). Вам нужно связаться с администратором сервера и сказать ему об этом.

**Comment by ValdikSS** [comment]
В GoodbyeDPI 0.1.2 добавлен механизм черного списка, теперь незаблокированные сайты не обрабатываются программой.

**Comment by Kommunist7304** [comment]
Можно ли механизм работы с черным списком внести параметром чтобы программа сама обновляла список, допустим раз в сутки/при запуске (что наступит раньше)?
Например у меня сейчас прописаны параметры:
goodbyedpi.exe -4
А было бы например: goodbyedpi.exe -4 --blacklist ..\blacklist.txt -blacklistAU

В чем смысл моей хотелки: я ставлю утилиту автономно на некоторые ПК и не хотелось бы там обновляться вручную или плодить задачи в планировщике. Автообновление списка в зависимости от ситуации: если стартует прога, то тут же пытается обновить список. Если сервер недоступен, то следующее обновление будет в 01:00 следующего дня (для круглосуточно работающих ПК актуально).
Спасибо за Ваш проект.

**Comment by r4sas** [comment]
@Kommunist7304 наполнение блеклиста полностью лежит на ваших плечах.
