### ISSUE TITLE
It stopped working in Yandex Browser and Chrome

### ISSUE THREAD

**Issue by denmorgenshtern** [ValdikSS/GoodbyeDPI#361]
### Operating system / операционная система

Windows 23H2 22631.3737

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

It stopped working in Yandex Browser, Chrome, Opera and Edge for a couple of days. Everything is OK in Firefox only. 
Probably some kind of Chromium update broke?

GoogleDPI itself runs normally, without errors. It's very similar to a chromium update because I first noticed it on one computer and it continues worked on the second. A day later it stopped working on the second computer. Maybe the chromium had been updated or Windows?.

**Comment by denmorgenshtern** [comment]
chrome://flags kyber disabled fixed the problem!

**Comment by VanillaDphdmn** [comment]
> chrome: // отключены флаги kyber, исправлена проблема! #330

Thank you!
