### ISSUE TITLE
Please add support for linux

### ISSUE THREAD

**Issue by MrDisguised** [ValdikSS/GoodbyeDPI#362]
### Describe your feature / Опишите ваше предложение

This is an awesome tool/program to circumvent deep packet inspection used by governments in various countries to block stuff. Therefore, I would like to make a small request: I would be grateful if we could have a Linux version of it. A simple bash script can do the trick, as it would not only work in Linux but also in other operating systems like macOS, OpenBSD, and so on.

EDIT: Please don't tell me look at "similar projects" section because most of the projects that are listed there are abandoned or are simply garbage imo.

**Comment by ValdikSS** [comment]
Zapret is superior to GoodbyeDPI, and supports Linux.
https://github.com/bol-van/zapret/
