### ISSUE TITLE
Обход работает минут десять, а потом перестает работать, и так по кругу.

### ISSUE THREAD

**Issue by MasterMegatron** [ValdikSS/GoodbyeDPI#363]
### Operating system / операционная система

Win 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Сначала установил как сервис и все работало, через десять минут перестало открывать заблокированные сайты.
Удалил сервис, запустил через командную строку - не помогло.
После всех копаний и попыток внезапно заработало снова, но через 10 минут опять перестало.
kyber в хроме отключен, с безопасным dns и без него та же проблема. 
Наблюдаю такое во всех браузерах, так что сдается проблема не в них.
Антивируса нет, VPN не установлен, виртуальные адаптеры типа хамачей отключены.
Пробовал также менять параметры запуска которые нашел в этом разделе, в других ответах.
Браузер выдает в основном ERR_CONNECTION_RESET либо таймаут.
Может мне показалось, но наступает такая фигня когда пытаюсь зайти на твиттер, а может просто совпадение.
ЧЯДНТ?

**Comment by ValdikSS** [comment]
>ЧЯДНТ?

Не читаете.
