### ISSUE TITLE
SSL_ERROR_RX_MALFORMED_SERVER_HELLO

### ISSUE THREAD

**Issue by Rajdave69** [ValdikSS/GoodbyeDPI#366]
### Operating system / операционная система

Windows 11 22631

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

`SSL_ERROR_RX_MALFORMED_SERVER_HELLO`

![image](https://github.com/ValdikSS/GoodbyeDPI/assets/86198810/e978e779-87c7-4036-bde8-e3c755ede9be)

I'm getting errors with a few sites that are normally unblocked, such as monkeytype.com

It's always some sort of SSL serror

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark

**Comment by ValdikSS** [comment]
No response.
