### ISSUE TITLE
Как это установить службой

### ISSUE THREAD

**Issue by italiani** [ValdikSS/GoodbyeDPI#37]
Не получается
Программа srvstart от 2000 года она точно должна работать?
И можно ли эти задачи перекинуть на роутер, так было бы намного удобнее

**Comment by Skykila** [comment]
> Программа srvstart от 2000 года она точно должна работать?

лично у меня работает без проблем.

**Comment by italiani** [comment]
ура я разобрался было не просто
https://windowsnotes.ru/programs/kak-zapustit-prilozhenie-v-vide-sluzhby-windows/
вот так работает
