### ISSUE TITLE
win7sp1x64 KB3033929 установлен, но goodbyedpi_x86_64_15eb10a не хочет стартовать.

### ISSUE THREAD

**Issue by Quqas** [ValdikSS/GoodbyeDPI#370]
### Operating system / операционная система

windows 7x64 sp1

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

![image](https://github.com/user-attachments/assets/68a955b6-7397-481a-abee-1ad27f87d6f6)

### Additional information / Дополнительная информация

я так понимаю дело в WinDivert
но нет понимания как быть на win7?
KB3033929 установлен
но может ещё _более-другие_ kb  нужны?

**Comment by SUGHuser** [comment]
Просто скачайте старую версию , оттуда возьмите dll файлы и пользуейтесь ) у меня например WinDivert.dll от 21.03.2022

**Comment by Quqas** [comment]
> Просто скачайте старую версию , оттуда возьмите dll файлы и пользуейтесь ) у меня например WinDivert.dll от 21.03.2022

если бы
не работает оно с старыми dll 
покрайней мере то ради чего брал --frag-by-sni
а без неё и старая такаяже

разово-то можно и по f8 проверку отключить
а на навсегда?

в свойствах всеголишь sha256

и чем эти dll нетакие чем старые?

**Comment by Quqas** [comment]
проверил на другой семёре где с wsus всё что только возможно было апдачено и тоже самое

это вообще собственно-писная версия sys и dll ?

[тут вот](https://github.com/basil00/Divert/releases) 22г крайние

**Comment by Quqas** [comment]
я даже заморочился переподписать
https://reqrypt.org/windivert-faq.html#q3
а ошибка таже
`Сбой при запуске службы "WinDivert" из-за ошибки 
Системе Windows не удается проверить цифровую подпись этого файла. При последнем изменении оборудования или программного обеспечения могла быть произведена установка неправильно подписанного или поврежденного файла либо вредоносной программы неизвестного происхождения.`
_такнебывает_
собственно и изначальный sys серты тоже без ошибок - но винда думает что да
в чём причина?

**Comment by Quqas** [comment]
единственная разница с десяткой где таки запустился - что в 10 цепочка сертов в sys из 4х штук а в win7 из 3х

отключение проверки по f8 да помогает.

но как ещё в 2019году (судя по подписи) так криво сваяли sys что семёра его отвергает? ну или ещё нелепей почему личная подпись [Windows Driver Kit](http://www.microsoft.com/en-us/download/details.aspx?id=11800)  тоже не помогла? (остальные серты напрочь из sys удалились, лична ещё древним sha1 и серт проставлен по инструкции)

**Comment by SUGHuser** [comment]
Необходимый набор апдейтов которые лично я ставлю 
![Screenshot_3231](https://github.com/user-attachments/assets/c230c655-7007-45c2-9349-bb844f3baab8)

**Comment by SUGHuser** [comment]
Необходимый набор апдейтов которые лично я ставлю 
![Screenshot_3233](https://github.com/user-attachments/assets/dd305cea-f08a-4462-b2f6-b692c988f3a7)
у меня Windows 7 не какой нибудь Zver Edition и ни какой нибудь там Kto-to sdelal Edition , у меня он оригинал , с мной лично вырезанными не используемыми компонентами которые я десятилетиями не использую )

**Comment by ValdikSS** [comment]
У меня работает на 7, с вот такими обновлениями (обычные автоматические обновления из windows update)

![image](https://github.com/user-attachments/assets/35b4527d-9cc9-459c-b19e-3c99139bbb2b)

![image](https://github.com/user-attachments/assets/62a65ec2-dcff-4b45-9f04-8a30b7f0f3ca)

**Comment by SUGHuser** [comment]
Проверил , если запустить самую новую вообще без обновлений на VM - работает без ошибок ) проверял на лысой Win7 x86 )

**Comment by Quqas** [comment]
> У меня работает на 7, с вот такими обновлениями (обычные автоматические обновления из windows update)

нещитово x86 vs x64 как у меня

https://github.com/ValdikSS/GoodbyeDPI/issues/370#issuecomment-2227038505

ну а почемуто на доменной 7x64 где вообще все стоят обновы тоже нехочет

самое обидное я както до конца не понял как обновил серты на новые и удали старые comodo и теперь цепочка в sys точна такая же как десятке (насам деле серв22 )
![image](https://github.com/user-attachments/assets/bed006b0-4be1-4c15-b3b3-4ef3b5efac8b)

и никак....
а с отключением проверки - да

**Comment by SUGHuser** [comment]
У меня и на x64 системе такого нет ) , единственное что я не могу поставить нормально без отключения проверки цыфровой подписи , это драйвера nVIDIA GeForce после версии 472.12 , да и то , они тоже ставятся если поставить их поверх 472.12 , таких проблем не имею )

**Comment by Quqas** [comment]
> У меня и на x64 системе такого нет ) , единственное что я не могу поставить нормально без отключения проверки цыфровой подписи , это драйвера nVIDIA GeForce после версии 472.12 , да и то , они тоже ставятся если поставить их поверх 472.12 , таких проблем не имею )

ну так если уже отключено - то как gbd проверяешь и т.п.

а с nvidia наоборот оч. сранно

у меня 474.11 и даже мысли не было что с подписями не то



> У меня работает на 7, с вот такими обновлениями (обычные автоматические обновления из windows update)
> 
щас вот на vm пытаюсь воспроизвести и никак не пускается покачто
и на всяк случай.... это скрин не x86 ? ну там где вообще нет проверки

**Comment by ValdikSS** [comment]
> и на всяк случай.... это скрин не x86 ? ну там где вообще нет проверки

Это x86, да. Подписи (и их проверка) не отличается от архитектуры.

**Comment by Quqas** [comment]
> > и на всяк случай.... это скрин не x86 ? ну там где вообще нет проверки
> 
> Это x86, да. Подписи (и их проверка) не отличается от архитектуры.

проверка м.б.
а невозможность юзать дройвер?
как я знаю такое тока в x64

и я уж думал у нас разные msdn откуда iso с 7x64 брали...
потому как с чистого iso накотив с ещё живого wu через инет =незапускается
могу ammyy дать 
хотя чем это поможет

**Comment by Al-Lexx** [comment]
Аналогичная проблема.
Windows 7, x64, sp1, KB3033929 установлен.
goodbyedpi-0.2.2 работает, goodbyedpi_x86_64_15eb10a ругается на подпись.

**Comment by SUGHuser** [comment]
Извините , а зачем вам промежуточный вариант который не является финальной версией ?

**Comment by Al-Lexx** [comment]
> [Al-Lexx](https://github.com/Al-Lexx)
> Извините , а зачем вам промежуточный вариант который не является финальной версией ?

Ради --frag-by-sni

**Comment by SUGHuser** [comment]
На абсолютно чистой винде прям с диска где нет ничего - так же как у вас ошибка , но когда ставлю Windows6.1-KB3033929-x64 - работает )  вот https://www.microsoft.com/en-us/download/details.aspx?id=46148 можете скачать и поставить ) после установки этого апдейта  у меня работает https://www.microsoft.com/en-us/download/details.aspx?id=46148 , эта вещь есть в двух версиях такя https://www.microsoft.com/ru-ru/download/details.aspx?id=46078 на 26 мегабайт она не помогает , а вот эта https://www.microsoft.com/en-us/download/details.aspx?id=46148 на 43,8 мегабайт работает )

**Comment by SUGHuser** [comment]
На абсолютно чистой винде прям с диска где нет ничего - так же как у вас ошибка , но когда ставлю Windows6.1-KB3033929-x64 - работает ) вот https://www.microsoft.com/en-us/download/details.aspx?id=46148 как вариант , можете сделать следующее , поставить апдейт , перезагрузиться , затем удалить апдейт , перезагрузиться и снова поставить апдейт. Иногда такой танец с бубном помогает )

**Comment by Al-Lexx** [comment]
Кроличья нора всё глубже.
Установщик https://www.microsoft.com/en-us/download/details.aspx?id=46148 на 43,8 мегабайт заявляет: "Установка Обновление системы безопасности для ОС Windows (**KB3033929**) на этом компьютере **уже выполнена**."
А команда `C:\Windows\System32\wusa.exe /uninstall /kb:3033929` выдаёт "Обновление **KB3033929** **не установлено** на этом компьютере."
Гуглёж подсказывает, что проблема могла возникнуть из-за кумулятивных обновлений. Попробую удалить и поставить заново.

**Comment by SUGHuser** [comment]
В панели управления найдите и удалите обновление в ручную , не через колмандную строку )

**Comment by Quqas** [comment]
> [Quqas](https://github.com/Quqas) Я не совсем понял что за версию вы ставите , лично я проверил всё что 0.1.5 от финала до всяких релиз кандидатов - всё ставится ) всё запускаетя даже на начисто поставленной VM с теми обновлениями которые я указал )
> 
> [Al-Lexx](https://github.com/Al-Lexx) Извините , а зачем вам промежуточный вариант который не является финальной версией ?

мы точно про x64 в этот раз? или опять x86 ?
и версия gdb какая? 0.22 и раньше sys 1.4 используют и только _15eb10a sys 2.0 который и не может в **x64** "признать"

**Comment by Quqas** [comment]
3033929 заменяется кучей других
и даже не предлагается если через wu искать
более того 3033929 даже не самое раннее которое sha2 включает

**Comment by SUGHuser** [comment]
Я так и не могу понять , где имено вывыкапали goodbyedpi_x86_64_15eb10a , я зашёл https://github.com/ValdikSS/GoodbyeDPI/releases и не могу найти эту версию... я скачал всё что от 0.2.2.0 и до 0.1.4  , так вот все даже RC версии после установки обновления работают )

**Comment by SUGHuser** [comment]
Я так и не могу понять , где именно вы выкопали goodbyedpi_x86_64_15eb10a , я зашёл https://github.com/ValdikSS/GoodbyeDPI/releases и не могу найти эту версию... я скачал всё что от 0.2.2.0 и до 0.1.4  , так вот все даже RC версии после установки обновления работают )

**Comment by SUGHuser** [comment]
И ещё по поводу замены обновлений , иногда надо именно вот такое , не какое-то другое , а именно это )

**Comment by Quqas** [comment]
>не читал но мнение имею(с)
https://github.com/ValdikSS/GoodbyeDPI/actions/runs/9307982032
нерелиз но новее нет
хотябы 24й год а не 22й

**Comment by Quqas** [comment]
с самого начала тогда что именно ты пытался донести? если даже не понимал о чём?

**Comment by SUGHuser** [comment]
[ValdikSS](https://github.com/ValdikSS)
Действительно эта версия не работает , у тебя наверное что-то не так в сборке , проверь пожалуйста и пересобери ) старайся проверять на VM с чистой Windows 7 SP1 + тот самый апдейт )

**Comment by SUGHuser** [comment]
[ValdikSS](https://github.com/ValdikSS)
Поставил всё что ты показал , всё равно не работает

**Comment by ValdikSS** [comment]
Я заменил драйвер на версию с другой подписью, она должна работать.
b08836de50f3c22dd8dca0a99d618a7d7bd0d62c

Однако в Windows 7 нельзя загружать новые драйверы — всё, что подписано после июля 2021 года, не будет работать без дополнительных действий, так что это только временная мера, пока нет необходимости обновлять драйвер.

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/actions/runs/10105927108

**Comment by Quqas** [comment]
> Я заменил драйвер на версию с другой подписью, она должна работать. [b08836d](https://github.com/ValdikSS/GoodbyeDPI/commit/b08836de50f3c22dd8dca0a99d618a7d7bd0d62c)
> 
> Однако в Windows 7 нельзя загружать новые драйверы — всё, что подписано после июля 2021 года, не будет работать без дополнительных действий, так что это только временная мера, пока нет необходимости обновлять драйвер.

а кинься ссылкой
на телодвиженья необходимые
стало понятно почему собственный серт тоже был послан
но казалосьбы можно перевести часы.. штампа времени не ставит по дефу

**Comment by Quqas** [comment]
а по сабжу - победы не наступило :(
![image](https://github.com/user-attachments/assets/8eb03724-5e39-4d5c-8080-26a40b28f7af)
и чистка скрытых дивайсов не очень спасает
![image](https://github.com/user-attachments/assets/ecef5950-a637-4c04-adb2-bdf67e63ab8b)

**Comment by Quqas** [comment]
русских букв и пробелов нет 
`C:\Users\DeN\Documents\Downloads\goodbyedpi`

**Comment by Chip11-n** [comment]
В моём случае помогло удаление виндиверта и перезапуск самой программы (перезагрузка компьютера не помогала).
`sc delete windivert`
