### ISSUE TITLE
All 3-rd level domains for blacklist by mask

### ISSUE THREAD

**Issue by minerfromhell** [ValdikSS/GoodbyeDPI#371]
### Describe your feature / Опишите ваше предложение

At current there is no way to add all possible existing 3-rd level domains (like *.googlevideo.com) in the blacklist file. So, it could be good if GoodbyeDPI can handle all of them if corresponding entry is added in file.

**Comment by ValdikSS** [comment]
There's no way NOT to do that. GoodbyeDPI always handle records from blacklist as domain _zones_, not as individual domains.
