### ISSUE TITLE
mingw32-make: *** Makefile:46: goodbyedpi-rc.o Error 2

### ISSUE THREAD

**Issue by systemhorse** [ValdikSS/GoodbyeDPI#372]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

`mingw32-make.exe CPREFIX=x86_64-w64-mingw32- BIT64=1 WINDIVERTHEADERS=C:\Users\systemhorse\Downloads\WinDivert-2.2.2-A\include WINDIVERTLIBS=C:\Users\systemhorse\Downloads\WinDivert-2.2.2-A\x64`

ends with an error:

```
x86_64-w64-mingw32-windres goodbyedpi-rc.rc goodbyedpi-rc.o
process_begin: CreateProcess(NULL, x86_64-w64-mingw32-windres goodbyedpi-rc.rc goodbyedpi-rc.o, ...) failed.

make (e=2): The system cannot find the file specified.

mingw32-make: *** [Makefile:46: goodbyedpi-rc.o] Error 2
```

### Additional information / Дополнительная информация

Using MSYS2 on Windows

**Comment by ValdikSS** [comment]
It is apparently named just `windres` in msys2, you need to remove the prefix in Makefile.
