### ISSUE TITLE
Viber CDN not working with -f

### ISSUE THREAD

**Issue by pasha-zzz** [ValdikSS/GoodbyeDPI#373]
### Operating system / операционная система

Windows 10 22h2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

When subj started with -f option (f.e. in 5/6 modes) - downloading from Viber CDN not working:
http://download.cdn.viber.com/cdn/desktop/windows/ViberSetup.exe
http://download.cdn.viber.com/cdn/desktop/windows/ViberSetup.msi

**Comment by ValdikSS** [comment]
Works for me, doesn't seem like a software bug.
To debug, use Wireshark to capture the traffic and check what's going on.
https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark
