### ISSUE TITLE
Cannot reach sites on Opera GX

### ISSUE THREAD

**Issue by Reqon** [ValdikSS/GoodbyeDPI#375]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

This issue used to occur on Chrome, but it was fixed after disabling Kyber. Now, it happens on Opera GX. How do we fix it there?

**Comment by ValdikSS** [comment]
It's not possible to say anything with this amount of information.
