### ISSUE TITLE
Apply DNS redirect only to blacklist

### ISSUE THREAD

**Issue by guapter** [ValdikSS/GoodbyeDPI#377]
### Describe your feature / Опишите ваше предложение

Здравствуйте. 
Обнаружил такую проблему, что при включенном gdpi при стандартных настройках (и при настройках с моим блэклистом, где чисто ютюб), нарушается работа некоторых соединений. Например discord перестаёт работать и не может загрузить чаты, стим комьюнити и некоторые другие страницы не открываются. (либо ошибка днс, либо пишет отсутствует соединение с интернетом)
Проблема воспроизводится и при обычном запуске и в качестве службы.
Выяснил, что проблема в dns переадресации (которая стоит по умолчанию на яндексовские сервера) - получается, что днс редирект применяется для всего контента и сайтов, а не только для blacklist, а яндексовские днс видимо плохо работают с некоторым сайтами. 
Не знаю, баг это или фича, по этому написал сюда. Было бы неплохо, если это возможно, применять днс редирект Только для блэклиста, а не для всех сайтов. Либо по умолчанию, либо переключать это по флагу.

Hello.
I found a problem with enabled gdpi on standard settings (or my custom blacklist with youtube only), some connections are disrupted. For example, discord stops working properly and cannot load chats, steam community and some other pages do not open. (return a DNS error, or no Internet connection mesage)
The problem is reproduced both with regular startup and as a service.
I found out that the problem is in DNS redirection (which is set by default to Yandex servers) - it turns out that DNS redirect is applied to all content and sites, not only for blacklist urls, and Yandex DNS apparently does not work well with some sites.
I don't know if this is a bug or a feature, so I'm applied post here. It would be nice, if it possible, to apply DNS redirect to blacklist, not to all urls. Either by default, or using some flag to switch it.

**Comment by ValdikSS** [comment]
Если проблема в DNS Яндекса, смените DNS на другой, или отключите функцию перенаправления.

**Comment by guapter** [comment]
Да, но что по поводу того, что бы сделать dns redirect только для черного списка, что бы это не затрагивало остальные сайты? Возможно ли такое реализовать?

**Comment by yenknot** [comment]
> Если проблема в DNS Яндекса, смените DNS на другой, или отключите функцию перенаправления.

А как, собственно, эту функцию перенаправления отключить? Я случайно запустил её и без запущенного dnsredir почти ничего не работает.
