### ISSUE TITLE
Possible to port on Ubuntu?

### ISSUE THREAD

**Issue by AndreiLeman** [ValdikSS/GoodbyeDPI#38]
Is it possible to port this on ubuntu?
It would be very useful for people who use Ubuntu Desktop instead of WIndows... :)

**Comment by ValdikSS** [comment]
Not possible.
Use https://github.com/bol-van/zapret

**Comment by TagandurdyB** [comment]
Thank you very much for this program. I tried to use this program on ubuntu, can you give some information about any way to do this?
