### ISSUE TITLE
It works directly opposity way for youtube

### ISSUE THREAD

**Issue by MaratZakirov** [ValdikSS/GoodbyeDPI#384]
### Operating system / операционная система

Win11

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

It works in exact opposite way after I start 2_any_country.cmd (in adfministrator mode) youtube.com stop working at all.

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by ValdikSS** [comment]
Your DNS doesn't work.
