### ISSUE TITLE
Как отключить скрипт?

### ISSUE THREAD

**Issue by Retabinow** [ValdikSS/GoodbyeDPI#385]
### Operating system / операционная система

Win 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Не могу выключить этот cкрипт после запуска. Не помогает даже перезагрузка. 
Запускал 1_russia_blacklist и 1_russia_blacklist_dnsredir, скрипт заработал. Сделал всё, что мне надо, подумал как всё вернуть в системе обратно и как было. 
Что делать? Как вернуть изменения?

**Comment by uranik777** [comment]
Открой диспетчер задач (ctr-alt-del) найи вкладку службы, если есть служба GoodbyeDPI нажми правой кнопкой мышкии выбери "остановить". Еще можно от администратора запустить service_remove.cmd После этого пока не запустишь вручную, GoodbyeDPI сам не заработает.

**Comment by ValdikSS** [comment]
Закройте окно программы. Всё.

**Comment by DmitriyBatkovich** [comment]
Я не могу удалить папку с GoodBye DPI со своего раб стола так как я скопировал её на диск, и хотел сделать ярлык, Операция не может быть завершена по скольку файл или программа занят другим процессом, при этом окно программы закрыто Windows была перезагружена, видимо где-то на уровне ядра она работает

**Comment by DmitriyBatkovich** [comment]
Ну и я так понял это майнер:
![image](https://github.com/user-attachments/assets/7386535e-9351-4d62-84a0-4038845821c4)

**Comment by YobaPriem** [comment]
> Ну и я так понял это майнер: ![image](https://private-user-images.githubusercontent.com/163001002/354893998-7386535e-9351-4d62-84a0-4038845821c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NzE5NTAsIm5iZiI6MTcyMjc3MTY1MCwicGF0aCI6Ii8xNjMwMDEwMDIvMzU0ODkzOTk4LTczODY1MzVlLTkzNTEtNGQ2Mi04NGEwLTQwMzg4NDU4MjFjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQxMTQwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTljYzE5YzM1OTNjMzc5MTNjOWU2NWRhNzY0YWVhZGE3ZmE4MDdkNDU5ZWIwNGFiY2NhMmI5YmYyYTA4YmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PNU8_KiN4y_ywUqxJfX6EytEyE4_Zvwi_Oq0yw4SO7A)

Просто грохни службы и спокойно удаляй. В директории также лежит `service_remove.cmd`, если лень по служба самому лазить

**Comment by DmitriyBatkovich** [comment]
> > Ну и я так понял это майнер: ![image](https://private-user-images.githubusercontent.com/163001002/354893998-7386535e-9351-4d62-84a0-4038845821c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NzE5NTAsIm5iZiI6MTcyMjc3MTY1MCwicGF0aCI6Ii8xNjMwMDEwMDIvMzU0ODkzOTk4LTczODY1MzVlLTkzNTEtNGQ2Mi04NGEwLTQwMzg4NDU4MjFjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQxMTQwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTljYzE5YzM1OTNjMzc5MTNjOWU2NWRhNzY0YWVhZGE3ZmE4MDdkNDU5ZWIwNGFiY2NhMmI5YmYyYTA4YmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PNU8_KiN4y_ywUqxJfX6EytEyE4_Zvwi_Oq0yw4SO7A)
> 
> Просто грохни службы и спокойно удаляй. В директории также лежит `service_remove.cmd`, если лень по служба самому лазить. А ссылка просто в описание файла запихана, вдруг ты задонатить захочешь

Да уже всё сделал через безопасный режим, ну хорошо что это не майнер, а то я испугался

**Comment by MRX9420** [comment]
![{FD63BC32-FAB4-4B4E-9EE2-34BF28E93693}](https://github.com/user-attachments/assets/8a6d0219-097c-4b40-a340-abf572235e09) ну скажем так не работает код который вычищает службы гудбай дипиай
