### ISSUE TITLE
GoodbyeDPI blocks YouTube! (for some reason)

### ISSUE THREAD

**Issue by 4-EyedGuy** [ValdikSS/GoodbyeDPI#386]
### Operating system / операционная система

Windows 11

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Every time I launch GoogleDPI, I restart the browser to make it work and go to YouTube. And it tells me "no internet connection", which is very strange. Is there a solution to this, or am I doing something wrong?  /  

Каждый раз, когда я запускаю GoogleDPI, я перезапускаю браузер, чтобы программа работала, и захожу на Ютуб. А он пишет мне, что "нет подключения к интернету", что очень странно. Есть ли этому решение, или может я что-то не так делаю?

![Снимок экрана 2024-07-31 230638](https://github.com/user-attachments/assets/fbdfb9be-958a-40ff-85b9-328bb8eb1d1f)

**Comment by Azitor** [comment]
ты какую версию запускаешь?
0.2.3?
0.2.2
0.2

**Comment by Azitor** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/378
Обновили версию, попробуй на новой

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by kkaazzoo** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/306 Оно?

**Comment by JustMKMe** [comment]
It seems, Dr.Web's firewall service is in conflict with DPI's driver. It results in overall stopping of processing http requests.

**Comment by 4-EyedGuy** [comment]
> ты какую версию запускаешь? 0.2.3? 0.2.2 0.2

0.2.3

**Comment by tomrus88** [comment]
У меня такая же ошибка появилась при использовании версии 0.2.3 rc1.

Путем экспериментов выяснилось что если в настройках браузер включить обратно QUIC и Kyber, то ошибка об отсутствии интернета пропадает.

**Comment by levva111** [comment]
Тоже самое. Спасибо за ответ

**Comment by levva111** [comment]
Это всё из-за другой инструкции которая не работает, как обходить блок

**Comment by qxzusero** [comment]
Интернет есть и видео грузятся (до установки не грузились ВООБЩЕ) но качество выше 144р не поднимается, будто ютуб вернулся на состояние 30-31 июля.

**Comment by levva111** [comment]
> Интернет есть и видео грузятся (до установки не грузились ВООБЩЕ) но качество выше 144р не поднимается, будто ютуб вернулся на состояние 30-31 июля.

У меня нормально работает, если долго не открывать ютуб то потом 1 раз подольше грузится. Если видео переключать то уже быстро работает

**Comment by Dan5783** [comment]
Windows 10.0.22635.4000, провайдер МТС, антивирусов и т.п. нет, QUIC и Kyber отключены.
С версией 0.2.2 youtube работает хорошо (через goodbyedpi.exe --blacklist youtube-domain.txt -e 1 --reverse-frag)
С 0.2.3rc1 пишет: "Нет подключения к Интернету", пробовал и 1_russia_blacklist_dnsredir.cmd и 1_russia_blacklist.cmd.

**Comment by levva111** [comment]
> Windows 10.0.22635.4000, провайдер МТС, антивирусов и т.п. нет, QUIC и Kyber отключены. С версией 0.2.2 youtube работает хорошо (через goodbyedpi.exe --blacklist youtube-domain.txt -e 1 --reverse-frag) С 0.2.3rc1 пишет: "Нет подключения к Интернету", пробовал и 1_russia_blacklist_dnsredir.cmd и 1_russia_blacklist.cmd.

Так QUIC и Kyber включены должны быть (Default)

**Comment by Dan5783** [comment]
> Так QUIC и Kyber включены должны быть (Default)

Kyber по умолчанию выключен, его не трогал. QUIC (http3) изменил на Default в Chrome и Firefox. В Chrome при включенном QUIC действительно заработало, но в Firefox всё равно показывается, что нет подключения.

**Comment by alexeinarsson** [comment]
Будет здорово если получится интегрировать обход блокировки youtube в [расширение для chromium браузеров](https://chromewebstore.google.com/detail/runet-censorship-bypass/npgcnondjocldhldegnakemclmfkngch) 🙏

**Comment by macsem1999** [comment]
У меня была та же проблема. Все работало минут 20, потом сдохло. QUIC и Kyber были deafult, но инструкция просила поставить на выкл. Сейчас переставил на enabled - все заработало

**Comment by levva111** [comment]
> У меня была та же проблема. Все работало минут 20, потом сдохло. QUIC и Kyber были deafult, но инструкция просила поставить на выкл. Сейчас переставил на enabled - все заработало

Умничка

**Comment by YopterMatbEro** [comment]
Chrome Версия 127.0.6533.89 (Официальная сборка), (64 бит). Провайдер: Билайн. Не работает ни один из сценариев.
флаги включал и отключал, но, к сожалению, не помогло

**Comment by Nikita805** [comment]
Фаерфокс/мтс. Ничего не помогало. Иногда вдруг начинало работать, чаще -нет. Сделал следующий цмд, ярлык на него закинул в автозагрузку (вместо службы). Так все работает. По содержимому ничего сказать не могу, взял у другого человека и просто склеил в 1 файл.
@ECHO OFF
PUSHD "%~dp0"
set _arch=x86
IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)

echo This script should be run with administrator privileges.
echo Right click - run as administrator.
echo Press any key if you're running it as administrator.
pause
sc stop "GoodbyeDPI"
sc delete "GoodbyeDPI"
sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -6 --blacklist \"%CD%\youtube-domain.txt\"" start= "auto"
sc description "GoodbyeDPI" "Passive Deep Packet Inspection blocker and Active DPI circumvention utility"
sc start "GoodbyeDPI"

POPD

@ECHO OFF
PUSHD "%~dp0"
set _arch=x86
IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)

echo This script should be run with administrator privileges.
echo Right click - run as administrator.
echo Press any key if you're running it as administrator.
pause
sc stop "GoodbyeDPI"
sc delete "GoodbyeDPI"
sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -e 1 --reverse-frag --blacklist \"%CD%\youtube-domain.txt\"" start= "auto"
sc description "GoodbyeDPI" "Passive Deep Packet Inspection blocker and Active DPI circumvention utility"
sc start "GoodbyeDPI"

POPD

**Comment by ValdikSS** [comment]
Нет ответа от автора.

**Comment by In1quity** [comment]
Всё та же проблема.

**Comment by Kitterss** [comment]
> Нет ответа от автора.

О, эта рандомная ссыль на какую-то инструкцию "как сделать что-то там" - это был твой "вопрос"?
