### ISSUE TITLE
PR_CONNECT_RESET_ERROR | Не открываются некоторые сайты при включенном GoodbyeDPI

### ISSUE THREAD

**Issue by bercute7** [ValdikSS/GoodbyeDPI#387]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Некоторые сайты не открываются с включенной программой, выдавая ошибку PR_CONNECT_RESET_ERROR (браузер Mozilla Firefox), при том с выключенной программой все в порядке. С чем это может быть связано и как это решить?

**Comment by MixerBaikalLover** [comment]
тоже самое, только ERR_SSL_PROTOCOL_ERROR
проверял в Edge и Opera

**Comment by cryptopollution** [comment]
Подтверждаю, например твич не открывается. Выключаешь прогу - начинает работать. Способ с форума по обходу блокировки ютуба, который был еще для предыдущей версии, работает хорошо и все сайты грузятся вроде бы

**Comment by grain12** [comment]
Тоже не открываются или долго грузятся сайты через goodbyedpi-0.2.3rc1 (2_any_country) хотя youtube нормально работает, а если отключить goodbyedpi то youtube не пашет а всё остальное нормально грузиться.

**Comment by ValdikSS** [comment]
Используйте `--blacklist` или опции, не нарушающие работу на вашем провайдере.
