### ISSUE TITLE
0.2.3rc1 не работает

### ISSUE THREAD

**Issue by dallas1981s** [ValdikSS/GoodbyeDPI#389]
### Operating system / операционная система

Windows 11 last update

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

1_russia_blacklist_dnsredir.cmd. 2_any_country.cmd. 2_any_country_dnsredir.cmd не работает в ру регионе, все запускается, но ютуб не грузит ролики, версия 0,2,2 работает хорошо 1_russia_blacklist_dnsredir.cmd

**Comment by lMikoFoxl** [comment]
Та же проблема, только теперь и 0.2.2 не работает, РКН окончательно походу ютуб убили

**Comment by dallas1981s** [comment]
0.2.2 в данный момент работает и тянет легко 4к на яндекс и эдже

**Comment by Anon8281** [comment]
Сообщайте в подобных жалобах своего провайдера, пожалуйста. Такая проблема сейчас наблюдается явно не у всех

**Comment by raven-xr** [comment]
Сейчас ютуб уже работает. Кажись, серваки ебнулись у них

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by DmitryHitRun77** [comment]
а есть какой-нибудь файл read me чтобы понимать что для чего служит?
пока что я знаю что единственное что можно запустить так это 2_any_country.cmd

**Comment by COldVision** [comment]
@ValdikSS А есть возможность тихого запуска как процесс, без нужды держать открытое окно с программой?

**Comment by wdrs** [comment]
> @ValdikSS А есть возможность тихого запуска как процесс, без нужды держать открытое окно с программой?

Да, конечно, есть же файлик service_install_russia_blacklist.cmd

**Comment by hardsavage** [comment]
та же самая проблема, ютуб не грузит ролики (

**Comment by JustMKMe** [comment]
Проблема вот в чем, господа, у 0.2.3. 

Opening filter
Error opening filter: The system cannot find the path specified.

Никто в консольное окошко просто не посмотрел. Я пока пытаюсь понять, что ему не нравится. Пробовал запускать по-разному с разными путями.

**Comment by vocalir145** [comment]
> Сообщайте в подобных жалобах своего провайдера, пожалуйста. Такая проблема сейчас наблюдается явно не у всех

Провайдер CONVEX, вообще никак

**Comment by dallas1981s** [comment]
1_russia_blacklist_dnsredir.cmd и 1_russia_blacklist работает версии 0.2.3 1rc(последняя), но показывает при запуске что версия 0.2.2. И если убрать из блаклиста только [www.youtube.com](http://www.youtube.com/) то все работает. Кадры еще дропает, но уже 45 из 2000 примерно

**Comment by Heymdale** [comment]
Попробуй заменить в батниках 0.2.3 -9 на -5 или -6, как в 0.2.2 и вернуть youtube в блэклист.

**Comment by 677230756E64** [comment]
> [https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark](https://github.com/ValdikSS/GoodbyeDPI/wiki/%D0%9A%D0%B0%D0%BA-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%B4%D0%B0%D0%BC%D0%BF-%D1%82%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0-%D0%B2-Wireshark)

А чей трафик дампить, ютуба? Ну он делает свои инишиал обмены пакетами, видео включить - ничего не грузится, только кипэлайв пакеты периодически летают.

**Comment by ValdikSS** [comment]
> > [https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark](https://github.com/ValdikSS/GoodbyeDPI/wiki/%D0%9A%D0%B0%D0%BA-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%B4%D0%B0%D0%BC%D0%BF-%D1%82%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0-%D0%B2-Wireshark)
> 
> А чей трафик дампить, ютуба? Ну он делает свои инишиал обмены пакетами, видео включить - ничего не грузится, только кипэлайв пакеты периодически летают.

Да, важно захватить первые пакеты (TLS ClientHello + фейковые от GoodbyeDPI).

**Comment by dallas1981s** [comment]
> Попробуй заменить в батниках 0.2.3 -9 на -5 или -6, как в 0.2.2 и вернуть youtube в блэклист.

пробовал изначально, не работает, пишет нет интернета

**Comment by hackYourAss228** [comment]
У меня 0.2.3rc1 не работает в принципе, 0.2.2 работает только 1_russia_blacklist_dnsredir, перекинул только новый блек лист, но ютуб так же долго грузит

**Comment by dallas1981s** [comment]
> > Попробуй заменить в батниках 0.2.3 -9 на -5 или -6, как в 0.2.2 и вернуть youtube в блэклист.
> 
> пробовал изначально, не работает, ютуб пишет нет интернета. только после удаления youtube.com заработало

дополню.....браузер эдже, вернул в черный список youtube.com, -9, и поставил шифрование kyber в дефолт,  запуск с 1_russia_blacklist и 1_russia_blacklist_dnsredir работает на ура, хоть 4к хоть 8к идет очень хорошо теперь
