### ISSUE TITLE
Не работает с портативной версией Firefox

### ISSUE THREAD

**Issue by MrModest** [ValdikSS/GoodbyeDPI#39]
Установил портативный Firefox 57.
Запускаю goodbyedpi.
В MS Edge пашет с ключами -1 и -2. (Проверял на rutracker.org)
В портативном Firefox никак.
У знакомого тоже Firefox 57 стоит, но установленный и всё работает.

Вообще может проблема крыться именно в портативности?

P.S. Кстати, судя по логам BlockCheck (https://pastebin.com/NXZPv3K1) у меня goodbyedpi вообще не должен работать, но работает в MS Edge =/
P.P.S. В том же MS Edge с включённым goodbyedpi при попытке перейти на https://chan.sankakucomplex.com открывает http://ru.videochat.guru/

**Comment by ValdikSS** [comment]
Если способ обхода DPI «фрагментирование заголовка, hoSt и отсутствие пробела одновременно» в тесте DPI работает, то и GoodbyeDPI будет работать.

Сделайте дамп перенаправления в формате pcap.
Скачайте и установите wireshark: https://www.wireshark.org/
Запустите программу, укажите в поле "enter a capture filter" следующее значение:

`host 195.82.146.214 or host 104.28.10.65 or host 104.28.11.65`

Это IP-адреса рутрекера и pbooru, и запустите blockcheck.
После того, как blockcheck завершит работу, остановите сбор данных в wireshark (значок с красной кнопкой стоп), сохраните файл pcapng (file → save as) и отправьте его мне на iam@valdikss.org.ru

**Comment by MrModest** [comment]
Видимо я что-то не так понял в программе. 
Для начала программа отказывается работать при выборе `Cisco remote capture` который стоит по умолчанию. 
При выборе `Random package generator` программа после запуска останавливается сама, не успеваю даже запустить blockcheck.
Режим ssh (сомневаюсь, что он нужен, но всё же) тоже не работает.
у UDP абсолютно пустой лог. 

Что я сделал не так? Я использовал портативную версию с сайта по вашей ссылке, но разве проблема может быть в этом? =/

**Comment by ValdikSS** [comment]
Я не пользовался портативной версией. В списке интерфейсов нужно выбирать настоящий сетевой адаптер, а не виртуальный.

**Comment by MrModest** [comment]
а где можно это явно указать?

**Comment by ValdikSS** [comment]
У меня нет сейчас ни Windows, ни нового интерфейса Wireshark. Насколько я помню, на главном экране чуть левее высвечивается список интерфейсов, там и нужно выбрать сетевой адаптер (вероятнее всего, он называется «подключение по локальной сети»).

**Comment by MrModest** [comment]
![2017-11-30_000304](https://user-images.githubusercontent.com/13031058/33398977-dcb281ce-d561-11e7-8d27-7adc2261940f.png)

**Comment by ValdikSS** [comment]
Должен быть еще и обычный сетевой интерфейс. Вероятно, портативная версия не умеет захватывать с него, нужен winpcap. Поставьте полноценную версию.

**Comment by MrModest** [comment]
из списка подключений единственный нелинейный график имело только "Беспроводное соединение", плюс я подключён к роутеру по Wifi, так что выбрал его. 
Высылаю логи на почту, если всё верно понял.

**Comment by MrModest** [comment]
К слову, pbooru заработал у меня без всяких обходов (видимо, провайдер не блочит)

**Comment by ValdikSS** [comment]
Разобрались. В портативном Firefox была установлена Cookie, которая заставляла сайт перенаправлять клиента на HTTPS-версию. HTTPS-версия блокировалась провайдером.
В MS Edge Cookie не было, и все работало, но по HTTP.
