### ISSUE TITLE
Не загружаются видео в Chrome после использования Goodbye DPI

### ISSUE THREAD

**Issue by andrey-nurullin** [ValdikSS/GoodbyeDPI#390]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Запускал несколько раз программу через 2_any_country.cmd, тестировал в Chrome. Потом отключал программу. Все работало.
Сейчас браузер Chrome не загружает никакие видео (при незапущенной программе). Другие браузеры работают как обычно нормально.

Причем видео с моего канала, в который я сейчас залогинен - загружает. Остальные видео на ютубе нет. Пробовал логиниться в другой свой канал - тоже загружает, но остальные видео - опять нет, включая мой первый канал. Чертовщина. Пробовал переустанавливать Chrome и сбрасывать настройки на по умолчанию. Ничего не помогает.
![Screenshot_39](https://github.com/user-attachments/assets/71087fa8-ec5e-481a-b08e-f27944a4e13d)

**Comment by BAXONnt** [comment]
То же самое. Скачал установил последнюю версию программы (0.2.3 rc1). Запустил 2_any_country.com - видео с ютуба грузит, но окно программы в фоне висит. Закрыл программу и всё, с ютуба ничего не посмотреть, вечно крутит.

**Comment by ValdikSS** [comment]
YouTube замедлили до несмотрибельных скоростей сегодня в полночь. Это не ошибка программы.
https://ntc.party/t/замедление-youtube-в-россии/8055/103

**Comment by andrey-nurullin** [comment]
> YouTube замедлили до несмотрибельных скоростей сегодня в полночь. Это не ошибка программы. [https://ntc.party/t/замедление-youtube-в-россии/8055/103](https://ntc.party/t/%D0%B7%D0%B0%D0%BC%D0%B5%D0%B4%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-youtube-%D0%B2-%D1%80%D0%BE%D1%81%D1%81%D0%B8%D0%B8/8055/103)

Повторюсь, в других браузерах все грузит

**Comment by wulfgar93** [comment]
Такая же история. Хром не хочет грузить, все playback запросы валятся с ошибкой (failed)net::ERR_CONNECTION_RESET
При этом в FF всё работает нормально.

**Comment by EgorWeders** [comment]
> Такая же история. Хром не хочет грузить, все playback запросы валятся с ошибкой (failed)net::ERR_CONNECTION_RESET При этом в FF всё работает нормально.

Kyber отключили?

**Comment by wulfgar93** [comment]
> Kyber отключили?
Спасибо! Теперь работает! Надо бы в README об этом написать...

**Comment by EgorWeders** [comment]
> > Kyber отключили?
> 
> Спасибо! Теперь работает! Надо бы в README об этом написать...

https://github.com/ValdikSS/GoodbyeDPI/issues/330
Закреплено вверху ;)
