### ISSUE TITLE
www.youtube.com работает, а youtube.com нет

### ISSUE THREAD

**Issue by VadimBoev** [ValdikSS/GoodbyeDPI#391]
### Operating system / операционная система

Win 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Часа 3 назад ютуб всё.
Решил затестить GoodByeDPI.
Обычное посещение любого видео всё работает, ютуб где-то может перенаправить с "youtube.com" на "www.youtube.com", тогда всё хорошо.
Но, есть проблема:
Мне скинули видео в телеге на ютуб, пример ссылки "https://youtube.com/shorts/XU6gagVmUgQ?si=2smf1J0YOVF4ZfxJ".
При переходе на неё, видео не работает, но если поменять "youtube.com" на "www.youtube.com" всё работает как часы.
Версия последняя: goodbyedpi-0.2.3rc1

**Comment by KiberAndy** [comment]
Перешёл по ссылке - всё работает (Запускаю, как службу)
Попробуй так (эта инфа с инета):

Сначала запускаешь service_remove.cmd и нажимаешь в нём на любую кнопку (пробел допустим) и потом запускаешь 2_any_country.cmd после запускаешь 0_russia_update_blacklist_file.cmd, теперь можно закрыть cmd окно с именем 2_any_country.cmd. Далее открываешь файл russia-blacklist.txt и добавляешь вот такие строки
www.youtube.com
googlevideo.com
nhacmp3youtube.com
Сохраняешь файл. И на последок от имени администратора запускаешь файл service_install_russia_blacklist.cmd и в нём на любую кнопку (пробел допустим).

**Comment by VadimBoev** [comment]
> Перешёл по ссылке - всё работает (Запускаю как службу) Попробуй так (эта инфа с инета):
> 
> Сначала запускаешь service_remove.cmd и нажимаешь в нём на любую кнопку (пробел допустим) и потом запускаешь 2_any_country.cmd после запускаешь 0_russia_update_blacklist_file.cmd, теперь можно закрыть cmd окно с именем 2_any_country.cmd. Далее открываешь файл russia-blacklist.txt и добавляешь вот такие строки [www.youtube.com](http://www.youtube.com) googlevideo.com nhacmp3youtube.com Сохраняешь файл. И на последок от имени администратора запускаешь файл service_install_russia_blacklist.cmd и в нём на любую кнопку (пробел допустим).

Да, это действительно сработало, спасибо!

**Comment by KiberAndy** [comment]
> А как сделать так чтобы через IDM видео скачать можно было ? А то 403 выдаёт

Попробуй другой путь, например так:
Поставь: https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=ru

И установи этот скрипт в него:
https://ru.savefrom.net/20/userjs-for-google-chrome.php
