### ISSUE TITLE
GoodbyeDPI и After Effects

### ISSUE THREAD

**Issue by Chris-Kyarov** [ValdikSS/GoodbyeDPI#392]
### Operating system / операционная система

Edition	Windows 11 Pro Version	23H2 Installed on	‎5/‎14/‎2024 OS build	22631.3880 Experience	Windows Feature Experience Pack 1000.22700.1020.0

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

При использовании GoodbyeDPI After Effects начинает странно себя вести (возможно, не только он, а вообще все продукты Adobe, но я не проверял).

Если коротко, то при включённом GoodbyeDPI при попытке закрытия After Effects он намертво зависает. После отключения GoodbyeDPI всё начинает работать нормально.

![image](https://github.com/user-attachments/assets/0ba37aaf-5445-497b-82d2-08cad8a8f446)

**Comment by ValdikSS** [comment]
Программа использует интернет?
Если это сетевая проблема, то подберите опции для вашего провайдера, в частности, используйте `--blacklist`.
Если нет, возможно, какая-то несовместимость с WinDivert.

**Comment by Chris-Kyarov** [comment]
Проблема ушла после того, как скачал 0.2.3rc1 версию. До этого не хотел её трогать, так как ждал релизную версию.
