### ISSUE TITLE
Странная работа с FireWall

### ISSUE THREAD

**Issue by KiberAndy** [ValdikSS/GoodbyeDPI#393]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

При использовании FireWall программа не работает нормально.
Я использую [TinyWall](https://tinywall.pados.hu), добавил в исключение и саму программу и службу, но в режиме "Обычная защита" инет просто пропадает, хотя не должен, как только включаю "Автообучение", то сразу всё грузится.
Хочу решить проблему. Может нужно что-то ещё добавить в исключения? Хотя программа в режиме Автообучения должна сама добавлять то, что входит в инет

**Comment by ValdikSS** [comment]
Трафик отправляет «процесс» system.
