### ISSUE TITLE
Не обновляется https://antizapret.prostovpn.org/domains-export.txt

### ISSUE THREAD

**Issue by Avtukhoff** [ValdikSS/GoodbyeDPI#397]
### Operating system / операционная система

Windows 10 22h2 

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

-
https://antizapret.prostovpn.org/domains-export.txt

Нельзя открыть 

### Additional information / Дополнительная информация

Пробовал через смартфон. Бесполезно

**Comment by ValdikSS** [comment]
А к программе это какое отношение имеет? Никакого.

**Comment by Avtukhoff** [comment]
Теоретически имеет. Программа же с этого файла берёт адреса
