### ISSUE TITLE
0.2.3rc1 с настройками 7, 8 и 9 блокирует большинство сайтов

### ISSUE THREAD

**Issue by SilverCutePony** [ValdikSS/GoodbyeDPI#399]
### Operating system / операционная система

Windows 10 22H2 19045.4651

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Windows 10 22H2 19045.4651, Chrome 127.0.6533.88, Провайдер Билайн
Новая версия с настройками 7, 8 и 9 препятствует загрузке сайтов, как заблокированных, так и нет. Браузер выдаёт ошибку ERR_SSL_PROTOCOL_ERROR, иногда также DNS_PROBE_FINISHED_BAD_SECURE_CONFIG. Quic и Kyber в chrome://flags отключены. С настройками от 1 до 6 таких ошибок нет

**Comment by ValdikSS** [comment]
Клёво.

**Comment by ringoz** [comment]
а что клевого то?
у меня та же проблема, прочитал 10 раз README, но не понял как починить.

**Comment by ringoz** [comment]
как и сказал @SilverCutePony, режим -6 действительно помогает.

**Comment by SilverCutePony** [comment]
> как и сказал @SilverCutePony, режим -6 действительно помогает.

Я сейчас использую "goodbyedpi.exe -6 -q --frag-by-sni", плюс, в браузере отключены Quic и Kyber. YouTube работает без проблем, сайты не ломает с такими настройками

**Comment by KiGamji** [comment]
нашли решение? я что-то тоже не выкупил, при аналогичной конфигурации и провайдере, у меня работает, а у знакомого нет. только -6
