### ISSUE TITLE
error opening filter: null

### ISSUE THREAD

**Issue by Shinnyss** [ValdikSS/GoodbyeDPI#400]
### Operating system / операционная система

Windiws 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Буквально вчера был первый запуск программы, все отлично работало. Сегодня запускаю ее так же и она закрывается. предварительно наградив меня такими данными.
![Безымянный](https://github.com/user-attachments/assets/d664d7cf-8ab1-44ab-a0e2-93d9d424e92a)

**Comment by ValdikSS** [comment]
Скорее всего, что-то не так с .dll. Либо вы не распаковали .dll-файлы, либо антивирус удалил, либо что-то еще.

**Comment by JustMKMe** [comment]
Нет, все стандартно распаковано с простым именем. Антивирус даже не притрагивался к файлам. Даже с отключенным антивирусом наглухо похожая проблема: 
Opening filter
Error opening filter: The system cannot find the path specified.

**Comment by ValdikSS** [comment]
```
sc stop windivert14
sc delete windivert14
sc stop windivert
sc delete windivert
```

**Comment by JustMKMe** [comment]
> sc stop windivert14
> sc delete windivert14
> sc stop windivert
> sc delete windivert

фильтр подцепил. Кубер отломал в браузере. Но замедление пока не обходится.
