### ISSUE TITLE
Не работает GoodbyeDPI / GoodbyeDPI is not working

### ISSUE THREAD

**Issue by stivfilippov** [ValdikSS/GoodbyeDPI#401]
### Operating system / операционная система

windows 10 22h2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Сегодня ночью начались масштабные проблемы с ютубом по всей стране, изначально наткнулся на инструкцию в группе в вк https://vk.com/wall-37865546_6409, не помогло, начал искать информацию дальше, далее пытался сделать всё по инструкции которая написана уже разработчиком тоже нечего, что интересно, это то что у моего брата всё работает(провайдеры одинаковые, версия системы одинаковая, только адреса разные) даже пробовал на виртуалке делать всё тоже самое на чистой винде, то же по нулям.
Прошу помощи!

**Comment by stivfilippov** [comment]
Забыл уточнить, браузер chrome, пробовал как 0.2.3 так и 0.2.2

**Comment by ValdikSS** [comment]
>GoodbyeDPI не гарантирует ни 100% работу с вашим провайдером, ни работу с каждым заблокированным сайтом. Если GoodbyeDPI не разблокирует доступ к некоторым или всем веб-сайтам, вероятнее всего, это не программная ошибка, и не стоит о ней сообщать здесь.
