### ISSUE TITLE
Маска для сайтов из списка

### ISSUE THREAD

**Issue by SolatK** [ValdikSS/GoodbyeDPI#402]
### Describe your feature / Опишите ваше предложение

Было бы очень удобно иметь возможность вводить маску или доменное имя определенного уровня. Сейчас замедляют сервера ютуба у которых имена это *.googlevideo.com, где * это какой-то набор символов.

**Comment by ValdikSS** [comment]
> --blacklist   <txtfile>  perform circumvention tricks only to host names **and subdomains** from
>                          supplied text file (HTTP Host/TLS SNI).
>                          This option can be supplied multiple times.
