### ISSUE TITLE
Unable to play roblox with GoodbyeDPI

### ISSUE THREAD

**Issue by SandFoxy** [ValdikSS/GoodbyeDPI#404]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Unable to play roblox with GoodbyeDPI
![Снимок экрана 2024-08-01 142111](https://github.com/user-attachments/assets/19f1c687-b5a5-4bab-b892-f4920d4c9bf6)

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark

**Comment by 21387A** [comment]
> https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark

Извините, я встреваю в чужую ветку, но похоже в 0.2.3rc1 отвалилась возможность подключаться к серверам очень многих игр. Не только к тем, на взаимосвязь которых с goodbyedpi тут жалуются.

Сегодня днем сообщали, что к Genshin Impact, а также к Honkai Star Rail и Zenless Zone Zero не получается подключиться. Ошибки там в духе "не получилось получить список серверов", короче говоря пользователи не пробиваются даже до выбора региона Европа/Азия/Америка. При этом если включить goodbyedpi уже после входа на сервер, то проблем нет.

Просто делюсь информацией. Лично от себя добавить ничего не могу, сейчас не до игр.

**Comment by ValdikSS** [comment]
Без дампа трафика невозможно сказать, почему так происходит.
Многие игры просто проверяют наличие драйвера WinDivert и отказываются работать, если он присутствует.

**Comment by 21387A** [comment]
Согласен с вами. Хотя, на примере вышеописанных игр, версия 0.2.2 осложнений не вызывала, несмотря на WinDivert. Ладно, я надеюсь, у кого сейчас возможность есть - дампы доставят. Прощу прощения за беспокойство еще раз.

**Comment by ValdikSS** [comment]
> Zenless Zone Zero

Сервер принимает данные, отправленные опцией `--wrong-seq`. Либо отключите её, либо используйте `blacklist` только на определённые сайты.

**Comment by TiBiDO** [comment]
У меня то же перестал работать LoL.... Началось после того как установил GoodbyeDPI как службу.
sc stop "GoodbyeDPI"
sc delete "GoodbyeDPI"
sc stop "WinDivert"
sc delete "WinDivert"
результатов не принесло.

Сделал дамп трафика 
[lol.zip](https://github.com/user-attachments/files/16478909/lol.zip)
Помогите разобраться.

**Comment by ValdikSS** [comment]
@TiBiDo Сервер не отвечает на пакеты. Проблем не в программе.
