### ISSUE TITLE
GoodbyeDPI для Украины

### ISSUE THREAD

**Issue by BlackHARD94** [ValdikSS/GoodbyeDPI#406]
### Describe your feature / Опишите ваше предложение

Сделай GoodbyeDPI для Украины, пожалуйста, а то у меня не грузит российские сайты типа vk.com, ok.ru, goodgame.ru, vkplay.com и другие

**Comment by tomrus88** [comment]
А вы их ручками добавили в blacklist чтобы они разблокировались?

**Comment by BlackHARD94** [comment]
> Сайты в Украине заблокированы по IP-диапазонам, а не по доменам с помощью DPI. Эта программа для обхода систем DPI, против блокировок IP она бессильна.

Тогда, что ещё кроме впн и прокси может помочь?
