### ISSUE TITLE
Error opening filter: The system cannot find the path specified

### ISSUE THREAD

**Issue by Daniel366Cobra** [ValdikSS/GoodbyeDPI#407]
### Operating system / операционная система

Windows 10 Pro 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Downloaded` 0.2.3rc1-2`, unzipped and tried to run `1-russia-blacklist.cmd`.
Got the "Error opening filter" as per screenshot.

![image](https://github.com/user-attachments/assets/b868a0ae-d7f8-4795-88f2-5c17b6f3cfcc)

Looked through issues for common solutions.
Kyber and QUIC are off.
Tried rebooting.
Tried running as admin or not.
Root folder (as extracted from zip) is in Windows Defender's exclusions.
`x86-64` contains `goodbyedpi.exe`, `WinDivert.dll` and `WinDivert64.sys`,
`x86` contains `goodbyedpi.exe`, `WinDivert.dll`, `WinDivert32.sys` and `WinDivert64.sys` - so no files lost to antivirus.

Any help please?

**Comment by ValdikSS** [comment]
Run `service-remove.cmd` to delete previous windivert service. It should work afterwards.
