### ISSUE TITLE
Error opening filter: There are no more endpoints available from the endpoint mapper.

### ISSUE THREAD

**Issue by FNLaker** [ValdikSS/GoodbyeDPI#409]
### Operating system / операционная система

windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

когда запуская появлляется вот такая ошибка 
![image](https://github.com/user-attachments/assets/ca0d3477-dffd-47d0-9154-f644a7a8af7d)

**Comment by alexdarthz** [comment]
Тебе нужно скачать новую версию отсюда
https://github.com/ValdikSS/GoodbyeDPI/issues/378

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/212
