### ISSUE TITLE
Crash and/or does not start Call of Duty MW3 Warzone™ Battle.net

### ISSUE THREAD

**Issue by SkyK0T** [ValdikSS/GoodbyeDPI#410]
### Operating system / операционная система

10 

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

When I run the program, no matter with or without filters, I have a crash and/or does not start Call of Duty MW3 Warzone™ Battle.net

**Comment by ValdikSS** [comment]
#172

**Comment by SkyK0T** [comment]
Ёмае не увидел, и чего нет никакого решения ещё даже через костыли?

**Comment by ValdikSS** [comment]
1. Удалять сервис после каждого запуска программы
2. Сообщить о проблеме разработчику игры
