### ISSUE TITLE
Проблема с Discord и Game jolt

### ISSUE THREAD

**Issue by DankaLoshkov** [ValdikSS/GoodbyeDPI#411]
### Operating system / операционная система

Windows 11, 23H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Проблема в том что у меня айпи WIFI украинский, и  когда запускаю 2_any_country.cmd, то у меня дискорд и гаме жолт не работают(почти полу сайта у меня не работают)

### Additional information / Дополнительная информация

(но вот когда вай фай с ру айпи то у меня всё норм)

**Comment by ValdikSS** [comment]
Не запускайте `2_any_country.cmd`, а настройте blacklist.
