### ISSUE TITLE
не открывается discord и aliexpress 

### ISSUE THREAD

**Issue by Gergish001** [ValdikSS/GoodbyeDPI#413]
### Operating system / операционная система

Windows 20H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

при открытом goodbyedpi пропадает соединение с серверами aliexpress и discord вечное подключение 
![Снимок экрана 2024-08-01 173013](https://github.com/user-attachments/assets/f673d0e3-3bc2-4518-b5aa-07a245ff40fa)
![Снимок экрана 2024-08-01 222712](https://github.com/user-attachments/assets/749af5d7-9f13-40b5-89e3-e81cfd31026b)

**Comment by ValdikSS** [comment]
Как вы запускаете программу?

**Comment by merlisscen** [comment]
братишка руки прокачай у тебя даже он не запущен

**Comment by Euphoreka7** [comment]
у меня в случае использования 1_russia_blacklist_dnsredir.cmd - ютуб заработал, но при попытке обращения к страницам гитхаба или днс анрезолвед или но коннекшн. в случае использования 1_russia_blacklist.cmd - работает. аргументы в скриптах не менялись

**Comment by Kent4r** [comment]
> братишка руки прокачай у тебя он даже не запущен

так вон снизу иконка goodbyeDPI, та же проблема и у меня

**Comment by Kent4r** [comment]
короче при запуске 1_russia_blacklist.cmd всё работает, и дискорд и алиэкспресс и ютуб, можно закрывать

**Comment by Euphoreka7** [comment]
> короче при запуске 1_russia_blacklist.cmd всё работает, и дискорд и алиэкспресс и ютуб, можно закрывать

не совсем. днс-редирект или не работает нормально или с адресами что-то не так. в случае скрипта днс-редиректа - доп апгументы в виде `--dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253`. было бы неплохо разобраться в чем проблема. и как минимум заменить в квикстарте ридмишки описание чтобы другие не наступали на эти же грабли

**Comment by Euphoreka7** [comment]
кАроч. прекрасно работает с `--dns-addr 8.8.8.8 --dns-port 853 --dnsv6-addr 2001:4860:4860::8888 --dnsv6-port 853`. только не нашла как можно задавать более одного адреса. если добавить --dns-addr 8.8.4.4 или через запятую или в кавычках и через запятую - не запускается. можно добавить поддержку более одного адреса или если она есть - дополнить доку инфой о том как

**Comment by Euphoreka7** [comment]
пфф. не. через время перестало работать. те же ошибки на гугл днс-е что и в яндексе. только там были сразу, а здесь через время: `DNS_PROBE_STARTED`, `DNS_PROBE_FINISHED_NO_INTERNET`. фича явно всё еще экспериментальная

**Comment by Baks456** [comment]
еще и twitch тупит с dnsredir

**Comment by Gergish001** [comment]
> братишка руки прокачай у тебя он даже не запущен

он у меня на втором рабочем столе чтобы иконки снизу не занимать

**Comment by shatcung** [comment]
Аналогичная ситуация, только отлег коннект не только к дискорду, но и к разным сайтам, сервисам (врод Xbox, Uplay, etc.). По какой-то причине, только Ютуб кое-как работает во время активного приложения.

**Comment by ValdikSS** [comment]
@shatcung, как вы запускаете программу? Без этого и дампа трафиков не имеет смысла писать сообщения, можно только гадать на кофейной гуще.

**Comment by DedMazaev** [comment]
@ValdikSS 
Та же самая проблама. В момент, когда запускается 2_any_country_dnsredir - отваливается дискорд.

**Comment by Glebkuz** [comment]
При использовании 2_any_country, 2_any_country_dnsredir дискорд перестаёт работать.

**Comment by blavonne** [comment]
У меня Дискорд работает через раз, и от чего это зависит, я не поняла. Я готова предоставить любую доп инфу, если есть инструкция, как её добыть. У меня есть Microsoft Network Monitor 3.4 - я могу с помощью этого сделать дамп трафика или я неправильно поняла, что требуется? Я запускаю 1_russia_blacklist.cmd.

**Comment by clover1980** [comment]
А зачем вы это делаете можно спросить? Эти ресурсы заблочены?
Если вы прочитаете описание, то все это работает только потому что вы гоните весь свой трафик через Яндекс, тобишь товарища майора. Дискорд скорее сам блокирует их днс.
_… при использовании Сервиса Яндексу в автоматическом режиме, в обезличенном виде (без привязки к Пользователю), может передаваться следующая информация: тип и модель устройства Пользователя, тип операционной системы устройства Пользователя, перечень доменных имён веб-сайтов, посещаемых Пользователем, а также иная статистическая информация об использовании Сервиса и техническая информация. Указанная информация хранится и обрабатывается Яндексом в соответствии с Политикой конфиденциальности[[8]](https://ru.wikipedia.org/wiki/%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81_DNS#cite_note-8). Указанная информация может также храниться и обрабатываться аффилированными компаниями Яндекса, и Пользователь настоящим даёт согласие на передачу такой персональной информации таким лицам.

— Условия использования сервиса «Яндекс.DNS». Пункт 2.8_

**Comment by SunCatMC** [comment]
у меня дискорд работает через -9, практически дефолтный 1_russia_blacklist_dnsredir.cmd (добавил еще один текстовый файл для себя)
но не работает через -6, а через -5 сильно тормозит

**Comment by blavonne** [comment]
> как оказалось на -9 тоже перестает работать, когда подгружает новые сервера, но если соединение с дискорд сервером ранее было установлено, то всё работает
Было и так, что спустя пару часов звонка внутри Дискорда, видимо, произошёл реконнект, и мы отвалились (1_russia_blacklist.cmd, т.е. -9).
