### ISSUE TITLE
There is no internet connection

### ISSUE THREAD

**Issue by k0nAtbl4** [ValdikSS/GoodbyeDPI#414]
### Operating system / операционная система

Windows 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

I followed the guide on the github, but did not find where to write "options -e1 -f1" for the MGTS provider.

**Comment by ValdikSS** [comment]
You need to pass it as an argument to the program. If you use .cmd file, modify the .cmd file.
This is not the issue of the program, do NOT report it here!
