### ISSUE TITLE
Добавление апи бывшего твиттера

### ISSUE THREAD

**Issue by bub4z0r** [ValdikSS/GoodbyeDPI#415]
### Describe your feature / Опишите ваше предложение

По возможности, могли бы вы добавить api.x.com в сборку в russia-blacklist.txt? Что бы руками каждый раз не пихать

**Comment by ValdikSS** [comment]
В списке есть x.com, даже дважды.

**Comment by UnoFortunato** [comment]
У меня X/Twitter давным-давно перестал открываться с GoodbyeDPI. Никак не пойму, в чем причина. Очень прошу разработчика помочь с решением этой проблемы. Спасибо!

**Comment by Leka1B** [comment]
Вчера тоже была проблема, но сейчас все работает отлично. Я дополнительно прописывал в список x.com, но не уверен дает ли это хоть что-то

**Comment by UnoFortunato** [comment]
> Вчера тоже была проблема, но сейчас все работает отлично. Я дополнительно прописывал в список x.com, но не уверен дает ли это хоть что-то
Я тоже вручную прописал, но нет, не открывается.

**Comment by jestxfot** [comment]
> У меня X/Twitter давным-давно перестал открываться с GoodbyeDPI. Никак не пойму, в чем причина. Очень прошу разработчика помочь с решением этой проблемы. Спасибо!

Пробуй новую версию и если МГТС флаги `-e1 -f1`

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/251

**Comment by UnoFortunato** [comment]
> #251

Добрый день! Все сделано по той самой инструкции. Hosts отредактирован под Билайн. Все равно не открывается. Windows 11 24H2, Firefox последняя версия.

**Comment by UnoFortunato** [comment]
> > У меня X/Twitter давным-давно перестал открываться с GoodbyeDPI. Никак не пойму, в чем причина. Очень прошу разработчика помочь с решением этой проблемы. Спасибо!
> 
> Пробуй новую версию и если МГТС флаги `-e1 -f1`

Скачана последняя версия специально для YouTube. Билайн здесь. Twitter не открывается, страница зависает в процессе открывания.

**Comment by bub4z0r** [comment]
@ValdikSS судя по тому куда браузер ломится не хватает "api.x.com" еще

**Comment by UnoFortunato** [comment]
> судя по тому куда браузер ломится не хватает "api.x.com" еще

Я добавил в russia-blacklist еще **api.x.com**. Бесполезно.

**Comment by ValdikSS** [comment]
`x.com` уже есть в списке, список применяется как для доменов, так и для субдоменов.
Если `api.x.com` не открывается, то, скорее всего, он заблокирован по IP-адресу. На моём провайдере проблем с доступом не наблюдается.

Если это блокировка по IP, нужно найти работающий IP. Это возможно, т.к. Twitter использует CDN.
https://github.com/ValdikSS/GoodbyeDPI/issues/251

**Comment by UnoFortunato** [comment]
> Если это блокировка по IP, нужно найти работающий IP.

А где искать надо **работающий IP** ?

**Comment by UnoFortunato** [comment]
Добрый день! Ваши **«актуальные»** IP адреса за 2024 год #251, не работают на Билайне.

**Comment by ValdikSS** [comment]
> А где искать надо **работающий IP**

На вашем провайдере. Каждые провайдеры могут блокировать разные адреса.
