### ISSUE TITLE
It is not deleted

### ISSUE THREAD

**Issue by KapitanAnall** [ValdikSS/GoodbyeDPI#417]
### Operating system / операционная система

windown 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

![Screenshot_2](https://github.com/user-attachments/assets/e7c18cf1-cf4a-4803-aea8-a10137155f4f)
Не удаляется файл и почему написан чей то биткоин кошелек, что делать?

**Comment by ewear2k** [comment]
![image](https://github.com/user-attachments/assets/d3ca2631-70c3-4f75-9e89-b0b235435688)
тоже не получается удалить эту замечательную штуку, что делать, как решать?

**Comment by ewear2k** [comment]
@Diskanskiy in the ready-made launcher with this program, there is no service for deletion

**Comment by KapitanAnall** [comment]
> ![image](https://private-user-images.githubusercontent.com/105595464/354340760-d3ca2631-70c3-4f75-9e89-b0b235435688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzgwMjUsIm5iZiI6MTcyMjUzNzcyNSwicGF0aCI6Ii8xMDU1OTU0NjQvMzU0MzQwNzYwLWQzY2EyNjMxLTcwYzMtNGY3NS05ZTg5LWIwYjIzNTQzNTY4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxODQyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTc5MWMxYWE1NDcxNTkwNmVhNDg5NjU2MDM5OTMyYWI1MGI1NzIwMzBmZDgxMDJjYWZlNmRiYmRhMjc5MmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vOEy5VU_CdfC54pGhkr3b9P1CfRSAz5rB93TFxYeo9M) тоже не получается удалить эту замечательную штуку, что делать, как решать?

service.remove.cmd от админа запусти, нажми любую клавишу, после чего все удаляется. Если так не получилось то запусти командную строку от имени админа и пропиши Sc stop Windivert, после чего можешь удалять папку

**Comment by ewear2k** [comment]
@KapitanAnall так тоже не получалось, все равно была запущена, через прогу получилось удалить только 
![image](https://github.com/user-attachments/assets/66d5dfb5-e6b6-43aa-8c95-15146332fdfa)

**Comment by KapitanAnall** [comment]
> @KapitanAnall так тоже не получалось, все равно была запущена, через прогу получилось удалить только ![image](https://private-user-images.githubusercontent.com/105595464/354345465-66d5dfb5-e6b6-43aa-8c95-15146332fdfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1Mzg3MTMsIm5iZiI6MTcyMjUzODQxMywicGF0aCI6Ii8xMDU1OTU0NjQvMzU0MzQ1NDY1LTY2ZDVkZmI1LWU2YjYtNDNhYS04Yzk1LTE1MTQ2MzMyZmRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxODUzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDgyYTY2OWUzYTk3Y2EyMDdkMGNmODZkYjA2MzE1NTlmMGViMmY4YzE5MmRiNTBjOTFjMWNiOGI4NTliYjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xE0wm1_f751wHmlZ6fkfENKrLsHEH5vzoVXNHXgRScw)

Ну, не знаю, у меня всё получилось и у моих друзей тоже

**Comment by V3rtos** [comment]
Есть ещё один способ это перезапустить пк и просто удалить этот файл

**Comment by FlerysGaMe2032** [comment]
> > ![image](https://private-user-images.githubusercontent.com/105595464/354340760-d3ca2631-70c3-4f75-9e89-b0b235435688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzgwMjUsIm5iZiI6MTcyMjUzNzcyNSwicGF0aCI6Ii8xMDU1OTU0NjQvMzU0MzQwNzYwLWQzY2EyNjMxLTcwYzMtNGY3NS05ZTg5LWIwYjIzNTQzNTY4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxODQyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTc5MWMxYWE1NDcxNTkwNmVhNDg5NjU2MDM5OTMyYWI1MGI1NzIwMzBmZDgxMDJjYWZlNmRiYmRhMjc5MmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vOEy5VU_CdfC54pGhkr3b9P1CfRSAz5rB93TFxYeo9M) тоже не получается удалить эту замечательную штуку, что делать, как решать?
> 
> service.remove.cmd от админа запусти, нажми любую клавишу, после чего все удаляется. Если так не получилось то запусти командную строку от имени админа и пропиши Sc stop Windivert, после чего можешь удалять папку

А разве это не троян или майнер?

**Comment by KapitanAnall** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/105595464/354340760-d3ca2631-70c3-4f75-9e89-b0b235435688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzgwMjUsIm5iZiI6MTcyMjUzNzcyNSwicGF0aCI6Ii8xMDU1OTU0NjQvMzU0MzQwNzYwLWQzY2EyNjMxLTcwYzMtNGY3NS05ZTg5LWIwYjIzNTQzNTY4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxODQyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTc5MWMxYWE1NDcxNTkwNmVhNDg5NjU2MDM5OTMyYWI1MGI1NzIwMzBmZDgxMDJjYWZlNmRiYmRhMjc5MmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vOEy5VU_CdfC54pGhkr3b9P1CfRSAz5rB93TFxYeo9M) тоже не получается удалить эту замечательную штуку, что делать, как решать?
> > 
> > 
> > service.remove.cmd от админа запусти, нажми любую клавишу, после чего все удаляется. Если так не получилось то запусти командную строку от имени админа и пропиши Sc stop Windivert, после чего можешь удалять папку
> 
> А разве это не троян или майнер?

Нет, автор просто указал свое авторство и номер кошелька для донатов. Так сказать указал, что он автор

**Comment by Bob7200** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/105595464/354340760-d3ca2631-70c3-4f75-9e89-b0b235435688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzgwMjUsIm5iZiI6MTcyMjUzNzcyNSwicGF0aCI6Ii8xMDU1OTU0NjQvMzU0MzQwNzYwLWQzY2EyNjMxLTcwYzMtNGY3NS05ZTg5LWIwYjIzNTQzNTY4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxODQyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTc5MWMxYWE1NDcxNTkwNmVhNDg5NjU2MDM5OTMyYWI1MGI1NzIwMzBmZDgxMDJjYWZlNmRiYmRhMjc5MmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vOEy5VU_CdfC54pGhkr3b9P1CfRSAz5rB93TFxYeo9M) тоже не получается удалить эту замечательную штуку, что делать, как решать?
> > > 
> > > 
> > > service.remove.cmd от админа запусти, нажми любую клавишу, после чего все удаляется. Если так не получилось то запусти командную строку от имени админа и пропиши Sc stop Windivert, после чего можешь удалять папку
> > 
> > 
> > А разве это не троян или майнер?
> 
> Нет, автор просто указал свое авторство и номер кошелька для донатов. Так сказать указал, что он автор

Это вирус , если это не был вирус там бы не было кода внутри , и этот код зашифрован ещё . Так что советую этот GoodbyeDPI поскорее удалить . . .
