### ISSUE TITLE
Не проксируется meta.com

### ISSUE THREAD

**Issue by electrifying** [ValdikSS/GoodbyeDPI#418]
### Operating system / операционная система

windows 11 23h2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

При запуске скрипта 1_russia_blacklist даже если добавить в russia-blacklist cайт meta.com то к нему нельзя получить доступ ERR_CONNECTION_TIMED_OUT, если запустить скрипт 1_russia_blacklist_dnsredir или 2_any_country то все работает нормально. С остальными сайтами на скрипте  1_russia_blacklist проблем нет

**Comment by Leka1B** [comment]
Предполагаю, что проблема в том, что meta не замедляется, а насухо блокируется. Стоит задуматься, может ли этот инструмент помочь с сайтом, доступ к которому с русского ip в принципе получить невозможно

**Comment by jestxfot** [comment]
https://www.meta.com/ проксируется, Москва, МТС

Со включенными флагами `-e1 -f1`

**Comment by ValdikSS** [comment]
Meta блокируется по диапазонам IP-адресов. Это не ошибка программы, не сообщайте о ней!

**Comment by Hannabiann** [comment]
> Meta блокируется по диапазонам IP-адресов. Это не ошибка программы, не сообщайте о ней!

У меня на zapret meta и фейсбук работают на Ростелекоме, так что не банят по IP.
