### ISSUE TITLE
Настройка GoodbyeDPI

### ISSUE THREAD

**Issue by qo4on** [ValdikSS/GoodbyeDPI#420]
### Operating system / операционная система

Windows 10 20H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Прошу прощения за вопрос здесь, но ntc.party не грузится вообще никак, даже с впн или тор.
Заметил, что ролики на ютубе иногда все равно не успевают кэшироваться и, соответственно подтормаживают.
Пробовал так, но какой-то разницы не заметил:
`goodbyedpi-0.2.3rc1`:
```
start "" goodbyedpi.exe -9 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
start "" goodbyedpi.exe -9 -e1 -f1 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
```

`goodbyedpi-0.2.2`:
```
start "" goodbyedpi.exe -5 --blacklist ..\russia-blacklist.txt
start "" goodbyedpi.exe -6 --blacklist ..\russia-blacklist.txt
```
Флаги `chrome://flags/#enable-quic` и `chrome://flags/#enable-tls13-kyber` отключены.
Может кто сталкивался с подобным, напишите какими настройками получалось это победить.

**Comment by geysha1337** [comment]
> Флаги chrome://flags/#enable-quic и chrome://flags/#enable-tls13-kyber отключены.

А разве quic не должен быть наоборот включён?

**Comment by igrigg** [comment]
Вопрос в том, что НЕТ ДОСТУПА к ntc.party (по ссылке со страницы: https://github.com/ValdikSS/GoodbyeDPI/issues/378
Любым способом, даже с VPN (когда всё доступно).
Когда запускаются сетевые утилиты - недоступность чего-то напрягает по-особенному...!

**Comment by geysha1337** [comment]
> > разве quic не должен быть наоборот включён?
> 
> На сколько мне известно он препятствует работе GoodbyeDPI.

короче не препятствует, по крайней мере у меня включён quic(в инструкции был специально удалён фрагмент с отключением quic вчера, ещё там есть поддержка http3, которая и помогала до недавнего времени обходить замедление, можно в инете посмотреть устаревшие инструкции как обходить блокировки) и стоит 0.2.3 gdpi и проблем у меня нет от слова совсем, 4к видео не подтормаживает и довольно быстро записывает в кэш ещё ~1минуту, то есть та скорость которая и была до замедления, попробуй со включённым короче

а вот с ntc.party да, засада, и непонятно чё делать

**Comment by geysha1337** [comment]
> У меня с включенным quic ютуб сильнее тормозит даже на версии 0.2.3.

хм, а какой провайдер и город?
кстати ntc.party заработал

**Comment by jestxfot** [comment]
> Вопрос в том, что НЕТ ДОСТУПА к ntc.party (по ссылке со страницы: #378 ) Любым способом, даже с VPN (когда всё доступно). Когда запускаются сетевые утилиты - недоступность чего-то напрягает по-особенному...! ... Т.е. подтверждаю момент от [qo4on](https://github.com/qo4on) и добавлю, что видео с Youtube не запускается после выполнения всех предложенных настроек. (под VPN - идёт).

ntc.party временно лёг, сейчас восстановили

**Comment by jestxfot** [comment]
> У меня с включенным quic ютуб сильнее тормозит даже на версии 0.2.3.

QUIC должен быть выключен, по крайней мере у меня работает так

**Comment by KirillMulygin** [comment]
Доброго времени суток. 
ntc.party лежит, поэтому хотел уточнить тут. 
Есть вариант откатить обратно все изменения после запуска скрипта по обходу блокировки ютуба в России?

**Comment by SagePtr** [comment]
> На сколько мне известно он препятствует работе GoodbyeDPI.

QUIC не препятствует GoodbyeDPI, а ходит мимо него, потому в качестве временного решения его отключают (GoodbyeDPI 0.2.3rc1 умеет блочить его сама, лишние телодвижения в браузере теперь не нужны). Надеюсь, @ValdikSS в будущем допилит полноценную поддержку QUIC (не только отключение, но и манипуляцию с пакетами), а то протокол полезный, меня не раз выручал при проблемах с сетью.

**Comment by turokman** [comment]
Доброй ночи, подскажите, пожалуйста, сделал всё по инструкции, однако видео подгружается до какого-то момента, полоска видео доходит до него и замертво ложится. Помогает только остановка видео и терпение — пока полоска снова не наберется.

Kyber, QUIC выключены.

Запускал последнюю версию разными способами (и через 1_russia_blacklist, и goodbyedpi). Провайдер — "Билан" (МСК).

**Comment by bkzlustra** [comment]
Хай, у меня невероятно плохо прогружаются видео в хроме, но в эдже более-менее. Существует ли какой-нибудь способ диагностики? ситуация странная, quic включен(без него в эдже прогрузка падает), kyber отключен в обоих случаях.

**Comment by LastDragon-ru** [comment]
У меня (билайн, поволжье) ютюб работает если запускать `2_any_country.cmd`, настройки хрома не трогал (точнее пытался, но они все делают только хуже). При этом правда пропадают авы на гитхабе, а так же доступ к али и редиту...

**Comment by Plaha64** [comment]
Привет, спасибо большое за обход блокировки, ты нереально крут.
Видео теперь работают без тормозов, а вот загрузка видео тормозит.
Нужно какие-то дополнительные настройки включить или прописать адреса?

**Comment by axe1000** [comment]
Привет, а как в Firefox настроить goodbyedpi, а то везде только хром?
Или постоянно теперь запускать 2_any_country.cmd?

**Comment by SagePtr** [comment]
> Вот нашёл параметр: security.tls.enable_kyber tru/false -это он?

Да, он, выставить false

**Comment by axe1000** [comment]
А cmd файлы нужно запускать, а то при закрытии youtube снова тормозит7
![11](https://github.com/user-attachments/assets/d71bfd21-2751-4890-95c7-17e8ec70d658)

**Comment by SagePtr** [comment]
> А cmd файлы нужно запускать, а то при закрытии cmd-шного файла, youtube снова тормозит?

Держать его включённым, при закрытии программа выключается и перестаёт модифицировать трафик

**Comment by SagePtr** [comment]
> Только у меня некоторые видеоролики сразу не загружаются и приходится перезагружать страницу или еще у кого также? Пробовал такие настройки, но разницы не заметил:

Возможно, у вас провайдер блокирует некоторые IPшники серверов гугла, нужно тогда смотреть через консоль браузера, куда он долбится и на какие адреса, а нерабочие заблочить через hosts (тогда браузер будет пытаться на них стучать, но получать отлуп сразу и не ждать, пока соединение отвалится по тайм-ауту, а сразу пробовать следующий).
