### ISSUE TITLE
Перестал работать vpn (psiphon+smartproxy) после использования GoodbyeDPI

### ISSUE THREAD

**Issue by AlexandrDermenji** [ValdikSS/GoodbyeDPI#422]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

После того как запустил "1_russia_blacklist" от имени администратора, ютуб начал норм работать. Но потом, попробовав запустить впн psiphon+smartproxy, обнаружил, что он не работает. С чем это может быть связано?

**Comment by glebobobr** [comment]
с впн попробуй запускать прогу через 2_any_country, так как при попытке запуска впн у тебя сбрасывается регион

**Comment by ValdikSS** [comment]
> С чем это может быть связано?

Не с программой.
