### ISSUE TITLE
What

### ISSUE THREAD

**Issue by FlerysGaMe2032** [ValdikSS/GoodbyeDPI#425]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

![Discord_Fo47WUyxp7](https://github.com/user-attachments/assets/e50c1338-e183-4bc1-b751-422acdc5cb84)
![Telegram_WSuOLd9F0G](https://github.com/user-attachments/assets/ef7d29cf-04a5-43af-a7d3-4620343f3c80)
![Telegram_tcOrdlgLry-2](https://github.com/user-attachments/assets/8e65c38f-9d37-4b0a-aa1a-d03309996b75)
![Telegram_ZhkIrwaGfa](https://github.com/user-attachments/assets/d7c255f5-5092-445f-91da-647638a11d76)

**Comment by jestxfot** [comment]
WinDivert - необходимая библиотека и драйвер для Windows, которые позволяют перехватывать и манипулировать сетевым трафиком на низком уровне. Неудивительно что антивирусы будут как обычно параноидировать и пускать ложные оповещения о вирусах. Программа должна была адекватно закрываться, что-то конечный пользователь намудрил

**Comment by FlerysGaMe2032** [comment]
> WinDivert - необходимая библиотека и драйвер для Windows, которые позволяют перехватывать и манипулировать сетевым трафиком на низком уровне. Неудивительно что антивирусы будут как обычно параноидировать и пускать ложные оповещения о вирусах. Программа должна была адекватно закрываться, что-то конечный пользователь намудрил

![Telegram_itnQUU3Xtx](https://github.com/user-attachments/assets/e00b39d3-7c53-45fe-b5ba-939cf72b5e27)

**Comment by krlvm** [comment]
Вы, наверное, думаете, что вместе с анонимами из ВК и какого-то телеграм-чата раскрыли мировой заговор, но это всего лишь [биткоин-кошелек для приема пожертвований](https://reqrypt.org/donate.html)

**Comment by ValdikSS** [comment]
@FlerysGaMe2032 на первом скриншоте троян.

**Comment by jestxfot** [comment]
Тогда они качали фейковую версию программы, вероятно
