### ISSUE TITLE
Как откатить всё к базе?

### ISSUE THREAD

**Issue by xXARONx** [ValdikSS/GoodbyeDPI#426]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

После установки goodbyedpi-0.2.3rc1, пинг в играх резко подскочил 
Как всё сбросить вернуть обратно?

**Comment by ValdikSS** [comment]
Закройте окно программы.

**Comment by xXARONx** [comment]
> Закройте окно программы.

Командную строку?

**Comment by Ponamarev** [comment]
У меня после включения приложения совершенно не работают VPN- сервисы
