### ISSUE TITLE
Если был создан файл обхода только для ютуба, то почему сверху загружены ещё все остальные сервисы?

### ISSUE THREAD

**Issue by GreMirid** [ValdikSS/GoodbyeDPI#427]
### Describe your feature / Опишите ваше предложение

Не логично ли создать отдельный батник только для ютуба?
Да, поменять ничего не стоит, но таким образом создатель подставляет тысячи Россиян, которые хотят воспользоваться его разработкой под угрозу взлома с правомерно заблокированных ресурсов ( фишинг сайты, сайты сект, опиумных веществ и прочего непотребства ).

**Comment by SagePtr** [comment]
> фишинг сайты, сайты сект, опиумных веществ и прочего непотребства

Фишинг сайты РКН не блокирует и так, этим должно заниматься защитное ПО наподобие антивируса/антишпиона и прочих анти-, а не государственный цензор.
А прочие перечисленные вами категории сайтов не имеют к киберугрозам никакого отношения, их посещение может навредить разве что неокрепшей психике пользователя, если он вдруг случайно прочитает новости и узнает правду о своём государстве, например.

Но да, отдельный батник - идея хорошая, и добавить в `russia-youtube.txt` домен `ggpht.com` обязательно, чтобы этот список был самодостаточным и исправлял не только загрузку видео, но и загрузку аватарок на ютубе.

**Comment by dim2603** [comment]
> подставляет тысячи Россиян

очень голословно. Руки есть, голова на плечах - не лезь куда не надо. Тем более зная, что провайдер продолжает видеть твои действия в сети.

**Comment by ValdikSS** [comment]
Программа не создана исключительно для обхода замедления. Скрипты также приведены как пример, предполагается, что пользователь их модифицирует под своего провайдера и под свои требования.
Если вам нужен только обход замедления, исключите russia-blacklist из `--blacklist`.
