### ISSUE TITLE
Конфликтует с nekobox vpn tun

### ISSUE THREAD

**Issue by kvinstar** [ValdikSS/GoodbyeDPI#428]
### Describe your feature / Опишите ваше предложение
PS ростелеком провайдер
Когда включен nekobox в режиме tun, и включаешь byedpi, то инет вырубается.
Если 1_russia_blacklist.cmd то инет работает, но ютуб тормозит. Если 1_russia_blacklist_dnsredir.cmd то инет не работает. 2_any_country.cmd тоже не работает. 2_any_country_dnsredir.cmd тоже не работает.
Подскажи может какие то настройки из тех что на скриншотах надо поменять, мне как то сказали что надо dpi надо завернуть в nekobox непонятно что имели ввиду и не понятно поможет ли, но лучше любая мысль чем её отсутствие.
[
![image](https://github.com/user-attachments/assets/a922a8e1-b415-4376-902f-25ab5d68d1ff)
]
![image](https://github.com/user-attachments/assets/b301c78d-314a-4b66-963f-08311558e428)
![image](https://github.com/user-attachments/assets/8511ebac-1102-4547-88b0-411d8dcda9c2)
![image](https://github.com/user-attachments/assets/238bcd5c-838f-40bb-aeeb-bb3a0dca91f8)

**Comment by gudron** [comment]
Да там много что отваливается, у меня например при его использовании отваливается рабочий vpn от tailscale

**Comment by Pashevka** [comment]
У меня тоже отваливается интернет, если рабочий OpenVpn включен одновременно. Если кто знает как их 2их запустить - скажите плз

**Comment by ValdikSS** [comment]
Юзерспейс-реализации туннелирования прокси как VPN:
* Все несколько кривые
* Точно не заработают с GoodbyeDPI (в лучшем случае не будет никакого эффекта)
