### ISSUE TITLE
Выпрямление заблокированных ссылок

### ISSUE THREAD

**Issue by shikulja** [ValdikSS/GoodbyeDPI#43]
Можете сделать какой нибудь файлик, или аддон для хрома\оперы чтобы заблокированные ссылки типа
http://warning.rt.ru/?id=4&st=0&dt=195.123.218.61&rs=http%3A%2F%2Fnnm-club.name%2Fforum%2Fviewtopic.php%3Ft%3D948566
вернуть старый адрес

**Comment by ValdikSS** [comment]
Ваше предложение не имеет отношение к GoodbyeDPI.
