### ISSUE TITLE
Regarding ReadMe.MD files - Links section

### ISSUE THREAD

**Issue by Lenar-Avia** [ValdikSS/GoodbyeDPI#431]
### Operating system / операционная система

Windows 10 64bit 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

The link to android implementation seems to be outdated,
correct link for #4
DPI Tunnel for Android by @zhenyolka (for Android)
is 
https://github.com/nomoresat/DPITunnel-android

### Additional information / Дополнительная информация

same is applicable to #3 in links list = [DPI Tunnel CLI](https://github.com/zhenyolka/DPITunnel-cli) by @zhenyolka (for Linux and routers) - that has now moved to 
https://github.com/nomoresat/DPITunnel-cli

**Comment by ValdikSS** [comment]
Fixed in 68bc67685fd599098d154dca64d35ff8a055e130
