### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by SergeVDev** [ValdikSS/GoodbyeDPI#432]
### Describe your feature / Опишите ваше предложение

Above all, thank you very much for the brilliant solution and all your support!

It would be great to see an Android port, working the same way.

**Comment by Sicdex** [comment]
> ### Describe your feature / Опишите ваше предложение
> Above all, thank you very much for the brilliant solution and all your support!
> 
> It would be great to see an Android port, working the same way.

https://github.com/krlvm/PowerTunnel-Android

**Comment by ValdikSS** [comment]
This program is Windows-only.
https://github.com/ValdikSS/GoodbyeDPI?tab=readme-ov-file#similar-projects
