### ISSUE TITLE
Error opening filter: Incorrect function.

### ISSUE THREAD

**Issue by nickthathasnotbeentakenyet** [ValdikSS/GoodbyeDPI#433]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

GoodbyeDPI v0.2.2: Passive DPI blocker and Active DPI circumvention utility
https://github.com/ValdikSS/GoodbyeDPI

Loaded 91310 hosts from file ..\russia-blacklist.txt
Block passive: 0
Fragment HTTP: 2
Fragment persistent HTTP: 2
Fragment HTTPS: 2
Native fragmentation (splitting): 1
Fragments sending in reverse: 1
hoSt: 0
Host no space: 0
Additional space: 0
Mix Host: 0
HTTP AllPorts: 0
HTTP Persistent Nowait: 1
DNS redirect: 0
DNSv6 redirect: 0
Allow missing SNI: 0
Fake requests, TTL: auto (fixed: 0, auto: 1-4-10, min distance: 3)
Fake requests, wrong checksum: 0
Fake requests, wrong SEQ/ACK: 0
Max payload size: 1200

Opening filter
**Error opening filter: Incorrect function.**

**Comment by ValdikSS** [comment]
Run this one:
https://github.com/ValdikSS/GoodbyeDPI/actions/runs/10217536058

What does it print?

**Comment by IRainman** [comment]
> Run this one: https://github.com/ValdikSS/GoodbyeDPI/actions/runs/10217554421
> 
> What does it print?

x86_64>goodbyedpi.exe  --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
GoodbyeDPI v0.2.2: Passive DPI blocker and Active DPI circumvention utility
https://github.com/ValdikSS/GoodbyeDPI

Loaded 137595 hosts from file ..\russia-blacklist.txt
Loaded 4 hosts from file ..\russia-youtube.txt
Block passive: 0
Fragment HTTP: 0
Fragment persistent HTTP: 0
Fragment HTTPS: 0
Fragment by SNI: 0
Native fragmentation (splitting): 0
Fragments sending in reverse: 0
hoSt: 0
Host no space: 0
Additional space: 0
Mix Host: 0
HTTP AllPorts: 0
HTTP Persistent Nowait: 0
DNS redirect: 0
DNSv6 redirect: 0
Allow missing SNI: 0
Fake requests, TTL: disabled (fixed: 0, auto: 0-0-0, min distance: 0)
Fake requests, wrong checksum: 0
Fake requests, wrong SEQ/ACK: 0
Max payload size: 0

Opening filter
Error opening filter: 3 The system cannot find the path specified.

**Comment by ValdikSS** [comment]
> Error opening filter: 3 The system cannot find the path specified.
no .dll or .sys

**Comment by Chimera-Syber** [comment]
How to fix this issue?

**Comment by kilyabin** [comment]
> > Error opening filter: 3 The system cannot find the path specified.
> 
> no .dll or .sys

у меня такая же проблема кстати, но windivert.dll и Windivert64.sys присутствуют в папке
версия 0.2.3rc-1

**Comment by Ho0LiGaN82** [comment]
```
GoodbyeDPI v0.2.2: Passive DPI blocker and Active DPI circumvention utility
https://github.com/ValdikSS/GoodbyeDPI

Loaded 137451 hosts from file ..\russia-blacklist.txt
Loaded 4 hosts from file ..\russia-youtube.txt
Block passive: 0
Block QUIC/HTTP3: 1
Fragment HTTP: 2
Fragment persistent HTTP: 2
Fragment HTTPS: 2
Fragment by SNI: 0
Native fragmentation (splitting): 1
Fragments sending in reverse: 1
hoSt: 0
Host no space: 0
Additional space: 0
Mix Host: 0
HTTP AllPorts: 0
HTTP Persistent Nowait: 1
DNS redirect: 0
DNSv6 redirect: 0
Allow missing SNI: 0
Fake requests, TTL: fixed (fixed: 0, auto: 0-0-0, min distance: 0)
Fake requests, wrong checksum: 1
Fake requests, wrong SEQ/ACK: 1
Max payload size: 1200

Opening filter
Error opening filter: The system cannot find the path specified.

```

Тоже самая проблема, автор как решить? Вы ответа не даёте.

**Comment by Kiwi1444** [comment]
> > Error opening filter: 3 The system cannot find the path specified.
> 
> no .dll or .sys

What .dll and .sys needed exactly? 
![2024-08-09 16_45_41](https://github.com/user-attachments/assets/ef254c9b-47cd-44f2-a097-6c66b35e7898)

**Comment by Ho0LiGaN82** [comment]
Так как автор решения не даёт, и видимо не пытался, я нашел решение проблемы.

И так, запускаем **командную строку - CMD от имени администратора**, и вводим поочерёдно команды: **sc stop windivert** -
**sc delete windivert**
Старый драйвер удалится от старой версии GoodbyeDPI  и запустится без ошибок новая версия GoodbyeDPI 0.2.3rc1.

Всем удачи!

**Comment by d1mulka** [comment]
Здраствуйте ночью чесов по Москве 4 еще работал а сегодня с 13 00 не работает  пишет error opening:The service cannot be  
 started either because it is disadled or because it has no enabled devices associated with it.

**Comment by XCanG** [comment]
@Ho0LiGaN82 решение было верным, в службах оставался старый WinDivert от 0.2.2, он и мешал.

**Comment by Chimera-Syber** [comment]
> Решение данной проблемы в 99.99%.
> 
> Запускаем **командную строку - CMD от имени администратора**, и вводим поочерёдно команды: **1) sc stop windivert** **2) sc delete windivert**
> 
> Старый драйвер удалится от старой версии GoodbyeDPI, и запустится без ошибок новая версия GoodbyeDPI 0.2.3rc1.
> 
> Так-же можете через батник файл **.cmd** попробовать автора, который в корне с программой лежит "**service_remove.cmd**"
> 
> Всем удачи!

It fixes the issue, thanks!

**Comment by GKashurin** [comment]
подскажите, какую конкретно службу запустить? 
![image](https://github.com/user-attachments/assets/eb1ca142-1561-4ec7-a3a1-e72aa12df2c3)

**Comment by diskree** [comment]
@GKashurin просто вызывайте `sc delete windivert` в таком случае

**Comment by ezverev** [comment]
> подскажите, какую конкретно службу запустить? ![image](https://private-user-images.githubusercontent.com/67225544/363461669-eb1ca142-1561-4ec7-a3a1-e72aa12df2c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MzE1MzEsIm5iZiI6MTcyNjgzMTIzMSwicGF0aCI6Ii82NzIyNTU0NC8zNjM0NjE2NjktZWIxY2ExNDItMTU2MS00ZWM3LWEzYTEtZTcyYWExMmRmMmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDExMjAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZmVlOGFlNjJlNzMwMTliOGNmYjA5NmE4NjgwNWM3NmMxOTM0MzAxYzBiNmYxZDVkM2Q2ODE4MGUyZjRjYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uEYskWvMUZxzsYS0v3-CYIX3_iXlGUI2Ecw5L3JA0Z4)

Не смотря на то, что указанные команды показывают результат, похожий на ошибку, а именно

```
C:\WINDOWS\system32>sc stop windivert
[SC] ControlService: ошибка: 1062:

Служба не запущена.


C:\WINDOWS\system32>sc delete windivert
[SC] OpenService: ошибка: 1060:

Указанная служба не установлена.
```
после их выполнения новая версия запускается без ошибок.

**Comment by frozenheal1337** [comment]
> > подскажите, какую конкретно службу запустить? ![image](https://private-user-images.githubusercontent.com/67225544/363461669-eb1ca142-1561-4ec7-a3a1-e72aa12df2c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MzE1MzEsIm5iZiI6MTcyNjgzMTIzMSwicGF0aCI6Ii82NzIyNTU0NC8zNjM0NjE2NjktZWIxY2ExNDItMTU2MS00ZWM3LWEzYTEtZTcyYWExMmRmMmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDExMjAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZmVlOGFlNjJlNzMwMTliOGNmYjA5NmE4NjgwNWM3NmMxOTM0MzAxYzBiNmYxZDVkM2Q2ODE4MGUyZjRjYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uEYskWvMUZxzsYS0v3-CYIX3_iXlGUI2Ecw5L3JA0Z4)
> 
> Не смотря на то, что указанные команды показывают результат, похожий на ошибку, а именно
> 
> ```
> C:\WINDOWS\system32>sc stop windivert
> [SC] ControlService: ошибка: 1062:
> 
> Служба не запущена.
> 
> 
> C:\WINDOWS\system32>sc delete windivert
> [SC] OpenService: ошибка: 1060:
> 
> Указанная служба не установлена.
> ```
> 
> после их выполнения новая версия запускается без ошибок.

у меня так пропала ошибка 433 A device which does not exist was specified.

только вот работать от этого не начало

**Comment by Ponomarev23** [comment]
Просто отключи его в диспетчере задач, лол

**Comment by bershasml** [comment]
> Решение данной проблемы в 99.99%.
> 
> Запускаем **командную строку - CMD от имени администратора**, и вводим поочерёдно команды: **1) sc stop windivert** **2) sc delete windivert**
> 
> Старый драйвер удалится от старой версии GoodbyeDPI, и запустится без ошибок новая версия GoodbyeDPI 0.2.3rc1.
> 
> Так-же можете через батник файл **.cmd** попробовать автора, который в корне с программой лежит "**service_remove.cmd**"
> 
> Всем удачи!

У меня пишет "Отказано в доступе".  [SC] OpenService: ошибка: 5:

**Comment by kornilovmustdie** [comment]
CMD от админа

`sc stop windivert`
`sc delete windivert`
ребутаем комп
ставим актуальную версию запрета (1.6.1) https://github.com/Flowseal/zapret-discord-youtube/releases/tag/1.6.1
через service_install.bat от админа, например general (ALT2)

**Comment by fixinchik** [comment]
Не помогает. Все та же ошибка.
Службу не устанавливаю, просто запускаю 1_russia_blacklist_YOUTUBE.cmd и вот протокол:
```
GoodbyeDPI v0.2.3rc3: Passive DPI blocker and Active DPI circumvention utility
https://github.com/ValdikSS/GoodbyeDPI

Loaded 154025 hosts from file ..\russia-blacklist.txt
Loaded 14 hosts from file ..\russia-youtube.txt
Block passive: 0
Block QUIC/HTTP3: 1
Fragment HTTP: 2
Fragment persistent HTTP: 2
Fragment HTTPS: 2
Fragment by SNI: 0
Native fragmentation (splitting): 1
Fragments sending in reverse: 1
hoSt: 0
Host no space: 0
Additional space: 0
Mix Host: 0
HTTP AllPorts: 0
HTTP Persistent Nowait: 1
DNS redirect: 0
DNSv6 redirect: 0
Allow missing SNI: 0
Fake requests, TTL: fixed (fixed: 0, auto: 0-0-0, min distance: 0)
Fake requests, wrong checksum: 1
Fake requests, wrong SEQ/ACK: 1
Fake requests, custom payloads: 6
Fake requests, resend: 1
Max payload size: 1200

Opening filter
Error opening filter: 3 The system cannot find the path specified.

```
Обнаружил что после запуска скрипта sc delete опять удаляет службу, т.е. видимо запуск опять где-то прописывает службу. Потому что если просто так вызывать удаление, пишет что службы нет.

```
D:\Users\fixin>sc delete windivert
[SC] DeleteService: успех
```

В папке x86_64 все файлы есть:
goodbyedpi.exe
WinDivert.dll
WinDivert64.sys
Проблема началась при переносе обработки в другой каталог, но как называется первый я не запомнил, удалил его, поэтому восстановить туда не получится.

**Comment by m4kogn4ik** [comment]
Thanks!
