### ISSUE TITLE
Установка (и удаление) в качестве сервиса Windows не работает

### ISSUE THREAD

**Issue by Savely22828** [ValdikSS/GoodbyeDPI#439]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Когда пытаюсь запустить файл выдаёт ошибку:
This script should be run with administrator privileges.
Right click - run as administrator.
Press any key if you're running it as administrator.
Я тыкаю правой кнопкой мыше по .bat файлу, нажимаю "Запуск от имени администратора" и выдаёт туже ошибку описанную выше. Тоже самое происходит с другими .bat фалами связанными с установкой как сервис Windows (включая удаление)

**Comment by mayorovp** [comment]
Это не ошибка, а напоминание. Вы любую клавишу -то нажимали?

**Comment by ValdikSS** [comment]
Что не работает? Сервис не устанавливается? Не удаляется?
Сообщение о необходимости запуска от администратора выдаётся в любом случае.

**Comment by lynrayy** [comment]
Вчера пытался брату на комп поставить, там была какая-то ошибка, что то типо device not found. Win 10
У меня же всё встало на Win 11

Кстати, сегодня перестало работать...

**Comment by chasingEcho** [comment]
позавчера работал, вчера перестал... все опции поперетыкал вроде googlevideo пингуется но работает только через прокси

**Comment by Handhok** [comment]
@ValdikSS 
![image](https://github.com/user-attachments/assets/80592c84-bc96-4c81-be2b-665f9c75f5a8)
![image](https://github.com/user-attachments/assets/b327efdb-17eb-40f2-aa63-fee68e578276)
![image](https://github.com/user-attachments/assets/300d6168-2a33-4a9b-9df0-f883b8166c59)
![image](https://github.com/user-attachments/assets/7ac96c35-e0f1-4a1f-a74a-10f3459d3f40)
![image](https://github.com/user-attachments/assets/795ff9dd-c7b2-4695-84ae-7c3043fb3d3e)
![image](https://github.com/user-attachments/assets/1f5f0e0b-7358-47ec-95da-9a0dd862439d)
если открывать фал не попути заранее рпопписав его в cmd, а просто double click по bat'нику, то скрипт автоматом закрывается за долю секунды, поэтому тебе никто не мог ничего кинуть. Все скрипты не были изменены. При изменении файлов на проверку/наличие UAC (из первого вопрос в закрепе) - ничего не поменялось.

**Comment by ValdikSS** [comment]
@Handhok проверяйте состояние службы после установки: `sc query GoodbyeDPI`

**Comment by NiroEnvy** [comment]
![image](https://github.com/user-attachments/assets/4af2ffde-5b3a-43e1-86c1-b2ab672f925e)
?

**Comment by MirlanAskingQuestions** [comment]
А как удалить? Через ПКМ не получается, пишет:  "Операция не может быть завершена, так как эти папка и файл уже открыты в другой программе"; и так уже после 3-й перезагрузок компьютера.

**Comment by lynrayy** [comment]
> А как удалить? Через ПКМ не получается, пишет: "Операция не может быть завершена, так как эти папка и файл уже открыты в другой программе"; и так уже после 3-й перезагрузок компьютера.

Запусти service_remove.cmd, она удалит сервис. После чего можно будет удалить файлы

**Comment by ValdikSS** [comment]
Нет ответа от автора.
