### ISSUE TITLE
Версия для MacOS

### ISSUE THREAD

**Issue by wsnnn** [ValdikSS/GoodbyeDPI#44]
Очень бы хотелось видеть версию под MacOS

**Comment by ValdikSS** [comment]
Программа совместима только с Windows, и это никак не изменить.

**Comment by kolyanok** [comment]
>Программа совместима только с Windows, и это никак не изменить.

Почему? В макоси же есть divert socket'ы из BSD, разве я не прав? Если разберусь с тем, как это вообще работает, возможно, сделаю порт.
Хотя, конечно, интереснее бы было сделать независимое от подключаемых девайсов решение для роутеров (хотя бы для OpenWRT), но там задачка посложнее, конечно...

**Comment by ValdikSS** [comment]
>windivert, на котором основана программа, по сути является их интерпретацией под винду, разве я не прав?

WinDivert — драйвер, использующий Windows Filtering Platform. Если переделывать под Linux и Mac OS, то сразу на связке TCP и RAW-сокетов.

**Comment by kolyanok** [comment]
> RAW-сокетов.
А через эту штуку же нельзя пакет остановить. Посмотреть и заглянуть во внутрь можно, а помешать ему дойти до адресата — нет.
Кроме divert-сокетов я вообще не понимаю, как еще можно сделать. Но в случае с маоксью даже с ними не особо ясно: ipfw, в котором можно было перенаправить пакеты в divert, выпилили в 10.10, а pf, который Элл рекомендует использовать вместо ipfw, в макоси почему-то не поддерживает divert. Короче, с эплом я пока не понял. Спрашивал на стэковерфлоу https://stackoverflow.com/questions/48540345/how-to-configure-pf-on-macos-to-work-with-divert-sockets , на ЛОРе https://www.linux.org.ru/forum/development/13995433?lastmod=1517704493374#comment-14000573 — никто ответа не знает, тема слишком нишевая. 

Попробую с линуксом чуть попозже.

**Comment by wsnnn** [comment]
А через что работает little Snitch? Ведь через него проходят все пакеты. Я вообще изначально думал, что стоит покопать именно его, вдруг достаточно в нем хакнуть какой-нибудь самый базовый фильтр.

**Comment by ValdikSS** [comment]
>А через эту штуку же нельзя пакет остановить. Посмотреть и заглянуть во внутрь можно, а помешать ему дойти до адресата — нет.

Поэтому нужно использовать RAW-сокет для отправки пакетов, и обычный TCP-сокет для их получения, перенаправляя все исходящие пакеты на него, аналогом iptables -j REDIRECT/DNAT в Linux.

**Comment by ValdikSS** [comment]
https://salferrarello.com/mac-pfctl-port-forwarding/

**Comment by kolyanok** [comment]
@ValdikSS 
А если приложение упало/не было запущено, то тогда, если используется это правило для файрвола, все пакеты пойдут "мимо кассы"? Мне кажется, что это не особо хорошее решение, если я все правильно понял...

**Comment by grandsilence** [comment]
https://github.com/dzhidzhoev/AntiRTDPI потенциальное решение, пока нет возможности попробовать

**Comment by wsnnn** [comment]
> https://github.com/dzhidzhoev/AntiRTDPI потенциальное решение, пока нет возможности попробовать

Попробовал, сделал все по инструкции, на 10.13.6 0 реакции.

**Comment by grandsilence** [comment]
> > https://github.com/dzhidzhoev/AntiRTDPI потенциальное решение, пока нет возможности попробовать
> 
> Попробовал, сделал все по инструкции, на 10.13.6 0 реакции.

очень жаль, но спасибо большое что отписались. Может попробую на Mojave, как будет время.

**Comment by Glorian** [comment]
> https://github.com/dzhidzhoev/AntiRTDPI потенциальное решение, пока нет возможности попробовать

На Mojave 10.14.4 все завелось, спасибо!

**Comment by grandsilence** [comment]
> 
> 
> > https://github.com/dzhidzhoev/AntiRTDPI потенциальное решение, пока нет возможности попробовать
> 
> На Mojave 10.14.4 все завелось, спасибо!

Возникли какие-то сложности?

**Comment by Glorian** [comment]
> > > https://github.com/dzhidzhoev/AntiRTDPI потенциальное решение, пока нет возможности попробовать
> > 
> > 
> > На Mojave 10.14.4 все завелось, спасибо!
> 
> Возникли какие-то сложности?

Практически никаких. Xcode при сборке бросил несколько варнингов, два из них сам же и исправил, а оставшиеся два я проигнорировал:
``` 
ld: warning: object file (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libkmod.a(c_start.o)) was built for newer OSX version (10.14) than being linked (10.12)

ld: warning: object file (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libkmod.a(c_stop.o)) was built for newer OSX version (10.14) than being linked (10.12)

```

**Comment by grandsilence** [comment]
> 
> 
> > > > https://github.com/dzhidzhoev/AntiRTDPI потенциальное решение, пока нет возможности попробовать
> > > 
> > > 
> > > На Mojave 10.14.4 все завелось, спасибо!
> > 
> > 
> > Возникли какие-то сложности?
> 
> Практически никаких. Xcode при сборке бросил несколько варнингов, два из них сам же и исправил, а оставшиеся два я проигнорировал:
> 
> ```
> ld: warning: object file (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libkmod.a(c_start.o)) was built for newer OSX version (10.14) than being linked (10.12)
> 
> ld: warning: object file (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libkmod.a(c_stop.o)) was built for newer OSX version (10.14) than being linked (10.12)
> ```

Спасибо большое за инфу)

**Comment by ValdikSS** [comment]
AntiRTDPI — очень простая программа, которая работает только для HTTP и только на Ростелекоме.

**Comment by Mesteriis** [comment]
Ну так может взять за аналог?) и допилить, у меня увы нет знаний WinAPI, Так бы сам переложил это дело на qt

**Comment by quyleanh** [comment]
I come here to ask a version for macOS. Do you change your mind?

**Comment by wsnnn** [comment]
> I come here to ask a version for macOS. Do you change your mind?

The minimum version that users still have is MacOS High Sierra. It has no such restrictions, as in the recent versions.

**Comment by quyleanh** [comment]
@wsnnn how can I use in MacOS?

**Comment by wsnnn** [comment]
> @wsnnn how can I use in MacOS?

No way. Windows only. The topic was with a proposal to the author to make a port for MakOS, he said that it was impossible.

**Comment by grishka** [comment]
> Ну так может взять за аналог?) и допилить, у меня увы нет знаний WinAPI, Так бы сам переложил это дело на qt

WinDivert платформозависимый. Проще с нуля написать. Единственное что я пока не нашёл, где и как можно подлезть в плане API, а то в последних macOS со сторонними кекстами всё очень грустно. Смотрю в сторону NetworkExtension, но как-то вот не очень понимаю, как оно должно работать.

**Comment by Mesteriis** [comment]
Привет, свои 5 копеек, в маке такое можно провернуть только с отключением Self protect (SiP) кажись называется, не очень кошерный способ, да и "домохозяйкам" не очень катит, так как по факту отключаем всю защиты оси. Если очень сильно хочется, я бы смотрел в сторону модуля для OpenWRT или аналога, коих много. Тогда вообще все устройства в сети будут пользоваться и пофиг на платформу

**Comment by grishka** [comment]
> в маке такое можно провернуть только с отключением Self protect (SiP) кажись называется, не очень кошерный способ, да и "домохозяйкам" не очень катит, так как по факту отключаем всю защиты оси

System integrity protection. Защищает системные файлы от записи из самой системы. Но нет, для загрузки кекстов её не нужно полностью отключать даже на М1. А для расширений системы (system extensions) вообще ничего отключать не надо, они работают в юзерспейсе.

**Comment by munrocket** [comment]
Пока только решение для сафари, открываем терминал и прописываем 
```sh
curl -fsSL https://raw.githubusercontent.com/xvzc/SpoofDPI/main/install.sh | bash -s darwin-amd64 
```
далее  
```sh
export PATH=$PATH:~/.spoof-dpi/bin 
```
запускаем   
```sh
spoof-dpi 
```

Теперь проверяем ютуб в сафари. если чет не открывается, то закрываем терминал, делаем все заново, но вместо последней команды прописываем:  
```sh
spoof-dpi --enable-doh --window-size 0 
```

**Comment by Rena-Ivis** [comment]
> Пока только решение для сафари, открываем терминал и прописываем
> 
> ```shell
> curl -fsSL https://raw.githubusercontent.com/xvzc/SpoofDPI/main/install.sh | bash -s darwin-amd64 
> ```
> 
> далее
> 
> ```shell
> export PATH=$PATH:~/.spoof-dpi/bin 
> ```
> 
> запускаем
> 
> ```shell
> spoof-dpi 
> ```
> 
> Теперь проверяем ютуб в сафари. если чет не открывается, то закрываем терминал, делаем все заново, но вместо последней команды прописываем:
> 
> ```shell
> spoof-dpi --enable-doh --window-size 0 
> ```

For google just enable proxy server auto-detection after all steps

**Comment by guinmoon** [comment]
Проверил на Sonoma 14.5, работает

**Comment by guinmoon** [comment]
> Пока только решение для сафари, открываем терминал и прописываем
> 
> ```shell
> curl -fsSL https://raw.githubusercontent.com/xvzc/SpoofDPI/main/install.sh | bash -s darwin-amd64 
> ```
> 
> далее
> 
> ```shell
> export PATH=$PATH:~/.spoof-dpi/bin 
> ```
> 
> запускаем
> 
> ```shell
> spoof-dpi 
> ```
> 
> Теперь проверяем ютуб в сафари. если чет не открывается, то закрываем терминал, делаем все заново, но вместо последней команды прописываем:
> 
> ```shell
> spoof-dpi --enable-doh --window-size 0 
> ```

Проверил на Sonoma 14.5, работает

**Comment by SamGamgee2105** [comment]
> Пока только решение для сафари, открываем терминал и прописываем
> 
> ```shell
> curl -fsSL https://raw.githubusercontent.com/xvzc/SpoofDPI/main/install.sh | bash -s darwin-amd64 
> ```
> 
> далее
> 
> ```shell
> export PATH=$PATH:~/.spoof-dpi/bin 
> ```
> 
> запускаем
> 
![Снимок экрана 2024-09-04 в 15 21 33](https://github.com/user-attachments/assets/675c809d-29bf-4261-9bd2-98a4dd3a566d)

> ```shell
> spoof-dpi 
> ```
> 
> Теперь проверяем ютуб в сафари. если чет не открывается, то закрываем терминал, делаем все заново, но вместо последней команды прописываем:
> 
> ```shell
> spoof-dpi --enable-doh --window-size 0 
> ```

У меня не вышло. Все делал строго по инструкции
![image](https://github.com/user-attachments/assets/56cf994d-4b4f-447b-92f4-b67157636719)

**Comment by SamGamgee2105** [comment]
> > Пока только решение для сафари, открываем терминал и прописываем
> > ```shell
> > curl -fsSL https://raw.githubusercontent.com/xvzc/SpoofDPI/main/install.sh | bash -s darwin-amd64 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > далее
> > ```shell
> > export PATH=$PATH:~/.spoof-dpi/bin 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > запускаем
> > ```shell
> > spoof-dpi 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Теперь проверяем ютуб в сафари. если чет не открывается, то закрываем терминал, делаем все заново, но вместо последней команды прописываем:
> > ```shell
> > spoof-dpi --enable-doh --window-size 0 
> > ```
> 
> Проверил на Sonoma 14.5, работает

У меня не вышло. Непонятно с чем связано
![Снимок экрана 2024-09-04 в 15 21 33](https://github.com/user-attachments/assets/9f535b27-8497-40a0-a299-d45ce5367661)

**Comment by erikdark** [comment]
> > > Пока только решение для сафари, открываем терминал и прописываем
> > > ```shell
> > > curl -fsSL https://raw.githubusercontent.com/xvzc/SpoofDPI/main/install.sh | bash -s darwin-amd64 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > далее
> > > ```shell
> > > export PATH=$PATH:~/.spoof-dpi/bin 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > запускаем
> > > ```shell
> > > spoof-dpi 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Теперь проверяем ютуб в сафари. если чет не открывается, то закрываем терминал, делаем все заново, но вместо последней команды прописываем:
> > > ```shell
> > > spoof-dpi --enable-doh --window-size 0 
> > > ```
> > 
> > 
> > Проверил на Sonoma 14.5, работает
> 
> У меня не вышло. Непонятно с чем связано ![Снимок экрана 2024-09-04 в 15 21 33](https://private-user-images.githubusercontent.com/61319522/364372742-9f535b27-8497-40a0-a299-d45ce5367661.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mjc4NzMsIm5iZiI6MTcyNTYyNzU3MywicGF0aCI6Ii82MTMxOTUyMi8zNjQzNzI3NDItOWY1MzViMjctODQ5Ny00MGEwLWEyOTktZDQ1Y2U1MzY3NjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDEyNTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNzdkNjI4MDdhZWFmYjE0YjJhYTQxNjRhODA0MmI3MWQ3MDgxMDEwZTg0ZTVmMjg5NjIwYjZkN2Q0OTE2MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8RgFs4e2uzS_4Y-q5Ouu4YT4INlRfdN-FXXiNM2UDas)

привет у тебя не вышло потому что имя файла без дефиса будет 
запусти ls ~/.spoofdpi/bin
и сам увидишь ))

**Comment by erikdark** [comment]
> > > Пока только решение для сафари, открываем терминал и прописываем
> > > ```shell
> > > curl -fsSL https://raw.githubusercontent.com/xvzc/SpoofDPI/main/install.sh | bash -s darwin-amd64 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > далее
> > > ```shell
> > > export PATH=$PATH:~/.spoof-dpi/bin 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > запускаем
> > > ```shell
> > > spoof-dpi 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Теперь проверяем ютуб в сафари. если чет не открывается, то закрываем терминал, делаем все заново, но вместо последней команды прописываем:
> > > ```shell
> > > spoof-dpi --enable-doh --window-size 0 
> > > ```
> > 
> > 
> > Проверил на Sonoma 14.5, работает
> 
> У меня не вышло. Непонятно с чем связано ![Снимок экрана 2024-09-04 в 15 21 33](https://private-user-images.githubusercontent.com/61319522/364372742-9f535b27-8497-40a0-a299-d45ce5367661.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mjc4NzMsIm5iZiI6MTcyNTYyNzU3MywicGF0aCI6Ii82MTMxOTUyMi8zNjQzNzI3NDItOWY1MzViMjctODQ5Ny00MGEwLWEyOTktZDQ1Y2U1MzY3NjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDEyNTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNzdkNjI4MDdhZWFmYjE0YjJhYTQxNjRhODA0MmI3MWQ3MDgxMDEwZTg0ZTVmMjg5NjIwYjZkN2Q0OTE2MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8RgFs4e2uzS_4Y-q5Ouu4YT4INlRfdN-FXXiNM2UDas)

а и папка для path тоже по другому

Скрипт установки указал, что SpoofDPI установился в папку ~/.spoofdpi/bin, а не ~/.spoof-dpi/bin, как ты добавил в PATH.

export PATH=$PATH:~/.spoofdpi/bin

**Comment by dmsabath** [comment]
не арбайтн
