### ISSUE TITLE
Проблема  OpenService FAILED 1060

### ISSUE THREAD

**Issue by YaNTCN** [ValdikSS/GoodbyeDPI#440]
### Operating system / операционная система

Windows 11 23H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS

SERVICE_NAME: GoodbyeDPI
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 2148
        FLAGS              :

### Additional information / Дополнительная информация

Изночально я случайно запустил не от имени администратора, потом запустил от имени администратора удаление скрипта, потом от имени администратора запустил service_install_russia_blacklist.cmd нажал на кнопку и вот такие вот ошибки.

**Comment by ValdikSS** [comment]
Ошибок нет, всё так и должно быть.

**Comment by ValdikSS** [comment]
Сервис запущен? Что конкретно не работает, предоставьте больше информации.

**Comment by YaNTCN** [comment]
пробовал открывать через cmd и powershall все от имени админа, по PID его небыло. С стандартными опциами которые может быть прописаны в service_install_russia_blacklist.cmd

сам 1_russia_blacklist работает, но когда запускаю сервис инстал, пишет такие ошибки, ничего не поделать, пробовал переустанавливать драйвера сетевухи и перезагружать пк, ничего не помогает. Устанавливал 2.0 2.1 2.2 2.3 версии

**Comment by YaNTCN** [comment]
@ValdikSS
