### ISSUE TITLE
Откат к дефолтным настройкам/выключение

### ISSUE THREAD

**Issue by kozlovva** [ValdikSS/GoodbyeDPI#442]
### Operating system / операционная система

Windows 11 23H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Есть ли возможность откатить настройки? После запуска команды 1_russia_blacklist перестали загружаться сайты с включенным VPN. Хочется иметь возможность возврата к дефолтным настройкам

**Comment by urayde** [comment]
#426

**Comment by kozlovva** [comment]
Помогло подключение Kyper

**Comment by ValdikSS** [comment]
Достаточно закрыть окно программы.
