### ISSUE TITLE
Неккоректная работа других программ

### ISSUE THREAD

**Issue by DaniilRen** [ValdikSS/GoodbyeDPI#443]
### Operating system / операционная система

Windows 11 Pro 23H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

После установки программы в качестве сервиса, ютюб работает как надо, но возникают проблемы с подключением к другим сайтам/приложениям. Например, не работает Discord (веб и десктопная версии) и Epic Games Store. При обычном запуске (не как сервис) таких проблем нет.

**Comment by ValdikSS** [comment]
> При обычном запуске (не как сервис) таких проблем нет.

Вы запускаете программу с такими же параметрами и в случае обычного запуска, и в случае сервиса?
Нет — проблема в этом.
Да — вероятно, программам не нравится WinDivert (или сам GoodbyeDPI) — обращайтесь к их создателям.
Как пример: https://github.com/ValdikSS/GoodbyeDPI/issues/148

**Comment by reas24** [comment]
> > При обычном запуске (не как сервис) таких проблем нет.
> 
> Вы запускаете программу с такими же параметрами и в случае обычного запуска, и в случае сервиса? Нет — проблема в этом. Да — вероятно, программам не нравится WinDivert (или сам GoodbyeDPI) — обращайтесь к их создателям. Как пример: #148

Ситуация ещё хуже этой, не работает очень многое из зарбежных/игровых и д.р сайтов/программ(включая стим дискорд и тд), ютуб работает(используется  стандартный файл и вообще вся пограмма только сток во всех описанных вариантах), не взависимости сервис или сама прогамма, но есть другой пк и знакомые у которых работает все выше перечисленное без проблем как через прогу так и через сервис.

**Comment by picolino** [comment]
А у меня вообще караул, не работают сервисы даже после закрытия программы и перезагрузки, в качестве службы не устанавливал) Ужас

**Comment by picolino** [comment]
> А у меня вообще караул, не работают сервисы даже после закрытия программы и перезагрузки, в качестве службы не устанавливал) Ужас

На машине выставился прокси. Не знаю сделали ли это GoodbyeDPI, но отключение прокси-сервера помогло с неработоспособностью сторонних приложений.

![image](https://github.com/user-attachments/assets/578579f9-e847-445f-b48a-aafad70124d6)

**Comment by IRainman** [comment]
> На машине выставился прокси. Не знаю сделали ли это GoodbyeDPI, но отключение прокси-сервера помогло с неработоспособностью сторонних приложений.
Прокси программа точно не использует нив  каком виде.

**Comment by DaniilRen** [comment]
> > А у меня вообще караул, не работают сервисы даже после закрытия программы и перезагрузки, в качестве службы не устанавливал) Ужас
> 
> На машине выставился прокси. Не знаю сделали ли это GoodbyeDPI, но отключение прокси-сервера помогло с неработоспособностью сторонних приложений.
> 
> ![image](https://private-user-images.githubusercontent.com/17460456/354674706-578579f9-e847-445f-b48a-aafad70124d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjY3NDMsIm5iZiI6MTcyMjYyNjQ0MywicGF0aCI6Ii8xNzQ2MDQ1Ni8zNTQ2NzQ3MDYtNTc4NTc5ZjktZTg0Ny00NDVmLWI0OGEtYWFmYWQ3MDEyNGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE5MjA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMWI4OGE2NjFiNWE1NWI1YjAzZDVhNDQxNDM4N2MyYWZmMjYyNDRkYTdiYjUwMjgwZTcxMjg2ZjViYzBkMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kRNdg_awgeMQAsN22zErT-pTaeRbSsaDdQnMFsHKpiA)

а ютюб у вас при этом работает?

**Comment by picolino** [comment]
> а ютюб у вас при этом работает?

Только при запуске GoodbyeDPI и отключении Kyber'а в браузере
