### ISSUE TITLE
Can't serf internet while script is working. Can only watch youtube (in high quality)

### ISSUE THREAD

**Issue by MaratZakirov** [ValdikSS/GoodbyeDPI#445]
### Operating system / операционная система

Windows 11 Pro 23H2 build 22631.3880

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

The tool is definitly working it gives me ability to watch youtube in hight quality without freezes but in case I try to enter other site or even comment section in same video I watch browser just refuses to access that.  I collected log traces using wireshark.

### Additional information / Дополнительная информация

1) I disabled IPv6 in Wi-Fi network connection and after that nslookup seems to be working
2) starting nslookup
C:\Users\user>nslookup
```
╤хЁтхЁ яю єьюыўрэш■:  UnKnown
Address:  192.168.1.254

> youtube.com
╤хЁтхЁ:  UnKnown
Address:  192.168.1.254

Не заслуживающий доверия ответ:
╚ь :     youtube.com
Addresses:  2a00:1450:4010:c0f::5d
          2a00:1450:4010:c0f::5b
          2a00:1450:4010:c0f::be
          2a00:1450:4010:c0f::88
          108.177.14.136
          108.177.14.190
          [108.177.14.93](url)
          108.177.14.91

> 
```
3) Starting your tool
4) Entering wireshark start collecting log trace
5) Entering yotube.com from Edge browser
6) Saving trace  [with_tool.zip](https://github.com/user-attachments/files/16473267/with_tool.zip)
7) Same thing but yor tool was stopped trace 
[without_tool.zip](https://github.com/user-attachments/files/16473279/without_tool.zip)

**Comment by ValdikSS** [comment]
`-e1`
