### ISSUE TITLE
Добавьте пожалуйста возможность сворачивать окно приложения в трей <3

### ISSUE THREAD

**Issue by Vilenchik** [ValdikSS/GoodbyeDPI#447]
### Describe your feature / Опишите ваше предложение

Добавьте пожалуйста возможность сворачивать окно приложения в трей <3

**Comment by Semka2014** [comment]
Если вдруг, сильно нужно, я сделал временное решение на питоне https://github.com/ValdikSS/GoodbyeDPI/issues/459#issuecomment-2266357285

**Comment by Geil** [comment]
@Vilenchik можно запустить программу как службу, тогда не будет беспокоить, достаточно один раз запустить service_install_russia_blacklist.cmd (от админа).

**Comment by AndyShade** [comment]
https://github.com/Virenbar/GDPIControl
все что нужно ничего лишнего

**Comment by ValdikSS** [comment]
#65
#459
#324

**Comment by durakivan** [comment]
I also tried to make my own GUI for tray and autostart. Currently it's in Beta state but if anyone is interested, please :)
[https://github.com/durakivan/GUIdbyeDPI](https://github.com/durakivan/GUIdbyeDPI)
