### ISSUE TITLE
Не открывается сайт на новой пререлизной версии goodbyedpi-0.2.3rc1

### ISSUE THREAD

**Issue by Quaterberg** [ValdikSS/GoodbyeDPI#448]
### Operating system / операционная система

Windows 10 20H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Суть такова. На новой версии goodbyedpi-0.2.3rc1 не открываются борды форчана, например https://boards.4chan.org/v/
- Код ошибки: SSL_ERROR_RX_MALFORMED_SERVER_HELLO - такая ошибка в FF версии 128.0.3 
- ERR_QUIC_PROTOCOL_ERROR - такая ошибка в Opera One (версия: 113.0.5230.8)

Но если зайти на главную страницу https://4chan.org/ - она открывается, а уже с нее открывается без проблем любая борда 

Такой проблемы нет на версии goodbyedpi-0.2.2

файл russia-blacklist.txt одинаковый
запуск произвожу через 1_russia_blacklist_dnsredir.cmd

**Comment by PukPukov** [comment]
У меня всё работает.
