### ISSUE TITLE
Аномальное пожирание памяти браузером

### ISSUE THREAD

**Issue by ssbugman** [ValdikSS/GoodbyeDPI#449]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

После запуска GoodbyeDPI потребление оперативной памяти браузером резко улетело в небо. Браузер занял более 15 гигабайт в оперативке и это похоже не предел а лишь на момент когда я заметил.

**Comment by kivimr** [comment]
ну  у меня 32Гб озу брат мне не грозит  такая проблем но вас жаль

**Comment by ValdikSS** [comment]
Вряд ли это как-либо связано с программой, разве что могло раскрыть какой-то баг сетевой части.
Вам нужно собрать данные самого браузера и сообщить о проблеме разработчикам браузера. Даже если на утечку повлиял GoodbyeDPI, проблема непосредственно в браузере, и я здесь бессилен.
