### ISSUE TITLE
Error when opening the site / Ошибка при открытии сайта

### ISSUE THREAD

**Issue by DUBINCA** [ValdikSS/GoodbyeDPI#450]
### Operating system / операционная система

Windows 11 23H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Hello, when trying to open kemono domains, error 504 appears in any program mode from -1 to -9, when using VPN everything works, when trying to open without GoodbyeDPI and VPN, the site does not open at all. It's not like working with any other sites. / Здравствуйте, при попытке открытия доменов kemono, при любом режиме программы от -1 до -9 появляется ошибка 504, при использовании ВПН всё работает, при попытке открытия без GoodbyeDPI и ВПН сайт вообще не открывается. Это не похоже на работу с какими-либо другими сайтами.

![image](https://github.com/user-attachments/assets/18ebd383-9459-4b63-84fc-1348a84fa2a4)

### Additional information / Дополнительная информация

Version: [0.2.3rc1](https://github.com/ValdikSS/GoodbyeDPI/releases/tag/0.2.3rc1)

**Comment by ValdikSS** [comment]
Это не проблема программы.
https://ntc.party/t/не-открывает-kemonosu/8489
