### ISSUE TITLE
Отключение дискорда

### ISSUE THREAD

**Issue by nmsltr** [ValdikSS/GoodbyeDPI#451]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Когда GBD работает дискорд перестаёт работать. Просто хотел сказать об этом если ещё не слышал

### Additional information / Дополнительная информация

нэту

**Comment by ValdikSS** [comment]
Используйте blacklist.
