### ISSUE TITLE
Умерли почти все игры и некоторые сайты

### ISSUE THREAD

**Issue by KiLLeRmAn19** [ValdikSS/GoodbyeDPI#455]
### Operating system / операционная система

Windows 10 22h2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Заголовок сказал все по факту, умер LoL, RotMG, не умерла разве что игра с русскими серверами. Стер все данные с диска С (ставил на другой, но перед очисткой диска удалил все, что "позволили" даже с отключением службы в диспетчере, после очистки удалил остаток). Итог - ютуб медленно грузит, часть сайтов и игр полностью отказываются грузиться. По факту хотел только спросить : как это все удалить/откатить?

**Comment by dallas1981s** [comment]
а что значит умерли, задержка, не запускаются? как такое возможно вообще.....

**Comment by KiLLeRmAn19** [comment]
> а что значит умерли, задержка, не запускаются? как такое возможно вообще.....

Формулировку выбрал не ту, согласен. Умерли в том плане, что вообще не пускает на сервера, максимум в меню, но зайти в матч или на сервер игры уже все, загрузка около минуты и ошибка о невозможности подключится к серверам

**Comment by dallas1981s** [comment]
Проблему уже решили? У меня к примеру чудил интернет 2 последние дня с гугловскими днс, пришлось изменить на стандард, полагаю это связано с последними новостями

**Comment by ValdikSS** [comment]
Если вы закрыли программу и не устанавливали её как сервис, некоторые игры могут проверять наличие сервиса WinDivert (#148), выполните дополнительно от имени администратора:

```
sc stop windivert
sc delete windivert
```

Если это не помогло, то проблема не в программе.
