### ISSUE TITLE
Произвольное отключение программы

### ISSUE THREAD

**Issue by Dogewagon** [ValdikSS/GoodbyeDPI#456]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Проблема состоит в том, что после того как я запускаю программу, она:
Во-первых, не всегда срабатывает. Под этим я имею в виду то, что после запуска, YouTube ложится окончательно и жалуется на отсутствие подключения к сети (иногда даже затрагивает и другие сайты, например не грузятся страницы на GitHub и ВК).
Во-вторых, после просмотра пары-тройки видео (суммарно через минут 40-50) программа перестаёт работать и, при попытке включить новое видео или перейти на любую иную страницу на сайте, тот умирает и жалуется на отсутствие интернета. Также подобная проблема касается и стримов: во время стрима перестаёт работать чат, тем не менее возможность смотреть стрим дальше остаётся.
Использую последнюю версию программы, запускаю service_install_russia_blacklist.cmd от имени администратора, Kyber отключён.

**Comment by ValdikSS** [comment]
Приведите конкретные параметры запуска, которые вы передаёте сервису.
Запишите дамп трафика, когда такое происходит, особенно не с сайтами из blacklist.

https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by Baks456** [comment]
если вы "запускаю service_install_russia_blacklist.cmd" - то у вас программа запущена как сервис, вам нет нужды её включать каждый раз.
 попробуйте:
 1) запустить от имени администратора service_remove.cmd
 2) потом запустить от имени администратора service_install_russia_blacklist.cmd
 3) перезагрузить компьютер и больше ничего запускать, оно должно работать.

**Comment by Dogewagon** [comment]
> если вы "запускаю service_install_russia_blacklist.cmd" - то у вас программа запущена как сервис, вам нет нужды её включать каждый раз. попробуйте:
> 
> 1. запустить от имени администратора service_remove.cmd
> 2. потом запустить от имени администратора service_install_russia_blacklist.cmd
> 3. перезагрузить компьютер и больше ничего запускать, оно должно работать.

То же самое происходит и когда я запускаю программу как сервис. То есть: запускаю service_install_russia_blacklist.cmd от имени администратора, проходит определённое время и программа снова перестаёт работать, после этого запускаю service_remove.cmd, также от имени администратора, и снова повторяю первый шаг. Только после этого программа вновь начинает работать и то только на определённый период. Грубо говоря мне приходится с определёнными промежутками перезагружать программу, чтобы был хоть какой-то эффект.

**Comment by ValdikSS** [comment]
То же самое и к вам, что во втором сообщении.

**Comment by ValdikSS** [comment]
Нет ответа от автора.
