### ISSUE TITLE
как удалить?

### ISSUE THREAD

**Issue by SkaT04** [ValdikSS/GoodbyeDPI#457]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

не может найти файл

### Additional information / Дополнительная информация

собираюсь переходить на новую версию

**Comment by GerHanNaAn** [comment]
Зайдите внутрь папки с программой и удалите файлы, которые возможно удалить. Часть файлов не удастся удалить, потому что они используются. С оставшимися папками сделать тоже самое. Зайти внутрь папки и удалить файлы. Дальше нужно перезагрузить ПК и удалить оставшееся. По крайней мере, у меня такой алгоритм сработал.

**Comment by ValdikSS** [comment]
Закройте программу, запустите от имени администратора:

```
sc stop windivert
sc delete windivert
```

**Comment by Devollox** [comment]
Всем привет! Кто будет читать эту проблема и выше предложения вам не помогли, то попробуйте: Нажимаете `win+r` вводим `msconfig` заходим в службы и находим GDPI и просто отключаем. Перезагружаем ПК и пробуем удалить.
