### ISSUE TITLE
Иконка в трее

### ISSUE THREAD

**Issue by Semka2014** [ValdikSS/GoodbyeDPI#459]
### Describe your feature / Опишите ваше предложение

Было бы неплохо добавить иконку в трее, чтобы когда программа запускалась через автозагрузку, её можно было включать и выключать. Просто когда я включаю VPN, с goodbyedpi у меня никакие сайты не загружаются.

**Comment by Semka2014** [comment]
[goodbyedpi-0.2.2.zip](https://github.com/user-attachments/files/16477977/goodbyedpi-0.2.2.zip)
Моё решение на python. Нужно поместить в папку с программой и запускать run_TrayManager.cmd. Но всё таки, решение из коробки, наверное будет лучше

**Comment by Slamifoe21** [comment]
Хорошая идея. Я за!!
