### ISSUE TITLE
Онлайн Радио

### ISSUE THREAD

**Issue by HunDev** [ValdikSS/GoodbyeDPI#46]
При запущенном GoodbyeDPI  винамп не играет онлайн радио (например http://icecast.pulsradio.com:80/pulsHD.mp3) всегда возвращая HTTP400

**Comment by ValdikSS** [comment]
Если вы не запускаете программу с опцией -a, это значит, что удаленный сервер не полностью соответствует стандарту HTTP. Это не проблема программы.

**Comment by ValdikSS** [comment]
В GoodbyeDPI 0.1.2 добавлен механизм черного списка, теперь незаблокированные сайты не обрабатываются программой, и ваше радио будет воспроизводиться.
