### ISSUE TITLE
Поддержка Linux, Android, Android TV

### ISSUE THREAD

**Issue by The-Mate-Developer** [ValdikSS/GoodbyeDPI#461]
### Describe your feature / Опишите ваше предложение

Я не разбираюсь, как работает GoodbyeDPI, но могу помочь с конкретно Android-приложением.

**Comment by Semka2014** [comment]
Есть аналоги проекта на другие платформы. В репозитории есть их список: https://github.com/ValdikSS/GoodbyeDPI?tab=readme-ov-file#similar-projects
