### ISSUE TITLE
Видео в youtube не грузится

### ISSUE THREAD

**Issue by danil123** [ValdikSS/GoodbyeDPI#462]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

![Screenshot 2024-08-03 142636](https://github.com/user-attachments/assets/46b5c503-1e7d-4cb2-a0a6-225e793cc1c1)
Запускаю программу, она вроде работает. Видео на ютубе все равно не грузится.
Пробовал и новую, и старую версию. Не работает

**Comment by Semka2014** [comment]
Вот инструкция для обхода замедления ютуба https://github.com/ValdikSS/GoodbyeDPI/issues/378
И ещё, убедитесь, что файл russia-blacklist.txt содержит строку googlevideo.com

**Comment by ValdikSS** [comment]
Это не ошибка программы. Читайте инструкцию!

**Comment by danil123** [comment]
Я делал все по инструкции, сайт в текстовый файловый фал добавлял, kyber отключал. Не работает.
