### ISSUE TITLE
Не работает видео в ютубе

### ISSUE THREAD

**Issue by Merlin2Github** [ValdikSS/GoodbyeDPI#464]
### Operating system / операционная система

WINDOWS 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Дня 2 назад программа работала исправна, но сегодня начались проблемы. Использую версию 0.2.3. Пытался использовать программу и обычным образом и службой, не помогло. Пытался также переустанавливать службу и открывал service_remove. Так сбилось на всех компьютерах в доме куда ставил программу.

**Comment by valkar24** [comment]
У меня то же самое. Вчера работало везде отлично, сегодня никакие манипуляции не помогают. Пробовал разные ключи -5, -6, -7 и ничего.
