### ISSUE TITLE
GoodbyeDPI major problem

### ISSUE THREAD

**Issue by Ch3rtila13123** [ValdikSS/GoodbyeDPI#466]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Я включал прогу через `1_russia_blakclist.cmd` как и было сказано. Kyber отключен. Главная проблема в том что все работает, но на 720 видео в ютубе кэширует очень медленно, что приводит к частым заиканиям. Так же я пробовал выключать и включать обратно прогу через `1_russia_blackist_dnsredir, 2_any_country, 2_any_country_dnsredir. `Все работает абсолютно так же - видео медленно кэшируются

**Comment by Merlin2Github** [comment]
тоже самое

**Comment by abizeyshn** [comment]
Протокол QUIC отключите.
