### ISSUE TITLE
Не грузятся изображения на сайте exhentai.org без VPN (ростелеком) 

### ISSUE THREAD

**Issue by metalslayer** [ValdikSS/GoodbyeDPI#467]
### Describe your feature / Опишите ваше предложение

https://exhentai.org/
![exhentai org](https://github.com/user-attachments/assets/e643e849-7b5c-457e-84af-0a729506a9ab)

Вместе с VPN грузятся

**Comment by Ch3rtila13123** [comment]
Гениален

**Comment by NetDriver0** [comment]
чел, скажи спасибо что сам сайт грузится
