### ISSUE TITLE
GoodbyeDPI v0.1.2rc2 ломает работу Modern приложений в Windows 10.

### ISSUE THREAD

**Issue by krab** [ValdikSS/GoodbyeDPI#47]
Сабж в заголовке. Так вот имеем свежеустановленную Windows 10 на SSD со всеми обновлениями и драйверами. 

Ставлю GoodbyeDPI v0.1.2rc2 и такие программы как Windows Store, Xbox, Браузер Edge загружают страницы на половину не важно какой сайт. Xbox как и Store выглядит совсем пустыми без загруженных изображений.

С GoodbyeDPI v0.1.1 все в порядке никаких проблем.

**Comment by ValdikSS** [comment]
С какими параметрами вы запускаете программу?

**Comment by krab** [comment]
-4 как и раньше

**Comment by ValdikSS** [comment]
В таком случае, снимите дамп сетевого трафика и отправьте его мне на почту.

**Comment by krab** [comment]
И чем же это лучше сделать?

**Comment by lieff** [comment]
https://www.wireshark.org/

**Comment by shikulja** [comment]
Тоже на Rc1 Rc2
в edge страницы то не открываются, то открываются, не разобрался еще.
 и в Heroes of the Storm 
> Подключение к серверу потоковой загрузки

висит и ничего не происходит, как только отключаю, сразу в игру заходит.
настройки
http://skrinshoter.ru/s/121217/XYvOfwkK?a
работает только когда выставлена одна галочка Обход пассивных DPI

надеюсь поможет

**Comment by ValdikSS** [comment]
Исправлено в GoodbyeDPI v0.1.2rc3

**Comment by shikulja** [comment]
Да и в hots и в edge вроде бы все нормально.
