### ISSUE TITLE
Не открывается

### ISSUE THREAD

**Issue by DALLORDCR** [ValdikSS/GoodbyeDPI#470]
### Operating system / операционная система

Андроид 12

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Нажимаю на файл для рф, но у меня выбирает какой тип открытия(аудио, текст и тд) открывается нормально только текст и ничего не происходит

**Comment by k0zyrev** [comment]
Goodbyedpi работает только под windows. Ищите клиент под андроид внизу [readme.md ](https://github.com/ValdikSS/GoodbyeDPI/blob/master/README.md)
