### ISSUE TITLE
GoodbyeDPI doesn't work on Windows XP

### ISSUE THREAD

**Issue by koke228666** [ValdikSS/GoodbyeDPI#471]
### Operating system / операционная система

Windows XP SP3 x86

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Starting any .bat file just shows a black cmd window without a text, also as starting .exe from x86 folder

**Comment by xtcorp** [comment]
винду нормальную поставь, а не некрофильскую
