### ISSUE TITLE
Автозапуск вместе с Windows и/или сворачивание в трей.

### ISSUE THREAD

**Issue by Pevznerok** [ValdikSS/GoodbyeDPI#472]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [ ] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Неудобно каждый раз запускать cmd, когда хочешь пользоваться интернетом. Было бы неплохо иметь автозапуск вместе с виндой или сворачивание в трей, чтобы не было лишнего окна.

**Comment by Sto3IV** [comment]
install service bat

**Comment by icynstant** [comment]
на главной странице рассказывается как установить службу

**Comment by KIRUYXAN** [comment]
Я то ли тупой то ли что, но где там чё рассказывается
