### ISSUE TITLE
Bittorrent

### ISSUE THREAD

**Issue by neo1894** [ValdikSS/GoodbyeDPI#473]
### Operating system / операционная система

Windows 10 Pro 22H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

При скачивании торрента скорость упала до 1Мб/с, а до GoodBye DPI было 10Мб/с. Скажите как вернуть скорость ?
Хотел удалить из служб, а его там нет.

**Comment by neo1894** [comment]
Кстати сейчас проверил , общая скорость  упала. А была 98Mbps, 98Mbps
![тэст скорости](https://github.com/user-attachments/assets/57854b2e-4e1b-4492-937f-2312850dcbdb)

**Comment by xahon** [comment]
`service_remove.cmd` запускали?

**Comment by JacksonFrost13** [comment]
Плюсую, установка goodbyedpi как сервиса навернула все сетевые маршруты до хостов торрента. У меня попросту прилетает ошибка "Этот хост неизвестен" в uTorrent. Деинсталляция через service_remove и перезагрузка ПК помогли.
Хотелось бы решение данной проблемы

**Comment by JacksonFrost13** [comment]
Даже разовый запуск утилиты за сессию приводит к перманентной потере сетевого доступа до раздач. Помогает только перезагрузка ПК

**Comment by ValdikSS** [comment]
> "Этот хост неизвестен"

У вас точно не сломан DNS? Вы используете перенаправление DNS в программе? DNS-сервер при этом рабочий?

**Comment by yadalik** [comment]
Рекомендую попробовать другой торрент-клиент и отписаться. Например, у меня в qBittorrent проблем нет. Плюс, если трекер не закрытый, ему при включенном DHT в целом фиолетово до доступности хоста.

**Comment by JacksonFrost13** [comment]
Проверил qBittorrent, никаких проблем нет. Общая скорость соответствует тарифу, скорость трекера не падает. Спасибо

**Comment by ValdikSS** [comment]
Нет ответа от автора.

**Comment by interpol-kun** [comment]
У меня все раздачи с рутрекера отваливаются. Пишет, что точно так же хост unreachable, либо ошибку выдает `expected value (list, dict, int or string) in bencoded string`

Как только выключается утилита, можно обновлять трекеры и они приходят в норму. Скорее всего нужно выделить торрент-трекеры в отдельный блоклист, опциональный.
