### ISSUE TITLE
Как удалить

### ISSUE THREAD

**Issue by Egor69123** [ValdikSS/GoodbyeDPI#474]
### Operating system / операционная система

Win 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Перепробовал все:
Перезагрузку компа
Диспетчер задач
**sc stop windivert
sc delete windivert
sc stop windivert1.4
sc delete windivert1.4
sc stop "GoodbyeDPI
sc delete "GoodbyeDPI
sc stop "WinDivert1.4
sc delete "WinDivert1.4**
Сами файлы удалились, но последствия(а именно неработоспособность некоторых сайтов) так и остались. 
Помогите, пожалуйста, а то мне нужно работать еще на этом компе 😞

**Comment by ValdikSS** [comment]
Если окно программы закрыто — программа не работает!

**Comment by 11kaisd11** [comment]
Так может он через install запускал
