### ISSUE TITLE
Переписать всё на Rust

### ISSUE THREAD

**Issue by Hattiffnat** [ValdikSS/GoodbyeDPI#475]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Просто для надёжности )

**Comment by dFasdGii** [comment]
Начинай

**Comment by xahon** [comment]
Надёжность Rust

```rust
let something = 42;
...
let something = 43;
...
do_something_with_42(something);
```

**Comment by xahon** [comment]
Удобность Rust
![image](https://github.com/user-attachments/assets/4d240d21-9a7b-486c-b87c-d08d5151c019)

**Comment by Hattiffnat** [comment]
> Надёжность Rust
> 
> ```rust
> let something = 42;
> ...
> let something = 43;
> ...
> do_something_with_42(something);
> ```

а в чем здесь проблема?

**Comment by Slamifoe21** [comment]
> > Надёжность Rust
> > ```rust
> > let something = 42;
> > ...
> > let something = 43;
> > ...
> > do_something_with_42(something);
> > ```
> 
> а в чем здесь проблема?

Наверно в том что переменную можно объявить с одинаковым именем более 1 раза. Это может путать.

**Comment by rawello** [comment]
В чем смысл переписывать на раст, когда оно работает исправно на С? Ладно переписать на с++, а раст то зачем, в чем его преимущества, кроме мнимой "безопасности"?

**Comment by xahon** [comment]
> > Надёжность Rust
> > ```rust
> > let something = 42;
> > ...
> > let something = 43;
> > ...
> > do_something_with_42(something);
> > ```
> 
> а в чем здесь проблема?

Именно в том, о чём написал @Slamifoe21 
Объявил константную переменную в начале большой функции, в конце функции ожидается определённое значение, но в середине его можно изменить. С точки зрения константности - всё легально, мы не меняем память на которую оно указывает, с точки зрения логики работы программы - всё сломалось

**Comment by SagePtr** [comment]
Никто не запрещает сделать свой проект с похожим функционалом, но на Rust. Принципы обхода DPI не запатентованы вроде как.

**Comment by pasabanov** [comment]
В целом-то проект довольно небольшой.
Поддерживаю.

**Comment by Hattiffnat** [comment]
> Именно в том, о чём написал @Slamifoe21 Объявил константную переменную в начале большой функции, в конце функции ожидается определённое значение, но в середине его можно изменить. С точки зрения константности - всё легально, мы не меняем память на которую оно указывает, с точки зрения логики работы программы - всё сломалось

Что бы объявить константу надо использовать не let, а const

**Comment by pasabanov** [comment]
> Что бы объявить константу надо использовать не let, а const

Но `const` годится только для констант времени компиляции.

**Comment by xahon** [comment]
> > Именно в том, о чём написал @Slamifoe21 Объявил константную переменную в начале большой функции, в конце функции ожидается определённое значение, но в середине его можно изменить. С точки зрения константности - всё легально, мы не меняем память на которую оно указывает, с точки зрения логики работы программы - всё сломалось
> 
> Что бы объявить константу надо использовать не let, а const

Как правильно пояснили, `const` работает только если у нас есть compile-time значение. Если мы хотим получить неизменяемое значение как продукт функции, то такой код
```rust
const texture = LoadTexture("a.png");
```
не скомпилируется

**Comment by askolt** [comment]
Считаю что надо всё переписать на brainfuck.
