### ISSUE TITLE
Не устанавливается как сервис. С обычного запуска работает нормально. (Возможно из-за win11)

### ISSUE THREAD

**Issue by TheSubDex** [ValdikSS/GoodbyeDPI#477]
### Operating system / операционная система

Windows 11 Pro 23H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Не устанавливается программа как сервис. При открытии файла "service_install_russia_blacklist.cmd" с правами админа и нажатии клавиши, окошко мгновенно закрывается. Затем после просмотра информации о установленных сервисах, сервиса "GoodbuyDPI" там не обнаруживается. Простой запуск работает без проблем. Так же удалось поставить сервис отдельно через команды PowerShell, но использовались другие, которые укажу в доп информации.

### Additional information / Дополнительная информация

С помощью этих команд удалось поставить службу через PowerShell
```
$exepath = "C:\goodbyedpi-0.2.3rc1-2\goodbyedpi-0.2.3rc1\x86_64\goodbyedpi.exe"
$blacklist1 = "C:\goodbyedpi-0.2.3rc1-2\goodbyedpi-0.2.3rc1\russia-blacklist.txt"
$blacklist2 = "C:\goodbyedpi-0.2.3rc1-2\goodbyedpi-0.2.3rc1\russia-youtube.txt"
if (Get-Service -Name "GoodbyeDPI" -ErrorAction SilentlyContinue) 
{
    Stop-Service -Name "GoodbyeDPI" -Force
    Remove-Service -Name "GoodbyeDPI"
}
New-Service -Name "GoodbyeDPI" -BinaryPathName "$exepath -9 --blacklist $blacklist1 --blacklist $blacklist2" -StartupType Automatic
```

Есть предположение, что не работает именно из-за Windows 11, т.к. на NTC.party есть несколько человек с Windows 11, у кого схожие проблемы.

**Comment by ValdikSS** [comment]
А что выдаёт запуск команд `sc`, которые в скрипте? Запустите скрипт в консоли от имени администратора и пришлите полный вывод.

**Comment by TheSubDex** [comment]
> А что выдаёт запуск команд `sc`, которые в скрипте? Запустите скрипт в консоли от имени администратора и пришлите полный вывод.

![изображение](https://github.com/user-attachments/assets/6879b594-5d29-4b30-bef4-858d1abe957f)

**Comment by ValdikSS** [comment]
У вас сломана ОС, наверное, какая-то пиратская сборка? Это стандартная команда Windows, а она у вас отсутствует (либо C:\Windows\System32 не добавлен в PATH, но это также не бывает на стандартной ОС)

**Comment by TheSubDex** [comment]
> У вас сломана ОС, наверное, какая-то пиратская сборка? Это стандартная команда Windows, а она у вас отсутствует (либо C:\Windows\System32 не добавлен в PATH, но это также не бывает на стандартной ОС)

Странно... Винду качал с офф сайта майков. После активировал ключом из интернета. Никакие "Улучшалки" а-ля ShutUp10+ или что есть сейчас на 11 не использовал после последней переустановки винды. Сборка качалась обычная, не LTSС.

**Comment by urayde** [comment]
> > У вас сломана ОС, наверное, какая-то пиратская сборка? Это стандартная команда Windows, а она у вас отсутствует (либо C:\Windows\System32 не добавлен в PATH, но это также не бывает на стандартной ОС)
> 
> Странно... Винду качал с офф сайта майков. После активировал ключом из интернета. Никакие "Улучшалки" а-ля ShutUp10+ или что есть сейчас на 11 не использовал после последней переустановки винды. Сборка качалась обычная, не LTSС.

Проверьте наличие C:\Windows и C:\Windows\system32 в переменной PATH системы.

**Comment by TheSubDex** [comment]
> > > У вас сломана ОС, наверное, какая-то пиратская сборка? Это стандартная команда Windows, а она у вас отсутствует (либо C:\Windows\System32 не добавлен в PATH, но это также не бывает на стандартной ОС)
> > 
> > 
> > Странно... Винду качал с офф сайта майков. После активировал ключом из интернета. Никакие "Улучшалки" а-ля ShutUp10+ или что есть сейчас на 11 не использовал после последней переустановки винды. Сборка качалась обычная, не LTSС.
> 
> Проверьте наличие C:\Windows и C:\Windows\system32 в переменной PATH системы. На моей памяти был один подобный случай, но не могу вспомнить, как я решил проблему, скорее всего действительно одноразовый прикол win11 был.
Действительно, там нет C:\Windows и C:\Windows\system32

**Comment by ValdikSS** [comment]
Добавьте и проверьте скрипты. Должно заработать.

**Comment by jilokus** [comment]
Здравствуйте, у меня такая же проблема с открытием. Но я по комментариям не очень понял, что исправлять (не шарю совсем), можете объяснить для чайника7

**Comment by ValdikSS** [comment]
@jilokus 
Здесь описано, как в принципе работать с переменными
https://remontka.pro/add-to-path-variable-windows/
А здесь — какой примерно должна быть PATH
https://answers.microsoft.com/ru-ru/windows/forum/all/удалил-path-в/b404f447-796d-4ce1-b8dc-4367346e6b51
Сообщение Denis_DDDeniiso
