### ISSUE TITLE
Странное поведение проводника Windows dj время работы скрипта

### ISSUE THREAD

**Issue by Koxae** [ValdikSS/GoodbyeDPI#479]
### Operating system / операционная система

Windows 10 x64

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Во время работы скрипта периодически подглючивает проводник. И всегда глючит при выходе из режима гибернации.
Либо рабочий стол и панель задач чернеют. Либо перестаёт обновляться панель задач. Чинится перезапуском проводника.

**Comment by ValdikSS** [comment]
У программы даже графического интерфейса нет.
