### ISSUE TITLE
С новой версией 0.2.3 ошибка

### ISSUE THREAD

**Issue by vsn80** [ValdikSS/GoodbyeDPI#483]
### Operating system / операционная система

Windows 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

В новой версии 0.2.3 сайты не открываются, вылазит ошибка ERR_SSL_PROTOCOL_ERROR
в версии 0.2.2 все работает нормально

**Comment by iRadioMan** [comment]
Кстати, у меня такая же ошибка. Я просто несколько раз тыкаю Refresh и все работает
