### ISSUE TITLE
прога гамно и вирус!!

### ISSUE THREAD

**Issue by pro100sanyok** [ValdikSS/GoodbyeDPI#485]
### Operating system / операционная система

Виндв

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

прога галимое гамно и не открывает сайты!! у меня перестали открываться сайты с этой прогой, скорее всего это вирус, НЕ СТАВЬТЕ

**Comment by NorthGames** [comment]
А у меня почему- то клавиши начали сами собой работать на ноутбуке после установки программы. В чем причина ? Не подскажете ?

**Comment by Amegatron** [comment]
А у меня собака забеременела и дождь пошел (прямо в квартире). Точно вирус! 😂

**Comment by NorthGames** [comment]
Бро ты прав ! Это дождь льет пиздец )) мыши китайские делают и  у кошки из
 за этого месячные :)
Вообщем дело не в этом :) спасибо за обратную связь :)

**Comment by NorthGames** [comment]
Просто так совпало что мышь компьютерная перестала корректно работать в тот
момент как я скачал dpi и из за этого мысли полезли в голову всякие. А
насчет собаки не переживай раздашь щенков если че :)
