### ISSUE TITLE
Не удаётся найти "goodbyedpi.exe". Проверьте, правильно указано ли имя и повторите попытку

### ISSUE THREAD

**Issue by SitVey** [ValdikSS/GoodbyeDPI#486]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

При запуске "1_russia_blacklist.cmd", да и любых других cmd кроме "service_remove.cmd" компьютер выдаёт ошибку: "Не удаётся найти "goodbyedpi.exe". Проверьте, правильно указано ли имя и повторите попытку.".

Я ничего не перемещал, баг возникает на всех версиях, хотя в папках "x86_64" и "x86" exe-шник на месте. Пробовал отключать антивирусник, не помогает(

**Comment by xahon** [comment]
Напрямую из архива запускаете? Сначала надо распаковать архив на диск

**Comment by SitVey** [comment]
> Напрямую из архива запускаете? Сначала надо распаковать архив на диск
Спасибо большое за совет, всё заработало) долго мучался

**Comment by AaphexTwin** [comment]
а где этот архив найти?

**Comment by xahon** [comment]
> а где этот архив найти?

https://github.com/ValdikSS/GoodbyeDPI/releases/tag/0.2.2


goodbyedpi-0.2.2.zip

**Comment by 4opTuk** [comment]
что ж у меня дерьмовее ошибка,но похожая
то же самое но разархивация не помогает,почему? потому что антивирус снес корневые 3 файла для его корректной работы,это winsw.exe и gdpi.exe и вот весь трабл что я тупо не могу восстановить файл и путь к нему так как надо файлу,и варианта два:снос винды что очевиндо поможет и надежда в то что есть какой-то способ как удаленные антивирусом файлы которые уже не вернуть(их 100% не вернуть ибо я антивирус после такого в "обиде" или грусти хз удалил,думая что он мне еще че снесет хуже будет,оказалось надо было достать файлы из карантина но я проебался и теперь нет их там,следственно оттуда я их не верну и что мне делать я не знаю) и вот как их по другому скачать заново? например один из таких это 
![image](https://github.com/user-attachments/assets/c4a5b7dd-82e6-4f3a-88f2-9e12eb4d3599)
