### ISSUE TITLE
версия 0.1.2 x64 под win7 просит админа, хотя уже запущено из под админа

### ISSUE THREAD

**Issue by 40OIL** [ValdikSS/GoodbyeDPI#49]
под win7 просит админские права, хотя уже запущено из под админа

пробовал в отдельной консоли от администратора, и как службу через nssm от системной учетной записи запускать, одинаково выводит вот такой текст и закрывается; служба еще перезапускается по таймеру и загаживает этими сообщениями лог.
запускал без параметров, запускал с "-1" и "-1 --blacklist blacklist.txt", одинаково не работает, в последнем варианте еще пишет "Loaded 50247 hosts from file blacklist.txt".

что ей еще надо-то? 0.1.1 через nssm работала замечательно...

*****************
GoodbyeDPI: Passive DPI blocker and Active DPI circumvention utility
Block passive: 1, Fragment HTTP: 2, Fragment HTTPS: 2, hoSt: 1, Host no space: 1, Additional space: 0, Mix Host: 0, HTTP AllPorts: 0, DNS redirect: 0

Opening filter
The system cannot find the file specified.
The system cannot find the file specified.
Something went wrong!
Make sure you're running this program with administrator privileges
*****************

**Comment by ValdikSS** [comment]
Обновите вашу систему хотя бы до состояния 2015 года.

**Comment by 40OIL** [comment]
а есть где-то у вас на сайте требования, которым должна система соответствовать? какие-то версии файлов\пакетов необходимых?  или владельцы необновленной win7 пролетают просто по умолчанию?

**Comment by ValdikSS** [comment]
Я полагаю, что здравомыслящие люди не будут подключать не обновленную ОС к интернету. Если у вас не стоит обновление 2015 года, это значит, что на ваш компьютер можно прогрузить троянов и криптолокеров из любой локальной сети и публичной Wi-Fi-точки.
