### ISSUE TITLE
Windows XP support required

### ISSUE THREAD

**Issue by saboteur1000** [ValdikSS/GoodbyeDPI#491]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

У меня XP, но я тоже хочу смотреть YouTube. Или ваш продукт только для богатых мажоров?

**Comment by kawashirov** [comment]
Не думаю, что это возможно.
![image](https://github.com/user-attachments/assets/acca6404-2311-40a2-ab80-2eb983c0c3cd)

**Comment by k0zyrev** [comment]
Если у вас настолько древнее железо, в 2024 году осваивайте линукс. Там и программы будут работать из этого тысячелетия.

**Comment by saboteur1000** [comment]
Ну и что, что древнее железо, мы что, не люди что ли? Я же говорю, вы снобы и мажоры. Ровно такие же как и власть, запрещающая YouTube, для которой несогласные - это меньшинство, которое надо чморить и лишать прав.

**Comment by krlvm** [comment]
ByeDPI или PowerTunnel при условии установки JRE 1.8 должны заработать на Windows XP

**Comment by PukPukov** [comment]
> Ну и что, что древнее железо, мы что, не люди что ли? Я же говорю, вы снобы и мажоры. Ровно такие же как и власть, запрещающая YouTube, для которой несогласные - это меньшинство, которое надо чморить и лишать прав.

Эти жалобы нужно направлять не сюда, а шинде, что постоянно раздувает системные требования, на прикреплённой картинке ясно показано что в XP нет нужного функционала для работы гудбай дпи. Боюсь только, там будут слушать ещё меньше, чем тут.

**Comment by saboteur1000** [comment]
Да, конечно. Это так, крик отчаяния. Живите долго, молодёжь, плодитесь и размножайтесь. А мы, старые пердуны, уходим на свалку истории.

**Comment by iRadioMan** [comment]
Боже мой, компьютер под Windows 10 можно купить на сдачу с бабкиной пенсии. Вы что, смеетесь?

**Comment by PukPukov** [comment]
> мям пасмчтри у миня диньги линщищи я целый шиндавс 10 комп магу купить мям видиш?
