### ISSUE TITLE
Можете сделать расширение для браузеров и на андроид 

### ISSUE THREAD

**Issue by livxbox5** [ValdikSS/GoodbyeDPI#493]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Здравствуйте хотел узнать возможно ли сделать расширение GoodbyeDPI для браузеров как Chrome,Mozilla firefox  , что бы автоматически обновлялся и не скачивали его каждый раз новую версии 
___________________________________________________
А на андроид приложение рабочие

**Comment by gegemon2012** [comment]
Здравствуйте!


> Здравствуйте хотел узнать возможно ли сделать расширение GoodbyeDPI для браузеров как Chrome,Mozilla firefox , что бы автоматически обновлялся и не скачивали его каждый раз новую версии

Я не автор но учитывая что он сейчас очень загружен то отвечу за него - такое невозможно сделать на уровне DPI но можно сделать на уровне proxy или VPN. Автор этим заниматься вряд ли будет.



> А на андроид приложение рабочие

Есть DPI Tunnel v2 но для него необходимы права root (скачивается через F-Droid). При их наличии и с настройками по умолчанию у меня работает Youtube без ограничений.

**Comment by apan65** [comment]
https://github.com/dovecoteescapee/ByeDPIAndroid/releases

**Comment by ValdikSS** [comment]
Это едва ли возможно: средства браузера крайне скудны в этом плане, чтобы можно было сделать что-то достойное лишь расширением.

Есть, разве что, подобные хаки, работающие в ограниченных случаях: https://github.com/anticensority/decrab-youtube
