### ISSUE TITLE
windows 7 x64 freezes

### ISSUE THREAD

**Issue by shaihkritzer** [ValdikSS/GoodbyeDPI#495]
### Operating system / операционная система

windows 7 x64

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

After starting goodbye dpi 50% chance system will freeze immediately until hard reset. Pls fix asap.

**Comment by k0zyrev** [comment]
> Pls fix asap.

How? You haven't provided _any_ info on your problem other that it's a freeze. No one else is reporting the same issue, so the problem is 99% in your system, not in GDPI software. Update your windows.

**Comment by iRadioMan** [comment]
That's your problem, because GoodbyeDPI works good and don't cause any freezes in system. Old versions of Windows may not be compatible with new WinDivert driver. Use Windows 10 or 11 instead.

**Comment by shaihkritzer** [comment]
> > Pls fix asap.
> 
> How? You haven't provided _any_ info on your problem other that it's a freeze. No one else is reporting the same issue, so the problem is 99% in your system, not in GDPI software. Update your windows.

how do you provide any info on a freeze that cannot be any other way cured than hard reset??? it happens. here you go. no logs provided by goodbyedpi either.

**Comment by shaihkritzer** [comment]
> That's your problem, because GoodbyeDPI works good and don't cause any freezes in system. Old versions of Windows may not be compatible with new WinDivert driver. Use Windows 10 or 11 instead.

wrong answer. if it works good on your specific one system, that doesn't mean it works on 100% systems or at least 'good'. the software developer says it's compatible with win7 then it MUST work 100% properly no matter of how old or bad that OS is. if the developer is not ready to provide 100% compatibility, then he should exclude win7 out of supported systems, or fix the issue.

**Comment by iRadioMan** [comment]
> > That's your problem, because GoodbyeDPI works good and don't cause any freezes in system. Old versions of Windows may not be compatible with new WinDivert driver. Use Windows 10 or 11 instead.
> 
> wrong answer. if it works good on your specific one system, that doesn't mean it works on 100% systems or at least 'good'. the software developer says it's compatible with win7 then it MUST work 100% properly no matter of how old or bad that OS is. if the developer is not ready to provide 100% compatibility, then he should exclude win7 out of supported systems, or fix the issue.

GoodbyeDPI works good on all my computers including those that work under Windows 7. You may be using modified, broken or outdated installation of Windows 7 which causes problems. 

You can try **DISM /Online /Cleanup-Image /RestoreHealth** and **sfc /scannow**, maybe it helps?

But I highly recommend you to use Windows 10 / 11 because there is no point in using something older now, it's unsafe and it's unstable for new software.

**Comment by shaihkritzer** [comment]
it's my decision what to use. it's absurd to waste time on windows update for youtube only. no other reasons for changing OS on this machine. everything except this software works perfectly so far.

**Comment by iRadioMan** [comment]
Of course, this is your business. But if you don't want to follow the advice, then don't complain. This is not a problem of this software.

**Comment by shaihkritzer** [comment]
wrong. if the developer announces Win7 as supported system, then it should work 100% properly and bugless. otherwise this info should be removed as not truthful.

**Comment by iRadioMan** [comment]
Calm down, you won't achieve anything this way.

> You may be using modified, broken or outdated installation of Windows 7 which causes problems.

**Comment by EgorWeders** [comment]
Can you give more info about your system? Version, service packs , activation method ;). Devs announce unmodified systems as supported in most cases .

**Comment by ValdikSS** [comment]
@shaihkritzer please provide any details (event logs upon next start), or anything.

**Comment by prblm** [comment]
Возможно зависает из-за установленного брандмауера. Похожие симптомы у меня были на win7 x64 с установленным Agnitum Outpost PRO иногда зависал комп и только кнопка reset помогала. При чём у меня режим обучения и для первого запуска сетевых прог брандмауер запрашивает действия для этого приложения, для GoodbyeDPI он ничего запросил. Поэтому я вручную в настройках брандмауера добавил exe файл GoodbyeDPI и установил ему политику "Разрешать все действия". Типа так
![image](https://github.com/user-attachments/assets/1c77421c-bea5-4c74-9e9b-8742ce2f29ca)
после добавления зависания пропали.

Надеюсь подсказка поможет.

**Comment by ValdikSS** [comment]
Нет ответа от автора.
