### ISSUE TITLE
WinDivert64.sys couldn't be deleted even after consol was closed

### ISSUE THREAD

**Issue by ShSSP** [ValdikSS/GoodbyeDPI#496]
### Operating system / операционная система

Windows 10 Pro

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Found that some users have issues during deleting this program because WinDivert64.sys is still in use even after the app is closed. I checked this myself and had the same issue. 

According to the documentation about WinDivert64.sys, "It's running as long as console window is visible and terminates when you close the window".

Meanwhile, after restarting the PC, the problem was solved and WinDivert64.sys could be deleted. Doubtful, this is a critical one, but the bug is still a bug. Did you check for nothing? At least, I decide to write it here.

Great regards for this app, btw!

### Additional information / Дополнительная информация

![image](https://github.com/user-attachments/assets/6dd9435a-bb19-4d18-a073-f7961188eaed)

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/378#issuecomment-2267201431
