### ISSUE TITLE
goodbyedpi error opening filter

### ISSUE THREAD

**Issue by PavelP42** [ValdikSS/GoodbyeDPI#497]
### Operating system / операционная система

windows 7 SP1

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Opening filter
Error opening filter: The system cannot find the path specified.

![image](https://github.com/user-attachments/assets/a078ef47-3349-4549-b8c1-3f3ed16bbc5c)

**Comment by ValdikSS** [comment]
Запустите версию отсюда, сделайте скриншот с ней:
https://github.com/ValdikSS/GoodbyeDPI/actions/runs/10247853563

**Comment by PavelP42** [comment]
Теперь другая ошибка
![image](https://github.com/user-attachments/assets/3ec40ecb-9d6b-4d50-b9ae-9551c95b89c7)

**Comment by PavelP42** [comment]
Установил KB3033929 - все заработало, спасибо
