### ISSUE TITLE
Завершать работу драйвера WinDivert при закрытии GoodbyeDPI

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [ValdikSS/GoodbyeDPI#498]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Добрый день!
Добавьте возможность завершения драйвера автоматически после закрытия программы GoodbyeDPI, т.е. при закрытии консольного окна, я не использую служба, свернуть окошко для меня не является проблемой. Может в батнике что то дописать для такого функционала?

**Comment by Uasissualij** [comment]
Это давным-давно реализовано.
![06-08-2024_09 22 53](https://github.com/user-attachments/assets/0d16d886-89dd-4bb3-92a0-597dba456ad4)

**Comment by ValdikSS** [comment]
Ответ разработчика WinDivert:

 > By the way, why doesn't WinDivert stop the service right away on closing? Is it for compatibility with other WinDivert software running on the system at the same time?
 
As I recall, it is something like that.  Ideally I'd like to automatically unload the driver if no program is using it, but I could not find a safe way to do this without introducing race conditions.

Fortunately, if the driver is loaded but no program using it, it should not affect anything except consume a few Kb of memory.  It will only inject itself into the packet processing path if an program is actually using it.
