### ISSUE TITLE
Не заходит на трекер! / Does not log in to the tracker!

### ISSUE THREAD

**Issue by SatanNintendo** [ValdikSS/GoodbyeDPI#499]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Не могу зайти на оригинальный трекер без зеркала: nnm-club.me | nnm-club.to
Если можно добавить к релизу, было бы здорово.
Спасибо.
..............
I can't log in to the original tracker without a mirror: nnm-club.me | nnm-club.to
If it is possible to add to the release, it would be great.
Thank you.

**Comment by askolt** [comment]
Вы уверено что nnm-club.me вообще работает?

nnm-club.to блок с их стороны. Так что не получится тут что либо сделать.

**Comment by GreLI** [comment]
Надо без дефиса и .to. Так работает.

**Comment by SatanNintendo** [comment]
> Вы уверены что nnm-club.me вообще работает?
> 
> nnm-club.to блок с их стороны. Так что не получится тут что либо сделать.
> 
> Используйте их зеркало, с ним всё работает.

**nnm-club.me** работает через **CENO браузер**, заходит без проблем.
По поводу **nnm-club.to** я не знал, извиняюсь.
