### ISSUE TITLE
Рутрекер не отркрывается в версии 0.2.3rc1, но без проблем открывается в 0.2.2

### ISSUE THREAD

**Issue by JAKill02** [ValdikSS/GoodbyeDPI#500]
### Operating system / операционная система

Win 7 64 bit

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

-

### Additional information / Дополнительная информация

вот парямо сейчас, запускаю старую версию **0.2.2**, и Рутрекер без проблем открывается, без редиректа и какого либо шаманства.
решил протестировать **0.2.3rc1** и Рутрекер делает вид что мы с ним не знакомы, и мол не задерживайтесь молодой человек, проходите мимо. DNS  редирект  так же не решает проблему.

 явно пагубно сказались какие-то програмные отличия.

**Comment by 1vanK** [comment]
Может в новой версии параметры забыл поменять? У меня с -9 не открывается, а с -5 -e1 -q открывается

**Comment by JAKill02** [comment]
> Может в новой версии параметры забыл поменять? У меня с -9 не открывается, а с -5 -e1 -q открывается

хорошая шутка. 
вы серьёзно думаете что обычные люди вроде меня могут понять что тут можно настраивать и где?
особенно если инструкция на инглише и ты даже в общех чертах не знаком с настройкой подобного софта.
вы переоцениваете способности людей далёких от подобных вещей. инструкция, если она написана, всегда должна быть написана как для идиота, в противном случае толка от неё считай нет.

**Comment by JAKill02** [comment]
что ж, если бы мне не сказали, я бы и искать не полез.
ну раз уж нашёл, то и с другими поделюсь.

в корневой папке где лежат файлы программы,  жмём правой кнопкой мышки на файлах "1_russia_blacklist.cmd" или "1_russia_blacklist_dnsredir.cmd"
выбираем пункт меню "Изменить"
![gdpi01](https://github.com/user-attachments/assets/94be54aa-ebaf-4410-bfe0-80b1d3aed9ae)

в открывшемся текстовике, скролим строку вправо, пока не упрёмся в значение "goodbyedpi.exe -9"
вместо -9, вписывает на пробу значение из этого списка.

`LEGACY modesets:
 -1          -p -r -s -f 2 -k 2 -n -e 2 (most compatible mode)
 -2          -p -r -s -f 2 -k 2 -n -e 40 (better speed for HTTPS yet still compatible)
 -3          -p -r -s -e 40 (better speed for HTTP and HTTPS)
 -4          -p -r -s (best speed)

Modern modesets (more stable, more compatible, faster):
 -5          -f 2 -e 2 --auto-ttl --reverse-frag --max-payload
 -6          -f 2 -e 2 --wrong-seq --reverse-frag --max-payload
 -7          -f 2 -e 2 --wrong-chksum --reverse-frag --max-payload
 -8          -f 2 -e 2 --wrong-seq --wrong-chksum --reverse-frag --max-payload
 -9          -f 2 -e 2 --wrong-seq --wrong-chksum --reverse-frag --max-payload -q (this is the default)`
![gdpi02](https://github.com/user-attachments/assets/2e147312-685d-4581-8621-ddd03df1b047)

сохраняем изменения, тестируем.

 моём случае Рутрекер начал открыватсья на значениях с -5 по -7, и всё ещё открывается Твитач.

теперь люди хоть будут знать **КАК** и **ГДЕ** это можно настраивать.

**Comment by 1vanK** [comment]
> теперь люди хоть будут знать КАК и ГДЕ это можно настраивать.

https://github.com/ValdikSS/GoodbyeDPI/issues/378

**Comment by JAKill02** [comment]
> Эта issue прилеплена на главной https://github.com/ValdikSS/GoodbyeDPI/issues

замечательно, только там не слова нет про то, что  именно нужно открыть, как нужно открыть, и где заменить.
видимо все должны читат мысли автора и всем будет счастье.

**Comment by 1vanK** [comment]
Обычные люди и винду сами не поставят, кому надо тот разберется)

**Comment by samvova** [comment]
понятно это ты сырая поделка. у меня не работает - надоело уже перебирать параметры. 
но автор не обещал работу - просто выложить свои вечерние наработки

**Comment by ValdikSS** [comment]
@JAKill02
> вы серьёзно думаете что обычные люди вроде меня могут понять что тут можно настраивать и где?

Без обид и предъяв: поясните, пожалуйста, чем вы руководствовались, открывая этот issue? Читали ли вы текст, который был там написан большими буквами на весь экран несколько раз специально для того, чтобы его не пропустили?
Я пытаюсь понять, как можно улучшить инструкции и сообщения, но каждый раз пытаюсь что-то изменить, когда получаю issue вроде вашего.

**Comment by JAKill02** [comment]
> @JAKill02
> 
> > вы серьёзно думаете что обычные люди вроде меня могут понять что тут можно настраивать и где?
> 
> Без обид и предъяв: поясните, пожалуйста, чем вы руководствовались, открывая этот issue? Читали ли вы текст, который был там написан большими буквами на весь экран несколько раз специально для того, чтобы его не пропустили? Я пытаюсь понять, как можно улучшить инструкции и сообщения, и каждый раз пытаюсь что-то изменить, когда получаю issue вроде вашего.

всё просто, я хотел разобраться как решить проблему, которая явно была решаема, особенно если учесть что имеется разница в поведении  в разных версиях. и разобравшись, дать людям наглядный пример, что им делать, в случае если у них возникнет такая же ситуация.

**ветку созданную собой, рассматриваю как полезно-информационную, для прочих пользователей.**

### текст написанный большими буквами прочёл, он хорошо заметен.

создано в **Ошибках**, так как мой вопрос ни коим образом не связан с предложениями, да и с ошибками он тоже врядли связан, но больше способов ТУТ получить какой-то живой ответ или обсудить трудности связанные с программой, нет.

**Comment by ValdikSS** [comment]
> но больше способов ТУТ получить какой-то живой ответ или обсудить трудности связанные с программой, нет.

Разумеется, это issues — сообщения об ошибках. Здесь не должно быть вопросов и обсуждений — им не место в репозитории.

![image](https://github.com/user-attachments/assets/103275e3-8b47-4857-85d8-5ba817e27bd8)

**Comment by 1vanK** [comment]
Я кстати на форум зайти не мог без этой проги))

**Comment by JAKill02** [comment]
> Я кстати на форум зайти не мог без этой проги))

подтверждаю, несколько дней назад и у меня форум тоже был наглухо перекрыт.

**Comment by 1vanK** [comment]
Можно на гитхабе обсуждения замутить кстати (врубить discussions в настройках репозитория), их заблочить разве что с гитхабом вместе

**Comment by samvova** [comment]
> Можно на гитхабе обсуждения замутить кстати (врубить discussions в настройках репозитория), их заблочить разве что с гитхабом вместе

нечего тут обсуждать. приложение хорошее и работает

**Comment by 1vanK** [comment]
> нечего тут обсуждать. приложение хорошее и работает

это аналог форума, или форум тоже не нужен?

**Comment by samvova** [comment]
> > нечего тут обсуждать. приложение хорошее и работает
> 
> это аналог форума, или форум тоже не нужен?

это я так дурацкие сарказм применил. Приложение не работает и нет никакой информации как его настроить под конкретные условия; как подбирать параметры; как провести диагностику.  Либо сразу искать другое решение.

**Comment by 1vanK** [comment]
Ну я так понимаю, что только перебором параметров. Конкретных инструкций невозможно дать, так как для разных провайдеров работают разные способы

**Comment by samvova** [comment]
ну тут в вами в основном технари - давайте посчитаем тупой перебор комбинации и сочетаний из 20 параметров сколько займет? пока не сменится политика и ютуб разблокируют

**Comment by 1vanK** [comment]
я думаю от -1 до -9 перебрать займет минут 10

**Comment by samvova** [comment]
> я думаю от -1 до -9 перебрать займет минут 10

это предустановленные наборы. они не работают.  надо подбирать непосредственно параметры. 
но я думаю в моем случае не сработает - ни одно приложение обхода не работает. сейчас оттестят и у вас всех упадет

**Comment by 1vanK** [comment]
Возможно работают, просто надо сервис прибивать перед запуском с новыми параметрами (service_remove.cmd от админа запускать)

**Comment by samvova** [comment]
> Возможно работают, просто надо сервис прибивать перед запуском с новыми параметрами (service_remove.cmd от админа запускать)

спасибо за желанию помочь. И автору что попробовал хоть что-то сделать.

**Comment by ValdikSS** [comment]
@1vanK
>Можно на гитхабе обсуждения замутить кстати (врубить discussions в настройках репозитория), их заблочить разве что с гитхабом вместе

Основная причина использования форума в гибкости управления сообщениями и установки мягких ограничений, чтобы нуждающиеся в помощи сперва читал, и только потом писал, если решения проблемы не было найдено.
Форум позволяет удобно перемещать сообщения для их каталогизации, делать wiki-посты, отслеживать кучу важных _мне_ вещей разом. Всего это нет ни в issues, ни в discussions github'а.

---

@samvova вся информация есть закреплённом посте: #378, "Программа не разблокирует сайты на моём провайдере!".
Если указанные примеры вам не подходят, то программа не заработает на вашем провайдере/роутере.
Я проверил работоспособность на ≈40 провайдерах 2 дня назад, везде работала, но требовались разные режимы.

Инструкцию для проведения диагностики написать в двух словах для технически неподкованного пользователя невозможно, а хоть какая-то запустит только больший поток сообщений — это именно то, от чего я пытаюсь огородиться. В обычные дни мне приходят 200+ емейлов в сутки, а с популярностью программы их 1000+. Я отвечаю людям по мере возможностей, но сообщения вроде «программа не работает» от человека, который не прочитал написанный текст, где всё разобрано, только отвлекают меня от более важных дел.

**Comment by ValdikSS** [comment]
@samvova
> давайте посчитаем тупой перебор комбинации и сочетаний из 20 параметров сколько займет?

Можете поперебирать комбинации с  помощью скрипта blockcheck, он работает минут 20. Вдруг какой-то из способов заработает на вашем провайдере (или заработает zapret из того, что не реализовано в goodbyedpi)

https://github.com/bol-van/zapret/
https://github.com/bol-van/zapret-win-bundle
