### ISSUE TITLE
Параметр --dns-port не влияет на вывод значения dstPort при --dns-verb в окне программы

### ISSUE THREAD

**Issue by EgorWeders** [ValdikSS/GoodbyeDPI#501]
### Operating system / операционная система

Windows 10 Enterprise LTSC 1809

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Параметр --dns-port не изменяет значение по-умолчанию.
Можно проследить даже на поставляемом .cmd файле.
![Снимок экрана (11)](https://github.com/user-attachments/assets/fb88f25c-567f-4aee-a7c2-fe696b2e3e7c)

Запускал:
start "" goodbyedpi.exe -9 --dns-verb --dns-addr 77.88.8.8 --dns-port 1254 --blacklist ..\russia-blacklist.txt

### Additional information / Дополнительная информация

Также валится без вывода инфы на неверных параметрах (порт днс без адреса), хотя в коде есть обработка ошибки. Если надо создам еще issue.

**Comment by ValdikSS** [comment]
> Параметр --dns-port не изменяет значение по-умолчанию.

Как воспроизвести? Ваша команда у меня работает.

![image](https://github.com/user-attachments/assets/c037a1bf-7d8d-47ed-bf1e-0175c7f9628a)

>Также валится без вывода инфы на неверных параметрах (порт днс без адреса), хотя в коде есть обработка ошибки. 

С какими параметрами запускать?

```
C:\Users\user2\Desktop\goodbyedpi-0.2.3rc1\x86_64>goodbyedpi.exe -9 --dns-verb --dns-port 1253
GoodbyeDPI v0.2.2: Passive DPI blocker and Active DPI circumvention utility
https://github.com/ValdikSS/GoodbyeDPI

--dns-port should be used with --dns-addr!
Make sure you use --dns-addr and pass it before --dns-port
```

**Comment by EgorWeders** [comment]
Я все запускаю через cmd

1. Прикладываю весь cmd

`@ECHO OFF
PUSHD "%~dp0"
set _arch=x86
IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)
PUSHD "%_arch%"

start "" goodbyedpi.exe -9 --dns-verb --dns-addr 77.88.8.8 --dns-port 1253 --blacklist ..\russia-blacklist.txt

POPD
POPD
`
Проблема может быть в выводе --dns-verb, я через него проверяю.

2.Запускаю напрямую екзешник, все равно нет вывода в консоль об ошибке.
1 запуск успешный
2 краш и возврат управления в cmd
![изображение](https://github.com/user-attachments/assets/4b83f23b-8f54-4894-9a57-bc24f86dd8e0)

**Comment by EgorWeders** [comment]
Как появится возможность чекнуть на других компах сразу напишу, может у меня конкретно волшебный.

**Comment by ValdikSS** [comment]
> 2.Запускаю напрямую екзешник, все равно нет вывода в консоль об ошибке.

Консоль необходимо запускать от имени администратора, чтобы получать вывод из программ, требующих запуска от администратора.

**Comment by EgorWeders** [comment]
Забыл, про консоль теперь понятно, но вывод работы cmd бы тоже хотелось бы увидеть при ошибке.

**Comment by ValdikSS** [comment]
У .cmd такое же ограничение, если я вас правильно понял. Если вы запускаете .cmd через командную строку администратора, то вы увидите вывод. Если нет — то программа откроется в новом окне и закроется.

https://window-opens-and-closes.info/

**Comment by EgorWeders** [comment]
А вот c .cmd нет вывода в любую консоль
![изображение](https://github.com/user-attachments/assets/b0dc04dc-0401-489f-a6c3-d2b6adcd9923)

**Comment by ValdikSS** [comment]
Действительно. Это из-за использования `start`.

**Comment by EgorWeders** [comment]
Таким образом мы никак не узнаем об ошибке параметров при запуске .cmd файла. Может при выходе по ошибке которую мы знаем  getChar какой-нибудь ставить?

**Comment by ValdikSS** [comment]
Тогда при установке сервисом программа будет как бы запущена, но при этом не работать.
Я не разбираюсь в Windows. Если у вас есть идеи, как это улучшить — пишите.

**Comment by EgorWeders** [comment]
Issue была не про вывод ошибки, а про некорректный dstPort в выводе программы

**Comment by ValdikSS** [comment]
А, он корректный: отображаются пакеты, принятые от клиента (запросы DNS на порт 53), а не перенаправленные.

**Comment by EgorWeders** [comment]
То есть dstPort в выводе не зависит от --dns-port в .cmd?
![изображение](https://github.com/user-attachments/assets/33f5bed2-5f6c-4a3a-a227-6360d3676e8d)
