### ISSUE TITLE
Убрать поддержку Windows 7

### ISSUE THREAD

**Issue by iRadioMan** [ValdikSS/GoodbyeDPI#503]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Уважаемый разработчик! Уберите из описания поддержку Windows 7, так как драйвер WinDivert больше не работает на ней стабильно. Сохраните нервы себе и другим. Заодно дадите хоть небольшую мотивацию людям не сидеть на старом rовне. Надеюсь на понимание!

**Comment by ValdikSS** [comment]
На текущий момент поддержка Windows 7 требует минимальных усилий (использование старой версии WinDivert, т.к. на 7 [не запускаются драйвера, подписанные после июля 2021 года](https://www.osr.com/blog/2020/10/15/microsoft-driver-updates-allowed-win7-win8/), хотя и для этого есть хаки).

Поддержка будет убрана, как только она станет невозможна или сильно затруднена. Пока программе не нужны новые функции из новых версий WinDivert, известных проблем в старых версиях также не наблюдается.
Пока всё работает, не вижу смысла убирать.
