### ISSUE TITLE
Return codes

### ISSUE THREAD

**Issue by EgorWeders** [ValdikSS/GoodbyeDPI#504]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

При ошибках ведущих к выходу программы  код всегда один (EXIT_FAILURE). Будет лучше добавить различные коды для обработки вне основного цикла работы программы. Сервисы кстати тоже могут обрабатывать код возврата.
Пример

```
const int EXIT_DNS_PORT_ARG=-1337
...
\\Ошибка чтения агрумента для днс порта
exit(ERR_DNS_PORT_ARG)
...
```

**Comment by ValdikSS** [comment]
Чем это может быть полезно практически, а не гипотетически? Вы какую-то оболочку делаете?

**Comment by EgorWeders** [comment]
1.С помощью них можно без особого переписывания кода на сях выводить описание ошибки в .cmd
2.Если он умрет в сервисах винды , то через журнал событий тоже можно будет увидеть код ошибки.
3.Это довольно легко добавить в код. Пару констант и их возврат где щас EXIT_FAILURE. Можно конечно его форкнуть для этого, но мне кажется это слишком малое улучшение для этого.

**Comment by EgorWeders** [comment]
Вдобавок, можно будет как модуль подключать без изменения исходников))

**Comment by ValdikSS** [comment]
Patches welcome

**Comment by EgorWeders** [comment]
https://github.com/ValdikSS/GoodbyeDPI/pull/507
