### ISSUE TITLE
Неактуально. Удалить.

### ISSUE THREAD

**Issue by OsclassEvo** [ValdikSS/GoodbyeDPI#505]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Неактуально. Можно удалять

**Comment by h4skell** [comment]
Найс заказуха, чел.

**Comment by OsclassEvo** [comment]
> Найс заказуха, чел.

офнись, лось
