### ISSUE TITLE
Не получается запустить Call Of Duty HQ пока программа установлена

### ISSUE THREAD

**Issue by Chebyrek180808** [ValdikSS/GoodbyeDPI#508]
### Operating system / операционная система

Windows 11 23H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Пытался запустить Call Of Duty HQ пока программа была **установлена**. Проблема не решалась не смотря на переустановку игры из разных лаунчеров (к примеру, Steam/Battle.net), проверку игровых файлов и т.д. Но стоило запустить  service_remove, игра заработала сразу же.

**Comment by ValdikSS** [comment]
❔ Почему не запускается Call Of Duty и некоторые другие игры?

Античитам не нравится драйвер WinDivert, см https://github.com/ValdikSS/GoodbyeDPI/issues/148, https://github.com/ValdikSS/GoodbyeDPI/issues/172.
Обращайтесь в поддержку игры.

**Comment by Skezz231** [comment]
https://www.youtube.com/watch?v=I8iwXR_SsvU&lc=Ugw0shagKBO6F_JTEQp4AaABAg.A6sMPNvOiY9A6sNJs7zuJM
