### ISSUE TITLE
Windows RT solution

### ISSUE THREAD

**Issue by hooddy** [ValdikSS/GoodbyeDPI#51]
Привет. Спасибо огромное за тулзу. Вопрос, есть ли возможность реализовать это на WinRT. Мне видится, что варианта два - либо компиляция под arm, либо скриптом на PowerShell (он на WinRT есть). Ну или руками. Устроит любой вариант, даже просто если объясните, как ручками все сделать.

**Comment by ValdikSS** [comment]
Я сомневаюсь, что на Windows RT есть возможность загрузки собственных драйверов. Она же, вроде, урезанная, без полного доступа к ОС? Там вообще программы от имени администратора можно запускать?

**Comment by hooddy** [comment]
Можно (почти) все, есть джейлбрейк, есть консоль и павершелл. Попробуйте скомпилить его для арм, я буду тестить. Не уверен, что могу мотивировать вас чем-то еще, кроме как "ну пжлста")

**Comment by ValdikSS** [comment]
Для начала нужно скомпилировать и подписать драйвер. На Windows RT есть возможность загрузки неподписанных драйверов?

**Comment by hooddy** [comment]
Насчет драйверов - VueScan появился под арм, как 32, так и 64 бита. Устанавливается на джейловую систему и если не париться потом с его обновлением, там кроме поддержки новых сканнеров, то можно и на джейл забить, он после обновлений винды отваливается. Но ставятся и дрова сторонние и приложение. Т.ч. все возможно, по крайней мере, нам первый взгляд.

**Comment by hooddy** [comment]
В общем, есть. Вы запилите, а я проверю.

**Comment by hooddy** [comment]
Можно и подписать драйвер, мне разраб vuescan скинул что-то.

**Comment by hooddy** [comment]
Вот письмо от разраба VueScan (весьма лаконичное))):
[key-surf.zip](https://github.com/ValdikSS/GoodbyeDPI/files/1623438/key-surf.zip)

This is the line from the makefile where I sign the drivers:
 
SIGNA    =    "$(SDKBRT)\signtool.exe" sign     /fd sha256 /f $(COMMON)sign\key-surf.pfx /p ""        /tr http://timestamp.digicert.com /td sha256 /as /v
 
I’ve attached key-surf.pfx
 
Regards,
Ed Hamrick

**Comment by ValdikSS** [comment]
Это какой-то утекший ключ для подписи? Или там пропатчено, что все ключи принимаются?

**Comment by hooddy** [comment]
Если честно, я не знаю. Я не спросил, он не писал подробностей. Давайте проверим, что получится на выходе.

**Comment by ValdikSS** [comment]
В архиве самоподписанный ключ, видимо, в качестве примера.
Я напишу разработчику WinDivert. Без драйвера ничего не получится.

**Comment by hooddy** [comment]
Есь утилита для подписывания в принципе.
[Windows_RT_8.1_Signtool.zip](https://github.com/ValdikSS/GoodbyeDPI/files/1623576/Windows_RT_8.1_Signtool.zip)

**Comment by hooddy** [comment]
Кароче, не судьба.
