### ISSUE TITLE
New adress for russia_blacklist

### ISSUE THREAD

**Issue by andreybexus** [ValdikSS/GoodbyeDPI#511]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Новые адреса для russia_blacklist
Больше доменов :)
More domains :)
[russia-blacklist.txt](https://github.com/user-attachments/files/16539715/russia-blacklist.txt)
Добавлены boosty.to и patreon.com
Отключайте VPN, некоторые сайты перестают работать, у меня такое было. Включил VPN и сайты просто не загружаются, пишет ошибка подключения. Отключил VPN и нормально всё грузится.
Turn off the VPN, some sites stop working, I had this. I turned on the VPN and the sites just don't load, writes a connection error. I turned off the VPN and everything is loading normally.

**Comment by andreybexus** [comment]
Ок Отправлено из приложения "Почта" для Windows От: EgorWedersОтправлено: 8 августа 2024 г. в 11:19Кому: ValdikSS/GoodbyeDPIКопия: andreybexus; AuthorТема: Re: [ValdikSS/GoodbyeDPI] New adress for russia_blacklist (Issue #511) В текстовом файле присутствуют url с протоколом (https://), это лишнее.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by andreybexus** [comment]
[Uploading russia-blacklist.txt…]()
Added glif.app
Добавлен glif.app

**Comment by EgorWeders** [comment]
> Uploading russia-blacklist.txt… Added glif.app Добавлен glif.app

Ты не успел дождаться пока файлик  txt загрузится . Отредачь коммент и подожди пока он в превью не появится для скачивания.
p.s Удалю этот коммент как починишь

**Comment by andreybexus** [comment]
> Contributor
Уже починил

**Comment by EgorWeders** [comment]
```
imaginepro.ai/create
krea.ai/apps/image/realtime
krea.ai/apps/image/enhancerdeviantart.com/studio?new=1
deviantart.com/notifications
deviantart.com/notifications/notes/
deviantart.com/notifications/notes/#1_0
glif.app
```

Достаточно добавить только  доменное имя. Остальное же через него грузишь

Например

```
imaginepro.ai
krea.ai
deviantart.com
glif.app
```

**Comment by andreybexus** [comment]
[russia-blacklist.txt](https://github.com/user-attachments/files/16539398/russia-blacklist.txt)
Простые домены
Simple domain.

**Comment by andreybexus** [comment]
> ```
> imaginepro.ai/create
> krea.ai/apps/image/realtime
> krea.ai/apps/image/enhancerdeviantart.com/studio?new=1
> deviantart.com/notifications
> deviantart.com/notifications/notes/
> deviantart.com/notifications/notes/#1_0
> glif.app
> ```
> 
> Достаточно добавить только доменное имя. Остальное же через него грузишь
> 
> Например
> 
> ```
> imaginepro.ai
> krea.ai
> deviantart.com
> glif.app
> ```
> 
> Могу ошибаться, проверь у себя.
На ютубе видео выход об отмене замедления, но все же на всякие случай GoodByeDpi установлен

**Comment by andreybexus** [comment]
Из недостатков, не все сайты работают, надеюсь в следующей версии исправят.

**Comment by andreybexus** [comment]
Забыл упомянуть отключите chrome://flags/Kyber, поставьте значение disabled

**Comment by EgorWeders** [comment]
Заработало только с доменными именами?

```
imaginepro.ai
krea.ai
deviantart.com
glif.app
```

**Comment by andreybexus** [comment]
> Заработало только с доменными именами?
> 
> ```
> imaginepro.ai
> krea.ai
> deviantart.com
> glif.app
> ```

У меня работает

**Comment by andreybexus** [comment]
[russia-blacklist.txt](https://github.com/user-attachments/files/16539499/russia-blacklist.txt)
Хоть ArtStation и не заблокировали, но я его все равно в список включил.

**Comment by EgorWeders** [comment]
На самом деле такие вещи пользователь сам добавляет для себя, так как тут вообще с сайта тянется список ресурсов, и у разных провайдеров разные есть фильтры.

**Comment by andreybexus** [comment]
> На самом деле такие вещи пользователь сам добавляет для себя, так как тут вообще с сайта тянется список ресурсов, и у разных провайдеров разные есть фильтры.

Щас список в самый верхний комментарий загружу, а то пока пролистают уснуть могут.

**Comment by EgorWeders** [comment]
Пометь как solved, чтобы люди видели как решенную ветку.

**Comment by EgorWeders** [comment]
Чтоб не переоткрывать issue на каждый домен ты можешь коммент внизу дописать и его редактировать
, просто пропиши в самом issue чтоб смотрели в комменты.

**Comment by andreybexus** [comment]
> Пометь как solved, чтобы люди видели как решенную ветку.

Надеюсь мой увидят, а то я сам кое-как свой нашел

**Comment by ValdikSS** [comment]
Список формируется автоматически, в него попадают почти все домены в выгрузке Роскомнадзора.
Список заблокированных на ТСПУ доменов ведётся отдельно: https://bitbucket.org/anticensority/russian-unlisted-blocks/src/master/readme.txt

**Comment by andreybexus** [comment]
Download from the comment above, the very first one
Скачивайте с комментария выше, cfvjuj gthdjuj
