### ISSUE TITLE
Remove Bitcoin miner from the DPI

### ISSUE THREAD

**Issue by kinkirill** [ValdikSS/GoodbyeDPI#513]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

![image](https://github.com/user-attachments/assets/ef8e2b4d-701c-48aa-a691-7518bb636618)
Why does this app even includes this?

**Comment by inikishev** [comment]
True and real

Close goodbyedpi, go to `goodbyedpi-0.2.3rc1\x86_64` and try to delete `WinDivert64.sys`, and this message appears. To be fair its probably just authors wallet for donations that he included in the dll name but it is sus that I am unable to delete the dll

**Comment by BuIlDaLiBlE** [comment]
WinDivert is a kernel mode driver, so it is loaded even after the program exits. You can use `service_remove.cmd` to stop the service. And I'm pretty sure the description is just asking for donations.

**Comment by kinkirill** [comment]
That solved the issue

**Comment by EgorWeders** [comment]
> That solved the issue

You can mark that issue as solved
