### ISSUE TITLE
Please add some action to SIMPLEWALL

### ISSUE THREAD

**Issue by iatndiag** [ValdikSS/GoodbyeDPI#514]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Please add an action after which Simplewall v.3.3.5 would ask whether to grant the application access to the network or not. That is, create one rule for the firewall. I do not want to completely disable filtering. It was Simplewall that blocked access. Now everything works when I disabled Simplewall. But I do not want to completely disable it.

Добавьте пожалуйста действие после которого Симплволл в.3.3.5 спрашивал бы предоставить приложению доступ в сеть или нет. Т.е. создать одно правило для брандмауэра. Я не хочу полностью отключать фильтрацию. Именно Симпвалл блокировал доступ. Сейчас всё работает, когда я отключил Симплволл. Но я не хочу его полностью отключать.

**Comment by EgorWeders** [comment]
This is a simplewall issue. Does simplewall provide CLI interfaces for the new rules in your version?
If it does you can do it yourself with extended cmd file.

**Comment by iatndiag** [comment]
Thank you. I opened Simplewall. Then I just added to the "My rules" tab: FTP, HTTP, ICMPv4, ICMPv6, IMAP/POP3,SMTP, QUIC, SSH, Telnet
and
Service GoodbyeDPI on the Services Tab
Now YouTube works Without Freeze

**Comment by iatndiag** [comment]
Спасибо. Я открыл Simplewall. Затем я просто добавил на вкладку "Мои правила": FTP, HTTP, ICMPv4, ICMPv6, IMAP/POP3,SMTP, QUIC, SSH, Telnet
и
Service GoodbyeDPI на вкладке Services
Теперь YouTube работает без зависаний

**Comment by EgorWeders** [comment]
Mark issue as solved pls
