### ISSUE TITLE
Здравствуйте, у меня почему goodbyedpi-0.2.2 перестал корректно работать, именно в том, что он не включается с виндусом "запускать программу от имени администрации" (автоматически). Он работал, но со вчерашнего дня он перестал работать пока я его не активирую и не убираю. Если я его закрываю, то он перестают работать. Могу я узнать, почему так происходит? (версию я обновил до goodbyedpi-0.2.3rc1)

### ISSUE THREAD

**Issue by dem0njlpegoxpahutel** [ValdikSS/GoodbyeDPI#517]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Перестал работать автоматически от имени администрации

### Additional information / Дополнительная информация

Здравствуйте, у меня почему goodbyedpi-0.2.2 перестал корректно работать, в том, что он не включается с виндусом "запускать эту программу от имени администрации". Он работал, но со вчерашнего дня он перестал работать пока я его не активирую и не убираю. Если я его закрываю, то он перестают работать. Могу я узнать, почему так происходит? (версию я обновил до goodbyedpi-0.2.3rc1, происходит тоже самое)

**Comment by EgorWeders** [comment]
Вы единственный пользователь на пк? Есть ли права администратора у вашего пользователя?

**Comment by dem0njlpegoxpahutel** [comment]
Да, я единственный пользователь этого пк, с правами администрации

**Comment by EgorWeders** [comment]
> ### Running as service / Запуск программы как сервис
> 
> I run it as a regular program / Запускаю программу обычным образом
> 

> ### Additional information / Дополнительная информация
> 
> Здравствуйте, у меня почему goodbyedpi-0.2.2 перестал корректно работать, в том, что он не включается с виндусом ...

Так вы его запускаете, или он у вас на автозапуске?

**Comment by dem0njlpegoxpahutel** [comment]
На автозапуске перестал работать.

**Comment by EgorWeders** [comment]
Как вы его поставили на автозапуск? Через поставляемый cmd?

**Comment by dem0njlpegoxpahutel** [comment]
![Скриншот 08-08-2024 142401](https://github.com/user-attachments/assets/ae6e7d1c-75ba-4b10-ae63-e223dffe11e6)

**Comment by EgorWeders** [comment]
Эээммм, вы думаете, что этот параметр ставит на автозапуск?

**Comment by mpustovoi** [comment]
В планировщике задач можно поставить на автозапуск файл `1_russia_blacklist.cmd`.
Однако, сегодня всё к сожалению перестало работать.

**Comment by dem0njlpegoxpahutel** [comment]
Да, без лишних вкладок, оно запускалось вместе с виндой. Уточню, программа работает. То есть, если я не включаю сам или закрою его, то перестаёт работать. Если это не так, извиняюсь, но для меня лично работала на автомате.

**Comment by EgorWeders** [comment]
How to install as Windows Service
Check examples in service_install_russia_blacklist.cmd, service_install_russia_blacklist_dnsredir.cmd and service_remove.cmd scripts.

Modify them according to your own needs.

**Comment by EgorWeders** [comment]
> Да, без лишних вкладок, оно запускалось вместе с виндой. Уточню, программа работает. Но сейчас если я не включаю сам или закрою его, то перестаёт работать. Если это не так, извиняюсь, но для меня лично работала на автомате.
> 

Этот параметр не влияет на запуск программы при заходе в виндовс.

**Comment by EgorWeders** [comment]
> В планировщике задач можно поставить на автозапуск файл `1_russia_blacklist.cmd`. Однако, сегодня всё к сожалению перестало работать.

Перестало запускаться? Или не грузит сайты?

**Comment by EgorWeders** [comment]
> В планировщике задач можно поставить на автозапуск файл `1_russia_blacklist.cmd`. Однако, сегодня всё к сожалению перестало работать.

Опишите проблему в отдельно issue

**Comment by dem0njlpegoxpahutel** [comment]
Спасибо что уточнили, теперь у меня работает и загружает видео! И спасибо mpustovoi, что написал и подсказал))

**Comment by mpustovoi** [comment]
> Перестало запускаться? Или не грузит сайты?

Работать программа не перестала. Перестал грузиться YouTube (только из-за него вообще и скачивал), хотя процесс `goodbyedpi.exe` есть.
Я отключал процесс через `service_remove.cmd` и включал программу через `1_russia_blacklist.cmd` вручную. Ничего не изменилось.

**Comment by EgorWeders** [comment]
> > Перестало запускаться? Или не грузит сайты?
> 
> Работать программа не перестала. Перестал грузиться YouTube (только из-за него вообще и скачивал), хотя процесс `goodbyedpi.exe` есть.
> Я отключал процесс через `service_remove.cmd` и включал программу через `1_russia_blacklist.cmd` вручную. Ничего не изменилось.
> Разумеется всё от администратора.

Создайте issue

**Comment by dem0njlpegoxpahutel** [comment]
Могу я вам подкинуть идею, добавить текстовый документ с расписанными cmd и что они делают. Чтобы простой человек мог прочитать, а не смотреть с ютуберов как в моём случаи? Вот пример: cпираченыная игра, есть текстовый документ где написаны чит-коды, как вызвать командную строку и как проходить сюжет, открывая сцены.

**Comment by EgorWeders** [comment]
> Могу я вам подкинуть идею, добавить текстовый документ с расписанными cmd и что они делают. Чтобы простой человек мог прочитать, а не смотреть с ютуберов как в моём случаи? Вот пример: cпираченыная игра, есть текстовый документ где написаны чит-коды, как вызвать командную строку и как проходить сюжет, открывая сцены.

Вы можете просто прочитать readme.md. Он открыт по умолчанию как на этот гит заходите.
