### ISSUE TITLE
Пропал ссд М2

### ISSUE THREAD

**Issue by st4xy** [ValdikSS/GoodbyeDPI#518]
### Operating system / операционная система

Windows 11 23H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Был открыт телеграм ( на ссд ), запустил софт. Телеграм вылетел. Чекаю Мой компьютер, а у меня пропал полностью М2 ССД. Проверил в diskmgmt.msc, а диск просто не видит

**Comment by st4xy** [comment]
Почему вопрос закрыт?

**Comment by EgorWeders** [comment]
Вероятно, что проблема на вашей стороне либо на стороне WinDivert.
