### ISSUE TITLE
Crashes when installed as a service.

### ISSUE THREAD

**Issue by petruchito** [ValdikSS/GoodbyeDPI#52]
Installed the app as a service using the batch file provided.
After reboot DPI bypass is no longer working and errors in the event log:
application error:
```
Faulting application name: goodbyedpi.exe, version: 0.0.0.0, time stamp: 0x5a3a79b7
Faulting module name: ntdll.dll, version: 6.1.7601.23915, time stamp: 0x59b94a16
Exception code: 0xc0000005
Fault offset: 0x00033b28
Faulting process id: 0x2ab8
Faulting application start time: 0x01d37f92169e87c5
Faulting application path: F:\utils\goodbyedpi-0.1.4\x86\goodbyedpi.exe
Faulting module path: C:\Windows\SysWOW64\ntdll.dll
Report Id: 54542320-eb85-11e7-8368-00e04ca14fe6
```
(unfortunately it seems I have reports saving disabled...)
SCM:
```
The WinDivert1.3 service failed to start due to the following error: 
The system cannot find the file specified.
```
SCM:
```
The GoodbyeDPI service terminated unexpectedly.  It has done this 3 time(s).
```

I suspect the problem is that `goodbyedpi.exe` fails to open the `windivert.dll` being run as a service.

**Comment by ValdikSS** [comment]
Hrm, it does load windivert.dll since it already tries to start `WinDivert1.3` service.
I have a strange feeling this may happen because of disk F:. Could you please remove the service, move the directory to C: and install it again?

**Comment by petruchito** [comment]
No luck moving it to `c:\goodbyedpi-0.1.4\` and even copying WinDivert to `%WINDIR%`, same error.

**Comment by ValdikSS** [comment]
Do you have some kind of software isolation or restriction? I'd like to have this problem documented. Please do more tests if possible.

**Comment by petruchito** [comment]
That's really strange but now I didn't find the dll and sys in the `%WINDIR%`... 
and the library is [loaded from the program directory](https://i.imgur.com/RopSWoB.png)
Last exception from goodbyedpi in windows log was on 28.12.17 - all this time it was working properly.

The only unusual setting that I have is windows in the "test mode" to run self-signed drivers.
Antivirus is free Avast.

note: my OS was installed in June 2009, and have encountered really bad bugs on SATA bus during migration to a new SSD, overall it seems to be working fine, but it's likely to have faults in the filesystem and system files.

**Comment by ValdikSS** [comment]
Please re-open this bug if this happens again. I can't reproduce it, and as I understand, it works for you now.
