### ISSUE TITLE
Программа перестала обходить замедление YouTube

### ISSUE THREAD

**Issue by mpustovoi** [ValdikSS/GoodbyeDPI#520]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Я настроил автозапуск файла `1_russia_blacklist.cmd` при включении компьютера с наивысшими правами через Планировщик задач. В течение недели программа работала штатно.

Сегодня YouTube **полностью** перестал загружать видео, хотя процесс `goodbyedpi.exe` в диспетчере задач по-прежнему есть.

Я несколько раз перезапускал программу вручную с помощью `service_remove.cmd` и `1_russia_blacklist.cmd` от имени администратора. Программа работает, а YouTube — нет.

### Additional information / Дополнительная информация

Провайдер — Ростелеком.
Версия GoodbyeDPI — 0.2.3rc1.

**Comment by EgorWeders** [comment]
1.Youtube пока сломали впринципе.
2. Попробуйте менять настройки в cmd, описание их найдете в readme

**Comment by JennyDoll** [comment]
У меня заработало в последние полчаса с -6 -e1 -q. Может, перестали тормозить, может, просто именно эта конфигурация хорошо подходит. Тревожно...

**Comment by EgorWeders** [comment]
Зачем у вас два файла блеклиста ?

**Comment by levva111** [comment]
У меня на мгтс заработало как в инструкции добавить -5 -e1 но не во всех браузерах

**Comment by EgorWeders** [comment]
Действительно,  забыл про это.

**Comment by EgorWeders** [comment]
Учтите , что некоторые настройки могут переставать работать, особенно когда ютуб у всех ложится.

**Comment by levva111** [comment]
Я добавил короче где файл, который устанавливает как службу -9 -e1 -f1 вместо -9 аргумент, и во всех браузерах заработало

**Comment by mpustovoi** [comment]
Пока что никакие другие аргументы не помогли. Запускал как установку службы.

**Comment by EgorWeders** [comment]
Попробуйте удалить службу, а потом, перебирая доступные параметры  в cmd и запуская как обычную программу, проверять какая комбинация у вас отработает.
