### ISSUE TITLE
Error opening filter: The system cannot find the path specified

### ISSUE THREAD

**Issue by Golden20-among1sas20** [ValdikSS/GoodbyeDPI#522]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Перестал работать сервис(автоматически запускаться и обходить замедление ютуба) решил обновить появилась ошибка
![image](https://github.com/user-attachments/assets/33091876-2b12-4222-8a4e-82d5f086001d)Установил старую версию(с которой и был) и тоже эта ошибка. Установил обновлёную версию от ютубера Хауди Хо и тоже эта ошибка.Что делать?

### Additional information / Дополнительная информация

Еще при удалении старой версии была ошибка файл WinDivert32.sys занят хотя процес GodByeDPI завершил помагла только перезагрузка ПК. Проблема в это или нет?

**Comment by EgorWeders** [comment]
Скиньте текст файла который вы запускаете

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/378#issuecomment-2267201431

**Comment by Ho0LiGaN82** [comment]
Так как автор решения не даёт, и видимо не пытался, я нашел решение проблемы.

И так, запускаем командную строку - CMD от имени администратора, и вводим поочерёдно команды: sc stop windivert -
sc delete windivert
Старый драйвер удалится от старой версии GoodbyeDPI и запустится без ошибок новая версия GoodbyeDPI 0.2.3rc1.

Всем удачи!

**Comment by EgorWeders** [comment]
> Так как автор решения не даёт, и видимо не пытался, я нашел решение проблемы.
> 
> И так, запускаем **командную строку - CMD от имени администратора**, и вводим поочерёдно команды: **sc stop windivert** - **sc delete windivert** Старый драйвер удалится от старой версии GoodbyeDPI и запустится без ошибок новая версия GoodbyeDPI 0.2.3rc1.
> 
> Всем удачи!

Когда вы ставите новую версию программы, предполагается, что вы замените ее предыдущую версию и поставляемые в той версии файлы.

**Comment by Ho0LiGaN82** [comment]
> > Так как автор решения не даёт, и видимо не пытался, я нашел решение проблемы.
> > И так, запускаем **командную строку - CMD от имени администратора**, и вводим поочерёдно команды: **sc stop windivert** - **sc delete windivert** Старый драйвер удалится от старой версии GoodbyeDPI и запустится без ошибок новая версия GoodbyeDPI 0.2.3rc1.
> > Всем удачи!
> 
> Когда вы ставите новую версию программы, предполагается, что вы замените ее предыдущую версию и поставляемые в той версии файлы.

Эта ошибка появляется у всех тех, кто не мог удалить старую версию GoodbyeDPI, из за запущенного процесса WinDivert который не давал удалить полностью программу старую версию программы. 
Данное решение помогает без проблем запустить последующие новые версии GoodbyeDPI.

**Comment by EgorWeders** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/378#issuecomment-2267201431

Буквально первый раздел.
