### ISSUE TITLE
 не работает discord   goodbyedp

### ISSUE THREAD

**Issue by genrihx2** [ValdikSS/GoodbyeDPI#523]
### Operating system / операционная система

Windows 11 Pro 24H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

 не работает discord   goodbyedp

### Additional information / Дополнительная информация

 не работает discord   goodbyedp
![image](https://github.com/user-attachments/assets/37886cc5-cee5-4726-a8b7-16d6ec2a17c0)

**Comment by EgorWeders** [comment]
Скиньте текст файла который вы запускаете и прочитайте на всякий readme.md на этом репозитории.

**Comment by genrihx2** [comment]
роскомнадзор блочить discord  

[README.md](https://github.com/user-attachments/files/16549590/README.md)

![image](https://github.com/user-attachments/assets/0f607b23-bbb7-4cc7-8f31-6acd28a96ae8)

**Comment by EgorWeders** [comment]
Зачем вы скинули этот файл? Вы считаете  вопрос решён?

**Comment by genrihx2** [comment]
нет   решён

**Comment by EgorWeders** [comment]
> нет   решён   

Вы прочитайте свой комментарий,  что я должен понять из него?
