### ISSUE TITLE
Discord не загружается

### ISSUE THREAD

**Issue by Koaxz** [ValdikSS/GoodbyeDPI#524]
### Operating system / операционная система

w 11

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Запускается ток веб версия в (браузере которая) а сама программа бесконечно ищет обновления

**Comment by EgorWeders** [comment]
Вы установили как сервис через cmd файл? Есть ли goodbyedpi.exe в процессах ?
