### ISSUE TITLE
Error opening filter: A device which does not exist was specified. (from russian)

### ISSUE THREAD

**Issue by SECRET-CONTENT** [ValdikSS/GoodbyeDPI#525]
### Operating system / операционная система

win10pro 22H2 19045.4651

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Error opening filter: A device which does not exist was specified.
![изображение](https://github.com/user-attachments/assets/464543b0-41b8-48d3-a2ce-63254a87e28a)

### Additional information / Дополнительная информация

Только скачал вроде сделал всё как по инструкций и чёт такое себе, при включений через x86_64 от админа инет дохнет, путь без кириллицы. Провайдер йота

**Comment by SECRET-CONTENT** [comment]
+ Программа сама по себе закрывается спустя менее минуты

**Comment by Grobovsky21** [comment]
программа не удаляется с компа. нельзя повторно разархивировать с заменой файлов - так как при закрытой программе - выдает окно о том что процесс занят другим приложением))))))

**Comment by EgorWeders** [comment]
> программа не удаляется с компа. нельзя повторно разархивировать с заменой файлов - так как при закрытой программе - выдает окно о том что процесс занят другим приложением)))))) 

Процесс занят другим приложением?

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/378#issuecomment-2267201431

**Comment by Ho0LiGaN82** [comment]
Так как автор решения не даёт, и видимо не пытался, я нашел решение проблемы.

И так, запускаем **командную строку - CMD от имени администратора**, и вводим поочерёдно команды: **sc stop windivert** -
**sc delete windivert**
Старый драйвер удалится от старой версии GoodbyeDPI и запустится без ошибок новая версия GoodbyeDPI 0.2.3rc1.

Всем удачи!

**Comment by EgorWeders** [comment]
> Так как автор решения не даёт, и видимо не пытался, я нашел решение проблемы.
> 
> И так, запускаем **командную строку - CMD от имени администратора**, и вводим поочерёдно команды: **sc stop windivert** - **sc delete windivert** Старый драйвер удалится от старой версии GoodbyeDPI и запустится без ошибок новая версия GoodbyeDPI 0.2.3rc1.
> 
> Всем удачи!

https://github.com/ValdikSS/GoodbyeDPI/issues/522#issuecomment-2277624117
