### ISSUE TITLE
После начала использования программы в игре Warframe установился строгий NAT.

### ISSUE THREAD

**Issue by ExaltedReaper** [ValdikSS/GoodbyeDPI#527]
### Operating system / операционная система

Windows 11 Pro 22000.526

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

После первого запуска программы в игре тип NAT сменился на "строгий". И теперь независимо от того запущена программа или нет он таким и остается. Это не позволяет играть совместно с другими людьми(Соло все еще можно).
Игра уже добавлена в настройки брандмауэра и все рекомендованные для нее порты тоже. Так что проблема не в отсутствии базовой настройки портов, рекомендации по настройке которых выдает она сама.

**Comment by ExaltedReaper** [comment]
Также теперь отсутствует стабильное соединение с людьми через программы по типу "RadminVPN". Они не могут присоединиться к игровым сессиям и постоянно теряют связь.

**Comment by Blueberryy** [comment]
Античиту не нравится скорее всего, читай самый низ #378

**Comment by TheByKotik** [comment]
> ### Operating system / операционная система
> Windows 11 Pro 22000.526
> 
> ### Running as service / Запуск программы как сервис
> I run it as a regular program / Запускаю программу обычным образом
> 
> ### Describe the bug / Опишите ошибку программы
> После первого запуска программы в игре тип NAT сменился на "строгий". И теперь независимо от того запущена программа или нет он таким и остается. Это не позволяет играть совместно с другими людьми(Соло все еще можно). Игра уже добавлена в настройки брандмауэра и все рекомендованные для нее порты тоже. Так что проблема не в отсутствии базовой настройки портов, рекомендации по настройке которых выдает она сама.
> 
> ### Additional information / Дополнительная информация
> _No response_

Хотелось бы уточнить, какие флаги используются? Используется blacklist или все соединения?

**Comment by ExaltedReaper** [comment]
> > ### Операционная система / операционная система
> > Windows 11 Профессиональная 22000.526
> > ### Запуск как услуга / Запуск программы как сервис
> > Запускаю как обычную программу / Запускаю программу обычным способом
> > ### Опишите ошибку / Опишите ошибку программы.
> > После первого запуска программы в игре тип NAT сменился на "строгий". И теперь независимо от того, запущена ли программа или нет, такого и остается. Это не позволяет играть совместно с другими людьми(В одиночку все еще можно). Игра уже добавлена ​​в настройки брандмауэра и все предпочтительные для нее порты тоже. Так что проблема не в отсутствии настройки портов, рекомендации по настройке которых выдает она сама.
> > ### Дополнительная информация / Дополнительная информация
> > _Нет ответа_
> 
> Хотелось бы уточнить, какие флаги использовались? Используется черный список или все соединения? Если ничего из этого не устанавливалось вручную, то какая именно версия [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI) используется? Возможное решение: указать черный список (список сайтов, только на который будет внесен пакет модификаций)

На вопрос про флаги я вам ответить не смогу, поскольку даже не понимаю о чем речь.
Программу использую как рядовой пользователь по типу: "скачал, распаковал, запустил", без предварительных настроек и копошений в файлах конфигураций.
Запуск произвожу через файл "goodbyedpi.exe" по пути "goodbyedpi-0.2.3rc1\x86_64".
Версия актуальная на данный момент.

**Comment by ExaltedReaper** [comment]
> Античиту не нравится скорее всего, читай самый низ #378

Если бы так и было, то на локальные игры, как в моем первом же комментарии после публикациии записи, влияния бы это не оказало.
Поскольку через Radmin мы с друзьями не играем в игры в которых есть античит. Последний пример Baldurs Gate 3: друг видит мою сессию, но соединение не стабильно и при попытке присоединения сразу обрывается не успев загрузиться в лобби. То же самое и при попытке подключиться к нему.

**Comment by ValdikSS** [comment]
Вопрос разобран в FAQ. Очевидно, вы его не читали.
