### ISSUE TITLE
Error opening filter: Incorrect function.

### ISSUE THREAD

**Issue by C3mka21** [ValdikSS/GoodbyeDPI#528]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Всё хорошо работало, но теперь при запуске выдает это
![image](https://github.com/user-attachments/assets/131f6cfb-1ba4-4d0f-bbc5-7766c0a419c3)
 после чего программа закрывается и всё.

**Comment by EgorWeders** [comment]
Скиньте текст cmd файла который вы запускаете или просто параметры командной строки для запуска

**Comment by Ho0LiGaN82** [comment]
Так как автор решения не даёт, и видимо не пытался, я нашел решение проблемы.

И так, **запускаем командную строку - CMD от имени администратора**, и вводим поочерёдно команды: **sc stop windivert** -
**sc delete windivert**
Старый драйвер удалится от старой версии GoodbyeDPI и запустится без ошибок новая версия GoodbyeDPI 0.2.3rc1.

Всем удачи!

**Comment by EgorWeders** [comment]
> Так как автор решения не даёт, и видимо не пытался, я нашел решение проблемы.
> 
> И так, **запускаем командную строку - CMD от имени администратора**, и вводим поочерёдно команды: **sc stop windivert** - **sc delete windivert** Старый драйвер удалится от старой версии GoodbyeDPI и запустится без ошибок новая версия GoodbyeDPI 0.2.3rc1.
> 
> Всем удачи!

https://github.com/ValdikSS/GoodbyeDPI/issues/522#issuecomment-2277624117

Цитируйте себя, а не копируйте комментарий.

**Comment by Ho0LiGaN82** [comment]
> > Так как автор решения не даёт, и видимо не пытался, я нашел решение проблемы.
> > И так, **запускаем командную строку - CMD от имени администратора**, и вводим поочерёдно команды: **sc stop windivert** - **sc delete windivert** Старый драйвер удалится от старой версии GoodbyeDPI и запустится без ошибок новая версия GoodbyeDPI 0.2.3rc1.
> > Всем удачи!
> 
> [#522 (comment)](https://github.com/ValdikSS/GoodbyeDPI/issues/522#issuecomment-2277624117)
> 
> Цитируйте себя, а не копируйте комментарий.

Извиняюсь, не знаком с github, только изучаю его интерфейс.

**Comment by C3mka21** [comment]
> **sc stop windivert** - **sc delete windivert**
Помогло, спасибо!
