### ISSUE TITLE
Can't open any websites (DNS redirection with Malwarebytes)

### ISSUE THREAD

**Issue by TeroBlaZe** [ValdikSS/GoodbyeDPI#53]
The Issue has become right after installing Malwarebyes anti-virus.
Any scripts with dnsredir cause to this issue. Can do ping but can't get domain name.

Workaround: Got new DNS IP and PORT form https://servers.opennic.org/ to replace 77.88.8.8
Solution: ???

**Comment by ValdikSS** [comment]
So you installed anti-virus and could no longer use dnsredir? Does this anti-virus have firewall function? Please check if it blocks port 1253 or IP address 77.88.8.8. Or better install Wireshark, run it with "port 1253" filter and see what's going on.

**Comment by TeroBlaZe** [comment]
@ValdikSS no. I can no longer use dnsredir with 77.88.8.8, but --dns-addr 185.121.177.177 --dns-port 1053 is ok for some reason. Yes there is firewall but I don't believe it blocks some ports by default

**Comment by ValdikSS** [comment]
Can you make traffic dump with Wireshark to port 1253?

**Comment by TeroBlaZe** [comment]
@ValdikSS I've made a [traffic dump](https://drive.google.com/file/d/1UvyKy0bssot0wnMklDsBC9BfT3wKNqam/view) for you

Another strange thing I've noticed even with no Malwarebytes installed that execution of 'apk update' fails due to DNS Lookup error in Docker Alpine container with port 1053 and 185.121.177.177 but in host system it works.
I've find out that in Docker the issue was with the port 1053 but port 53 or default "3_all_dnsredir_hardcore" works fine, so I don't see a much problem but [here's a dump](https://drive.google.com/file/d/1EEJC50ZrLV6XzmuxQO25k_-CgRojicxQ/view?usp=sharing).

**Comment by ValdikSS** [comment]
Please add `--dns-verb` to the command line and run it again.

**Comment by ValdikSS** [comment]
I can confirm the issue with Malwarebytes. Will investigate.

**Comment by ValdikSS** [comment]
Sorry, I don't know why this happens. Malwarebytes intercepts DNS queries and re-injects DNS replies, but the application which performed DNS query can't receive them. Current GoodbyeDPI version drops incoming DNS retransmissions, but changing it to handle retransmissions and pass them to the application doesn't fix the issue.
What confuses me the most is that Malwarebytes handles DNS queries on port 1253, but not on 1053 (these are very unusual ports for DNS).

I don't know how can I workaround this issue in GoodbyeDPI. I tried to increase filter priority and to exclude local addresses, and it still doesn't work with Malwarebytes.

I'll write to Malwarebytes tech support and we'll see how it goes.

**Comment by ValdikSS** [comment]
Malwarebytes asked me for a debug log several days ago. I've sent it.

**Comment by ValdikSS** [comment]
No updates yet. Asked for status once more.

**Comment by ValdikSS** [comment]
Asked for status.

**Comment by ValdikSS** [comment]
Please try GoodbyeDPI v0.1.5rc3
https://github.com/ValdikSS/GoodbyeDPI/releases/tag/0.1.5rc3

Should be fixed in this version. Please reopen this ticket if issue is still present in this version.
