### ISSUE TITLE
MinGW GCC 14.2.0 build bad exe file for x86

### ISSUE THREAD

**Issue by mxlgv** [ValdikSS/GoodbyeDPI#530]
### Operating system / операционная система

Windows 10 Pro 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

The linker generates a bad executable file with `i686-w64-migw32-gcc` __v14.2.0__, with the warning:
```log
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.2.0/../../../../i686-w64-mingw32/bin/ld.exe: goodbyedpi.exe:.text: section below image base
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.2.0/../../../../i686-w64-mingw32/bin/ld.exe: goodbyedpi.exe:.data: section below image base
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.2.0/../../../../i686-w64-mingw32/bin/ld.exe: goodbyedpi.exe:.rdata: section below image base
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.2.0/../../../../i686-w64-mingw32/bin/ld.exe: goodbyedpi.exe:.eh_fram: section below image base
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.2.0/../../../../i686-w64-mingw32/bin/ld.exe: goodbyedpi.exe:.bss: section below image base
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.2.0/../../../../i686-w64-mingw32/bin/ld.exe: goodbyedpi.exe:.edata: section below image base
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.2.0/../../../../i686-w64-mingw32/bin/ld.exe: goodbyedpi.exe:.idata: section below image base
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.2.0/../../../../i686-w64-mingw32/bin/ld.exe: goodbyedpi.exe:.CRT: section below image base
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.2.0/../../../../i686-w64-mingw32/bin/ld.exe: goodbyedpi.exe:.tls: section below image base
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.2.0/../../../../i686-w64-mingw32/bin/ld.exe: goodbyedpi.exe:.rsrc: section below image base
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/14.2.0/../../../../i686-w64-mingw32/bin/ld.exe: goodbyedpi.exe:.reloc: section below image base
```
The build was carried out from the __MINGW32 (MSYS2)__ environment.
The file does not run: Windows 10 reports that "The application cannot be run on your PC."

### Additional information / Дополнительная информация

The linker has two incompatible options `--dynamicbase` and `--image-base` (see https://learn.microsoft.com/en-us/cpp/build/reference/base-base-address?view=msvc-170) which Probably on the older version (which is now in CI) `mingw-w64` somehow worked.

In addition, if you use `--image-base`, then for __x86__ it should be `0x400000`, and for __x64__ `0x140000000`.

**Comment by ValdikSS** [comment]
Please paste PE headers of the builds here if you have them on hand.

**Comment by EgorWeders** [comment]
[Removed --image-base ](https://github.com/ValdikSS/GoodbyeDPI/compare/master...EgorWeders:GoodbyeDPI:master)
It builds working artifacts, both x32 and x64 .
Tested on win 10 x64.

**Comment by mxlgv** [comment]
@ValdikSS 
```
goodbyedpi.exe:     file format pei-i386
goodbyedpi.exe
architecture: i386, flags 0x00000103:
HAS_RELOC, EXEC_P, D_PAGED
start address 0x000013f0

Characteristics 0x30e
	executable
	line numbers stripped
	symbols stripped
	32 bit words
	debugging information removed

Time/Date		Fri Aug 09 13:03:01 2024
Magic			010b	(PE32)
MajorLinkerVersion	2
MinorLinkerVersion	42
SizeOfCode		0000e800
SizeOfInitializedData	0001a600
SizeOfUninitializedData	00000c00
AddressOfEntryPoint	000013f1
BaseOfCode		00001000
BaseOfData		00010001
ImageBase		ffffffff
SectionAlignment	00001000
FileAlignment		00000200
MajorOSystemVersion	4
MinorOSystemVersion	0
MajorImageVersion	1
MinorImageVersion	0
MajorSubsystemVersion	4
MinorSubsystemVersion	0
Win32Version		00000000
SizeOfImage		00023001
SizeOfHeaders		00000400
CheckSum		00020782
Subsystem		00000003	(Windows CUI)
DllCharacteristics	00000140
					DYNAMIC_BASE
					NX_COMPAT
SizeOfStackReserve	00200000
SizeOfStackCommit	00001000
SizeOfHeapReserve	00100000
SizeOfHeapCommit	00001000
LoaderFlags		00000000
NumberOfRvaAndSizes	00000010
```

This is how I understand the problem `ImageBase: ffffffff`.

Full log:
[goodbyedpi-objdump.log](https://github.com/user-attachments/files/16559802/goodbyedpi-objdump.log)

**Comment by mxlgv** [comment]
> [Removed --image-base ](https://github.com/ValdikSS/GoodbyeDPI/compare/master...EgorWeders:GoodbyeDPI:master) It builds working artifacts, both x32 and x64 . Tested on win 10 x64.

Sorry, but don't you think that commit messages like "Update makefile" are harmful and do not reflect the essence.

**Comment by EgorWeders** [comment]
I make it fast in browser for testing and for you, my fault but i cant find how to edit and remove commits on web github))

**Comment by EgorWeders** [comment]
Если будешь собирать, то отпиши как что. плз

**Comment by mxlgv** [comment]
> [Removed --image-base ](https://github.com/ValdikSS/GoodbyeDPI/compare/master...EgorWeders:GoodbyeDPI:master) It builds working artifacts, both x32 and x64 . Tested on win 10 x64.

Yes it works, I made these changes locally. According to Microsoft documentation: "For security reasons, Microsoft recommends you use the /DYNAMICBASE option instead of specifying base addresses for your executables." So it seems unnecessary to specify the base address initially.

**Comment by EgorWeders** [comment]
https://github.com/ValdikSS/GoodbyeDPI/pull/533#issue-2457633133
