### ISSUE TITLE
как обойти блокировку на линукс

### ISSUE THREAD

**Issue by peacedoorballl** [ValdikSS/GoodbyeDPI#532]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

как обойти блокировку на линукс?

**Comment by mxlgv** [comment]
@peacedoorballl I don’t know how appropriate it is to answer here, but there is a similar utility for Linux: https://github.com/xvzc/SpoofDPI (but with such a question I think you will get banned, I hope I’m not with you).

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI?tab=readme-ov-file#similar-projects

**Comment by 1vanK** [comment]
@ValdikSS а ваше личное предпочтение какое?

**Comment by peacedoorballl** [comment]
https://github.com/xvzc/SpoofDPI

Настроил прокси в приложении freetube. Можно смотреть Ютуб как и раньше без рекламы.

Также можно поставить расширение uboost юбуст к гугл хром. Мороки меньше, но смотреть рекламу и вроде как подтормаживает ( но это может у меня такой тормозной комп)

**Comment by ValdikSS** [comment]
> @ValdikSS а ваше личное предпочтение какое?

Я использую nfqws из состава zapret на роутере.
