### ISSUE TITLE
Забанить... Некоторых

### ISSUE THREAD

**Issue by den4ik-webdev** [ValdikSS/GoodbyeDPI#534]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [x] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

2024-08-10 01-02 - Бесконечная загрузка видео, хотя вчера с gdpi  все летало

**Comment by ValdikSS** [comment]
Отличное предложение! Спасибо-пожалуйста!
