### ISSUE TITLE
Обработка длинных запросов с параметрами

### ISSUE THREAD

**Issue by GitUserNameCheck** [ValdikSS/GoodbyeDPI#537]
### Operating system / операционная система

Windows 11 23H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Не обрабатываются длинные запросы с параметрами на youtube. Выдает 403 ошибку на них. Запросы вида https://rr5---sn-ntq7yney.googlevideo.com/videoplayback? и дальше 500+ символов с параметрами.

**Comment by ValdikSS** [comment]
>Выдает 403 ошибку на них. 

Вам это выдаёт сам сервер, программа не имеет к этому отношения.
См. ветку https://habr.com/ru/news/833016/comments/#comment_27113306
Будет здорово, если продиагностируете и задокументируете причину.
