### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by inkmv** [ValdikSS/GoodbyeDPI#54]
Не работает ни одна версия, запускал с разными параметрами, всегда одно и тоже, заблокированные сайты не открываются, хотя до недавнего времени все работало. прикладываю вывод блокчекера:
<a target="_blank" href="http://fastpic.ru"><img src="http://i100.fastpic.ru/big/2017/1229/62/387e4eb364fb088a4d51d1aecd193d62.jpg" border="0"></a>
<a target="_blank" href="http://fastpic.ru"><img src="http://i100.fastpic.ru/big/2017/1229/79/b47cd34c6deebf26f9119246856f9f79.jpg" border="0"></a>

**Comment by ValdikSS** [comment]
Видимо, ваш провайдер изменил настройки DPI.

**Comment by intergleam** [comment]
BlockCheck v0.0.9.6
Для получения корректных результатов используйте DNS-сервер провайдера и отключите средства обхода блокировок.

Проверка работоспособности IPv6: IPv6 недоступен.
IP: 37.190.72.xxx, провайдер: OJS Moscow city telephone network/ МГТС ОАО

[O] Тестируем IPv4 DNS
	Через системный DNS:	 ['104.20.134.45', '104.20.135.45', '104.24.10.70', '104.24.11.70', '184.173.136.161', '195.8.215.136', '195.82.146.214', '5.178.68.100']
	Через Google DNS:	 ['104.20.134.45', '104.20.135.45', '104.24.10.70', '104.24.11.70', '184.173.136.161', '195.8.215.136', '195.82.146.214', '5.178.68.100']
	Через Google API:	 ['104.20.134.45', '104.20.135.45', '104.24.10.70', '104.24.11.70', '184.173.136.161', '195.8.215.136', '195.82.146.214', '5.178.68.100']
	Несуществующий DNS не вернул адресов (это не ошибка)
[✓] DNS-записи не подменяются
[✓] DNS не перенаправляется

[O] Тестируем HTTP
	Открываем  http://furry.booru.org/index.php?page=post&s=view&id=111173
[✓] Сайт открывается
	Открываем  http://a.putinhuylo.com/
[✓] Сайт открывается
	Открываем  http://furry.booru.org/
[✓] Сайт открывается
	Открываем  http://pbooru.com/
[✓] Сайт открывается
	Открываем  http://pbooru.com/index.php?page=post&s=view&id=303026
[✓] Сайт открывается
	Открываем  http://rutracker.org/forum/index.php
[✓] Сайт открывается

[O] Тестируем HTTPS
	Открываем  https://lolibooru.moe/
[☠] Сайт не открывается
	Открываем  https://e621.net/
[☠] Сайт не открывается
	Открываем  https://www.dailymotion.com/
[☠] Сайт не открывается
	Открываем  https://rutracker.org/forum/index.php
[☠] Сайт не открывается

[!] Результат:
[⚠] Ваш провайдер полностью блокирует доступ к HTTPS-сайтам из реестра.

**Comment by ValdikSS** [comment]
@inkmv, @intergleam, выполните следующую команду и пришлите ее полный вывод:
`tracert rutracker.org`

**Comment by ValdikSS** [comment]
Нет ответа, закрываю баг.

**Comment by sergeevabc** [comment]
@ValdikSS, см. [лог][1] трасировки.
@inkmv, @intergleam, используйте зеркало на другом домене.

[1]: https://privatebin.net/?c1ab076e9244d11a#gZIqWULuXKxcvISYSnfBSelb6LuY9Pukx0Zo4BF1w/w=

**Comment by ValdikSS** [comment]
@sergeevabc, ваш провайдер, вероятно, блокирует сайт по IP-адресу.

**Comment by WallBurn** [comment]
Поменял пройвайдера с Onlime (Ростелеком), перешел на МГТС, тут начались чудеса.
GoodbyeDpi - лочит ВК, Steam, ответы мейл и т.д., причем количество сайтов хаотичное, одно заметил точно Steam - не работает, как только отключаю goodbyedpi, все работает.
Что порекомендуете, чтобы в дальнейшем избежать данную проблему и продолжить пользоваться Вашей замечательной программой?
Данный баг, замечен на разных машинах.

**Comment by ValdikSS** [comment]
Вероятнее всего, блокирует провайдер, а не программа.
Следуйте инструкции: https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark
