### ISSUE TITLE
Error opening filter: There are no more endpoints available from the endppoint mapper

### ISSUE THREAD

**Issue by maksvolk022** [ValdikSS/GoodbyeDPI#540]
### Operating system / операционная система

win 10 22h2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

![изображение](https://github.com/user-attachments/assets/19d980d0-9c26-4b91-a27b-0d1d959d3d4a)

**Comment by EgorWeders** [comment]
Вы запустили .cmd файл без изменений?

**Comment by maksvolk022** [comment]
> Did you run the .cmd file without any changes?

yes

**Comment by ValdikSS** [comment]
#212
>This error occurs when the **Base Filtering Engine** service has been disabled.
