### ISSUE TITLE
Программа некорректно обрабатывает пакеты на Windows 11 Pro 23H2

### ISSUE THREAD

**Issue by cupespresso22** [ValdikSS/GoodbyeDPI#541]
### Operating system / операционная система

Windows 11 Pro для рабочих станций 23H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Программа некорректно обрабатывает пакеты на Windows 11 Pro 23H2, либо же ей что-то мешает это делать.
В одной подсети и из под одного динамического IP, в интернет имеют доступ на разных ПК две ОС — Windows 8 и Windows 11. На Windows 8 использую следующий конфиг установки сервиса:
![изображение](https://github.com/user-attachments/assets/9fa1cc36-28b7-4c1e-bb86-8f5821f5c63a)
При использовании этого конфига и ОС Windows 8, без проблем осуществляется вход на такие сайты, как rutracker.net, ntc.party и т.д. Версия программы goodbyedpi-0.2.3rc1. По умолчанию, без использования goodbyedpi, доступ на эти сайты заблокирован.
При использовании этой же версии программы и идентичного конфига на Windows 11, в Firefox с отключенным network.http.http3.enable, вышеуказанные сайты не загружаются и выдают ошибку PR_CONNECT_RESET_ERROR. Со включённым network.http.http3.enable, ситуация аналогичная, но rutracker всё же очень долго загружается и с поломанной разметкой сайта.
Windows 11 скачана с офф. сайта Microsoft. Твикеры и оптимизаторы не применялись. Пробовал временно отключать Defender, добавлять программу в список разрешённых для брандмауэра — не помогло. Изоляция ядра отключена.

**Comment by k0zyrev** [comment]
Без дампа трафика вряд ли автор сможет вам помочь. Устанавливайте Wireshark, включайте запись дампа, открывайте браузер и пытайтесь зайти на заблокированный сайт.

**Comment by cupespresso22** [comment]
[nnm_rutr_ntc.zip](https://github.com/user-attachments/files/16575504/nnm_rutr_ntc.zip)
Записал попытки входа на nnmclub, rutracker и ntc.party.

**Comment by alexandrage** [comment]
У меня нормально работает с флагами -6 -q

**Comment by ValdikSS** [comment]
В дампе нет следов работы программы.
Запустите просто .exe-файл. Что-то поменялось?

**Comment by cupespresso22** [comment]
Запустил под правами администратора. Рутрекер в первый раз крайне медленно загружался и отобразился с поломанной вёрсткой сайта. nnmclub и ntc.party не загрузились.
[test2.zip](https://github.com/user-attachments/files/16594571/test2.zip)

Также в другом тесте отдельно запустил консоль из под админа и через неё — установку сервиса. Выдало ошибку 1060.

![изображение](https://github.com/user-attachments/assets/1b996c0b-316b-4c4d-8ac2-bcba73719899)

**Comment by ValdikSS** [comment]
> Также в другом тесте отдельно запустил консоль из под админа и через неё — установку сервиса. Выдало ошибку 1060.

Так и должно быть, это не проблема.

1. Удалите сервис (`service_remove.cmd` от администратора)
2. Скачайте https://reqrypt.org/download/WinDivert-2.2.2-A.zip
3. Распакуйте архив
4. Запустите `cmd` от администратора, перейдите в распакованную папку с помощью `cd`, запустите `netdump.exe true > output.txt`
5. Откройте браузер, попробуйте зайти на какой-либо сайт.
6. Нажмите ctrl+c в окне консоли
7. Сожмите output.txt и пришлите сюда

**Comment by cupespresso22** [comment]
russia-blacklist с записями, оба сайта там имеются.
К сожалению, без изменений.
Конечно оффтоп, но у меня и Anydesk отказывается работать — нет соединения с сервером их организации. Что-то с ОС...

**Comment by craftersmine** [comment]
Заметил такое же поведение, что службой, что просто в окне запускать, программа не обрабатывает трафик, как будто он идет в обход WinDivert. Patreon не открывается с GDPI выбрасывает ERR_CONNECTION_RESET.

Windows 11 Pro x64 23H2 Release Channel

**Comment by ValdikSS** [comment]
@cupespresso22 установлен ли у вас Killer Control Center? Если да, попробуйте отключить Advanced Stream Detect.

**Comment by cupespresso22** [comment]
Да, установлен. И да, именно настройки из этой программы создавали помехи. Отключил две опции как на скриншоте и теперь могу заходить на сайты. Killer Control Center изначально стоял, когда ОС ставил.
Спасибо большое за наводку!
![изображение](https://github.com/user-attachments/assets/e4644e85-ed98-4c5e-b48a-bd9f7d4ce620)

**Comment by v0id24** [comment]
Для истории, эти настройки могуть быть включены и Intel Connectivity Performance Suite, и ставиться в комплекте. Обнаружил так же - искал, почему на пк работает, а на ноуте - нет.
![Image](https://github.com/user-attachments/assets/0ee83f8d-30f4-480c-a21b-3eafa5d15377)

**Comment by v0id24** [comment]
Для истории, эти настройки могут быть включены и в Intel Connectivity Performance Suite, и ставиться в комплекте с драйверами Intel.
Обнаружил так же - искал, почему на пк работает, а на ноуте - нет.
![Image](https://github.com/user-attachments/assets/12fc43c2-872d-46b7-a211-4c77cfa2c1b7)

**Comment by pypapipy** [comment]
Помогите, помогло выключить приоритизацию intel connectivity, затем вновь возникла проблема с подключением, было решено полностью удалить приложение, однако, теперь когда я запускаю проверку, выдает что приложение мешает корректной работе, хотя я его удалил... Как это фиксить? 

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/08aad9c5-1a2f-4484-962a-85b03f493551" />

**Comment by R0me0Star** [comment]
> Помогите, помогло выключить приоритизацию intel connectivity, затем вновь возникла проблема с подключением, было решено полностью удалить приложение, однако, теперь когда я запускаю проверку, выдает что приложение мешает корректной работе, хотя я его удалил... Как это фиксить?

Win + R, вводишь services.msc и находишь там службу Intel Connectivity Network Service. Останавливаешь её и в свойствах отключаешь автозапуск, перезапускаешь пк. Если хочешь с корнями удалить, то в тех же свойствах прописан путь до исполняемого файла.
