### ISSUE TITLE
Домен (p.thenewone.lol) обновления списка для РФ недоступен

### ISSUE THREAD

**Issue by Arksault** [ValdikSS/GoodbyeDPI#542]
### Operating system / операционная система

Windows 7 7601

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

при запуске 0_russia_update_blacklist_file.cmd выдаёт ошибку об истёкшем времени на подкюлчение.
![выфа](https://github.com/user-attachments/assets/cd39de66-62f0-40aa-946c-b8418246965a)

хорошо бы сделать запасной домен)

### Additional information / Дополнительная информация

РКН вроде как не банили домен, в базах его нет.

**Comment by proninyaroslav** [comment]
@ValdikSS 
Ни через vpn/tor не качает. С разных сетей пробовал. Может с сайтом что-то не так?
https://p.thenewone.lol/domains-export.txt

**Comment by fluffydaddy** [comment]
Да, у меня сегодня та же самая проблема появилась недавно. Список не обновляется, а сам GoodbyeDPI вовсе перестал работать (в плане ютуба). Пробовал параметры от -1 до -9 и ничего подобного. Запускаю как службу. Такой путь программы с аргументами: "D:\Software\goodbyedpi\x86_64\goodbyedpi.exe" -7 -e1 --blacklist "D:\Software\goodbyedpi\russia-blacklist.txt" --blacklist "D:\Software\goodbyedpi\russia-youtube.txt"
