### ISSUE TITLE
GoodbyeDPI не работает / doesn't work

### ISSUE THREAD

**Issue by PavelSBakhtin** [ValdikSS/GoodbyeDPI#543]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Ситуация следующая:
скачал 0.2.3rc1, на компе с Windows 7 (браузер: хром) работает только через - 2_any_country, но работает отлично;
на ноуте с Windows 10 (браузеры: хром, эдж) ни версия 0.2.3rc1, ни 0.2.2 не работают от слова совсем, кроме того - после активации программы вообще ни на какой сайт зайти не возможно, не загружаются страницы и в браузере сообщение - нет подключения к интернету, хотя в три доступ в интернет есть.

The situation is as follows:
downloaded 0.2.3rc1, on a computer with Windows 7 (browser: chrome) it only works through - 2_any_country, but it works fine;
on a laptop with Windows 10 (browsers: chrome, edge) versions 0.2.3rc1 and 0.2.2 doesn't work, after activating the program it is not possible to go to any site at all, pages do not load and a message appears in the browser - no Internet connection, although three have Internet access.

**Comment by Strater1** [comment]
+

**Comment by EgorWeders** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/330
Проверьте это решение.

**Comment by ValdikSS** [comment]
Запишите дамп трафика, можно без фильтров по IP-адресам.
https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by PavelSBakhtin** [comment]
Забыл указать, что на Windows 10 отключал Kyber. А на Windows 7 такого параметра нет, и без него работает.
Про дамп трафика - попробую позже, надеюсь это не сложно.

**Comment by SUGHuser** [comment]
> Забыл указать, что на Windows 10 отключал Kyber. А на Windows 7 такого параметра нет, и без него работает. Про дамп трафика - попробую позже, надеюсь это не сложно.

Я надеюсь речь не идёт о таком подключении когда прямо на компьютере ставится PPPoE или PPTP ?

**Comment by danyanya111** [comment]
Всем привет, уважаемые! Может кто сможет помочь: к сожалению goodbyeDPI не появляется в службах windows, хоть при запуске командной строки пишет, что все работает
т.к. не добавляется службы - никаких изменений нет, не знаю что делать((

**Comment by iturnes** [comment]
@ValdikSS не запускается с флагом --frag-by-sni

**Comment by EgorWeders** [comment]
> @ValdikSS не запускается с флагом --frag-by-sni, -9 а так же -q

> Всем привет, уважаемые! Может кто сможет помочь: к сожалению goodbyeDPI не появляется в службах windows, хоть при запуске командной строки пишет, что все работает т.к. не добавляется службы - никаких изменений нет, не знаю что делать((

Создайте отдельные issue.

**Comment by SUGHuser** [comment]
> Всем привет, уважаемые! Может кто сможет помочь: к сожалению goodbyeDPI не появляется в службах windows, хоть при запуске командной строки пишет, что все работает т.к. не добавляется службы - никаких изменений нет, не знаю что делать((

Какая версия Windows ?

**Comment by YuriDavydov** [comment]
Windows 10. Запускаю программу обычным образом.
Ситуация следующая:
скачал 0.2.3rc1, на компе с Windows 10 (браузер: хром) не работает, ни с any county, ни с Russia. Загружается главная youtube с надписью - "Нет подключения к интернету". Kyber отключен.

**Comment by zefirnaya** [comment]
Аналогично. Windows 11, стандартный запуск для России не работает. Нет подключения к интернету. Пробовала с Edge и Chrome.

**Comment by alod2019** [comment]
Есть роутер Keenetic Runner 4G с симкой от Мегафона - с ним проблемы нет, на ноутах с Windows 10 и 11 все нормально работет.
А вот на тех же ноутах  подключенных к GPON роутеру МГТС никак. 
Kyber в Хроме отключен.

**Comment by justwolk** [comment]
Попробуйте параметры kyber и quic поставить на "Default", у меня всё заработало магическим образом

**Comment by neranil** [comment]
> Есть роутер Keenetic Runner 4G с симкой от Мегафона - с ним проблемы нет, на ноутах с Windows 10 и 11 все нормально работет. А вот на тех же ноутах подключенных к GPON роутеру МГТС никак (по крайней мере с параметрами по умолчанию). Kyber в Хроме отключен.

Да, у самого роутер от мгтс и ни отключение флага Kyber, ни goodbyeDPI и даже впн некоторые не помогают.

**Comment by ValdikSS** [comment]
Нет ответа от автора.

**Comment by Alexandr180** [comment]
У меня заработало под "другие страны" провайдер проводной домашний билайн. Спасибо решение! Может кто подскажет решение для android TV?
