### ISSUE TITLE
Не устанавливается служба. |  The service is not being installed.

### ISSUE THREAD

**Issue by softcoder2020** [ValdikSS/GoodbyeDPI#544]
### Operating system / операционная система

Win 10 LTSC x64

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

![2024-08-11_220402](https://github.com/user-attachments/assets/65aebc76-dbaa-4f13-9b69-897663ef1b3a)

### Additional information / Дополнительная информация

goodbyedpi-0.2.3rc1>service_install_russia_blacklist_dnsredir.cmd
This script should be run with administrator privileges.
Right click - run as administrator.
Press any key if you're running it as administrator.
Для продолжения нажмите любую клавишу . . .
[SC] OpenService: ошибка: 1060:
Указанная служба не установлена.
[SC] OpenService: ошибка: 1060:
Указанная служба не установлена.
[SC] CreateService: успех
[SC] ChangeServiceConfig2: успех
Имя_службы: GoodbyeDPI
        Тип                : 10  WIN32_OWN_PROCESS
        Состояние          : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        Код_выхода_Win32   : 0  (0x0)
        Код_выхода_службы  : 0  (0x0)
        Контрольная_точка  : 0x0
        Ожидание           : 0x0
        ID_процесса        : 13688
        Флаги              :

**Comment by EgorWeders** [comment]
Вы проверьте список служб после запуска cmd.

**Comment by ValdikSS** [comment]
Вывод такой и должен быть, это не ошибка.
Что именно не работает?

**Comment by craftersmine** [comment]
Служба устанавливается, однако не запускалась, лично у меня. Создал службу через NSSM, все завелось

**Comment by craftersmine** [comment]
Диспетчер служб начинал запускать службу, однако через какое-то время выкидывало ошибку, мол не удалось запустить службу. Хотя, сейчас вроде работает... 🤔

**Comment by craftersmine** [comment]
Win11 x64 23H2 Release Channel если нужно.
