### ISSUE TITLE
Добавьте пожалуйста поддержку авторизации через Госуслуги при работающей программе

### ISSUE THREAD

**Issue by astrabankrot** [ValdikSS/GoodbyeDPI#545]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Добавьте пожалуйста авторизацию через Госуслуги при работающей программе goodbyedpi. На данный момент авторизация не работает.

**Comment by EgorWeders** [comment]
Не работает каким образом, не соединяет или пишет что-то другое? Конкретно как ошибка себя проявляет.

**Comment by johnnyd-78** [comment]
Она не на данный момент не работает, она никогда не работала. Сколько себя помню и использую GDPI никогда она без blacklist не работала. Крутил где-то час настройки, еще на версии то ли 0.1.2 то ли 0.1.5 - так ничего и не добился. Пров - Ростелеком, если это важно.

> Не работает каким образом, не соединяет или пишет что-то другое? Конкретно как ошибка себя проявляет.

Да описано в ридми она себя проявляет - SSL Error чего-то там. Хотя сейчас у меня все работает с -6 -e1 -p -r -m

**Comment by ValdikSS** [comment]
Нет ответа от автора.
