### ISSUE TITLE
Вылеты CS2, CS:GO (legacy) во время использования GoodbyeDPI (я запускаю 2_any_country.bat)

### ISSUE THREAD

**Issue by Vladikboy13** [ValdikSS/GoodbyeDPI#546]
### Operating system / операционная система

Windows 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

здравствуйте те которые сделали обход замедления ютуба (а также X (Twitter) ) короче когда я с вашим GoodbyeDPI хочу поиграть в CS2, CS:GO (legacy) у меня во время загрузки карты и во время матча у меня происходят вылеты игры (они даже происходят после отлючения GoodbyeDPI)
![NrSddlZmgX](https://github.com/user-attachments/assets/c8797c5a-e332-4fff-84d6-1e864f79fc4e)
![eS6GOF8cqC](https://github.com/user-attachments/assets/bcc1157e-0b60-4d8f-ac96-b7090dd2c217)

и после того как произошел еще один вылет Steam запустил проверку файлов CS2, CS:GO (legacy)

### Additional information / Дополнительная информация

как я думаю что когда я запускаю этот батник (2_any_country.bat) то у меня именно из него происходят вылеты в CS2, CS:GO (legacy)

**Comment by EgorWeders** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/172#issuecomment-607769100
Но выглядит так, что из-за goodbyedpi.exe у вас криво обновились пакеты, проведите проверку целостности в steam для игр.

**Comment by ValdikSS** [comment]
У вас, случаем, не Intel 12 или 13 серии. Возможно, это аппаратная деградация процессора. GoodbyeDPI не инжектится в процессы и не взаимодействует с файловой системой, а у вас ошибки памяти и чтения файлов.

**Comment by jfima** [comment]
> У вас, случаем, не Intel 12 или 13 серии. Возможно, это аппаратная деградация процессора. GoodbyeDPI не инжектится в процессы и не взаимодействует с файловой системой, а у вас ошибки памяти и чтения файлов.

рекомендую скачать бесплатную occt и запустить тест ram+cpu есть ли ошибки аппаратные или нет.

**Comment by Vladikboy13** [comment]
> У вас, случаем, не Intel 12 или 13 серии. Возможно, это аппаратная деградация процессора. GoodbyeDPI не инжектится в процессы и не взаимодействует с файловой системой, а у вас ошибки памяти и чтения файлов.

у меня процессор Ryzen 5 5600G и я пк собирал в марте 24 года

**Comment by Vladikboy13** [comment]
я проверял OCCT ошибок нет (а вылетов CS2, CS:GO (legacy) нету после перезагрузки пк)
