### ISSUE TITLE
Дополнительный блэклист (РФ) | Additional blacklist (Russia)

### ISSUE THREAD

**Issue by pr0kuk** [ValdikSS/GoodbyeDPI#549]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Предлагаю добавить отдельный блэклист по тому же принципу что и `russia-youtube.txt`, например `russia-essential.txt` где будут перечислены диапазоны адресов, которые действительно могут пригодиться обычному юзеру из России и при этом являются относительно безопасными (инстаграм, фейсбук, ютуб и тд). 
Да, такой список тяжелее обновлять, зато он будет совсем небольшим. 
Большинство адресов из дефолтного списка заблокированы вовсе не просто так и большинству пользователей далеко не обязательно иметь доступ к каким-нибудь доменам типа `000.pe`, `5632.com.ua` и тд.

**Comment by ValdikSS** [comment]
Вы готовы вести такой блеклист?

**Comment by pr0kuk** [comment]
Я бы предложил следующую схему
Отталкиваться от такого списка:
<details>
<summary>simple blacklist</summary>
<pre><code>facebook.com
fbcdn.net
fb.com
fbsbx.com
fbpigeon.com
messenger.com
instagram.com
cdninstagram.com
ig.me
twitter.com
twimg.com
t.co
x.com
yt3.ggpht.com
play.google.com
play.google.ru
</code></pre>
</details>
Может в этой ветке кто-нибудь ещё какие домены накидает.<br>
Далее разместить этот список и <code>russia-youtube.txt</code> где-нибудь в репозитории и дополнять их через pr'ы.<br>
Учитывая, что в данном списке скорее всего будут находится буквально считанные ресурсы (meta, twitter и google), то обновлять их часто не придётся, в отличие от полного списка с (судя по всему стороннего) ресурса <code>p.thenewone.lol/domains-export.txt</code>.<br>
К тому же о блокировке действительно популярных ресурсов обычно трезвонят из каждого утюга, что обеспечит своевременное обновление списка.<br><br>

Аргументы в пользу ведения дополнительных списков:
- Во-первых уже есть прецедент добавления списка с ресурсами ютуба (которые официально вроде как не заблокированы)
- Во-вторых рядовому пользователю вряд ли захочется скачивать лишний раз что-то с вебсайта с именем <code>thenewone.lol</code>
- В текущих обстоятельствах есть смысл подстраивать этот проект не под энтузиастов, а под массового пользователя, которому не нужно ничего лишнего

Конечно хотелось бы иметь какой-то официальный или хотя бы надёжный сторонний ресурс, который сам бы следил за заблокированными адресами в РФ и желательно ещё сортировал бы их по причине блокировки, но судя по всему такого ресурса пока нет, так что ведение собственных списков, наверное, имеет смысл.

**Comment by ValdikSS** [comment]
@pr0kuk, вы готовы сделать такой лист и поддерживать его актуальность?
Я не против сделать еще один .cmd-файл с прямой ссылкой на альтернативный лист, но не более.

> Во-вторых рядовому пользователю вряд ли захочется скачивать лишний раз что-то с вебсайта с именем `thenewone.lol`

Пусть не скачивает — полная свобода выбора. Это мой домен, список формируется из выгрузки Роскомнадзора путём обработки [генератором](https://bitbucket.org/anticensority/antizapret-pac-generator-light/src) в рамках проекта антизапрет.

> В текущих обстоятельствах есть смысл подстраивать этот проект не под энтузиастов, а под массового пользователя, которому не нужно ничего лишнего

Если хотите — действуйтее, я буду только рад и поддержку вас морально. Но вне основного репозитория.

Вы, вероятно, считаете, что если программа опубликована в свободном доступе, то она делалась для всех и ПОД ВАС, пользователя, конкретно. Я рад, если программа вам подходит и работает у вас должным образом, но я её делал прежде всего для себя, она решает мою задачу тем способом, которым мне удобно.

Вы предлагаете, если я всё правильно понял, сделать _мне_ еще один лист и самостоятельно поддерживать его актуальность потому, что вам не нравятся заблокированные сайты. Хорошо, а _мне_-то это зачем?

**Comment by pr0kuk** [comment]
> Вы, вероятно, считаете, что если программа опубликована в свободном доступе, то она делалась для всех и ПОД ВАС, пользователя, конкретно. Я рад, если программа вам подходит и работает у вас должным образом, но я её делал прежде всего для себя, она решает мою задачу тем способом, которым мне удобно.

Абсолютно не важно для чего она делалась, важно для чего она используется, а используется она много кем, учитывая количество звёзд на репозитории.

> сделать мне еще один лист и самостоятельно поддерживать его актуальность

Я предлагаю поддерживать лист опенсорс сообществу

Основной стейтмент я уловил так, в репозитории будет находится только сам софт и ничего больше, в таком случае закрываю обсуждение
