### ISSUE TITLE
Хотелось бы релиз под Mac

### ISSUE THREAD

**Issue by kostakoff** [ValdikSS/GoodbyeDPI#55]
Есть софт под linux, есть Этот под win, а под мак нет.
GoodbyeDPI хороший проект, хотелось бы релиз под мак.

**Comment by ValdikSS** [comment]
Мне тоже. Если вы намерены его делать, я не против.

**Comment by ValdikSS** [comment]
#44

**Comment by grandsilence** [comment]
https://github.com/dzhidzhoev/AntiRTDPI кто-то пробовал?
