### ISSUE TITLE
* wildcard character

### ISSUE THREAD

**Issue by ghost** [ValdikSS/GoodbyeDPI#550]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

`*` : the wildcard character. It is used to represent any set of characters. This can also be an empty string or a string of any length.
To use `*` : the wildcard character I just need to add
`*.twitch.tv`
`*.ttvnw.net`
or 
`*.twitch.*`
`*.ttvnw.*`

---
I need to add subdomains one by one. It's a pain in the ass.
www.twitch.tv
gql.twitch.tv
assets.twitch.tv
usher.ttvnw.net
video-edge-d956ca.lhr08.abs.hls.ttvnw.net
video-weaver.ams02.hls.ttvnw.net
video-weaver.ams03.hls.ttvnw.net
video-edge-c683ec.arn03.abs.hls.ttvnw.net
video-edge-af3827.pdx01.abs.hls.ttvnw.net
video-weaver.arn04.hls.ttvnw.net

**Comment by ValdikSS** [comment]
> I need to add subdomains one by one. It's a pain in the ass.

Just add

```
twitch.tv
ttvnw.net
```

That's all.

>--blacklist   <txtfile>  perform circumvention tricks only to host names **and subdomains** from supplied text file (HTTP Host/TLS SNI).
