### ISSUE TITLE
Add google service/Добавьте сервисы гугл

### ISSUE THREAD

**Issue by DrKYST** [ValdikSS/GoodbyeDPI#552]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

At the moment, I live in the Donetsk region and Google is blocked on our side. Without it, I can't use a fairly extensive list of other services.
На данный момент я проживаю на территории Донецкой области и у нас с нашей стороны заблокирован гугл. Без него я не могу пользоваться довольно обширным списком иных сервисов.

**Comment by ValdikSS** [comment]
Что вам мешает добавить домены самостоятельно? .cmd-файлы и список доменов в .zip-релизе — только примеры. Модифицируйте их под свои нужды.

**Comment by SUGHuser** [comment]
> Что вам мешает добавить домены самостоятельно? .cmd-файлы и список доменов в .zip-релизе — только примеры. Модифицируйте их под свои нужды.

Я тебе писал в джабере в чём проблема... существуют сайты которые открываются только без GoodByeDPI , но основная масса сайтов открывается нормально , то как у тебя сделано сейчас , ты очень ограничеваешь людей в выборе... а конкретно , чтоб открывать всё нужно запускать программу без --blacklist , если запустить с --blacklist то мы получим доступ только к тому , что записано в нём , а  если например www.x.y имеет адресацию на www.y.x и www.y.x заблочен - мы можем не открыть www.x.y , если бы ты добавил возможность писать не только --blacklist , но и --whitelist , то тогда можно было бы гнать весь трафик через GoodByeDPI , но конкретные сайты через этот список не гнать ) по сути работает так же как --blacklist , только не с + , а с - пожалуйста , добавь эту опцию ) в тех регионах откуда тебе пишут всё очень очень упорото и могут создавать сайты для обслуживания анселения УМЫШЛЕННО так , чтоб при использовании твоего средства они не работали )

**Comment by DrKYST** [comment]
> Что вам мешает добавить домены самостоятельно? .cmd-файлы и список доменов в .zip-релизе — только примеры. Модифицируйте их под свои нужды.

Не выходит, я уже попытался

**Comment by ValdikSS** [comment]
Что вы пытались сделать?

**Comment by DrKYST** [comment]
> Что вы пытались сделать?

Вписывать домены в russia-blacklist.txt

**Comment by ValdikSS** [comment]
Почему вы тогда считаете, что программа вам поможет?

Запустите .exe-файл без параметров.
Заработало? Вы, вероятно, вписали не все домены.
Не заработало? Вероятно, блокировка по IP, программа не поможет.

**Comment by SUGHuser** [comment]
> Не заработало? Вероятно, блокировка по IP, программа не поможет.
Вот как раз поэтому , я тебе предлагаю сделать праметр --use-sys-proxy который сможет переназначать все запросы на системный прокси если у людей есть VPN который стоит как прокси )

**Comment by DrKYST** [comment]
> Почему вы тогда считаете, что программа вам поможет?
> 
> Запустите .exe-файл без параметров. Заработало? Вы, вероятно, вписали не все домены. Не заработало? Вероятно, блокировка по IP, программа не поможет.

Скорее всего гугл у нас заблокирован по второму варианту

**Comment by SUGHuser** [comment]
https://github.com/DrKYST , просите сделать https://github.com/ValdikSS/GoodbyeDPI/issues/538 , голосуйте чтоб была такая возможность

**Comment by ValdikSS** [comment]
@SUGHuser, еще одно сообщение не по теме где-либо и я вас забаню.

**Comment by DrKYST** [comment]
> Почему вы тогда считаете, что программа вам поможет?
> 
> Запустите .exe-файл без параметров. Заработало? Вы, вероятно, вписали не все домены. Не заработало? Вероятно, блокировка по IP, программа не поможет.

В общем, я написал сей высер из-за того, что у меня не получалось отправить картинку по discord. Так идёт PUT запрос на discord-attachments-uploads-prd.storage.googleapis.com, а так как гугл заблокирован с моей стороны, то мне пришла идея воспользоваться вашей утилитой. Я вписал как сам адрес запроса, так и googleapis.com. Как видите, идея не вышла, а я разочаровался в себе.

Пока я это писал, я запустил exeшник, как вы советовали, и у меня стала нормално открываться главная страница гугла.

Если я что-то неправильно понял в устройстве утилиты, но прошу прояснить.

**Comment by ValdikSS** [comment]
Возможно, вы не отключили Kyber?
https://github.com/ValdikSS/GoodbyeDPI/issues/330

**Comment by DrKYST** [comment]
> Возможно, вы не отключили Kyber? #330

Я это сделал перед установкой утилиты

**Comment by ValdikSS** [comment]
Тогда только записывать трафик и анализировать домены:
https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark
