### ISSUE TITLE
No internet at all with Windows Firewall configured

### ISSUE THREAD

**Issue by DelikliBurun** [ValdikSS/GoodbyeDPI#553]
### Operating system / операционная система

Windows 11 23H2 22631.3880

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

My Windows Firewall is configured to allow only specified apps (firefox.exe, yt-dlp.exe, and some others).
When I start GoodbyeDPI, all internet connecrtions stop working.
When I add "allow all outgoing TCP to 443 port" internet starts working. But this is unsecure and can't be used in real life.
It seams that the process ID is lost when processing the package.

**Comment by SUGHuser** [comment]
Simply add GoodbyeDPI in Firewall )
Also you can add this application as not snifed in Windows Firewall )

**Comment by DelikliBurun** [comment]
Adding GoodbyeDPI.exe to FW rules doesn't help.
And if this had worked, it would have broken the firewall anyway, because a packet from any application that passed through the GoodbyeDPI would have been allowed.
I need the PID to be saved in the processed package.

**Comment by ValdikSS** [comment]
GoodbyeDPI reinjects packets as `system`.

**Comment by GitUser200607** [comment]
But how can I allow this connection?
```
The Windows Filtering Platform has blocked a connection.

Application Information:
	Process ID:		4
	Application Name:	System

Network Information:
	Direction:		Outbound
	Source Address:		192.168.1.64
	Source Port:		25007
	Destination Address:	52.166.127.37
	Destination Port:		443
	Protocol:		255

Filter Information:
	Filter Run-Time ID:	130933
	Layer Name:		Connect
	Layer Run-Time ID:	48
```
