### ISSUE TITLE
Проблемы с VPN после установки 

### ISSUE THREAD

**Issue by Valeron-bit** [ValdikSS/GoodbyeDPI#557]
### Operating system / операционная система

Win 11 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

После установки программы (service_install_russia_blacklist.cmd) перестали работать vpn расширения во всех браузерах, хотя с десктопными vpn'нами такого не замечено. Полный откат непомог. Проверил проблему на другом пк и ситуация аналогичная.

**Comment by EgorWeders** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/349
https://github.com/ValdikSS/GoodbyeDPI/issues/526
https://github.com/ValdikSS/GoodbyeDPI/issues/330
https://github.com/ValdikSS/GoodbyeDPI/issues/340

Изучите другие issues

**Comment by ValdikSS** [comment]
Напишите пошагово, какие действия приводят к проблеме.

**Comment by Valeron-bit** [comment]
> Напишите пошагово, какие действия приводят к проблеме.
Установка service_install_russia_blacklist.cmd
Отключение в edge://flags/ Experimental QUIC protocol и TLS 1.3 hybridized Kyber support

**Comment by ValdikSS** [comment]
@Valeron-bit напишите максимально подробно, что нужно сделать для полного воспроизведения проблемы. Какие VPN/расширения вы используете, какой сервер выбираете, и т.п., чтобы я проделал ровно те же шаги и воспроизвёл проблему.

**Comment by Valeron-bit** [comment]
Сведенья о том что использовал:
Операционная система: Windows 11 Version 22H2 (Build 22621.3880). Используемая версия Edge — 127.0.2651.98 (официальная сборка, 64-разрядная). VeePN версии 2.7.2, сервер Netherlands, Amsterdam (Скорее всего, это не имеет значения, поскольку все VPN и расширения перестали работать). Goodbyedpi версии 0.2.2.

Что делал чтобы получить пробему:
1. Запустил с правами администратора файл service_install_russia_blacklist.cmd
2. Открыл chrome://flags, поставил значение параметров Experimental QUIC protocol и TLS 1.3 hybridized Kyber support на Disabled.
3. Перезапустил браузер.

**Comment by ValdikSS** [comment]
Особенность фильтра ТСПУ по работе с TLS. Включите Kyber — должно заработать (но сломает фильтр по доменам в goodbyedpi).
Не ошибка программы.

**Comment by ValdikSS** [comment]
Напишите, пожалуйста, помогло ли включение kyber (установите его в default, не обязательно в enable).

**Comment by ValdikSS** [comment]
Альтернативный вариант, без включения Kyber:

1. Добавить домен `tlsext.com` в blacklist
2. Запускать GoodbyeDPI с дополнительной опцией `--port 10799`

**Comment by Valeron-bit** [comment]
Ничего из вышеперечисленного не помогло. К слову, при попытке включить VPN консоль выдает следующие ошибки:
![image](https://github.com/user-attachments/assets/ed05f6f3-7ca4-4b2d-aab3-b5b0d0eea9a7)

**Comment by ValdikSS** [comment]
У вас, вероятно, уже есть какой-то прокси (об этом говорят ошибки ERR_PROXY_CONNECTION_FAILED). Не удивлюсь, если проблема не в сети, а в конфликте расширений.

**Comment by Valeron-bit** [comment]
Это не может быть GoodbyeDPI?

**Comment by ValdikSS** [comment]
Запишите дамп трафика (без фильтров по IP) в момент, когда вы нажимаете на большую кнопку подключения в veepn.
https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark


> Это не может быть GoodbyeDPI?

Если он у вас не запущен — он не работает.

**Comment by Valeron-bit** [comment]
[Desktop.zip](https://github.com/user-attachments/files/16627833/Desktop.zip)

**Comment by ValdikSS** [comment]
Что есть что?
В обоих дампах нет ни Kyber, ни следов работы GoodbyeDPI.
