### ISSUE TITLE
Ошибка "Error loading filter: System cannot find file specified" после запуска программы

### ISSUE THREAD

**Issue by johnnyd-78** [ValdikSS/GoodbyeDPI#558]
### Operating system / операционная система

Windows 8.1 Embedded Industry Pro x86

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Версия 0.2.2. Программа запускается, но в конце выдеает ошибку Error loading filter: System cannot find file specified и через несколько секунд закрывается.

### Additional information / Дополнительная информация

Более старые версии нормально работали. Если бы хотя бы писало, что за файл - я бы сюда не обращался, сам бы все нашел и установил.

**Comment by EgorWeders** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/446
