### ISSUE TITLE
Проблема с запуском GoodbyeDPI v0.1.4

### ISSUE THREAD

**Issue by bkostik** [ValdikSS/GoodbyeDPI#56]
GoodbyeDPI: Passive DPI blocker and Active DPI circumvention utility
Block passive: 1, Fragment HTTP: 2, Fragment persistent HTTP: 2, Fragment HTTPS:
2, host: 1, Host no space:  1, Additional space: 0, Mix Host: 0, HTTP All Ports:
0, HTTP Persistent  Nowait:  1, DNS redirect: 0

Opening filter
Windows cannot verify the digital signature for this file. A recent  hardware or
Software change might have installed a file that is signed incorrectly or damage
d, or that might be malicious software from an unknown source.
![goodbyedpi](https://user-images.githubusercontent.com/35203220/34654818-26d92308-f41a-11e7-82ac-cc6f3be62a8a.jpg)

**Comment by ValdikSS** [comment]
На дворе 2018 год, а не 2014. Обновите вашу систему хотя бы до состояния 2015 года.

https://docs.microsoft.com/en-us/security-updates/SecurityAdvisories/2015/3033929

Если у вас не установлено это обновление, то у вас и нет, как минимум, патчей для закрытия уязвимостей MS17-010, и любой злоумышленник из локальной сети или публичного Wi-Fi вам беспрепятственно прогрузит вирусов. Не пользуйтесь «сборками» Windows, копиями со сломанными обновлениями, «кумулятивными updatepack от simplix-а».

**Comment by bkostik** [comment]
Спасибо Вам за исчерпывающий и мгновенный ответ! Естественно помогло.
