### ISSUE TITLE
GoodbyeDPI не появляется в службах Windows

### ISSUE THREAD

**Issue by danyanya111** [ValdikSS/GoodbyeDPI#562]
### Operating system / операционная система

ex. Windows 10 2H22

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Всем привет, уважаемые! Может кто сможет помочь: к сожалению goodbyeDPI не появляется в службах windows, хоть при запуске командной строки пишет, что все работает т.к. не добавляется службы - никаких изменений нет, не знаю что делать((

Я еще тот чайник и может что - то делаю не так, но строго соблюдал все инструкции, пытался запустить и другие cmd команды, не только для рф - тот же результат, служба не появляется, хотя в командной строке пишет, что все работает

P.S. Пробовал разные версии GoodbyeDPI - никакая не работает

**Comment by danyanya111** [comment]
https://ibb.co/9qJfdCR не заливается скрин сюда, залил на фотообменик

**Comment by ValdikSS** [comment]
На скриншоте запечатлена просто запущенная программа.
Что именно происходит при установке сервиса? Предоставьте вывод.

**Comment by danyanya111** [comment]
> На скриншоте запечатлена просто запущенная программа. Что именно происходит при установке сервиса? Предоставьте вывод.

Что именно надо сделать? Я немного не понимаю Вас(

**Comment by ValdikSS** [comment]
Как вы пытаетесь установить службу? Какие действия вы проделываете и какой результат получаете?
Иными словами, в чём именно проблема?

**Comment by danyanya111** [comment]
> Как вы пытаетесь установить службу? Какие действия вы проделываете и какой результат получаете? Иными словами, в чём именно проблема?

Так служба должна появится после запуска командной строки(файла 1_russia_blacklist), но не появляется, ошибки никакие не выдает, просто ее нет и все

**Comment by ValdikSS** [comment]
Нет, не должна.

**Comment by danyanya111** [comment]
> Нет, не должна.

Хмм, сравнивал с товарищами, у всех появилась в службах...
Ну ладно, что тогда делать? Все равно не работает, параметр kyber вырубал в браузере...

**Comment by ValdikSS** [comment]
> Да тоже самое, не появляется

Какой вывод вам даёт запуск файла `service_install_russia_blacklist`? Пришлите его целиком.

**Comment by danyanya111** [comment]
Проблема решилась, всем спасибо
