### ISSUE TITLE
Перестала работать программа сегодня с утра. 

### ISSUE THREAD

**Issue by droedy** [ValdikSS/GoodbyeDPI#563]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

До сегодняшнего дня всё отлично работало. 
Вписал руками в блокнот russia-blacklist.txt: 
_youtube.com
youtube.com/feed/
youtube.com/feed/subscriptions
youtube.com/shorts/
youtube.com/feed/history
studio.youtube.com
googlevideo.com
https://nhacmp3youtube.com/_
Стала прогружаться страница и ютуб студия, на роликах же стоит ограничение 5kbps. 
Браузер - яндекс. 
В огнелисе вообще не грузит студию и главную страницу ютуба. 
Скриншот - это данные с видео. 
![photo_2024-08-14_11-40-29](https://github.com/user-attachments/assets/504ab802-e9fa-4f57-878d-38fcdb5038c4)

**Comment by johnnyd-78** [comment]
1) Попробуйте отключить в настройках браузера Kyber
2) Впишите сервера в блэклист нормально, пример:
```
nhacmp3youtube.com
ytimg.com
studio.youtube.com
youtube.com
googlevideo.com
youtu.be
googleusercontent.com
gvt1.com
video.google.com
video.l.google.com
youtubeembeddedplayer.googleapis.com
youtube.googleapis.com
youtubei.googleapis.com
youtube-nocookie.com
youtube-ui.l.google.com
ggpht.com
yt.be
ytimg.l.google.com
ytkids.app.goo.gl
yt-video-upload.l.google.com
withyoutube.com
wide-youtube.l.google.com
```
3) Комбинируйте настройки, блокираторы на месте не стоят. Все настройки описаны в readme.md

**Comment by MiTereKun** [comment]
@droedy я почти уверен, что проблема именно в яндекс браузере (но очень мало пишут об этом), 3 дня назад в нём работало. У друга старая ОС и это единственный браузер где есть настройка Kyber.
Проверяли на хроме 127.0.6...?

**Comment by johnnyd-78** [comment]
@droedy Насчет везде пишут... Решение с выключением QUIC так называетмое obsolete (устаревшее) решение, из времен, когда провы еще репы чесали и думали, как бы нам это замедлить? У меня уж недели 2 как перестало работать. И теперь с включенным QUIC у меня лично все летает, в отличии от выключенного. Кстати, опция -q из GDPI видимо из той же оперы, от нее тоже пришлось отказаться, как и от режима -9.
Для QUIC Default и enable - суть одно и то же, по дефолту она и так включена, это написано внизу описания опции
Ну а Kyber нужно отключать потому что он ломает функцию блэклиста в GDPI, в итоге если ты используешь --blacklist в настройках, весь функционал программы по обходу нафиг перестает работать (я так это понял, если неправ - пусть @ValdikSS поправит)
Как-то так...

**Comment by johnnyd-78** [comment]
@droedy На данный момент так `goodbyedpi.exe -6 -e 1 --max-payload 2400 -p -r -m --blacklist ..\russia-blacklist.txt --blacklist ..\YT.txt`
Но наш местный офис РТК никогда не отличался особыми зверствами в блокировках, как там у вас блокируют (хуже/лучше) - неизвестно.
Единственное, что сейчас у меня отличает "новый" ютуб от "старого" - секундная задержка при загрузке превьюшек роликов, но то такое... может просто кажется )

**Comment by johnnyd-78** [comment]
> вписывали что-то в russia-blacklist и youtube-blacklist?
В первый - ничего, во втором то что указано выше, [тут](https://github.com/ValdikSS/GoodbyeDPI/issues/563#issuecomment-2288560721)

**Comment by SUGHuser** [comment]
> итоге если ты используешь --blacklist в настройках, весь функционал программы по обходу нафиг перестает работать (я так это понял, если неправ - пусть @ValdikSS поправит)

--blacklist работает только на то , что записано в файл например --blacklist list.txt и в этом list.txt добавлен какой нибудь сайт пусь будет www.xxx.com и больше ничего нет , это означает , что если www.xxx.com заблокирован - вы сможете его открыть , но если www.xxx.com ссылается на какие-то ресусрсы например на www.yyy.com и этот сайт тоже заблокирован и на нём лежат допустим картинки к www.xxx.com , то вы не увидите картинок хотя сайт www.xxx.com у вас откроется ) но если теперь вый пойдёте допустим на www.uuu.com и он тоже заблокирован и не находится в файле list.txt , то туда вы уже попасть не сможете )
