### ISSUE TITLE
Поддержка доменов первого уровня в чёрном списке

### ISSUE THREAD

**Issue by midncircus** [ValdikSS/GoodbyeDPI#564]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Блочатся (все?) сайты в зоне ua, хотя их нет в реестре. При этом сами сайты (нейтральной тематики вроде фитнеса, питания) часто открыты на Россию. Пример https://fitnessclubs.ua/

Как я понимаю, текущая реализация блеклиста не поддерживает добавление доменов первого уровня.

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/actions/runs/10389771539
