### ISSUE TITLE
GoodbyeDPI замедляет загрузку файлов на Google диск

### ISSUE THREAD

**Issue by PRXPHET** [ValdikSS/GoodbyeDPI#565]
### Operating system / операционная система

Windows 10 21H1

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

GoodbyeDPI замедляет загрузку файлов на Google диск.
UPD: Проблема актуальна и на других облачных дисках.

### Additional information / Дополнительная информация

С включенным GoodbyeDPI:
![image](https://github.com/user-attachments/assets/0984369c-b82e-4de1-bd0f-5f556a550e37)
Без:
![image](https://github.com/user-attachments/assets/623ca5dc-06a7-4a77-8041-09b5c3df2f6d)

**Comment by johnnyd-78** [comment]
Любая фрагментация пакетов будет замедлять выгрузку. Для этого вам и дана опция --blacklist - она позволяет программе не обрабатывать траффик с сайтов, не указанных в черном списке. Читайте раздел How to use

**Comment by ValdikSS** [comment]
См. #554
