### ISSUE TITLE
Opening filter Error opening filter: The system cannot find the path specified.

### ISSUE THREAD

**Issue by 677230756E64** [ValdikSS/GoodbyeDPI#566]
### Operating system / операционная система

windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Работала нормально все это время, после перезагрузки компа почему-то стала показывать эту ошибку

**Comment by kirysobstvennoypersonoy** [comment]
Столкнулся с этой проблемой, решил её переустановкой.

**Comment by ValdikSS** [comment]
1. Убедитесь, что файлы windivert.dll и windivert64.sys действительно существуют в x86_64, не были удалены антивирусом
2. Пуск - cmd - запустить от имени администратора. В появившемся окне консоли набрать:  
```
sc stop windivert
sc delete windivert
sc stop windivert14
sc delete windivert14
``` 
3. Пробовать запускать программу

**Comment by Tabintaban** [comment]
Иногда этот сценарий не срабатывает
`sc stop windivert
sc delete windivert
sc stop windivert14
sc delete windivert14`

и все равно пишет:
_Opening filter Error opening filter: The system cannot find the path specified._
Надо удалить папку:  Goodbydpi-0.2.3rc1
Виндоус напишет вам что не возможно удалить так как процесс WinDivert.dll или WinDivert.sys занят.
Это как раз говорит что косячный процесс который пишет _Opening filter Error opening filter: The system cannot find the path specified._ занят и не дает нормально отрабатывать.
Перезагрузитесь и удалите папку Goodbydpi-0.2.3rc1.
Потом заново распакуйте скачанный архив и из распакованной папки заново запустите 1_russia_blacklist.cmd
У меня только таким способом удалился косячный процесс и запустился нормальный
