### ISSUE TITLE
Пожалуйста добавьте ключ -help или --help

### ISSUE THREAD

**Issue by SUGHuser** [ValdikSS/GoodbyeDPI#567]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Пожалуйста , добавьте -help или --help или просто -h или --h для того чтоб можно было смотреть какие ключи в програме появились если они ещё не описаны в readme.md

**Comment by ValdikSS** [comment]
Этот ключ уже имеется.

**Comment by SUGHuser** [comment]
А тогда почему в тестовых сборках он не работает ? Я скачал вчера  то что в бета версиях с описанием Allow to add the whole root zones into blacklist. Fixes #564. и когда я попробовал ввести этот ключ чтоб посмотреть какие команды добавились или изменились , мне выдало 
![Screenshot_3248](https://github.com/user-attachments/assets/ad5c856d-3ac3-4c1d-964e-9ee90c7379b3)
![Screenshot_3249](https://github.com/user-attachments/assets/3f661ae2-54e0-4158-a32a-e57f893d1328)
![Screenshot_3250](https://github.com/user-attachments/assets/403caa13-b2c6-43ee-9998-01844e165053)
![Screenshot_3251](https://github.com/user-attachments/assets/eab7a8fe-db36-4968-9235-aa4f8fa57661)
и посмотреть что конкретно из команд добавилось я могу только в определённых сборках , а в определённых вот такая байда.

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/commit/7b66094f560b1511e2efe00ed4c429c16a3a5f7c

**Comment by ValdikSS** [comment]
>А тогда почему в тестовых сборках он не работает ? Я скачал вчера то что в бета версиях

Это не бета версии и не тестовые сборки, использовать их не нужно.

**Comment by SUGHuser** [comment]
Понял , но лично мне пришлось взять одну из самых новых от 09/08/2024 так как только с ней заработало на телевизорах

**Comment by k0zyrev** [comment]
> было бы не плохо добавить опцию -help print чтоб справка не просто выводилась , а выводилась в файл например в goodbyedpi.txt , то есть чтоб всегда можно было прям из программы получить файл с возможными ключами и описанием их 

goodbyedpi.exe -h > help.txt
