### ISSUE TITLE
Проблемы с запуском на windows 11

### ISSUE THREAD

**Issue by AlexChecker** [ValdikSS/GoodbyeDPI#568]
### Operating system / операционная система

Windows 11 23H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Проблема такова: я подобрал параметры, с которыми  ютуб нормально работает (сам пользуюсь wind 10), все работает нормально. Затем я отправил те же самые параметры своему товарищу (у которого как раз win11), и у него программа отказывается запускаться. Провайдер один и тот же (МГТС). Не запускается именно сама программа, и судя по всему это может быть багом версии 0.2.3rc1

### Additional information / Дополнительная информация

Команда, которая используется для запуска: `goodbyedpi.exe -f 1 -e 1 --wrong-chksum --reverse-frag --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --blacklist ./youtube-domain.txt`

**Comment by EgorWeders** [comment]
Запустите сначала cmd.exe под администратором, потом через него запустите с этой командой goodbyedpi.exe. Будет ли какой-то вывод или его вообще нет.

**Comment by ValdikSS** [comment]
Что программа выдаёт?

**Comment by AlexChecker** [comment]
> Запустите сначала cmd.exe под администратором, потом через него запустите с этой командой goodbyedpi.exe. Будет ли какой-то вывод или его вообще нет.

Если бы оно так работало. Программа работает только если ее запускать вообще без каких либо параметров

> Что программа выдаёт?

Ничего. Если запускать с параметрами, то просто запрашивает права администратора (если команду через bat файл запускать), после чего программа просто не открывается

**Comment by EgorWeders** [comment]
> > Запустите сначала cmd.exe под администратором, потом через него запустите с этой командой goodbyedpi.exe. Будет ли какой-то вывод или его вообще нет.
> 
> Если бы оно так работало. Программа работает только если ее запускать вообще без каких либо параметров
> 
То есть у вас просто так выглядит вывод :

```
C:\Program Files (x86)>goodbyedpi.exe -f 1 -e 1 --wrong-chksum --reverse-frag --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --blacklist ./youtube-domain.txt
C:\Program Files (x86)>

```

?

**Comment by AlexChecker** [comment]
> > > Запустите сначала cmd.exe под администратором, потом через него запустите с этой командой goodbyedpi.exe. Будет ли какой-то вывод или его вообще нет.
> > 
> > 
> > Если бы оно так работало. Программа работает только если ее запускать вообще без каких либо параметров
> 
> То есть у вас просто так выглядит вывод :
> 
> ```
> C:\Program Files (x86)>goodbyedpi.exe -f 1 -e 1 --wrong-chksum --reverse-frag --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --blacklist ./youtube-domain.txt
> C:\Program Files (x86)>
> ```
> 
> ?

Именно так

**Comment by johnnyd-78** [comment]
Ошибка в ключах должно быть `--blacklist ..\youtube-domain.txt`
И c IPv6 адресом тоже у меня сомнения, написан ли он правильно

**Comment by AlexChecker** [comment]
> Ошибка в ключах, должно быть написано `--blacklist ..\youtube-domain.txt`

Понял, видимо это прихоти чисто 11 винды

**Comment by johnnyd-78** [comment]
> это прихоти чисто 11 винды

Наверное )) Если напрочь забыть про то, что прямые слэши отродясь в путях не использовались (только в URL) и как это может работать на 10, лично мне непонятно.

**Comment by ValdikSS** [comment]
> Ничего. Если запускать с параметрами, то просто запрашивает права администратора (если команду через bat файл запускать), после чего программа просто не открывается

С большой вероятностью вы запускаете cmd не от имени администратора. Запустите от администратора.

**Comment by AlexChecker** [comment]
> > Ничего. Если запускать с параметрами, то просто запрашивает права администратора (если команду через bat файл запускать), после чего программа просто не открывается
> 
> С большой вероятностью вы запускаете cmd не от имени администратора. Запустите от администратора.

В том то и дело, что пробовали так тоже. Плюс, так или иначе программа сама запрашивает доступ администратора при запуске. Судя по всему это действительно проблема в пути к файлу

**Comment by ValdikSS** [comment]
Сделайте скриншоты ваших шагов.

**Comment by plenilla** [comment]
Такая же штука, когда запускаешь через 1_russia_blacklist.cmd то программа не запускается

**Comment by UserGit-2021** [comment]
> Сделайте скриншоты ваших шагов.

Привет, может ли программа влиять на скорость qbittorrent? Я его отключил, но скорость не повышается.
![изображение](https://github.com/user-attachments/assets/5e04d554-f4f2-4220-b98e-1d8e23691b23)

**Comment by johnnyd-78** [comment]
@UserGit-2021 Как запускаете программу?

Возможно и может, у меня лично не влияет, ни на загрузку, ни на отдачу.

**Comment by UserGit-2021** [comment]
> @UserGit-2021 Как запускаете программу?
> 
> Возможно и может, у меня лично не влияет, ни на загрузку, ни на отдачу.

Запускал как в инструкции. 
1 Скачайте [последнюю версию]), распакуйте архив
2  Запустите 1_russia_blacklist.cmd

**Comment by johnnyd-78** [comment]
@UserGit-2021 Если у вас даже без запущенной GDPI скорость ужасная, то при чем тут программа? Никакие настройки сети она не меняет и никаких изменений в систему вообще не вносит, чтобы это еще после перезагрузки работало.

**Comment by ValdikSS** [comment]
Нет ответа от автора.

**Comment by Mracobez11** [comment]
Приветы всем, прога всё, сломалась, второй день с Ростелекома войти не могу ни на 10-ке, не на 11-й, на работе МТС пока показывает. =)
