### ISSUE TITLE
VirusTotal detect unsafe software

### ISSUE THREAD

**Issue by constantin-evseev** [ValdikSS/GoodbyeDPI#57]
Antivirus Cylance on site VirusTotal.com detect GoodByeDPI as Unsafe program: https://www.virustotal.com/en/file/61ecf179f96aa2c24e97865155489d4b3714123cc58134b5adb0c6dbb9e510c1/analysis/

**Comment by ValdikSS** [comment]
Uh, so what?

**Comment by ValdikSS** [comment]
It's a false positive of a little-known antivirus software. Other 66 antiviruses didn't detect anything.

**Comment by ValdikSS** [comment]
На дворе 2018 год, а не 2014. Обновите вашу систему хотя бы до состояния 2015 года.

https://docs.microsoft.com/en-us/security-updates/SecurityAdvisories/2015/3033929

**ВНИМАНИЕ!** Если вы видите эту ошибку на Windows 7, это значит, что ваша система крайне устарела, и НЕ ДОЛЖНА ИСПОЛЬЗОВАТЬСЯ ДЛЯ ДОСТУПА В ИНТЕРНЕТ!
Скорее всего, у вас не установлены заплатки безопасности, и любой человек в вашей локальной сети или публичном Wi-Fi может получить полный доступ к вашему компьютеру и прогрузить вирусы (уязвимости MS17-010 и другие).

Установите обновления безопасности НЕМЕДЛЕННО.

**Comment by Swiftkill** [comment]
Hmm, KAV and AntiMalware delete it too or bock its traffic. It appears that everyone follows Google's claim that no one ever should use anti-dpi  utilities.
