### ISSUE TITLE
Можно ли с помощью неё обойти игровые блокировки?

### ISSUE THREAD

**Issue by ZmeYEditioN** [ValdikSS/GoodbyeDPI#570]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Доброго времени суток, подскажите можно ли с помощью этой программки обойти игровые блокировки?
А именно например игроки с Украины не могут найти и увидеть Российские сервера, я как понимаю в данном случае 443 и 80 порт используются. Или как-то добавить другие порты?

**Comment by ValdikSS** [comment]
>Можно ли с помощью неё обойти игровые блокировки?

Нет.

>Или как-то добавить другие порты?

См. readme.
