### ISSUE TITLE
Здравствуйте, перестала работать программа. Помогите пожалуйста ее решить!!!

### ISSUE THREAD

**Issue by ArtemLiveGames** [ValdikSS/GoodbyeDPI#571]
### Operating system / операционная система

windows 10 pro 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Здравствуйте,стоит Opening filter и все,дальше ничего не происходит. Ютуб не работает. На других устройствах прогружает фильтры и все работает! Помогите пожалуйста решить данную проблему. Дайте посмотреть ютуб как человеку!!!
![image](https://github.com/user-attachments/assets/f85d274a-1e49-41b3-b25d-275c690ef060)

**Comment by prblm** [comment]
try it
https://github.com/ValdikSS/GoodbyeDPI/issues/566#issuecomment-2290908472

**Comment by ArtemLiveGames** [comment]
> попробуйте [#566 (комментарий)](https://github.com/ValdikSS/GoodbyeDPI/issues/566#issuecomment-2290908472)

![image](https://github.com/user-attachments/assets/b6865cbd-09e6-47e9-b228-171cfee87539)

**Comment by prblm** [comment]
> > попробуйте [#566 (комментарий)](https://github.com/ValdikSS/GoodbyeDPI/issues/566#issuecomment-2290908472)
> 
> ![image](https://private-user-images.githubusercontent.com/39933939/358368166-b6865cbd-09e6-47e9-b228-171cfee87539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NTMwMTQsIm5iZiI6MTcyMzc1MjcxNCwicGF0aCI6Ii8zOTkzMzkzOS8zNTgzNjgxNjYtYjY4NjVjYmQtMDllNi00N2U5LWIyMjgtMTcxY2ZlZTg3NTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDIwMTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZDk3NTY1YTg0YWM4NjBmNmU2OTM2NTk5YTE0YTE0NjEwMzQ3YjE0ZGNlMWViZjg1MDc4MWYzNzU4Mzc1MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ulFlS7i2ZPSt1zTFClBv8HOJ4HFLq0QJgKUSpW77nUY) ![image](https://private-user-images.githubusercontent.com/39933939/358368390-5b102e97-6294-457f-9f2e-8257ee23fefe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NTMwMTQsIm5iZiI6MTcyMzc1MjcxNCwicGF0aCI6Ii8zOTkzMzkzOS8zNTgzNjgzOTAtNWIxMDJlOTctNjI5NC00NTdmLTlmMmUtODI1N2VlMjNmZWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDIwMTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNDRiMDg2OWE3Y2ZmY2EyMWI3YTI1MTNhYWIzM2RmZGQxMzE1OWE0ZThhMGJmNTYwYzE0ZDdkODU5MmFjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZrbWj9UbrykisiI7ioJeeMrNnfIWfxgBAk3I7Tu5Ey8)

возможно она уже остановлена, попробуй следующие команды, ну и потом ребутнись

**Comment by ArtemLiveGames** [comment]
> > > попробуйте [#566 (комментарий)](https://github.com/ValdikSS/GoodbyeDPI/issues/566#issuecomment-2290908472)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/39933939/358368166-b6865cbd-09e6-47e9-b228-171cfee87539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NTMwMTQsIm5iZiI6MTcyMzc1MjcxNCwicGF0aCI6Ii8zOTkzMzkzOS8zNTgzNjgxNjYtYjY4NjVjYmQtMDllNi00N2U5LWIyMjgtMTcxY2ZlZTg3NTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDIwMTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZDk3NTY1YTg0YWM4NjBmNmU2OTM2NTk5YTE0YTE0NjEwMzQ3YjE0ZGNlMWViZjg1MDc4MWYzNzU4Mzc1MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ulFlS7i2ZPSt1zTFClBv8HOJ4HFLq0QJgKUSpW77nUY) ![image](https://private-user-images.githubusercontent.com/39933939/358368390-5b102e97-6294-457f-9f2e-8257ee23fefe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NTMwMTQsIm5iZiI6MTcyMzc1MjcxNCwicGF0aCI6Ii8zOTkzMzkzOS8zNTgzNjgzOTAtNWIxMDJlOTctNjI5NC00NTdmLTlmMmUtODI1N2VlMjNmZWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDIwMTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNDRiMDg2OWE3Y2ZmY2EyMWI3YTI1MTNhYWIzM2RmZGQxMzE1OWE0ZThhMGJmNTYwYzE0ZDdkODU5MmFjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZrbWj9UbrykisiI7ioJeeMrNnfIWfxgBAk3I7Tu5Ey8)
> 
> возможно она уже остановлена, попробуй следующие команды, ну и потом ребутнись

![image](https://github.com/user-attachments/assets/cd179d7e-1526-4309-b997-56817071ccb1)

**Comment by johnnyd-78** [comment]
Можно сделать проще.
1) Правой кнопкой мыши по service_remove.cmd - Запуск от имени Администратора
2) Перезагрузиться
3) Проверить

**Comment by ArtemLiveGames** [comment]
> Можно сделать проще.
> 
> 1. Правой кнопкой мыши по service_remove.cmd - Запуск от имени Администратора
> 2. Перезагрузиться
> 3. Проверить

Спасибо большое! Заработало!

**Comment by ArtemLiveGames** [comment]
Спасибо большое всем за помощь!

**Comment by HodovVladislav** [comment]
> Спасибо большое всем за помощь!

У меня в яндекс браузере ютуб не пашет.
Можешь сказать, что ты сделал чтобы у тебя работало?

**Comment by ArtemLiveGames** [comment]
> > Спасибо большое всем за помощь!
> 
> У меня в яндекс браузере ютуб не пашет. Можешь сказать, что ты сделал, чтобы ты работал? (в целом какая конструкция)

Experimental QUIC protocol enabled 
TLS 1.3 hybridized Kyber support disabled
У меня такие настройки стоят на другом пк
