### ISSUE TITLE
Error opening filter: There are no more endpoints available from the endpoint mapper.

### ISSUE THREAD

**Issue by LTSCTeam** [ValdikSS/GoodbyeDPI#576]
### Operating system / операционная система

Windows 10 22H2 (19045.2965)

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Не хочет по какой то причине запускаться. Уже все перепробывал
![image](https://github.com/user-attachments/assets/bf688da7-8f46-4324-bbd0-5559f5bb7713)

**Comment by EgorWeders** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/540
