### ISSUE TITLE
Не запускается на Windows 7, 

### ISSUE THREAD

**Issue by kagalenko-m-b** [ValdikSS/GoodbyeDPI#577]
### Operating system / операционная система

Windows 7

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Возникает "ошибка подписи фильтра" и рекомендация срочно установить обновления. Однако служба обновления работает, все рекомендованные обновления установлены, включая KB3033929

**Comment by k0zyrev** [comment]
на 7 с драйверами нетривиальные проблемы, изучайте этот тред https://ntc.party/t/%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D0%B8-%D0%B4%D1%80%D0%B0%D0%B9%D0%B2%D0%B5%D1%80%D0%BE%D0%B2-windows-7-x64/8510/17

Характерная цитата от ValdikSS:
>  В официальных сборках Windows 7 с официальными обновлениями, которые и есть у подавляющего большинства пользователей, работать не будет.

**Comment by sersoftin** [comment]
Боже, зачем вообще сидеть на 7 винде в 2024…

**Comment by kagalenko-m-b** [comment]
> Боже, зачем вообще сидеть на 7 винде в 2024…

Потому, что на Линуксе нет требуемых программ, а выбрасывать работающий комп потому что в Редмонде так левая пятка захотела не позволяют средства?

**Comment by SUGHuser** [comment]
> @ sersoftin 
> Боже, зачем вообще сидеть на 7 винде в 2024…

Причин много , от логики системы Windows 10 и до её дизайна ) MS сделали ошибку поптавшись скрестить клава-мышку и пальцетык.... хотели унификацию , получили что на пальцетыке система особой поулярности не получила из-за того что там распростарнённей Android и IOS , а тем кто привык к клав-мышке лишние элементы от пальцетыка сильно не понравились ) и я один из таких людей )

**Comment by AKotov-dev** [comment]
Только что ставил по удалёнке на Win-7 (lic) [goodbyedpi-0.2.3rc1-2.zip](https://github.com/ValdikSS/GoodbyeDPI/releases/download/0.2.3rc1/goodbyedpi-0.2.3rc1-2.zip) одному человеку. Всё отлично воркает. Тот сразу полез в ютуб искать - "чем просверлить в стене дырку большого диаметра".

**Comment by marlynka** [comment]
> > @ sersoftin
> > Боже, зачем вообще сидеть на 7 винде в 2024…
> 
> Причин много , от логики системы Windows 10 и до её дизайна ) MS сделали ошибку попытавшись скрестить клава-мышку и пальцетык.... хотели унификацию , получили что на пальцетыке система особой популярности не получила из-за того что там распространнёнее Android и IOS , а тем кто привык к клава-мышке лишние элементы от пальцетыка сильно не понравились ) и я один из таких людей ) потому и буду пользоваться Windows 7 до упора ) пока она хоть как-то работает ) я понимаю что собственно браузероделы могут тоже прижать чтоб пересадить на Windows 10 , та же Mozilla например... но я это всё таки считаю извращением.

Вы не представляете, сколько сложностей добавляете разрабам софта, когда хотите, чтобы что-то работало из того, что не работает. Особенно на стороне дров. В некоторых местах различия прям очень большие, особенно в сети и WFP.

**Comment by k0zyrev** [comment]
> > @ sersoftin
> > Боже, зачем вообще сидеть на 7 винде в 2024…
> 
> Причин много , от логики системы Windows 10 и до её дизайна ) MS сделали ошибку попытавшись скрестить клава-мышку и пальцетык.... хотели унификацию , получили что на пальцетыке система особой популярности не получила из-за того что там распространнёнее Android и IOS , а тем кто привык к клава-мышке лишние элементы от пальцетыка сильно не понравились ) и я один из таких людей ) потому и буду пользоваться Windows 7 до упора ) пока она хоть как-то работает ) я понимаю что собственно браузероделы могут тоже прижать чтоб пересадить на Windows 10 , та же Mozilla например... но я это всё таки считаю извращением.

аргумент про интерфейс полностью дурацкий. Это не эксперименты на восьмерке, в десятке ничего подобного нет. Сам упарывался на 7 излишне долго, перешел на 10 LTSC и вообще не заметил никакой разницы кроме того, что ос перестала быть старой как говно мамонта. Когда вы наконец будете вынуждены сделать то же самое, и сами увидите, что почем зря столько времени долбались с семеркой. Кстати, 11 LTSC IoT точно так же абсолютно адекватная система, без заскоков по поддержке железа, свистелок и мусора. Если бы мне было не лень переустонавливать всё, я бы на неё давно перешел.

**Comment by k0zyrev** [comment]
> Хмм, спасибо, чтение не очень обнадеживающиее. Окончательного ответа я так и не заметил. Возможно проще поднять антизапрет на какой-нибудь малинке?

где-то на том форуме была более подробная инструкция от bolvan о том, каким образом можно накатить необходимое обновление на 7 из платных покетов обновлений и заставить работать драйвер, но я что-то не могу найти.

Да, и читайте мой коммент выше - LTSC версии современных ос - это всё та же семерка.

**Comment by kagalenko-m-b** [comment]
> Вы не представляете, сколько сложностей добавляете разрабам софта, 

Не мы добавляем, а бил гейц со своим "запланированным устареванием".

**Comment by kagalenko-m-b** [comment]
LTSC версии современных ос будут работать на thinkpad 15-летней давности?

**Comment by AKotov-dev** [comment]
Поскольку, вероятно, придётся ставить и на "другие" Win-7, пришлось установить следующие обновления (см. скриншот):

+ Windows6.1-KB3033929-x64.msu
+ Windows6.1-KB3162835-x64.msu
+ Windows6.1-KB3004394-v2-x64.msu
+ NDP472-KB4054530-x86-x64-AllOS-ENU.exe

![Snapshot_2024-08-21_00-52-42](https://github.com/user-attachments/assets/44709f49-47a5-43ce-9278-71c69b3c5398)

Скачать всё можно здесь: https://cloud.mail.ru/public/FWjd/JcimdHv95

**Comment by AKotov-dev** [comment]
@kagalenko-m-b 
Если решите перейти на Windows-10, то при желании можно попробовать вернуть к жизни `Cloudflare WARP` с помощью [WARPActivator](https://github.com/AKotov-dev/WARPActivator). Внутри используется `GoodbyeDPI` с расширенным списком; Apache-2.0 license вроде этого не запрещает. Хотя, кто её знает, нужно у **ValdikSS** узнать при случае.

**Comment by kagalenko-m-b** [comment]
>     * Windows6.1-KB3033929-x64.msu
>     * Windows6.1-KB3162835-x64.msu

Эти два обновления уже были усьановлены

>     * Windows6.1-KB3004394-v2-x64.msu

 Про это обновление было сообщение, что оно неприменимо к данному компьютеру

>     * NDP472-KB4054530-x86-x64-AllOS-ENU.exe

Это обновление установилось, но никак не повлияло на результат запуска `1_russia_blacklist_dnsredir` -- по-прежнему появляется сообщение о неверной подписи.

**Comment by AKotov-dev** [comment]
@kagalenko-m-b 
Осталось выяснить, какой у Вас Windows7 - x86 или x64? Установлен ли накопительный пакет SP1?

"...обновление неприменимо к данному компьютеру" часто возникало из-за разницы архитектур (x86/x64)

Если у Вас Win7 (x86), т.е. 32-бита: [Windows6.1-KB3004394-v2-x86.msu](https://download.microsoft.com/download/0/4/7/0473DB9B-16DE-41C6-A02A-4CBEEB04E777/Windows6.1-KB3004394-v2-x86.msu). Это важное обновление, связанное с корневыми сертификатами. [Дополнительная информация](https://djinn.ru/soft/certificate/).

У меня на vm вот это (Windows-7-Professional-SP1-x64):

![W7-SP1x64](https://github.com/user-attachments/assets/aeaafcc6-e979-4bae-98f2-4d726ecb5b64)

...и контроль UAC отключен

![UAC](https://github.com/user-attachments/assets/3576c4cb-bb9b-4709-b6a2-bcbadeb2298f)

...на этом пока всё.

**Comment by kagalenko-m-b** [comment]
> @kagalenko-m-b Осталось выяснить, какой у Вас Windows7 - x86 или x64? Установлен ли накопительный пакет SP1?

Windows домашняя базовая, SP1 установлен, 64 разрядная, UAC включен.

**Comment by AKotov-dev** [comment]
@kagalenko-m-b 
В той копии Win-7-HomeBasic-x64-SP1, которую мне удалось скачать, всё заработало сразу после установки изначально рекомендованного `Windows6.1-KB3033929-x64.msu` и перезагрузки (UAC отключен).

![s1](https://github.com/user-attachments/assets/8d9cb1e4-f4f2-4d95-b230-f083bb77169e)

**Comment by k0zyrev** [comment]
вот пошаговая инструкция https://ntc.party/t/zapret-whats-new/61/142

**Comment by kagalenko-m-b** [comment]
> вот пошаговая инструкция https://ntc.party/t/zapret-whats-new/61/142

Скрипт вот с [этой](http://www.bifido.net/tweaks-and-scripts/8-extended-security-updates-installer.html) страницы поставил ESU-обновления, после чего `1_russia_blacklist_dnsrёedir` запустился.

**Comment by ekungurov** [comment]
Можно поставить Windows 8.1 (я не знаю решает ли это проблемы с подписанными драйверами, не проверял). Да, меню пуск в этой версии не очень, но я какое-то время жил на ней, используя Windows + S вместо меню Пуск. 

Но это всё полумеры. Лучше поставить Windows 10, ибо семёрка и восьмёрка уже не поддерживаются вендором.

**Comment by kagalenko-m-b** [comment]
> Лучше поставить Windows 10, ибо семёрка и восьмёрка уже не поддерживаются вендором.

https://github.com/ValdikSS/GoodbyeDPI/issues/577#issuecomment-2299558114

**Comment by ekungurov** [comment]
@kagalenko-m-b если на SSD то да, будут работать хорошо. Если же HDD, то нужно выпиливать Defender, в LTSC не выпилен.

**Comment by ValdikSS** [comment]
Программа работает на полностью обновлённой Windows 7. Ничего дополнительно делать не нужно.

**Comment by MaximusPanin** [comment]
Поставил **Набор обновлений UpdatePack7R2 для Windows 7 SP1 и Server 2008 R2 SP1 22.2.10 [Multi/Ru]** с nnmclub и GoodbyeDPI заработал с заменой [windivert](https://reqrypt.org/download/) на 2.2.0-C. А вот _zapret-discord-youtube_ не хочет - по моему ошибка 216.

**Comment by r-agro-tel** [comment]
У меня всё запускается, но никакая конфигурация не работает.  В некоторых случаях просто не соединяется с youtube, а бывает что часть сайта/меню грузится и говорит, что нет интернета.  Хотя полгода назад неделю работало.  

Но с телефона на том же провайдере какой-то присланный мне apk работает.  Значит дело в настройках - как бы их с Андроид тел-на выцепить ?

PS Проверял наличие обновления KB3033929 - по версии ntoskrnl.exe 6.1.7601.2414 получается, что это обновление стоит.
