### ISSUE TITLE
Приложение не работает как сервис (сервис запускается и выполняется)

### ISSUE THREAD

**Issue by leglays** [ValdikSS/GoodbyeDPI#578]
### Operating system / операционная система

Windows 10 Pro 22H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

При установке приложения, как сервис через nssm или скрипт, служба запускается нормально, в службах windows она отображается и работает (см. скрин 1), однако youtube не загружается. При этом при запуске обычным способом (сперва скрипт 1_russia_blacklist, затем .exe файл) все работает нормально, проблема исключительно при установке службы.
Скрин настройки службы также прикладываю (см. скрин 2).

Скрин 1:
![image](https://github.com/user-attachments/assets/ae4ea352-8060-41f1-b9cb-6c5a1da7b454)

Скрин 2:
![image](https://github.com/user-attachments/assets/142015c8-846f-4857-9c2a-294de189c637)

**Comment by leglays** [comment]
Скрипт 1_russia_blacklist.cmd не правил, прикладываю скрин
![image](https://github.com/user-attachments/assets/235090d4-ca57-4274-be52-24e22e5f8af1)

**Comment by johnnyd-78** [comment]
@leglays При использовании только russia-blacklist.txt ютуб работать и не будет, для него существует отдельный блэклист russia-youtube.txt который тоже надо подключать.

При запуске службы [этот сайт](https://nnmclub.to/forum/) работает?

**Comment by leglays** [comment]
@johnnyd-78 странно, при запуске скрипта руками, который использует только russia-blacklist.txt youtube работает нормально (по крайней мере в самом скрипте указан только один блеклист), при этом служба отказывается работать с ютубом. Сайт по вашей ссылке работает. Можете подсказать где взять russia-youtube.txt?

**Comment by johnnyd-78** [comment]
@leglays В архиве [последней версии](https://github.com/ValdikSS/GoodbyeDPI/releases/tag/0.2.3rc1)

**Comment by leglays** [comment]
Всем спасибо за помощь, проблему решил. Для тех кто столкнется с похожей проблемой, вот решение:
1. Качаем последнюю версию (на текущий момент эта https://github.com/ValdikSS/GoodbyeDPI/releases/tag/0.2.3rc1)
2. Устанавливаем NSSM, если у вас не работает скрипт из архива (не забудьте прописать nssm.exe в системную переменную PATH)
3. Открываем PowerShell от имени админа и прописываем nssm install GoodbyeDPI. Откроется диалоговое окно, в котором указываем путь до goodbyedpi.exe, затем в arguments прописываем {-5 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt} (без скобок). Первый аргумент можете выбрать свой, сверяясь с таблицей отсюда https://github.com/ValdikSS/GoodbyeDPI и отсюда https://github.com/ValdikSS/GoodbyeDPI/issues/378
