### ISSUE TITLE
Не стартует

### ISSUE THREAD

**Issue by tihiygrom** [ValdikSS/GoodbyeDPI#58]
брал отсюда - https://github.com/ValdikSS/GoodbyeDPI/releases/download/0.1.4/goodbyedpi-0.1.4.zip

при запуске получаю вот это
https://gyazo.com/106830628001dbb80da8f8fc69d1cedc

Win7 x64 в тестовом режиме без проверки цифровых подписей

**Comment by ValdikSS** [comment]
На дворе 2018 год, а не 2014. Обновите вашу систему хотя бы до состояния 2015 года.

https://docs.microsoft.com/en-us/security-updates/SecurityAdvisories/2015/3033929

**ВНИМАНИЕ!** Если вы видите эту ошибку на Windows 7, это значит, что ваша система крайне устарела, и НЕ ДОЛЖНА ИСПОЛЬЗОВАТЬСЯ ДЛЯ ДОСТУПА В ИНТЕРНЕТ!
Скорее всего, у вас не установлены заплатки безопасности, и любой человек в вашей локальной сети или публичном Wi-Fi может получить полный доступ к вашему компьютеру и прогрузить вирусы (уязвимости MS17-010 и другие).

Установите обновления безопасности НЕМЕДЛЕННО.
