### ISSUE TITLE
Прессет только для ютуба

### ISSUE THREAD

**Issue by Ananim353** [ValdikSS/GoodbyeDPI#582]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Лично у меня good bye dpi очень плохо работает со многими приложениями(discord как пример) или рандомными сайтами. Было бы хорошо ввести отдельнай режим только для ютуба. Вроде это можно сделать и самому(Но я аутист)

**Comment by lesharodin** [comment]
Удали из .cmd файла `--blacklist ..\russia-blacklist.txt` и тогда останется только ютуб..

**Comment by SUGHuser** [comment]
Вообще при ключе --blacklist всё то что не входит в чёрный список проходит напрямую без фрагментации )  , а плохо работают сайты как я уже говорил в другой теме из-за --wrong-seq , по-умолчанию GoodbyeDPI стартует так :
 -9          -f 2 -e 2 --wrong-seq --wrong-chksum --reverse-frag --max-payload -q (this is the default)
если её подправить таким способом : 
-f 2 -e 2 --wrong-chksum --reverse-frag --max-payload -q 
то в большинстве случапев проблем с сайтами нет

**Comment by d1mulka** [comment]
Здравствуйте как добавлять другие сайты например инсту или тикток
