### ISSUE TITLE
please add Tizen ! 

### ISSUE THREAD

**Issue by olegaix** [ValdikSS/GoodbyeDPI#583]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

if your goodbyeDPI could run on Tizen for samsung it would make such a big difference) 
or if it would be possible for us to use goodbyedpi and share connection to TV from computer .... (as it is only computer youtube works and TV is not:(

**Comment by krlvm** [comment]
С учётом того, что настроить прокси в Tizen нельзя, единственной опцией остаётся поднятие на компьютере в локальной сети, на котором запущено средство обхода блокировок, HTTP-сервера, прозрачно проксирующего запросы к YouTube, и подключение к нему через браузер

**Comment by ValdikSS** [comment]
GoodbyeDPI is a Windows software.

**Comment by ValdikSS** [comment]
Например, так
https://ntc.party/t/обход-блокировки-youtube-для-любых-smart-tv-с-goodbyedpi-v2ray-maradns/9415

**Comment by olegaix** [comment]
ValdikSS спасибо огромное только вот сервера (ntc.party)  больше нет или его закрыли( v2ray-maradns.7z если у кого то есть выложите пожста!

**Comment by Quake4Life** [comment]
Ты просто спаситель.
