### ISSUE TITLE
GoodbyeDPI не фиксит работу YouTube полностью. Вот 3 случая, которые не пофиксил ещё никто.

### ISSUE THREAD

**Issue by RaptorT1V** [ValdikSS/GoodbyeDPI#584]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

     Я установил GoodbyeDPI, но это **не решило мою проблему**

У меня YouTube, иногда работает и без VPN. Когда как, в общем. 
Но есть 3 случая, когда видео перестаёт грузиться нормально и замораживается навечно. И эти случаи возникают **вне зависимости** от того: включен ли VPN, установлен ли GoodbyeDPI...

  1) Добавление видосов в очередь / Создание плейлиста
  2) Открытие видео в полный экран
  3) Просмотр видео, длиною более 45 минут

          Во всех этих 3 случаях происходит следующее:
-- Если были включены субтитры, они больше не продвигаются дальше с видео;
-- Таймлайн видео замораживается;
-- Изменить качество или скорость видео не представляется возможным;
-- Само видео вскоре перестаёт загружаться;
-- При попытке выйти из полноэкранного режима (если ты в него зашёл) видео возвращается лишь наполовину. И после этого нельзя было уже ни на что нажать;
-- При закрытии вкладки сочетанием Ctrl + W нужно ещё 5 секунд подождать, пока она закроется.

       Что происходит "под капотом"?
Как только создаётся очередь или видео открывается в полный экран, оно перестаёт загружаться нормально (скорость стремительно падает в 0).
Судя по диспетчеру задач, вкладка с Ютубом, на которой произошёл "случай", начинает в геометрической прогрессии жрать всё больше и больше видеопамяти... доходило даже до 7 тысяч MB

![image](https://github.com/user-attachments/assets/f524899e-0456-4ade-a026-85d9fb3b525d)

Это пока не фиксится ничем! Просто нужно обходить стороной все эти действия.
Но большие видосы, которые длятся больше 45 минут, теперь я не могу смотреть(

UPD:  Я смотрю YouTube уже лет 10 как. За это время НИ РАЗУ с чем-то подобным не сталкивался

**Comment by Amegatron** [comment]
Если это происходит даже с VPN, то GoodbyeDPI тут точно не при чем. Какой-то баг либо с самим YT (что вряд ли), либо с Хромом. Вполне может быть из-за каких-нибудь расширений. Может быть это связано с блокировщиком рекламы (еще до блокировок, YT иногда начинал сильно тупить при включенном блокировщике рекламы типа AdBlock). Может, у тебя какие-то еще расширения имеются, которые потенциально приводят к такому результату.

**Comment by RaptorT1V** [comment]
> Может, у тебя какие-то еще расширения имеются, которые потенциально приводят к такому результату.

Да, ты абсолютно прав! Я только что нашёл решение этой проблемы и побежал сюда, чтобы о нём рассказать! 
Это issue можно закрывать! Всё дело в расширении _Return YouTube Dislike_. 
И, знаете, даже **не нужно удалять это расширение полностью**, ведь тут дело не в самом расширении, а в одной его особенности, которая обнаружила себя лишь с августа: **если у вас стоит масштаб 150%**, то тогда вашей вкладке копец. Но стоит лишь изменить масштаб на 125% или 100%, то всё приходит в норму! Ура!

**Comment by MiTereKun** [comment]
где-то 10 лет назад ютуб скатился, отменили красивый дизайн каналов и стал приходить наш телевизор. (я это не серьёзно конечно)

`Просмотр видео, длиною более 45 минут`
100% и 3-х часовые видео работают с программой. Недавно по быстрому (с перемоткой) посмотрел как мистр бист считает до 100 000 просто для понимания (лучше чем "сутки режу воду") - всё ок, а ролик 23 часа+
Но обычно такое не смотрю, это как 1 из границ человеческой сущности, сделать самое самое

ВПН купить прям рекомендую даже не смотря, что есть эта программа Gdip (но не заблокированные протоколы), бесплатные вас и будут так негласно слать с большими запросами трафика. А напрямую из рф не работает даже французский сайт где писали о Дурове (хотя его нет в списке запрещённых РКН) - https://www.tf1info.fr/justice-faits-divers/info-tf1-lci-le-fondateur-et-pdg-de-la-messagerie-cryptee-telegram-interpelle-en-france-2316072.html

Следите за версией браузера. Ну и можно подумать о более сильном компьютере, тяжёлого js будет с каждым годом только больше, 7 ГБ ерунда сейчас
