### ISSUE TITLE
Не работает Parsec

### ISSUE THREAD

**Issue by kirillall** [ValdikSS/GoodbyeDPI#589]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Приветсттвую! При запуске одного из режимов, которые cmd, parsec тут же теряет связь. Добавление адреса parsec.app не решает. Как я понимаю, парсек ломится на конкретные ip, но blacklist не принимает ip формат, и как быть?

**Comment by ValdikSS** [comment]
> При запуске одного из режимов, которые cmd

Какого?

**Comment by kirillall** [comment]
> > При запуске одного из режимов, которые cmd
> 
> Какого?

Любого из этих, 1_russia_blacklist.cmd, 1_russia_blacklist_dnsredir, 2_any_country.cmd, 2_any_country_dnsredir.cmd.

**Comment by ValdikSS** [comment]
Запишите дамп трафика, без фильтров.
https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by ValdikSS** [comment]
> Да, добавлял домен в блэклист, было, что он не работал, при запущенном DPI. Сейчас проверил - работает.
> Если так, прошу прощения, что ввёл в заблуждение и благодарю за помощь, и уделённое время!
