### ISSUE TITLE
МТС М/О - "Ошибка при установлении защищённого соединения" 

### ISSUE THREAD

**Issue by Demos25** [ValdikSS/GoodbyeDPI#59]
Начиная с 16 февраля сайты из чёрного списка выдают "Ошибка при установлении защищённого соединения", независимо от режима goodbyedpi
Кажись, прикрыли лавочку.

**Comment by ValdikSS** [comment]
https://nnm-club.me/forum/viewtopic.php?p=9516088#9516088

**Comment by Demos25** [comment]
Ясненько.

**Comment by Demos25** [comment]
На всякий случай оставляю свой результат проверки blockcheck-0.0.9.6:
[⚠] Ваш провайдер полностью блокирует доступ к HTTPS-сайтам из реестра.
[⚠] У вашего провайдера "обычный" DPI. Вам поможет HTTPS/Socks прокси, VPN или Tor.

Хотя, наверно, и так всё ясно. 

Настроил ФФ на использование https://antizapret.prostovpn.org/proxy.pac
В качестве альтернативы на ближайшее время.

**Comment by Kuroyuki1** [comment]
Мм, тоже само от того же самого провайдера. 
Хотя интересный факт, на http://danbooru.donmai.us/ пускает спокойно, а на тот же рутрекер и т.д нет.

Жду фикса, если он вообще возможен.

**Comment by ValdikSS** [comment]
>Жду фикса, если он вообще возможен.

Поэкспериментируйте с параметром -e. Попробуйте установить его в значения от 1 до 40.

**Comment by Kuroyuki1** [comment]
Попробовал, всё так же вечно продолжает загружать.

**Comment by Kuroyuki1** [comment]
С данными(startup=goodbyedpi.exe  -p -r -s -f 2 -k 2 -n -e 40) параметрами пропускает.

**Comment by Kuroyuki1** [comment]
Никак не хочет пропускать, да, пробовал менять флаги и ставить очень не очевидные значения.

**Comment by ValdikSS** [comment]
Попробуйте использовать только -e 40, без остальных параметров, и тестируйте только на HTTPS-сайтах, желательно на нескольких, чтобы исключить блокировку по IP-адресу.
Если есть возможность, потестируйте диапазон значений от 1 до 40, чтобы понимать, что конкретно предпринял ваш провайдер.

**Comment by Kuroyuki1** [comment]
Абсолютно ничего, всё такая же вечная загрузка. Тестировал на HTTPS сайтах.

**Comment by ValdikSS** [comment]
А без GoodbyeDPI что происходит? Вечная загрузка, или разрыв соединения, или что-то другое?
Пожалуйста, предоставьте дампы pcap. Нужно:

1. Скачать и установить [Wireshark](https://www.wireshark.org/). Нужна полная версия, портативная не подойдет.
2. Определить адрес блокируемого сайта командой `nslookup [адрес сайта]`. Выполнять из-под командной строки.
3. Выбрать сетевой интерфейс, ввести в поле "…using this filter" строку вида:
`host [IP-адрес]`
4. Если адресов несколько, нужно объединить их словом "or":
`host [IP-адрес 1] or [IP-адрес 2]`
После чего нажать enter, чтобы запустить захват трафика.
5. Зайти на заблокированный сайт по HTTPS.
6. Остановить захват трафика кнопкой с иконкой красного квадрата на панели. Нажать file → save as, сохранить в файл.
7. Отправить мне на iam@valdikss.org.ru

Проделать это дважды, с запущенным GoodbyeDPI и без.

**Comment by Kuroyuki1** [comment]
Как бы всё это было не печально, но у меня не видит интерфейсы, просто весит в not found и всё. Советы из интернета конечно же не помогли.

**Comment by ValdikSS** [comment]
Вы точно установили winpcap, и скачали инсталлятор, а не портативную версию?
Запускать нужно от имени администратора. Может еще помочь вот это: https://osqa-ask.wireshark.org/questions/12192/usb-to-ethernet-adapter-doesnt-show-under-interfaces

**Comment by Kuroyuki1** [comment]
Хм, что-то пошло не так, неизвестно что, но банальная установка помогла, хотя до этого и ставил winpcap и не портатив. Файлы отправил.

**Comment by Demos25** [comment]
@ValdikSS при использовании -e 40 у меня выскакивает новый, доселе невиданный вид заглушки на http сайтах, https не грузит.

**Comment by ValdikSS** [comment]
Если кто-то может предоставить VPN или SSH к интернет-каналу, где HTTPS-сайты перестали открываться, напишите мне.

**Comment by ValdikSS** [comment]
Исправлено функцией fake packet в 2019.
