### ISSUE TITLE
Videos accessed via a link do not load well

### ISSUE THREAD

**Issue by IInjector** [ValdikSS/GoodbyeDPI#591]
### Operating system / операционная система

Win10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Videos that are accessible via a link and uploaded to YouTube by me load very poorly, no matter how I use the program.
//
Видео, c доступом по ссылке загруженные мной на YouTube, при просмотре грузятся очень плохо, как будто бы я не пользуюсь программой, при том, что остальной сайт ютуб работает идеально.

**Comment by SUGHuser** [comment]
Имеете ввиду что если смотрите видео других авторов то они работают нормально ,  а конкретно загруженные на ютуб ваши тормозят ?

**Comment by IInjector** [comment]
> Имеете ввиду что если смотрите видео других авторов то они работают нормально , а конкретно загруженные на ютуб ваши тормозят ?

да, именно которые с доступом по ссылке, открытые видосы норм грузит

**Comment by Slamifoe21** [comment]
> да, именно которые с доступом по ссылке, открытые видосы норм грузит

нет такой проблемы. Попробуй поэксперементировать с опциями программы
