### ISSUE TITLE
Не открываются доски Форчана

### ISSUE THREAD

**Issue by garzovic** [ValdikSS/GoodbyeDPI#592]
### Operating system / операционная система

Windows `11

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Сам сайт открывается, но доски, например, pol, не открываются, возникает следующая ошибка:

### Additional information / Дополнительная информация

Сам сайт открывается, но доски, например, pol, не открываются, возникает следующая ошибка:

Ошибка при установлении защищённого соединения

При соединении с boards.4chan.org произошла ошибка. SSL получило искажённое сообщение рукопожатия «Приветствие сервера».

Код ошибки: SSL_ERROR_RX_MALFORMED_SERVER_HELLO

    Страница, которую вы пытаетесь просмотреть, не может быть отображена, так как достоверность полученных данных не может быть проверена.
    Пожалуйста, свяжитесь с владельцами веб-сайта и сообщите им об этой проблеме

**Comment by Tail870** [comment]
Каким образом запускаете программу GoodbyeDPI?
Если устанавливали сервис, то попробуйте запуск не службой.

**Comment by garzovic** [comment]
>Открываются ли другие сайты (в т.ч. "сломанные")?
Ютуб да, насчёт остальных -- Фейсбук начал открываться.

**Comment by garzovic** [comment]
> Попробуйте во время работы программы программы скрипт 0_russia_update_blacklist_file. После этого перезапустите GoodbyeDPI и браузер (именно в таком порядке). Если не поможет - выполните команду: ipconfig /flushdns
> 
> _Ну и последний ультимативный вариант - перезагрузить ПК..._

Сделал всё по инструкции, не помогло.

**Comment by garzovic** [comment]
Установил в about:config это
security.tls.version.max на 3
security.tls.hello_downgrade_check на false
security.osclientcerts.autoload на true
И всё заработало.

**Comment by garzovic** [comment]
Установил в about:config это
security.tls.version.max на 3
security.tls.hello_downgrade_check на false
security.osclientcerts.autoload на true
И всё заработало.
