### ISSUE TITLE
Потеря пакетов

### ISSUE THREAD

**Issue by Dum0sss** [ValdikSS/GoodbyeDPI#593]
### Operating system / операционная система

windows 10 22h2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

картинка застывает но звук идет или видео не прогружается совсем, помогает обновление страницы на время. 

### Additional information / Дополнительная информация

выглядит как потеря пакетов, или недостаток пропускной способности

**Comment by ValdikSS** [comment]
Если вы действительно испытываете что-то похожее на потерю пакетов, то см. #236, #554.
