### ISSUE TITLE
Майнер? Серьёзно? 

### ISSUE THREAD

**Issue by trn7** [ValdikSS/GoodbyeDPI#594]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Как теперь твой червь вычистить из системы? 
![Screenshot_2](https://github.com/user-attachments/assets/4a129765-fff8-43e2-9bfa-397064ce4144)

**Comment by xtclovver** [comment]
Ты преждем чем такое писать прочитал как работает эта програма и что такое reqrypt

**Comment by xtclovver** [comment]
"Программа загружает драйвер WinDivert, который использует Windows Filtering Platform для установки фильтров и перенаправления пакетов в пользовательское пространство. Она работает, пока видно консольное окно, и завершается, когда вы закрываете окно."

**Comment by trn7** [comment]
> "Программа загружает драйвер WinDivert, который использует Windows Filtering Platform для установки фильтров и перенаправления пакетов в пользовательское пространство. Она работает, пока видно консольное окно, и завершается, когда вы закрываете окно."

Нет, не завершается. И не закрывается просто так процесс.

**Comment by xtclovver** [comment]
Ты какой файл открывал? service_install_russia_blacklist.cmd?

**Comment by xtclovver** [comment]
WinDiver используется для захвата пакетов и их модификации. Чем и занимается эта программа. Она модефецирует пакеты для того, чтобы запутать DPI

**Comment by johnnyd-78** [comment]
> завершается, когда вы закрываете окно

Это не правда. Драйвер висит в памяти до перезагрузки компа. Именно поэтому файл sys и нельзя удалить. Ну и конечно автору WinDivert огромная "благодарность" за кошелек для донатов в **описании** этого sys который у альтернативно одаренных типа автора этого поста вызывает жгучее желание обмайнерить автора )) Они даже не знают, что биткоин накомпах уж лет 10 как не майнится и даже нет таких инструментов, но им то что - они же УНИКАЛЬНЫЕ, единственные кто нашел! Да нет, ребята, вы не уникальные - таких тут и на других платформах уже целый зоопарк собрался ;)

**Comment by johnnyd-78** [comment]
Ой, майнир, спосите-памигити!1!1!1
![изображение](https://github.com/user-attachments/assets/a4079088-2fd3-4c56-a9ff-2f25955b7692)

Извините )

**Comment by opiums9** [comment]
https://www.virustotal.com/gui/file/e3ff0de76a44978ebd02b890f66be6f3f4320c99f8b443de1877d4e16a4a5443
Мало ли, вдруг кому пригодится, никакими майнерами там даже не пахнет. Программа вообще не нагружает систему.

**Comment by AKotov-dev** [comment]
На всякий случай добавил `sc stop WinDivert` в [WARPActivator](https://github.com/AKotov-dev/WARPActivator); подальше от греха т.с. Спасибо.

p.s. если вылезет ещё что-нибудь подозрительное, сообщите пожалуйста...

**Comment by marlynka** [comment]
И как такие люди смогли зарегаться вообще на GitHub... Ах да, расхайпили утилиту, так сразу всякие непонятные личности приходят написывать тут.

**Comment by bsun0000** [comment]
Да, майнер, майнер. С цифровой подписью от "Microsoft Windows Hardware Compatibility Publisher". Сам Билл майнит копеечку у тебя на пекарне! Вот откуда у него бабок столько.

**Comment by meJevin** [comment]
@marlynka зарегаться в любой современной соц сети сложнее, чем в тут) не налетайте на ребят
@johnnyd-78 спасибо за развернутый ответ! все верно.

**Comment by DmitriyPekar** [comment]
Если ты доверяешь своему антивирусу то доверяй и дальше, просто не используй программу и не нужно делать очередную тему про майнер, уже не смешно.

**Comment by johnnyd-78** [comment]
Странный какой-то "майнер", ага. Видюху не греет (у меня при повышении температуры меняется цвет подсветки и я это вижу), согласно виджету AllCPUMeter никакой особой загрузки проца нет... На чем он биткоины майнит, на вентиляторе, что ли или блоке питания? ;D
