### ISSUE TITLE
Заменить предупреждение о необходимости запуска с правами администратора на запрос прав администратора.

### ISSUE THREAD

**Issue by Zapzatron** [ValdikSS/GoodbyeDPI#595]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Добавить запрос прав администратора в `service_install_russia_blacklist.cmd`, `service_install_russia_blacklist_dnsredir.cmd`, `service_remove.cmd`

Заменить предупреждение о необходимости запуска с правами администратора на запрос прав администратора.

Поменять
```
echo This script should be run with administrator privileges.
echo Right click - run as administrator.
echo Press any key if you're running it as administrator.
pause
```
На
```
if not "%1"=="am_admin" (powershell start -verb runas '%0' am_admin & exit /b)
```

**Comment by ValdikSS** [comment]
#460
