### ISSUE TITLE
Windows2019 + 2 Ethernet + GoodbyeDPI = router?

### ISSUE THREAD

**Issue by chelaxian** [ValdikSS/GoodbyeDPI#596]
### Operating system / операционная система

Windows Server 2019 Core

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

**[English in next comment]**

Установил полноценную оригинальную версию Windows Server 2019 в редакции Standard Core (no GUI).

Настроил 2 сетевых адаптера:
LAN - 10.11.x.x
WAN - 10.12.x.x

Включил в windows режим роутера - IPEnableRouter=1

Настроил Source NAT для маскардинга транзитного трафика из LAN в WAN

Перенаправил трафик своего ПК через этот Windows Server 2019 Core

Без запуска GoodbyeDPI всё работает как обычно (трафик ходит, но запрещенные ресурсы не открываются)
После запуска GoodbyeDPI на ПК ломается веб. пинги ходят, но сайты не открываются.

Локально пробовал с аналогичных ВМ с GUI (Winows 10/11)- c локально запущенным GoodbyeDPI блокировки обходятся. 

========================

Как использовать ВМ/ПК на Windows с несколькими сетевыми интерфейсами с установленным GoodbyeDPI в качестве роутера для обработки трафика с других хопов в локальной сети?

Возможно TTL где-то на 1 хоп нужно увеличить? А если у меня несколько промежуточных роутеров между моим ПК и этой ВМ - на их количество увеличивать? Или не в этом дело?

<img width="823" alt="image_2024-08-28_20-53-07" src="https://github.com/user-attachments/assets/ae36c298-2bfd-43fd-a8a2-7a68923183b7">

**Comment by johnnyd-78** [comment]
@chelaxian Думаю, ваша ситуация похожа на [мою](https://github.com/ValdikSS/GoodbyeDPI/issues/569#issuecomment-2311473748). Подозреваю, что и причина та же

**Comment by johnnyd-78** [comment]
> То есть на 0.2.1 все работает?

У меня - да. Но вот будет ли у вас на этой версии корректно обходиться DPI вашего провайдера - это вопрос.

**Comment by ValdikSS** [comment]
Давайте сюда #436

**Comment by ValdikSS** [comment]
Если вы хотите обрабатывать транзитный трафик, вам нужен linux + zapret.
