### ISSUE TITLE
Ютуб нет подключения к интернету

### ISSUE THREAD

**Issue by demoteLTF** [ValdikSS/GoodbyeDPI#597]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Утром ещё более менее работало, но почему-то сейчас, когда я запустил goodbyedpi, ютуб выдаёт мне это
![2024-08-30_17-36-16](https://github.com/user-attachments/assets/754476d4-ba6e-4eb8-98cd-389fbaf2f98c)

**Comment by kirakiradesu** [comment]
Тоже самое, перезагрузка помогает, но после времени простоя, возможно из за сна, так получается. Раньше такого не было.

**Comment by Lol-Slava** [comment]
У меня такая же проблема... 
есть конечно решение но это лютый костыль
нужно поменять днс сервер в браузере 
если брать яндекс браузер то там менять на "cleanbrowsing family filter" но на ютубе будет "детский режим" и очень много видео будет не доступно.
Наверное можно использовать другой днс сервер но его нужно еще найти.

**Comment by MiTereKun** [comment]
@demoteLTF - https://github.com/ValdikSS/GoodbyeDPI/issues/598#issuecomment-2322660003

**Comment by Stason2222** [comment]
Внезапно перестал работать ютуб, пишет нет подключения к сети. Не работает ни на телевизоре, ни в смартфоне
