### ISSUE TITLE
YouTube работает на половину

### ISSUE THREAD

**Issue by F1lterEr** [ValdikSS/GoodbyeDPI#598]
### Operating system / операционная система

Windows 10 21H1

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Одни видео открываются мгновенно и все работает, другие вообще не грузит (черное окно с прогрузкой (ни через пару секунд, ни через минуту не прогружает)).

Проверил соединения в консоли разработчика в Networks для запрета серверов GGC и добавил их в hosts, но не помогло (все равно к ним обращается).
Все видео он грузит с одних и тех же серверов.

В Яндексе совсем не работает (бесконечная загрузка сайта), в Microsoft Edge такая же ситуация.

### Additional information / Дополнительная информация

Провайдер: Ростелеком
Браузер: Opera GX
Сервера:
rr1---sn-gvnuxaxjvh-2x1e.googlevideo.com
rr2---sn-gvnuxaxjvh-2x1e.googlevideo.com
rr6---sn-gvnuxaxjvh-bvwz.googlevideo.com
rr7---sn-gvnuxaxjvh-bvwz.googlevideo.com
Работают попарно (rr1 с rr7 и rr2 с rr6)
В тех видео, что он не может загрузить пишет в причине ошибки (ERR_CONNECTION_REFUSED).

**Comment by johnnyd-78** [comment]
В "обычный способ" запуска вносились изменения?
Kyber отключен?

**Comment by F1lterEr** [comment]
> В "обычный способ" запуска вносились изменения? Kyber отключен?

Да, после стандартного способа пробовал и через -5 -e1 -q --blacklist и через -6 -e1 -q --blacklist в параметрах запускать, итоговый результат тот же.
Kyber отключен

**Comment by johnnyd-78** [comment]
А если так?
goodbyedpi.exe -e 1 -r -m --reverse-frag --blacklist russia... --blacklist youtube...

**Comment by F1lterEr** [comment]
> goodbyedpi.exe -e 1 -r -m --reverse-frag --blacklist russia... --blacklist youtube...

Не помогло

**Comment by F1lterEr** [comment]
> В hosts как добавляли?

Через блокнот в конце добавил эти строчки
127.0.0.1 rr1---sn-gvnuxaxjvh-2x1e.googlevideo.com
127.0.0.1 rr2---sn-gvnuxaxjvh-2x1e.googlevideo.com
127.0.0.1 rr6---sn-gvnuxaxjvh-bvwz.googlevideo.com
127.0.0.1 rr7---sn-gvnuxaxjvh-bvwz.googlevideo.com

**Comment by johnnyd-78** [comment]
Смените 127.0.0.1 на 0.0.0.0

**Comment by F1lterEr** [comment]
> Смените 127.0.0.1 на 0.0.0.0

Не помогло

**Comment by johnnyd-78** [comment]
И на всякий... Если QUIC в браузере отключен - включите обратно

**Comment by johnnyd-78** [comment]
Покажите окно программы (на всякий случай), она у вас работает вообще?

**Comment by F1lterEr** [comment]
> И на всякий... Если QUIC в браузере отключен - включите обратно

Никаких изменений

**Comment by F1lterEr** [comment]
> Покажите окно программы (на всякий случай), она у вас работает вообще?

![image](https://github.com/user-attachments/assets/2813afd2-636a-4128-98ed-8e712a9d8b32)

**Comment by johnnyd-78** [comment]
Так у вас из ютубовского блэклиста не грузится ничего ) Что у вас там?

**Comment by F1lterEr** [comment]
> Так у вас из ютубовского блэклиста не грузится ничего ) Что у вас там?

youtube.com
youtu.be
googlevideo.com
ytimg.com

**Comment by johnnyd-78** [comment]
Попробуйте этот
[russia-youtube.txt](https://github.com/user-attachments/files/16821789/russia-youtube.txt)

**Comment by F1lterEr** [comment]
> Попробуйте этот [russia-youtube.txt](https://github.com/user-attachments/files/16821789/russia-youtube.txt)

![image](https://github.com/user-attachments/assets/18b5acb8-5ed0-49a4-a44e-6862b627971e)
Видео так же не грузится

**Comment by johnnyd-78** [comment]
Фигня какая-то должно быть так: Loaded 24 hosts...

**Comment by MiTereKun** [comment]
@F1lterEr 30 августа действительно много обращений, особенно с провайдера ГМТС и МТС.
Минимум 11 тем обновилась, читайте https://ntc.party/c/community-software/goodbyedpi/8 (это форум самого ValdikSS)

https://ntc.party/t/%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D1%82%D0%B0%D0%BB-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D1%82%D1%8C-%D0%BF%D0%BB%D0%B5%D0%B5%D1%80-youtube-%D0%BF%D0%BE%D0%BC%D0%BE%D0%B3%D0%B8%D1%82%D0%B5-%D1%87%D0%B0%D0%B9%D0%BD%D0%B8%D0%BA%D1%83/9905

**Comment by lllyx1** [comment]
мне помогло выключение кубера
и такой конфиг
start "" goodbyedpi.exe -5 -e1 -q --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
