### ISSUE TITLE
Система зависает при воспроизвидении потокового видео

### ISSUE THREAD

**Issue by nxrighthere** [ValdikSS/GoodbyeDPI#6]
Это происходит когда открыта страничка со стримом на Twitch, реже это происходит на Youtube. Через некоторое время (примерно после часа просмотра), система зависает с зацикленным звуком. Для примера, словил фриз сегодня на этом канале https://www.twitch.tv/twitch

**Comment by ValdikSS** [comment]
Попробуйте c WinDivert 1.2.0, собранным в VS. Нужно скопировать с заменой файлы WinDivert.dll и WinDivert[32/64].sys из соответствующей папки следующего архива:
https://reqrypt.org/download/WinDivert-1.2.0-rc-MSVC.zip

**Comment by nxrighthere** [comment]
С этой версией сайты не загружаются несмотря на то, что соединение установлено.

**Comment by ValdikSS** [comment]
Что вы имеете в виду? Соединение с чем установлено? Только что проверил, у меня работает.
Попробуйте перезагрузиться.

**Comment by nxrighthere** [comment]
![Firefox](https://s18.postimg.org/6968c8zw9/scrn.png)
Перезагрузка не помогла. Пробовал и 32 и 64 разрядные версии.

**Comment by ValdikSS** [comment]
Посмотрите трафик в Wireshark, что-нибудь красное есть?

**Comment by nxrighthere** [comment]
![Wireshark](https://s15.postimg.org/4ilymtx63/image.png)
![Wireshark](https://s17.postimg.org/ye5bae7zz/fs2.png)

**Comment by nxrighthere** [comment]
Прошу прощения, проблема с фризами по итогу оказалась в Firefox...
