### ISSUE TITLE
Goodbye DPI перестала работать в google chrome

### ISSUE THREAD

**Issue by Roodweell** [ValdikSS/GoodbyeDPI#600]
### Operating system / операционная система

Windows 10 19045

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Goodbye DPI перестала работать в google chrome. Я так понимаю, после обновления, т.к. у моего друга ровно такая же история произошла в одно время. В Opera всё работает хорошо. Kyber и Quic отключены, была версия 0.2.2, пробовал обновить до актуальной, всё так же. Подскажите, связано ли это с обновлением хрома и есть ли советы как можно решить? 

UPD: выяснилось, что проблема в провайдере скайнет, у многих такая же ситуация с 30го августа. Пока что конкретного решения не нашёл, как только найду -- отпишу в эту ветку

**Comment by johnnyd-78** [comment]
ОБновился. Версия 128.0.6613.114 (Официальная сборка), (64 бит) Как работало так и работает.

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by sergx** [comment]
У меня странным образом в chrome (инкогнито тоже) не открывается instagram, в то время как другие заблокированные - открываются. При этом в соседнем firefox instagram открывается нормально

**Comment by vysmirnov** [comment]
У меня так же несколько дней назад начало глючить. Вот сейчас нашел эту тему - попробовал edge. Отрубил в нем флаги - скорость соединения десятки мбит, на хроме было 2 мбит и то с трудом пробивались.  Посмотрел после в хроме: стало тоже десятки мбит. Но! У меня скайнет, это у них такая хрень. На ростелекоме такого не было. Я им в поддержку написал, мол "Выслуживаетесь перед РКН доп. мерами? Может мне свалить от вас?". Ответили, что "не у нас проблема". Но скорость таки вернулась. Так что хз, что из этого подействовало: флаги или "не прокатило".

**Comment by vysmirnov** [comment]
А какой провайдер? У меня скайнет и тоже последние дни работает раз через 10. В статистике скорость соединения то иногда 90мбит держится, то чаще всего ~2 мбит, то иногда падает до 100-300 кбит (редко). При этом сам прием пакетов не происходит, потом может просраться и видео дальше идет с переменным успехом в зависимости от скорости соединения. Режимы менял - не помогает, отключал службу что-то разницы не заметил. Примерно одинаково что в хроме, что в edge, что в огнелисе. Длинные видео как будто получше грузит, которые закодированы кодеком av1. VP9 дропается в 2 мбит.
И похоже, самая печаль в получении первого пакета видео с заголовком, видимо и сопутствующей инфой.
Возможно, есть разница в том, откуда тянется видео: с "устаревших" серверов в рф или из-за бугра.

**Comment by ziggerd** [comment]
> А какой провайдер? У меня скайнет и тоже последние дни работает раз через 10. В статистике скорость соединения то иногда 90мбит держится, то чаще всего ~2 мбит, то иногда падает до 100-300 кбит (редко). При этом сам прием пакетов не происходит, потом может просраться и видео дальше идет с переменным успехом в зависимости от скорости соединения. Режимы менял - не помогает, отключал службу - что-то разницы не заметил. Примерно одинаково что в хроме, что в edge, что в огнелисе. Длинные видео как будто получше грузит, которые закодированы кодеком av1. VP9 дропается в 2 мбит. И похоже, самая печаль в получении первого пакета видео с заголовком, видимо и сопутствующей инфой. Возможно, есть разница в том, откуда тянется видео: с "устаревших" серверов в рф или из-за бугра.

У меня тоже скайнет и позавчера ютуб на половину умер. Не знаю что происходит. только заметил, что когда в network появляются обращения к забугорным каноник гугл сервакам например `rr1.sn-axq7sn76.googlevideo.com` сразу всё ломается, только после нескольких перезагрузок страницы начинает грузится, сначала медленно и немного, потом лучше, потом всё видео работет нормально и скорость более-менее, goodbyedpi ни на что не влияет по сути, кодек и длительность видео тоже

**Comment by Roodweell** [comment]
> А какой провайдер? У меня скайнет и тоже последние дни работает раз через 10. В статистике скорость соединения то иногда 90мбит держится, то чаще всего ~2 мбит, то иногда падает до 100-300 кбит (редко). При этом сам прием пакетов не происходит, потом может просраться и видео дальше идет с переменным успехом в зависимости от скорости соединения. Режимы менял - не помогает, отключал службу - что-то разницы не заметил. Примерно одинаково что в хроме, что в edge, что в огнелисе. Длинные видео как будто получше грузит, которые закодированы кодеком av1. VP9 дропается в 2 мбит. И похоже, самая печаль в получении первого пакета видео с заголовком, видимо и сопутствующей инфой. Возможно, есть разница в том, откуда тянется видео: с "устаревших" серверов в рф или из-за бугра.

Кстати да, у меня тоже скайнет.. И позже заметил, что действительно не имеет значения, какой браузер, иногда загрузит, иногда нет. Есть ли идеи по поводу решения?

**Comment by LafosHaas** [comment]
Подтверждаю, в Chrome проблема, в Firefox все работает отлично. Проблема только с ютубом, остальные сайты работают идеально.
Версия 128.0.6613.114 (Официальная сборка), (64 бит)

**Comment by vysmirnov** [comment]
> > А какой провайдер? У меня скайнет и тоже последние дни работает раз через 10. В статистике скорость соединения то иногда 90мбит держится, то чаще всего ~2 мбит, то иногда падает до 100-300 кбит (редко). При этом сам прием пакетов не происходит, потом может просраться и видео дальше идет с переменным успехом в зависимости от скорости соединения. Режимы менял - не помогает, отключал службу - что-то разницы не заметил. Примерно одинаково что в хроме, что в edge, что в огнелисе. Длинные видео как будто получше грузит, которые закодированы кодеком av1. VP9 дропается в 2 мбит. И похоже, самая печаль в получении первого пакета видео с заголовком, видимо и сопутствующей инфой. Возможно, есть разница в том, откуда тянется видео: с "устаревших" серверов в рф или из-за бугра.
> 
> У меня тоже скайнет и позавчера ютуб на половину умер. Не знаю что происходит. только заметил, что когда в network появляются обращения к забугорным каноник гугл сервакам например `rr1.sn-axq7sn76.googlevideo.com` сразу всё ломается, только после нескольких перезагрузок страницы начинает грузится, сначала медленно и немного, потом лучше, потом всё видео работет нормально и скорость более-менее, goodbyedpi ни на что не влияет по сути, кодек и длительность видео тоже

У меня просто так совпало, что короткие видосы по идее с Америки или Японии, а длинные попались из Германии. Длинное из Канады или Японии тоже тормозит. Я пишу страны, т.к. не смотрел, где они конкретно лежат, чисто по происхождению.

**Comment by vysmirnov** [comment]
> Подтверждаю, в Chrome проблема, в Firefox все работает отлично. Проблема только с ютубом, остальные сайты работают идеально. Версия 128.0.6613.114 (Официальная сборка), (64 бит)

А у меня в огнелисе так же, как и в остальных. Там что-то отключать надо? kyber там вроде отключен по умолчанию, а QUIC вообще нет.

**Comment by johnnyd-78** [comment]
> а QUIC вообще нет

Есть. Вводите в строке адреса about:config - ищите network.http.http3.enable - переводите в false

По скайнету на форуме целая тема уже с кучей постов, вряд ли ваша проблема в Хроме. Как я уже сказал - у меня все работает (Ростелеком)

**Comment by smsteel** [comment]
Иногда нужно рестартить сервис, хз почему.

**Comment by LafosHaas** [comment]
> > Подтверждаю, в Chrome проблема, в Firefox все работает отлично. Проблема только с ютубом, остальные сайты работают идеально. Версия 128.0.6613.114 (Официальная сборка), (64 бит)
> 
> А у меня в огнелисе так же, как и в остальных. Там что-то отключать надо? kyber там вроде отключен по умолчанию, а QUIC вообще нет.

Я не меняла ничего, просто был поставлен с нуля и запущен на проверку - все работает как часы. Подумала сначала на расширения ublock и SponsorBlock, но нет.
В Хроме через какое-то время тоже завелось, но со скрипом - долго подключает. В лисе запускается моментально.

В вашем случае скорее всего сам goodbyeDPI неправильно настроен

**Comment by DSRClient01** [comment]
Ростелеком, работает на текущей момент нормально во всех браузерах.
