### ISSUE TITLE
в russia-youtube.txt к ytimg.com не проходит пинг а вот к i.ytimg.com пинг проходит.

### ISSUE THREAD

**Issue by gegemon2012** [ValdikSS/GoodbyeDPI#601]
### Operating system / операционная система

Windows 22H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

в russia-youtube.txt к ytimg.com не проходит пинг а вот к i.ytimg.com пинг проходит.

### Additional information / Дополнительная информация

Собственно, все что могу сказать. Не знаю влияет ли это на функциональность программы.

**Comment by johnnyd-78** [comment]
И что? Проход/не проход пингов никак не связан с работоспособностью программы, она просто не работает с протоколом ICMP по которому работают пинги.
Так что ответ - нет, не влияет.
Тем более ytimg.com в текстовике - это как собственно ytimg.com так и *.ytimg.com и i.ytimg.com как раз под этот шаблон подходит.

**Comment by extde** [comment]
Прописал дополнительно строчку i.ytimg.com в russia-youtube.txt и стало работать как часы.
