### ISSUE TITLE
Добавить сайты в russia-blacklist.txt OpenAI и ChatGPT 

### ISSUE THREAD

**Issue by KurtCobainsDad** [ValdikSS/GoodbyeDPI#604]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Я заметил, то что нету сайтов OpenAI в russia-blacklist.txt, и общаться с ChatGPT надо через VPN. 
Идея такова: добавить в блэклист сайты OpenAI

**Comment by BBBlok** [comment]
Так добавь ручками :) или создай свой тхт файл и в параметрах запуска укажи его по тако же типу ..\my-site-list.txt

**Comment by KurtCobainsDad** [comment]
Уже пробовал, не работает

> Так добавь ручками :) или создай свой тхт файл и в параметрах запуска укажи его по такому же типу аля ..\my-site-list.txt

**Comment by johnnyd-78** [comment]
Они же вроде гео-блок поставили на Россию, со своей сторны, нет?

**Comment by KurtCobainsDad** [comment]
> Они же вроде гео-блок поставили на Россию, со своей сторны, нет? Во всяком случае у меня сайт OpenAI открывается нормально со стандартным блэклистом + ютуб. Болтать не пробовал
> 
> Может вам банально блэклист надо обновить?

Ну, ты попробуй в ChatGPT что-нибудь написать, у меня OpenAI открывается тоже

**Comment by johnnyd-78** [comment]
Попробовал. Проходит 1 запрос на chatgpt.com и сайт отвечает 403 Forbidden
GDPI тут не поможет, это гео-блок на российские IP

**Comment by KurtCobainsDad** [comment]
> Попробовал. Проходит 1 запрос на chatgpt.com и сайт отвечает 403 Forbidden GDPI тут не поможет, это гео-блок на российские IP

Теперь ясно.

**Comment by TvoyaKurva666** [comment]
> Попробовал. Проходит 1 запрос на chatgpt.com и сайт отвечает 403 Forbidden GDPI тут не поможет, это гео-блок на российские IP
> 
> Это раз. Теперь два: автору нафиг не нужно нужные ВАМ сайты куда-то там добавлять, это исключительно ваша задача. Автор программу писал в первую очередь для себя, а не с прицелом на то, чтобы всем угодить.

пусть угодит пж
