### ISSUE TITLE
[0.2.3rc1] Утечка памяти в ядре ОС / общая деградация быстродействия системы

### ISSUE THREAD

**Issue by vmech** [ValdikSS/GoodbyeDPI#608]
### Operating system / операционная система

Windows 10.0.17763.4499

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

После порядка 10 запусков программы ядро системы распухает до 2,2-2,5 Гбайт.
Снижается быстродействие всей системы как минимум на ~15-20%.
Очевидно, что утечка памяти в ядре.

Обычные условия (__goodbyedpi ни разу не запускался__):
Ядро системы занимает 1,5-1,8 Гбайт.
Быстродействие стабильное, в пределах погрешности (доли процента).
Аптайм системы от двух недель до месяца, и больше.
На ночь система отправляется в сон (НЕ гибернация - она отключена полностью).

### Additional information / Дополнительная информация

При увеличении числа запусков goodbyedpi распухание ядра и снижение быстродействия продолжают нарастать.
Остановка драйвера WinDivert не приносит результатов - деградация системы монотонно прогрессирует.
Быстродействие проверялось как синтетикой: тест быстродействия 7zG со словарём 512 МБайт, тест памяти TestMem5, тесты AIDA64; так и реальными приложениями (игры) - падение фпс до 50%, фреймтайм рваный (пила), играть крайне неприятно, вне зависимости от того сколько ядер ЦП задействует игра.

После перезагрузки ПК симптомы деградации полностью исчезают. Если не запускать goodbyedpi - не появляются. Про аптайм написал выше.

**Comment by ValdikSS** [comment]
Как вы проверяете потребление памяти ядром?

**Comment by Andrasolin** [comment]
Выпуск	Windows 10 Домашняя
Версия	22H2
Дата установки	‎11.‎08.‎2022
Сборка ОС	19045.4780
Взаимодействие	Windows Feature Experience Pack 1000.19060.1000.0

спустя 2+++часов просмотра шорттс в ютубе

![003](https://github.com/user-attachments/assets/ad1f8b0e-4252-42fa-8674-706d739005cf)

всё норм

**Comment by vmech** [comment]
> Как вы проверяете потребление памяти ядром?

Как проверить потребление именно ядром я не знаю.
Ориентируюсь на общие показатели памяти. Инструментов много: Process Explorer, wmic, много других утилит.

**Comment by Andrasolin** [comment]
покажите скриншот с активным Гудбай и этого мониторщика мощности. Потом врите с пруфами, я ушел в игнор

**Comment by ValdikSS** [comment]
> Ориентируюсь на общие показатели памяти.

Какие именно показатели вы учитываете? Какие цифры вы видите в paged pool/non-paged pool?

**Comment by Mitradis** [comment]
Вы рам дисками случаем не увлекаетесь?
Ну а по делу: бред, бредом. Вы бы хоть нормальными инструментами начали пользоваться.
![image](https://github.com/user-attachments/assets/2a4dcd10-e707-487c-a3f5-6dd2c9d6abdd)

**Comment by vmech** [comment]
> Какие именно показатели вы учитываете? Какие цифры вы видите в paged pool/non-paged pool?

Запущен только Process Explorer. windivert остановлен.
![](https://i.imgur.com/sGdeZAC.png)

**Comment by ValdikSS** [comment]
Сделайте такой же скриншот в момент, когда, по вашему мнению, начинаются проблемы от goodbyedpi.

**Comment by vmech** [comment]
> Сделайте такой же скриншот в момент, когда, по вашему мнению, начинаются проблемы от goodbyedpi.

Они уже есть.
Погодите, забыл куда положил скриншоты тестов.

**Comment by ValdikSS** [comment]
Тесты производительности не имеют смысла — производительность может меняться по совершенно разным причинам.
Если вы утверждаете, что в windivert утекает память, приведите хотя бы цифры, чтобы можно было выдвигать какие-либо предположения о причинах.

**Comment by ValdikSS** [comment]
>Это тот же тест, в тот же день, сразу после перезагрузки

На скриншотах разные версии 7zip (24.08 и 24.06).

**Comment by vmech** [comment]
> Тесты производительности не имеют смысла — производительность может меняться по совершенно разным причинам. Если вы утверждаете, что в windivert утекает память, приведите хотя бы цифры, чтобы можно было выдвигать какие-либо предположения о причинах.

Мне сложно утверждать, потому что я не могу обнаружить причин. Поэтому только предполагаю.
Предположение могу подкрепить только одним фактом:
Как несложно заметить по аптайму, ПК перезагружался на прошлой неделе, в среду. До воскресенья я ни разу не запускал goodbyedpi - сначала не было времени, а в субботу провёл тесты, чтобы убедиться что ОС в порядке. И всё было нормально, 7zG показал результаты как на **втором** (N2) скриншоте.
В воскресенье, впервые после перезагрузки, решил посмотреть ютуб, и вот сейчас имею то, что имею... Производительность не падает одним скачком, она деградирует постепенно. Чем больше раз запускается goodbyedpi, тем всё больше и больше деградация.

**Comment by vmech** [comment]
> На скриншотах разные версии 7zip (24.08 и 24.06).

Поверьте мне на слово - это не имеет никакого значения. Просто я сначала подумал что проблема в 7-zip, но после перезагрузки понял, что дело вовсе не в нём.

**Comment by vmech** [comment]
@ValdikSS у меня появилась идея.
Я пробовал 0.2.3rc1 с ключом `-5`, и ютуб нормально открывался и работал (вроде бы).
М.б. стОит попробовать версию 0.2.2 с ключом `-5`. В ней же более старая версия windivert ?

**Comment by ValdikSS** [comment]
>Чем больше раз запускается goodbyedpi, тем всё больше и больше деградация.

Тогда это должно быть легко отладить — запустите программу много раз.

**Comment by vmech** [comment]
> Тогда это должно быть легко отладить — запустите программу много раз.
Одного запуска недостаточно. Необходимо чтобы пакеты через фильтр бегали. Т.е. чтобы код драйвера исполнялся.

**Comment by vmech** [comment]
> Как это связано с утечкой памяти? Она есть, или вы предположили, не основываясь ни на чём? Утечки памяти обычно никак не связаны с производительностью.

Потому что кроме падения производительности увеличивается потребление памяти в простое.
В те дни, когда я не пользовался goodbyedpi, потребление памяти в простое (когда закрыты все программы) оставалось неизменным: 1,4-1,5 Гбайт сразу после перезагрузки, и до 1,7-1,8 Гбайт после использования множества программ (vscode/vscodium, Opera, Edge, архиваторы, парочка игр).
Повторюсь - на протяжении нескольких дней.
Но как только я начал запускать goodbyedpi, чтобы посмотреть ютуб, потребление памяти в простое и снижение производительности начали монотонно нарастать. С воскресенья, и до сегодняшнего дня.

**Comment by ValdikSS** [comment]
Если это ядерная память, то это можно отладить — https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/using-poolmon-to-find-a-kernel-mode-memory-leak

Если это не ядерная память, ну, вряд ли это GoodbyeDPI.

**Comment by vmech** [comment]
> Если это ядерная память, то это можно отладить — https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/using-poolmon-to-find-a-kernel-mode-memory-leak
> 
> Если это не ядерная память, ну, вряд ли это GoodbyeDPI.

О! Отлично! Изучу, и обязательно попробую.

А что скажете про идею с версией 0.2.2 ? СтОит попробовать, или «мёртвому припарки» ?

**Comment by ValdikSS** [comment]
Не стоит

**Comment by vmech** [comment]
> Если это не ядерная память, ну, вряд ли это GoodbyeDPI.

Запустил `goodbyedpi`
Запустил `poolmon`
Открыл ролик на ютуб.
Отсчёт страниц в пуле для отмеченного драйвера начался со значения `10.007.121` (точки поставил для ясности)
![poolmon](https://i.imgur.com/01NSPb4.png)

**Comment by vmech** [comment]
Посмотрел с десяток видосов и стримов, в среднеи по 15-30 минут.
Показатели изменились на следующие:
![poolmon](https://i.imgur.com/F2XeZln.png)
Всё в порядке ? Так и должно быть ?

**Comment by ValdikSS** [comment]
Так и должно быть, потребление памяти только уменьшилось. Смотреть нужно в верхний правый угол (Krnl и Pool N/P).
Ничего необычного нет.

**Comment by EgorWeders** [comment]
Возможно оффтоп, но на win 10 версий 17xxx были проблемы с драйверами сетевых карт. Их было сложно отследить, но симптомы были такие же. Чинилось обновлением драйверов или установкой более старой их версии.

**Comment by vmech** [comment]
> Так и должно быть, потребление памяти только уменьшилось. Смотреть нужно в верхний правый угол (Krnl и Pool N/P). Ничего необычного нет.

Понятно, что с драйвером всё в порядке. Напрямую он никак не влияет на ситуацию.
М.б. косвенно влияет... Но как это понять. И разобраться с этой чехардой.

PS. Сегодня не выдержал, и перезагрузил ПК - ОС начала ощутимо тормозить. Я конечно не мангуст, но было отчётливо видно как по очереди отрисовываются элементы интерфейса в Code/Codium и браузерах. При чём абсолютно одинаково со схемами энергосбережения Balanced (разрешены снижение частоты и парковка ядер ЦП) и Ultimate Performance (всё железо жарит на полную).
Несколько дней не буду запускать gbdpi, в понедельник отпишусь - изменилось ли хоть что то.

**Comment by Dum4G** [comment]
Пора на 22H2. Даже если Вы докажете косяк в работе windivert вряд ли кто-то будет переотлаживать драйвер под неподдерживаемую более версию системы

**Comment by Kfizzrixs** [comment]
Я только что удалял часа 3 эту залупу, он подсунул тебе майнер биткоинов, не верьте Владу, он хуесос

**Comment by Kfizzrixs** [comment]
При попытках использования по инструкции ничего не работало, а при попытке удаления оставался файл который не удалялся ничем, даже после чистки реестра его ни одна программа не могла удалить, потом я посмотрел повнимательнее на ошибку и там была длиннющая ссылка со словом "bitcoin"

**Comment by vmech** [comment]
Прошу прощения, что ничего не написал в прошлый понедельник. Писать было не о чем, как и ожидалось, без gbdpi ничего не изменилось.
Полистав интернеты, в нескольких местах обнаружил рекомендацию попробовать отключить драйвер NDU (Network Data Usage), что он может вызывать утечки памяти.
Перед перезагрузкой в пятницу, 6-го сентября, отключил. И всё даже было хорошо.
Ровно до вчерашнего дня. Вчера снова случился всплеск потребления памяти и падение быстродействия, в точности как ранее.

**Comment by vmech** [comment]
Здравствуйте снова.
Вобщем уже месяц прошёл, проблема вроде бы ушла/больше не проявляется.
Не могу со 100% уверенностью сказать, что именно исправило ситуацию - установка родного драйвера сетевого адаптера из пакета драйверов nForce (его версия чуть ниже, чем комплектного из Windows, но он того же года издания), или обновлённая версия `gbdpi` (rc3 которая), или и то и другое вместе.

Думаю, на этом топик можно закрывать. Не вижу причин держать его открытым и дальше.
