### ISSUE TITLE
Error opening filter: The system cannot find the path specified.

### ISSUE THREAD

**Issue by e1uen** [ValdikSS/GoodbyeDPI#612]
### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Error opening filter: The system cannot find the path specified.

пытаюсь открыть через админа, что делать

**Comment by johnnyd-78** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/566

**Comment by zipmishahl2** [comment]
> #566

пробовал, не работает

**Comment by e1uen** [comment]
Короче, это служба BFE. Которая отвечает за Windows брандмауэр.
Спасибо кто помог 🤙
