### ISSUE TITLE
Провайдер Невалинк ограничил доступ ко всем доменам .com - хотелось бы услышать мнение и способы обхода этого дерьма

### ISSUE THREAD

**Issue by Linaryx** [ValdikSS/GoodbyeDPI#613]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

добавить флаги для обхода

**Comment by yuriinet** [comment]
Прочитайте новости вашего оператора. Из-за ddos атаки у них проблемы с доступом в интернет. Могу предположить из-за этого забиты зарубежные каналы, поэтому и не работает в том числе . com, которые за бугром.

**Comment by Linaryx** [comment]
> Прочитайте новости вашего оператора. Из-за ddos атаки у них проблемы с доступом в интернет. Могу предположить из-за этого забиты зарубежные каналы, поэтому и не работает в том числе . com, которые за бугром.

Думаешь они не специально лочат это под видом дудос атак?

**Comment by EgorWeders** [comment]
[https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark](https://github.com/ValdikSS/GoodbyeDPI/wiki/%D0%9A%D0%B0%D0%BA-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%B4%D0%B0%D0%BC%D0%BF-%D1%82%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0-%D0%B2-Wireshark)

**Comment by johnnyd-78** [comment]
Деб... хм, непродвинутые пользователи из прошлого века с ВПНами наперевес, смотрящие через него ютуп,  заставляют провайдера тратить огромные деньги на зар. трафик и терять прибыль, уходить в минус. Именно поэтому почти все ВПНы, котрыми могли бы воспользоваться эти деб... хм, непродвинутые пользователи у всех адекватных провайдеров давно перекрыты на уровне протокола + сайты/адреса проверки авторизации перебанены.
Видимо, ваш провайдер решил пойти еще дальше, ограничив зар. трафик таким вот способом. А может и просто сбой, действительно

**Comment by EgorWeders** [comment]
https://downdetector.su/nevalink
Там ему впринципе плохо.

**Comment by yuriinet** [comment]
> > Прочитайте новости вашего оператора. Из-за ddos атаки у них проблемы с доступом в интернет. Могу предположить из-за этого забиты зарубежные каналы, поэтому и не работает в том числе . com, которые за бугром.
> 
> Думаешь они не специально лочат это под видом дудос атак?

Не лочат, а отключают вышестоящих операторов от которых идет ddos трафик, а как следствие связность с инетом сильно ухудшается. Анонс их AS по факту остался на SPB и Peter Ix. Проверить можете сами на ресурсах типа bgp view online. Периодически через других операторов появляется, но на минут 20-30, видимо потом опять шквал трафика летит. Это самая обычная практика. Никакой DPI тут не причём.
