### ISSUE TITLE
Call of Duty MW3 крашиться из-за GoodByeDPI

### ISSUE THREAD

**Issue by kuzan83** [ValdikSS/GoodbyeDPI#614]
### Operating system / операционная система

Windows 11 Pro 23H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Игра крашиться спустя примерно 5 минут если на компьютере присутсвует файл связанный с GoodByeDPI, эту проблему также подметили некоторые пользователи стима на форуме.
![image](https://github.com/user-attachments/assets/142ce9d8-6157-4ae0-94f6-1a1a5fe23ad8)

**Comment by EgorWeders** [comment]
> ❔ Почему не запускается Call Of Duty и некоторые другие игры?
> 
> Античитам не нравится драйвер WinDivert, см https://github.com/ValdikSS/GoodbyeDPI/issues/148, https://github.com/ValdikSS/GoodbyeDPI/issues/172.
> Обращайтесь в поддержку игры.

**Comment by johnnyd-78** [comment]
1. Откажитесь от запуска программы как сервис
2. После закрытия GDPI перед игрой выгружайте WinDivert с помощью запуска от админа service_remove.cmd
3 и **главное**. Автор GDPI ничего не может сделать с WinDivert - это стороннее ПО, так что писать **сюда** из-за проблем каких-то античитов с ним - **бессмысленно**
