### ISSUE TITLE
GoodbyeDPI мешает скачиванию реплеев в игре Dota2 

### ISSUE THREAD

**Issue by AmplifyDamage** [ValdikSS/GoodbyeDPI#615]
### Operating system / операционная система

Windows 11 Pro 23H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Side effect при эксплуатации:

1. Включаю компьютер
2. Запускаю "2_any_country.cmd" 
3. Запускаю Dota2
4. В самой игре нажимаю Download replay, во время загрузки появляется ошибка.
5. Если выключить программу, и через какое-то время попробовать загрузить реплей, то он корректно скачивается. Повторял несколько раз. 

Так же проблема скачивания реплея вручную через браузер, адрес вероятнее всего тот же что и при скачивании внутри игры  —  пример: http://replay186.valve.net/570/7934964348_606577371.dem.bz2

Провайдер — Ростелеком.

### Additional information / Дополнительная информация

P.S.
Не знаю баг ли это, заранее извиняюсь, если нерелевантно. Или я как-то не так эксплуатирую программу. Желаемый эффект в работе Youtube достигнут тем не менее. С этим всё в порядке и за это огромное спасибо!

**Comment by EgorWeders** [comment]
Если вы используете 2_any_country.cmd, то там стоит параметр ломающий часть доменов. Скорее всего этот домен один из них.

```
> ❔ Программа не разблокирует сайты на моём провайдере!

GoodbyeDPI не гарантирует ни 100% работу с вашим провайдером, ни работу с каждым заблокированным сайтом.

Опция -9, используемая по умолчанию при запуске программы, работает на большинстве, но не всех провайдерах.
Если программа не работает при запуске скриптом 1_russia_blacklist.cmd, и вы получаете ERR_SSL_PROTOCOL_ERROR, ERR_TIMED_OUT, SSL_ERROR_RX_MALFORMED_SERVER_HELLO, Нет подключения к Интернету (от YouTube), попробуйте следующие режимы:
```

**Comment by johnnyd-78** [comment]
Используйте 1_russia_blacklist.cmd заменив в нем -9 на -r -m -e 1 --reverse-frag --max-payload 1400 и будет вам счастье
