### ISSUE TITLE
После запуска GoodbyeDPI не открывается страница настроек роутера

### ISSUE THREAD

**Issue by RandomNamelessUser** [ValdikSS/GoodbyeDPI#617]
### Operating system / операционная система

Windows 10 Pro 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

После запуска GoodbyeDPI становится невозможно открыть страницу настроек роутера Asus. Не работают никакие адреса, ни asusrouter.com, ни router.asus.com, ни 192.168.1.1, и просто выдаёт стандартную заглушку браузера о том, что не удаётся найти такой сайт. И нет, это не сайт Asus, а локальная страница настроек роутера. До запуска GoodbyeDPI страница открывается нормально, и начинает снова нормально открываться после завершения GoodbyeDPI и затирания её кэша через ctrl+F5.

### Additional information / Дополнительная информация

В блэклистах упоминания указанных адресов нет.
GoodbyeDPI  запускаю с параметрами: -q -r -s -m -f 2 -e 2 --frag-by-sni --auto-ttl --wrong-seq --reverse-frag --max-payload --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
Пробовал открывать и в Файрфоксе, и в Хроме, и в Опере.
Параллельно никакие другие средства обхода блокировок не включал.
Роутер подключён по кабелю. Модель: ASUS RT-AX1800U.

**Comment by johnnyd-78** [comment]
Попробуйте без --auto-ttl и без --max-payload тоже

**Comment by SUGHuser** [comment]
Попробкйте ещё без --wrong-seq , это на многих сайтах приводит к интересностям , а так как админка роутера это аналог вебсайта - проверьте без этого ключа , скопируйте всё что в -9 , только уберите из строки --wrong-seq )

**Comment by ValdikSS** [comment]
Сделайте и пришлите дамп трафика
https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by RandomNamelessUser** [comment]
> Попробуйте без --auto-ttl и без --max-payload тоже И без -s
> Попробуйте ещё без --wrong-seq , это на многих сайтах приводит к интересностям , а так как админка роутера это аналог вебсайта - проверьте без этого ключа , скопируйте всё что в -9 , только уберите из строки --wrong-seq )

Не помогает. К тому же, без --wrong-seq ещё и обход блокировок полностью перестаёт работать.

> Сделайте и пришлите дамп трафика [https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark](https://github.com/ValdikSS/GoodbyeDPI/wiki/%D0%9A%D0%B0%D0%BA-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%B4%D0%B0%D0%BC%D0%BF-%D1%82%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0-%D0%B2-Wireshark)

Так и не понял, как этим Wireshark'ом пользоваться... Ввожу согласно гайду "host 192.168.50.1", пишет Unable to check capture filtrer. На всякий случай в квадратных скобках тоже попробовал.  Да, IP-адрес роутера оказался 192.168.50.1, а не 192.168.1.1, но сути это не поменяло, с ним всё точно так же, как и со входом по другим указанным адресам.
В добавок, в гайде говорится заходить на проверяемый сайт по HTTPS, но страница настроек открывается только по HTTP даже без использования GoodbyeDPI.

**Comment by johnnyd-78** [comment]
А если попробовать с -f 1 ?

**Comment by RandomNamelessUser** [comment]
Попробовал настройки для Дом.ру из соседней темы, немного дополнив яндексовскими ДНС.
-e 2 --wrong-seq --reverse-frag --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
В таком виде вход по 192.168.50.1 работает, хоть asusrouter.com и router.asus.com по прежнему отваливаются, ну да и фиг с ними.

**Comment by ValdikSS** [comment]
> Так и не понял, как этим Wireshark'ом пользоваться... Ввожу согласно гайду "host 192.168.50.1", пишет Unable to check capture filtrer.

Где вы получаете эту ошибку? Вводите без кавычек?

**Comment by Quawetim** [comment]
На версии [0.2.3rc3] адрес router.asus.com снова доступен с запущенным GDPI.

**Comment by ValdikSS** [comment]
@Quawetim снова? А на какой версии не работало?

**Comment by Quawetim** [comment]
> @Quawetim снова? А на какой версии не работало?

На v0.2.2

**Comment by ValdikSS** [comment]
Запишите дамп трафика на обоих версиях, и напишите точную строку запуска, с которой вы используете программу.
https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by ValdikSS** [comment]
Нет ответа ни от кого.
