### ISSUE TITLE
Goodbye DPI для android

### ISSUE THREAD

**Issue by andreybexus** [ValdikSS/GoodbyeDPI#618]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Хотелось бы чтобы на андроид был функционал как на ПК, ByeDPI вообще не работает.

**Comment by johnnyd-78** [comment]
A [Power Tunnel - Android](https://github.com/krlvm/PowerTunnel-Android) ?

В плагине Liberty Tunnel можно настроить всякие опции блокировки. А в плагине DNS - прописать какой-нибудь DoH для верности.

**Comment by ValdikSS** [comment]
Это программа для Windows
