### ISSUE TITLE
Проблема с ютубом

### ISSUE THREAD

**Issue by andreybexus** [ValdikSS/GoodbyeDPI#621]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Почему-то ютуб работает, но сама видео не загружается, 30 минут жду, протокол Kyber отключен

**Comment by andreybexus** [comment]
GoodBye DPI включен, но видео не грузятся

**Comment by AKotov-dev** [comment]
Здравствуйте. Вы можете подтвердить при **выключенном** GDPI работу [WARPActivator}(https://github.com/AKotov-dev/WARPActivator)?

**Comment by PuroOfficial** [comment]
у меня тоже проблема я обновил blacklist нечего

**Comment by PuroOfficial** [comment]
добавил service нечего

**Comment by AKotov-dev** [comment]
ещё раз... Здравствуйте. Вы можете подтвердить при **выключенном** GDPI работу [WARPActivator](https://github.com/AKotov-dev/WARPActivator)

**Comment by PuroOfficial** [comment]
> ещё раз... Здравствуйте. Вы можете подтвердить при **выключенном** GDPI работу [WARPActivator](https://github.com/AKotov-dev/WARPActivator)

не вирус?

**Comment by andreybexus** [comment]
> ещё раз... Здравствуйте. Вы можете подтвердить при **выключенном** GDPI работу [WARPActivator](https://github.com/AKotov-dev/WARPActivator)

Как-же долго активация длится, безуспешно

**Comment by AKotov-dev** [comment]
как минимум - 2 раза жать на кнопку...

**Comment by AKotov-dev** [comment]
эта информация нужна для общего анализа...

**Comment by KomAuras** [comment]
поменял -9 на -5 -e1 и заработало. Хабаровск. Редком

**Comment by andreybexus** [comment]
> эта информация нужна для общего анализа...

Попробовал ещё раз запустить, но уже без Warp сработало

**Comment by AKotov-dev** [comment]
@PuroOfficial  ? )))

**Comment by andreybexus** [comment]
> @PuroOfficial ? )))

Что я просто прогу от админа запустил, а сам Warp не активировал.

**Comment by andreybexus** [comment]
> @PuroOfficial ? )))

И это заработало

**Comment by AKotov-dev** [comment]
...Валдис... с DNS какие-то грабли у народа...

**Comment by andreybexus** [comment]
> ...Валдис... с DNS какие-то грабли у народа...

Было бы круто, если бы на андроде работало

**Comment by AKotov-dev** [comment]
на ipv6 - всё гут... опять ркн завёлся... Ладно... Зайду позже... Удачи.

**Comment by PuroOfficial** [comment]
> @PuroOfficial ? )))

бляяяят не работает

**Comment by PuroOfficial** [comment]
![image](https://github.com/user-attachments/assets/89e5e2d7-0625-46e8-9e6a-24ce2ae0bb9c)

**Comment by andreybexus** [comment]
> > @PuroOfficial ? )))
> 
> бляяяят не работает

Попробуй приложение загружить а WARP не активировать

**Comment by andreybexus** [comment]
> > @PuroOfficial ? )))
> 
> бляяяят не работает

Ой запустить приложение

**Comment by PuroOfficial** [comment]
бллллят что я делаю не так

**Comment by PuroOfficial** [comment]
все не работает

**Comment by montigomo35** [comment]
тоже больше не работает

**Comment by PuroOfficial** [comment]
хуи нам :/

**Comment by ItsNeverLight** [comment]
+

**Comment by Baptizen666** [comment]
Сам ютуб грузится, грузятся все аватарки и превьюшки, но вот сами видео не алё

**Comment by AKotov-dev** [comment]
@PuroOfficial 
мы не враги. любой из вас может быть пищей Гулага. Приезжайте, смелые люди.

**Comment by PuroOfficial** [comment]
> @PuroOfficial мы не враги. любой из вас может быть пищей Гулага. Приезжайте, смелые люди.

о теперь работает

**Comment by andreybexus** [comment]
> на ipv6 - всё гут... опять ркн завёлся... Ладно... Зайду позже... Удачи.

Будет-ли гудбай обновляться?

**Comment by kerekobar** [comment]
> поменял модсет с -9 на -7 заработало

да, это решение, спасибо большое!

**Comment by PuroOfficial** [comment]
если вам нужно установить, еще установите cloudflare warp, я просто не понял первые раз

**Comment by PuroOfficial** [comment]
> @PuroOfficial мы не враги. любой из вас может быть пищей Гулага. Приезжайте, смелые люди.

все спасибо

**Comment by andreybexus** [comment]
> > @PuroOfficial мы не враги. любой из вас может быть пищей Гулага. Приезжайте, смелые люди.
> 
> все спасибо

Я Warpactivator просто скинул в папку с GoodBye DPI и работает, кнопку активацией WARP я не нажимал.

**Comment by PomalinTheCat** [comment]
WarpActivator рил работает
только без Redirect DNS с ним инет вообще не работает ни на каком сайте
спасибо AKotov-dev

**Comment by EgorWeders** [comment]
Обращаю внимание всех, что в репозитории warpactivator не исходный код, а zip файл, и за то что будет с вашим пк после его использования **не имеет отношения к GoodbyeDPI**.

**Comment by AKotov-dev** [comment]
> Обращаю внимание всех, что в репозитории warpactivator не исходный код, а zip файл, и за то что будет с вашим пк после его использования **не имеет отношения к GoodbyeDPI**.

обращаю внимание, что исходный код и контрольные суммы неизменны. Изменения в рабочем текстовом файле. Исходный код ни кто не трогал. GPLv3... Apache v2.0 Прошу Вас привести изменения в коде. Я Вас засужу, ибо в России GPL3 - это авторское право. Жду с нетерпением...

**Comment by whitehattyhank** [comment]
ебаный роскомнадзор

**Comment by montigomo35** [comment]
Для меня сработало скачать версию 0.2.3rc1 и поменять в 1_russia_blacklist.cmd -9 на -7

**Comment by EgorWeders** [comment]
> > Обращаю внимание всех, что в репозитории warpactivator не исходный код, а zip файл, и за то что будет с вашим пк после его использования **не имеет отношения к GoodbyeDPI**.
> 
> обращаю внимание, что исходный код и контрольные суммы неизменны. Изменения в рабочем текстовом файле. Исходный код ни кто не трогал. GPLv3... Apache v2.0 Прошу Вас привести изменения в коде. Я Вас засужу, ибо в России GPL3 - это авторское право. Жду с нетерпением...

?
че
 Я указал на то, что проверить файлы через репу гитхаба нельзя, только zip качать. А это уже само по себе небезопасно и уж точно не ответственность автора GoodbyeDPI

**Comment by BateauSD** [comment]
Вообще никак ютуб не работает и с включенным и выключенным. 
Скорость в сис.статистике 50-100кб и все красное с черным.

**Comment by AKotov-dev** [comment]
@PuroOfficial 
Развлекается молодёжь... ))

**Comment by Damonis** [comment]
Такая же проблема, грузит комменты и превьюшки, но не само видео.Пробовал все модсеты из Modern modesets, но ничего не поменялось

**Comment by ElochkaGithub** [comment]
Я так понял не у меня одного час назад перестал гуд бай дпиай работать, что делаем судари для решения проблемы?

**Comment by BateauSD** [comment]
VLESS VPN кстати тоже несколько часов назад перестали почти полностью работать. Подключение есть, смена айпи есть но скорость низкая настолько что использовать это нельзя.

**Comment by AKotov-dev** [comment]
@PuroOfficial
))) пусть развлекаются )) Понимаю...

**Comment by ElochkaGithub** [comment]
Читали же новость про то что аболтусам выделили 20 млрд рублей на борьбу с впн и прочей дичью?

**Comment by PomalinTheCat** [comment]
> Читали же новость про то что аболтусам выделили 20 млрд рублей на борьбу с впн и прочей дичью?

ИМ СЕРЬЕЗНО ВЫДЕЛИЛИ 20 МИЛЛИАРДОВ?

**Comment by BateauSD** [comment]
> > Читали же новость про то что аболтусам выделили 20 млрд рублей на борьбу с впн и прочей дичью?
> 
> ИМ СЕРЬЕЗНО ВЫДЕЛИЛИ 20 МИЛЛИАРДОВ? если да то это конец пора тикать с россии

Если точнее, то почти 60 миллиардов рублей им дали.

**Comment by AKotov-dev** [comment]
260 миллиардов... Симонян - именно с этим говном в москве несовместиность. .

**Comment by AKotov-dev** [comment]
Есть объект...

**Comment by ElochkaGithub** [comment]
Так и что судари хоть что то помогло? WARP - не  работает ну и GoodbyeDPI - соостветсвенно тоже

**Comment by PomalinTheCat** [comment]
> Так и что судари хоть что то помогло? WARP - не работает ну и GoodbyeDPI - соостветсвенно тоже

мне помогло изменить 1 цифру в 1_russia_blacklist.cmd а именно изменить -9 на -7
просто изменяешь вышеупомянутый файл в .txt файл (или используй какой нибудь notepad++ если у тебя он есть) найди длинную строку в файле и где то в начале будет -9 после изменения сохрани и сделай файл обратно .cmd после этого запусти и проверяй

**Comment by ElochkaGithub** [comment]
> > Так и что судари хоть что то помогло? WARP - не работает ну и GoodbyeDPI - соостветсвенно тоже
> 
> мне помогло изменить 1 цифру в 1_russia_blacklist.cmd а именно изменить -9 на -7 просто изменяешь вышеупомянутый файл в .txt файл (или используй какой нибудь notepad++ если у тебя он есть) найди длинную строку в файле и где то в начале будет -9 после изменения сохрани и сделай файл обратно .cmd после этого должно заработать если нет то либо впн либо тикай с россии (я не патриотист сорян)

Офигеть, спасибо чувак. Больше интересно на что влияет данный параметр

**Comment by EgorWeders** [comment]
> > > Так и что судари хоть что то помогло? WARP - не работает ну и GoodbyeDPI - соостветсвенно тоже
> > 
> > 
> > мне помогло изменить 1 цифру в 1_russia_blacklist.cmd а именно изменить -9 на -7 просто изменяешь вышеупомянутый файл в .txt файл (или используй какой нибудь notepad++ если у тебя он есть) найди длинную строку в файле и где то в начале будет -9 после изменения сохрани и сделай файл обратно .cmd после этого должно заработать если нет то либо впн либо тикай с россии (я не патриотист сорян)
> 
> Офигеть, спасибо чувак. Больше интересно на что влияет данный параметр

https://github.com/ValdikSS/GoodbyeDPI?tab=readme-ov-file#how-to-use

**Comment by ElochkaGithub** [comment]
спасибо

**Comment by BateauSD** [comment]
> > Так и что судари хоть что то помогло? WARP - не работает ну и GoodbyeDPI - соостветсвенно тоже
> 
> мне помогло изменить 1 цифру в 1_russia_blacklist.cmd а именно изменить -9 на -7 просто изменяешь вышеупомянутый файл в .txt файл (или используй какой нибудь notepad++ если у тебя он есть) найди длинную строку в файле и где то в начале будет -9 после изменения сохрани и сделай файл обратно .cmd после этого должно заработать если нет то либо впн либо тикай с россии (я не патриотист сорян)

Жаль, мне нечего не дало вообще. Но спасибо.

**Comment by PomalinTheCat** [comment]
> Жаль, мне нечего не дало вообще. Но спасибо.
я забыл упомянуть что нужно открывать ИМЕННО 1_russia_blacklist.cmd после изменения
если запустить GoodbyeDpi.exe из папки x86 или x86_64 то нифига не поменяется

**Comment by PomalinTheCat** [comment]
сообщение багануло но вроде бы видно

**Comment by Seeroy** [comment]
Поменял -9 на -1, заработало
-9, -7, -5 (в т.ч. -e1 -f1) не работают

**Comment by ElochkaGithub** [comment]
Разве? мне -7 c первого раза помогло, надо запустить тот же файл что мы изменяли с правами администратора если что

**Comment by Psych0S0cial** [comment]
-7 не помогло, поставил -1, всё заработало

**Comment by Stic1337** [comment]
Тоже час назад youtube перестал работать. Поменял параметр на -7, видео начали открываться, но с задержкой в 1-2 сек.

**Comment by PomalinTheCat** [comment]
эта штука видимо так же зависит от рандома провайдера города в котором ты живешь направления ветра фазы луны и тд
-7 работает на ростелеком

**Comment by Seeroy** [comment]
Причём на -1 почему-то перестают открываться некоторые [другие сайты](https://genius.com), вообще случайно заметил

**Comment by owldrugs** [comment]
Изменил на -7 - ничего не изменилось.

**Comment by BateauSD** [comment]
> > Жаль, мне нечего не дало вообще. Но спасибо.
> > я забыл упомянуть что нужно открывать ИМЕННО 1_russia_blacklist.cmd после изменения
> > если запустить GoodbyeDpi.exe из папки x86 или x86_64 то нифига не поменяется

именно 1_russia_blacklist и поменял, попробовал -7 и далее, нихрена, живу на ДВ

**Comment by Damonis** [comment]
> > > Жаль, мне нечего не дало вообще. Но спасибо.
> > > я забыл упомянуть что нужно открывать ИМЕННО 1_russia_blacklist.cmd после изменения
> > > если запустить GoodbyeDpi.exe из папки x86 или x86_64 то нифига не поменяется
> 
> именно 1_russia_blacklist и поменял, попробовал -7 и далее, нихрена, живу на ДВ

Тоже самое

**Comment by Psych0S0cial** [comment]
> > > > Жаль, мне нечего не дало вообще. Но спасибо.
> > > > я забыл упомянуть что нужно открывать ИМЕННО 1_russia_blacklist.cmd после изменения
> > > > если запустить GoodbyeDpi.exe из папки x86 или x86_64 то нифига не поменяется
> > 
> > 
> > именно 1_russia_blacklist и поменял, попробовал -7 и далее, нихрена, живу на ДВ
> 
> Тоже самое

Попробуйте -1, сам с ДВ, помогло

**Comment by Psych0S0cial** [comment]
> > > Жаль, мне нечего не дало вообще. Но спасибо.
> > > я забыл упомянуть что нужно открывать ИМЕННО 1_russia_blacklist.cmd после изменения
> > > если запустить GoodbyeDpi.exe из папки x86 или x86_64 то нифига не поменяется
> 
> именно 1_russia_blacklist и поменял, попробовал -7 и далее, нихрена, живу на ДВ

Попробуйте -1, сам с ДВ, помогло

**Comment by Jadovran** [comment]
Я просто добавил "--dns-addr 1.1.1.1" в параметры запуска и мне помогло.

**Comment by Mintstorm** [comment]
Попробовал другой браузер(не яндекс), все заработало

**Comment by LillianZero** [comment]
> поменял -9 на -5 -e1 и заработало. Хабаровск. Редком

а где что ты менял? в какой папке?

**Comment by TeslaWP** [comment]
Нижегородская область, Билайн, поменял -9 на -7 и заработало.

**Comment by johnnyd-78** [comment]
Та же проблема. Была ) Убрал --wrong-seq и все заработало

**Comment by LillianZero** [comment]
> > > > Жаль, мне нечего не дало вообще. Но спасибо.
> > > > я забыл упомянуть что нужно открывать ИМЕННО 1_russia_blacklist.cmd после изменения
> > > > если запустить GoodbyeDpi.exe из папки x86 или x86_64 то нифига не поменяется
> > 
> > 
> > именно 1_russia_blacklist и поменял, попробовал -7 и далее, нихрена, живу на ДВ
> 
> Попробуйте -1, сам с ДВ, помогло

Подскажи пж, а что там менять? Название сценария который запускаешь или как?

**Comment by kirakiradesu** [comment]
1_russia_blacklist -7 -e 1  ... работает
как служба такой конфиг не работает :(

**Comment by stgtg** [comment]
[LillianZero](https://github.com/LillianZero) Вроде это это надо менять, у меня заработало
![jhkj](https://github.com/user-attachments/assets/ca8f3d29-84c4-4285-a680-a7dcd7f6b35b)

**Comment by heuggehaap** [comment]
> Попробовал другой браузер(не яндекс), все заработало

У меня в яндексе больше недели так себе работал, до того, как сейчас поменял настройки

**Comment by Jadovran** [comment]
> Та же проблема. Была ) Убрал --wrong-seq и все заработало
> 
> goodbyedpi.exe -r -m -e 2 -f 1 --reverse-frag --set-ttl 2 --max-payload 1400 --blacklist ...

У меня пиратский варкрафт на запускается из-за твоего ttl 2, пришлось ставить 4.

**Comment by LillianZero** [comment]
> [LillianZero](https://github.com/LillianZero) Вроде это это надо менять, у меня заработало ![jhkj](https://private-user-images.githubusercontent.com/108290617/366857472-ca8f3d29-84c4-4285-a680-a7dcd7f6b35b.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDI1MDEsIm5iZiI6MTcyNjE0MjIwMSwicGF0aCI6Ii8xMDgyOTA2MTcvMzY2ODU3NDcyLWNhOGYzZDI5LTg0YzQtNDI4NS1hNjgwLWE3ZGNkN2Y2YjM1Yi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxMTU2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTUxZGMyNzM3ZGUyYjllMGVmMjlkMDlmYjYyMGFjZjQ0Y2FkM2Y3MzY2MDVhZTI4NDAxYTRiNjdhNTc4Nzc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vXUk1nIiSFmazZY8cOkyp5ewzVT3vitPtiKcEA-Zcxo)

Понял, спасибо, но как я понял, цифра после минуса зависит от оператора или региона

**Comment by Snr-Zhan** [comment]
Помогла смена -9 на -1. Город Владивосток

**Comment by ComShep** [comment]
Помогло с -9 на -7. Саранск

**Comment by johnnyd-78** [comment]
> У меня пиратский варкрафт на запускается из-за твоего ttl 2, пришлось ставить 4.

Все верно, это значение каждый себе подбирает сам, начиная с 2 и так пока не заработает

**Comment by Andrewin1Dark** [comment]
-9 сменил на -1, заработало, провайдер МТС

**Comment by kirakiradesu** [comment]
> -9 сменил на -1, заработало, провайдер МТС

прикол что у всех всё разное :) у меня тоже МТС и работает токо "-7 -e 1" просто "-7" не работает... и только с запуском файла, как служба эти параметры не работают почему то

**Comment by Andrewin1Dark** [comment]
> > -9 сменил на -1, заработало, провайдер МТС
> 
> прикол что у всех всё разное :) у меня тоже МТС и работает токо "-7 -e 1" просто "-7" не работает... и только с запуском файла, как служба эти параметры не работают почему 
Интересно, интересно

**Comment by johnnyd-78** [comment]
> прикол что у всех всё разное :) у меня тоже МТС и работает токо "-7 -e 1" просто "-7" не работает... и только с запуском файла, как служба эти параметры не работают почему то

Наверное потому, что cmd для обычного запуска и для как служба - разные? Это раз. Значит у вас при создании службы передача параметров работает как-то неправильно и стоит туда добавить что-нибудь кроме -ХЕРЬ - все ломается

**Comment by kekmachine123** [comment]
> Помогла смена -9 на -1. Город Владивосток
Мне тоже помогло, Владивосток, Подряд

**Comment by JustMKMe** [comment]
Похоже, на стороне DPI-оборудования что-то начали менять и экспериментировать с реакцией.

**Comment by kirakiradesu** [comment]
>> Наверное потому, что cmd для обычного запуска и для как служба - разные? Это раз. Значит у вас при создании службы передача параметров работает как-то неправильно и стоит туда добавить что-нибудь кроме -ХЕРЬ - все ломается

Перепроверил и правда, раньше стояло -5 -e1 -q ... я изменил на -7 -e1 -q и служба заработала. Странно вроде до этого запуск файла 1_russia_blacklist и службы с одинаковым конфигом работали, а сейчас нет

**Comment by d000b** [comment]
-9 сменил на **-7**, **заработало**, провайдер Инфосервис (teleos) Братск, Черемхово. Кому-то может помочь

**Comment by ItsNeverLight** [comment]
> > > -9 сменил на -1, заработало, провайдер МТС
> > 
> > 
> > Перетыкал все и тишина, либо в 360р ролик заводится, либо вообще нет. Редачил файл 1_russia_blacklist в текстовом. Владивосток. Провайдер Альянс, по сути тот же Ростелеком.
> 
> А так goodbyedpi.exe -r -m -e 2 -f 1 --reverse-frag --blacklist ... ?

Подряд, ДВ. Помогло

**Comment by dakses** [comment]
ничего не работает, все перепробовал, вообще никак. Запускается еле как на 360.

**Comment by VizartLA** [comment]
> > > -9 сменил на -1, заработало, провайдер МТС
> > 
> > 
> > Перетыкал все и тишина, либо в 360р ролик заводится, либо вообще нет. Редачил файл 1_russia_blacklist в текстовом. Владивосток. Провайдер Альянс, по сути тот же Ростелеком.
> 
> А так goodbyedpi.exe -r -m -e 2 -f 1 --reverse-frag --blacklist ... ?

Помогло, Самара, Ростелеком

**Comment by xShKeT** [comment]
Томск, Ростелеком, помогло заменить -9 на -1

**Comment by LoverVud** [comment]
> > > -9 сменил на -1, заработало, провайдер МТС
> > 
> > 
> > Перетыкал все и тишина, либо в 360р ролик заводится, либо вообще нет. Редачил файл 1_russia_blacklist в текстовом. Владивосток. Провайдер Альянс, по сути тот же Ростелеком.
> 
> А так goodbyedpi.exe -r -m -e 2 -f 1 --reverse-frag --blacklist ... ?

Братск, телеос, помогло

**Comment by Snr-Zhan** [comment]
> > > -9 сменил на -1, заработало, провайдер МТС
> > 
> > 
> > Перетыкал все и тишина, либо в 360р ролик заводится, либо вообще нет. Редачил файл 1_russia_blacklist в текстовом. Владивосток. Провайдер Альянс, по сути тот же Ростелеком.
> 
> А так goodbyedpi.exe -r -m -e 2 -f 1 --reverse-frag --blacklist ... ?

теперь при запуске сразу закрывается... 
у меня так: start "" goodbyedpi.exe -r -m -e 2 -f 1 --reverse-frag --blacklist.txt --blacklist ..\russia-youtube.txt

**Comment by johnnyd-78** [comment]
А надо так: start "" goodbyedpi.exe -r -m -e 2 -f 1 --reverse-frag --blacklist ..\russia-youtube.txt

**Comment by EtherealDragon123** [comment]
Поменял -9 на -5, всё заработало. Саратовская область, местный провайдер, вроде как, использующий сервера Билайна.

**Comment by qxzusero** [comment]
Транстелеком, помогло -5.

**Comment by TheMagicPe4enka** [comment]
Ростелеком, Кемеровская область
-9 не работает, как тут говорят "не грузит видео"
почитал тут, говорят что перестал работать параметр --wrong-seq
Предлагаю параметры: 
-7 -q
Будет почти та же -9, только без --wrong-seq

**Comment by rpcot** [comment]
НСК, провайдер МТС
не помогло ничего из вышеперечисленного
в данный момент команда запуска выглядит следующим образом:
start "" goodbyedpi.exe -r -m -e 2 -f 1 --reverse-frag --blacklist ..\russia-blacklist.txt
запускаю 1_russia_blacklist.cmd

**Comment by feduardoflex** [comment]
Ростелеком, Якутск. Помог модсет -1.

**Comment by Snr-Zhan** [comment]
> А надо так: start "" goodbyedpi.exe -r -m -e 2 -f 1 --reverse-frag --blacklist ..\russia-youtube.txt
> 
> Короче, меняем **-9** на **-r -m -e 2 -f 1 --reverse-frag** и больше ничего не трогаем

Спасибо огромное, помогло (Владивосток). А РКН пусть идёт нахуй

**Comment by johnnyd-78** [comment]
> в данный момент команда запуска выглядит следующим образом:
> start "" goodbyedpi.exe -r -m -e 2 -f 1 --reverse-frag --blacklist ..\russia-blacklist.txt

Попробуйте -e 1 вместо -e 2

**Comment by rpcot** [comment]
> > в данный момент команда запуска выглядит следующим образом:
> > start "" goodbyedpi.exe -r -m -e 2 -f 1 --reverse-frag --blacklist ..\russia-blacklist.txt
> 
> Попробуйте -e 1 вместо -e 2

не-а, всё так же

**Comment by Animator2003** [comment]
-7 работает для видосиков! (покрайне мере для меня)

Красноярск, Сибирские сети

**Comment by CraftyCrab** [comment]
> поменял -9 на -5 -e1 и заработало. Хабаровск. Редком

Заработало. Спасибо

**Comment by TheMagicPe4enka** [comment]
> > поменял -9 на -5 -e1 и заработало. Хабаровск. Редком
> 
> Заработало. Спасибо

Посмотри -7 -q, пожалуйста. Ради спортивного интереса

**Comment by johnnyd-78** [comment]
> не-а, всё так же
А так -r -m -e 2 -f 1 --reverse-frag --wrong-chksum ?

**Comment by neverovije** [comment]
> А надо так: start "" goodbyedpi.exe -r -m -e 2 -f 1 --reverse-frag --blacklist ..\russia-youtube.txt
> 
> Короче, меняем **-9** на **-r -m -e 2 -f 1 --reverse-frag** и больше ничего не трогаем

Алтайский край Ростелеком, работает, всем спасибо за помощь

**Comment by Navelion** [comment]
-r -m -e 2 -f 1 --reverse-frag Саратов домру, только так получилось, остальное не хотело.

**Comment by johnnyd-78** [comment]
> так же

А покажите-ка скрин окна программы

**Comment by rpcot** [comment]
всё, сделал
в итоге всё же остановился на start "" goodbyedpi.exe -r -m -e 2 -f 1 --reverse-frag --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt, видимо я тупанул и поставил не ту версию, у меня изначально не было последнего параметра с ютубом
всем спасибо

**Comment by VLOD-ZDOV** [comment]
Ростелеком, программа как сервис, смена на -5 и -1 помогла

**Comment by johnnyd-78** [comment]
> у меня изначально не было последнего параметра с ютубом всем спасибо

Ну, я так и подумал )

**Comment by rpcot** [comment]
> > у меня изначально не было последнего параметра с ютубом всем спасибо
> 
> Ну, я так и подумал )

причем изначально стояла версия 0.2.3, потом я поставил 0.2.2, ибо она была релизнута и показывалась как последняя

**Comment by SektantPiva** [comment]
Всё от имени администратора:
1. Запускаете 0_russia_update_blacklist_file
2.  Как закроется предыдущая, service_install_russia_blacklist
3. Затем сам гудбай
Мне помогло

**Comment by rpcot** [comment]
> Ну, это вы зря. Не всегда то, что последнее в Releases есть последнее на самом деле

0.2.3 в пре-релизе же, так что гитхаб показал последнюю релизнутую версию, видимо

**Comment by Heymdale** [comment]
Самара Домашний Мегафон (WiFire) работает с параметром -1

**Comment by crefter** [comment]
Ростелеком, Кемеровская область
сменил -9 на -1 и помогло
работает как wifi, так и lan 
использую 2_any_country

**Comment by johnnyd-78** [comment]
> 0.2.3 в пре-релизе же, так что гитхаб показал последнюю релизнутую версию, видимо

У этого пререлиза в окне программы отображается 0.2.2 по прежнему. А есть версия, где уже все правильно отображается - 0.2.3 Лежит [тут](https://github.com/ValdikSS/GoodbyeDPI/actions/runs/10433461667) Но если у вас все работает, лучше ничего не трогайте пока
