### ISSUE TITLE
VPN+GDPI

### ISSUE THREAD

**Issue by Andrasolin** [ValdikSS/GoodbyeDPI#622]
### Operating system / операционная система

WinOS 10x64 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Провайдеры начали блокировать ВПН сервисы, без вашей ГДПИ  они не работают. а час назад Ютуб начал долго загружаться, и то только стартовые страницы, а сами видео лоад только крутится и всё

**Comment by johnnyd-78** [comment]
И что? В чем прблема то? Видосы не грузятся без ВПН? Так настраивайте GDPI пока не начнут.

**Comment by crefter** [comment]
Попробуй в файлах .cmd изменить параметр -9 (или какой есть) на другой, например, на -1. Мне помогло

**Comment by Andrasolin** [comment]
> Попробуй в файлах .cmd изменить параметр -9 (или какой есть) на другой, например, на -1. Мне помогло

уже пробовал, разные варианты, не помогло

**Comment by ValdikSS** [comment]
Понятно, тогда это не баг.

**Comment by Andrasolin** [comment]
Ждать фикса или уйти в лес по грибы?

**Comment by johnnyd-78** [comment]
> Ждать фикса или уйти в лес по грибы?

Фикса чего? Программа работает, надо только сменить настройки. Идите на форум - там вам помогут их подобрать.
