### ISSUE TITLE
GoodbyeDPI стал работать только при запуске и 1_russia_blacklist_dnsredir и 1_russia_blacklist.

### ISSUE THREAD

**Issue by Mishail009** [ValdikSS/GoodbyeDPI#623]
### Operating system / операционная система

Windows 10 KB5043064

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Приходится включать и 1_russia_blacklist_dnsredir и 1_russia_blacklist. Раньше включал только первую и всё работало, сейчас видео не грузит если не включены обе.

**Comment by johnnyd-78** [comment]
В 1_russia_blacklist_dnsredir.cmd попробуйте поменять -9 на -e 2 -f 1 --reverse-frag

Закройте все окна GDPI и выполните service_remove.cmd от админа

Потом запустите измененный 1_russia_blacklist_dnsredir.cmd

**Comment by deltaradune** [comment]
2_any_country.cmd запускаешь и все работает как прежде

**Comment by 22baobab8** [comment]
> В 1_russia_blacklist_dnsredir.cmd попробуйте поменять -9 на -e 2 -f 1 --reverse-frag
> 
> Закройте все окна GDPI и выполните service_remove.cmd от админа
> 
> Потом запустите измененный 1_russia_blacklist_dnsredir.cmd
а можешь пожалуйста объяснить куда это вводить надо?

**Comment by mazinilya** [comment]
> > В 1_russia_blacklist_dnsredir.cmd попробуйте поменять -9 на -e 2 -f 1 --reverse-frag
> > Закройте все окна GDPI и выполните service_remove.cmd от админа
> > Потом запустите измененный 1_russia_blacklist_dnsredir.cmd а можешь пожалуйста объяснить куда это вводить надо?



Открываешь CMD файл обычным блокнотом тот который ты используешь там есть -9  и меняй на -e 2 -f 1 --reverse-frag

**Comment by 22baobab8** [comment]
> > > В 1_russia_blacklist_dnsredir.cmd попробуйте поменять -9 на -e 2 -f 1 --reverse-frag
> > > Закройте все окна GDPI и выполните service_remove.cmd от админа
> > > Потом запустите измененный 1_russia_blacklist_dnsredir.cmd а можешь пожалуйста объяснить куда это вводить надо?
> 
> Открываешь CMD файл обычным блокнотом тот который ты используешь там есть -9 и меняй на -e 2 -f 1 --reverse-frag

а что делать если нету -9?

**Comment by mazinilya** [comment]
> > > > В 1_russia_blacklist_dnsredir.cmd попробуйте поменять -9 на -e 2 -f 1 --reverse-frag
> > > > Закройте все окна GDPI и выполните service_remove.cmd от админа
> > > > Потом запустите измененный 1_russia_blacklist_dnsredir.cmd а можешь пожалуйста объяснить куда это вводить надо?
> > 
> > 
> > Открываешь CMD файл обычным блокнотом тот который ты используешь там есть -9 и меняй на -e 2 -f 1 --reverse-frag
> 
> а что делать если нету -9?

какой файл открываешь?

**Comment by Designer1347** [comment]
> > > > В 1_russia_blacklist_dnsredir.cmd попробуйте поменять -9 на -e 2 -f 1 --reverse-frag
> > > > Закройте все окна GDPI и выполните service_remove.cmd от админа
> > > > Потом запустите измененный 1_russia_blacklist_dnsredir.cmd а можешь пожалуйста объяснить куда это вводить надо?
> > 
> > 
> > Открываешь CMD файл обычным блокнотом тот который ты используешь там есть -9 и меняй на -e 2 -f 1 --reverse-frag
> 
> а что делать если нету -9?

Все там есть 3-я строчка снизу ,почти самое начало. Проблема в другом - не помогает. Буквально час назад все работало как системная служба - сейчас фулл отказ работать. Страницы грузит, а вот сами ролики на утубе - нет.

**Comment by 22baobab8** [comment]
а если я это делаю с 2_any_country сработает?

**Comment by 22baobab8** [comment]
всем спасибо за пояснения, все работает как раньше

**Comment by saNYAunbrain** [comment]
> В 1_russia_blacklist_dnsredir.cmd попробуйте поменять -9 на -e 2 -f 1 --reverse-frag
> 
> Закройте все окна GDPI и выполните service_remove.cmd от админа
> 
> Потом запустите измененный 1_russia_blacklist_dnsredir.cmd

Помогло, спасибо

**Comment by Designer1347** [comment]
> Выглядеть это должно примерно так ![изображение](https://private-user-images.githubusercontent.com/65572205/366913974-0bda10a5-e118-4b33-9703-12dac70b57f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTA2ODYsIm5iZiI6MTcyNjE1MDM4NiwicGF0aCI6Ii82NTU3MjIwNS8zNjY5MTM5NzQtMGJkYTEwYTUtZTExOC00YjMzLTk3MDMtMTJkYWM3MGI1N2Y1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE0MTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YmRjOGQyOTdjZDQwZTg2NWUzNjMwMmE2MWQ4YTliZmRmNzI0YzQ4Njg4YTUwNTM2MjEyYjQyM2RiZjNhNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gBe6nqXFhbGOtfOw1cR6e38-O9BkOBSVvsjgzWJV1Xg)

Делайте строчку как у этого человечка -r -m -r -m -e 2 -f 1 --reverse-frag ..... Если вдруг просто замена -9 на -r -m -e 2 -f 1 --reverse-frag не помогло.

**Comment by rockkman** [comment]
что я только не поставил... них... не работает :/

**Comment by SergioSikoni** [comment]
Сегодня впервые установил. Всё работает на windows 7.Никаких действий кроме запуска goodbyedpi.exe не применял.

**Comment by SergioSikoni** [comment]
> В 1_russia_blacklist_dnsredir.cmd попробуйте поменять -9 на -e 2 -f 1 --reverse-frag
> 
> Закройте все окна GDPI и выполните service_remove.cmd от админа
> 
> Потом запустите измененный 1_russia_blacklist_dnsredir.cmd

РАБОТАЕТ, ОДНАКО НЕТ ДОСТУПА С ЭТИМИ НАСТРОЙКАМИ К ТВОРЧЕСКОЙ СТУДИИ ЮТЮБ
