### ISSUE TITLE
Обновление GoodBye DPI

### ISSUE THREAD

**Issue by mazinilya** [ValdikSS/GoodbyeDPI#624]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Будет ли обновление для программы? так как сегодня перестал работать ютуб и тут мне помог один способ 

Изменить -9 на -e 2 -f 1 --reverse-frag

Но дело в том что не все знают что да как делать  я даже сталкивался с тем что не все знают как редактировать cmd файл

Может ли автор обновить файл и прописать все?

Так всем будет легче

**Comment by Dombezd** [comment]
Спасибо, видел что писали на форуме про это, но не знал что нужно заменить -9 на то что ты написал, просто дописывал. Теперь все заработало.
