### ISSUE TITLE
Кликните, оказывается Тыкабельно!

### ISSUE THREAD

**Issue by Andrasolin** [ValdikSS/GoodbyeDPI#625]
Тыкните, мне помогло

![001](https://github.com/user-attachments/assets/f3e284a8-0dda-477d-b718-e27b45f5f0f8)

**Comment by MaxAt100** [comment]
Да ты шо

**Comment by Daniil1265** [comment]
После обновления начинает работать инстаграм и X :D

**Comment by MaxAt100** [comment]
Они вроде и раньше работали...

**Comment by Daniil1265** [comment]
> Они вроде и раньше работали...

ну мб от провайдера зависит или настроек GoodBye

**Comment by Andrasolin** [comment]
Выделенный Красным - странный. спустя какое-то время блокирует весь Интернет-связь, помогает только перезапуск Скрипта.

а этот АЛЬТ уже 1+++часов просмотра Шортс в Ютубе, всё гуд

![001](https://github.com/user-attachments/assets/db2521ce-73f3-4a93-bd93-131b91f1dfcc)

**Comment by prblm** [comment]
> > Они вроде и раньше работали...
> 
> ну мб от провайдера зависит или настроек GoodBye, у меня только с обновой снова заработали

если на уровне провайдера/публичного dns забанен адрес, то работать не будет, батник где есть _dnsredir перенаправляет на публичный dns, который не блочит инстаграмм

**Comment by ValdikSS** [comment]
Wow, amazing. Вода мокрая, ветер шумный, по ссылкам можно кликать.
