### ISSUE TITLE
Глобальный режим работы (без списков)

### ISSUE THREAD

**Issue by QNetITQ** [ValdikSS/GoodbyeDPI#626]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Сейчас скрипт работает только с содержимым списков. Это имеет такое неприятное последствие как необходимость периодически их обновлять. Предлагаю добавить глобальный режим работы скрипта, что бы он работал со всем трафиком. Это позволит использовать скрипт не дожидаясь обновлений списков. Что бы снизить вероятность возможных проблем, установить для этого режима лайтовые методы обхода блокировок, HTTP/HTTPS Fragmentation и/или DNS редирект и типа того.

**Comment by johnnyd-78** [comment]
2_any_country... работают без списков, они чем не устроили? ) 
Или вам под каждую из сотен комбинаций параметров свой CMD нужен? Ну так создайте его сами, в чем проблема?
Вместо -9 пишем -e 2 -f 2 - вот вам и лайт фрагментация, dns редирект уже есть в 2_any_country_dnsredir.cmd

**Comment by Andrasolin** [comment]
> 2_any_country... работают без списков, они чем не устроили? ) Или вам под каждую из сотен комбинаций параметров свой CMD нужен? Ну так создайте его сами, в чем проблема? Вместо -9 пишем -e 2 -f 2 - вот вам и лайт фрагментация, dns редирект уже есть в 2_any_country_dnsredir.cmd

мы все обычные люди(потребители) а не кодеры/программисты как вы...
а я умею читать и тыкать, а ещё умею Ctrl+С и Ctrl+В

**Comment by QNetITQ** [comment]
> 2_any_country... работают без списков, они чем не устроили? )
Не знал что `2_any_country` работает без списков. В шапке об этом ничего не написано. Только то что это для других стран.

> Вместо -9 пишем -e 2 -f 2 - вот вам и лайт фрагментация, dns редирект уже есть в 2_any_country_dnsredir.cmd
Да, я так и сделал. Этого оказалось достаточно для моего провайдера SkyNet(СПб). Ютуб всё равно чуть притормаживает, но ничего критичного.

Я пробовал удалить параметр `--blacklist` из `1_russia_blacklist.cmd`, но после этого просто перестал запускаться скрипт. Вот я и прошу добавить такую возможность, или уточнить этот момент в шапке репозитория.
