### ISSUE TITLE
При запуске возникает ошибка

### ISSUE THREAD

**Issue by MaxStive** [ValdikSS/GoodbyeDPI#628]
### Operating system / операционная система

Windows 11 23H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Error opening filter: 1058 The service cannot be started, either because it is disabled or because it has no enabled devices associated with it. Выдаёт эту ошибку и крашится

**Comment by Rumaruka** [comment]
Попробуй перезагрузить пк и запустить программу

**Comment by MaxStive** [comment]
Пробовал, не помогло. Сейчас полностью снёс GoodbyeDPI и переустановил прграмку (снёс WinDivert.sys через cmd), теперь всё заработало

**Comment by Ho0LiGaN82** [comment]
> Пробовал, не помогло. Сейчас полностью снёс GoodbyeDPI и переустановил прграмку (снёс WinDivert.sys через cmd), теперь всё заработало

а так не пробовали? https://github.com/ValdikSS/GoodbyeDPI/issues/433#issuecomment-2277618307
