### ISSUE TITLE
Github action for pull requests style check.

### ISSUE THREAD

**Issue by EgorWeders** [ValdikSS/GoodbyeDPI#631]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Не нашел в репозитории ничего кроме .editorconfig. Если вы работаете через редактор с форматированием, было бы славно узнать конфиг (.clang-format или стандарт допустим), и я бы смог сделать проверку для pr.  Если без форматтера, то issue не актуально.

**Comment by ValdikSS** [comment]
Не работаю, мои редакторы его не используют, вроде бы. Это было добавлено не мной.
