### ISSUE TITLE
Перенос на другой ресурс

### ISSUE THREAD

**Issue by ZeoNish** [ValdikSS/GoodbyeDPI#632]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Пока РКН не забанил ГитХаб перенеси проект на сторонний ресурс.

**Comment by sulfur17** [comment]
ntc.party тоже перенести бы в телегу, а то он уже тоже недоступен

**Comment by ZeoNish** [comment]
просто 80% приходят качнуть прогу, а кто то тут репы держит...

**Comment by aoay775live** [comment]
сумасшедший слоник вытирает попу хоботом

**Comment by ValdikSS** [comment]
https://bitbucket.org/ValdikSS/goodbyedpi/src/master/

**Comment by ZeoNish** [comment]
> https://bitbucket.org/ValdikSS/goodbyedpi/src/master/

Да зайти скачать то не проблема. Найти качнуть. Проблема если GH под раздачу попадет.

**Comment by SeryiBaran** [comment]
> > https://bitbucket.org/ValdikSS/goodbyedpi/src/master/
> 
> Да зайти скачать то не проблема. Найти качнуть. Проблема если GH под раздачу попадет.

Поздно наверн, но ты не поверишь -  на ГХ сотни других таких вот репо.

**Comment by Alucard648** [comment]
> > > https://bitbucket.org/ValdikSS/goodbyedpi/src/master/
> > 
> > 
> > Да зайти скачать то не проблема. Найти качнуть. Проблема если GH под раздачу попадет.
> 
> Поздно наверн, но ты не поверишь - на ГХ сотни других таких вот репо.

В том то и дело, что все эти репозитории станут недоступными, если РКН полностью заблокирует ГитХаб из-за способов обхода блокировок.
