### ISSUE TITLE
-7 начали детектить тоже, какие еще есть варианты?

### ISSUE THREAD

**Issue by 677230756E64** [ValdikSS/GoodbyeDPI#633]
### Operating system / операционная система

windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

работало сначала на дефолтном конфиге, когда начали его детектить повсеместно, поменял на -7, заработало. вот теперь это тоже начали детектить. какие еще есть варианты?

**Comment by BERaleks** [comment]
душат по чуть чуть

**Comment by Thekefa** [comment]
-1 пашет

**Comment by Kxarlex** [comment]
Нет -1 у меня не работает и не -7 мтс

> -1 пашет

**Comment by demeja1610** [comment]
Скачал последний релиз, основной файлик 1_russia_blacklist.cmd не работает, но есть 1_russia_blacklist_YOUTUBE_ALT - он работает
тут https://github.com/ValdikSS/GoodbyeDPI/issues/378 это написано:)
