### ISSUE TITLE
ntc.party не работает

### ISSUE THREAD

**Issue by sulfur17** [ValdikSS/GoodbyeDPI#635]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

похоже ntc.party заблокирован, предлагаю перейти в телеграмм. Можно создать свой или например на https://t.me/goodbye_dpi

**Comment by johnnyd-78** [comment]
Как смешно - на гитхабе программы по разблокировке писать, что что-то заблокировано :D

**Comment by sulfur17** [comment]
ребенок, это тебе не чат, не надо выражать тут свои эмоции, пиши только по делу

**Comment by johnnyd-78** [comment]
Прорекламил свою телегу - возьми с полки пирожок. Я с тобой никаких дел иметь не хочу, иди в своей телеге с такими как ты общайся.

**Comment by Gxtod** [comment]
> Прорекламил свою телегу - возьми с полки пирожок. Я с тобой никаких дел иметь не хочу, иди в своей телеге с такими как ты общайся.

Грубо, но правда, телега уже всех задолбала особенно после ареста Дурова, такая же ФСБшная помойка как и ВК, нет смысла в ней делать каналы и чаты. 

Но вот **GoodbyeDPI** почаще бы обновлять, снова ничего не работает и об этом почему-то пишут на другом ресурсе, а автору словно пофиг... https://dtf.ru/howto/3009307-goodbyedpi-snova-perestal-rabotat-kak-ego-pochinit-i-razblokirovat-youtube

**Comment by ValdikSS** [comment]
Форум работает, проблем не вижу

**Comment by sulfur17** [comment]
@ValdikSS вчера не работал, сегодня работает, а завтра заблочат и что делать?

@Gxtod вместо благодарности автору за его бесплатную работу ты решил выставить ему претензии? \
Для задолбанных ФСБшными помойками объясняю, какой в них смысл: когда ntc.party заблокируют, то мы нигде кроме телеги не найдем рекомендации по обходу блокировки. В ишью гитхаба общаться очень неудобно, т.к. для получения ответа надо обновлять страницу. Чат для этого подходит гораздо лучше. Так понятно?

**Comment by FaidaenShatz** [comment]
Добрый день. У меня вопрос касательно содержимого файла "russian-blacklist". Правильно ли я понимаю, что данная программа обеспечивает доступ ко всем ссылка из данного документа, и что все приведенные ссылки ведут на реально существующий сайты?
![Снимок экрана 2024-10-25 в 19 37 09](https://github.com/user-attachments/assets/440365a7-6c6f-4de2-8bba-9ec7fa290687)
