### ISSUE TITLE
Не могу удалить программу, WinDivert64.sys всегда запущен

### ISSUE THREAD

**Issue by RainbowGolem** [ValdikSS/GoodbyeDPI#637]
### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

![2024-09-18_23-12-58](https://github.com/user-attachments/assets/9ec309a3-40f9-4c7b-b7fb-53494d89bbbd)
Хочу скачать новую версию. У меня версия 0.2.3rc1, пытался удалить и скачать 0.2.3rc3-2. Удалил всё кроме одного единственного файла. Я уже незнаю что делать, я и компьютер перезагружал, и в интернете искал, не могу удалить. В интернете сказали удалять через консоль, я запускаю консоль от имени администратора, удаляю файл, "отказано в доступе". Что делать?

**Comment by dimitrus0** [comment]
пробовал запустить service_remove.cmd?

**Comment by Ho0LiGaN82** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/433#issuecomment-2277618307

**Comment by RainbowGolem** [comment]
> пробовал запустить service_remove.cmd?

да

**Comment by RainbowGolem** [comment]
> решение проблемы: [#433 (comment)](https://github.com/ValdikSS/GoodbyeDPI/issues/433#issuecomment-2277618307)

![2024-09-19_07-57-05](https://github.com/user-attachments/assets/27399720-5f1a-4b97-bd85-bff359305aed)
Не работает. После того как я ввёл команды я зашёл в папку и нажал "обновить" а потом удалил файл, но получил ту же самую ошибку. Похоже я застрял в этом мире с этим файлом на всегда

**Comment by idMysteries** [comment]
Unlocker в помощь

**Comment by Andrasolin** [comment]
> Unlocker в помощь (сам удалял через iobit unlocker)

Тык https://www.iobit.com/en/iobit-unlocker.php

**Comment by PaNFiLoVeTs** [comment]
> > пробовал запустить service_remove.cmd?
> 
> да

Эта команда запускается от имени Администратора - по-другому не работает, поскольку WinDivert - это служба и для её остановки от имени обычного пользователя прав не хватает

**Comment by johnnyd-78** [comment]
После sc stop windivert и sc delete windivert иногда требуется перезагрузка. Хз с чем это связано, скорее всего с кривизной винды или наличием старых виндивертов в системе (например от активаторов винды/офиса)

**Comment by RainbowGolem** [comment]
> После sc stop windivert и sc delete windivert иногда требуется перезагрузка. Хз с чем это связано, скорее всего с кривизной винды или наличием старых виндивертов в системе (например от активаторов винды/офиса)

Чувак огромное тебе спасибо! Только что попробовал удалить, сработало!!! Я даже не пытался со вчерашнего дня, а зря

**Comment by InkHellish** [comment]
открываете cmd от имени админа, и не важно какие числа у вашего файла, главное впишите сначала "sc stop WinDivert"
после вписываете "sc delete WinDivert" он может написать "Не удалось найти файл" или что то в этом роде, заходите в папку с этим файлом, и удаляете его, если выдало ошибку, перезагружаете компьютер через кнопку "Выключить питание" и снова запускаете через системник, далее удаляете файл и чистите корзину, и еще раз перезагружаете пк.
Воуля, и все готово.
У меня лично, WinDivert64 оказался Стиллер + Майнер.

**Comment by dobrota133** [comment]
ошибка 1060 служба не установлена, как удалять?

**Comment by W-A-Y-F-A-R-E-R** [comment]
> ### Operating system / операционная система
> Windows 10
> 
> ### Running as service / Запуск программы как сервис
> I run it as a regular program / Запускаю программу обычным образом
> 
> ### Describe the bug / Опишите ошибку программы
> ![2024-09-18_23-12-58](https://private-user-images.githubusercontent.com/111136464/368723600-9ec309a3-40f9-4c7b-b7fb-53494d89bbbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDc1ODIsIm5iZiI6MTczMzM0NzI4MiwicGF0aCI6Ii8xMTExMzY0NjQvMzY4NzIzNjAwLTllYzMwOWEzLTQwZjktNGM3Yi1iN2ZiLTUzNDk0ZDg5YmJiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQyMTIxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWE4MGJmMTkwNDRmZWEyYTJkNDdmNWJjZDk1ZmIwZmQ1MGVjODlkNWJjNTRiYTMyNTUxMjhhYjY4OTEwOTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bmiEiiU2Dj-X-ulG6b68pJap0TipyTxdHWxQJ456Fj8) Хочу скачать новую версию. У меня версия 0.2.3rc1, пытался удалить и скачать 0.2.3rc3-2. Удалил всё кроме одного единственного файла. Я уже незнаю что делать, я и компьютер перезагружал, и в интернете искал, не могу удалить. В интернете сказали удалять через консоль, я запускаю консоль от имени администратора, удаляю файл, "отказано в доступе". Что делать?
> 
> ### Additional information / Дополнительная информация
> _No response_

Открываешь командную строку от имени администратора, и пишешь "sc stop WinDivert". Служба будет остановлена. И затем удаляешь файлы. Конец)))

**Comment by Gizmarian** [comment]
![2024-09-18_23-12-58](https://github.com/user-attachments/assets/9ec309a3-40f9-4c7b-b7fb-53494d89bbbd) 

Никого не смущает что там **Bitcoin:** и хэш ??? 

Майнят ?

**Comment by SoulMinf** [comment]
У меня такой файл остался от старой версии Zapret и не мог долго удалить
В этом треде нашёл команды. Нужно запускать CMD от имени администратора. Через `cd "путь к файлу"` перейти в нужную папку и там уже выполнить команды `sc stop windivert` и `sc delete windivert`. Если со второй не сработало, значит нужно попробовать просто удалить файл и всё. На крайняк запустить windows в безопасном режиме и удалить

**Comment by suthul** [comment]
Воспользовался советом и удалил файл через команду, но когда потребовалось снова скачать запрет, он вовсе перестал открываться. Что новая, что предыдущая версия. После запуска любого файла он сразу же закрывается, и следовательно, ничего не работает. Я не особо разбираюсь во всех этих программах, поэтому помогите, пожалуйста, если кто знает, в чем дело. Может ли это быть как раз из-за тех команд?

**Comment by lkhorasandzhian** [comment]
> открываете cmd от имени админа, и не важно какие числа у вашего файла, главное впишите сначала "sc stop WinDivert" после вписываете "sc delete WinDivert" он может написать "Не удалось найти файл" или что то в этом роде, заходите в папку с этим файлом, и удаляете его, если выдало ошибку, перезагружаете компьютер через кнопку "Выключить питание" и снова запускаете через системник, далее удаляете файл и чистите корзину, и еще раз перезагружаете пк. Воуля, и все готово. У меня лично, WinDivert64 оказался Стиллер + Майнер.

@InkHellish бро, а как ты понял, что это Стиллер + Майнер?
