### ISSUE TITLE
Error opening filter: 1058 The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

### ISSUE THREAD

**Issue by QwertySP234** [ValdikSS/GoodbyeDPI#639]
### Operating system / операционная система

WINDOWS 10 21H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Error opening filter: 1058 The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
![QCMHaW7N9q](https://github.com/user-attachments/assets/fe174f99-9a86-4cbb-a5b2-c5c4d00d2aa1)

**Comment by Ho0LiGaN82** [comment]
Попробуйте остановить и переустановить WinDivert: https://github.com/ValdikSS/GoodbyeDPI/issues/433#issuecomment-2277618307

**Comment by XO6bl4** [comment]
Вероятно ошибка в неправильном обновлении GoodbyeDPI (думаю, вы удалили сервис предыдущей версии, распаковали новую версию GoodbyeDPI в другую папку и попытались запустить его). В таком случае сервис является зарегистрированным для удаления - вам требуется лишь перезапустить ПК. В противном случае данный способ не поможет.

**Comment by QwertySP234** [comment]
Ho0LiGaN82, сделал, ошибка в cmd пропала, но ютуб все равно не работает

**Comment by johnnyd-78** [comment]
Он и не будет. Судя по скрину вы запускакете тупо EXE а надо CMD запускать, со словом YouTube в названии

**Comment by QwertySP234** [comment]
johnnyd-78, спасибо большое за помощь
