### ISSUE TITLE
Duolingo issue

### ISSUE THREAD

**Issue by reserved-word** [ValdikSS/GoodbyeDPI#64]
Win 10 64bit, служба запущена с параметрами `-1 --blacklist "C:\Program Files\goodbyedpi\blacklist.txt"`
Домен cloudfront.net отсутствует в blacklist.txt.

При попытке зайти на https://www.duolingo.com/ браузер (Chrome, FF) не может получить скрипты и стили с https://d7mj4aqfscim2.cloudfront.net и страница не отображается. 

При остановленной службе сайт грузится без проблем. _При включении службы работоспособность сайта сохраняется из-за кэша._

На других сайтах проблем с cloudfront.net не замечал.

**Comment by ValdikSS** [comment]
Хм, у меня проблема не проявляется, сайт открыватеся корректно, https://d7mj4aqfscim2.cloudfront.net выдает 404.
Возможно, у какого-то балансировщика cloudfront, на который попадаете вы, но не попадаю я, проблемы с фрагментированными пакетами. Попробуйте использовать параметр `-4`, если с ним будет открываться, то проблема действительно во фрагментации.

Могу еще предположить, что это ваш провайдер отвергает фрагментированные пакеты на некоторые IP-адреса.

В будущем планируется реализовать другой механизм для HTTPS-сайтов, подобный опции `-k` для HTTP.

**Comment by reserved-word** [comment]
С `-4` проблемы нет.

**Comment by ValdikSS** [comment]
Проблема такая же, как в #4.
В будущих версиях GoodbyeDPI будет реализована пакетная фрагментация, а не фрагментация путем уменьшения TCP Window Size, и эта проблема не будет проявляться.

**Comment by reserved-word** [comment]
Держу в курсе: проблема сейчас не воспроизводится, запросы к cloudfront идут нормально. Может быть что-то изменилось в инфраструктуре провайдера, например, связано с тем, что блокировки доменов сейчас отключены.

**Comment by ValdikSS** [comment]
Проблемы с TCP-фрагментацией должны быть решены в версии GoodbyeDPI 0.1.7, опцией `--reverse-frag`.

TCP fragmentation issues should be solved in GoodbyeDPI 0.1.7, by using `--reverse-frag` option.
