### ISSUE TITLE
Can't find WinDivert64.sys or WinDivert32.sys

### ISSUE THREAD

**Issue by samponet** [ValdikSS/GoodbyeDPI#640]
### Operating system / операционная система

Windows 8.1

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Программа не может найти драйвера при запуске. Пробовал различные местоположения для размещения папки с программой, кидал симлинки в папку Windows - всё равно сообщение с ошибкой и программа закрывается. Версия goodbyedpi-0.2.3rc3-2, с версией goodbyedpi-0.2.2 такого не было.

**Comment by EgorWeders** [comment]
А вы просто архив распаковываете и запускаете в итоговой папке скрипт?

**Comment by johnnyd-78** [comment]
Какой номер ошибки, покажите скрин окна программы

**Comment by samponet** [comment]
Неизвестно что произошло, но теперь всё работает, ветку можно закрывать

**Comment by iGG1m** [comment]
> Какой номер ошибки, покажите скрин окна программы
> 
> Скорее всего у вас неправильные права на ветку реестра HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDivert выдайте на нее полные права группе Администраторы

а если нет WinDivert раздела?
