### ISSUE TITLE
Не запускается программа

### ISSUE THREAD

**Issue by Leshiy220** [ValdikSS/GoodbyeDPI#641]
### Operating system / операционная система

Windows 11 Pro 23H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Установил версию 0.2.3rc3-2. Программа перестала запускаться вообще, не реагирует ни на запуск через консоль, ни на любые другие методы.

### Additional information / Дополнительная информация

В консоли от администратора запускаю через команду `C:\GoodbyeDPI\goodbyedpi-0.2.3rc3-2\goodbyedpi-0.2.3rc3-2>1_russia_blacklist_YOUTUBE`

**Comment by lp85d** [comment]
Запусти 1_russia_blacklist_YOUTUBE_ALT.cmd
У меня только с ним запустилось

**Comment by johnnyd-78** [comment]
Добавьте в cmd слово pause отдельной строкой после POPD запустите измененный cmd и покажите что напишет

**Comment by Leshiy220** [comment]
> Добавьте в cmd слово pause отдельной строкой после POPD запустите измененный cmd и покажите что напишет

В консоли просто появляется надпись "Для продолжения нажмите клавишу"
![DPI pause](https://github.com/user-attachments/assets/95ad783c-c52d-4108-8a67-ba1f8dda4822)

**Comment by johnnyd-78** [comment]
А можете архив просто в c:\GoodbyeDPI распаковать, без этих всех .-1. (без папки, которая в архиве) что-нибудь изменится?
И перед этим перезагрузите комп

**Comment by ValdikSS** [comment]
> В консоли просто появляется надпись "Для продолжения нажмите клавишу"

А справа в окне у вас что?

**Comment by Leshiy220** [comment]
> А справа в окне у вас что?
blacklist youtube, но он не реагирует на нажатия никаких клавиш. Если окно просто закрыть - то программа не запуститься

**Comment by Leshiy220** [comment]
> А справа в окне у вас что?

blacklist youtube, но он не реагирует на нажатия никаких клавиш. Если окно просто закрыть - то программа не запуститься

**Comment by ValdikSS** [comment]
>Если окно просто закрыть - то программа не запуститься

Что это значит? Это и есть программа, она запущена.

**Comment by Leshiy220** [comment]
> Что это значит? Это и есть программа, она запущена.
При запуске программы в таком варианте ничего не происходило.

**Comment by Leshiy220** [comment]
> Что это значит? Это и есть программа, она запущена.

При запуске программы в таком варианте ничего не происходило.

**Comment by ValdikSS** [comment]
А что вы ожидаете, чтобы происходило?

**Comment by Leshiy220** [comment]
на данный момент у меня все заработало. Необходимо было через консоль открыть service_install_russia_blacklist_YOUTUBE
Спасибо всем большое за помощь
