### ISSUE TITLE
Не грузят видео на YouTube

### ISSUE THREAD

**Issue by AmidTyorkin** [ValdikSS/GoodbyeDPI#642]
### Operating system / операционная система

Windows 11

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Не загружаются видео в YouTube, хоть и сам сайт запускается, но когда открываю видео, 0 прогруза.

**Comment by johnnyd-78** [comment]
QUIC отключен?

**Comment by grincha09** [comment]
попробуй скачать последнюю версию https://github.com/ValdikSS/GoodbyeDPI/releases/tag/0.2.3rc3
и запускать 1_russia_blacklist_YOUTUBE.cmd

**Comment by AmidTyorkin** [comment]
Всё заработало, огромное спасибо!!!
