### ISSUE TITLE
Проксификация трафика мессенджера Wire

### ISSUE THREAD

**Issue by malwareprogrammer** [ValdikSS/GoodbyeDPI#645]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [x] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Недавно Роскомнадзор заблокировал мессенджер Wire, предлагаю настроить спуф пакетов данного мессенджера.
**Домены мессенджера:**

> wire.com
origin-docs.wire.com
fanboys.wire.com
geektalk.wire.com
get.wire.com
ubercast.wire.com
countly.wire.com
wire-webapp-staging.wire.com
docs.wire.com
clientblacklist.wire.com
static.web.wire.com
brand.wire.com
account.wire.com
workingdraft.wire.com
developer.wire.com
developers.wire.com
teams.wire.com
app.wire.com
securealert.wire.com
sft.prod-calling.wire.com
coturn.prod-calling.wire.com
prod-nginz-ssl.wire.com
wire-docs.wire.com
go.wire.com
outlook.integrations.wire.com
prod-nginz-https.wire.com
staging-assets.wire.com
prod-assets.wire.com
wire-app.wire.com
start.wire.com
status.wire.com
staging.wire.com
brand-http.wire.com
www.wire.com
support.wire.com
sft12.sft.prod.wire.com
sft7.sft.prod.wire.com
sft18.sft.prod.wire.com
integration.wire.com
turn.prod-calling.wire.com
sft25.sft.prod.wire.com
sft14.sft.prod.wire.com
turn01.de.prod.wire.com
sft24.sft.prod.wire.com
earlybird.wire.com
sft9.sft.prod.wire.com
www.try.wire.com
www.app.wire.com
sft6.sft.prod.wire.com
sft15.sft.prod.wire.com
blog.wire.com
turn04.de.prod.wire.com
motion.wire.com
sft17.sft.prod.wire.com
sft13.sft.prod.wire.com
sft5.sft.prod.wire.com
sunrise.wire.com
sft20.sft.prod.wire.com
mobile.wire.com
sft26.sft.prod.wire.com
web.wire.com
sft16.sft.prod.wire.com
wire-static.wire.com
sft27.sft.prod.wire.com
de.prod.wire.com
go2.wire.com
ccdhasdfsasjsdfaasd2n8oflxonyolp-app-prod.wire.com
sft3.sft.prod.wire.com
sft22.sft.prod.wire.com
sft1.sft.prod.wire.com
turn03.de.prod.wire.com
prod-calling.wire.com
sft4.sft.prod.wire.com
sft2.sft.prod.wire.com
wire-website-staging.web.wire.com
pwa.wire.com
sft21.sft.prod.wire.com
sft0.sft.prod.wire.com
sft23.sft.prod.wire.com
turn02.de.prod.wire.com
turn05.de.prod.wire.com
sft1.sft.beta.wire.com
sft01-beta.wire.com
people.wire.com
sft19.sft.prod.wire.com
w.wire.com
wire-webapp-prod-next.wire.com
news.wire.com
marketing.wire.com
try.wire.com
sft10.sft.prod.wire.com
consent.wire.com
sft8.sft.prod.wire.com
sft11.sft.prod.wire.com
admin-broadcast.proxy.services.wire.com
cert.services.wire.com
charon.services.wire.com
echo.services.wire.com
github.services.wire.com
github.staging.services.wire.com
jbb.proxy.services.wire.com
poll.proxy.services.wire.com
proxy.services.wire.com
recording.services.wire.com
securealert.services.wire.com
services.wire.com
stripe.proxy.services.wire.com
swisscom.services.wire.com

**Я добавил данный список доменов через --blacklist, но к сожалению мессенджер не работает. Пробовал разные конфиги GoodbyeDPI, к сожалению мессенджер не работает ни с один конфигом.**

**Wire - мессенджер, который не подвергается цензуре РКН, имеет сквозное шифрование и не сотрудничает с властями РФ.**

**Comment by johnnyd-78** [comment]
Вместо этой простыни достаточно вписать просто wire.com
Впрочем, если он забанен по IP (или диапазону его IP) это ничем не поможет, как и GDPI в принципе.
