### ISSUE TITLE
Unblocked site blocked by programm 

### ISSUE THREAD

**Issue by oncceh** [ValdikSS/GoodbyeDPI#646]
### Operating system / операционная система

windows 11 22h2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Site "https://cyberpunk.fandom.com/" does not open with the app, but opens without it.

**Comment by johnnyd-78** [comment]
![изображение](https://github.com/user-attachments/assets/603de736-1be3-4c92-933c-356efe7edc35)

Try add --wrong-chksum то CMD what you use

**Comment by oncceh** [comment]
This helped, thank you.

**Comment by oncceh** [comment]
After a while, the same problem still occurs, and you have to either turn off the application or restart it.
