### ISSUE TITLE
Разблокировка черно-оранджевого ютуба

### ISSUE THREAD

**Issue by LTSCTeam** [ValdikSS/GoodbyeDPI#647]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Добавьте просто в russia-blacklist.txt эти домены, и будьте счастливы:
`rt.pornhub.com`
`cv-h.phncdn.com`
`ei.phncdn.com`
P.S сначала будет небольшая прогрузка в 3-6 секунд, а потом будет нормальная загрузка видео)

**Comment by johnnyd-78** [comment]
Достаточно просто
pornhub.com
phncdn.com

Поддомены программа обрабатывает автоматически, если указан основной домен

**Comment by NullPointerExeptionBruh** [comment]
Но вот анонимность... Провайдер если что то подозрительное заметит попробует узнать куда ведёт айпи и потом увидит этот сайт и потом 103... Но маловероятно так как есть шифрование, но кто знает

**Comment by lolomap** [comment]
> и потом 103...

103?
