### ISSUE TITLE
windivert.sys и античит в играх

### ISSUE THREAD

**Issue by anauthentic** [ValdikSS/GoodbyeDPI#648]
### Operating system / операционная система

Windows 11

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Даже после закрытия goodbyedpi (сервис не установлен) некоторые игры (например, cod warzone) с античитом не запускаются и приходится перезагружать систему, поскольку драйвер windivert остается висеть в памяти. Есть ли способ его выгружать принудительно?

**Comment by johnnyd-78** [comment]
Самый легкий - выполнить от админа service_remove.cmd
Если через командную строку от админа, там пищем sc stop windivert
Этого достаточно

**Comment by anauthentic** [comment]
> Самый легкий - выполнить от админа service_remove.cmd Если через командную строку от админа, там пишем sc stop windivert Этого достаточно

спасибо! не думал, что служба создается при обычном запуске
