### ISSUE TITLE
Нереально долго грузится DeviantArt и imaginePro

### ISSUE THREAD

**Issue by andreybexus** [ValdikSS/GoodbyeDPI#649]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Я 2 минуты жду загрузки этих двух сайтов, почему-то при включенном VPN они загружаются секунд за 30.

**Comment by johnnyd-78** [comment]
Это при запуске какого CMD и на какой версии?

**Comment by andreybexus** [comment]
> Это при запуске какого CMD и на какой версии программы?

Самая последняя версия

**Comment by johnnyd-78** [comment]
А на первую часть вопроса ответа не будет?

**Comment by andreybexus** [comment]
> А на первую часть вопроса ответа не будет?

1_russia_blacklist_youtube_alt

**Comment by johnnyd-78** [comment]
Попробуйте добавить --auto-ttl куда-нибудь между -5 и --blacklist
