### ISSUE TITLE
Feature - Traybar support

### ISSUE THREAD

**Issue by fuzun** [ValdikSS/GoodbyeDPI#65]
There may be an option for showing statistics in a traybar icon (while mouse hover, no more).

This would be useful when it is working through a service silently.

**Comment by ValdikSS** [comment]
I'm planning to implement GUI with tray and simple configuration dialog. For some reason it's not that simple to create GUI windows from a console application, so it would be different exe file which controls service or starts console application.

**Comment by fuzun** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/65#issuecomment-373887865

**Comment by satnatantas** [comment]
@ValdikSS what if I'd like no window at all?
https://stackoverflow.com/questions/4441551/how-to-stop-a-program-compiled-with-mingw-g-from-opening-a-console-window-in
It looks that it's hardcoded so it would require second executable to make it optional, I might do it just for myself.

**Comment by ValdikSS** [comment]
@satnatantas then you should use service mode.
