### ISSUE TITLE
youtube грузит медленее после последнего обновления goodbyedpi

### ISSUE THREAD

**Issue by ArtemChik103** [ValdikSS/GoodbyeDPI#651]
### Operating system / операционная система

windows 11 pro 22H2 22621.1848

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Ютуб стал грузить намного медленее после обновления проги, я запускаю по инструкции
раньше идеально грузило 1080, теперь только 480 могу смотреть

**Comment by Nelimu5221** [comment]
тож

**Comment by ArtemChik103** [comment]
> тож

стала скорость тупо на уровне впн

**Comment by unlike777** [comment]
goodbyedpi-0.2.3rc3 
1_russia_blacklist_YOUTUBE.cmd  ->  открываем в текстовом редакторе -> меняем -9 на -6
мне помогло

**Comment by prblm** [comment]
провайдер не дом.ру случаем?

**Comment by JohnyPjato4ka** [comment]
> goodbyedpi-0.2.3rc3 
> 1_russia_blacklist_YOUTUBE.cmd  ->  открываем в текстовом редакторе -> меняем -9 на -6
> мне помогло

Тоже возникли проблемы, этот способ помог. Спасибо 🖖

**Comment by ArtemChik103** [comment]
> провайдер не дом.ру случаем?

ростелеком

**Comment by ArtemChik103** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/652#issuecomment-2365244269 это помогло

**Comment by ArtemChik103** [comment]
закрываю ишью

**Comment by ArtemChik103** [comment]
> [#652 (comment)](https://github.com/ValdikSS/GoodbyeDPI/issues/652#issuecomment-2365244269) это помогло

пж попробуйте, оно помогает
