### ISSUE TITLE
Грузит долго ОЧЕНЬ долга

### ISSUE THREAD

**Issue by Nelimu5221** [ValdikSS/GoodbyeDPI#652]
### Operating system / операционная система

ex. Windows 20H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Я сижу пробуя новую версию гудбай дипиай но ютуб не работает (не грузит видео) я хз что случилось так что я перехожу на дзен 

### Additional information / Дополнительная информация

хз как это контрить

**Comment by Andrasolin** [comment]
![002](https://github.com/user-attachments/assets/f921799b-c57f-49f5-88af-3a4944813e3e)
выключите все ГудбайДПИ и запустите один из них

**Comment by SenyaZver** [comment]
Перестали работать новые файлы

**Comment by unlike777** [comment]
goodbyedpi-0.2.3rc3 
1_russia_blacklist_YOUTUBE.cmd  ->  открываем в текстовом редакторе -> меняем -9 на -6
мне помогло

**Comment by shuriklol** [comment]
Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex

Пример:
--fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25

**Comment by KaaLoli** [comment]
Решение от shuriklol помогло, спасибо

**Comment by Memfivosfey** [comment]
Ростелеком, Новосибирск. 

Прога, просто волшебная! Только вот разобраться в ней и понять, не получается. Всё методом тыка только.
Работал ютуб, чудно, классно, великолепно, божественно!  Думал всё, теперь проблема решена. Вот примерно дней 5 назад, что-то случилось и перестал работать. Я перебрал все сайты к которым обращается. Добавил ещё парочку в файл russia-youtube.txt. Не помогло. Мучился и оставил. Сейчас прочитал, про то что заменить в 1_russia_blacklist_YOUTUBE.cmd -> изменить -9 на -6, сделал. О ЧУДО!!! Сам сайт грузится как пуля. НО! Видео по прежнему не показывает, колёсико крутит и крутит, а видео не идёт. 100%, провайдер что-то химичит. Помогите пожалуйста. Может есть какая-то ещё настройка?

И ещё. Может быть существует утилита какая-нибудь, что бы допустим запустить её у себя в сети, протестировать сеть, на предмет того, какие методы блокировки использует мой провайдер? Что бы сразу выставить правильные параметры в GBDPI? Как мне понять, какие переключатели включить?! Помогите, ютуб реально очень нужен.

**Comment by Memfivosfey** [comment]
> Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex
> 
> Пример: --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25
> 
> Так же замените значение --fake-gen Пример: --fake-gen 29
Подскажите пожалуйста, где именно находится эта строка?

**Comment by prblm** [comment]
> > Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex
> > Пример: --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25
> > Так же замените значение --fake-gen Пример: --fake-gen 29
> 
> Подскажите пожалуйста, где именно находится эта строка?

если запускаешь один из батников типа "1_russia_blacklist_dnsredir.cmd" , то вот эта строка
"start "" goodbyedpi.exe -9 --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt"

для начала просто по перебирай предустановки, вместо дефолтового -9 , меняй цифры на 2, 5, 6, 7 мб сработают без танцев бубнов с конкретными ключами.

**Comment by shuriklol** [comment]
> > Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex
> > Пример: --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25
> > Так же замените значение --fake-gen Пример: --fake-gen 29
> 
> Подскажите пожалуйста, где именно находится эта строка?

Убедитесь, что вы используете последнюю версию программы:
[goodbyedpi-0.2.3rc3-2.zip](https://github.com/ValdikSS/GoodbyeDPI/releases/download/0.2.3rc3/goodbyedpi-0.2.3rc3-2.zip)

внутри папки программы находится файл -> 1_russia_blacklist_YOUTUBE.cmd (если он отсутствует у вас это значит что вы используете устаревшую версию программы)
откройте его с помощью блокнота, и отредактируйте его
Пример:
start "" goodbyedpi.exe -9 --fake-gen 29 --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

Так же можете использовать -> 1_russia_blacklist_dnsredir.cmd
откройте его с помощью блокнота, и отредактируйте его
Пример:
start "" goodbyedpi.exe -9 -e1 -q --fake-gen 29 --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25 --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

**Comment by prostoman** [comment]
Решение от shuriklol работает, спасибо!

**Comment by joric** [comment]
Отрубили ютуб наглухо в ночь на 22 сентября. Решение от shuriklol работает.

**Comment by GennadijK1987** [comment]
> Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex
> 
> Пример: --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25
> 
> Так же замените значение --fake-gen Пример: --fake-gen 29

Здравствуйте. Можете пожалуйста описать чуть подробнее , куда нужно заходить , что взять значение о котором вы говорите .

**Comment by Hegins255** [comment]
Спасибо shuriklol!

**Comment by cmepkalocb** [comment]
Перепробовал кучу рах hex коды. fake gen менял, ноль! ютуб как помер, так и не оживает ((

**Comment by johnnyd-78** [comment]
Думаю многим, но вряд ли всем, будет достаточно
start /MIN "" goodbyedpi.exe -6 --fake-gen 2 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

from-hex статичен, его так же быстро могут снова забанить. У меня прошлый продержался сутки )

**Comment by GennadijK1987** [comment]
> > > Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex
> > > Пример: --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25
> > > Так же замените значение --fake-gen Пример: --fake-gen 29
> > 
> > 
> > Подскажите пожалуйста, где именно находится эта строка?
> 
> Убедитесь, что вы используете последнюю версию программы: [goodbyedpi-0.2.3rc3-2.zip](https://github.com/ValdikSS/GoodbyeDPI/releases/download/0.2.3rc3/goodbyedpi-0.2.3rc3-2.zip)
> 
> внутри папки программы находится файл -> 1_russia_blacklist_YOUTUBE.cmd (если он отсутствует у вас это значит что вы используете устаревшую версию программы) откройте его с помощью блокнота, и отредактируйте его Пример: start "" goodbyedpi.exe -9 --fake-gen 29 --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
> 
> Так же можете использовать -> 1_russia_blacklist_dnsredir.cmd откройте его с помощью блокнота, и отредактируйте его Пример: start "" goodbyedpi.exe -9 -e1 -q --fake-gen 29 --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25 --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

Всё получилось! Спасибо большое ! Понял как редактировать ( 116 символов и что в итоге заменять ) СПАСИБО!!! Дай вам Бог крепкого здоровья и вашим родным людям.

**Comment by Tolokrov** [comment]
> Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex
> 
> Пример: --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25
> 
> Так же замените значение --fake-gen Пример: --fake-gen 29

Помогло, огромное спасибо!

**Comment by Memfivosfey** [comment]
> > > Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex
> > > Пример: --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25
> > > Так же замените значение --fake-gen Пример: --fake-gen 29
> > 
> > 
> > Подскажите пожалуйста, где именно находится эта строка?
> 
> Убедитесь, что вы используете последнюю версию программы: [goodbyedpi-0.2.3rc3-2.zip](https://github.com/ValdikSS/GoodbyeDPI/releases/download/0.2.3rc3/goodbyedpi-0.2.3rc3-2.zip)
> 
> внутри папки программы находится файл -> 1_russia_blacklist_YOUTUBE.cmd (если он отсутствует у вас это значит что вы используете устаревшую версию программы) откройте его с помощью блокнота, и отредактируйте его Пример: start "" goodbyedpi.exe -9 --fake-gen 29 --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
> 
> Так же можете использовать -> 1_russia_blacklist_dnsredir.cmd откройте его с помощью блокнота, и отредактируйте его Пример: start "" goodbyedpi.exe -9 -e1 -q --fake-gen 29 --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25 --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt



Не знаю, как это работает!!! Но оно сработало)) Спасибо! Выручили!
![22-09-2024 03-06](https://github.com/user-attachments/assets/c1f0a457-7dcb-4633-a779-84544a6d1540)

**Comment by PomalinTheCat** [comment]
спасибо shuriklol это действительно сработало

**Comment by qiwixe** [comment]
22.09 01:10 починил заменой на вот это 
-9 -e1 -q --fake-gen 11 --fake-from-hex 0f0babf6244910c195fa630cec6f5c2f793ab0d7f32c12db77cf89c7b342bbe0192cfe38dc4bf122f6646b69cde211f8d8951a164662c974a64040dcc58f87828f5c1d0523498790de7026487ac62d05

**Comment by Yakim3396** [comment]
Я просто --fake-gen 5 на 29 поменял и поехало)

**Comment by Varkaus** [comment]
МТС  тоже отрубил около 23:00 21.09.  метод @shuriklol помог, спасибо!

**Comment by Capewearer** [comment]
Что-то не робит, ну и ладно, дождусь патчей.

**Comment by Varkaus** [comment]
Походу Роскомпозор, Ростелеком и МТС в одно время положил через тспу.

**Comment by lynrayy** [comment]
Опять наебнулся
Ростелеком москва

**Comment by AntiAnti** [comment]
Сегодня на Ростелеком-Москва срезали. Замена hex-кода помогла.

**Comment by lynrayy** [comment]
`.exe\" -9 -e1 -q --fake-gen 29`

Вот такое изменение вроде как помогло

**Comment by Ho0LiGaN82** [comment]
У многих работает и **-1** параметр, меняем -9 на единицу в  **1_russia_blacklist_YOUTUBE.cmd**

**Comment by LeniumSo** [comment]
> Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex
> 
> Пример: --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25
> 
> Так же замените значение --fake-gen Пример: --fake-gen 29

Хм.... по моим подсчётам, у них уходит примерно 3 дня на разгадывание и комбинация hex и fake-gen перестают работать. 

Неплохо было бы, чтобы прога могла сама генерить эти значения с некоторым интервалом.

**Comment by s3l3ba** [comment]
не могу внести изменения через блокнот , не даёт сохранить файл , в ошибке пишет что отсутствуют разрешения на открытие этого файла, обратитесь к владельцу файла , или администратору сети,

**Comment by Fuwiz** [comment]
Помогла смена fake-from-hex и fake-gen, спасибо shuriklol. И на это они тратят 60 миллиардрв рублей, мда

**Comment by qweaeqew** [comment]
> Помогла смена fake-from-hex и fake-gen, спасибо shuriklol. И на это они тратят 60 миллиардрв рублей, мда

не каркай, вдруг они начнут реально эффективно использовать деньги и ресурсы

**Comment by Norrino** [comment]
> > Помогла смена fake-from-hex и fake-gen, спасибо shuriklol. И на это они тратят 60 миллиардрв рублей, мда
> 
> не каркай, вдруг они начнут реально эффективно использовать деньги и ресурсы

Тогда им придётся закрыть РКН и уволить половину депутатов.

**Comment by qweaeqew** [comment]
> > > Помогла смена fake-from-hex и fake-gen, спасибо shuriklol. И на это они тратят 60 миллиардрв рублей, мда
> > 
> > 
> > не каркай, вдруг они начнут реально эффективно использовать деньги и ресурсы
> 
> Тогда им придётся закрыть РКН и уволить половину депутатов.

я про РКН, вдруг все 60 миллиардов реально уйдут на блокировку способов обхода цензуры? конечно маловероятно, но всё таки

**Comment by Dexchrono** [comment]
> Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex
> 
> Пример: --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25
> 
> Так же замените значение --fake-gen Пример: --fake-gen 29

Всё работает, подтверждаю )

**Comment by Fuwiz** [comment]
> > > > Помогла смена fake-from-hex и fake-gen, спасибо shuriklol. И на это они тратят 60 миллиардрв рублей, мда
> > > 
> > > 
> > > не каркай, вдруг они начнут реально эффективно использовать деньги и ресурсы
> > 
> > 
> > Тогда им придётся закрыть РКН и уволить половину депутатов.
> 
> я про РКН, вдруг все 60 миллиардов реально уйдут на блокировку способов обхода цензуры? конечно маловероятно, но всё таки

Ничего они не смогут сделать и никакие деньги им не помогут, уже понятно всё, они одну программу от аниме девочки месяцами заблокировать нормально не могут даже

**Comment by Capewearer** [comment]
> > > > Помогла смена fake-from-hex и fake-gen, спасибо shuriklol. И на это они тратят 60 миллиардрв рублей, мда
> > > 
> > > 
> > > не каркай, вдруг они начнут реально эффективно использовать деньги и ресурсы
> > 
> > 
> > Тогда им придётся закрыть РКН и уволить половину депутатов.
> 
> я про РКН, вдруг все 60 миллиардов реально уйдут на блокировку способов обхода цензуры? конечно маловероятно, но всё таки

Парадокс блокировок в том, что даже Китай с его несравнимо большими бюджетами и специалистами не может заблокировать всё и вся.
Единственный способ заблочить интернет - это выдавать к нему доступ по карточкам, в университетских библиотеках, как это сделано в КНДР.

**Comment by qweaeqew** [comment]
> > > > > Помогла смена fake-from-hex и fake-gen, спасибо shuriklol. И на это они тратят 60 миллиардрв рублей, мда
> > > > 
> > > > 
> > > > не каркай, вдруг они начнут реально эффективно использовать деньги и ресурсы
> > > 
> > > 
> > > Тогда им придётся закрыть РКН и уволить половину депутатов.
> > 
> > 
> > я про РКН, вдруг все 60 миллиардов реально уйдут на блокировку способов обхода цензуры? конечно маловероятно, но всё таки
> 
> Парадокс блокировок в том, что даже Китай с его несравнимо большими бюджетами и специалистами не может заблокировать всё и вся. Единственный способ заблочить интернет - это выдавать к нему доступ по карточкам, в университетских библиотеках, как это сделано в КНДР.

ну или для выхода в интернет требовать ввода номера и серии паспорта

**Comment by johnnyd-78** [comment]
> не могу внести изменения через блокнот , не даёт сохранить файл , в ошибке пишет что отсутствуют разрешения на открытие этого файла, обратитесь к владельцу файла , или администратору сети,
> 
> p.s я чайник в этом деле , помогите плс))

Нефиг файлы программы распаковывать туда, где прав нет. Распакуйте в Мои документы или на рабочий стол. Или вообще на другой диск (если есть)

**Comment by SerGlushko** [comment]
> Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex
> 
> Пример: --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25
> 
> Так же замените значение --fake-gen Пример: --fake-gen 29

Почему-то ломает дискорд, невозможно присоединиться к звонкам, есть у кого-нибудь идеи, в чем проблема? Выключаю службу, сразу работает нормально

**Comment by lynrayy** [comment]
У меня войс в дискорде рабооает

**Comment by SerGlushko** [comment]
Со строкой 
`-9 --fake-gen 29 --fake-from-hex 7d329dd7dd17d266367054730ddd4dc119dbdd380dc3d5ca48c52baa472d02dd8e5ba82a99b28be4dfa08b7348ad58dad13d5a06bfb3d2ada23e6da12b7f2c12c0e4660f48939001ba831a9e7e5e0370176e0fabd6d5c775e415083747ccb90a3ffb53c3a0834a01fc48a8e80672b7e0e287f10eb812da8d71690ff57770578fdcc09923b6cf7e7cb02195300aa6dd53a5495a21940508f45d8e45e1525a221c97222085216d6e6bc4a8a80c11690e204558fdb59d7a0e165117b6f296b2b20b4dabebd2b14c0c365a6251ef4fb07e44c403dea37a3d8d7a1c207228be012380010b835f025a73fc83be5bfc79cf31a1f01ee2d1ba50f79e83fafb30600ad841ca90a9cdc1d5523ea954d49af327dee4ff6aa4b24518fd608f759404221291545432`

Невозможно подключиться к звонкам в дискорде, при закрытии приложения оно виснет на проверке обновления

**Comment by Psycho-A** [comment]
> Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex
> 
> Пример: --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25
> 
> Так же замените значение --fake-gen Пример: --fake-gen 29


Интересно, а возможно ли добавить эти процедуры прямо в бинарник GoodbyeDPI, чтобы у каждого при запуске были всегда свои данные? Не уверен конечно, что РКН сам алгоритм не пропалят - но это хотя бы немного продлит жизнь...

**Comment by BateauSD** [comment]
Проснулся с самого утра сейчас и тоже перестало работать. Вчера вечером все было ок. И альт и просто ютуб, ноль реакции.

**Comment by BateauSD** [comment]
платный впн тоже черный экран выдает, прокси тем более, хз что эти мудни там навертели снова

**Comment by andreybexus** [comment]
Было круто, если бы HEX и gen генерировались автоматически

**Comment by MrKart0plya** [comment]
> > Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex
> > Пример: --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25
> > Так же замените значение --fake-gen Пример: --fake-gen 29
> 
> Интересно, а возможно ли добавить эти процедуры прямо в бинарник GoodbyeDPI, чтобы у каждого при запуске были всегда свои данные? Не уверен конечно, что РКН сам алгоритм не пропалят - но это хотя бы немного продлит жизнь...

Более чем возможно. Простой рандом. Проблема скорее в том, что, например у меня, даже с новым сгенерированым hex'ом не работало, пока не поставил другой fake gen. А их всего 30.

**Comment by myrnavero** [comment]
> Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex
> 
> Пример: --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25
> 
> Так же замените значение --fake-gen Пример: --fake-gen 29

Благодарю, все работает!

**Comment by APECR-Username** [comment]
С коротким hex'ом (32) тоже работает

**Comment by BateauSD** [comment]
Попробовал хекс, пару часов вроде поработало сейчас снова затупы пошли. Владивосток, Альянс, поменял провайдера таки с Ростелекома но нихрена не дало.

**Comment by johnnyd-78** [comment]
Менять сейчас РТК на какого-то ноунейма, кторых РКН ипет в хвост и гриву - конечно "мудрое" решение :)

**Comment by johnnyd-78** [comment]
> Невозможно подключиться к звонкам в дискорде

Голос в дискорде работает по UDP, гудбай тут не поможет, но может zapret справится, там вроде есть опция "любой протокол"

**Comment by BateauSD** [comment]
> Менять сейчас РТК на какого-то ноунейма, кторых РКН ипет в хвост и гриву - конечно "мудрое" решение :) У них самые сильные и порой непробиваемые ничем блокировки ютуба

Этот РТК работал через задницу, последние года пол и игры перестали без ВПНа работать нужные мне и часто вылеты были, а Альянс не такой и нонейм, один из первых провайдеров Владивостока уже 20 лет как тут. И с ним к слову те же игры хотя бы работают, а вот ютуб уже сложно смотреть без проксей или впна, по 1000 в месяц уходит на оплату. Гудбай бесплатно но как видно уже не всегда работает, предпочитаю все же его.

**Comment by johnnyd-78** [comment]
О, какой важный провайдер, первый парень на деревне прямо ) Его то РКН точно не тронет. Ну тут уж или шашечки или ехать - игры или 1000 рублей. Я бы лучше выбрал 1000 рублей потраченные на что-нибудь полезное, вы выбрали по-другому. Платите и дальше, только каяться не надо - это другая тема ))

**Comment by BateauSD** [comment]
> О, какой важный провайдер, первый парень на деревне прямо ) Его то РКН точно не тронет. Ну тут уж или шашечки или ехать - игры или 1000 рублей. Я бы лучше выбрал 1000 рублей потраченные на что-нибудь полезное, вы выбрали по-другому. Платите и дальше, только каяться не надо - это другая тема ))

Как бы и платил но и протон и хайдми и бланк отлетели еще неделю назад. 
Перестали даже с VLESS работать. Так что придется ждать как гудбай пофиксится.

**Comment by Andrasolin** [comment]
а че делать то?  когда кроме Ростелекома нет :(

**Comment by ArtemChik103** [comment]
> Требуется изменить значение в строке хекса на своё, можете сгенерировать тут (116 символов) -> https://www.browserling.com/tools/random-hex
> 
> Пример: --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25
> 
> Так же замените значение --fake-gen Пример: --fake-gen 29

БРО ПОМОГЛО ЧТО

**Comment by dima78123** [comment]
1_russia_blacklist_YOUTUBE.cmd   открываем ставим туда --fake-gen 29 вместо  того что стоит у меня всё заработала !!!

**Comment by Dron333-sys** [comment]
Решение от shuriklol помогло, спасибо

**Comment by Mikle-Bond** [comment]
Помогло `-9 -e1 -q --fake-gen 16` и новый fake-from-hex

**Comment by Andrasolin** [comment]
> Решение от **shuriklol** помогло, спасибо

+++ попробовал, всё круто!

**Comment by Parovozik** [comment]
Вчера в районе 23-00 отвалился гудбай. Частично помогла смена режима с 9 на 11 (ют ожил в хроме, но например в лисе и на телеке, который берет интернет с пк, так и не работало). Полностью починилось по рекомендации выше с генерацией нового хэша и фейкген 22 (а режим вернул обратно на 9ку).
