### ISSUE TITLE
YouTube всё равно зависает при новейшей версии GoodByeDPI

### ISSUE THREAD

**Issue by timcodebreaker** [ValdikSS/GoodbyeDPI#653]
### Operating system / операционная система

Windows 10 Pro 21H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

При запуске видео на YouTube с GoodByeDPI оно НУ ОЧЕНЬ ДОЛГО ГРУЗИТЬСЯ, а потом работает, но перемотка такая же долгая. Пробовал в каждом файле менять -9 на цифры от -1 до -8 и -11 и ничего не помогло. Так же пробовал открыть каждый файл от имени администратора - тоже не помогло. Я уже не знаю что делать, может дело в Ростелекоме? Умоляю, помогите!!!

**Comment by VladPedro** [comment]
буквально сейчас тоже перестал работать ютуб. крепись, бро. эта битва будет долгой...

**Comment by Lockal** [comment]
Тоже буквально сейчас перестало работать. Как это надоело

**Comment by geoniz** [comment]
Та же фигня, что-то мусор из РКН опять поправил в тспу, 1_russia_blacklist_YOUTUBE.cmd и ALT перестали работать буквально 20 минут назад, уроды.

**Comment by Gxtod** [comment]
Да хватит плодить ветки, вот ответ, это решение помогает: https://github.com/ValdikSS/GoodbyeDPI/issues/652#issuecomment-2365244269

Жаль автор слоупок и обновит ГудбайДПИ наверное через неделю после срачей и 100500+ однотипных тем и сообщений.

**Вывод:** ОБНОВЛЯЙТЕ СУКА (ЛИТЕРАТУРНОЕ СЛОВО) - **ЧАЩЕ**

P.S. Что такое слово "чаще" нужно объяснять?

**Comment by BigCoinX** [comment]
Мне помогло вот это 
https://github.com/ValdikSS/GoodbyeDPI/issues/652#issuecomment-2365244269

**Comment by geoniz** [comment]
> Да хватит плодить ветки, вот ответ, это решение помогает: [#652 (comment)](https://github.com/ValdikSS/GoodbyeDPI/issues/652#issuecomment-2365244269)
> 
> Жаль автор слоупок и обновит ГудбайДПИ наверное через неделю после срачей и 100500+ однотипных тем и сообщений.
> 
> **Вывод:** ОБНОВЛЯЙТЕ СУКА (ЛИТЕРАТУРНОЕ СЛОВО) - **ЧАЩЕ**
> 
> P.S. Что такое слово "чаще" нужно объяснять?

Автору за софт не платят, он делает всё на добровольной основе, не думаю, что вы в праве что-то требовать от него, прошу прощения за оффтоп.

**Comment by Norrino** [comment]
> Да хватит плодить ветки, вот ответ, это решение помогает: [#652 (comment)](https://github.com/ValdikSS/GoodbyeDPI/issues/652#issuecomment-2365244269)
> 
> Жаль автор слоупок и обновит ГудбайДПИ наверное через неделю после срачей и 100500+ однотипных тем и сообщений.
> 
> **Вывод:** ОБНОВЛЯЙТЕ СУКА (ЛИТЕРАТУРНОЕ СЛОВО) - **ЧАЩЕ**
> 
> P.S. Что такое слово "чаще" нужно объяснять?

Не. Не помогло.

**Comment by Ellaemi** [comment]
для файлов:
- service_install_russia_blacklist_YOUTUBE (13 строка)
- 1_russia_blacklist_YOUTUBE (8 строка)

изменить значения в обоих файлов, номера строк написаны где искать. После goodbyedpi.exe будет значение типа "goodbyedpi.exe -1 --fake-gen 5" вот эти "-1" меняете на "-9" . 
Также можно попробовать -5 или -6. Лично мне помогло на -1 изменить.

**Comment by 1NFERR** [comment]
Ага

**Comment by Norrino** [comment]
Хм... не менял ничего больше. Вкл-выкл пару раз. Просто так само заработало.

**Comment by 1NFERR** [comment]
Способ @Gxtod помог

**Comment by 1NFERR** [comment]
> Да хватит плодить ветки, вот ответ, это решение помогает: [#652 (comment)](https://github.com/ValdikSS/GoodbyeDPI/issues/652#issuecomment-2365244269)
> 
> Жаль автор слоупок и обновит ГудбайДПИ наверное через неделю после срачей и 100500+ однотипных тем и сообщений.
> 
> **Вывод:** ОБНОВЛЯЙТЕ СУКА (ЛИТЕРАТУРНОЕ СЛОВО) - **ЧАЩЕ**
> 
> P.S. Что такое слово "чаще" нужно объяснять?

Помогло. Благодарю

**Comment by timcodebreaker** [comment]
> Да хватит плодить ветки, вот ответ, это решение помогает: https://github.com/ValdikSS/GoodbyeDPI/issues/652#issuecomment-2365244269
> 
> Жаль автор слоупок и обновит ГудбайДПИ наверное через неделю после срачей и 100500+ однотипных тем и сообщений.
> 
> **Вывод:** ОБНОВЛЯЙТЕ СУКА (ЛИТЕРАТУРНОЕ СЛОВО) - **ЧАЩЕ**
> 
> P.S. Что такое слово "чаще" нужно объяснять? 

Я даже это пробовал, всё равно не работает. Думаешь я не облазил весь Интернет?

**Comment by timcodebreaker** [comment]
> для файлов:
> - service_install_russia_blacklist_YOUTUBE (13 строка)
> - 1_russia_blacklist_YOUTUBE (8 строка)
> 
> изменить значения в **обоих файлах**, номера строк написаны где искать. После goodbyedpi.exe будет значение типа `goodbyedpi.exe -1 --fake-gen 5` вот эти `-1` меняете на `-9` . 
> Также можно попробовать `-5` или `-6`. Лично мне помогло на `-1` изменить.
> 
> Далее обязательно запустить `service_install_russia_blacklist_YOUTUBE` от имени администратора

Я же написал, что пробовал это - всё равно не работает. Походу дело в моём провайдере, а именно в Ростелекоме 😕

**Comment by Norrino** [comment]
> > для файлов:
> > 
> > * service_install_russia_blacklist_YOUTUBE (13 строка)
> > * 1_russia_blacklist_YOUTUBE (8 строка)
> > 
> > изменить значения в **обоих файлах**, номера строк написаны где искать. После goodbyedpi.exe будет значение типа `goodbyedpi.exe -1 --fake-gen 5` вот эти `-1` меняете на `-9` .
> > Также можно попробовать `-5` или `-6`. Лично мне помогло на `-1` изменить.
> > Далее обязательно запустить `service_install_russia_blacklist_YOUTUBE` от имени администратора
> 
> Я же написал, что пробовал это - всё равно не работает. Походу дело в моём провайдере, а именно в Ростелекоме 😕

-9 --fake-gen 29 и рандомный hex - у меня всё заработало. Хотя! Хотя не работало 3 раза. На 4й раз запустил не меняя ничего и пошло.

**Comment by noremac09** [comment]
Билайн, работает такая конфигурация.

`@ECHO OFF
PUSHD "%~dp0"
set _arch=x86
IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)
PUSHD "%_arch%"

start "" goodbyedpi.exe -5 -e1 -q --fake-gen 29 --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

POPD
POPD
`

**Comment by timcodebreaker** [comment]
> Билайн, работает такая конфигурация.
> 
> ```
> @ECHO OFF
> PUSHD "%~dp0"
> set _arch=x86
> IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
> IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)
> PUSHD "%_arch%"
> 
> start "" goodbyedpi.exe -5 -e1 -q --fake-gen 29 --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
> 
> POPD
> POPD
> ```

Вряд ли у меня на Ростелекоме сработает, но попробую. Это в каком файле?

**Comment by noremac09** [comment]
> > Билайн, работает такая конфигурация.
> > ```
> > @ECHO OFF
> > PUSHD "%~dp0"
> > set _arch=x86
> > IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
> > IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)
> > PUSHD "%_arch%"
> > 
> > start "" goodbyedpi.exe -5 -e1 -q --fake-gen 29 --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
> > 
> > POPD
> > POPD
> > ```
> 
> Вряд ли у меня на Ростелекоме сработает, но попробую. Это в каком файле?

1_russia_blacklist_YOUTUBE_ALT.cmd

**Comment by timcodebreaker** [comment]
> > > для файлов:
> > > 
> > > * service_install_russia_blacklist_YOUTUBE (13 строка)
> > > * 1_russia_blacklist_YOUTUBE (8 строка)
> > > 
> > > изменить значения в **обоих файлах**, номера строк написаны где искать. После goodbyedpi.exe будет значение типа `goodbyedpi.exe -1 --fake-gen 5` вот эти `-1` меняете на `-9` .
> > > Также можно попробовать `-5` или `-6`. Лично мне помогло на `-1` изменить.
> > > Далее обязательно запустить `service_install_russia_blacklist_YOUTUBE` от имени администратора
> > 
> > Я же написал, что пробовал это - всё равно не работает. Походу дело в моём провайдере, а именно в Ростелекоме 😕
> 
> -9 --fake-gen 29 и рандомный hex - у меня всё заработало. Хотя! Хотя не работало 3 раза. На 4й раз запустил не меняя ничего и пошло.

Окей, завтра ещё раз попробую этот способ. Но скорее всего назло это уже пофиксят

**Comment by V3nilla** [comment]
> Билайн, работает такая конфигурация.
> 
> ```
> @ECHO OFF
> PUSHD "%~dp0"
> set _arch=x86
> IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
> IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)
> PUSHD "%_arch%"
> 
> start "" goodbyedpi.exe -5 -e1 -q --fake-gen 29 --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
> 
> POPD
> POPD
> ```

Подтверждаю. Работает на Ростелекоме тоже

**Comment by KrackensCorp** [comment]
В 1_russia_blacklist_YOUTUBE_ALT записал -9 -e1 -q --fake-gen 29 и рандомный хекс - заработало

**Comment by Decavoid** [comment]
На билайне сработало в `1_russia_blacklist_YOUTUBE_ALT.cmd` удаление ключа `--fake-from-hex 16...00` И замена значения ключа `--fake-gen` с 5 на 15:

```
start "" goodbyedpi.exe -5 -e1 -q --fake-gen 15 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
```
Секунд 10 крутится загрузка, но дальше видео работает нормально.

**Comment by vault-thirteen** [comment]
Предлагаю Валдику добавить в свою программу генератор рандомных байтов, чтобы усложнить жизнь запрещателям интернетов.

**Comment by timcodebreaker** [comment]
> Предлагаю Валдику добавить в свою программу генератор рандомных байтов, чтобы усложнить жизнь запрещателям интернетов.

Да удивительно что он вообще прогу обновляет

**Comment by Yokayo** [comment]
> Да хватит плодить ветки, вот ответ, это решение помогает: [#652 (comment)](https://github.com/ValdikSS/GoodbyeDPI/issues/652#issuecomment-2365244269)
> 
> Жаль автор слоупок и обновит ГудбайДПИ наверное через неделю после срачей и 100500+ однотипных тем и сообщений.
> 
> **Вывод:** ОБНОВЛЯЙТЕ СУКА (ЛИТЕРАТУРНОЕ СЛОВО) - **ЧАЩЕ**
> 
> P.S. Что такое слово "чаще" нужно объяснять?

Поддерживаю оратора выше, автор нам ничем по сути не обязан. Стоит его поблагодарить за то, что он этим занимается, щас буквально пол-страны спасает его творение.
Также напоминаю, что программа опенсорс, так что можете сами сделать любое изменение и внести пул реквест, либо вообще сделать свой форк.

**Comment by johnnyd-78** [comment]
Самое смешное - люди даже не понимают, что эти параметры значат - лепят от балды, заработало - надо побежать всем рассказать )))

**Comment by Mesushirabu** [comment]
> в РКН не дебилы сидят

Разве пойдёт нормальный человек в РКН работать?

**Comment by NeuralAIM** [comment]
> > в РКН не дебилы сидят
> 
> Разве пойдёт нормальный человек в РКН работать?

Умные как раз таки не руководствуются моральными принципами. Если платят хорошо, то почему бы и нет?

**Comment by Mesushirabu** [comment]
> Если платят хорошо

РКН не то место где платят хорошо, можешь глянуть вакансии. В региональных отделениях вообще смех, предлагают 40к за полный рабочий день.

**Comment by vlastelin8611** [comment]
> Билайн, работает такая конфигурация.
> 
> ```
> @ECHO OFF
> PUSHD "%~dp0"
> set _arch=x86
> IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
> IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)
> PUSHD "%_arch%"
> 
> start "" goodbyedpi.exe -5 -e1 -q --fake-gen 29 --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
> 
> POPD
> POPD
> ```

подтверждаю работу на домру, спасибо большое

**Comment by johnnyd-78** [comment]
> Предлагаю Валдику добавить в свою программу генератор рандомных байтов, чтобы усложнить жизнь запрещателям интернетов.
Он уже добавлен - называется --fake-gen

**Comment by iv3lord** [comment]
есть тут люди с МГТС у которых проблема была и они смогли ее решить  ? отпишите если есть варианты как пофиксить plz^^

**Comment by johnnyd-78** [comment]
> есть тут люди с МГТС у которых проблема была и они смогли ее решить ? отпишите если есть варианты как пофиксить plz^^

Удалите --fake-from-hex из вашего CMD и увеличивайте значение --fake-gen на единичку, пока не заработает.

**Comment by iv3lord** [comment]
> > есть тут люди с МГТС у которых проблема была и они смогли ее решить ? отпишите если есть варианты как пофиксить plz^^
> 
> Удалите --fake-from-hex вместе с его длинной строкой из вашего CMD и увеличивайте значение --fake-gen на единичку, пока не заработает. Чтобы windivert не перекорежило от частых перезапусков программы, останавливайте его командой sc stop windivert в командной строке от админа, перед каждым внесением правок в конфиг. И браузер перезапускайте

а в каком именно файле cmd нужно перебирать значения fake gen? 
в 1_russia_blacklist_YOUTUBE или 1_russia_blacklist_YOUTUBE_ALT?

**Comment by johnnyd-78** [comment]
В том, которым вы пользовались до этого. Не надо ничего менять кроме удаления фром-хекс и увеличения цифры в фейк-ген

**Comment by iv3lord** [comment]
> В том, которым вы пользовались до этого. Не надо ничего менять кроме удаления фром-хекс и увеличения цифры в фейк-ген

до этого я пользовался старой версией ( с помощью фикса ) но она перестала работать и я скачал самую новую версию и пока что она у меня не работала вообще , с самого начала проблемы (

**Comment by johnnyd-78** [comment]
Понял. Попробуйте сначала с 1_russia_blacklist_YOUTUBE_ALT.cmd

**Comment by vault-thirteen** [comment]
> Удалите --fake-from-hex вместе с его длинной строкой из вашего CMD и увеличивайте значение --fake-gen на единичку, пока не заработает. 
Спасибо за подсказку.

Описание ключа `--fake-gen` вообще не понятно. Значение ключа это размер буффера для мусора или что-то другое ? 

В мануале написано "value of them", что вообще означает "их значение", т.е. "значение пакетов". Не понятно, о каком значении пакетов идёт речь.

**Comment by johnnyd-78** [comment]
Это означает **количество**  То есть к пакету, там где нужно вставить фейк будет прицеплено количество фейков, заданных цифрой. Я уже представляю, как сайты и DPI охренеют от 29 фейков. У меня фейки прицепляются к wrong-seq например, но всего 2 и все работает, возможно пока

**Comment by sibkofeman** [comment]
> Да хватит плодить ветки, вот ответ, это решение помогает: [#652 (comment)](https://github.com/ValdikSS/GoodbyeDPI/issues/652#issuecomment-2365244269)
> 
> Жаль автор слоупок и обновит ГудбайДПИ наверное через неделю после срачей и 100500+ однотипных тем и сообщений.
> 
> **Вывод:** ОБНОВЛЯЙТЕ СУКА (ЛИТЕРАТУРНОЕ СЛОВО) - **ЧАЩЕ**
> 
> P.S. Что такое слово "чаще" нужно объяснять?

Вообще дурачок что ли? Автор тебе не чем не обязан. Скажи спасибо, что вообще выложил в массы решение. Хочешь сделать хорошо сделай сам ты находишься на соответствующей площадке.

**Comment by fyflo** [comment]
```
> @ECHO OFF
> PUSHD "%~dp0"
> set _arch=x86
> IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
> IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)
> PUSHD "%_arch%"
> 
> start "" goodbyedpi.exe -5 -e1 -q --fake-gen 29 --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
> 
> POPD
> POPD
```

По Вашему коду скорректировал файл для сервисов service_install_russia_blacklist_YOUTUBE.cmd
РТК МСК работает

```
@ECHO OFF
PUSHD "%~dp0"
set _arch=x86
IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)

echo This script should be run with administrator privileges.
echo Right click - run as administrator.
echo Press any key if you're running it as administrator.
pause
sc stop "GoodbyeDPI"
sc delete "GoodbyeDPI"
sc create "GoodbyeDPI" binPath= "\"%CD%\%_arch%\goodbyedpi.exe\" -5 -e1 -q --fake-gen 29 --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25 --blacklist \"%CD%\russia-blacklist.txt\" --blacklist \"%CD%\russia-youtube.txt\"" start= "auto"
sc description "GoodbyeDPI" "Passive Deep Packet Inspection blocker and Active DPI circumvention utility"
sc start "GoodbyeDPI"

POPD
```

**Comment by timcodebreaker** [comment]
> > Предлагаю Валдику добавить в свою программу генератор рандомных байтов, чтобы усложнить жизнь запрещателям интернетов.
> 
> Он уже добавлен - называется --fake-gen А все орущие тут "Ура, заработало!" используют один и тот же пакет из --fake-from-hex который недолго проживет

Ну так расскажи свой способ. Ты же думаешь что все в мире прошаренные в компах

**Comment by timcodebreaker** [comment]
> Билайн, работает такая конфигурация.
> 
> ```
> @ECHO OFF
> PUSHD "%~dp0"
> set _arch=x86
> IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
> IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)
> PUSHD "%_arch%"
> 
> start "" goodbyedpi.exe -5 -e1 -q --fake-gen 29 --fake-from-hex f1c48aca82bf0716fe28fc31c87e259b84a489946d5c819809a31471f3a26e4bfb09bcaa8a3fbdabae152e0f1db41f1c4952d480204fc26d2b25 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
> 
> POPD
> POPD
> ```

Спасибо! На Ростелекоме работает. На долго ли?

**Comment by HALMAO** [comment]
Попробуйте запустить 2_any_country_dnsredir. Лично мне помогло
