### ISSUE TITLE
не грузит видео на youtube, хоть сам сайт очень быстро работает

### ISSUE THREAD

**Issue by RaniK-s** [ValdikSS/GoodbyeDPI#654]
### Operating system / операционная система

Windows 11

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

буквально на днях установил самую новую версию программы, начало все грузиться(причем я заметил такую особенность, что если я не перезайду на другую любую вкладку, и не вернусь обратно на ютуб, то само видео не начнет грузиться). И вот сейчас опять все тоже самое, просто видео не загружаеться, хотя весь остальной сайт работает. (запускал что и 1_russia_blacklist_YOUTUBE.cmd, что и 1_russia_blacklist_YOUTUBE.ALTcmd, в итоге до определенного момента работало на втором варианте)

**Comment by johnnyd-78** [comment]
Зачем вы лепите одинаковые темы? Хотите чтобы автор опять всем закрыл возможность тут что-то писать?

**Comment by iv3lord** [comment]
есть тут люди с МГТС у которых проблема была и они смогли ее решить ? отпишите если есть варианты как пофиксить plz^^

**Comment by ruskotwo** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/652#issuecomment-2365244269

**Comment by Demos25** [comment]
> есть тут люди с МГТС у которых проблема была и они смогли ее решить ? отпишите если есть варианты как пофиксить plz^^
В
blacklist_YOUTUBE_ALT
Заменить
-5 -e1 -q
На
-4 -e1 -q

**Comment by johnnyd-78** [comment]
Ахахха, так и знал что -r и -s как-то сбивают очередную блокировку )

**Comment by TheMagicPe4enka** [comment]
Провел пару тестов, за основу взял флаги режима -9:
 -f 2 -e 2 --wrong-seq --wrong-chksum --reverse-frag --max-payload -q
 и флаги режима -4:
 -p -r -s
Результат:
1) Из-за --reverse-frag перестали грузиться видео, поэтому я убрал его, но перестали грузиться превью видео и прочие изображения.
добавил флаг:
 -r
Результат:
2) Изображения вновь грузятся.
Готовое решение:
Заменить в 1_russia_blacklist_YOUTUBE.cmd
флаг -9 на:
-f 2 -e 2 --wrong-seq --wrong-chksum --max-payload -q -r
P.s:
Режим -4 тоже работает

> > есть тут люди с МГТС у которых проблема была и они смогли ее решить ? отпишите если есть варианты как пофиксить plz^^
> 
> В blacklist_YOUTUBE_ALT Заменить -5 -e1 -q На -4 -e1 -q

**Comment by Oidaho** [comment]
Предлагаю создать топик, в котором все будут целенаправленно писать о рабочих\нерабочих стратегиях.

@ValdikSS , я думаю можно организовать что-то подонобное.
Многие пользователи GoodByeDPI даже не являются программистами\\сетевиками, пришли с гайдов ютуба.

Централизованное "обсуждение" в духе "Снова ничо не работает, кто придумал как обойти?"

**Comment by XaksFlaX** [comment]
Москва. МГТС. Порядок того, что нужно попробовать, чтобы устранить загрузку видео:
Я запускаю только 1_russia_blacklist_YOUTUBE_ALT (и менять нужно только в нем). Если не работает пункт, переходим к следующему, не откатывая изменения.
1) заменить цифру после --fake-gen (по умолчанию 5) на 29
2) заменить значение после --fake-from-hex на любое свое (проще всего сгенерировать тут: https://www.browserling.com/tools/random-hex не забыв установить длину в 116 символов)
3) заменить первую цифру после goodbyedpi.exe (по умолчанию -5) на -9

**Comment by TheRealRyi** [comment]
А для Омск?

**Comment by crefter** [comment]
@XaksFlaX Помогло для Ростелеком, Кемеровская область

**Comment by xrLil-Batya** [comment]
> Москва. МГТС. Порядок того, что нужно попробовать, чтобы устранить загрузку видео: Я запускаю только 1_russia_blacklist_YOUTUBE_ALT (и менять нужно только в нем любым блокнотом). Если не работает пункт, переходим к следующему, не откатывая изменения.
> 
> 1. заменить цифру после --fake-gen (по умолчанию 5) на 29
> 2. заменить значение после --fake-from-hex на любое свое (проще всего сгенерировать тут: https://www.browserling.com/tools/random-hex не забыв установить длину в 116 символов)
> 3. заменить первую цифру после goodbyedpi.exe (по умолчанию -5) на -9

Заработало для Ростелекома, Удмуртская Республика

**Comment by lednik** [comment]
> Ростелеком, Кемеровская область Провел пару тестов, за основу взял флаги режима -9: -f 2 -e 2 --wrong-seq --wrong-chksum --reverse-frag --max-payload -q и флаги режима -4: -p -r -s Результат:
> 
> 1. Из-за --reverse-frag перестали грузиться видео, поэтому я убрал его, но перестали грузиться превью видео и прочие изображения.
>    добавил флаг:
>    -r
>    Результат:
> 2. Изображения вновь грузятся.
>    Готовое решение:
>    Заменить в 1_russia_blacklist_YOUTUBE.cmd
>    флаг -9 на:
>    -f 2 -e 2 --wrong-seq --wrong-chksum --max-payload -q -r
>    P.s:
>    Режим -4 тоже работает
> 
> > > есть тут люди с МГТС у которых проблема была и они смогли ее решить ? отпишите если есть варианты как пофиксить plz^^
> > 
> > 
> > В blacklist_YOUTUBE_ALT Заменить -5 -e1 -q На -4 -e1 -q

А для томской области надо какой-то другой параметр? По твоему варику не выходит

**Comment by Diklofozzz1** [comment]
@lednik 

> > Москва. МГТС. Порядок того, что нужно попробовать, чтобы устранить загрузку видео: Я запускаю только 1_russia_blacklist_YOUTUBE_ALT (и менять нужно только в нем любым блокнотом). Если не работает пункт, переходим к следующему, не откатывая изменения.
> > 
> > 1. заменить цифру после --fake-gen (по умолчанию 5) на 29
> > 2. заменить значение после --fake-from-hex на любое свое (проще всего сгенерировать тут: https://www.browserling.com/tools/random-hex не забыв установить длину в 116 символов)
> > 3. заменить первую цифру после goodbyedpi.exe (по умолчанию -5) на -9
> 
> Заработало для Ростелекома, Удмуртская Республика

Для ТО работает

**Comment by lednik** [comment]
> Для ТО работает

Можете помочь? я может что-то не так делаю? Если не трудно, мой тг @ledengskiy

**Comment by BummppY** [comment]
> Москва. МГТС. Порядок того, что нужно попробовать, чтобы устранить загрузку видео: Я запускаю только 1_russia_blacklist_YOUTUBE_ALT (и менять нужно только в любом блокноте). Если не работает пункт, переходим к следующему, не откатывая изменений.
> 
> 1. заменить цифру после --fake-gen (по умолчанию 5) на 29
> 2. значение после --fake-from-hex на любое свое (проще всего сгенерировать тут: https://www.browserling.com/tools/random-hex не забыв установить длину в 116 символов)
> 3. восстановить первую цифру после Goodbyedpi.exe (по умолчанию -5) на -9

МСК Ростелеком - помогло

**Comment by louise9483** [comment]
> Москва. МГТС. Порядок того, что нужно попробовать, чтобы устранить загрузку видео: Я запускаю только 1_russia_blacklist_YOUTUBE_ALT (и менять нужно только в нем любым блокнотом). Если не работает пункт, переходим к следующему, не откатывая изменения.
> 
> 1. заменить цифру после --fake-gen (по умолчанию 5) на 29
> 2. заменить значение после --fake-from-hex на любое свое (проще всего сгенерировать тут: https://www.browserling.com/tools/random-hex не забыв установить длину в 116 символов)
> 3. заменить первую цифру после goodbyedpi.exe (по умолчанию -5) на -9

Казань Ростелеком - тож помогло

**Comment by louise9483** [comment]
> > Для ТО работает
> 
> Можете помочь? я может что-то не так делаю? Если не трудно, мой тг @ledengskiy .В свою очередь подробно распишу остальным, таким же как я

если тебе нужен ютуб - просто установи расширение юбуст, оно до сих пор работает
