### ISSUE TITLE
Работает Youtube, но не работают другие заблокированные сайты.

### ISSUE THREAD

**Issue by Ridgital** [ValdikSS/GoodbyeDPI#657]
### Operating system / операционная система

Windows 10 20H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Примерно неделю на GDPI работает только Ютуб, либо только остальные заблокированные сайты. После скачивания обновления и фикса через HEX числа у меня работает только Ютуб. Параметры youtube.CMD следующие 
-9 -e1 -q --fake-gen 29
Через эти параметры соответственно работает только Ютаб.
Для работы же других сайтов приходится закрывать обычный cmd и открывать youtube_alt, через который уже спокойно открывается Твиттер, Рутрекер и остальные, ютуб тоже открывается но грузит только сам сайт и превьюшки. Пробовал как то редактировать youtube альт, но всё сводится к тому, что работает только Ютуб, по итогу для других сайтов стал использовать стандартный alt cmd без изменений. Из-за этого постоянно приходится переключаться между CMD для каждого сайта отдельно. Знаю, что привыкнуть можно, но хотелось бы как сделать так, чтобы всё работало сразу через единый CMD.

**Comment by PuroOfficial** [comment]
вы пробовали установить исправленную версию или [AngryHammer](https://github.com/PuroOfficial/AngryHammer)?

**Comment by PuroOfficial** [comment]
> вы пробовали установить исправленную версию или [AngryHammer](https://github.com/PuroOfficial/AngryHammer)?

порекомендуйте ознакомиться с предыдущими проблемами в поисках возможных решений

**Comment by Ridgital** [comment]
> вы пробовали установить исправленную версию или [AngryHammer](https://github.com/PuroOfficial/AngryHammer)?

Нет, впервые про AngryHammer слышу. А какую исправленную версию вы имеете в виду ?

**Comment by Ridgital** [comment]
Нет, ни исправленная версия, ни AH не помогли. Всё так же, ютуб работает, от оригинального youtube.cmd, всё остальное от youtube_alt.cmd. Я думал может у кого похожая проблема есть, но раз уже ветку закрыли, то бесполезно вообще даже справшивать...

**Comment by Ridgital** [comment]
В общем проблема вся в том, что Ютуб работает при настройке - 9, все остальные сайты только при - 5 -q. Что с этим делать вообще не понятно.

**Comment by johnnyd-78** [comment]
Запустить 2 копии программы, у одной такие настройки и блэклист ютуба, у другой - другие настройки и блэклист твиттеров и прочего. Все это можно сделать из 1 CMD

**Comment by MrKart0plya** [comment]
> В общем проблема вся в том, что Ютуб работает при настройке - 9, все остальные сайты только при - 5 -q. Что с этим делать вообще не понятно.

Временным решением - прописать 2 старта в батнике и разбить блеклисты. Например:
`start "" goodbyedpi.exe _Рабочие параметры для сайтов_ --blacklist ..\russia-blacklist.txt`
`start "" goodbyedpi.exe _Рабочие параметры для ютуба_  --blacklist ..\russia-youtube.txt`

**Comment by Ridgital** [comment]
> Запустить 2 копии программы, у одной такие настройки и блэклист ютуба, у другой - другие настройки и блэклист твиттеров и прочего. Все это можно сделать из 1 CMD

Понял, спасибо попробую

**Comment by Ridgital** [comment]
> > В общем проблема вся в том, что Ютуб работает при настройке - 9, все остальные сайты только при - 5 -q. Что с этим делать вообще не понятно.
> 
> Временным решением - прописать 2 старта в батнике и разбить блеклисты. Например: `start "" goodbyedpi.exe *Рабочие параметры для сайтов* --blacklist ..\russia-blacklist.txt` `start "" goodbyedpi.exe *Рабочие параметры для ютуба* --blacklist ..\russia-youtube.txt`

Спасибо, попробую

**Comment by Ridgital** [comment]
Да, способ рабочий.  MrKart0plya и johnnyd-78 огромное вам спасибо :)
