### ISSUE TITLE
обход ютуба (в том числе альтернативный) перестал работать

### ISSUE THREAD

**Issue by IshuCute** [ValdikSS/GoodbyeDPI#658]
### Operating system / операционная система

Win 11

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

просто не работает, видео не грузятся

**Comment by HOOTORO** [comment]
Аналогично. Провайдер МТС(МГТС)
Помогли проставленые руками аргументы 
`-e1 -f1 -q`

**Comment by Rosschus** [comment]
Ростелеком, аналогично

**Comment by loroxnya** [comment]
Москва МГТС
В 1_russia_blacklist_YOUTUBE_ALT замените
-5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116

**Comment by v2lorde** [comment]
> Москва МГТС В 1_russia_blacklist_YOUTUBE_ALT замените -5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116

помогло. Спасибо

**Comment by Foxyz1302** [comment]
То же самое на Дом.ру СПБ

> Москва МГТС В 1_russia_blacklist_YOUTUBE_ALT замените -5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116

Мне видимо не помогло

**Comment by ledbsd** [comment]
> Москва МГТС В 1_russia_blacklist_YOUTUBE_ALT замените -5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116

спасибо!

**Comment by VLAGUERT5** [comment]
> Москва МГТС В 1_russia_blacklist_YOUTUBE_ALT замените -5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116
что такое длинна nex?

**Comment by 1vanK** [comment]
Ну что-то вообще конечная, настройки никакие не помогают, даже с https://www.browserling.com/tools/random-hex

**Comment by 1vanK** [comment]
Зато рутрекер стал работать без гудбая, все силы на оборону от ютуба!

**Comment by Mike-Karn** [comment]
> > Москва МГТС В 1_russia_blacklist_YOUTUBE_ALT замените -5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116
> 
> что такое длинна nex?

В генераторе HEX ставишь длину 116, "How many digits? -116".

**Comment by SirOlegsiy** [comment]
> Москва МГТС В 1_russia_blacklist_YOUTUBE_ALT замените -5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116

Ростелеком (СПб). Помогло. Спасибо.

**Comment by aSxDox** [comment]
> Ну что-то вообще конечная, настройки никакие не помогают, даже с https://www.browserling.com/tools/random-hex

Тоже никакие настройки и смена Хекса не помогает, Билайн.

**Comment by Aletiy93** [comment]
> Москва МГТС В 1_russia_blacklist_YOUTUBE_ALT замените -5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116

Центра, Кемеровская область, помогло спасибо

**Comment by Pustamel** [comment]
> > Ну что-то вообще конечная, настройки никакие не помогают, даже с https://www.browserling.com/tools/random-hex
> 
> Тоже никакие настройки и смена Хекса не помогает, Билайн.

а если запускать именно 1_russia_blacklist_YOUTUBE_ALT? после его изменения непосредственно.

**Comment by 1vanK** [comment]
Нашел рабочие для себя параметры тут https://ntc.party/t/%D0%B5%D1%81%D0%BB%D0%B8-%D0%BE%D0%BF%D1%8F%D1%82%D1%8C-%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D1%82%D0%B0%D0%BB-%D1%81%D0%B5%D0%B3%D0%BE%D0%B4%D0%BD%D1%8F-%D0%B3%D1%80%D1%83%D0%B7%D0%B8%D1%82%D1%8C%D1%81%D1%8F-youtube/10529/192
```
-f 1 -k 1 -e 1 --native-frag --max-payload --wrong-chksum --wrong-seq --fake-gen 2 --blacklist
```

**Comment by GibonKenobi** [comment]
> Москва МГТС В 1_russia_blacklist_YOUTUBE_ALT замените -5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116

Помогло Ростелеком, спасибо

**Comment by aSxDox** [comment]
> > > Ну что-то вообще конечная, настройки никакие не помогают, даже с https://www.browserling.com/tools/random-hex
> > 
> > 
> > Тоже никакие настройки и смена Хекса не помогает, Билайн.
> 
> а если запускать именно 1_russia_blacklist_YOUTUBE_ALT? после его изменения непосредственно.

Вообще ничего не помогает, 
Ютуб: Нет подключения к Интернету
Проверьте подключение к Интернету.

Другие сайт: Доступ к информационному ресурсу ограничен на основании Федерального закона «Об информации, информационных технологиях и о защите информации»

или

Не удается получить доступ к сайту ERR_TUNNEL_CONNECTION_FAILED

или ERR_TIMED_OUT

**Comment by GibonKenobi** [comment]
> Нашел рабочие для себя параметры тут https://ntc.party/t/%D0%B5%D1%81%D0%BB%D0%B8-%D0%BE%D0%BF%D1%8F%D1%82%D1%8C-%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D1%82%D0%B0%D0%BB-%D1%81%D0%B5%D0%B3%D0%BE%D0%B4%D0%BD%D1%8F-%D0%B3%D1%80%D1%83%D0%B7%D0%B8%D1%82%D1%8C%D1%81%D1%8F-youtube/10529/192
> 
> ```
> -f 1 -k 1 -e 1 --native-frag --max-payload --wrong-chksum --wrong-seq --fake-gen 2 --blacklist
> ```

Ростелеком помогло, спасибо

**Comment by Eugenius69** [comment]
> Нашел рабочие для себя параметры тут https://ntc.party/t/%D0%B5%D1%81%D0%BB%D0%B8-%D0%BE%D0%BF%D1%8F%D1%82%D1%8C-%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D1%82%D0%B0%D0%BB-%D1%81%D0%B5%D0%B3%D0%BE%D0%B4%D0%BD%D1%8F-%D0%B3%D1%80%D1%83%D0%B7%D0%B8%D1%82%D1%8C%D1%81%D1%8F-youtube/10529/192
> 
> ```
> -f 1 -k 1 -e 1 --native-frag --max-payload --wrong-chksum --wrong-seq --fake-gen 2 --blacklist
> ```

Мегафон, Чебоксары. Помогло. Большое спасибо!

**Comment by 1vanK** [comment]
Правда у меня с этим настройками https://ntc.party перестал работать (у меня фаерфокс если что)

**Comment by nem0o** [comment]
> Москва МГТС В 1_russia_blacklist_YOUTUBE_ALT замените -5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116

ростелеком, помогло спасибо)

**Comment by johnnyd-78** [comment]
Отлично работает
goodbyedpi.exe -s -r -m -e 2 -f 1 --native-frag --wrong-seq --fake-gen 1 --set-ttl 3 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
Можно поиграться с --native-frag заменив на --reverse-frag или увеличить --fake-gen до 12
Спасибо ребятам с форума, дай им бог здоровья!
--fake-gen 29 - шляпа, вроде и работает но пинги до гуглкэшей выросли в разы, видосы может и посмотришь, но стримы будут тормозить и отставать

**Comment by Barmaley0** [comment]
МГТС
" -9 -e1 -f1 -q --fake-gen 12 --fake-from-hex (сгенерированные числа) --blacklist \"%CD%\russia-blacklist.txt\" --blacklist \"%CD%\russia-youtube.txt\"" start= "auto"
Помог только этот вариант.

**Comment by IshuCute** [comment]
> Москва МГТС В 1_russia_blacklist_YOUTUBE_ALT замените -5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116

сибирский медведь. помогло

**Comment by palachzzz** [comment]
Интересно насколько хватит, сейчас в МГТС сидят: challenge accepted

**Comment by IshuCute** [comment]
> Интересно насколько хватит, сейчас в МГТС сидят: challenge accepted

та и не только в МГТС. либо Сибирский медведь их филиал :D

**Comment by IshuCute** [comment]
> > Интересно насколько хватит, сейчас в МГТС сидят: challenge accepted
> 
> та и не только в МГТС. либо Сибирский медведь их филиал :D

ну или большой фанат

**Comment by leskei217** [comment]
> Москва МГТС В 1_russia_blacklist_YOUTUBE_ALT замените -5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116

проводной Ростелеком. Помогло, спасибо!

**Comment by Andrasolin** [comment]
это нормально? GDPI v.023rc3-2 (latest) со вчерашними настройками, сегодня увидел спустя 2 часа

![003](https://github.com/user-attachments/assets/6c4e97da-c982-4a3c-b57b-20f480825955)

у обычного Скрипта, столько памяти О_о

**Comment by dexianox** [comment]
> Москва МГТС В 1_russia_blacklist_YOUTUBE_ALT замените -5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116

Тоже помогло. Спасибо.
Ростелеком, Смоленская область.

**Comment by ValdikSS** [comment]
>просто не работает, видео не грузятся

Это НЕ ошибка программы и её НЕ НУЖНО сообщать сюда!

**Comment by Foxtrot52th** [comment]
МГТС, Москва. Помог этот вариант -5 --fake-gen 29

**Comment by AwareFoxy** [comment]
> Отлично работает `goodbyedpi.exe -s -r -m -e 2 -f 1 --native-frag --wrong-seq --fake-gen 1 --set-ttl 3 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt` Можно поиграться с --native-frag заменив на --reverse-frag или увеличить --fake-gen до 12 Спасибо ребятам с форума, дай им бог здоровья! --fake-gen 29 - шляпа, вроде и работает но пинги до гуглкэшей выросли в разы, видосы может и посмотришь, но стримы будут тормозить и отставать

проводной ртк, помогло

**Comment by banta84** [comment]
> Москва МГТС В 1_russia_blacklist_YOUTUBE_ALT замените -5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116

Замена -5 на -9 на некоторых сайтах приводит к ошибке SSL_ERROR_PROTOCOL_VERSION_ALERT, а подмена hex нездорово сказывается на твиттере - вечно висят сообщения о TLS соединенях, однако со скрипом он все же загружается - исходное число видимо не совсем рандомно? Но ютуб после этих манипуляций вроде оживает, да =)

**Comment by johnnyd-78** [comment]
@banta84 Потому что "советователи" не в курсе, что есть такая волшебная вещь, как --set-ttl )
У них пакет засранный 30 фейками долетает прямо до сервера - естественно ему сильно плохеет

**Comment by johnnyd-78** [comment]
@Gxtod Внезапно - на форум. Прикинь, он есть!

**Comment by ValdikSS** [comment]
@Gxtod 
> А куда её простите сообщать?

На любую подходящую вам площадку, допускающую это. Например, на https://ntc.party/, но не только.
Здесь же место только для непосредственно ошибок в программе — github не допускает гибкую настройку уведомлений, все сообщения приходят мне на email, а меня интересуют только потенциальные ошибки.

>Лучше бы работу работали чем рты зактыкать людям.

Я не оказываю поддержку программы, консультаций, не предоставляю услуг по настройке.
Сообщения:

>просто не работает, видео не грузятся

Не помогают ни в диагностике проблемы, ни приближают к её устранению.

**Comment by Gxtod** [comment]
> На любую подходящую вам площадку, допускающую это. Например, на https://ntc.party/, но не только. 

@ValdikSS а ничё что её заблокировали? https://pikabu.ru/story/yeto_sluchilos_goodbyedpi_24092024_11838547

или как обычно всем плевать на чужие проблемы... (

P.S. Вас никто ни в чём не упрекает и не командует, ну можно как-то почеловечнее что ли, видите пора внести изменения - ну так сделайте, неужили так сложно? Закрепите важное, сделайте сверху в закрепе, а то люди бегают советуют друг другу непонятную дичь, даже распространяют какие-то левые сборки GooDbyeDPI с вируснёй, нафига до этого доводить? Да сделайте вы им 20-30 батников на все случаи жизни так сказать - в официальном репозитарии, и всё, проблема решена.

**Comment by NeuralAIM** [comment]
> > На любую подходящую вам площадку, допускающую это. Например, на https://ntc.party/, но не только.
> 
> @ValdikSS а ничё что её заблокировали? https://pikabu.ru/story/yeto_sluchilos_goodbyedpi_24092024_11838547
> 
> или как обычно всем плевать на чужие проблемы... (
> 
> P.S. Вас никто ни в чём не упрекает и не командует, ну можно как-то почеловечнее что ли, видите пора внести изменения - ну так сделайте, неужили так сложно? Закрепите важное, сделайте сверху в закрепе, а то люди бегают советуют друг другу непонятную дичь, даже распространяют какие-то левые сборки GooDbyeDPI с вируснёй, нафига до этого доводить? Да сделайте вы им 20-30 батников на все случаи жизни так сказать - в официальном репозитарии, и всё, проблема решена.

Вы на гитхабе если что, хотите исправить проблему, welcome - https://github.com/ValdikSS/GoodbyeDPI/pulls

Решение проблемы здесь сообщили, и даже не одно. Внесите свою лепту в эту прекрасную программу а не просите от некоммерческого проекта то, чем вам не обязаны.

Именно вы тут поступаете не человечно, не нравиться - не пользуйтесь. VPN по прежнему работает.

**Comment by ValdikSS** [comment]
>видите пора внести изменения - ну так сделайте, неужили так сложно?

У меня нет времени даже на то, чтобы просто прочитать все сообщения, которые ко мне приходят, и именно поэтому я направляю людей на разные площадки, чтобы получать конкретную информацию по конкретным каналам. Здесь я не могу добавить модераторов, переносить сообщения, закреплять более трех тикетов, настраивать уведомления, и т.п.

Я бегло протестировал текущие рекомендуемые .cmd'шники на трех интернет-провайдерах — на всех всё продолжает работать (и youtube, и другие заблокированные сайты). Если вы провели более глубокое исследование и можете предложить оптимальные параметры — предлагайте, конечно, желательно в развёрнутом формате бумажного письма, чтобы оно содержало обоснование и не требовало дополнительных расспросов, иными словами, чтобы обновление заняло у меня минимум времени.

**Comment by Andrasolin** [comment]
плохая ситуация...вы оба правы, автор ГДПИ хотел как лучше, но гитхаб особенный...а мы потребители должны давать конкретную тнформацию без спама/флуда.

вы же видели тематики постов...и при в выборе поста-репорта. а автор не умеет общаться: с людьми с улиц...ему это не надо, у него талант и скил в другом

**Comment by dre40** [comment]
> Москва МГТС В 1_russia_blacklist_YOUTUBE_ALT замените -5 на -9, --fake-gen 5 на --fake-gen 29, замените HEX на свой сгенерировать можно на https://www.browserling.com/tools/random-hex не забудьте поставить длину hex 116

Спасибо, помогло. Ростелеком Калуга

**Comment by Mifkill** [comment]
У всех ГДПИ работает? у меня сегодня перестал и замена HEX не помогает, может уже нашёл кто решенье

**Comment by XXXkila** [comment]
попробуйте https://codly.ru/gdp/   классный генератор, у меня работает всегда когда перестает работать

**Comment by TY-ai108** [comment]
> Нашел рабочие для себя параметры тут https://ntc.party/t/%D0%B5%D1%81%D0%BB%D0%B8-%D0%BE%D0%BF%D1%8F%D1%82%D1%8C-%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D1%82%D0%B0%D0%BB-%D1%81%D0%B5%D0%B3%D0%BE%D0%B4%D0%BD%D1%8F-%D0%B3%D1%80%D1%83%D0%B7%D0%B8%D1%82%D1%8C%D1%81%D1%8F-youtube/10529/192
> 
> ```
> -f 1 -k 1 -e 1 --native-frag --max-payload --wrong-chksum --wrong-seq --fake-gen 2 --blacklist
> ```

ссылка не работает
можно пожалуйста полное описание что и куда нужно вписать.
благодарю!

**Comment by TY-ai108** [comment]
не работает ни один способ
может обновить всё-таки программу с новыми cmd ? люди мучаются, зайти не могут никуда.

**Comment by TY-ai108** [comment]
> [@banta84](https://github.com/banta84) Потому что "советователи" не в курсе, что есть такая волшебная вещь, как --set-ttl ) У них пакет засранный 30 фейками долетает прямо до сервера - естественно ему сильно плохеет. В том то и дело, что "вроде"

вы можете нормально написать куда и что нужно сделать ?
быть нормальным советователем.
Благодарю!
