### ISSUE TITLE
all the scripts / service installs (not including 2_any_country scripts) wont work even when --fake-from-hex value is changed, 

### ISSUE THREAD

**Issue by suspiciouspotato47** [ValdikSS/GoodbyeDPI#659]
### Operating system / операционная система

Windows 11 pro 21H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

 Even when --fake-from-hex value is changed, it wont work. i tried **ALL** methods how to fix gDPI. youtube wont work.

### Additional information / Дополнительная информация

my internet provider is krystal (https://kristall-pervoe.tv/ufa/home/), maybe it blacklisted every fake value ig????? i have absolutely no clue.

**Comment by johnnyd-78** [comment]
Если не работает ютуб, но работает [форум](https://ntc.party/t/%D0%B5%D1%81%D0%BB%D0%B8-%D0%BE%D0%BF%D1%8F%D1%82%D1%8C-%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D1%82%D0%B0%D0%BB-%D1%81%D0%B5%D0%B3%D0%BE%D0%B4%D0%BD%D1%8F-%D0%B3%D1%80%D1%83%D0%B7%D0%B8%D1%82%D1%8C%D1%81%D1%8F-youtube/10529/202) - идите туда, там ребята вам помогут.

**Comment by ValdikSS** [comment]
>youtube wont work.

This is NOT an application issue and you should NOT report it here!
