### ISSUE TITLE
RCN is doing dirty tricks again... Or not them...

### ISSUE THREAD

**Issue by Alto3** [ValdikSS/GoodbyeDPI#660]
### Operating system / операционная система

Win 11 23H3

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

23 числа сентября, перестал работать DPI. Я не знаю как и почему и решил полазить по инету в поиске ответа, все что сделать смог - так это починить ютуб через "service_install_russia_blacklist_dnsredir". Но хочу дальше пользоваться "1_russia_blacklist" который не работает на таких сайтах как сам ютуб и данбору. Пробовал делать как все через Hex... Может я не понял как правильно?

### Additional information / Дополнительная информация

Провайдер - дом ру, поставлено число -11.

**Comment by johnnyd-78** [comment]
Скорее всего не поняли. Хотите пользоваться - пользуйтесь, только не 1_russia_blacklist а 1_russia_blacklist_dnsredir

Никакого -11 нет, откуда вы его берете? В итоге у вас получается банальный -1

**Comment by Alto3** [comment]
> Скорее всего не поняли. Хотите пользоваться - пользуйтесь, только не 1_russia_blacklist а 1_russia_blacklist_dnsredir И службу которую вы установили при помощи service_install... удалите, запустив service_remove от админа Никакого -11 нет, откуда вы его все берете? В итоге у вас получается банальный -1 который никакой hex вообще не использует

Ну, допустим, что я сделал все, что вы написали - использовал service_remove, поставил -9 в 1_russia_blacklist_dnsredir... Но в чем разница? Простите за мое незнание по поводу этого. И мне стоит также в 1_russia_blacklist_dnsredir делать с Hex или нет?

**Comment by ValdikSS** [comment]
>23 числа сентября, перестал работать DPI.

Это не ошибка программы и её НЕ НУЖНО сообщать сюда!
