### ISSUE TITLE
Совместная работа GbDPI (0.2.3rc3-2) и Adguard (версия 7.18.1 (4778))

### ISSUE THREAD

**Issue by vladikas** [ValdikSS/GoodbyeDPI#666]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 10 Pro 22H2 19045.4894

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

При совместной работе GbDPI (0.2.3rc3-2) и Adguard (версия 7.18.1 (4778)) ютуб не работает. Запускаю GbDPI с помощью cmd файла.
`@ECHO OFF
PUSHD "%~dp0"
set _arch=x86
IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (set _arch=x86_64)
IF DEFINED PROCESSOR_ARCHITEW6432 (set _arch=x86_64)
PUSHD "%_arch%"

for /f %%i in ('powershell -command "[byte[]]$bytes = (1..58 | ForEach-Object { Get-Random -Max 256 }); $randomHex = -join ($bytes | ForEach-Object { $_.ToString('x2') }); $randomHex"') do set "hex_value=%%i"

start "" goodbyedpi.exe -9  -e2 -q --fake-gen 29 --fake-from-hex %hex_value% --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt

POPD
POPD`
Ну и любые другие параметры запуска не дают результата (если Adguard запущен). Конфигурация Adguard по-умолчанию.
Сделал дампы траффика и послал на почту из профиля.

### Additional information / Дополнительная информация

PS Если нужен лицензионный ключ на Adguard, сообщите.

**Comment by oren19737373** [comment]
Adguard пришлось удалить из за своих новых правил пользуюсь скриптами через Tampermonkey  и я этим доволен , чем ставить всякий мусор в систему .

**Comment by ValdikSS** [comment]
Adguard самостоятельно бьет ClientHello на несколько частей, GoodbyeDPI с таким несовместим. Отключите обход блокировок в Adguard.

**Comment by vladikas** [comment]
Спасибо. Я даже и не знал, что в Adguard есть такое.
Настройки -> Защита от трекинга -> Защита от DPI
