### ISSUE TITLE
Discord does not open / Не открывается Discord на ПК, телефоне, с браузера

### ISSUE THREAD

**Issue by checkoutcommunity** [ValdikSS/GoodbyeDPI#667]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Если у вас не открывается DISCORD в России, который теперь официально внесён в реестр РКН и МВД России, используйте в файле russia-youtube.txt эти домены:
www.discord.com
www.discord.app
discord.com
discord.app
cdn.discordapp.com
![image](https://github.com/user-attachments/assets/f8326343-ee57-4e58-ab3f-72ecc468000b)

**Comment by antieksi** [comment]
I feel that I must mention it's the second time the Russian government is trying to block Discord here.
