### ISSUE TITLE
добавление поддержки discord

### ISSUE THREAD

**Issue by hirotokun4ik** [ValdikSS/GoodbyeDPI#668]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

добавление поддержки discord так как с 26 сентября 2024 года discord точечно заблокирован на территории российской федерации и работает (там где он заблокирован) только с VPN

**Comment by fortdevv** [comment]
Уже работаю над этим.

**Comment by Hell0-Kitty** [comment]
добавил в russia-blacklist
```
discord.com
gateway.discord.gg
cdn.discordapp.com
discordapp.net
discordapp.com
discord.gg
media.discordapp.net
images-ext-1.discordapp.net
```

но не помогло

**Comment by fortdevv** [comment]
добавил в russia-youtube
`discord.com
*.discord.com
discord.gg
*.discord.gg
discordapp.com
*.discordapp.com
discordapp.net
*.discordapp.net
discord.media
*.discord.media`
Сайт работает, но при попытке подключения к rtc выдает ошибку

**Comment by SMorokhin** [comment]
Добавьте в файлы:
```
russia-blacklist
russia-youtube.txt
```
домены: 
```
discord.gg
discord.com
discordapp.com
discord.media
discordapp.net
discordcdn.com
discord.dev
discord.new
discord.gift
discordstatus.com
dis.gd
discord.co
```
После этого все заработало

**Comment by fortdevv** [comment]
> Добавьте в файлы:
> 
> ```
> russia-blacklist.txt
> russia-youtube.txt
> ```
> 
> домены:
> 
> ```
> discord.gg
> discord.com
> discordapp.com
> discord.media
> discordapp.net
> discordcdn.com
> discord.dev
> discord.new
> discord.gift
> discordstatus.com
> dis.gd
> discord.co
> ```
> 
> После этого все заработало

Здесь наблюдается абсолютно та же проблема, что и у меня - после подключения к rtc, сервер не может найти маршрут

**Comment by SMorokhin** [comment]
@fortdevv у меня заработало, к rtc подключился, может кому тоже поможет

**Comment by fortdevv** [comment]
> @fortdevv у меня заработало, к rtc подключился, может кому тоже поможет

Не, тут не спорю, и круто если поможет. Странно что у меня просто не сработало)

**Comment by SMorokhin** [comment]
@fortdevv попробовал добавить другие домены, перестало работать, работает только с тем списком, оч странно

**Comment by Wafer-EX** [comment]
У меня вообще ни один из вариантов не работает, Ростелеком

**Comment by Zer0dol** [comment]
> Добавьте в файлы:
> 
> ```
> russia-blacklist.txt
> russia-youtube.txt
> ```
> 
> домены:
> 
> ```
> discord.gg
> discord.com
> discordapp.com
> discord.media
> discordapp.net
> discordcdn.com
> discord.dev
> discord.new
> discord.gift
> discordstatus.com
> dis.gd
> discord.co
> ```
> 
> После этого все заработало

У меня работает приложение и сайт с этим списком, однако также не получилось к rtc подключиться.
С другими списками в общем та же история, всё работает кроме войсов. И не могу её файлы сообщениями отправлят

**Comment by Hell0-Kitty** [comment]
> добавил в russia-blacklist
> 
> ```
> discord.com
> gateway.discord.gg
> cdn.discordapp.com
> discordapp.net
> discordapp.com
> discord.gg
> media.discordapp.net
> images-ext-1.discordapp.net
> www.discord.com
> www.discord.app
> discord.app
> *.discord.com
> *.discord.gg
> *.discordapp.com
> *.discordapp.net
> discord.media
> *.discord.media
> discordcdn.com
> discord.dev
> discord.new
> discord.gift
> discordstatus.com
> dis.gd
> discord.co
> ```
> 
> но не помогло, не работает ни приложение, ни сайт

Только что на ростелекоме начал грузиться сайт. В войс дает зайти

**Comment by fortdevv** [comment]
> > добавил в russia-blacklist
> > ```
> > discord.com
> > gateway.discord.gg
> > cdn.discordapp.com
> > discordapp.net
> > discordapp.com
> > discord.gg
> > media.discordapp.net
> > images-ext-1.discordapp.net
> > www.discord.com
> > www.discord.app
> > discord.app
> > *.discord.com
> > *.discord.gg
> > *.discordapp.com
> > *.discordapp.net
> > discord.media
> > *.discord.media
> > discordcdn.com
> > discord.dev
> > discord.new
> > discord.gift
> > discordstatus.com
> > dis.gd
> > discord.co
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > но не помогло, не работает ни приложение, ни сайт
> 
> Только что на ростелекоме начал грузиться сайт. В войс в веб-версии дает зайти

Тоже заработало, спасибо!

**Comment by Zer0dol** [comment]
Апдейт. Войс работает через сайт, как и отправка файлов

**Comment by Hell0-Kitty** [comment]
Дело не в том, что списки заработали, а в том что провайдер пустил. Списки доменов можете удалять, ни на что не влияют

**Comment by Zer0dol** [comment]
Ещё апдейт. Внезапно, без изменений каких-либо в файлах, войс заработал и с приложения. Как и отправка файлов. Возможно и вправду что-то провайдеры подкрутили.
Билайн если что у меня.

**Comment by Zer0dol** [comment]
Возможно это всё был чисто тест блокировок)

**Comment by Hell0-Kitty** [comment]
> Возможно это всё был чисто тест блокировок)

Опять умерло :(

**Comment by C4erries** [comment]
> Возможно это всё был чисто тест блокировок)

Челлендж от РКН, успеем ли мы обход придумать
Не успели -- починили сами

**Comment by Wafer-EX** [comment]
Ростелеком, все еще не работает

**Comment by C4erries** [comment]
> Ростелеком, все еще не работает

у меня только discord.com грузит

**Comment by justMan2440** [comment]
есть идеи как обойти ?

**Comment by Rtaidem** [comment]
также пробовал домены добавлять, толку нет. работает только с vpn. Ростелеком, если что

**Comment by ValdikSS** [comment]
Для начала необходимо понять, что именно не работает. Если это блокировка по IP, то программа бессильна, что в неё не добавляй. Аналогично при блокировке трафика в сторону какого-либо датацентра. Если это блокировка SNI, то никаких изменений не нужно, достаточно создать blacklist, что вы уже предложили.

Я ни по одному домену, упомянутому выше, блокировок не вижу ни через какого провайдера.

Записи вида:

>*.discord.com

Работать не будут. Необходимо добавлять зону, без звёздочки.

**Comment by Andrasolin** [comment]
> > @fortdevv у меня заработало, к rtc подключился, может кому тоже поможет
> 
> Не, тут не спорю, и круто если поможет. Странно что у меня просто не сработало)

маршрутизация/трафик другой. бан на бане - наверно

**Comment by TheMagicPe4enka** [comment]
Пока с доменами дискорда экспериментируете, добавьте в *.cmd строчку
--blacklist ..\russia-discord.txt
и заполняйте домены в russia-discord.txt, чтобы файлы не портить

**Comment by johnnyd-78** [comment]
@ValdikSS Это блокировка по IP их гейтвея - gateway.discord.gg Причем всех его IP, как сообщают люди на форуме. В принципе, после этого понятно, что создавать какие-то списки нет никакого смысла.

P.S. Работал и работает сейчас. Ростелеком

**Comment by Serega11112222** [comment]
Сегодня перестал работать Discord. Посмотрел в интернете, ни у меня одного такое. У одних работает, у других нет. Добавил в файл блеклиста адреса написанные выше и всё заработало. Единственное ещё не проверял голосовую связь, демонстрацию экрана. Скриншоты не отправляются в чат, как решить? Возможно ещё какой-то ссылки не хватает в списке помимо добавленных

**Comment by deftt55** [comment]
Есть варики как голосовую связь наладить? RTC подключение и все потом ошибка...

**Comment by dadee** [comment]
> Скриншоты не отправляются в чат дискорда, как решить? Возможно ещё какой-то ссылки не хватает в списке помимо добавленных.

может помочь
discord-attachments-uploads-prd.storage.googleapis.com

**Comment by MARK2580** [comment]
Чёт сегодня вечером дискорд совсем умер, все адреса включая последний у меня давно добавлены. Даже цензор трекер не спасает =(
