### ISSUE TITLE
All the *_YOUTUBE*.cmd files crash

### ISSUE THREAD

**Issue by olegboldyrev** [ValdikSS/GoodbyeDPI#669]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 11 23H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

I downloaded the latest 0.2.3_rc2.
When I run any of *.cmd files not containing YOUTUBE in their name, all is OK except Youtube doesn't run. When I run any of *_
YOUTUBE(_ALT).cmd flies, the console windows closes immediately. I observe in Events the following error messages:
Faulting application name: goodbyedpi.exe, version: 0.0.0.0, time stamp: 0x66e5f196
Faulting module name: goodbyedpi.exe, version: 0.0.0.0, time stamp: 0x66e5f196
Exception code: 0xc0000094
Fault offset: 0x0000000000003790
Faulting process id: 0x0x1A64
Faulting application start time: 0x0x1DB102B6B1B4B24
Faulting application path: D:\Utils\goodbyedpi-0.2.3rc2\x86_64\goodbyedpi.exe
Faulting module path: D:\Utils\goodbyedpi-0.2.3rc2\x86_64\goodbyedpi.exe
Report Id: ccad621a-12d7-47ba-9eb7-7a8630cc5993
Faulting package full name: 
Faulting package-relative application ID:

**Comment by ValdikSS** [comment]
This has been fixed in 0.2.3rc3. You're using not the latest version.
