### ISSUE TITLE
problem with the TTK provider

### ISSUE THREAD

**Issue by ErsoJami** [ValdikSS/GoodbyeDPI#671]
### CAPTCHA

- [x] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

На провайдере ттк не открывется ютуб, перебробывал уже очень много аргуметнов запуска програмы такие как: -1 -1e, --fake-from-hex --fake-gen.

**Comment by TokcDK** [comment]
В #672 указана ссылка на форум с гидом, там объяснили, как решить.
