### ISSUE TITLE
29.09.2024 Провайдер ТелПлюс, программа не работает

### ISSUE THREAD

**Issue by WinzyGG** [ValdikSS/GoodbyeDPI#672]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 10, номер сборки 22H

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Просто не работает, прикреплять нечего

### Additional information / Дополнительная информация

Перестало работать где то в 20-х числах сентября, думал подожду, фиксанут, в итоге фикс какой-то вышел, но на моем провайдере не заработало, пошел перешерстил интернет, на моего провайдера подходящих чисел для изменения конфига там не нашел, надеюсь товарищи с гитхаба смогут помочь. Буду максимально благодарен.
**Мой провайдер - Телплюс.**

**Comment by FreeFinder999** [comment]
Провайдер Ростелеком. Сегодня тоже всё сдохло. :( Интерфейс Ютуба ещё как-то грузит, а вот плеер не работает совсем.

**Comment by johnnyd-78** [comment]
На форум идите. А тут вам лишь бан грозит, как в вашем сообщении и написано.

**Comment by Andrey5757Wart** [comment]
> На [форум](https://ntc.party/t/%D0%B5%D1%81%D0%BB%D0%B8-%D0%BE%D0%BF%D1%8F%D1%82%D1%8C-%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D1%82%D0%B0%D0%BB-%D0%B3%D1%80%D1%83%D0%B7%D0%B8%D1%82%D1%8C%D1%81%D1%8F-youtube-%D0%B8%D0%BB%D0%B8-%D0%B5%D0%B3%D0%BE-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE/10529) идите. А тут вам лишь бан грозит, как в вашем сообщении и написано.

Форум уже недоступен на территории РФ

**Comment by 1vanK** [comment]
> На [форум](https://ntc.party/t/%D0%B5%D1%81%D0%BB%D0%B8-%D0%BE%D0%BF%D1%8F%D1%82%D1%8C-%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D1%82%D0%B0%D0%BB-%D0%B3%D1%80%D1%83%D0%B7%D0%B8%D1%82%D1%8C%D1%81%D1%8F-youtube-%D0%B8%D0%BB%D0%B8-%D0%B5%D0%B3%D0%BE-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE/10529) идите. А тут вам лишь бан грозит, как в вашем сообщении и написано.

Ну ты же понимаешь, что чел не может зайти на заблокированный форум без программы?

**Comment by johnnyd-78** [comment]
> что чел не может зайти на заблокированный форум без программы?

Зато он может туда зайти с любым другим способом обхода. И вообще непонятно, что у человека именно не работает. При неработающем ютубе на форум можно легко зайти, а у кого-то - наоборот.

**Comment by 1vanK** [comment]
Смешнее только когда на ютубе выкладывают ролики, как обойти блокировку ютуба

**Comment by Andrey5757Wart** [comment]
> > что чел не может зайти на заблокированный форум без программы?
> 
> Зато он может туда зайти с любым другим способом обхода. И вообще непонятно, что у человека именно не работает. При неработающем ютубе на форум можно легко зайти, а у кого-то - наоборот, не работает форум, а ютуб работает.

У меня тоже перестал работать полностью GoodbyeDPI, ни на Ютуб, ни на форум зайти не могу

**Comment by Dimadin27** [comment]
ТелПлюс Астрахань: 1_russia_blacklist.cmd  попробуйте изменить start "" goodbyedpi.exe -6 --fake-gen 29 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt  у меня работает.

**Comment by johnnyd-78** [comment]
Или [сюда](https://github.com/ValdikSS/GoodbyeDPI/pull/665)
