### ISSUE TITLE
Adding abbility to add *.domain.space in files (subdomain | subdomains mask)

### ISSUE THREAD

**Issue by f1den** [ValdikSS/GoodbyeDPI#673]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

header. 
Я заметил что у ютуба всё ок, кроме серверов *.googlevideo.com, а их дохуя, при этом их блочат.
Я думаю можете ли ВЫ добавить поддержку * в сабдомене? или она уже есть и я дегроид

**Comment by f1den** [comment]
Vladikss поясни нормально что ты будешь иметь ввиду
![image](https://github.com/user-attachments/assets/2807d0fa-d8c7-42ed-bb3a-99ee1eb686e4)
Это не особо катит на объяснение.
Будет ли так работать не будет, Работает ли так уже и это проблема лично моего провайдера?

**Comment by An1onS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/371#issuecomment-2244223226

**Comment by ValdikSS** [comment]
Домены, добавленные в blacklist, обрабатываются как зоны, т.е. ко всем поддоменам указанного домена применяется обход блокировки (и это не настраивается).
