### ISSUE TITLE
Превышено время ожидания youmail.com

### ISSUE THREAD

**Issue by andreybexus** [ValdikSS/GoodbyeDPI#674]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Здраствуйте при загрузке сайта youmail.com выдается ошибка, превышено время ожидания. Когда включен сам VPN, такой ошибки не возникает.

**Comment by andreybexus** [comment]
А также сайт temp-mail.org вообще не загружается, err_ssl_protocol_error, сайт temp-mail.org отправил недействительный ответ

**Comment by andreybexus** [comment]
Какой cmd я использовал? 1_russia_blacklist_youtube

**Comment by andreybexus** [comment]
Так и не ответили на вопрос, грустно

**Comment by Supergamerrr** [comment]
Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках**, а для вопросов или сообщении о «неработающем веб-сайте».**
Ты поставил галочку даже, не прочитав?

**Comment by andreybexus** [comment]
> Прочитай на что ты поставил галочку: "Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, **а для вопросов или сообщении о «неработающем веб-сайте»."** Ты поставил галочку даже, не прочитав? Это не сообщение об ошибки программы, а сообщение о неработающем веб-сайте. Создавать по поводу Issue не нужно

Это feature request

**Comment by andreybexus** [comment]
> [Supergamerrr](/Supergamerrr)

Товарищ вы что-то перепутали :)

**Comment by ValdikSS** [comment]
> Товарищ вы что-то перепутали :)

Боюсь, всё же вы.
