### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by oncceh** [ValdikSS/GoodbyeDPI#675]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

windows 11 22h2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

When the program is running, the video on YouTube often freezes after a while in an endless loading state, and after reloading the page everything returns to normal.

**Comment by EgorWeders** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/378#issuecomment-2267201431


> ❔ У меня временами долго загружаются видео на YouTube!
> 
>     

> Заблокируйте плохо работающие серверы файлом hosts

> 
> Локальные серверы Google Global Cache, установленные у некоторых провайдеров в инфраструктуре, подвергаются замедлению/блокировке по IP-адресу, а не по имени домена, и программа в этом случае бессильна.
> 
> Можно заблокировать локальные серверы провайдера, чтобы YouTube использовал общие для города или региона у другого провайдера, в надежде, что с ними не будет проблем. См. тему [Задержка перед запуском видео Youtube 6-10 секунд](https://ntc.party/t/%D0%B7%D0%B0%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%BE%D0%BC-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE-youtube-6-10-%D1%81%D0%B5%D0%BA%D1%83%D0%BD%D0%B4/8395) с примером того, как следует поступать в данном случае.

This is not a bug, at least not a GoodbyeDpi bug

**Comment by Averssem** [comment]
I second that problem. Honestly I thought this behavior is "works as intended" so I just made peace with having to f5 every video on youtube. 'Cause if I dont it'll stop loading after a minute or two (and shorts stop loading even sooner). but after i reload the page it works fine even if I watch at x2 speed.

**Comment by EgorWeders** [comment]
Which arguments (or cmd file) do you use?

**Comment by johnnyd-78** [comment]
Попробуйте [это](https://github.com/ValdikSS/GoodbyeDPI/pull/665).

**Comment by oncceh** [comment]
1_russia_blacklist

**Comment by oncceh** [comment]
> Попробуйте [это](https://github.com/ValdikSS/GoodbyeDPI/pull/665).

Не помогло/didn't help

**Comment by oncceh** [comment]
I noticed that the freeze almost always occurs only at the 19th second

**Comment by Averssem** [comment]
> I noticed that the freeze almost always occurs only at the 19th second

I just noticed something. Would like you to try to replicate it. When you start the video and it only buffered to 20th second try skipping forward 5 seconds. For me it then loads perfectly fine for the rest of the video with no need to refresh the page.
I need to know if it's just a me thing or if it's related to the overall problem.

**Comment by oncceh** [comment]
Unfortunately, I can't catch such a moment, the last few days the video either loads normally, or I forget. Although today for some reason the videos started to freeze in the middle.

**Comment by oncceh** [comment]
> > I noticed that the freeze almost always occurs only at the 19th second
> 
> I just noticed something. Would like you to try to replicate it. When you start the video and it only buffered to 20th second try skipping forward 5 seconds. For me it then loads perfectly fine for the rest of the video with no need to refresh the page. I need to know if it's just a me thing or if it's related to the overall problem.

Some videos stopped loading at all. Restarting doesn't help. Is it the same for you?

**Comment by oncceh** [comment]
> > I noticed that the freeze almost always occurs only at the 19th second
> 
> I just noticed something. Would like you to try to replicate it. When you start the video and it only buffered to 20th second try skipping forward 5 seconds. For me it then loads perfectly fine for the rest of the video with no need to refresh the page. I need to know if it's just a me thing or if it's related to the overall problem.

No, its didnt work for me.

**Comment by Averssem** [comment]
Why would you mark it as "complete" when you fixed nothing and the problem still remains?

**Comment by SeregaKR** [comment]
> Thanks, but it doesn't apply to me. It didn't help me. I don't have a delay before the video starts. For me it hangs forever after 10 seconds from starting and only after a while, at the beginning never, until I reload the page.

I had the same problem when using Revanced YouTube. I believe it may be related to YouTube as a platform itself. This is most likely not the GoodByeDPI problem. Could you try playing with browser user agents? iPhone or Android VR now works in the new ReVanced YouTube app; try something similar.

**Comment by Averssem** [comment]
> > Thanks, but it doesn't apply to me. It didn't help me. I don't have a delay before the video starts. For me it hangs forever after 10 seconds from starting and only after a while, at the beginning never, until I reload the page.
> 
> I had the same problem when using Revanced YouTube. I believe it may be related to YouTube as a platform itself. This is most likely not the GoodByeDPI problem. Could you try playing with browser user agents? iPhone or Android VR now works in the new ReVanced YouTube app; try something similar.
> 
> P.S. I saw a reference in another thread about this issue being a problem of Google Cloud Cache. Check the discussion here #676

Well, considering it doesn't happen unless the thing is turned on I am pretty sure it the GoodByeDPI fault.
To your p.s. that google cloud thing is for completely unrelated issue. Which sound similar if you cant or dont care to read.
Videos do not wait 5 seconds to start playing. They do so immediately. But they stop loading past 20th second (or like 5th in shorts) which forces you to reload the page from which point they load properly.

My earlier comment about skipping forward wasn't a solution i hoped it to be.

**Comment by SeregaKR** [comment]
> > > Thanks, but it doesn't apply to me. It didn't help me. I don't have a delay before the video starts. For me it hangs forever after 10 seconds from starting and only after a while, at the beginning never, until I reload the page.
> > 
> > 
> > I had the same problem when using Revanced YouTube. I believe it may be related to YouTube as a platform itself. This is most likely not the GoodByeDPI problem. Could you try playing with browser user agents? iPhone or Android VR now works in the new ReVanced YouTube app; try something similar.
> > P.S. I saw a reference in another thread about this issue being a problem of Google Cloud Cache. Check the discussion here #676
> 
> Well, considering it doesn't happen unless the thing is turned on I am pretty sure it the GoodByeDPI fault. To your p.s. that google cloud thing is for completely unrelated issue. Which sound similar if you cant or dont care to read. Videos do not wait 5 seconds to start playing. They do so immediately. But they stop loading past 20th second (or like 5th in shorts) which forces you to reload the page from which point they load properly.
> 
> My earlier comment about skipping forward wasn't a solution i hoped it to be.

later in discussion they mentioned the problem like yours.

**Comment by Averssem** [comment]
> @Averssem Create a dump after starting a video [https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark](https://github.com/ValdikSS/GoodbyeDPI/wiki/%D0%9A%D0%B0%D0%BA-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%B4%D0%B0%D0%BC%D0%BF-%D1%82%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0-%D0%B2-Wireshark)

No matter what ip for yuotube.com I use as a filter it doesn't capture anything at all. I tried the ones from my local cmd nslookup and i tried the ones that i could find from online lookup.

**Comment by oncceh** [comment]
> > @Averssem Create a dump after starting a video [https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark](https://github.com/ValdikSS/GoodbyeDPI/wiki/%D0%9A%D0%B0%D0%BA-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%B4%D0%B0%D0%BC%D0%BF-%D1%82%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0-%D0%B2-Wireshark)
> 
> No matter what ip for yuotube.com I use as a filter it doesn't capture anything at all. I tried the ones from my local cmd nslookup and i tried the ones that i could find from online lookup.

This is not an extension issue. Go to chrome/flags and set everything to default and this issue will go away.

**Comment by Averssem** [comment]
> This is not an extension issue. Go to chrome/flags and set everything to default and this issue will go away.

I'm on firefox

**Comment by oncceh** [comment]
> > This is not an extension issue. Go to chrome/flags and set everything to default and this issue will go away.
> 
> I'm on firefox

Doesnt have same menu?

**Comment by Averssem** [comment]
> Doesnt have same menu?

i have no idea. I will not just randomly revert to all the defaults. if you know the specific one that is the issue then i'll check.

**Comment by oncceh** [comment]
> > Doesnt have same menu?
> 
> i have no idea. I will not just randomly revert to all the defaults. if you know the specific one that is the issue then i'll check.

chrome://flags/#enable-quic and chrome://flags/#enable-tls13-kyber.

**Comment by oncceh** [comment]
> > Doesnt have same menu?
> 
> i have no idea. I will not just randomly revert to all the defaults. if you know the specific one that is the issue then i'll check.

Disable adblocker.

**Comment by Averssem** [comment]
> Disable adblocker.

You insane? Hell no. I'd rather die.

**Comment by oncceh** [comment]
> > Disable adblocker.
> 
> You insane? Hell no. I'd rather die.

try this https://habr.com/ru/articles/845114/

**Comment by Antarigron** [comment]
Have the same problem

**Comment by Rutakate8** [comment]
19 second freeze as well

**Comment by oncceh** [comment]
> 19 second freeze as well

zapret
