### ISSUE TITLE
проблема

### ISSUE THREAD

**Issue by azim218** [ValdikSS/GoodbyeDPI#676]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

windows 11 сборка 22635

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Запускаю , всё  нормально, но иногда видео просто перестают грузить/прогружатся, пока не обновлю страницу или видео.

**Comment by RomZerr0** [comment]
В описании есть упоминание подобной проблемы 
https://github.com/ValdikSS/GoodbyeDPI/issues/378
Локальные серверы Google Global Cache, установленные у некоторых провайдеров в инфраструктуре, подвергаются замедлению/блокировке по IP-адресу, а не по имени домена, и программа в этом случае бессильна.

Можно заблокировать локальные серверы провайдера, чтобы YouTube использовал общие для города или региона у другого провайдера, в надежде, что с ними не будет проблем. См. тему [Задержка перед запуском видео Youtube 6-10 секунд](https://ntc.party/t/%D0%B7%D0%B0%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%BE%D0%BC-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE-youtube-6-10-%D1%81%D0%B5%D0%BA%D1%83%D0%BD%D0%B4/8395) с примером того, как следует поступать в данном случае.

**Comment by azim218** [comment]
> В описании есть упоминание подобной проблемы #378 Локальные серверы Google Global Cache, установленные у некоторых провайдеров в инфраструктуре, подвергаются замедлению/блокировке по IP-адресу, а не по имени домена, и программа в этом случае бессильна.
> 
> Можно заблокировать локальные серверы провайдера, чтобы YouTube использовал общие для города или региона у другого провайдера, в надежде, что с ними не будет проблем. См. тему [Задержка перед запуском видео Youtube 6-10 секунд](https://ntc.party/t/%D0%B7%D0%B0%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%BE%D0%BC-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE-youtube-6-10-%D1%81%D0%B5%D0%BA%D1%83%D0%BD%D0%B4/8395) с примером того, как следует поступать в данном случае.


Я вообще не разбираюсь, и ничего в данной статье не понял, кроме того что провайдеры что то блокируют.

**Comment by Mitradis** [comment]
Поддержу. Можно коротко и ясно что и где нужно сделать.

**Comment by EgorWeders** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/675

**Comment by EgorWeders** [comment]
> > В описании есть упоминание подобной проблемы #378 Локальные серверы Google Global Cache, установленные у некоторых провайдеров в инфраструктуре, подвергаются замедлению/блокировке по IP-адресу, а не по имени домена, и программа в этом случае бессильна.
> > Можно заблокировать локальные серверы провайдера, чтобы YouTube использовал общие для города или региона у другого провайдера, в надежде, что с ними не будет проблем. См. тему [Задержка перед запуском видео Youtube 6-10 секунд](https://ntc.party/t/%D0%B7%D0%B0%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%BE%D0%BC-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE-youtube-6-10-%D1%81%D0%B5%D0%BA%D1%83%D0%BD%D0%B4/8395) с примером того, как следует поступать в данном случае.
> 
> Я вообще не разбираюсь, и ничего в данной статье не понял, кроме того что провайдеры что то блокируют.

Программа не дает прочитать письмо, если его выкидывают из-за содержания, то программа поможет. Если же выкидывают из-за того, что оно идет на запрещенный адрес, то его выкидывают не читая. Как-то так.

**Comment by Mitradis** [comment]
@EgorWeders вы все скидываете одну и ту же ссылку, там сотни комментариев. Нужно все прочитать? И? Просим же коротко и ясно.

**Comment by EgorWeders** [comment]
@Mitradis я ответил на комментарии,  это цитата.

**Comment by azim218** [comment]
> > > В описании есть упоминание подобной проблемы #378 Локальные серверы Google Global Cache, установленные у некоторых провайдеров в инфраструктуре, подвергаются замедлению/блокировке по IP-адресу, а не по имени домена, и программа в этом случае бессильна.
> > > Можно заблокировать локальные серверы провайдера, чтобы YouTube использовал общие для города или региона у другого провайдера, в надежде, что с ними не будет проблем. См. тему [Задержка перед запуском видео Youtube 6-10 секунд](https://ntc.party/t/%D0%B7%D0%B0%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%BE%D0%BC-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE-youtube-6-10-%D1%81%D0%B5%D0%BA%D1%83%D0%BD%D0%B4/8395) с примером того, как следует поступать в данном случае.
> > 
> > 
> > Я вообще не разбираюсь, и ничего в данной статье не понял, кроме того что провайдеры что то блокируют.
> 
> Программа не дает прочитать письмо, если его выкидывают из-за содержания (а там написан адресат без конкретного адреса), то программа поможет. Если же выкидывают из-за того, что оно идет на запрещенный конкретный адрес, то его выкидывают не читая. Как-то так.

А можете пожалуйста дать какую нибудь команду или что то ещё чтобы не было этой ошибки? Просто в той статье, то что понял и сделал, то не помогло.

**Comment by azim218** [comment]
> > > > В описании есть упоминание подобной проблемы #378 Локальные серверы Google Global Cache, установленные у некоторых провайдеров в инфраструктуре, подвергаются замедлению/блокировке по IP-адресу, а не по имени домена, и программа в этом случае бессильна.
> > > > Можно заблокировать локальные серверы провайдера, чтобы YouTube использовал общие для города или региона у другого провайдера, в надежде, что с ними не будет проблем. См. тему [Задержка перед запуском видео Youtube 6-10 секунд](https://ntc.party/t/%D0%B7%D0%B0%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%BE%D0%BC-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE-youtube-6-10-%D1%81%D0%B5%D0%BA%D1%83%D0%BD%D0%B4/8395) с примером того, как следует поступать в данном случае.
> > > 
> > > 
> > > Я вообще не разбираюсь, и ничего в данной статье не понял, кроме того что провайдеры что то блокируют.
> > 
> > 
> > Программа не дает прочитать письмо, если его выкидывают из-за содержания (а там написан адресат без конкретного адреса), то программа поможет. Если же выкидывают из-за того, что оно идет на запрещенный конкретный адрес, то его выкидывают не читая. Как-то так.
> 
> А можете пожалуйста дать какую нибудь команду или что то ещё чтобы не было этой ошибки? Просто в той статье, то что понял и сделал, то не помогло.

если что , у меня провайдер "марьино.нет"
