### ISSUE TITLE
Перестали работать сетевые папки и localhost

### ISSUE THREAD

**Issue by kraamis** [ValdikSS/GoodbyeDPI#681]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

У меня на компе были расшаренные папки, с доступом внутри сети роутера. Сейчас к ним пропал доступ, после того как начал пользоваться goodbyedpi. Удаление сервиса и папки с перезагрузкой не помогает. 

Тоже касается служб запускаемых на localhost типа jupyter notebook из WinPython.

**Comment by ValdikSS** [comment]
>Удаление сервиса и папки с перезагрузкой не помогает.

Программа не меняет никакие настройки ОС.

В чём выражается недоступность, порт не принимает подключения? Запишите дамп трафика при доступе к localhost, см. https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark
Интерфейс нужно выбрать "adapter for loopback traffic capture".

**Comment by kraamis** [comment]
Поставил Wireshark и все вдруг заработало. 

Я уже весь мозг в улитку свернул. 

Прошу прощения за кипеш, но других версий у меня же не оставалось, я все перерыл. Я не профи, а просто любитель, на уровне выше среднего.

**Comment by ValdikSS** [comment]
Если сломается еще раз — напишите.
