### ISSUE TITLE
МГТС (Калуга), видео работают выборочно, смена параметров не спасает

### ISSUE THREAD

**Issue by Saytromi** [ValdikSS/GoodbyeDPI#682]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Win 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Добрый день!
Запускаю 1_russia_blacklist, со следующими настройками: 
`start "" goodbyedpi.exe -9 -e1 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt`
Часть видео работает, а часть не прогружается. Смена параметра `-9` на иные в диапазоне от 1 до 11 не помогает.  Перезагрузка (F5) и перезапуск браузера не помогают.
Альтернатива через 
`start "" goodbyedpi.exe -9 --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt` не помогает.
Провайдер МГТС (Калуга).
Браузер Хром.
Кибер отключен.

**Comment by qwace13** [comment]
Попробуй добавить -q и после продолжить перебирать цифры.
