### ISSUE TITLE
Crash при добавлении флага fake-with-sni

### ISSUE THREAD

**Issue by LightGameStudio42** [ValdikSS/GoodbyeDPI#683]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 21H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

1. Запускаю 1_russia_blacklist_YOUTUBE, консоль работает в фоне.
2. Модифицирую его, добавляю параметр `--fake-with-sni www.google.com`, либо целиком копипащу строку со "start" с обсуждений - консоль сразу после запуска крашится. На консоле нет никакого вывода
![image](https://github.com/user-attachments/assets/7b28f46c-b03f-411e-a73a-6f86eb820d66)

### Additional information / Дополнительная информация

Версия goodbyedpi-0.2.3rc3-2

**Comment by bsun0000** [comment]
Этот флаг из этого пулл-реквеста: https://github.com/ValdikSS/GoodbyeDPI/pull/665
Ещё не замержили в этот репозиторий. Качай скомпилированный бинарник из обсуждения в реквесте - он работает.
И не выделяй ничего в консоли, это фризит вывод и не всё консольное такое переваривает.

**Comment by ValdikSS** [comment]
>Версия goodbyedpi-0.2.3rc3-2

Этой опции нет в этой версии.
