### ISSUE TITLE
'--dns-addr' is not recognized as an internal command...

### ISSUE THREAD

**Issue by Kangoshi** [ValdikSS/GoodbyeDPI#684]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Запускаю модифицированный (дефолтный не помогает, добавлено `-e1 -q --fake-gen 29 --fake-from-hex тут_сгененированное_число`) service_install_russia_blacklist_dnsredir.cmd, выдаёт следующее:
![image](https://github.com/user-attachments/assets/f44f3605-a5e0-43f3-aba8-8dda5a16b53a)

### Additional information / Дополнительная информация

В службах оно появляется, но в режиме запуска "Вручную". Нужно сменить на "Автоматически" и тогда прога запускается при старте ОС и работает в нормальном режиме.

**Comment by ValdikSS** [comment]
У вас ошибка в .cmd-файле, скорее всего, --dns-addr на новой строке, и воспринимается как новая команда.
