### ISSUE TITLE
Throne And Liberty

### ISSUE THREAD

**Issue by jabbofet** [ValdikSS/GoodbyeDPI#689]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Привет! Сервера стим версии игры Throne and Liberty блокируют доступ к серверам без VPN. Есть ли шанс допилить функционал текущей проги так, чтобы не только ютуб можно было смотреть, но и поиграть с нормальным пингом в стим версию? Не уверен, какой технологией там не пускают в игру, как думаете, можно ли что-то с гудбаем сделать, чтобы помогло?

**Comment by ValdikSS** [comment]
GoodbyeDPI не поможет обойти региональную блокировку. Если доступ запрещают на стороне сервера, а не провайдера, программа бесполезна.
