### ISSUE TITLE
Developing GUI

### ISSUE THREAD

**Issue by hex4d0r** [ValdikSS/GoodbyeDPI#69]
Hey, I'm trying to developing GUI for it by execute it externally. Using Qt Framework.

But there is a problem when i tried to communicate with your software which is It seems it doesnt write stdout(buffered) i can't catch stdout from software.

I tried to compile it myself but WDK is not working, at least 7.1.0 requires very old OS.

Could you add "fflush(stdout)" to after every "printf()" statement?

It's hard to determine If the software properly works or not without reading stdout :)

**Comment by ValdikSS** [comment]
You need to switch stdout to line-buffered mode somehow. It should be line-buffered by default in Windows (at least it's so for the console output), so most probably it's a problem on your side.

**Comment by hex4d0r** [comment]
Well I was trying to compile WinDivert from source then I realize It has already compiled binary in releases. :)

So I modified code and compiled myself, problem fixed.

Btw Im planning to publish it with Turkish language only. If I wanted to add Russian lang support will you help me about it?

**Comment by ValdikSS** [comment]
It depends on a license which you're going to use for GUI source code. There's one Russian closed-source GUI exist: http://rgho.st/6dBF59FLC

**Comment by hex4d0r** [comment]
Its open source qt so I have to distribute this with Open Source, and I will.

I already implemented parameters and many things(like startup, tray icon etc). Im pretty sure my parameter implementation is poorly done :) and going to make it efficient in next releases.

I wanted to use it everyone with %100 safety(without doubt if who was think maybe something else going on in backend).

I will prepare full compilation guide for community.(for your code also)

It will be under MIT and I really didnt searched differences between open sources licences too much, just know MIT and LGPLv3.

**Comment by hex4d0r** [comment]
@sgeto qt5

**Comment by sgeto** [comment]
Oh boi…

Is it public already?
And can we see a Screenshot?

**Comment by hex4d0r** [comment]
@sgeto check my github. I released yesterday.

**Comment by madmaximka** [comment]
maybe you can add english?

**Comment by hex4d0r** [comment]
@ardor97 Ok, I will

**Comment by sgeto** [comment]
:+1

"We are saddened by a bird's cry, but not for a fish's blood.
Blessed are those with voices."

-Mamoru Oshii

**Comment by ardor97** [comment]
@hex4d0r many thanks!

**Comment by madmaximka** [comment]
@hex4d0r please translate tray icon menu. still not in english. thank you.

**Comment by hex4d0r** [comment]
@ardor97 @madmaximka Will do but please open this issues in my repository, I think this is not the place for it. :)
