### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by EGIR212GAMES** [ValdikSS/GoodbyeDPI#690]
### CAPTCHA

- [x] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 11 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Goodbyedpi Вылетает при открытии Ютуба.

### Additional information / Дополнительная информация

Я запускаю Goodbyedpi открываю ютуб и через несколько секунд Goodbyedpi вылетает

**Comment by ValdikSS** [comment]
Запустите программу в консоли, запущенной от имени администратора (пуск - cmd - запустить от имени администратора, и внутри этой консоли запускайте программу). Так вы увидите возможный вывод ошибки, если она есть.

Если её нет и программа действительно упала, нужно включить генерацию minidump-файлов в windows и прислать его.
https://helgeklein.com/blog/creating-an-application-crash-dump/

Какая у вас версия?

**Comment by EGIR212GAMES** [comment]
![Снимок экрана (39)](https://github.com/user-attachments/assets/1f685a8c-5516-40e1-9c48-00516bab1408)
На скриншоте показано то, что написано после вылета программы, я пробовал использовать последнюю и предпоследнюю версии, и они обе вылетают.

**Comment by EGIR212GAMES** [comment]
![Снимок экрана (40)](https://github.com/user-attachments/assets/26bacc8e-d84d-41da-908e-95a5e07ea9ec)
А здесь показана программа после запуска.

**Comment by deadcxde** [comment]
> ![Снимок экрана (40)](https://private-user-images.githubusercontent.com/124560022/374236872-26bacc8e-d84d-41da-908e-95a5e07ea9ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTg1MzMsIm5iZiI6MTcyODMxODIzMywicGF0aCI6Ii8xMjQ1NjAwMjIvMzc0MjM2ODcyLTI2YmFjYzhlLWQ4NGQtNDFkYS05MDhlLTk1YTVlMDdlYTllYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxNjIzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWIyZWFkMTFhYTk3NzkwODlkNmZmZTg1YzgzZWFjOGZiYWI1NTgwNzdiNTc1ZWI5YTljZWVjNGExYzM4M2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4QKtjORg8vq7aFgCJBjKcr7wFTdc9TxQQtNHIrq-WKs) А здесь показана программа после запуска.

судя по ошибке, драйвера нет в папке _где_goodbyedpi_/x86_64

**Comment by TheGlitchedMan** [comment]
забавный факт: отрубите флаг QUIC в хроме или другом браузере, тогда ютуб заработает (тестил только на своей машине)

**Comment by EGIR212GAMES** [comment]
![Снимок экрана (41)](https://github.com/user-attachments/assets/1b0a61ee-b865-4dde-ac0c-566bba25614d)
В папке все файлы на месте.

**Comment by johnnyd-78** [comment]
regedit. Перейдите в раздел HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDivert
Покажите скриншот

**Comment by ValeraBro** [comment]
> забавный факт: отрубите флаг QUIC в хроме или другом браузере, тогда ютуб заработает (тестил только на своей машине)

Не работало с самого начала. Тестил на нескольких устройствах. Голый гдпи не работает тоже.
Нужно конфиги подбирать

**Comment by EGIR212GAMES** [comment]
![Снимок экрана (43)](https://github.com/user-attachments/assets/3460e689-ee94-4952-9cec-d4a0ceabb4a3)
@johnnyd-78 Вот.

**Comment by TheGlitchedMan** [comment]
> > забавный факт: отрубите флаг QUIC в хроме или другом браузере, тогда ютуб заработает (тестил только на своей машине)
> 
> Не работало с самого начала. Тестил на нескольких устройствах. Голый гдпи не работает тоже. Нужно конфиги подбирать

я смастерил этот конфиг чтобы на ютуб просто зайти:
`for /f %%i in ('powershell -command "[byte[]]$bytes = (1..58 | ForEach-Object { Get-Random -Max 256 }); $randomHex = -join ($bytes | ForEach-Object { $_.ToString('x2') }); $randomHex"') do set "hex_value=%%i"
start "" goodbyedpi.exe -6 --fake-gen 6 --fake-resend 2 --set-ttl 1 -f 2 -e 2 --wrong-chksum --reverse-frag --max-payload -q --fake-from-hex %hex_value% --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
`

**Comment by johnnyd-78** [comment]
@EGIR212GAMES Выполните от админа service_remove.cmd - этот раздел в реесте исчезает? Обновить инфу в регедит - F5

**Comment by EGIR212GAMES** [comment]
![Снимок экрана (44)](https://github.com/user-attachments/assets/0a43318b-1d6e-4d21-9a90-1d61d8d4fbeb)
@johnnyd-78 Мне пишет это при запуске от имени администратора.

**Comment by TheGlitchedMan** [comment]
Кстати, роскомнадзор заблокировал дискорд зачем-то))

**Comment by EGIR212GAMES** [comment]
@johnnyd-78 Нажал энтер, командная строка закрылась.

**Comment by johnnyd-78** [comment]
@EGIR212GAMES Это нормально. В регедит раздел WinDivert исчез?

**Comment by EGIR212GAMES** [comment]
@johnnyd-78 Да.

**Comment by Decavoid** [comment]
> ![Снимок экрана (44)](https://private-user-images.githubusercontent.com/124560022/374469403-0a43318b-1d6e-4d21-9a90-1d61d8d4fbeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzYxODUsIm5iZiI6MTcyODM3NTg4NSwicGF0aCI6Ii8xMjQ1NjAwMjIvMzc0NDY5NDAzLTBhNDMzMThiLTFkNmUtNGQyMS05YTkwLTFkNjFkOGQ0ZmJlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwODI0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjY4OGE2ZDA5ZmU1NWM3ZDU3NGQ2NDUyYzBhNzI4MjlmYWU4OWRkOTc1OTFlZjMyMjNmYTMyMjIyMjkxMDlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LL0UtonRAhN8UIvFbVeWohrLfilWgfY2IpoVlaRTqmQ) @johnnyd-78 Мне пишет это при запуске от имени администратора.

Скрипт запущен не от админа. В окне написано, что чтобы запустить его от админа, надо нажать на него правой кнопкой и выбрать Запустить от админа.

**Comment by johnnyd-78** [comment]
@EGIR212GAMES Теперь вот всю эту goodbyedpi-0.2.3блаблабла переименуйте просто в GoodbyeDPI
Попробуйте снова запустить exe - что внизу напишет?

**Comment by EGIR212GAMES** [comment]
![Снимок экрана (45)](https://github.com/user-attachments/assets/3d72501f-dde6-4814-aa00-f19cb0161b33)
@johnnyd-78 Пишет это:

**Comment by EGIR212GAMES** [comment]
@johnnyd-78 И ютуб заработал большое спасибо :)

**Comment by johnnyd-78** [comment]
Пожалуйста.

@Decavoid Это предупреждение скрипт пишет всегда, хоть от админа, хоть нет.
