### ISSUE TITLE
"goodbyedpi" спаси Discord

### ISSUE THREAD

**Issue by BERaleks** [ValdikSS/GoodbyeDPI#691]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Возможна ли такая функция чтоб я мог попадать в Discord с помощью "goodbyedpi", если нет то можно ли будет как то это реализовать в будущем?

**Comment by DrPHDCat** [comment]
так же, дискорд пошёл к хуям

**Comment by PTS-Rus** [comment]
ByeDPI на телефоне обходит, значит вполне возможно такое сделать, спасай нас бог интернета

**Comment by HelloGamesBS** [comment]
В блэк-лист файлы### (russia-youtube.txt/russia-blacklist.txt) нужно добавить пару строк и перезагрузить комп

```
discord.com
gateway.discord.gg
cdn.discordapp.com
discordapp.net
```

**Comment by VivishkaRU** [comment]
> ByeDPI на телефоне обходит, значит вполне возможно такое сделать, спасай нас бог интернета

Блин, работает только реально чат, но всё остальное тупо встало

**Comment by johnnyd-78** [comment]
Гоу zapret изучать - будут и войс-чаты ;)

**Comment by zzzombie1989** [comment]
> Гоу zapret изучать - будут и войс-чаты ;)

Что там изучать, если на zapret такое же нытьё. Пока что не придумали способ обойти UDP пакеты.

**Comment by johnnyd-78** [comment]
В блэклист ютуба добавляем:
`discord.com
discord.gg
discordapp.com
discordapp.net
discord.media
discord-attachments-uploads-prd.storage.googleapis.com`

Работает все, кроме войса. На GDPI только так.

**Comment by unreal79** [comment]
Мой список:
```
dis.gd
discord.co
discord.com
discord.design
discord.dev
discord.gg
discord.gift
discord.gifts
discord.media
discord.new
discord.store
discord.tools
discordapp.com
discordapp.net
discordmerch.com
discordpartygames.com
discord-activities.com
discordactivities.com
discordsays.com
discordstatus.com
gateway.discord.gg
cdn.discordapp.com
discord-attachments-uploads-prd.storage.googleapis.com
```
