### ISSUE TITLE
как "починить" discord

### ISSUE THREAD

**Issue by HafuPlay** [ValdikSS/GoodbyeDPI#692]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

пока официального фикса нет, используйте этот

откройте russia-blacklist.txt и допишите домены

```
discord-attachments-uploads-prd.storage.googleapis.com
dis.gd
discord.co
discord.com
discord.design
discord.dev
discord.gg
discord.gift
discord.gifts
discord.media
discord.new
discord.store
discord.tools
discordapp.com
discordapp.net
discordmerch.com
discordpartygames.com
discord-activities.com
discordactivities.com
discordsays.com
```

затем перезапустите goodbyedpi или запустите service install снова (или перезагрузите ПК)

если у вас не работает ютуб, то этот фикс работать тоже не будет, сначала найдите актуальную конфигурацию goodbyedpi

если знаете еще домены, то поделитесь в комментариях
если вам нужные голосовые каналы, то попробуйте использовать zapret, ибо goodbyedpi может обходить определенные домены

**Comment by HelloGamesBS** [comment]
Голосовые вряд-ли можно починить, ибо они идут на UDP адреса

**Comment by VivishkaRU** [comment]
> ### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> * [x]  I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> 
> ### Describe your feature / Опишите ваше предложение
> пока официального фикса нет, используйте этот
> 
> откройте russia-blacklist.txt и допишите домены
> 
> ```
> dis.gd
> discord.co
> discord.com
> discord.design
> discord.dev
> discord.gg
> discord.gift
> discord.gifts
> discord.media
> discord.new
> discord.store
> discord.tools
> discordapp.com
> discordapp.net
> discordmerch.com
> discordpartygames.com
> discord-activities.com
> discordactivities.com
> discordsays.com
> discordstatus.com
> ```
> 
> затем перезапустите goodbyedpi или запустите service install снова
> 
> я не смог найти все домены, по этому войс не работает. если найдете еще, то дополните в комментариях

На удивление, в byedpi на андроид фурычат вложения, видимо у них отдельный домен тоже, хз

**Comment by suspiciouspotato47** [comment]
@HafuPlay , не работает. похоже надо будет что то менять, ждём фикса от кого то.

**Comment by HelloGamesBS** [comment]
> > ### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> > 
> > * [x]   I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> > 
> > ### Describe your feature / Опишите ваше предложение
> > пока официального фикса нет, используйте этот
> > откройте russia-blacklist.txt и допишите домены
> > ```
> > dis.gd
> > discord.co
> > discord.com
> > discord.design
> > discord.dev
> > discord.gg
> > discord.gift
> > discord.gifts
> > discord.media
> > discord.new
> > discord.store
> > discord.tools
> > discordapp.com
> > discordapp.net
> > discordmerch.com
> > discordpartygames.com
> > discord-activities.com
> > discordactivities.com
> > discordsays.com
> > discordstatus.com
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > затем перезапустите goodbyedpi или запустите service install снова
> > я не смог найти все домены, по этому войс не работает. если найдете еще, то дополните в комментариях
> 
> На удивление, в byedpi на андроид фурычат вложения, видимо у них отдельный домен тоже, хз

На андроиде ciadpi работает по другому, вроде как

**Comment by VivishkaRU** [comment]
> > > ### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> > > 
> > > * [x]    I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> > > 
> > > ### Describe your feature / Опишите ваше предложение
> > > пока официального фикса нет, используйте этот
> > > откройте russia-blacklist.txt и допишите домены
> > > ```
> > > dis.gd
> > > discord.co
> > > discord.com
> > > discord.design
> > > discord.dev
> > > discord.gg
> > > discord.gift
> > > discord.gifts
> > > discord.media
> > > discord.new
> > > discord.store
> > > discord.tools
> > > discordapp.com
> > > discordapp.net
> > > discordmerch.com
> > > discordpartygames.com
> > > discord-activities.com
> > > discordactivities.com
> > > discordsays.com
> > > discordstatus.com
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > затем перезапустите goodbyedpi или запустите service install снова
> > > я не смог найти все домены, по этому войс не работает. если найдете еще, то дополните в комментариях
> > 
> > 
> > На удивление, в byedpi на андроид фурычат вложения, видимо у них отдельный домен тоже, хз
> 
> На андроиде ciadpi работает по другому, вроде как

Это печально, надеюсь мы найдём решение проблемы, которую нам создали

**Comment by HromasDev** [comment]
В Discord работает, но войсе пишет Не установлен маршрут

> ### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> * [x]  I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> 
> ### Describe your feature / Опишите ваше предложение
> пока официального фикса нет, используйте этот
> 
> откройте russia-blacklist.txt и допишите домены
> 
> ```
> dis.gd
> discord.co
> discord.com
> discord.design
> discord.dev
> discord.gg
> discord.gift
> discord.gifts
> discord.media
> discord.new
> discord.store
> discord.tools
> discordapp.com
> discordapp.net
> discordmerch.com
> discordpartygames.com
> discord-activities.com
> discordactivities.com
> discordsays.com
> discordstatus.com
> ```
> 
> затем перезапустите goodbyedpi или запустите service install снова
> 
> я не смог найти все домены, по этому войс не работает. если найдете еще, то дополните в комментариях

В Discord работает, но войсе пишет Не установлен маршрут

**Comment by Kredwi** [comment]
Ребята, как сделать, чтобы goodbyedpi работал на вебсокеты? А то звонки не работают

**Comment by Azperin** [comment]
Chrome нормально заходит.
Firefox выдает SSL_ERROR_PROTOCOL_VERSION_ALERT.
Десктопная не может подключиться.

Есть решения починки последних двух ?

**Comment by PomalinTheCat** [comment]
ростелеком якутия данный фикс помог
кста discordstatus.com работает нормально зачем его было добавлять

**Comment by Nastyaosincavatv** [comment]
голосовой тупо подключение к RTC.. и не установлен маршрут😑

**Comment by pavel355** [comment]
Прошу, найдите домены, чтобы войс работал

**Comment by johnnyd-78** [comment]
Да нет смысла искать домены чтобы войс работал, GDPI не умеет в обход UDP, усвойте это наконец

**Comment by 0egortv0** [comment]
Хочу спросить, а для браузера ещё не сделали фикс?

**Comment by KOlabZz** [comment]
> Хочу спросить, а для браузера ещё не сделали фикс?

Там для голоса используется тот же WebRTC, можно с VPN сидеть, но это снижение скорости трафика, а goodbyedpi в обход UDP не умеет

**Comment by Senpai262** [comment]
> ### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> * [x]  I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> 
> ### Describe your feature / Опишите ваше предложение
> пока официального фикса нет, используйте этот
> 
> откройте russia-blacklist.txt и допишите домены
> 
> ```
> discord-attachments-uploads-prd.storage.googleapis.com
> dis.gd
> discord.co
> discord.com
> discord.design
> discord.dev
> discord.gg
> discord.gift
> discord.gifts
> discord.media
> discord.new
> discord.store
> discord.tools
> discordapp.com
> discordapp.net
> discordmerch.com
> discordpartygames.com
> discord-activities.com
> discordactivities.com
> discordsays.com
> ```
> 
> затем перезапустите goodbyedpi или запустите service install снова (или перезагрузите ПК)
> 
> если у вас не работает ютуб, то этот фикс работать тоже не будет, сначала найдите актуальную конфигурацию goodbyedpi
> 
> если знаете еще домены, то поделитесь в комментариях если вам нужные голосовые каналы, то попробуйте использовать zapret, ибо goodbyedpi может обходить определенные домены

[discord.txt](https://github.com/user-attachments/files/17291754/discord.txt)

Это какие я нашел домены

**Comment by PomalinTheCat** [comment]
этот фикс работает через раз
мол иногда он может перестать работать

**Comment by Fennec-F0x** [comment]
> > ### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> > 
> > * [x]   I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> > 
> > ### Describe your feature / Опишите ваше предложение
> > пока официального фикса нет, используйте этот
> > откройте russia-blacklist.txt и допишите домены
> > ```
> > discord-attachments-uploads-prd.storage.googleapis.com
> > dis.gd
> > discord.co
> > discord.com
> > discord.design
> > discord.dev
> > discord.gg
> > discord.gift
> > discord.gifts
> > discord.media
> > discord.new
> > discord.store
> > discord.tools
> > discordapp.com
> > discordapp.net
> > discordmerch.com
> > discordpartygames.com
> > discord-activities.com
> > discordactivities.com
> > discordsays.com
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > затем перезапустите goodbyedpi или запустите service install снова (или перезагрузите ПК)
> > если у вас не работает ютуб, то этот фикс работать тоже не будет, сначала найдите актуальную конфигурацию goodbyedpi
> > если знаете еще домены, то поделитесь в комментариях если вам нужные голосовые каналы, то попробуйте использовать zapret, ибо goodbyedpi может обходить определенные домены
> 
> [discord.txt](https://github.com/user-attachments/files/17291754/discord.txt)
> 
> Это какие я нашел домены

Добавь к ним еще:

cdn.discordapp.com
tenor.com

Для картинок и гифок внутри дискорда

**Comment by Decavoid** [comment]
> Добавь к ним еще:
> 
> cdn.discordapp.com

Поддомены включаются автоматически. Нет смысла включать cdn.discordapp.com, потому что в списке уже есть discordapp.com.

**Comment by kekmachine123** [comment]
> ### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> * [x]  I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> 
> ### Describe your feature / Опишите ваше предложение
> пока официального фикса нет, используйте этот
> 
> откройте russia-blacklist.txt и допишите домены
> 
> ```
> discord-attachments-uploads-prd.storage.googleapis.com
> dis.gd
> discord.co
> discord.com
> discord.design
> discord.dev
> discord.gg
> discord.gift
> discord.gifts
> discord.media
> discord.new
> discord.store
> discord.tools
> discordapp.com
> discordapp.net
> discordmerch.com
> discordpartygames.com
> discord-activities.com
> discordactivities.com
> discordsays.com
> ```
> 
> затем перезапустите goodbyedpi или запустите service install снова (или перезагрузите ПК)
> 
> если у вас не работает ютуб, то этот фикс работать тоже не будет, сначала найдите актуальную конфигурацию goodbyedpi
> 
> если знаете еще домены, то поделитесь в комментариях если вам нужные голосовые каналы, то попробуйте использовать zapret, ибо goodbyedpi может обходить определенные домены

Подряд ВДК дискорд зарабоотал

**Comment by johnnyd-78** [comment]
tenor не нужен, гифки и так нормально работают.

**Comment by SOOOOFA** [comment]
Вообще не пашит( Всё сделала по инструкции. Не браузерная версия, не приложение не работает*

**Comment by 1MuTTiX1** [comment]
Нашёл один способ как подключаться к голосовому каналу без пинга(правда придётся тыкать постоянно). Так же устанавливайте гудбай дипиай если у вас заходит в сам дискорд всё хорошо. Скачиваете какой нибудь впн на пк и подключаетесь к голосовому каналу потом отключаете. Не знаю почему он не отрубается так как не знаю как работают подключения но они как-то работают без впн. Такая же ситуация и с трансляцией такой же порядок.
Может как-то поможет эти знания для модификации гудбай дипиай

**Comment by NikitaNasedkin** [comment]
> Нашёл один способ как подключаться к голосовому каналу без пинга(правда придётся тыкать постоянно). Так же устанавливайте гудбай дипиай если у вас заходит в сам дискорд всё хорошо. Скачиваете какой нибудь впн на пк и подключаетесь к голосовому каналу потом отключаете. Не знаю почему он не отрубается так как не знаю как работают подключения но они как-то работают без впн. Такая же ситуация и с трансляцией такой же порядок. Может как-то поможет эти знания для модификации гудбай дипиай

На данный момент сработало, подключиться с впн потом его выключить, вроде норм

**Comment by antieksi** [comment]
Сделал всё так, как вы писали в этом треде. Не работает.
ByeDPI на телефоне притом прекрасно справляется.

**Comment by AshyDisaster** [comment]
тоже самое у меня как и у antieksi тут. всё на телефоне прекрасно но на ПК трудно

**Comment by ExplosiveTNT** [comment]
Не работает на WIN PC ;(

**Comment by Olegus-Dark** [comment]
хы, 
- а не раздать ли мне инет наааааа ПэээКаааа? 
- а не бустят ли мобильные провадеры запрет?
...
кста у кого анлим и ловит норма (ну мбит 5-20 - как вариант, я так первое время обходил блок ютубов


а так как вариант - поднимать ssh на vps/vds в другой стране и будет вам и ютаб и дискорд и много чего (вариантов подобных конфигов в сети достаточно как и серваков на любой вкус и цвет)

**Comment by G1ZMO** [comment]
Спасибо @Olegus-Dark за совет, мы его очень ценим, но мы тут ищем бесплатный способ решения.

**Comment by Abamalitanin** [comment]
боже храни россию от запретов

**Comment by iiitoiiop2** [comment]
нашел решение, костылем: качаете какой-нибудь VPN на комп. Включаете, подключаетесь с ГС каналу, выключаете впн после успешного коннекта

**Comment by Abamalitanin** [comment]
> нашел решение, костылем: качаете какой-нибудь VPN на комп. Включаете, подключаетесь с ГС каналу, выключаете впн после успешного коннекта

не у всех работает

**Comment by Roman-n** [comment]
Народ, сегодня ничего не работает, у меня Yota - ВПН вообще не работает, как только врубаешь впн -> скорость тупа падает на ноль, видимо Yota глушит, с DPI работал и ютуб и дискорд, не идеально но работало, а сегодня с утра запускаю DPI - работает секунд 10 и просто закрывается сам, не хочет работать сам DPI. У кого подобное было? Винду не обновлял, ничего подобного.

**Comment by drafwodgaming** [comment]
138.128.136.0/21
162.158.0.0/15
172.64.0.0/13
34.0.0.0/15
34.2.0.0/16
34.3.0.0/23
34.3.2.0/24
35.192.0.0/12
35.208.0.0/12
35.224.0.0/12
35.240.0.0/13
5.200.14.128/25
66.22.192.0/18
162.158.0.0/15

Этих айпи обычно должно хватать для гс диса

**Comment by Nakilon** [comment]
> 138.128.136.0/21 162.158.0.0/15 172.64.0.0/13 34.0.0.0/15 34.2.0.0/16 34.3.0.0/23 34.3.2.0/24 35.192.0.0/12 35.208.0.0/12 35.224.0.0/12 35.240.0.0/13 5.200.14.128/25 66.22.192.0/18 162.158.0.0/15
> 
> Этих айпи обычно должно хватать для гс диса

пардон, а куда это вставлять?
я пока переключился на использование другой проги

**Comment by Godbyedpi** [comment]
А скажи где взять все адреса, хочу попробовать с Battle.net такое провернуть

**Comment by NNMA222** [comment]
> ### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> * [x]  I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> 
> ### Describe your feature / Опишите ваше предложение
> пока официального фикса нет, используйте этот
> 
> откройте russia-blacklist.txt и допишите домены
> 
> ```
> discord-attachments-uploads-prd.storage.googleapis.com
> dis.gd
> discord.co
> discord.com
> discord.design
> discord.dev
> discord.gg
> discord.gift
> discord.gifts
> discord.media
> discord.new
> discord.store
> discord.tools
> discordapp.com
> discordapp.net
> discordmerch.com
> discordpartygames.com
> discord-activities.com
> discordactivities.com
> discordsays.com
> ```
> 
> затем перезапустите goodbyedpi или запустите service install снова (или перезагрузите ПК)
> 
> если у вас не работает ютуб, то этот фикс работать тоже не будет, сначала найдите актуальную конфигурацию goodbyedpi
> 
> если знаете еще домены, то поделитесь в комментариях если вам нужные голосовые каналы, то попробуйте использовать zapret, ибо goodbyedpi может обходить определенные домены
