### ISSUE TITLE
КАК УДАЛИТЬ, пишет что занято другим процессом, я про файл windivert64.sys

### ISSUE THREAD

**Issue by razradRRR** [ValdikSS/GoodbyeDPI#698]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

.

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

не удаляется

### Additional information / Дополнительная информация

.

**Comment by TokcDK** [comment]
переименовать, если цель заменить здесь и сейчас, либо перезагрузить систему.

**Comment by ValdikSS** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/378
