### ISSUE TITLE
Новая прога совмещающая в себе функции впн, ZZapret и goodbyedpi

### ISSUE THREAD

**Issue by ERmak148** [ValdikSS/GoodbyeDPI#700]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Я не знаю точно, возможно ли это или же нет, но я думаю возможно. Идея в том что бы пропускать весь траффик через локальный прокси сервер (который можно по дефолту в винде включить), который будет работать как GoodbyeDPI для Youtube, как Zapret для Discord и как впн для указанных сервисов (ну там покупать покупать прокси в другой стране надо, там главное разобраться), такие как chatgpt, инстаграм и прочие. Такая многофункциональная программа в наше время нужна каждому

**Comment by ValdikSS** [comment]
Прокси-серверы, в основной массе, либо не поддерживают UDP, либо поддерживают его ограниченно. Звонки, с большой вероятностью, работать не будут.

**Comment by Jebati** [comment]
Да, определенно такие решение было бы нужно. Учитывая, что одним анти-DPI сыт не будешь, когда надо обходить ограничения уже с дрогой стороны

**Comment by Gxtod** [comment]
> Прокси-серверы, в основной массе, либо не поддерживают UDP, либо поддерживают его ограниченно. Звонки, с большой вероятностью, работать не будут.

Вы можете собрать новую версию? У вас коммит висит недельной давности куда добавили генератор [Add TLS ClientHello fake packet generator](https://github.com/ValdikSS/GoodbyeDPI/commit/810aef6aedf2f14f25e5726736c0baa635c18eb0)

А в релизах всё ещё болтается [0.2.3rc3](https://github.com/ValdikSS/GoodbyeDPI/releases/tag/0.2.3rc3) Pre-release месячной давности...

**Comment by Sovenok-Hacker** [comment]
> ### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> * [x]  I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> 
> ### Describe your feature / Опишите ваше предложение
> Я не знаю точно, возможно ли это или же нет, но я думаю возможно. Идея в том что бы пропускать весь трафик через локальный прокси сервер (который можно по дефолту в винде включить), который будет работать как GoodbyeDPI для Youtube, как Zapret для Discord и как впн для указанных сервисов (ну там покупать покупать прокси в другой стране надо, там главное разобраться), такие как chatgpt, инстаграм и прочие. Такая многофункциональная программа в наше время нужна каждому

Можно сделать скрипты для переключения, вроде Zapret делает то же, что и GoodbyeDPI. Увы, насколько я знаю, WebRTC работает на UDP, так что как и сказал @ValdikSS WebRTC-звонки работать не будут, как и QUIC и тд.

**Comment by etadex** [comment]
> > ### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> > 
> > * [x]   I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
> > 
> > ### Describe your feature / Опишите ваше предложение
> > Я не знаю точно, возможно ли это или же нет, но я думаю возможно. Идея в том что бы пропускать весь трафик через локальный прокси сервер (который можно по дефолту в винде включить), который будет работать как GoodbyeDPI для Youtube, как Zapret для Discord и как впн для указанных сервисов (ну там покупать покупать прокси в другой стране надо, там главное разобраться), такие как chatgpt, инстаграм и прочие. Такая многофункциональная программа в наше время нужна каждому
> 
> Можно сделать скрипты для переключения, вроде Zapret делает то же, что и GoodbyeDPI. Увы, насколько я знаю, WebRTC работает на UDP, так что как и сказал @ValdikSS WebRTC-звонки работать не будут, как и QUIC и тд.

прямо сейчас использую для дискорда связку Oblivion + ProxyCAP, обливион открывает подключение своё, хостит SOCKS5 прокси, который поддерживает UDP, а ProxyCAP заворачивает в него трафик (tcp + udp) дискорда. 
Из проблем - голосовой трафик от меня притормаживает, но голос в дискорде работает. 
По сути для аналогичной функциональности у GoodbyeDPI не хватает  только поддержки работы с UDP и модуля для прокси SOCKS5. А потом желающие могут точно так же через ProxyCap завернуть в созданную проксю свой трафик.

**Comment by Sovenok-Hacker** [comment]
> ProxyCAP

У меня CF WARP уже не работает.

**Comment by johnnyd-78** [comment]
> У вас коммит висит недельной давности

Самому пулл-реквесту вообще почти месяц. Да он и не особо помогает сейчас, после 9-го это все накрылось медным тазиком на большинстве провайдеров. Да, сайты открывает, но с видео ютуба проблем не решает от слова совсем.

**Comment by MasterBanka** [comment]
> У меня CF WARP уже не работает.

Всё прекпасер работает, конфиг нужно обновлять раз в сколько то дней

**Comment by warelog1** [comment]
> > У меня CF WARP уже не работает.
> 
> Всё прекрасно работает, конфиг нужно обновлять раз в сколько то дней

уточните пожалуйста что и где нужно сменить, а то вообще не конектит уже 3 или 4 день (грешил на то что у них техработы, но с виду рф сервера работают стабильно)

**Comment by Fan4eGGG** [comment]
> Вы можете собрать новую версию? У вас коммит висит недельной давности куда добавили генератор [Add TLS ClientHello fake packet generator](https://github.com/ValdikSS/GoodbyeDPI/commit/810aef6aedf2f14f25e5726736c0baa635c18eb0)
> 
> А в релизах всё ещё болтается [0.2.3rc3](https://github.com/ValdikSS/GoodbyeDPI/releases/tag/0.2.3rc3) Pre-release месячной давности...

это так и будет проигнорировано?

**Comment by razor179** [comment]
я думаю тут давно никто ничем не занимается

**Comment by Alucard648** [comment]
> я думаю тут давно никто ничем не занимается, так как прога на мгтс вообще перестала работать, всё равно с какими ключами запускать, печально это всё, очень печально, а программистов у нас походу нету или они все работают на....

А ещё они боятся получить срок в тюрьме по будущей статье "Предоставление средств для доступа к запрещённой информации". А там, скорее всего, запросто можно угодить лет на 20... :-(
