### ISSUE TITLE
Discord patch

### ISSUE THREAD

**Issue by LemoLev** [ValdikSS/GoodbyeDPI#701]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

I have added a patch for this DPI to be able to open the discord app.

How to add:
Download [the patch archive](https://github.com/user-attachments/files/17349312/discordPatch.zip)
Unpack in the release folder
And launch your preferred file.
////RUS////
Я сделал патч. который с которым можно открыть дискорд (проверенно)

Как добавить:
Скачайте [архив с патчем](https://github.com/user-attachments/files/17349312/discordPatch.zip)
Разархивируйте в папку релиза GoodbyeDPI
И запустите свой предпочитаемый файл

**Comment by dfyzdeus** [comment]
start "" goodbyedpi.exe -9 --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt --blacklist ..\russia-discord.txt
ток так запустилось (просто добавил блеклист)

**Comment by slxsh1k** [comment]
работает ли войс?

**Comment by LemoLev** [comment]
> работает ли войс?

должен

**Comment by LemoLev** [comment]
> Any source code or PR?

no, i only added a text file and changed some .bat's

**Comment by Zelassin** [comment]
с чего бы войс работал? там же UDP

**Comment by zzzombie1989** [comment]
Для тех, кому надо - собрал рабочий патч GoodbyeDPI для Discord
Нужно распаковать содержимое в папку с GoodbyeDPI и запустить Discord_Install_FIX.exe
[GoodbyeDPI_Discord_FIX_by_zzzombie89.zip](https://github.com/user-attachments/files/17350161/GoodbyeDPI_Discord_FIX_by_zzzombie89.zip)

**Comment by ID86s** [comment]
вот <strike>все</strike> многие ip и dns сервера для voip discord [ds.txt](https://github.com/user-attachments/files/17354396/ds.txt)

> с чего бы войс работал? там же UDP



вот список ру серверов [ds-ru.txt](https://github.com/user-attachments/files/17354427/ds-ru.txt)
