### ISSUE TITLE
YouTube не грузит само видео, превью и прочее грузит

### ISSUE THREAD

**Issue by risandkiss** [ValdikSS/GoodbyeDPI#702]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 11 24H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Перебрал тысячу методов с раздела issues. Ни в какую не работает видео. Страницы грузит, превьюшки тоже, стоп кадры тоже все видны, но видео не загружает. Пробовал этот[ метод](https://github.com/ValdikSS/GoodbyeDPI/pull/665) ,с генерацией фейк хекса пробовал, разные настройки тоже. Ничего не помогло. Проблема такая примерно уже неделю. Оператор дом ру.

### Additional information / Дополнительная информация

-

**Comment by N1ckn1ght** [comment]
Раз уж issue создан, тоже несколько дней GDPI как отвалился, никакой пресет не работает, да и действия из issues тоже. Тестировал на Билайн, ТТК, Теле2. РКН уже запатчил коробки?

**Comment by dwoodd** [comment]
Все работает и по сей день
Билайн, пресет таков
-e 2 --native-frag --set-ttl 5 --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --frag-by-sni

**Comment by albamef** [comment]
> Все работает и по сей день Билайн, пресет таков -e 2 --native-frag --set-ttl 5 --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --frag-by-sni

Не работает, ростелеком

**Comment by dwoodd** [comment]
> > Все работает и по сей день Билайн, пресет таков -e 2 --native-frag --set-ttl 5 --fake-from-hex 1603030135010001310303424143facf5c983ac8ff20b819cfd634cbf5143c0005b2b8b142a6cd335012c220008969b6b387683dedb4114d466ca90be3212b2bde0c4f56261a9801 --frag-by-sni
> 
> Не работает, ростелеком

Можешь попробовать поставить ttl меньше

**Comment by rellikmil** [comment]
> Раз уж issue создан, тоже несколько дней GDPI как отвалился, никакой пресет не работает, да и действия из issues тоже. Тестировал на Билайн, ТТК, Теле2. РКН уже запатчил коробки?

тоже самое, пробовал через goodcheck - показывает пресеты только на 4 из 23 сайтов, и все, а так пробовал что видел; провайдер не скажу, но региональный малоизвестный

**Comment by Legion-101** [comment]
> > Раз уж issue создан, тоже несколько дней GDPI как отвалился, никакой пресет не работает, да и действия из issues тоже. Тестировал на Билайн, ТТК, Теле2. РКН уже запатчил коробки?
> 
> тоже самое, пробовал через goodcheck - показывает пресеты только на 4 из 23 сайтов, и все, а так пробовал что видел; провайдер не скажу, но региональный малоизвестный

Аналогично, GoodCheck показывает 4 рабочих из 23, ничего не помогает(
