### ISSUE TITLE
Прога запускается, но несмотря на все изменения, которые я вносил ютуб не запускается

### ISSUE THREAD

**Issue by KOSTYANKO08** [ValdikSS/GoodbyeDPI#703]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 11 23H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Менял фейк ген хекс, не помогает

**Comment by rellikmil** [comment]
Это конечно интересно, зачем даже в закрытых issue закрывают комментарии, но тем не менее у меня как я говорил goodcheck предлагал пресеты только на 4 из 23 сайтов, не телефоне вообще было плохо, но там предложили вот такой пресет для ByeDPI: -n “www.google.com” -q 1+s -O 1 -s 25+s -t 5, и мало того что заработало, так ещё наконец за все время предзагрузка видео в 10 секунд ушло, вот интересно, можно ли на компе это сделать?

**Comment by KOSTYANKO08** [comment]
сори я только недавно сюда в первый раз зашёл

**Comment by KOSTYANKO08** [comment]
аааа просто опять не туда нажал. я здесь недавно

**Comment by YuzuMajere** [comment]
> Это конечно интересно, зачем даже в закрытых issue закрывают комментарии, но тем не менее у меня как я говорил goodcheck предлагал пресеты только на 4 из 23 сайтов, на телефоне вообще было плохо, но там предложили вот такой пресет для ByeDPI: -n “www.google.com” -q 1+s -O 1 -s 25+s -t 5, и мало того что заработало, так ещё наконец за все время предзагрузка видео в 10 секунд ушло, вот интересно, можно ли на компе это сделать?

Наконец-то заработал BDPI на телефоне, спасибо за аргументы!

**Comment by N1ckn1ght** [comment]
За автором, походу, приехали. Но тут рабочий совет был для Билайна, хотя бы. https://github.com/ValdikSS/GoodbyeDPI/issues/702
