### ISSUE TITLE
Dead-link

### ISSUE THREAD

**Issue by Andrasolin** [ValdikSS/GoodbyeDPI#705]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

По идее много времени прошло и уже не актуально, и всё же. Просто удалите этот текст или восстановите, оно не работает при Клике

![001](https://github.com/user-attachments/assets/e637f905-8b26-4f07-9535-93583357e49c)

**Comment by Andrasolin** [comment]
:) нужен мод на переподключение или откл.функции Отключения мода-ВПН спустя 14минут, есть мод-ВПН Hoxx, который для пиара себя использует хороший сервер, и спустя 15 минут отключается

**Comment by ValdikSS** [comment]
Только что проверил — проблем не вижу. В каком браузере не работает?

**Comment by uniqm** [comment]
Форум открывается 10% времени из суток, остальное время или полностью не открывается, или сыпет ошибками и не грузит комментарии.

**Comment by ValdikSS** [comment]
Проблем на последние дни в доступности не было.
Домен форума заблокирован, необходимо использовать VPN и другие способы обхода блокировок.

**Comment by Andrasolin** [comment]
аа вот оно что. а дописать про это не судьба и лень

**Comment by Studyoz** [comment]
> не судьба и лень

Я объясню, почему не судьба.

Вы это пишете в репозитории, посвящённом обходу блокировок, описание и обсуждение (равно распространение) которого уже достаточно давно в стране является незаконным. Думаю, это просто очевидно, что для получения доступа к ресурсу, особенно вне такой площадки, как GitHub, касающемуся этой темы понадобятся уже хоть какие-то способы обхода. Вы в этом живёте, это реалии текущего дня. И указывать, что какой-то домен на сегодня может быть заблокирован/разблокирован (особенно с той частотой и в тех объёмах, в которых это происходит сейчас) - ненужное действие. Я 90% времени в сети через прокси, не могу сёрфить банальные обои на десктоп из-за того, что сайт блокнули через суд в Вышнем Волочке, потому что на нём есть страница с картинкой, на которой обнимаются две женщины, а, чтобы увидеть львиную долю встроенного контента с ресурсов, которыми пользуется вся Россия, приходится жать вкл./выкл. регулярно.

Просто не приходите сюда, чтобы писать такое. На этом сайте Вам никто ничем не обязан, и Вы сами ищете решение Вашей же проблемы. Ленитесь в этом топике только Вы, когда оказываетесь не в состоянии обеспечить себе самому комфорт в быту. Читая каждый следующий ответ, в котором Вам что-либо такое же элементарное разжевали, приходите постепенно к пониманию, что Вам помогли, хоть и не были обязаны, за что, по правилам хорошего тона, вообще-то говорят волшебные слова, как минимум. Не надо гадить людям в душу, особенно в тех местах, в которых Вы не знаете, как всё устроено.
