### ISSUE TITLE
Функция --fake-with-sni <value> не найдена

### ISSUE THREAD

**Issue by yaangelos** [ValdikSS/GoodbyeDPI#712]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

windows 10 22/h2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

1

### Additional information / Дополнительная информация

Добрый день.
Скачал последний релиз, но там нет функции --fake-with-sni <value> 
и вопросик еще насчет компиляции
При выполнении компиляции make CPREFIX=x86_64-w64-mingw32- BIT64=1 WINDIVERTHEADERS=/path/to/windivert/include WINDIVERTLIBS=/path/to/windivert/amd64

выдает
path/to/mingw goodbyedpi.o:goodbyedpi.c:(.text.startup+0x662): undefined reference to `flush_dns_cache'
path/to/mingw goodbyedpi.o:goodbyedpi.c:(.text.startup+0x67b): undefined reference to `blackwhitelist_load_list'
path/to/mingw goodbyedpi.o:goodbyedpi.c:(.text.startup+0x1427): undefined reference to `dns_handle_incoming'
path/to/mingw goodbyedpi.o:goodbyedpi.c:(.text.startup+0x190f): undefined reference to `dns_handle_outgoing'
path/to/mingw goodbyedpi.o:goodbyedpi.c:(.text.startup+0x1ba5): undefined reference to `dns_is_dns_packet'
path/to/mingw goodbyedpi.o:goodbyedpi.c:(.text.startup+0x1c14): undefined reference to `dns_is_dns_packet'
path/to/mingw goodbyedpi.o:goodbyedpi.c:(.text.startup+0x2044): undefined reference to `dns_handle_outgoing'
path/to/mingw goodbyedpi.o:goodbyedpi.c:(.text.startup+0x20b2): undefined reference to `dns_handle_incoming'
path/to/mingw goodbyedpi.o:goodbyedpi.c:(.text.startup+0x2480): undefined reference to `blackwhitelist_check_hostname'
path/to/mingw goodbyedpi.o:goodbyedpi.c:(.text.startup+0x2546): undefined reference to `blackwhitelist_check_hostname'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:56: goodbyedpi.exe] Error 1

**Comment by EgorWeders** [comment]
Насчет --fake-with-sni : вам надо сюда https://github.com/ValdikSS/GoodbyeDPI/pull/665  и вытащить оттуда уже файлы с новой функцией.

**Comment by EgorWeders** [comment]
Насколько я помню порядок работы makefile, ваши флаги он перезапишет он перезапишет внутри на 

```
ifndef MSYSTEM
	CPREFIX = x86_64-w64-mingw32-
endif


WINDIVERTHEADERS = ../../../include
WINDIVERTLIBS = ../../binary
MINGWLIB = /usr/x86_64-w64-mingw32/lib/

```

если вы пользуетесь makefile в репозитории.

**Comment by EgorWeders** [comment]
Не в тему немного: 
Если нужно вам или автор решит, могу CMakeLists.txt со сборкой такой же сделать. чтобы рядом просто лежал в репе

**Comment by yaangelos** [comment]
Спасибо будем пробывать.
