### ISSUE TITLE
я уже устал, можете новичку помочь с этой фигнёй? я ничерта не понимаю

### ISSUE THREAD

**Issue by 123ozzo123** [ValdikSS/GoodbyeDPI#714]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

windows10 22ч2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

несколько месяцев пользовался DPI по решению https://github.com/ValdikSS/GoodbyeDPI/issues/658, и всё работало. потом я отлучился от компа на 2 недели, прихожу и ничего не работает, смотрю решения а там все пишут что-то непонятно, ничерта не понимаю. скинте пожалуйста актуальное решение просто чтоб ютуб работал

### Additional information / Дополнительная информация

пишу сюда, потому-что другие ссылки для оставления вопросов просто не работают

**Comment by GoldenDelicio** [comment]
С GoodbyeDPI теперь проблемы, роскомнадзор решил избавится от него, но есть альтернатива в виде ZAPRET

**Comment by 123ozzo123** [comment]
ЕБАТЬ ТЫ ПЕРЕЦ! СПАСИБО ЗА ПОМОЩ! буквально 1 файл открыл и уже работает и ютуб и дискорд
