### ISSUE TITLE
GoodbyeDPI

### ISSUE THREAD

**Issue by VerGanT** [ValdikSS/GoodbyeDPI#715]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Возможно не по теме
До этого работало отлично. Нужно было срочно отключить сервис, отключил через диспеетчер задач, забыл, что можно отключить через .cmd в папке. 
После этого GoodbyeDPI перестал работать, перепробовал всё, менял значения в тексте и так далее
После последний манипуляций выдало ошибку 1062, но решения не нашел, хотел бы попросить помощи
![i40BB3tkIOA](https://github.com/user-attachments/assets/89ec533d-75a2-4a16-b462-74125e46bb9e)

**Comment by ValdikSS** [comment]
У вас сломан .cmd-файл.

**Comment by VerGanT** [comment]
как его можно починить, даже скачивал из чистого архива, проблема не ушла

**Comment by ValdikSS** [comment]
Из вашего скриншота видно, что вы перенесли строку (нажали enter) в недопустимом месте в .cmd-файле.
В файлах cmd из архива такой проблемы нет. Если программа не запускается, предоставьте актуальную информацию (выводы, ошибки).
