### ISSUE TITLE
KES 11 + GoodByDPI = BSOD

### ISSUE THREAD

**Issue by Kommunist7304** [ValdikSS/GoodbyeDPI#72]
Все прекрасно работало с KES 10 SP2 MR1 и более старыми, но после обновления до релизной версии KES 11 стало падать в BSOD.
После остановки службы GoodByDPI падения прекратились и можно спокойно лазить в инете. Стоит запустить службу и секунд через 30 серфинга система падает с руганью на драйвер tcpip.sys.

KES 11.0.0.6499
GoodbyeDPI v0.1.4
Windows 10 PRO x64 Build 1709

Наверное следует завести как багу на форуме ЛК, но может с вашей стороны удастся поправить.

**Comment by ValdikSS** [comment]
Похоже на проблему в антивирусе. Напишите в техническую поддержку, что используете программу, использующую Windows Filtering Platform через WinDivert.

**Comment by Kommunist7304** [comment]
Просто это единственная версия KES официально совместимая с Windows 10 Buid 1803. Предыдущие версие работают либо в искалеченном режиме, либо вообще не дают загрузиться системе.

**Comment by madmaximka** [comment]
@Kommunist7304 по мне так корпоративный дрвеб значительно лучше чем каспер с его педалями.

**Comment by Kommunist7304** [comment]
Данная тема не предназначена для обсуждения предпочтений. Кому-то и без антивиря хорошо живется.

**Comment by ValdikSS** [comment]
@Kommunist7304, вам что-нибудь ответили в технической поддержке?

**Comment by ValdikSS** [comment]
Приложите minidump и информацию о BSOD, которую вы видите на экране при падении. Там должно быть написано, какой драйвер по какому адресу вызвал ошибку.

**Comment by Kommunist7304** [comment]
Я обновился до бета-версии или может так звёзды совпали, но падения прекратились.

**Comment by ValdikSS** [comment]
Закрываю issue. Откройте, если проблема будет повторяться.
