### ISSUE TITLE
excuse me, please, I have a question  windows defender

### ISSUE THREAD

**Issue by matador163** [ValdikSS/GoodbyeDPI#722]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 11

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

excuse me, please, I have a question, can you tell me if this is a false positive or not is it a virus? I read about windivert, but it's something else, I didn't find where else to ask a question, so I turned here PS sorry
![Снимок экрана 2024-10-25 200207](https://github.com/user-attachments/assets/39c5d3c8-dd1a-453c-948e-ec6744b1b788)

### Additional information / Дополнительная информация

sorry for writing here, I haven't found where else I can ask you a question

**Comment by generxl** [comment]
this just happend to me also, probly a false positive but it would be nice to know

**Comment by Goebbelens** [comment]
Same problem, Win Defender found this only on October 25th. And, strangely, Defender sees zip-file as a problem/virus, but not the unpacked folder.

**Comment by generxl** [comment]
you should change issue title to "windows defender found a virus in goodbyedpi" or something like that so more people click in it

**Comment by EgorWeders** [comment]
Вы скачали с этого репозитория? Или с других ресурсов?

**Comment by EgorWeders** [comment]
Try to check previous version with your defender

**Comment by ValdikSS** [comment]
The archive does not contain anything related to Android. You should report false positives to your antivirus software vendor.
