### ISSUE TITLE
goodbyedpi для игры world of warcraft

### ISSUE THREAD

**Issue by Alex45665** [ValdikSS/GoodbyeDPI#723]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

win 10

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Есть игра world of warcraft вот в ней пинг падает и обрывы играть не возможно, включаю ужасный planet vpn все чисто и нормально работает, значит что то с провайдером блокирует что то, но planet vpn часто обрывается и не стабилен, нужен goodbyedpi для игры wow, есть просто универсальная сборка? я уже все скачал с гитхаба перепробовал все версии, так же в клиенте игры указанены реалмлисты set realmlist logon.gamefreedom.org
set patchlist localhost может их в корень программы прописать что бы работало? помогите как сделать рабочий вариант

**Comment by serpen7** [comment]
Это так не работает, goodbyedpi это не впн, впны работают по другому используя сервера, ваш пинг поэтому и падает что вы попадаете на другой кластерный сервер игры используя впн, либо же обходите сервер с которым у вас проблемы по пингу, к которому вас подключают.

**Comment by serpen7** [comment]
> Понял, просто вот источник некий Юрий Кочетов пишет что повышает пингш с GoodbyeDPI или там скам? https://www.securitylab.ru/blog/personal/SimlpeHacker/353948.php
Это из серии "оптимизаторов интернета, которые заставят ваш интернет летать(возможно в пропасть)" вещей которые не имеют к оговоренному отношения. ТСПУ видит трафик который не нужно фильтровать ибо на него ничего нет по правилам и пропускает его, с гудбайдпи, у вас наоборот ТСПУ может увидеть правила дурения тем более старые и может начать юлить трафик по своим правилам. 
1 конфиг вообще в пачке легаси модов лежит с обновы когда вышли новые конфиги И он не самый быстрый но совместимый раньше был когда то давно
>  LEGACY modesets:
>  -1          -p -r -s -f 2 -k 2 -n -e 2 (most compatible mode)
>  -2          -p -r -s -f 2 -k 2 -n -e 40 (better speed for HTTPS yet still compatible)
>  -3          -p -r -s -e 40 (better speed for HTTP and HTTPS)
>  -4          -p -r -s (best speed)

Странно что статья писалась в 2024 году в июле, если инфа с 1 конфигом вообще из старого прошлого гудбайдпи. 

Не нужно врубать гудбайдпи в общем режиме и на незаблокированные ресурсы, потому что это может поломать много чего незаблоченного и конфликтовать с сервисами тех же игр. На то в нем и блеклисты, чтобы работать только с заблоченными ресурсами и применять правила модификации и фильтрации трафика только к тому, что заблочено т.к. к этому нет доступа все равно. Даже в блеклист ставя незаблоченные ресурсы вы рискуете, что ТСПУ может опознать правило дурения или какой то из его методов и начать применять свои правила к этому трафику пытаясь задержать его.

**Comment by Alex45665** [comment]
> Поэтому ВПН и решает эту проблему если она есть, т.к. там другой маршрут к серверу, другие узлы и из другой точки. К примеру ВПНы были актуальны еще в бородатых годах потому что пинг через них был не 120-160, а 70-90(максимум 100), на даже амер сервера игр. Я так в терру играл в свое время до ру сервера. С пингом 120-160 проблематично играть и выкидывает, а 70-90 уже играбельно и нормально было.

Такое дело. Все три года у меня и у тысяч моих согильдейцев был хороший пинг, на евро сервере. И вот именно в тот день, как дискорд блокнули, ну еще с блокировки Ютуба начиналось, начались проблемы в World of Warcraft. оно может час хорошо работать, потом прихватывает, иногда постоянно пингует, иногда отпускает. И так у всех у нас, особенно у кого Ростелеком, да и у остальных так же. Это может они трафик теперь проверяют, или фильтры поставили, Это попытка как то ограничить трафик, попытка контролировать все? Или они неуклюже все делают и теперь все кто играет в онлайн игры постадают? Включаем Впн и все хорошо. Мне начинает казаться, что они заблокировав Ютуб и дискорд, это как то и игровой трафик затронуло и теперь страдаем.

**Comment by serpen7** [comment]
> > Поэтому ВПН и решает эту проблему если она есть, т.к. там другой маршрут к серверу, другие узлы и из другой точки. К примеру ВПНы были актуальны еще в бородатых годах потому что пинг через них был не 120-160, а 70-90(максимум 100), на даже амер сервера игр. Я так в терру играл в свое время до ру сервера. С пингом 120-160 проблематично играть и выкидывает, а 70-90 уже играбельно и нормально было.
> 
> Такое дело. Все три года у меня и у тысяч моих согильдейцев был хороший пинг, на евро сервере. И вот именно в тот день, как дискорд блокнули, ну еще с блокировки Ютуба начиналось, начались проблемы в World of Warcraft. оно может час хорошо работать, потом прихватывает, иногда постоянно пингует, иногда отпускает. И так у всех у нас, особенно у кого Ростелеком, да и у остальных так же. Это может они трафик теперь проверяют, или фильтры поставили, Это попытка как то ограничить трафик, попытка контролировать все? Или они неуклюже все делают и теперь все кто играет в онлайн игры постадают? Включаем Впн и все хорошо. Мне начинает казаться, что они заблокировав Ютуб и дискорд, это как то и игровой трафик затронуло и теперь страдаем.

это скорее всего связанно с тем что в Евро серверах игр тоже меняются правила и там есть датацентровые сервера которые "не але". У меня опять же как к примеру не пускало в апекс просто недели 2, вообще, только с ВПН, ни с гудбайдпи, ни с чем другим, просто потому что попался какой то датацентр во франкфурте который фигачит трафик. Тут скорее всего такой же принцип. Сжимаются все и закручивают гайки, поэтому это дает такой эффект даже при том что оборудование пропускает трафик. ВОВ насколько знаю не использует никакие сервера дискорда и прочего, он на старой технологии хоть и обновленной, там есть логи и всякое чтобы слежка за поведением работала да. Но не думаю что у них есть какие то притензии к самому трафику. Скорее там химичит тоже датацентр который арендован как кластер чтобы был доступ и у людей с других регионов проблемы из-за арендатора просто из-за рубежа особенно.

**Comment by ValdikSS** [comment]
GoodbyeDPI не может улучшить связность
