### ISSUE TITLE
При запущенном goodbyedpi не работает игра Identity V

### ISSUE THREAD

**Issue by AlSkopy** [ValdikSS/GoodbyeDPI#724]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 10 version 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

При запуске goodbyedpi версии 0.2.3 не загружается игра Identity V. Ютуб работает, как все остальные сайты. проблемы возникают лишь с игрой. Игра работает только если закрыть goodbyedpi через диспетчер задач. При этом с включенным goodbyedpi версии 0.2.2 игра прекрасно работает

### Additional information / Дополнительная информация

В целом проблема решилась установкой goodbyedpi версии 0.2.2 обратно вместо версии 0.2.3, но я решил написать о возникшей проблеме.

**Comment by serpen7** [comment]
Вы запускаете какой батник?

**Comment by ValdikSS** [comment]
С какими конкретно параметрами вы запускаете GoodbyeDPI? Приведите полную строку запуска.
Также желательно записать дамп трафика: https://github.com/ValdikSS/GoodbyeDPI/wiki/Как-сделать-дамп-трафика-в-Wireshark

**Comment by ValdikSS** [comment]
Может быть, что игра проверяет наличие сервиса `windivert`, а в 0.2.2 он называется `windivert14`.

**Comment by ValdikSS** [comment]
Нет ответа.
