### ISSUE TITLE
Если не работает ютуб. на 26.10.24

### ISSUE THREAD

**Issue by KosmoFromWhiteStar** [ValdikSS/GoodbyeDPI#725]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Добрый день. Я не сетевик. Но всё же данные настройки работают:
```
goodbyedpi.exe -9 -e1 -p --max-payload 12 --fake-resend 1 --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --fake-gen 29 --fake-from-hex 160301FFFF01FFFFFF0303594F5552204144564552544953454D454E542048455245202D202431302F6D6F000000000009000000050003000000 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
```
UPD: Согласен странный скрипт. На одном и том же вайфае работает на одно устройстве и не работает на другом)

**Comment by lp85d** [comment]
Microsoft Windows [Version 10.0.22621.2428]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Windows\System32>cd C:\Users\user\Desktop\goodbyedpi-0.2.3rc3-2\x86_64

C:\Users\user\Desktop\goodbyedpi-0.2.3rc3-2\x86_64>goodbyedpi.exe -9 -e1 -p --max-payload 12 --fake-resend 1 --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --fake-gen 20 --fake-from-hex 160301FFFF01FFFFFF0303594F5552204144564552544953454D454E542048455245202D202431302F6D6F000000000009000000050003000000 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt
GoodbyeDPI v0.2.3rc3: Passive DPI blocker and Active DPI circumvention utility
https://github.com/ValdikSS/GoodbyeDPI

WARNING: fake-resend is 1, no resending is in place!
Loaded 154025 hosts from file ..\russia-blacklist.txt
Loaded 14 hosts from file ..\russia-youtube.txt
Block passive: 1
Block QUIC/HTTP3: 1
Fragment HTTP: 2
Fragment persistent HTTP: 2
Fragment HTTPS: 1
Fragment by SNI: 0
Native fragmentation (splitting): 1
Fragments sending in reverse: 1
hoSt: 0
Host no space: 0
Additional space: 0
Mix Host: 0
HTTP AllPorts: 0
HTTP Persistent Nowait: 1
DNS redirect: 1
DNSv6 redirect: 1
Allow missing SNI: 0
Fake requests, TTL: fixed (fixed: 0, auto: 0-0-0, min distance: 0)
Fake requests, wrong checksum: 1
Fake requests, wrong SEQ/ACK: 1
Fake requests, custom payloads: 21
Fake requests, resend: 1
Max payload size: 12

Opening filter
Filter activated, GoodbyeDPI is now running!

**Comment by KosmoFromWhiteStar** [comment]
> Microsoft Windows [Version 10.0.22621.2428] (c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
> 
> C:\Windows\System32>cd C:\Users\user\Desktop\goodbyedpi-0.2.3rc3-2\x86_64
> 
> C:\Users\user\Desktop\goodbyedpi-0.2.3rc3-2\x86_64>goodbyedpi.exe -9 -e1 -p --max-payload 12 --fake-resend 1 --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253 --fake-gen 20 --fake-from-hex 160301FFFF01FFFFFF0303594F5552204144564552544953454D454E542048455245202D202431302F6D6F000000000009000000050003000000 --blacklist ..\russia-blacklist.txt --blacklist ..\russia-youtube.txt GoodbyeDPI v0.2.3rc3: Passive DPI blocker and Active DPI circumvention utility https://github.com/ValdikSS/GoodbyeDPI
> 
> WARNING: fake-resend is 1, no resending is in place! Loaded 154025 hosts from file ..\russia-blacklist.txt Loaded 14 hosts from file ..\russia-youtube.txt Block passive: 1 Block QUIC/HTTP3: 1 Fragment HTTP: 2 Fragment persistent HTTP: 2 Fragment HTTPS: 1 Fragment by SNI: 0 Native fragmentation (splitting): 1 Fragments sending in reverse: 1 hoSt: 0 Host no space: 0 Additional space: 0 Mix Host: 0 HTTP AllPorts: 0 HTTP Persistent Nowait: 1 DNS redirect: 1 DNSv6 redirect: 1 Allow missing SNI: 0 Fake requests, TTL: fixed (fixed: 0, auto: 0-0-0, min distance: 0) Fake requests, wrong checksum: 1 Fake requests, wrong SEQ/ACK: 1 Fake requests, custom payloads: 21 Fake requests, resend: 1 Max payload size: 12
> 
> Opening filter Filter activated, GoodbyeDPI is now running!

Заработало?

**Comment by lp85d** [comment]
Работает
Давно с ПК не заходил
Сегодня купил квартиру и подключил MTS 
Данная настройка работает
Но на ноутбуке аудиокарта сломана
Так что проверил всё работает
Теперь надо искать дрова на блютуз Win11
Буду на колонку выводить звук

**Comment by nclabs** [comment]
MTS. Не работает. (Давно уже и с разными вариантами настроек).

**Comment by KosmoFromWhiteStar** [comment]
> MTS (GPON). Не работает. (Давно уже и с разными вариантами настроек).
Могу предложить для начало, сменить эти переменные, попробовать раз-два. 
```
--max-payload 12 --fake-resend 1 --dns-port 125 --dnsv6-port 1253 --fake-gen 29
```

Если иэто не работает....

**Comment by nclabs** [comment]
При этом надо как-то перенастраивать DNS?

**Comment by KosmoFromWhiteStar** [comment]
> При этом надо как-то перенастраивать DNS?

Не думаю.

**Comment by nclabs** [comment]
Если в свойствах cетевого адаптера поставить "DNS - автоматически", то выдаётся ответ "этот сайт не может обеспечить безопасное соединение. А если поставить DNS=1.1.1.1, то "нет соединения с интернетом." При этом обычные сайты открываются нормально.

**Comment by KosmoFromWhiteStar** [comment]
> Если в свойствах cетевого адаптера поставить "DNS - автоматически", то выдаётся ответ "этот сайт не может обеспечить безопасное соединение". А если поставить DNS=1.1.1.1, то "нет соединения с интернетом." При этом обычные сайты открываются нормально. То есть наверное в скрипте либо порт неправильно указан, либо адрес DNS.

Не понял где?

**Comment by nclabs** [comment]
DNS redirect починился (указан только v4), cтраница грузится, но стрима нет.

**Comment by KosmoFromWhiteStar** [comment]
> DNS redirect починился (указан только v4), cтраница грузится, но стрима нет. Upd: пробовал указать также v6, адреса v6 также пробовал разные, это не влияет: страница грузится, стрима нет.

Попробуй убрать настройки днс.

**Comment by nclabs** [comment]
Это ещё утром проверено, не работает.

**Comment by Vladi4ka-coder** [comment]
Ростелеком, Красноярск, не работает ни один вариант

**Comment by JoyHoggers** [comment]
> Ростелеком, Красноярск, не работает ни один вариант

Тоже самое, крск, только Орион.

**Comment by DimonDit210** [comment]
31.10.24
Вот такая ошибка, как пофиксить кто знает? 
![image](https://github.com/user-attachments/assets/2057ab71-0de2-4924-ae82-39b2d9160ecf)

**Comment by prblm** [comment]
> 31.10.24 Вот такая ошибка, как пофиксить кто знает? ![image](https://private-user-images.githubusercontent.com/177000064/381929249-2057ab71-0de2-4924-ae82-39b2d9160ecf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NzI5MzMsIm5iZiI6MTczMDQ3MjYzMywicGF0aCI6Ii8xNzcwMDAwNjQvMzgxOTI5MjQ5LTIwNTdhYjcxLTBkZTItNDkyNC1hZTgyLTM5YjJkOTE2MGVjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxNDUwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmYzYWI5ZmQ5NmFkMDY3MWMxMDZkMGM2ZWFjNzVlN2IyNmU4NmYwZjA4MDU4M2JhZDJkMTM1M2M4ODRjMDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OwMxVmjIIaBWaDManeZ8_3hLk88W4Z1tkgH4vnOrM1o)

попробуй удалить запуском service_remove.cmd и заново попробуй

**Comment by ElPadreX** [comment]
мне не помогло.
