### ISSUE TITLE
Видео не воспроизводится

### ISSUE THREAD

**Issue by DartMitai** [ValdikSS/GoodbyeDPI#727]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 11 Версия 23H2 сборка ОС 22631.4317

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Главная страница ютуба открывается вижу списки видео но при нажатии видео воспроизводиться так и не начинает просто бесконечно крутит при этом если навести мышкой на строку воспроизведения то появляются картинки

**Comment by ull123** [comment]
В данном по зашит майнер, пользуйтесь но знайте чем вы за это платите) бесплатно только в мышеловке и да на него агрятся системы защиты от читов в играх

**Comment by Studyoz** [comment]
> на него агрятся системы защиты от читов в играх

Ну всё правильно. Майнер же крутит валюту. Значит чит.

**Comment by RoyMatus** [comment]
Если запустить \x86_64\goodbyedpi.exe и не закрывать окно консоли которе открывается после запуска то видео будет работать.
Иконка программы остаётся на панели инструментов и окно консоли открыто.

**Comment by EgorWeders** [comment]
> > на него агрятся системы защиты от читов в играх
> 
> Ну всё правильно. Майнер же крутит валюту. Значит чит.



> В данном по зашит майнер, пользуйтесь но знайте чем вы за это платите) бесплатно только в мышеловке и да на него агрятся системы защиты от читов в играх

@Studyoz @ull123 

Прежде чем вводить людей в заблуждение изучите файлы или прикрепите основание для таких заявлений (адрес кошелька для поддержки WinDivert не является основанием)

**Comment by EgorWeders** [comment]
> да на него агрятся системы защиты от читов в играх

Это программа модифицирует пакеты , так что да, античитам не нравится такое

Из очень сложно находимого и читаемого issue https://github.com/ValdikSS/GoodbyeDPI/issues/378
> ❔ Почему не запускается Call Of Duty и некоторые другие игры?
> 
> Античитам не нравится драйвер WinDivert, см https://github.com/ValdikSS/GoodbyeDPI/issues/148, https://github.com/ValdikSS/GoodbyeDPI/issues/172.
> Обращайтесь в поддержку игры.
>

**Comment by DartMitai** [comment]
> Если запустить \x86_64\goodbyedpi.exe и не закрывать окно консоли которе открывается после запуска то видео будет работать. Иконка программы остаётся на панели инструментов и окно консоли открыто.
> 
> Видимо по какой то причине программа перестала нормально работать как сервис windows.

Пробовал запускать от админа но результат точно такой же 
![image](https://github.com/user-attachments/assets/dbaec87d-d5a5-4464-8080-83879752a9ad)

**Comment by louise9483** [comment]
друзья это форум, где нужно говорить о багах программы, а не о том, что у вас параметры перестали работать для обхода блокировки
есть куча альтернатив, например расширения: юбуст, fast proxy

**Comment by serpen7** [comment]
> В данном по зашит майнер, пользуйтесь но знайте чем вы за это платите) бесплатно только в мышеловке и да на него агрятся системы защиты от читов в играх

А можно побольше таких майнеров которые не потребляют ресурсы системы?
![image](https://github.com/user-attachments/assets/cba548da-7773-489e-b03b-73cb151561c8)

**Comment by ElPadreX** [comment]
Да абсолютно такая же проблема, открывается ytb, а видео не загружается. Я поковырялся с параметрами и рекомендации, в том числе и тут, результата особого не возымело. Один раз видео загрузилось, но через пять раз перезагрузки страницы. Забил и просто поробовал "запрет" и там всё превосходно , не игрался даже с настройками. Забил на goodbyedpi, тем более на похожую тему мне ответа не дали, а просто удалили мой issue.
