### ISSUE TITLE
При запуске закрывается. вместе с goodbyedpi также

### ISSUE THREAD

**Issue by ereshenkodashka1** [ValdikSS/GoodbyeDPI#728]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

WINDOWS 10 

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

При запуске закрывается. вместе с goodbyedpi также

**Comment by ereshenkodashka1** [comment]
solved.

**Comment by MahBoiDeveloper** [comment]
> solved.

How?
