### ISSUE TITLE
GoodbyeDPI не даёт возможность обновлять антивирусные базы KIS-ов

### ISSUE THREAD

**Issue by SUGHuser** [ValdikSS/GoodbyeDPI#729]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 7 x64

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Если я пытаюсь обновить антивирусную базу Kaspersky Internet Security (год выпуска не важен) , то до тех пор пока используются ключи такие как --reverse-frag или --wrong-chksum или --frag-by-sni никакие обновления не приходят вообще , если убираю эти ключи и оставляю настроенными значения -f и -e  , а так же -q то базы Kaspersky Internet Security обновляются , но заблокированные по методу замедления сайты не работают. В данном варианте GoodbyeDPI  открывает всё в самом буквальном смысле как для пользователя , так и для людей которые этому пользователю хотят навредить. Я вижу как выход из положения , всё таки добавить не только --blacklist , но и ключ --ignorelist и в этот ignorelist прописывать те адреса и IP адреса которые GoodbyeDPI должен пропускать насквозь без фрагментации и модификации.
То есть... как выход из такого положения , я предлагаю сделать настройку которая будет работать как --blacklist , но с противоположным эффектом... --blacklist устроен так что трафик идёт без фрагментации совсем, кроме списка который занесён в файл , а --ignorelist по-моей идее должен работать иначе , фрагментируется всё , кроме того что занесено в файл )

### Additional information / Дополнительная информация

Особенно от флагов --reverse-frag / --native-frag --frag-by-sni / --wrong-chksum страдают прежние версии антивирусных решений , например у Лаборатории Касперского KIS 2017 17.0.0.611 вообще не может скачать ничего до тех пор пока не закрою службу. А закрыв службу не могу попасть на многие сайты , когда вспоминаю почему и запускаю GoodbyeDPI - снова оказываюсь в положении когда антивирусные решения прошлых лет не способны обновляться с его присутствием. Так же этому подвержены всякие сервисы оплаты комунальных услуг , всякие государственные сервисы... например если я пытаюсь зайти на сайт оплаты комунальных услуг и подать данные о расходе электричества , воды и отопления - я не могу это сделать , у меня это прсото не получается до тех пор , пока я не закрою GoodbyeDPI  , а закрыв его вспоминаю что надо включить только когда хочу кое какие ресурсы посмотреть.
Я не исключаю вероятность что такое только вмоём регионе.

_No response_

Причины по которым я предпочетаю KIS 2017 состоят в том , что он менее ядовито реагирует на мои программки написанные и скомпилированные в VBSEdiit-е 7.1.1.10 , новые же версии в каждом exe файле видят то трояна , то вирус , то не вирус и что-то просто не жилательное и приходится почти каждую программку добавлять в исключения. Лично мне это не удобно.

**Comment by SUGHuser** [comment]
Теперь и в 2021-ом KIS-е базы не обновляются
![Screenshot_3436](https://github.com/user-attachments/assets/6ce618c4-8734-4c58-bb0a-0ce50d532362)
![Screenshot_3437](https://github.com/user-attachments/assets/364c6a81-3fba-47e6-91c6-7be927a953b9)
![Screenshot_3438](https://github.com/user-attachments/assets/2a288d9f-a58c-4c82-aae7-7a3784345591)
когда добавите ключ --ignorelist для того чтоб можно было добавить в список игнорируемых адресов то что надо ?

**Comment by EgorWeders** [comment]
https://github.com/ValdikSS/GoodbyeDPI/issues/374
https://github.com/ValdikSS/GoodbyeDPI/issues/271
https://github.com/ValdikSS/GoodbyeDPI/issues/96

**Comment by SUGHuser** [comment]
Ну ? Столько просим добавить ключ для игнорирования КОНКРЕТНЫХ , не всех адресов которые проблемные в плане использования GoodByeDPI , но в итоге пока ничего не делается.

**Comment by EgorWeders** [comment]
Автор указал, что добавил их в категорию будущих ВОЗМОЖНЫХ улучшений. А там как руки дойдут.

**Comment by SUGHuser** [comment]
Я думаю из-за происходящего с антивирусными базами , это надо делать не как руки дойдут ,  а в срочном порядке... потому что в России сами знаете что процветает... и если получится так что из-за желания смотрения известно чего с запущенным GoodbyeDPI люди нацепляют вирусов , то это сильно испортит репутацию программе и автору.

**Comment by EgorWeders** [comment]
У вас есть возможность внести свой вклад в улучшение программы. Мне нужны были коды выхода программы, я добавил для себя, и потом это внесли в основную базу.

**Comment by EgorWeders** [comment]
И если вы используете win 7 в 2024 , то вам любой антивирус не поможет закрыть все бреши.

**Comment by SUGHuser** [comment]
Так я и жду ) , надеюсь это будет добавлено в близжайшее время , так как когда стали появляться проблемы с анивирусными базами , это уже перебор как по-моему ) , хотя я понимаю что виноват в этом ничуть не автор , а кое кто другой )

**Comment by EgorWeders** [comment]
Проверьте схожие проекты из readme, возможно там будет нужный функционал.

**Comment by EgorWeders** [comment]
Вроде код посмотрел, на выходных постараюсь допилить, должно легко встать.

**Comment by ValdikSS** [comment]
Используйте `--blacklist`. Пожелания о добавлении `--whitelist` уже есть (см. https://github.com/ValdikSS/GoodbyeDPI/issues/729#issuecomment-2456196821).

**Comment by SUGHuser** [comment]
@ ValdikSS 
Осталось только одно , чтоб ты хотя бы бетку таую выложил )

**Comment by SUGHuser** [comment]
@EgorWeders  или @ValdikSS 
Очень сильно жду --whitelist или --ignorelist
