### ISSUE TITLE
SOCKS Proxy on 443 port

### ISSUE THREAD

**Issue by DillianSky** [ValdikSS/GoodbyeDPI#73]
При запущенном GoodbyeDPI со стандартными настройками невозможно использовать SOCKS-прокси через 443 порт. Как это можно победить?

**Comment by DillianSky** [comment]
У меня блокировка обходятся полностью стабильно только с `-1`, что и есть стандартные настройки (в т. ч. и HTTPS-сайты, конечно же). В других режимах наблюдаются различные проблемы. А прокси работает с ключами `-4`, `-3` и `-2`. Кстати, сайт Граней вообще ни в каком режиме работает, что странно, как по мне.

**Comment by DillianSky** [comment]
Кстати, сайты Telegram тоже не открываются у меня. К теме не относится, но такое ощущение, что некоторые ресурсы какими-то другими методами блокируются.

**Comment by ValdikSS** [comment]
В РФ провайдеры блокируют сайты, внесенные по домену или по URL на DPI или DNS-серверах, а диапазоны IP-адресов блокируются средствами маршрутизации (blackhole). В последнем случае GoodbyeDPI бессилен, но может помочь [ReQrypt](https://reqrypt.org/reqrypt.html), это такой односторонний прокси-сервер, который проксирует трафик только от клиента к сайту, но не наоборот.

**Comment by DillianSky** [comment]
Хорошо. Но как решить проблему с прокси?

**Comment by ValdikSS** [comment]
Снимите дамп через wireshark, здесь написано, как это сделать: https://github.com/ValdikSS/GoodbyeDPI/issues/59#issuecomment-366519333
В host вводите IP-адрес своего прокси. После сохранения дампа, пришлите его на iam@valdikss.org.ru

**Comment by DillianSky** [comment]
Хорошо, я отправил дампы на почту.

**Comment by ValdikSS** [comment]
Проблема в прокси-сервере. Похоже, код написан без учета возможности фрагментации пакетов. Каким ПО для прокси-сервера вы пользуетесь?
Попробуйте запустить goodbyedpi с параметром `-e 4`

**Comment by DillianSky** [comment]
Прокси не мой, по этой части не могу сказать.
С таким ключом ни один заблокированный сайт не открывается.

**Comment by ValdikSS** [comment]
А прокси с ключом `-e 4` начинает работать?

**Comment by DillianSky** [comment]
Да. И прокси, и HTTPS-сайты.

**Comment by ValdikSS** [comment]
Значит, проблема с ПО прокси-сервера.

**Comment by moraks** [comment]
Оптика Ростелеком. ReQrypt не помогает против блокировок по IP тоже, все настройки перебрал. Google, который по IP заблокирован не открывается ни через  GoodbyeDPI, ни через ReQrypt, операторской заглушки даже нет . 
Всякие торренты пока по прежнему нормально открываются с GoodbyeDPI.

**Comment by ValdikSS** [comment]
@hooddy, GoodbyeDPI обходит блокировки систем Deep Packet Inspection, а не блокировки по IP-адресам и диапазонам. Не поможет для разблокировки Telegram.

**Comment by hooddy** [comment]
Google.com не открывается, он по адресам вроде лочится.

**Comment by ValdikSS** [comment]
Закрываю issue, ошибка не в GoodbyeDPI.
