### ISSUE TITLE
Error about KB3033929 however i have KB3033929 installed

### ISSUE THREAD

**Issue by Telejaba** [ValdikSS/GoodbyeDPI#730]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 7

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

basically it doesnt let me use Goodbye DPI with giving an error

> Opening filter
> Error opening filter: 577 Windows cannot verify the digital signature for this f
> ile. A recent hardware or software change might have installed a file that is si
> gned incorrectly or damaged, or that might be malicious software from an unknown
>  source.
> 
> Could not load driver due to invalid digital signature.
> Windows Server 2016 systems must have secure boot disabled to be
> able to load WinDivert driver.
> Windows 7 systems must be up-to-date or at least have KB3033929 installed.
> https://www.microsoft.com/en-us/download/details.aspx?id=46078
> 
> WARNING! If you see this error on Windows 7, it means your system is horribly ou
> tdated and SHOULD NOT BE USED TO ACCESS THE INTERNET!
> Most probably, you don't have security patches installed and anyone in you LAN o
> r public Wi-Fi network can get full access to your computer (MS17-010 and others
> ).
> You should install updates IMMEDIATELY.

however i have update installed

### Additional information / Дополнительная информация

Sevice install doesnt work as well
Programm called ZAPRET doesnt work either, maybe it somehow related
I have anitivirus turned off

**Comment by 128th** [comment]
Same problem. GDPI and Zapret stopped working about 1.5 weeks ago for me.

**Comment by Belka24** [comment]
Had same problem, found solution in downloading older WinDivert-2.2.0-c version and replacing files WinDiwert.dll and WinDivert64.sys in GDPI (x86_64, x84) and Zapret (bin) folders.

**Comment by Telejaba** [comment]
> Had same problem, found solution in downloading older WinDivert-2.2.0-c version and replacing files WinDivert.dll and WinDivert64.sys in GDPI (x86_64, x84) and Zapret (bin) folders.

ill try that, thanks!

**Comment by Telejaba** [comment]
that didnt work

**Comment by Telejaba** [comment]
however it worked for zapret so partially fixed i guess?

**Comment by EgorWeders** [comment]
It gives same output with different windivert version?

**Comment by ValdikSS** [comment]
Ensure that you have all the fresh updates installed in the OS.
The current GoodbyeDPI release and pre-release versions are tested on the fully updated Windows 7 and work without any issues.

**Comment by ValdikSS** [comment]
Also try to delete all the cruft and leftovers of potentially incompatible WinDivert version if you ever tried to use it:

```
sc stop windivert
sc delete windivert
```

in `cmd` as administrator.
