### ISSUE TITLE
Old windivert version causes crashes

### ISSUE THREAD

**Issue by kotenok2000** [ValdikSS/GoodbyeDPI#731]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 11 24h1

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Sometimes Windows crashes with UNEXPECTED_KERNEL_MODE_TRAP.
Version of Windivert GoodbyeDPI v0.2.3rc3 ships is dated to 2019, while one from https://github.com/bol-van/zapret-win-bundle is dated to 2022.
Tech support on Sysnative believe windivert caused crashes.
https://www.sysnative.com/forums/threads/unexpected_kernel_mode_trap.41935/#post-408143

**Comment by EgorWeders** [comment]
You can replace goodbyedpi's dll with zapret's

**Comment by kotenok2000** [comment]
Already did that.

**Comment by ValdikSS** [comment]
Please send the minidump file.

https://www.mercusys.com/en/faq-810

**Comment by ValdikSS** [comment]
@kotenok2000 any updates?

**Comment by kotenok2000** [comment]
Crashes stopped after I upgraded to windows 11 24h2
