### ISSUE TITLE
virustotal: 15/65 security vendors flagged this file as malicious

### ISSUE THREAD

**Issue by andry81** [ValdikSS/GoodbyeDPI#733]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 8.1

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

goodbyedpi-0.2.3rc3-2.zip

https://www.virustotal.com/gui/file/37f96b32d050dadcc930a639eba68e1ccd57ed5c04a5f77dfca908f01905a4c5

pretty many a malware detections

**Comment by serpen7** [comment]
Kaspersky
Not-a-virus:HEUR:RiskTool.Multi.WinDivert.gen

Все остальное эвристики которые пишут что поведение фильтра перехвата и модификации трафика подобно трояну, что логично довольно, но не могут его распознать по сигнатуре, поэтому и пишут generic, agent, suspicious, maliciou, riskware. Вирусы тоже программы, но не все что есть вирусы полезно. Кряки на играх тоже флагает как хактул или троян. Но люди уже сколько лет играют. Все зависит от людей которые их делают и используют. Антивирусы как бы тоже вирусы, потому что они используют те же самые механики вирусов, только на уровне системы глобально сразу и признаны безопасными т.к. делают защиту ПК. Ваше дело верить или нет виндайверту. Всегда можете написать свой сетевой фильтр с драйвером, который будет так же флагать всякая эвристика.

**Comment by SUGHuser** [comment]
Right , so and so it should be , because windivert modifed TCP packages for bypass DPI , simply ignore this and use GoodbyeDPI if you this need ) or if you can no ignore this , not use GoodbyeDPI and be have problems from DPI servies your provider

**Comment by ValdikSS** [comment]
You need to report the issue to antivirus vendors, not here, if you're using one of the products and is affected by it.

**Comment by andry81** [comment]
https://tip.neiki.dev/file/37f96b32d050dadcc930a639eba68e1ccd57ed5c04a5f77dfca908f01905a4c5

**Comment by andry81** [comment]
> It's up to you to believe or not the windivert. You can always write your own network filter with driver, which will also flag all kinds of heuristics because it interferes with your traffic modifying it according to your settings.

@serpen7 The question is not in the false positive detection itself. More interesting why it did notably increased:

goodbyedpi-0.2.3rc2.zip
https://www.virustotal.com/gui/file/f081740ce7d0fef4d8e7988347697b37943c3cb14cfcc0a32d22328752d0fef0
_3/66_ security vendors flagged this file as malicious

**Comment by serpen7** [comment]
> @serpen7 The question is not in the false positive detection itself. More interesting why it did notable increase:

cause it's heuristics and windivert can 

>  capture network packets
> filter/drop network packets
> sniff network packets
> (re)inject network packets
> modify network packets

that is basically auto flagging for it to be "trojan" at the point of it possibilities. Especially if it falls in wrong hands and you will download it from unknown who and unknown where of the internet where it can become real trojan. 

Heuristics are on high alarm for whole package zip of program cause it's packed. You can unpack it and check DLLs, Syss and Exes by yourself on virustotal, there would be much less of detection.

**Comment by andry81** [comment]
> cause it's heuristics and windivert can

But it existed before the report detection increase, what is changed then?

**Comment by serpen7** [comment]
> > cause it's heuristics and windivert can
> 
> But it existed before the report detection increase, what is changed then?

because peope scan it and heuristics are changing score of their detections based on their signatures, behaviour, connection, popularity of malware that is using this or similar container to be hidden with with fake versions of this program, because of MANY things.
