### ISSUE TITLE
Ребят если есть такая возможность разблокируйте  7tv и FFZ 

### ISSUE THREAD

**Issue by SpikerRoa** [ValdikSS/GoodbyeDPI#734]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Ребят если есть такая возможность разблокируйте  7tv и FFZ, это смайлики для твича которые были заблокированы овощами из одной известной организации. Спасибо вам большое за вашу работу!

**Comment by EgorWeders** [comment]
Просто добавьте в свой blacklist или используйте any_country. Или даже с этим не работает?

**Comment by EgorWeders** [comment]
> можешь в лист добавить cloudflare-ech.com

Это вопрос? Или это предложение? И кому именно?
