### ISSUE TITLE
Friends GDPI doesnt work

### ISSUE THREAD

**Issue by JohnnyUltimatum** [ValdikSS/GoodbyeDPI#736]
### CAPTCHA

- [x] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

windows 10 pro

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Service suddenly doesnt load anything media related except for discord, we have tried to fix anything that could be the problem (from my own expirence as well) but nothing worked

### Additional information / Дополнительная информация

something similar happend to me as well but it kinda fixed itself after i used other programs, my friends situation is kinda different, the media didnt load after using other services

**Comment by JohnnyUltimatum** [comment]
no, it isnt just youtube, its also twitter and other web-sites

**Comment by CortexReaver** [comment]
Похожее и у меня, провайдер "Цифровой Диалог".
Не видит даже серверов в игре OpenRA.

**Comment by CortexReaver** [comment]
> no, it isnt just youtube, its also twitter and other web-sites 

Hi, can you please open this page: https://www.openra.net/games/
and say if the list of servers is loading on your side.

**Comment by JohnnyUltimatum** [comment]
![Uploading 2024-11-28_14-12-21.png…]()

**Comment by AlexSoft1911** [comment]
> Похожее и у меня, провайдер "Цифровой Диалог". Не видит даже серверов в игре OpenRA.
> 
> Не работают также Фейсбук (работает с переменным успехом), Дискорд, почта на Протоне и ещё куча всего. [Nitter](https://nitter.poast.org/) иногда выплёвывает "403 | Forbidden", X работает нормально на удивление. С трудом работают клиенты matrix'а: периодически пишут, что не могут подключиться к серверам, ни к matrix.org, ни к каким либо другим. Как обстоит ситуация с Ютубом у меня: сам сайт грузится и работает отлично, включая студию. Но вот видео я никакие смотреть не могу - за исключением своих, что самое интересное. Превью на таймлайне при этом видны всегда. Твитч работает даже без goodbyeDPI и трансляции идут на него без проблем.

Абсолютно ни как не похоже и я бы сказал является оффтопом. Автор налил общей воды, без деталей. Собственно, ваш случай не особо лучше, конечно, в данном контексте.

> Как я решаю проблему в веб-браузере. Есть два дополнения: stealthy и антизапрет. Stealthy не включается, пока я не активирую антизапрет. По-этому, сначала я включаю антизапрет, потом включаю и отключаю stealthy пока оно не загорится зелёным (само дополнение в настройках браузера), дальше отключаю антизапрет. При этом, со stealthy не хочет работать куча сайтов в РФ, включая Озон и русский Алиэкспресс. Приходится всё это отключать и повторять процедуру снова, если захочу посмотреть видео на YT :)

Вы включаете одну прокси, потом включаете другую прокси и выключаете прошлую. Собственно, меняете шило на мыло, с разным местом хостинга. Но это так, с моей колокольни, конечно.
