### ISSUE TITLE
0.2.3rc3 Cant download and unpack

### ISSUE THREAD

**Issue by oncceh** [ValdikSS/GoodbyeDPI#737]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

windows 11 22h2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Chrome says it's a virus and won't let me download, although there were no problems a month ago. Also, the antivirus does not allow unpacking the archive

**Comment by oncceh** [comment]
yep

**Comment by oncceh** [comment]
> well, tame your browser and antivirus software

Yes, that's what I did, I just wanted to understand, is it just me or everyone else who has Chrome acting up like this? And also the antivirus. Although there was no such problem before. And is it possible to fix it without resorting to tricks?

**Comment by EgorWeders** [comment]
I recommend you to download file and check it with other antivirus, its possible false positive result on windivert.
