### ISSUE TITLE
discord RTC connecting no route error

### ISSUE THREAD

**Issue by mlcni** [ValdikSS/GoodbyeDPI#739]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Win10 

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

The discord is updated, the program interface is loaded, but there are no voice messages. Discord gives the following error: 'connecting to RTC... No route'

**Comment by Vugluskr32** [comment]
у меня каким-то образом удалось обойти, но пришлось переустановить виндовс и настройки потерял(

**Comment by idicudarodnoi** [comment]
> Программа не обходит блокировку голосовых каналов в Discord, это не баг

обходило до блокировки Cloudflare
