### ISSUE TITLE
Unable to turn off service.

### ISSUE THREAD

**Issue by CanerC006** [ValdikSS/GoodbyeDPI#741]
### CAPTCHA

- [x] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 10 Pro

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Hello I'm executing 2_any_country_dnsredir script with -5 value. Everything is okay but when i try to turn off the service. Can not turn off service without restarting computer. 
How did i understand that it's not turning off : Before running script : i can play the game, after running cannot.
If i run service remover, still cannot run my game.

**Comment by EgorWeders** [comment]
How do you try to turn service off ?

**Comment by EgorWeders** [comment]
And 2_any_country_dnsredir script  does not install any services AFAIK

**Comment by CanerC006** [comment]
@EgorWeders  Running service as an administrator service remover

**Comment by EgorWeders** [comment]
What is service remover? service_remove.cmd?

**Comment by CanerC006** [comment]
cmd. 
![Ekran Alıntısı](https://github.com/user-attachments/assets/fb9b8ec4-b1cf-435e-a8e0-159066d7f242)

**Comment by EgorWeders** [comment]
try `sc stop windivert` in cmd.exe with admin

**Comment by EgorWeders** [comment]
no, just use it in cmd and try to launch game or test it other way

**Comment by CanerC006** [comment]
Does not worth both way. There is nothing to do. I have to restart my pc every time i turn on dns

**Comment by EgorWeders** [comment]
Is this game uses kernel level anti-cheat system? (Valorant etc)

**Comment by EgorWeders** [comment]
Btw

> And 2_any_country_dnsredir script does not install any services AFAIK

Do you use only this .cmd to start app?

**Comment by CanerC006** [comment]
Game is Silkroad Online. I dont think they have that high level protection system just exe is not starting when i run dns cmd

**Comment by EgorWeders** [comment]
So you don't use any service

**Comment by EgorWeders** [comment]
Summary:
1. You have GoodbyeDpi cmd window in background
2. Even if you close window with GoodbyeDpi , your game does not launch

Am i right?

**Comment by MayanKoyote** [comment]
check if any program is using WinDivert with [WinDivertTool](https://github.com/basil00/WinDivertTool)

**Comment by EgorWeders** [comment]
> Yes

And even if you close the cmd window, your game still won't start?

**Comment by CanerC006** [comment]
Yes

**Comment by EgorWeders** [comment]
Try after reboot

1. Add `pause` at end of 2_any_country_dnsredir file
2. Run 2_any_country_dnsredir file as admin and screenshot output 
3. Close cmd.exe with cmd file's run result
4. Run `sc query goodbyedpi` in cmd.exe and screenshot output

**Comment by EgorWeders** [comment]
Looks like something breaks after goodbyedpi launch. Maybe you use something what screens or controls network connections? Or other specific programs? Try to reproduce problem with other .cmd configurations (without "service" word in filename)

**Comment by CanerC006** [comment]
First of all, Thank you for your attention and consideration. I prefer restart computer instead of giving lot of effort bro. It's temporary process for me.
