### ISSUE TITLE
Youtube serch suggestions

### ISSUE THREAD

**Issue by oncceh** [ValdikSS/GoodbyeDPI#742]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

windows 11 22h2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

YouTube search suggestions often don't work. Tried the following modes:
-6 -e1 -q --blacklist …
-5 -e1 -q --blacklist …
-5 -f 2 -e 2 --auto-ttl --reverse-frag --max-payload
-6 -f 2 -e 2 --wrong-seq --reverse-frag --max-payload
-7 -f 2 -e 2 --wrong-chksum --reverse-frag --max-payload
-8 -f 2 -e 2 --wrong-seq --wrong-chksum --reverse-frag --max-payload
-9 -f 2 -e 2 --wrong-seq --wrong-chksum --reverse-frag --max-payload -q

**Comment by EgorWeders** [comment]
> CAPTCHA

> I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

> YouTube search suggestions often don't work. Tried the following modes:


???

**Comment by oncceh** [comment]
> > CAPTCHA
> 
> > I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».
> 
> > YouTube search suggestions often don't work. Tried the following modes:
> 
> ???

Is it a bug that you can't use YouTube search suggestions with the app? Without the app, this feature works just fine.

**Comment by EgorWeders** [comment]
Exactly, its a broken website/ connection

**Comment by oncceh** [comment]
> Exactly, its a broken website/ connection

"Without the app, this feature works perfectly."  
Am I missing something? When you launch the app, the function often just disappears, but sometimes it works. This does not happen when using any other workaround.

**Comment by EgorWeders** [comment]
YouTube search use requests to fill suggestions and that request can fail, so it is "Broken website", app does not guarantee you to have all website features working

**Comment by EgorWeders** [comment]
❔ My websites have stopped working! 
Use *blacklist* scripts (and the --blacklist option if you run it manually). Do not use 2_any_country! The program can and will disrupt sites if you run it in a mode without domain restrictions. This is an unavoidable feature of the circumvention methods used. The performance of individual sites depends on the site (server) settings, on your router, as well as on the DPI equipment of your provider.

Translated from https://github.com/ValdikSS/GoodbyeDPI/issues/378

**Comment by EgorWeders** [comment]
>This does not happen when using any other workaround(VPNs).

This app is not VPN

**Comment by EgorWeders** [comment]
@oncceh 
Is this issue complete for you?
