### ISSUE TITLE
Is it safe to browse Steam or buy games when it's active?

### ISSUE THREAD

**Issue by Yaerveth** [ValdikSS/GoodbyeDPI#743]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

I apologize for asking this question under a feature request, but the community seems to be completely in Russian which I can't comprehend. 

My question is: Is it safe to use Steam when it's active? Would I get banned if I buy games while using this software? Steam ToS makes it clear that buying games when VPN is active is strictly prohibited, but this software is obviously very different from a VPN. Also if I want to terminate Goodbyedpi after usage, do I have to simply close the window or do I have to run service_remove.cmd every single time?

Thanks in advance!

**Comment by EgorWeders** [comment]
> Also if I want to terminate Goodbyedpi after usage, do I have to simply close the window or do I have to run service_remove.cmd every single time?

 service_remove.cmd  will remove service after service_install.cmd. So, yes , just close Goodbyedpi.

> My question is: Is it safe to use Steam when it's active?

GoodbyeDpi doesn't change you ip, just packets. Main issue with steam that users can buy app with other regional prices. If you use your native region even with vpn, its ok. But for more information you need to ask steam tos.

**Comment by bioluks** [comment]
Just like @EgorWeders said, DPI Bypass does not change your IP and its usage shouldn't break the Steam ToS for this specific matter.
