### ISSUE TITLE
Goodbye DPI for North Caucas

### ISSUE THREAD

**Issue by Klu1d** [ValdikSS/GoodbyeDPI#746]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Не знаю в курсе ли вы последних событий на серверном кавказе, но тут по полной затягивают все возможные связи с внешним миром. Важным для меня инструментом был телеграм. Его на Кавказе отключили, по крайней в Чечне, Ингушетии и Дагестане. У многих он заблокирован.
Многие поэтому пользуются впн или прокси. Но интересно то, что со вчерашнего дня был отключен и такая возможность обхода блокировки. Не работает ни один впн, прокси отвалились. Если посмотрите на последние новости в интернете по этому, то постоянно фигурирует словосочетание "золотой щит как в Китае".

C некоторого момента заработали только отечественные сайты, теперь работают и некоторые внешние, так как github. А телеграм нет. Новостях об этом не говорят, но эта проблема существует давно и останется после.

Пожалуйста, скажите мне, есть ли возможность использовать goodbyedpi для обхода блокировки telegram?

**Comment by araviyski** [comment]
Добрый день, я сам с кавказа, и вчера пережил эту блокировку, действительно не работал ни один VPN, но какие-то варианты всё равно работали, судя из моего опыта и моего круга
1) VPN который шёл через Москву или другой регион
2) VLESS с разным подбором маршрутизации. Пинг поднимался до 500-700, но он работал.

**Comment by theJosephGoodman** [comment]
у меня в Осетии че-то перстал работать GoodbyeDPI. Подскажете варианты что можно сделать?
