### ISSUE TITLE
Зависает дс 

### ISSUE THREAD

**Issue by MaI-rgb** [ValdikSS/GoodbyeDPI#748]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 10 Pro

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Скажу кратко 3 дня назад дс перестал работать от слова совсем 
зависает на сером экране 
Снизу скину фото

### Additional information / Дополнительная информация

![1970bb14aaed3178](https://github.com/user-attachments/assets/f600251e-e8a6-4742-b579-3c5609ddbc6e)

**Comment by ValdikSS** [comment]
Не вижу запущенного GoodbyeDPI. Вы ошиблись.
