### ISSUE TITLE
ограничения на размер файлов?

### ISSUE THREAD

**Issue by Quqas** [ValdikSS/GoodbyeDPI#75]
если скачивать файл с лоченого ресурса, то есть ли разница какого он размера? м.б. в проге есть предел на кол-во отфильтрованных пакетов?

пример: goodbyedpi-0.1.4 запускаю с ключом -p этого хватает для всех случаев. пока не столкнулся с траблой скачать телегу по ссылке https://telegram.org/dl/desktop/win_portable  

начинает качать архив, определяет размер в 24 метра, но всегда раз за разом перестаёт качать после 12метров

в тоже время с полноценным vpn скачивает полностью

win7 64bit браузер chrome

**Comment by ValdikSS** [comment]
У меня не проявляется проблема, файл закачивается полностью.
Возможно, дело в маршрутизации вашего провайдера, а не в программе. В начале закачки пакеты идут через один маршрут, а в процессе закачки маршрут меняется на альтернативный, где уже действует блокировка по IP-адресу.

Если у вас с включенным VPN и GoodbyeDPI файл закачивается нормально, то это не ошибка программы. Протестируйте и напишите результат, пожалуйста.

**Comment by Quqas** [comment]
тут вообще странное

удалил  службу - ребутался и т.д. - и всё равно

> BlockCheck v0.0.9.6
> Для получения корректных результатов используйте DNS-сервер провайдера и отключите средства обхода блокировок.
> 
> Проверка работоспособности IPv6: IPv6 недоступен.
> [O] Тестируем IPv4 DNS
> 	Через системный DNS:	 ['104.20.134.45', '104.20.135.45', '104.24.10.70', '104.24.11.70', '184.173.136.161', '195.8.215.136', '195.82.146.214', '5.178.68.100']
> 	Через Google DNS:	 ['104.20.134.45', '104.20.135.45', '104.24.10.70', '104.24.11.70', '184.173.136.161', '195.8.215.136', '195.82.146.214', '5.178.68.100']
> 	Через Google API:	 ['104.20.134.45', '104.20.135.45', '104.24.10.70', '104.24.11.70', '184.173.136.161', '195.8.215.136', '195.82.146.214', '5.178.68.100']
> 	Несуществующий DNS не вернул адресов (это не ошибка)
> [✓] DNS-записи не подменяются
> [✓] DNS не перенаправляется
> 
> [O] Тестируем HTTP
> 	Открываем  http://a.putinhuylo.com/
> [✓] Сайт открывается
> 	Открываем  http://furry.booru.org/index.php?page=post&s=view&id=111173
> [✓] Сайт открывается
> 	Открываем  http://rutracker.org/forum/index.php
> [✓] Сайт открывается
> 	Открываем  http://furry.booru.org/
> [✓] Сайт открывается
> 	Открываем  http://pbooru.com/index.php?page=post&s=view&id=303026
> [✓] Сайт открывается
> 	Открываем  http://pbooru.com/
> [✓] Сайт открывается
> 
> [O] Тестируем HTTPS
> 	Открываем  https://www.dailymotion.com/
> [✓] Сайт открывается
> 	Открываем  https://e621.net/
> [✓] Сайт открывается
> 	Открываем  https://lolibooru.moe/
> [✓] Сайт открывается
> 	Открываем  https://rutracker.org/forum/index.php
> [✓] Сайт открывается
> 
> [!] Результат:
> [☺] Ваш провайдер не блокирует сайты.
> 

видать ростелеком сломался от миллионов новых записей
т.е. буквально нелочится и без проги

предположение про кривой маршрут скорее всего верное, но невозможно проверить - pingplotter изначально не может до крайнего хопа достучаться

![image](https://user-images.githubusercontent.com/38732439/39370542-da2cac4e-4a47-11e8-8597-fff449f5385e.png)

видать сам сайт отрубает icmp. с вашего прова пингуется?

а файл всё равно не скачать.

качает целиком только череp vpn (SecurityKISS Tunnel)

**Comment by ValdikSS** [comment]
Я вчера тестировал на Ростелекоме, без GoodbyeDPI сайт telegram.org не открывается вообще, без каких-либо ошибок (бесконечная загрузка), а с GoodbyeDPI открывается, и скачивается файл, но медленно. Такое чувство, что пакеты теряются, вероятно, из-за разных маршрутов. Но файл скачался полностью, проблем не было.

**Comment by Quqas** [comment]
кстати по поводу задержки согласен - сначала тупит но открывает t.me  и без проги

а пинг? идёт ? у меня и с vpn нет ответа.

а с файлом такое впечатление что маршрут меняется только раз - и не возвращается

**Comment by ValdikSS** [comment]
На t.me отключен ICMP Echo.

**Comment by Quqas** [comment]
как писал выше, да скачивается, но только менеджером загрузки, который приходится закрывать\открывать чтоб заново коннект установился. (т.е. в нём тоже до нуля успевает упасть скорость) 

иначе никак. 

тот же хром не умеет после закрытия продолжить загрузку. а пауза\возобновить не помогают

**Comment by ValdikSS** [comment]
Вероятно, это не проблема GoodbyeDPI. Закрываю сообщение.
