### ISSUE TITLE
Videos on YouTube are uploaded only up to 59 seconds / Видео на ютубе загружаются только до 59-ти секунд 

### ISSUE THREAD

**Issue by HamsterKokesh** [ValdikSS/GoodbyeDPI#750]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 10 PRO 22H2     v.19045.5131

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

прощай дпи загружает видео на ютубе только до 59 секунд. Пробовал на Яндекс браузере и фаерфокс. Пробовал выходить из аккаунта Гугл , а также запускать ютуб во вкладках инкогнито. Ничего не помогало. 

Goodbye DPI uploads videos on YouTube only up to 59 seconds. I tried it on Yandex browser and firefox. I tried logging out of my Google account, as well as launching YouTube in incognito tabs. Nothing helped.
![Безымян45н5й](https://github.com/user-attachments/assets/b01a3ca6-01b0-4aa6-b0da-23d178532be5)
![Безымянн5й](https://github.com/user-attachments/assets/b7721505-dc0e-4404-bba5-ce438e159ca1)
![Безымянный](https://github.com/user-attachments/assets/75d15e41-77a0-412f-b980-21d296c658a1)

### Additional information / Дополнительная информация

Начало это происходить после отключения некоторых районов России от зарубежного интернета. Хоть и ДНР не был в списке этих стран , но проблемы  ютубом появились именно во время отключения россии от интернета. Возможно это просто совпадение. Также , если ютуб включить с ВПН , а затем закрыть ВПН и запустить Goodbye dpi , то он (GBD) сможет дальше самостоятельно загружать видео. И да , я пробовал все рабочие коды для  "Russia blacklist" и "Russia blacklist youtube". Кстати , браузерное расширение Ютуб-буст никогда не работало. 

This began to happen after disconnecting some areas of Russia from the foreign Internet. Although the DPR was not on the list of these countries, YouTube's problems appeared precisely during Russia's disconnection from the Internet. Maybe it's just a coincidence. Also, if you turn on YouTube with VPN , and then close VPN and run Goodbye dpi, then it (GBD) will be able to continue uploading videos on its own. And yes, I tried all the working codes for "Russia blacklist" and "Russia blacklist youtube". By the way, the YouTube boost browser extension has never worked.

**Comment by NoriNgtoN666** [comment]
Это странно... Столкнулся ровно с такой же проблемой, пользуюсь точно такими же методами обхода, тем же браузером. Но у меня проблема исчезает если выйти из аккаунта или войти в инкогнито. Попробуй открыть видео в другом, чистом браузере без захода в аккаунт. Если проблема сохраниться, тогда все мои изучения этой проблемы насмарку. Пока что всё говорит о том, что эта проблема как-то связана напрямую с аккаунтами гугл.

**Comment by HamsterKokesh** [comment]
> Это странно... Столкнулся ровно с такой же проблемой, пользуюсь точно такими же методами обхода, тем же браузером. Но у меня проблема исчезает если выйти из аккаунта или войти в инкогнито. Попробуй открыть видео в другом, чистом браузере без захода в аккаунт. Если проблема сохраниться, тогда все мои изучения этой проблемы насмарку. Пока что всё говорит о том, что эта проблема как-то связана напрямую с аккаунтами гугл. 

- Пробовал в фуррефоксе , не помогло. И инкогнито тоже не помогало. Я слышал об этом варианте проблемы , но у меня скорее всего другой случай

**Comment by ultimatum97** [comment]
> > Это странно... Столкнулся ровно с такой же проблемой, пользуюсь точно такими же методами обхода, тем же браузером. Но у меня проблема исчезает если выйти из аккаунта или войти в инкогнито. Попробуй открыть видео в другом, чистом браузере без захода в аккаунт. Если проблема сохраниться, тогда все мои изучения этой проблемы насмарку. Пока что всё говорит о том, что эта проблема как-то связана напрямую с аккаунтами гугл.
> 
> * Пробовал в фуррефоксе , не помогло. И инкогнито тоже не помогало. Я слышал об этом варианте проблемы , но у меня скорее всего другой случай

мне тоже не помогает выход из акка или игкогнито

**Comment by AutismGaming228** [comment]
не блокируйте в адблоке или добавтье в лист доменов jnn-pa.googleapis.com

**Comment by HamsterKokesh** [comment]
> не блокируйте в адблоке или добавьте в лист доменов jnn-pa.googleapis.com

Адблок не использую

**Comment by NoriNgtoN666** [comment]
> > Это странно... Столкнулся ровно с такой же проблемой, пользуюсь точно такими же методами обхода, тем же браузером. Но у меня проблема исчезает если выйти из аккаунта или войти в инкогнито. Попробуй открыть видео в другом, чистом браузере без захода в аккаунт. Если проблема сохраниться, тогда все мои изучения этой проблемы насмарку. Пока что всё говорит о том, что эта проблема как-то связана напрямую с аккаунтами гугл.
> 
> * Пробовал в фуррефоксе , не помогло. И инкогнито тоже не помогало. Я слышал об этом варианте проблемы , но у меня скорее всего другой случай

Карма меня настигла. Сегодня проснулся и увидел, что такая же проблема появилась и без захода в аккаунт. Теперь не помогает ничего, ни ВПН, ни инкогнито, ни другие браузеры. Молю тебя, если вдруг у тебя появиться хоть какое-то решение даже с помощью костылей, чтобы включить ролик на ютубе, то не забывай об этом посте. Отпиши сюда решение.

**Comment by TheMenos** [comment]
Такая же проблема сегодня утром появилась, пробовал и разные браузеры, чистку кэша, менял kyber и quic протоколы, перескачивал обходы, выходил из аккаунта - ничего не помогло. И это только на пк такая проблема, на телефоне всё нормально

**Comment by NoriNgtoN666** [comment]
UPD. Перепробовал всё что можно, но нашёл решение на Ответах_Mailru, лол. Скачал TroyWell VPN и поставил регион Греции. Не понимаю как, но видео стали грузить без проблем даже если зайти в аккаунт Ютуб. До этого пробовал ВПН, но ничего не помогало.

**Comment by HamsterKokesh** [comment]
> UPD. Перепробовал всё что можно, но нашёл решение на Ответах_Mailru, лол. Скачал TroyWell VPN и поставил регион Греции. Не понимаю как, но видео стали грузить без проблем даже если зайти в аккаунт Ютуб. До этого пробовал ВПН, но ничего не помогало. 
> Оказалось, что дело не в каком-то блокировщике рекламы или в чем-то подобном. А именно в доступе к конкретным серверам ютуб. 
> 

Не хочу использовать впн , они ломаются по 3 раза в неделю , так еще и реклама н ютубе появляется

**Comment by TheMenos** [comment]
> UPD. Перепробовал всё что можно, но нашёл решение на Ответах_Mailru, лол. Скачал TroyWell VPN и поставил регион Греции. Не понимаю как, но видео стали грузить без проблем даже если зайти в аккаунт Ютуб. До этого пробовал ВПН, но ничего не помогало. Оказалось, что дело не в каком-то блокировщике рекламы или в чем-то подобном. А именно в доступе к конкретным серверам ютуб.

Тоже самое. Сейчас на этом же впн сижу, только вместо Греции, Молдова стоит

**Comment by NoriNgtoN666** [comment]
> > UPD. Перепробовал всё что можно, но нашёл решение на Ответах_Mailru, лол. Скачал TroyWell VPN и поставил регион Греции. Не понимаю как, но видео стали грузить без проблем даже если зайти в аккаунт Ютуб. До этого пробовал ВПН, но ничего не помогало.
> > Оказалось, что дело не в каком-то блокировщике рекламы или в чем-то подобном. А именно в доступе к конкретным серверам ютуб.
> 
> Не хочу использовать впн , они ломаются по 3 раза в неделю , так еще и реклама на ютубе появляется

Понимаю тебя. Но моя зависимость от Ютуба сильнее моего комфорта, поэтому я пытался хоть как-то запустить ролики.

**Comment by ZN4K** [comment]
добавка в странности: на skidrowreloaded.com встраиваемые ролики геймплеев работают нормально...

**Comment by ChaseAndTront** [comment]
Аналогичная ситуация с загрузкой видео до 0:59 секунд. Сижу в ютюбе через VPN, который проксирует конкретный домен. Если сменить аккаунт или полностью выйти из него, то всё работает без проблем. 

Самое интересное, что если включить VPN на весь ПК, то у меня всё загружается на любых аккаунтах. Даже если я буду использовать VPN на весь ПК + VPN на конкретный домен, то всё будет работать.

**Comment by t5ov** [comment]
в другой теме я уже поделился своим опытом: Началось всё 6 декабря 2024 года. Сменил как обычно, норм. 
С 8 декабря Youtube грузит 59 секунд любого видео. Включение, отключение Goodbyedpi, Zapret, блокировщиков рекламы и любых/всех расширений в браузере, смена браузера firefox/chrome, чистка кэша, изменение dns google/cloudflare, инкогнито, вход/выход из аккаунта и любые другие всевозможные инструкции - ничего не помогает. Только VPN. 
Много времени искал ответы, на редите тоже есть жалобы от жителей других стран. Проблема не массовая, но встречается. Не знаю что делать. С Goodbyedpi или zapret видео грузится быстрее, чем без него, но 1 минуту и всё.
с 13 декабря заметил, что даже минуту не всегда удаётся загрузить, вылезает классическая ошибка "Что-то пошло не так. Обновите страницу или повторите попытку позже. [Подробнее…]"
скорее всего это гугл сделал в каких-то своих интересах.
...
Коммент выше попробовал, и правда, на stopgame.ru встраиваемые ролики работают. Посмотрел трейлер ведьмака в качестве аж 144p, и с большими остановками/подгрузками, но до конца.... удивительно. После просмотра поставил качество 720p и быстро прогрузилось. Но это с Goodbyedpi. Без него тоже норм 720p загрузилось. Однако при переходе в ютуб всё как раньше - только 59сек.

**Comment by Prolbo** [comment]
Подобная проблема с начала декабря или конца ноября. Временами ютуб просто залупался и видео дальше не шло, помогали переподключения, сбросы днсов или выход из аккаунта гугла. Теперь - нет, загружает одну минуту видео и потом встает намертво. 

Единственный найденный костыль -  скопировать ссылку на видео с привязкой по времени и закинуть в новую страницу инкогнито. Можно посмотреть еще минуту. Потом надо повторять. 

И уже не по теме - отвалился или стал крайне нестабильным доступ ко многим сайтам, доступ к которым раньше легко обеспечивался Goodbyedpi.

**Comment by pavlenkoprog** [comment]
Тоже столкнулся с такой проблемой, сначала помогал инкогнито, но потом ни смена аккаунта, ни  впн не помогало. Пока рабочая лазейка смотреть через сторонние сайты с встроенным проигрывателем ютуба. #
Вот пример
https://yandex.ru/video/preview/9764713102349499937

**Comment by TheMenos** [comment]
> Тоже столкнулся с такой проблемой, сначала помогал инкогнито, но потом ни смена аккаунта, ни впн не помогало. Пока рабочая лазейка смотреть через сторонние сайты с встроенным проигрывателем ютуба. # Вот пример https://yandex.ru/video/preview/9764713102349499937

Реально работает, но мне проще через впн сидеть. Ещё забавно, у меня на телефоне ютуб без всяких обходов работает

**Comment by DikozImpact** [comment]
Столкнулся с этой проблемой, причём я не использую запрет, а просто впн. Никак не хотело работать в режиме прокси, останавливалось на 59 секунде, пока не включил TUN режим и всё заработало. Всё дело было в UDP Трафике

**Comment by HamsterKokesh** [comment]
> Столкнулся с этой проблемой, причём я не использую запрет или гудюбайdpi, а просто впн. Никак не хотело работать в режиме прокси, останавливалось на 59 секунде, пока не включил TUN режим и всё заработало. Всё дело было в UDP трафике 

Что за TUN режим? В яндекс браузере такое есть?

**Comment by HamsterKokesh** [comment]
Проблема популярная , но пока нет даже догадок о том, как ее можно решить. Остаётся только ждать. Надеюсь ValdikSS выпустит новое обновление с фиксом и утилитой для генерации кодов (набор букв и чисел , который вставляется в "russian blacklist.cmd")

**Comment by Dimon1757** [comment]
Это проблема ютуба, обновите страницу

**Comment by TheMenos** [comment]
> Это проблема ютуба, обновите страницу

Что за бред? Не работает это. Хоть обновляй, не обновляй, всё это мы уже пробовали. Здесь работают только выше перечисленные способы

**Comment by hb220** [comment]
Также столкнулся с проблемой. Грешил на ВПНы и всякое прочее, всё излазил. Но вдруг оказалось, что под другим аккаунтом всё работает. Прошла неделя - вчера работало, а сегодня уже и другой аккаунт так же загнулся... Обычно у меня в браузере заворачиваются нужные домены в ВПН, не всё подряд. Но в процессе отладки пробовал уже и Wireguard до своего VPS, целиком весь трафик. До не своего, другого ВПН. Amnezia на не свой ВПН. Amnezia на свой VPS. Разные компьютеры, разные браузеры. До лампочки! Всё равно та же проблема. С телефона (пока?) работает без проблем.
Режим без входа в аккаунт и инкогнито мне тоже никак не помогли.

Сейчас вот скачал расширение для браузера в магазине Chrome, "Enhancer for YouTube™", https://chromewebstore.google.com/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle

В нём есть функция "Mini-player", открывает отдельное мелкое окно, но его можно расширить. Внезапно, в нём почему-то нормально играет. Может кому поможет с этой дрянью, когда с одной стороны РКН, а с другой - сам YouTube палки в колесо суёт.

**Comment by TheMenos** [comment]
> Также столкнулся с проблемой. Грешил на ВПНы и всякое прочее, всё излазил. Но вдруг оказалось, что под другим аккаунтом всё работает. Прошла неделя - вчера работало, а сегодня уже и другой аккаунт так же загнулся... Обычно у меня в браузере заворачиваются нужные домены в ВПН, не всё подряд. Но в процессе отладки пробовал уже и Wireguard до своего VPS, целиком весь трафик. До не своего, другого ВПН. Amnezia на не свой ВПН. Amnezia на свой VPS. Разные компьютеры, разные браузеры. До лампочки! Всё равно та же проблема. С телефона (пока?) работает без проблем. Режим без входа в аккаунт и инкогнито мне тоже никак не помогли.
> 
> Сейчас вот скачал расширение для браузера в магазине Chrome, "Enhancer for YouTube™", https://chromewebstore.google.com/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle
> 
> В нём есть функция "Mini-player", открывает отдельное мелкое окно, но его можно расширить. Внезапно, в нём почему-то нормально играет. Может кому поможет с этой дрянью, когда с одной стороны РКН, а с другой - сам YouTube палки в колесо суёт.

Спасибо, бро, реально помогло

**Comment by TheMenos** [comment]
[
![b12](https://github.com/user-attachments/assets/ded589ad-7e43-4875-bc8d-a982dc8eda5d)
![b1](https://github.com/user-attachments/assets/0e6461e2-459b-48a9-9d76-8f10b8fec717)
](url)
Как и написал человек выше (за что огромное ему спасибо), скачиваете расширение Enhancer for YouTube, дальше на видео делаете как на фото, откроется всплывающее окно, и оно уже будет работать без проблем, его также можно расширить до полноэкранного, но минус в том, что нельзя делать плейлист, а каждое видео отдельно так открывать. Но ладно уж, потерпим, не впервой
