### ISSUE TITLE
Error opening filter: -2144206839 (null)

### ISSUE THREAD

**Issue by FowlizM** [ValdikSS/GoodbyeDPI#752]
### CAPTCHA

- [x] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 11 23h2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

![image](https://github.com/user-attachments/assets/9a0d64c4-cf67-4cab-9d50-74f7ce58adcf)
Tried many stuff, none did slight change.
Even did this fix https://github.com/ValdikSS/GoodbyeDPI/issues/400#issuecomment-2262375499
which was given for another null error

### Additional information / Дополнительная информация

Im assuming it happened after the last discord update, right around after december 8th or so, i dont remember exact date.
Possibly because that screwed up network settings but i have no clue on fixing it

**Comment by AKotov-dev** [comment]
Госсподи Исусе Хисте, чтож Вы так читать то то не любите...  
https://drive.google.com/drive/folders/1-YNvW4q6i4qth8skLFUtukIqJU0EYYPg

**Comment by FowlizM** [comment]
Who are you and why do you expect me to use whatever that is. I had no issue with the app before and youre no one, got no reason to trust to you and use your app.

**Comment by AKotov-dev** [comment]
That's right. But if you have to, use it. The license is free. So are you. The code is free, see for yourself.

**Comment by FowlizM** [comment]
Why would i expect that one to work all of a sudden while its just same thing... im not buying the idea

**Comment by AKotov-dev** [comment]
@FowlizM 
Convincing you of something is not my rule. It's just that Valdis now seems to have a lot of problems without you. Many people are already using this code today, while you are looking for definitions. I remember myself in my youth. You are behaving correctly. I have never trusted anyone either. But in this case there are no mistakes.

**Comment by AKotov-dev** [comment]
@FowlizM
No thanks. Good luck to you, mistrustful person. ;) The only request - do not talk about this in public. Thank you.

**Comment by AKotov-dev** [comment]
@FowlizM
If the problem is solved, I recommend closing the topic. ;)

**Comment by FowlizM** [comment]
It is not. Please stop replying to the post

**Comment by AKotov-dev** [comment]
Ок

**Comment by ValdikSS** [comment]
Do you have other WinDivert software in the system?

**Comment by FowlizM** [comment]
None im aware of, could easily be tho, im not into these stuff much

**Comment by FowlizM** [comment]
![image](https://github.com/user-attachments/assets/eea62fca-6ee8-437b-94dc-2c99c1fa29be)
Searched it with everything app and the only ones are these

**Comment by MayanKoyote** [comment]
```
WinDivertTool.exe is a simple program for:
    Listing information about which (if any) programs are using WinDivert.
    Terminating all programs that are using WinDivert.
    Uninstalling WinDivert from your system.
```

https://github.com/basil00/WinDivertTool

**Comment by FowlizM** [comment]
I cant figure out how to run the tool. Theres no .exe file anywhere

**Comment by EgorWeders** [comment]
> I cant figure out how to run the tool. Theres no .exe file anywhere

@FowlizM 

https://github.com/basil00/WinDivertTool/releases/tag/v2.2.0

**Comment by FowlizM** [comment]
![image](https://github.com/user-attachments/assets/02438ea0-88ac-46fa-b16d-eb3a71d67590)
this is the result

**Comment by FowlizM** [comment]
and i still have the exact same null error, no changes

**Comment by ValdikSS** [comment]
Try this:

1. Download https://github.com/basil00/WinDivert/releases/download/v2.2.2/WinDivert-2.2.2-A.zip
2. Unpack
3. Run `x64\passthru.exe true` in an administrator command line

See if it works

**Comment by ValdikSS** [comment]
Does it show any additional details, or only the same error code?
Could you make a screenshot?

**Comment by FowlizM** [comment]
![image](https://github.com/user-attachments/assets/54865257-d452-4220-b1ec-a6b4bdf3b9f3)
Everything is exactly same

**Comment by FowlizM** [comment]
that thing closest instantly after being opened

**Comment by FowlizM** [comment]
![image](https://github.com/user-attachments/assets/c01e3ef7-d4e8-4366-b87a-65889b444e3c)
Managed to capture this by recording the screen

**Comment by FowlizM** [comment]
![image](https://github.com/user-attachments/assets/8c6f040c-6a50-48dd-83f1-101112a6f458)
Another capture

**Comment by FowlizM** [comment]
![image](https://github.com/user-attachments/assets/726c3923-7b88-4f16-925b-04d46086f455)

**Comment by FowlizM** [comment]
![image](https://github.com/user-attachments/assets/e67b6fbb-8982-4276-b4e0-6981d18222d9)

**Comment by Decavoid** [comment]
This command is from a user cmd.exe, not administrator cmd.exe. When administrator cmd.exe is opened the prompt, it shows `C:\Windows\System32>`, not `C:\Users\user>`.

**Comment by FowlizM** [comment]
Ah my bad, did the correct way now
![image](https://github.com/user-attachments/assets/6df3b4b6-50ad-4cf4-953e-aab1c1e3b33e)

**Comment by ValdikSS** [comment]
That's error 0x80320009. If you search the internet about it, it brings many results of "Base Filtering Engine service corrupt".

Do you have some kind of hacked-up Windows? It's probably it.

**Comment by ValdikSS** [comment]
Here's the fix you can try, but it's for Windows 7.
https://www.hageltech.com/blog/2012/02/07/base-filtering-engine-problems.html

**Comment by FowlizM** [comment]
On it

**Comment by FowlizM** [comment]
> That's error 0x80320009. If you search the internet about it, it brings many results of "Base Filtering Engine service corrupt".
> 
> Do you have some kind of hacked-up Windows? It's probably it.

Nope, its fully normal windows, came with the prebuilt pc(HP TG01).

**Comment by FowlizM** [comment]
Did this fix https://www.winhelponline.com/blog/fix-base-filtering-engine-service-startup-problems/
but now im getting "
Opening filter
Error opening filter: 1753 (null)
This error occurs when the Base Filtering Engine service has been disabled.
Enable Base Filtering Engine service.
"
and i get error 1083 when i try to run the BFE

**Comment by FowlizM** [comment]
https://www.winhelponline.com/blog/base-filtering-engine-bfe-error-1083-windows/
![image](https://github.com/user-attachments/assets/f2c2ecf7-82c4-4bc0-b586-518ac833e99e)
i already have BFE written there but its still same error. The BFE was there from the start

**Comment by FowlizM** [comment]
![image](https://github.com/user-attachments/assets/1c2c7c7f-8a5f-471a-ada5-3b17e1955a39)
and now proton is saying this, doing what it says doesnt fix the problem

**Comment by FowlizM** [comment]
Tried this fix https://www.kapilarya.com/fix-error-1083-the-executable-program-that-this-service-is-configured-to-run-in-does-not-implement-the-service
but no change

**Comment by FowlizM** [comment]
Tried https://protonvpn.com/support/how-to-enable-the-base-filtering-engine 
got the link from proton's app but theres no improvement at all, the bfe doesnt run and now im stuck without a vpn

**Comment by FowlizM** [comment]
Tried booting in safe mode and BFE still didnt turn on even when i tried to do it manually

**Comment by FowlizM** [comment]
Also tried sfc /scannow to see if its related to corrupted files but it didnt change anything

**Comment by EgorWeders** [comment]
Do you have some 3rd party antivirus  software installed (Bitdefender etc)? Or its only Windows defender

**Comment by EgorWeders** [comment]
run services.msc and find "Base Filtering engine" and check  status (is it running in services or not)

**Comment by EgorWeders** [comment]
Also check if your firewall is disabled due lack of running BFE instance, if that is true your pc is in danger of basic network hacks. Better to repair or reinstall windows (as i remember all hp laptops and pc have recovery drive)

**Comment by FowlizM** [comment]
> Do you have some 3rd party antivirus software installed (Bitdefender etc)? Or its only Windows defender

Nope, only windows defender

**Comment by FowlizM** [comment]
> Also check if your firewall is disabled due lack of running BFE instance, if that is true your pc is in danger of basic network hacks. Better to repair or reinstall windows (as i remember all hp laptops and pc have recovery drive)

Defender shows it as active but i saw the pop-up telling me to turn it on a few times. Its not showing anymore for the last 2-3 boot ups

**Comment by FowlizM** [comment]
> Run services.msc and find "Base Filtering engine", check status (is it running in services or not)

Its not running, thats where i get the error 1083. When trying to run/start BFE

**Comment by EgorWeders** [comment]
> > Run services.msc and find "Base Filtering engine", check status (is it running in services or not)
> 
> Its not running, thats where i get the error 1083. When trying to run/start BFE

It means your firewall isnt running now, because it depends on BFE

**Comment by EgorWeders** [comment]
In that case best option is just trying to repair windows or just reinstall it. Trying to fix it will lead to huge problems later.

**Comment by FowlizM** [comment]
I have a HDD but i dont know how reinstalling windows is on storage devices, would it delete files on the HDD as well?

**Comment by EgorWeders** [comment]
In my personal experience i had a lot of problems with preinstalled and embedded software on HP (laptop mostly).

**Comment by EgorWeders** [comment]
> I have a HDD but i dont know how reinstalling windows is on storage devices, would it delete files on the HDD as well?

Reinstalling yes, but try to repair windows first

**Comment by FowlizM** [comment]
Alright, could u recommend a guide

**Comment by EgorWeders** [comment]
https://www.techtarget.com/searchenterprisedesktop/tip/How-to-repair-Windows-11-with-an-ISO-file

Or just google it. You need REPAIR, not REINSTALLING.

But best option is clean setup, but it will erase all data on system disk.

But im not responsible for any consequences. I am not tech support

**Comment by FowlizM** [comment]
I'll be moving my files to the HDD and gonna do a local reinstall after i unplug the hdd, just to make sure

**Comment by EgorWeders** [comment]
> Everything is done and the app is running good
> ![image](https://github.com/user-attachments/assets/fe856bc2-af0e-4f6d-a1b1-868e8b21a4b7)
> but it's not working with the desktop app of discord, web opens fine tho. (I live in turkey and discord situation is same as russia, as in its also blocked here)

Good, you can close this issue now. Discord problem is other issue.

**Comment by FowlizM** [comment]
So, what should i do about the discord not properly working? It was fine before the last update about a week or two ago

**Comment by EgorWeders** [comment]
Create another issue.

**Comment by FowlizM** [comment]
Fixed that problem as well. Everything works as expected now, thanks to you two for helping <3
