### ISSUE TITLE
как это контрить?

### ISSUE THREAD

**Issue by denrumm1** [ValdikSS/GoodbyeDPI#755]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 11 24H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

![Снимок экрана 2024-12-20 133602](https://github.com/user-attachments/assets/031d4299-7fb9-497b-abc8-6da282fd12db)
как это контрть?

### Additional information / Дополнительная информация

запуская и от имени админстратора и так, не работает, что делать? и хз как описать проблему подробнее, и запускаю везде, 86_64 86 просто цмдшки

**Comment by Nkosinsk** [comment]
есть подозрение что  оба файла в директории 
.\dpi\goodbyedpi-0.2.3rc3-2\x86_64\
у вас ктото/чтото удалило

**Comment by cardikwars** [comment]
Переустанови или снова разархивируй гудбай дипиай, у меня тоже так было вот и решил таким способом

**Comment by Alucard648** [comment]
Такая же проблема. Антивирус Касперского сносит эти файлы, считая их вредоносными.

**Comment by ValdikSS** [comment]
Файлы должны быть в директории, чтобы программа работала.
