### ISSUE TITLE
МГТС Московская область

### ISSUE THREAD

**Issue by roma095** [ValdikSS/GoodbyeDPI#757]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Mikrotik

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

Ютуб открывает только главную страницу и выполняет поиск. Видео перестали воспроизводиться.
Запускаю контейнер с параметрами -o1 -o25+s -T3 -At o--tlsrec 1+s
Что покрутить можно?

### Additional information / Дополнительная информация

Запускаю контейнер с параметрами -o1 -o25+s -T3 -At o--tlsrec 1+s

**Comment by roma095** [comment]
all ok.

**Comment by EgorWeders** [comment]
Закройте тогда issue, если все ок.
