### ISSUE TITLE
Goodbye DPI breaks websites when used in conjunction with Wireguard

### ISSUE THREAD

**Issue by johnsonjamees** [ValdikSS/GoodbyeDPI#761]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

OS: Windows 10 Pro 22H2  OS build: 19045.5131

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

![25-December-2024 @ 10 31 56 AM (msedge)](https://github.com/user-attachments/assets/e3c10ee9-3e77-4377-a2c4-7feee516ddbe)
![25-December-2024 @ 10 32 15 AM (chrome)](https://github.com/user-attachments/assets/5a5f6e19-bfed-4451-a5ea-1883a1a9ed65)

### Additional information / Дополнительная информация

I am running GoodbyeDPI `v0.2.3rc3` on a Windows 10 machine with the default modeset 9. My system also has the official WireGuard client configured with three tunnels:

1. A self-hosted WireGuard server running on a Virtual Private Server (VPS), with the following configuration file:
```
[Interface]
PrivateKey = <redacted>
Address = 10.67.79.2/24
DNS = 10.67.79.1

[Peer]
PublicKey = <redacted>
PresharedKey = <redacted>
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = <redacted>:51820
```
2. Proton VPN, with the following configuration file:
```
[Interface]
PrivateKey = <redacted>
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
PublicKey = <redacted>
AllowedIPs = 0.0.0.0/1, 128.0.0.0/1
Endpoint = <redacted>:51820
````
3. Cloudflare WARP, with the following configuration file:
```
[Interface]
PrivateKey = <redacted>
Address = 172.16.0.2/32, 2606:4700:110:8aea:851f:523d:73a0:ff94/128
DNS = 1.1.1.1, 1.0.0.1, 2606:4700:4700::1111, 2606:4700:4700::1001
MTU = 1280

[Peer]
PublicKey = <redacted>
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = engage.cloudflareclient.com:2408
```

Each of these tunnels exhibits different behavior when GoodbyeDPI is running. Specifically:

1. When using the first tunnel, I encounter errors on websites hosted behind Cloudflare (e.g., [ChatGPT](https://chatgpt.com/), [Claude AI](https://claude.ai/), and [Pluralsight](https://www.pluralsight.com/)). In Chromium-based browsers, I get the error `ERR_SSL_PROTOCOL_ERROR` or `ERR_QUIC_PROTOCOL_ERROR`. Meanwhile, Firefox and its forks return `SSL_ERROR_RX_MALFORMED_SERVER_HELLO`. Other websites not hosted by Cloudflare work fine.

2. When using the Proton VPN tunnel along with GoodbyeDPI, all websites break. While I can use the ping command to ping IP addresses and domain names, attempting to load any website (including Google) results in Firefox-based browsers returning `SSL_ERROR_RX_MALFORMED_SERVER_HELLO` and Chromium-based browsers returning `ERR_QUIC_PROTOCOL_ERROR`.

3. However, the Cloudflare Warp tunnel works without any issues, allowing me to access all websites as expected.

I am confident that the issue lies with GoodbyeDPI and not WireGuard, as disabling GoodbyeDPI resolves all of the strange behavior, and the VPN connections work as expected.

### Environment Details:
```
OS: Windows 10 Pro
Version: 22H2
OS build: 19045.5131
WireGuard App version: 0.5.3
GoodbyeDPI Version: 0.2.3rc3
Command used to launch GoodbyeDPI: "goodbyedpi-0.2.3rc3-2\x86_64\goodbyedpi.exe"** -9  (Note that I am not using any blacklist.)
```

**Comment by EgorWeders** [comment]
-9 can break some sites, try another

Translated text from https://github.com/ValdikSS/GoodbyeDPI/issues/378#issuecomment-2267201431

>  The program does not unblock sites on my provider!
> 
> GoodbyeDPI does not guarantee 100% work with your provider, nor work with every blocked site.
> 
> Option -9, used by default when starting the program, works on most, but not all providers.
> 
> If the program does not work when launched by the script 1_russia_blacklist.cmd, and you get ERR_SSL_PROTOCOL_ERROR, ERR_TIMED_OUT, SSL_ERROR_RX_MALFORMED_SERVER_HELLO, No Internet connection (from YouTube), try the following modes:
> 
> -6 -e1 -q --blacklist …
> -5 -e1 -q --blacklist …
> 
> You need to either manually launch the program with these arguments, or modify the .cmd file (replace -9 with -5 -e1 -q, as an example).

**Comment by johnsonjamees** [comment]
For posterity, the first issue can be solved by running GoodbyeDPI in any modern modeset other than 9. However, if you want to use Proton VPN, you'll need to set it to either 5 or 6.
