### ISSUE TITLE
Добавление сервера battle.net в список заблокированных сайтов

### ISSUE THREAD

**Issue by gnsd26** [ValdikSS/GoodbyeDPI#762]
### I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

- [X] I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал

### Describe your feature / Опишите ваше предложение

Привет, хочу раскладывать потные картишки, но блокировка в Крыму не позволяет мне это делать в игре Heartstone, т.к. battle.net в Крыму пользоваться нельзя из-за санкций. Можно было бы добавить сервесы battle.net в обход, чтоб можно было пользоваться сервисом и играть в игры из этого лаунчера не территории Крыма и Севастополя?

**Comment by EgorWeders** [comment]
Вы это сами можете сделать без помощи автора и пересборки проекта. Много issues где говорится как добавить свои домены в blacklist

**Comment by gnsd26** [comment]
> Вы это сами можете сделать без помощи автора и пересборки проекта. Много issues где говорится как добавить свои домены в blacklist

можешь пример скинуть?
