### ISSUE TITLE
Error opening filter: 1058 The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

### ISSUE THREAD

**Issue by RusBaton** [ValdikSS/GoodbyeDPI#763]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 10 22H2

### Running as service / Запуск программы как сервис

I run it as a regular program / Запускаю программу обычным образом

### Describe the bug / Опишите ошибку программы

пытался скачать zapret для дискорда, немного что-то там сделал, и теперь goodbyedpi не работает. удалил все папки zapret, всё равно так

**Comment by ValdikSS** [comment]
#639
