### ISSUE TITLE
HTTP Redirect

### ISSUE THREAD

**Issue by Daniel978** [ValdikSS/GoodbyeDPI#77]
Привет, я так понял, мой провайдер перенаправляет именно по url, на скрине видно что захожу на сайт, а он перенаправляет меня сразу на мой локальный ип адресс компьютера, и в итоге вылазит object not found, а по ип доступ открыт, GoodByeDPI не помогает, испробовал все режимы, 
![image](https://user-images.githubusercontent.com/39338647/40120433-9ef75a7a-5938-11e8-86ee-ea0581b8d6da.png) Помоги пожалуйста, до этого работало, потом провайдер видимо что то сделал.

**Comment by ValdikSS** [comment]
Пришлите pcap на почту.

**Comment by ValdikSS** [comment]
Нет ответа.
