### ISSUE TITLE
Revert changes

### ISSUE THREAD

**Issue by Alex-302** [ValdikSS/GoodbyeDPI#8]
Не понятно, с чем точно связано, но подозреваю, что после запуска утилиты
<details>

![image](http://imagizer.imageshack.com/img923/6360/qtId47.png)
</details>
перестал гугловый DNS работать.
Можно как-то откатить все изменения?

**Comment by ValdikSS** [comment]
Программа работает только тогда, когда она запущена. Если вы ее закрыли, она перестает работать. Изменений в ОС она не вносит.

**Comment by Alex-302** [comment]
Понял, спасибо.
