### ISSUE TITLE
Adding new website

### ISSUE THREAD

**Issue by fatihbjk90** [ValdikSS/GoodbyeDPI#85]
Can we add new website to blacklist.txt, or is it needed ? Some websites still not working.

**Comment by sergeevabc** [comment]
@ValdikSS, by the way, at the moment [domains-export.txt][1] surprisingly includes 2 domains only (archive.org and lostfilm.tv), why is that?

[1]: https://antizapret.prostovpn.org/

**Comment by ValdikSS** [comment]
@sergeevabc, sourceforge is on maintenance. Changed list URL back to github, updating now.

**Comment by ValdikSS** [comment]
@fatihbjk90, sure, you can add any website you want.

**Comment by sergeevabc** [comment]
@ValdikSS, sorry, but I didn’t get it, where is full https://antizapret.prostovpn.org/domains-export.txt ?

**Comment by ValdikSS** [comment]
@sergeevabc, what do you mean? The link provided contains all blocked domains in Russian Federation.

**Comment by sergeevabc** [comment]
@ValdikSS, it was a cache issue, now I see the full one, thanks.
By the way, I use another approach to update the blacklist (```0_russia_update_blacklist_file.cmd```).

```
@echo off
rem pushd "%~dp0"
rem bitsadmin /transfer blacklist https://antizapret.prostovpn.org/domains-export.txt "%CD%\blacklist.txt"
rem popd

wget -N https://antizapret.prostovpn.org/domains-export.txt -O blacklist.txt
```

**Comment by ValdikSS** [comment]
That would work only on Windows 10 with linux subsystem installed, or with linux utils (cygwin/etc).

**Comment by sergeevabc** [comment]
@ValdikSS, indeed, I use [wget.exe][1] in PATH on Windows 7.

[1]: https://eternallybored.org/misc/wget/
