### ISSUE TITLE
Running "service_install_russia_blacklist.cmd". error "sc" is not a recognized command...

### ISSUE THREAD

**Issue by alvathe1** [ValdikSS/GoodbyeDPI#86]
"sc" is not a recognized command... error flashes on the screen and window closes.
thanks for your help!

**Comment by ValdikSS** [comment]
It should be in the regular Windows installation. I tried to find how to install "sc.exe" if it's missing but found no result. It could be that your Windows installation is broken or you're using some sort of repack with essential features stripped off.

**Comment by catlion** [comment]
It's just `%WINDIR%\System32` is not in `PATH`. Could be some buggy installer or antivirus software messed it up.

@alvathe1 https://superuser.com/a/284351/3374

**Comment by Atavic** [comment]
As catlion above says, *path* should go to the folder containing *cmd.exe* as sc command is run into it. There's no *sc.exe*

**Comment by catlion** [comment]
@Atavic:
```PowerShell
Get-Command sc.exe

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     sc.exe                                             10.0.17... C:\Windows\system32\sc.exe
```
Not sure, maybe I have one after installing [Windows SDK](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682053(v=vs.85).aspx).

**Comment by Atavic** [comment]
I was wrong, sc.exe is present on windows xp sp3

**Comment by ValdikSS** [comment]
@alvathe1, do you use proper Windows installation (not a third-party repack)? I believe sc.exe should be included in every Windows edition unless stripped or removed.

**Comment by Atavic** [comment]
You can try something like wget: https://github.com/ValdikSS/GoodbyeDPI/issues/85#issuecomment-393811666

**Comment by ValdikSS** [comment]
@Atavic wget is file downloader, not a service manipulation software.

**Comment by Atavic** [comment]
sorry for that.

**Comment by Atavic** [comment]
My fault, sorry.

**Comment by ValdikSS** [comment]
Closing due to lack of reply.
