### ISSUE TITLE
GoodbyeDPI and Windows 10 Mobile (ARM)

### ISSUE THREAD

**Issue by AlexGenP1** [ValdikSS/GoodbyeDPI#87]
Здравствуйте!
Есть ли возможность запустить GoodbyeDPI на разблокированном устройстве
с Windows 10 Mobile (ARM)?

**Comment by ValdikSS** [comment]
Что у вас за устройство? Как именно оно разблокировано?

**Comment by AlexGenP1** [comment]
MICROSOFT Lumia 640 LTE, доступ к SSH и SFTP, cmd, reg.

**Comment by ValdikSS** [comment]
А, Mobile. Нет, вероятно, нельзя.

**Comment by AlexGenP1** [comment]
Через пакет разработчика получится конвертировать или не стоит заморачиваться?

**Comment by ValdikSS** [comment]
На Windows Mobile есть вообще какие-либо сторонние драйверы?

**Comment by AlexGenP1** [comment]
Вроде бы в пакете есть x86->ARM32, точно не скажу.

**Comment by AlexGenP1** [comment]
Только Desktop и только в ARM64, жаль...
