### ISSUE TITLE
This doesn't work in Turkey anymore

### ISSUE THREAD

**Issue by Bloomfear** [ValdikSS/GoodbyeDPI#89]
Thank you for this great little software. It was wonderful while working but somehow they figured out a way to block this. Sadly it doesn't work anymore in Turkey. Instead of going to the blocked site, it started to direct to the "this site is banned" page again.

**Comment by satnatantas** [comment]
You should at least try using HTTPS.

**Comment by Bloomfear** [comment]
What do you mean by using HTTPS? Neither **https**://www.wikipedia.org/ nor **http**://www.wikipedia.org/ works any more.

**Comment by satnatantas** [comment]
Thing is, if you are using HTTPS, you cannot get redirects - unless site itself sends them or you have a forged root certificate.

**Comment by satnatantas** [comment]
Worst you can get with HTTPS is connection timeout or TLS failure - if DPI of provider is bad enough for that.

**Comment by Bloomfear** [comment]
Update: Some sites work with **2_all_dnsredir.cmd** which uses the Yandex dns address, unfortunately others don't.  It turned out to be DNS spoofing. I'm closing this issue for now.

**Comment by satnatantas** [comment]
I'm assuming that you ruled out root certificate forgery and that those HTTPS sites which do not work are giving either timeout or TLS failure.
