### ISSUE TITLE
Как на счёт версии, хотя бы для Ubuntu?

### ISSUE THREAD

**Issue by GoodGuyNick** [ValdikSS/GoodbyeDPI#9]
Собирать из исходников мало кому хочется, особенно тому, кто не разбирается в сборке с исходников или имеет малый опыт. Как вариант можно завернуть во Flatpack или в Snap, для использования на большинстве дистрибутивов.

**Comment by ValdikSS** [comment]
Программа работает только под Windows, использует слои файрволла Windows и драйвер Windows.
