### ISSUE TITLE
Accessing non-banned subdomain of banned domain kickstarts the connection

### ISSUE THREAD

**Issue by satnatantas** [ValdikSS/GoodbyeDPI#90]
https://8ch.net is banned and I cannot access it with any mode in GDPI (blacklist included), connection timeout being the reason.
When GDPI is not running, the reason is TLS handshake fail.
However, when I access https://sys.8ch.net with or **without** GDPI running I get access to 8ch.net for like twenty minutes or something even if I stop GDPI right after getting access. <del>If I access that subdomain without GDPI running, nothing changes.</del>

Reproducible 100% of times on my machine. Never had a single issue with any other blacklisted site. Never had an issue with 8ch.net on same machine when I go to place with Rostelecom.
W7x64SP1, Megafon, 1.5.0.rc1

How do I find out the reason? Could it be some sort of server-side issue?

**Comment by ValdikSS** [comment]
Both `8ch.net` and `sys.8ch.net` have the same set of IP addresses and the same HTTPS certificate. I suppose your browser is smart and re-uses existing TLS (HTTPS) connection to `sys.8ch.net` to access `8ch.net` resources for a long period of time.
Please provide wireshark dump to be sure:
https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark

**Comment by satnatantas** [comment]
[Documents.zip](https://github.com/ValdikSS/GoodbyeDPI/files/2144414/Documents.zip)

**Comment by satnatantas** [comment]
Interesting detail is that same phenomena is happening with Samsung Wave.
Also that accessing subdomain from Wave does not kickstart connection.
The only logical conclusion is that it's a super-rare router bug.

**Comment by ValdikSS** [comment]
Yes, your browser establishes 1 connection and uses it for both `sys.8ch.net` and `8ch.net`.\

>but it happens much later with GDPI.

That is because GoodbyeDPI discards injected RST packets.

**Comment by satnatantas** [comment]
So, any way to fix it? :D

**Comment by satnatantas** [comment]
I also forgot to check other sites after I moved to different provider. Other sites are not accessible as well, so...

**Comment by ValdikSS** [comment]
Seems like GoodbyeDPI doesn't work with your ISP. DPI bypass could be implemented once the proxy mode is implemented.

**Comment by satnatantas** [comment]
@ValdikSS could you please hint at what layer of abstraction makes it possible to reuse connection even when connecting to a different domain? Wget fails at that when I use `wget -r `, throws a GNUTLS error.

**Comment by ValdikSS** [comment]
@satnatantas I'm not sure if it's possible to reuse connections in a wget or curl like this. Curl seems to not support this feature, just as Firefox. What browser do you use?

Basically, you need to connect once and re-use this connection manually. You can do the following with curl:
`curl https://sys.8ch.net -H "Host: 8ch.net"`
It will send TLS ClientHello with "sys.8ch.net", but a HTTP request will contain `Host: 8ch.net`.

Could you also try changing case in SNI and post the results?
`openssl s_client -servername 8ch.nEt -connect 104.20.43.57:443`

**Comment by TechnikEmpire** [comment]
Any other details about this proposed proxy solution to DPI evasion? It blows my mind that this is such a pervasive problem.

**Comment by ValdikSS** [comment]
@TechnikEmpire Stripping SNI, chaning case in SNI value.

**Comment by TechnikEmpire** [comment]
@ValdikSS Ah I see. Proxying is a lot of heavy lifting for just that though.

**Comment by ValdikSS** [comment]
@TechnikEmpire well, technically that would be TLS-only modification/reencryption proxy. You can't modify TLS packets without re-encryption since that would break packets integrity.

**Comment by TechnikEmpire** [comment]
@ValdikSS Oh I know all about the pains of intercepting and modifying SSL/TLS. :)
