### ISSUE TITLE
Блокирует запросы к корпоративному DNS при VPN подключении

### ISSUE THREAD

**Issue by Shedon** [ValdikSS/GoodbyeDPI#92]
При подключении к корпоративной сети через CISCO AnnyConnect Client, не работают ресурсы корпоративной сети, т.к. goodbydpi блокирует все запросы к внутреннему DNS серверу.

**Comment by ValdikSS** [comment]
GoodbyeDPI не блокирует DNS-запросы, если вы вручную не пропишите сторонний DNS-сервер.

**Comment by catlion** [comment]
От себя добавлю, что VPN с AnyConnect у меня работает.

**Comment by Shedon** [comment]
> GoodbyeDPI не блокирует DNS-запросы, если вы вручную не пропишите сторонний DNS-сервер.
Не очень понял, AnnyConnect прописывает внутренний DNS сервер и суффикс в настройки адаптера после установки подключения.

**Comment by ValdikSS** [comment]
@Shedon GoodbyeDPI взаимодействует с DNS только в том случае, если вы указываете параметр `--dns-addr` или `--dnsv6-addr`. Только в этом случае он перенаправляет запросы на указанные в параметрах адреса. По умолчанию GoodbyeDPI не трогает DNS.
