### ISSUE TITLE
qBittorrent blocked

### ISSUE THREAD

**Issue by Shedon** [ValdikSS/GoodbyeDPI#93]
При включенном goodbydpi, qBittorrent при добавлении новых закачек уходит в состояние "простаивает" и ничего не качается

**Comment by ValdikSS** [comment]
Вы тестировали только на одном трекере? Если так, то проблема в несоответствии стандарту HTTP веб-сервера анонсера, а не в GoodbyeDPI.

**Comment by ValdikSS** [comment]
Какой анонсер так себя ведет, напомните. Кинозал?

**Comment by Shedon** [comment]
lostfilm.tv
конкретно на этой раздаче воспроизводится lostfilm.tv/series/Preacher/season_3/episode_4

**Comment by ValdikSS** [comment]
Веб-сервер анонсера несовместим с опцией `-s`.
Запускайте GoodbyeDPI без опции `-s`, например, так:
`goodbyedpi.exe -p -r -f 2 -k 2 -n -e 2`

**Comment by celomu** [comment]
а как быть если ни один трекер не пробивает? прописать все свои трекеры в список? глядишь пробьет
