### ISSUE TITLE
Простите, нужна помощь!

### ISSUE THREAD

**Issue by liveonloan** [ValdikSS/GoodbyeDPI#94]
Здравствуйте!
Не знаю сюда ли я обращаюсь с просьбой о помощи...
Проблема в следующем:
Список blacklist.txt обновлен сегодня, GoodbyeDPI v0.1.5rc2, провайдер Ростелеком.
НЕДОСТУПНЫ:
Сайт StarCraft 2:
starcraft2.com (34.241.188.84)
Сервер с картинками для вов-армори и форумных аватарок:
render-eu.worldofwarcraft.com (34.250.105.135)
Сайт Hearthstone:
playhearthstone.com (34.242.62.226)
Сайт Heroes of the Storm:
heroesofthestorm.com (34.251.161.255)
Главный сайт Blizzard (работает через раз):
blizzard.com (34.253.163.21)
Форумы Overwatch:
eu.forums.blizzard.com (34.247.239.226)
Подробнее ситуация описана тут: https://waa.ai/afd1

http://blocklist.rkn.gov.ru/ показала что все эти IP (следовательно сайты) заблокированы решением суда.
В списке blacklist.txt нет ни одного из перечисленных выше сайтов.

P.S.
Простите что написал сюда, просто не знаю куда можно обратиться с данной проблемой.
Спасибо.

**Comment by ValdikSS** [comment]
Эти сайты заблокированы по диапазонам адресов:
```
34.240.0.0/13
34.248.0.0/13
```
GoodbyeDPI не способен обходить блокировку по IP. Используйте ReQrypt или VPN антизапрета, или любой другой.

**Comment by liveonloan** [comment]
Спасибо большое за объяснение! По простоте душевной думал если вы добавите starcraft2.com в blacklist.txt - то все заработает :) А тут все гораздо сложнее.
Удачи вашему проекту.
