### ISSUE TITLE
CMD & AdminRightCheck

### ISSUE THREAD

**Issue by iDolmatov** [ValdikSS/GoodbyeDPI#99]
I think, need add autocheck.

Windows XP and later
```
@echo off

call :isAdmin
if %errorlevel% == 0 (
echo Running with admin rights.
) else (
echo Error: Access denied.
)

pause >nul
exit /b

:isAdmin
fsutil dirty query %systemdrive% >nul
exit /b
```
Windows 2000 / Windows PE
```
@echo off

call :isAdmin
if %errorlevel% == 0 (
echo Running with admin rights.
) else (
echo Error: Access denied.
)

pause >nul
exit /b

:isAdmin
sfc 2>&1 | find /i "/SCANNOW" >nul
exit /b
```
Applies to
Windows 2000
Windows XP
Windows Vista
Windows 7
Windows 8
Windows 8.1 
--- 
Windows PE

https://stackoverflow.com/questions/4051883/batch-script-how-to-check-for-admin-rights#21295806

**Comment by iDolmatov** [comment]
May be work all win 10. I don't check metod.

**Comment by AHOHNMYC** [comment]
```
@echo off
>NUL 2>&1 REG.exe query "HKU\S-1-5-19" || (
    ECHO SET UAC = CreateObject^("Shell.Application"^) > "%TEMP%\Getadmin.vbs"
    ECHO UAC.ShellExecute "%~f0", "%1", "", "runas", 1 >> "%TEMP%\Getadmin.vbs"
    "%TEMP%\Getadmin.vbs"
    DEL /f /q "%TEMP%\Getadmin.vbs" 2>NUL
    Exit /b
)
```
The most elegant way to start `*.cmd` with High integrity level.
(I hope authors of `Stop_ABBYY_Server.cmd` from `crack` folder will not be upset if we use their code)

**Comment by DeenOConnor** [comment]
You can try creating a file somewhere in C:\Windows folder. It's a stone age admin rights check, but works for most users.

**Comment by ValdikSS** [comment]
The exe file has requireAdmin manifest for quite a long time.
